### ISSUE TITLE
rtl8821ae slows down and stalls

### ISSUE THREAD

**Issue by owuor** [lwfinger/rtlwifi_new#103]
Hallos, 

I am new to wifi troubleshooting. I took an rtl8821ae chip from a router that I have seen doing more than 9MB/s (on a large scp) at close range with Wireless N. However when I plug it into ubuntu with the latest rltwifi-new drivers, the most I can get is 2MB/s, which drops to about 50KB after about 30 seconds. At times, scp stalls. This happens both with stock ubuntu (trusty tahr) and with updated drivers as well. I have given details below. What could be the problem or how could I troubleshoot further? Are there rtl8821ae chips that deliver good throughput with this driver with Wireless N?

Thanks.

iwconfig
wlan4     IEEE 802.11abgn  ESSID:"ThisNet"  
          Mode:Managed  Frequency:2.412 GHz  Access Point: 1C:49:7B:2A:00:F4  
          Bit Rate=130 Mb/s   Tx-Power=20 dBm  
          Retry short limit:7   RTS thr=2347 B   Fragment thr:off
          Encryption key:off
          Power Management:off
          Link Quality=70/70  Signal level=-34 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

lspci
0c:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8812AE 802.11ac PCIe Wireless Network Adapter (rev 01)
    Subsystem: Realtek Semiconductor Co., Ltd. RTL8812AE 802.11ac PCIe Wireless Network Adapter
    Flags: bus master, fast devsel, latency 0, IRQ 47
    I/O ports at de00 [size=256]
    Memory at f69fc000 (64-bit, non-prefetchable) [size=16K]
    Capabilities: [40] Power Management version 3
    Capabilities: [50] MSI: Enable+ Count=1/1 Maskable- 64bit+
    Capabilities: [70] Express Endpoint, MSI 00
    Capabilities: [100] Advanced Error Reporting
    Capabilities: [140] Device Serial Number 00-12-88-fe-ff-4c-e0-00
    Capabilities: [150] Latency Tolerance Reporting
    Capabilities: [158] L1 PM Substates
    Kernel driver in use: rtl8821ae

**Comment by lwfinger** [comment]
There are very few RTL8723AE devices in use. In fact, there are so few that very little testing has been done. The first thing to try is setting the module option "ips=0". Not many of the Realtek drivers handle power save very well. In particular, the RTL8723BE does not, which makes me suspect the AE version.

If that does not help, then you will need to determine whether the slowdown is triggered by an error in the rate-control code, or a bug in the gain-setting routines. Unfortunately, there are very few aids for this kind of targeted debugging.

**Comment by jashandeep-sohi** [comment]
@owuor I was having similar problems w/ the stock rtl8821ae driver included in the 4.4.5 kernel. I tried disabling features (i.e. `ips=0`, swenc=1`, etc), but unfortunately it had no effect on the performance or the stalling.

I'm able to get better performance now using `rtl8821ae_dkms` compiled from master. I still get the occasional stall (much more infrequent), but I am able to get better speeds. Are you sure you're using the latest drivers?

**Comment by owuor** [comment]
Thanks @jashandeep-sohi, I've been working on this with not much improvement. How does one get the _dkms from the driver?

**Comment by owuor** [comment]
Is it true that the chip is a softAP device... That the AP system is not implemented in hardware? Why are there so few devices built with it?

**Comment by lwfinger** [comment]
There are NO devices with the AP software built into hardware. If you look carefully at nearly all router/AP devices, they are running some form of Linux and hostapd. That is why the standard firmware can be exchanged for openWRT and similar packages.

The choice of devices upon which to base an AP is largely dependent on cost. Only wifi devices built into SOC chips are usually considered. Building such a router by starting with a PCIe device would be prohibitively expensive.

**Comment by owuor** [comment]
Thanks for the advice.
However, I have a ralink USB device (RT2870) which has very low CPU overhead. Less than 5% on a 1.4Ghz processor when doing a 2MB/s scp. However my rtl8812ae takes about 50% overhead. This is with an older (3.1x) kernel. I had assumed that the USB device had AP implemented in hardware, or what can explain that discrepancy...?

**Comment by owuor** [comment]
The ralink USB device id is: 148f:3070. It's just markes 802.11n wifi dongle. It's a very old device - so I wonder how it is able to outperform a more recent device.

**Comment by lwfinger** [comment]
We welcome any patches to improve the driver.

**Comment by owuor** [comment]
Give me a few leads on how to debug these things and I'll promise you a patch or two. At the moment, I don't know where to start. Please share any documentation available, especially regarding 8812ae chip

**Comment by jashandeep-sohi** [comment]
@owuor It's just one of the modules provided by this repo (using the latest commit). I'm using Arch Linux & the package renames the modules to `xxxx_dkms` to avoid conflict with the stock. I'm not sure how Ubuntu does it, though. Are you building the modules from git?

**Comment by owuor** [comment]
Thanks,Yes,  I did build them,  but after porting to a 4.4.4 kernel. I
think running 'make' in Ubuntu simply creates the .ko modules.

**Comment by lwfinger** [comment]
That is what make is supposed to do. 

I have no knowledge of the internals of the RTL8821AE chip. The only documentation I have is what is contained in the driver. If I knew how to make this driver faster, I would do so.

The router that was using the RTL8821AE chip was likely using a different driver than is in the kernel and this repo. Those drivers have a lot of code in common with the Windows drivers. If that is the case here, it is in a form that is totally unacceptable for inclusion in Linux.

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
