### ISSUE TITLE
Lenovo T440s RTL8192EE PCIe Wireless Network Adapter

### ISSUE THREAD

**Issue by JS52766** [lwfinger/rtlwifi_new#105]
Hi

Im fairly new to Kali Linux but im an experience IT Tech.

Iv installed Kali Linux on my Lenovo T440s side by side with WIndows 10

In Kali i get an internet connection when connecting to the LAN but am unable to connect to any WIFI

Sometimes the WIFI SSID's are listed and sometimes they are not. If i select my home SSID it allows me to enter the encrption key but never connects. Iv even remove all passwords and it still will not connect.

The only thing i can think of is that its the wireless card/driver/firmware

Can anyone help me?

Thanks
Jason

**Comment by lwfinger** [comment]
It is possible that your vendor has only installed one antenna and connected it to a different connector than is programmed in the EEPROM. If so, this will be the first instance of this problem with an RTL8192EE. It is quite common on HP laptops with RTL8723BE cards.

To test this case, run the command "sudo iw dev wlan0 scan | grep signal" and post the output. Replace wlan0 with the actual name of your wireless device.

**Comment by dylanfprice** [comment]
I have a Lenovo T440 (not the T440s) but it has the same RTL8192EE PCIe Wireless Network Adapter.
>Sometimes the WIFI SSID's are listed and sometimes they are not. If i select my home SSID it allows me to enter the encrption key but never connects. Iv even remove all passwords and it still will not connect.

Seeing similar behavior in Ubuntu 16.04.

Right now I can't even get the wlan0 interface up so that command you suggested won't be very useful ("command failed: Network is down"). I see messages like this in syslog:
```
Apr 22 11:41:48 dylan-esv wpa_supplicant[1207]: wlan0: Failed to initialize driver interface
Apr 22 11:41:48 dylan-esv kernel: [ 9650.529185] rtl8192ee:rtl92ee_hw_init():<0-0> Init MAC failed
Apr 22 11:41:48 dylan-esv NetworkManager[906]: <error> [1461350508.4916] sup-iface[0x22a8400,wlan0]: error adding interface: wpa_supplicant couldn't grab this interface.
```

Right now I am running with drivers built from the troy branch of this repo, as I have seen it referenced in other issues for this chipset. But I don't see any difference compared to the stock drivers that came with my installation of Ubuntu.

**Comment by lwfinger** [comment]
For the RTL8192EE, there should not be any difference between the standard kernel driver and any branch of this repo, as long as the kernel is recently new. As an aside, I wish people would state their kernel version. I am not an Ubuntu user, and I have no desire to waste my time trying to determine what kernel version is used with any version of their distro. The same applies to any distro!

I have no idea why you are getting that failure of the MAC initialization as long as the firmware is available.

**Comment by dylanfprice** [comment]
Fair point.
```
release: 4.4.0-21-generic
version: #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016
arch: x86_64
```

Just grasping at straws here since I've tried a lot of things and most of the info from google searches is out of date wrt my kernel. Saw this more recent issue and figured I'd throw in my +1. I will probably just buy a wifi dongle and be done with it.

**Comment by vectorliu** [comment]
Same happens with my thinkpad x240 with the RTL8192EE. The wifi will be ok for a while after a reinstall and reboot. However, after that it went down and was unable to work. The same issue has been with me for a few months and have tried all the methods in the google search results.
`Linux *******-ThinkPad-X240 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
`
Kind of think this is a common issue with RTL8192EE. Never saw a stable version.

**Comment by gpstuff** [comment]
Same problem of vectorliu on a thinkpad x240, wifi is ok on reboot but after some minutes it lose the connection and can't detect any wifi network.
Couldn't run "sudo iw dev wlan0 scan | grep signal" as suggested because the network is down but there is no way to bring it up.
I'm running debian testing:
```
Linux gplap 4.5.0-2-amd64 #1 SMP Debian 4.5.3-2 (2016-05-08) x86_64 GNU/Linux
firmware-realtek                      20160110-1
```

This is from /var/log/messages if I try to turn off and back on the wifi with the function key:
```
ay 19 17:32:11 gplap NetworkManager[882]: <info>  [1463671931.9024] manager: WiFi now disabled by radio killswitch
May 19 17:32:11 gplap NetworkManager[882]: <info>  [1463671931.9025] device (wlp3s0): state change: disconnected -> unavailable (reason 'none') [30 20 0]
May 19 17:32:12 gplap NetworkManager[882]: <info>  [1463671932.7434] manager: WiFi now enabled by radio killswitch
May 19 17:32:12 gplap NetworkManager[882]: <warn>  [1463671932.8134] device (wlp3s0): device not up after timeout!
```
/var/log/messages during "modprobe -r rtl8192ee; modprobe rtl8192ee"
```
May 19 17:34:47 gplap NetworkManager[882]: <info>  [1463672087.6610] device (wlp3s0): state change: unavailable -> unmanaged (reason 'removed') [20 10 36]
May 19 17:34:47 gplap NetworkManager[882]: <warn>  [1463672087.6620] device (wlp3s0): failed to disable userspace IPv6LL address handling
May 19 17:34:47 gplap NetworkManager[882]: <info>  [1463672087.6648] devices removed (path: /sys/devices/pci0000:00/0000:00:1c.1/0000:03:00.0/net/wlp3s0, iface: wlp3s0)
May 19 17:34:47 gplap NetworkManager[882]: <info>  [1463672087.6736] radio killswitch /sys/devices/pci0000:00/0000:00:1c.1/0000:03:00.0/ieee80211/phy0/rfkill2 disappeared
May 19 17:34:54 gplap kernel: [ 1621.720228] rtl8192ee 0000:03:00.0: Refused to change power state, currently in D3
May 19 17:34:54 gplap kernel: [ 1621.720367] rtl8192ee: Using firmware rtlwifi/rtl8192eefw.bin
May 19 17:34:54 gplap kernel: [ 1621.721709] rtlwifi: rtlwifi: wireless switch is on
May 19 17:34:54 gplap kernel: [ 1621.722063] rtl8192ee 0000:03:00.0: firmware: direct-loading firmware rtlwifi/rtl8192eefw.bin
May 19 17:34:54 gplap NetworkManager[882]: <info>  [1463672094.6345] (wlan0): using nl80211 for WiFi device control
May 19 17:34:54 gplap NetworkManager[882]: <info>  [1463672094.6346] device (wlan0): driver supports Access Point (AP) mode
May 19 17:34:54 gplap NetworkManager[882]: <info>  [1463672094.6359] manager: (wlan0): new 802.11 WiFi device (/org/freedesktop/NetworkManager/Devices/4)
May 19 17:34:54 gplap NetworkManager[882]: <info>  [1463672094.6380] rfkill3: found WiFi radio killswitch (at /sys/devices/pci0000:00/0000:00:1c.1/0000:03:00.0/ieee80211/phy0/rfkill3) (driver rtl8192ee)
May 19 17:34:54 gplap kernel: [ 1621.779503] rtl8192ee 0000:03:00.0 wlp3s0f0: renamed from wlan0
May 19 17:34:54 gplap NetworkManager[882]: <info>  [1463672094.7049] device (wlan0): interface index 5 renamed iface from 'wlan0' to 'wlp3s0f0'
May 19 17:34:54 gplap NetworkManager[882]: <info>  [1463672094.7085] devices added (path: /sys/devices/pci0000:00/0000:00:1c.1/0000:03:00.0/net/wlp3s0f0, iface: wlp3s0f0)
May 19 17:34:54 gplap NetworkManager[882]: <info>  [1463672094.7085] device added (path: /sys/devices/pci0000:00/0000:00:1c.1/0000:03:00.0/net/wlp3s0f0, iface: wlp3s0f0): no ifupdown configuration found.
May 19 17:34:54 gplap NetworkManager[882]: <info>  [1463672094.7086] device (wlp3s0f0): state change: unmanaged -> unavailable (reason 'managed') [10 20 2]
May 19 17:34:54 gplap kernel: [ 1621.796512] IPv6: ADDRCONF(NETDEV_UP): wlp3s0f0: link is not ready
May 19 17:34:54 gplap NetworkManager[882]: <warn>  [1463672094.7791] device (wlp3s0f0): device not up after timeout!
May 19 17:34:54 gplap NetworkManager[882]: <info>  [1463672094.9021] device (wlp3s0f0): supplicant interface state: starting -> down
May 19 17:35:04 gplap NetworkManager[882]: <warn>  [1463672104.9257] device (wlp3s0f0): re-acquiring supplicant interface (#1).
May 19 17:35:05 gplap NetworkManager[882]: <info>  [1463672105.0473] device (wlp3s0f0): supplicant interface state: starting -> down
May 19 17:35:14 gplap NetworkManager[882]: <warn>  [1463672114.9313] device (wlp3s0f0): re-acquiring supplicant interface (#2).
May 19 17:35:15 gplap NetworkManager[882]: <info>  [1463672115.0533] device (wlp3s0f0): supplicant interface state: starting -> down
May 19 17:35:24 gplap NetworkManager[882]: <warn>  [1463672124.9314] device (wlp3s0f0): re-acquiring supplicant interface (#3).
May 19 17:35:25 gplap NetworkManager[882]: <info>  [1463672125.0531] device (wlp3s0f0): supplicant interface state: starting -> down
May 19 17:35:34 gplap NetworkManager[882]: <warn>  [1463672134.9293] device (wlp3s0f0): re-acquiring supplicant interface (#4).
May 19 17:35:35 gplap NetworkManager[882]: <info>  [1463672135.0520] device (wlp3s0f0): supplicant interface state: starting -> down
May 19 17:35:44 gplap NetworkManager[882]: <warn>  [1463672144.9286] device (wlp3s0f0): re-acquiring supplicant interface (#5).
May 19 17:35:45 gplap NetworkManager[882]: <info>  [1463672145.0509] device (wlp3s0f0): supplicant interface state: starting -> down
May 19 17:35:45 gplap NetworkManager[882]: <info>  [1463672145.0510] device (wlp3s0f0): supplicant interface keeps failing, giving up
```
iwconfig:
```
wlp3s0    IEEE 802.11bgn  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=20 dBm   
          Retry short limit:7   RTS thr=2347 B   Fragment thr:off
          Encryption key:off
          Power Management:off
```

**Comment by cpacchierotti** [comment]
I am having the same issue on a Thinkpad x240. Kernel 4.4.0-24-generic on Ubuntu 16.04.

**Comment by jefferymiller** [comment]
The 4.4 kernel does not have the rtl8188ee code needed for a reasonable connection in my tests. I have been testing with a mostly vanilla 4.4.14 kernel . Make sure to try the master branch of this repo.

**Comment by jefferymiller** [comment]
I apologize. I for some reason thought this was a rtl8188ee thread.

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
