### ISSUE TITLE
[Solved: remove Windows fastboot] Working config for HP 250 G4: ant_sel=2 but ips=1 

### ISSUE THREAD

**Issue by laugeo** [lwfinger/rtlwifi_new#108]
hi,

The correct setting for  this HP recent computer is  ant_sel=2 (because it was affected
by the antenna bug) but unlike often seen in forums, **ips must be 1** (default value) , and not disabled .
 ips=0 make long delay when pinging router and slow internet browsing.
(note: fwlps is also set to 1 , default value) 
Thanks for the driver,

Laurent

**Comment by pressure679** [comment]
wifi card rtl8191seva (driver rtl8192se) got that issue aswell. Guide for others:
do the following command in terminal:

echo "options rtl8192se ant_sel=2" | sudo tee /etc/modprobe.d/rtl8192se.conf"

and reboot.

**Comment by pressure679** [comment]
It seems like wifi card rtl8192seva (driver rtl8192se) has same issue. The connection is somewhat stable, but it drops when starting to load a movie and reconnects with a stable connection ~20 sec's after.
Solution:

echo "options rtl8192se ant_sel=2" | sudo tee /etc/modprobe.d/rtl8192se.conf

and reboot.

**Comment by lwfinger** [comment]
Very interesting as the rtl8192se driver has no idea what to do with the ant_sel option, thus it ignores it. Check your dmesg output.

**Comment by pressure679** [comment]
Yeah you are probably right. Weird thing is; the connection is stable when computer is idling. When I am e.g writing the connection drops every ~30 sec. I will open an independent issue with rtl8192se.

**Comment by laugeo** [comment]
Problem was finally fixed by disabling "fastboot " in windows 10  energy setting .
This was confirmed by Maximiliano  in another thread .

**Comment by lwfinger** [comment]
As I never boot Windows of any form except for Virtual Machines, I have not encountered this problem. Of course, "fast boot" is essentially hibernation, and it will leave the hardware in a strange state.

**Comment by pressure679** [comment]
Nice to know - except my specific issue was my ISP used a DNS with DHCP so I could not set up a static DNS - and LAN was not an option.

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
