### ISSUE TITLE
A few thoughts on the driver

### ISSUE THREAD

**Issue by nikolaandj** [lwfinger/rtlwifi_new#109]
Here are a few things I have noticed while using this driver on HP Probook 455 G2 on Fedora 23 and openSUSE Leap 42.1.

First of all, this driver on GNOME just works! When I add the parameters in modprobe (`msi=1`) it starts working flawlessly.

Second of all, on KDE it works ... sometimes ... kind of. Let me explain. The latest commit (45a5e3822f22b7e3e85a7f11162fb268416d42bf) did NOT work. It wouldn't even modprobe saying that the exec was wrong. The commit b12da7c4b5b2684e4d3d74cffa4967078bef34c1 is the "best" one I have used on KDE. It would modprobe on boot everytime, but would connect about 60% - 70% of the time. The times it would not connect it would get stuck on "Configuring interface" message for about 30 seconds to a minute, than it would drop and try to reconnect. The only way to get it working at this point would be to reboot the laptop. Sadly, I had to switch back to GNOME since I need wi-fi for work, thus I am not able to provide you with logs.

Finally, the 4.4.6 kernel default one will still not work. It would always act as b12da7c4b5b2684e4d3d74cffa4967078bef34c1 on KDE would regardless of the DE. I haven't encountered a kernel driver that would work, yet. Also it would drop connections and would not connect again.

That is all I have noticed. Hope it helps!

**Comment by lwfinger** [comment]
A few more tho9ughts are as follows: If the driver loads correctly with the modprobe command, AND you are using this repo as the source of your driver, then any differences between KDE and Gnome desktops are a problem in the user space components. The kernel code is identical. Are you sure that the two desktops are using exactly the same method to connect. That might be wicd, wicked, or NetworkManager. If the latter, the controlling applet is likely different.

All my tests are done with KDE, and most with NetworkManager. Thus I know the driver works with that combination using openSUSE 13.2.

Most users find that the option "ips=0" improves the stability. Power save in the driver does not work very well. It does depend on the firmware in the connected AP.

When a module is loaded, the new code will be allowed to run with very few checks. Thus it has the possibility of interfering with the work of the kernel and it could crash the system. Think of the Blue Screen of Death in Windows. To reduce the failures, the kernel ensures that the new driver is using exactly the same set of definitions for the kernel's data structures. These are defined in the kernel headers. In addition, the loader code also checks that the same version of the compiler is used. A different version might change the layout of these critical data structures. If commit 45a5e38 fails to load, it means that you have violated one of the two requirements.

**Comment by nikolaandj** [comment]
I agree that the DE problem might be in the userspace. I was using the 
NetworkManager service to be exact. I brought this point up to help any 
users that might have these issues. I don't know which service is the 
default for GNOME, but in either case it was the default one. I might 
add that on the GNOME DE the connection process starts in the GDM in 
case I have connected the AP prior, whilst on KDE the process starts 
the moment I log in.

One thing slipped by me on the first comment. On KDE, on both distros I 
could not connect to any AP after I successfully connected and then 
disconnected. Once again it might be due to some KDE specific NM thing.

I haven't tried the `ips` option. I will try it when I switch over to 
KDE next time.

And finally, personally I have no idea why the module failed to load. I 
tried recompiling it twice, and the modprobe failed both times. The 
funny thing is, that on GNOME on the SAME EXACT kenel version (albeit 
after a reinstall) the modprobe was successful. After the failed 
modprobes, i recompiled the working commit and I continued using the 
older version, until the reinstall.

Personally, I think that there is no reason to keep this issue open. I 
just wanted to point out my observations, just in case it could  you or 
someone having these issues.

Take care :)

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
