### ISSUE TITLE
rtl8723be does not show password protected networks Fedora 23.

### ISSUE THREAD

**Issue by Sanjayjeyavel** [lwfinger/rtlwifi_new#110]
Hi.I am new to linux.The rtl8723be driver is installed but doesnt show any networks.
My kernel version is 4.2.3

please help...

**Comment by liningRS** [comment]
did you load it?use the order:

sudo modprobe -r rtl8723be

sudo modprobe rtl8723be

if it does not work,try restart your computer.

________________________________
发件人: Sanjayjeyavel <notifications@github.com>
发送时间: 2016年4月5日 18:10:46
收件人: lwfinger/rtlwifi_new
主题: [lwfinger/rtlwifi_new] rtl8723be does not show any networks Fedora 23. (#110)


Hi.I am new to linux.The rtl8723be driver is installed but doesnt show any networks.
My kernel version is 4.2.3

please help...

―

**Comment by Sanjayjeyavel** [comment]
I tried doing it but it doesnt work.And i cant seem to reinstall the drivers the make command shows no targets found..

**Comment by Sanjayjeyavel** [comment]
Hi!! Now my wifi driver is showing open networks but no password protected ones.
please help..

**Comment by lwfinger** [comment]
The steps needed to "show" a network are all done without encryption, thus I do not understand your statement unless your password-protected networks are also hidden. In that case, you will need to use the procedures specific to your distro to connect to them.

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
