### ISSUE TITLE
Exec format error

### ISSUE THREAD

**Issue by georgerock** [lwfinger/rtlwifi_new#111]
Hi, I'm having this problem after make compilation ran successfully : 
"modprobe : Error : could not insert rtl8723be Exec format error"
I'm running Fedora 23 4.4.6-300.fc23.x86_64

I've searched everywhere and seems to be a dead end so please help me! I'd be much obliged.

**Comment by lwfinger** [comment]
Did you look at the output of the dmesg command for the specific error? Errors in loading a module with modprobe are usually due to using the wrong kernel headers when building the driver.

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
