### ISSUE TITLE
Kernel 3.13, 3.16, 4.2, rtl8192se driver with rtl8191seva card unstable

### ISSUE THREAD

**Issue by pressure679** [lwfinger/rtlwifi_new#112]
The connection is stable when computer is idling. When I am e.g writing the connection drops every ~30 sec.

**Comment by lwfinger** [comment]
Have you tried any of the options? Changing ips would be a good start.

**Comment by pressure679** [comment]
Yeah you are on to something, it is solved now.
I added the option ips=N to /etc/modprobe.d/rtl8192se.conf plus some others just to be sure.
Also, the program TLP interferred with the option so I had to comment out some options at line 130-132 and 154-160.

with rtl8192se.conf I did the following command(s):
sudo touch /etc/modprobe.d/rtl8192se.conf; echo "options rtl8192se ips=N fwlps=N swlps=N debug=1 disable_watchdog=Y swenc=N" | sudo tee /etc/modprobe.d/rtl8192se.conf

in /etc/default/tlp I commented out the options at line 130-132 like this:
# WiFi power saving mode: 1=disable, 5=enable; not supported by all adapters.
WIFI_PWR_ON_AC=1
WIFI_PWR_ON_BAT=1

line 154-160 like this:
# Runtime Power Management for PCI(e) bus devices: on=disable, auto=enable
RUNTIME_PM_ON_AC=auto
RUNTIME_PM_ON_BAT=auto

# Runtime PM for *all* PCI(e) bus devices, except blacklisted ones:
#   0=disable, 1=enable
RUNTIME_PM_ALL=1

and line 162-164
# Exclude PCI(e) device adresses the following list from Runtime PM
# (separate with spaces). Use lspci to get the adresses (1st column).
RUNTIME_PM_BLACKLIST="04:00.0"

then following command to apply:
sudo modprobe -r rtl8192se; sudo modprobe rtl8192se

to check if settings in /etc/modprobe.d/rtl8192se.conf are applied I used sysfsutils' systool with following command:

sudo systool -a -v -m rtl8192se | grep -A6 "Parameters:"

which should have given the following:
  Parameters:
    debug                       = "1"
    disable_watchdog    = "Y"
    fwlps                         = "N"
    ips                            = "N"
    swenc                       = "N"
    swlps                        = "N"

Now my Ubuntu 14.04.4 wifi definitely works better, some drops still happen, I am not sure why.

**Comment by pressure679** [comment]
Something helped, this is my rtl8192se parameters:
    debug               = "1"
    disable_watchdog    = "Y"
    fwlps               = "N"
    ips                 = "N"
    swenc               = "N"
    swlps               = "N"
and here is my dmesg (grep rtl) as requested:
    [   18.909816] rtlwifi: module verification failed: signature and/or required key missing - tainting kernel
    [   19.515998] Loading firmware rtlwifi/rtl8192sefw.bin
    [   19.516011] rtlwifi: channel plan 0xb
    [   19.516013] rtlwifi: bad channel plan 0xb
    [   19.516014] rtlwifi: country code 11
    [   19.539234] ieee80211 phy0: Selected rate control algorithm 'rtl_rc'

btw, I tried configuring tlp to blacklist rtl8192 from pci(e) power management and disabling wifi power saving mode. I have ended up uninstalling and i now hardly notice wifi dropping

**Comment by pressure679** [comment]
It is most definitely TLP, doing "sudo service tlp stop" makes connection flawless.

**Comment by pressure679** [comment]
I realized it was a DNS problem when setting a static IP using Network-Manager. I am sorry for taking your time.
