### ISSUE TITLE
RTL8723BE make error

### ISSUE THREAD

**Issue by Prrmod** [lwfinger/rtlwifi_new#114]
While running the make command, the bash throws the below error in opensuse leap 42.1 OS

pramodc@linux-6i6o:~/rtlwifi_new> make
make -C /lib/modules/4.1.12-1-default/build M=/home/pramodc/rtlwifi_new modules
make[1]: *** /lib/modules/4.1.12-1-default/build: No such file or directory.  Stop.
Makefile:57: recipe for target 'all' failed
make: *** [all] Error 2
pramodc@linux-6i6o:~/rtlwifi_new> 

How to fix this error and install the driver?

**Comment by lwfinger** [comment]
Install the kernel headers.

**Comment by Asgator** [comment]
@lwfinger, helo, you can say, how to install?

**Comment by Prrmod** [comment]
Kernel headers were installed by the OS during its installation.  The problem is with the build command. On stackovelow, i've was advised to installed Base Development package. I've installed devel_basis pattern package, but the problem still persists. http://stackoverflow.com/questions/36578318/realtek-wifi-issue-in-opensuse

**Comment by Prrmod** [comment]
This solution helped me fix the issue https://forums.opensuse.org/showthread.php/509680-Realtek-8723BE-wireless-adapter-establishes-connection-then-unstable-and-intermittent?p=2728948#post2728948
