### ISSUE TITLE
Unable to install RTL8723BE driver Ubuntu 16.04

### ISSUE THREAD

**Issue by shivisuper** [lwfinger/rtlwifi_new#115]
I just upgraded to Ubuntu 16.04 (from 15.10 on which the driver was working perfectly fine), and now my driver is uninstalled. Even after compiling and installing the build from https://github.com/lwfinger/rtlwifi_new/tree/rock.new_btcoex branch, the iwconfig shows "no wireless extensions". I tried installing and then "modprobe"ing but that gave me "error: rtl8723be required key missing".

**Comment by sovietunion96** [comment]
I have the same problem as shivisuper .The driver works very well on 15.10 but just cannot work on 16.04

**Comment by lwfinger** [comment]
What changed? This driver did not. You need to investigate what Ubuntu changed.

**Comment by shivisuper** [comment]
Any specific direction from where I should start investigating the issue? @lwfinger

**Comment by lwfinger** [comment]
I am not an Ubuntu user and I have no idea what they may have altered. The key message indicates that the system now expects modules to be signed. My code does not generate that info. You may be able to find some way around that problem by searching; however, you should check to see if the driver that comes with their system works with the ant_sel option. There may also be test kernels. I know that Fedora has generated kernels with this feature enabled.

**Comment by shivisuper** [comment]
Ok thanks for the headstart @lwfinger . Will start with the option first.

**Comment by shivisuper** [comment]
@lwfinger you were right regarding this issue being related to signed and unsigned modules. Since my machine runs UEFI BIOS with a secure boot, all the modules that are to be initiated must be signed. So, the solution (maybe not permanent) to my problem was to disable "secure boot" in the BIOS settings, and now the wifi works like a charm. I'll close this issue now but just out of curiosity, I wanted to know that why did I not face this problem with the previous version of the kernel? Even though I had my secure boot option enabled?

**Comment by lwfinger** [comment]
It is possible that previous versions of the kernel were generated without the module signing option. I have no other explanation; however, disabling secure boot will work. When Ubuntu distributes kernel 4.7, or one with the antenna selection code included, then you will be able to use the standard kernel driver and you will be able to turn secure boot back on.

**Comment by shivisuper** [comment]
Thanks very much @lwfinger . I'm closing this issue now.
