### ISSUE TITLE
Trouble Installing On Fedora 23 Kernel 4.4.8-300

### ISSUE THREAD

**Issue by leoadhemartan** [lwfinger/rtlwifi_new#117]
I always install this driver manually every new kernel update. No issues from 4.4.6 and 4.4.7 but on 4.4.8, I get this error when I run make..

make -C /lib/modules/4.4.8-300.fc23.x86_64/build M=/mnt/data/installers/linux/fedora drivers/rtlwifi_new-master modules
make[1]: Entering directory '/usr/src/kernels/4.4.8-300.fc23.x86_64'
Makefile:660: Cannot use CONFIG_CC_STACKPROTECTOR_STRONG: -fstack-protector-strong not supported by compiler
make[1]: *** No rule to make target 'drivers/rtlwifi_new-master'.  Stop.
make[1]: Leaving directory '/usr/src/kernels/4.4.8-300.fc23.x86_64'
Makefile:57: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lwfinger** [comment]
I have no idea why your build is failing. I have a fully-updated F23 instance running in a virtual machine with exactly the kernel you have. It builds rtlwifi_new without error. The 4.4.8-300.fc23.x86_64 kernel was built with CONFIG_CC_STACKPROTECTOR_STRONG=y, but the compiler in my machine handles it OK.

On my VM, the command 'gcc --version' shows version "5.3.1 20160406 (Red Hat 5.3.1-6)". Perhaps yours is not up to date.

**Comment by leoadhemartan** [comment]
Your comment made redo the download of the latest commits. I apologize as I did not check there was a new version since last month. 

Make and Make Install were successful.

Thanks for creating and maintaining this.
