### ISSUE TITLE
rtl8192ee Init MAC failed after Connection to AP lost. [openSuSE 4.1.20-11]

### ISSUE THREAD

**Issue by damianoct** [lwfinger/rtlwifi_new#118]
I'm running openSuSE Leap 42.1 on Thinkpad x240 with 4.1.20-11-default kernel.
The connection works at first boot and it's absolutely unstable. After lost Connection to AP the device cannot find any available wireless network. 
So i disable and then able the wifi card and the result from dmesg is "rtl8192ee:rtl92ee_hw_init():<0,0> Init MAC Failed".

I'm using the rtlwifi_new driver from master branch.

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
