### ISSUE TITLE
Red Hat 7.2 - Compile error on start.

### ISSUE THREAD

**Issue by bryn1u** [lwfinger/rtlwifi_new#122]
Hello. I've got an error.

> [root@localhost rtlwifi_new]# make
> make -C /lib/modules/3.10.0-327.18.2.el7.x86_64/build M=/root/rtlwifi_new modules
> make[1]: Wejście do katalogu `/usr/src/kernels/3.10.0-327.18.2.el7.x86_64'
>   CC [M]  /root/rtlwifi_new/pci.o
> In file included from /root/rtlwifi_new/pci.c:33:0:
> /root/rtlwifi_new/pci.h:349:1: error: redefinition of ‘pci_zalloc_consistent’
>  pci_zalloc_consistent(struct pci_dev *hwdev, size_t size,
>  ^
> In file included from /usr/src/kernels/3.10.0-327.18.2.el7.x86_64/arch/x86/include/asm/pci.h:118:0,
>                  from include/linux/pci.h:1449,
>                  from /root/rtlwifi_new/pci.h:33,
>                  from /root/rtlwifi_new/pci.c:33:
> include/asm-generic/pci-dma-compat.h:23:1: note: previous definition of ‘pci_zalloc_consistent’ was here
>  pci_zalloc_consistent(struct pci_dev *hwdev, size_t size,
>  ^
> make[2]: *** [/root/rtlwifi_new/pci.o] Błąd 1
> make[1]: *** [_module_/root/rtlwifi_new] Błąd 2
> make[1]: Opuszczenie katalogu`/usr/src/kernels/3.10.0-327.18.2.el7.x86_64'
> make: **\* [all] Błąd 2
> [root@localhost rtlwifi_new]#

**Comment by lwfinger** [comment]
The code for pci_zalloc_consistent() is not supposed to exist in the kernel sources before 3.17. Whatever Red Hat is putting into include/asm-generic/pci-dma-compat.h is interfering.

Once again, if I fix the source for you, I will break the build for every other user with kernels older than 3.17. You will need to modify pci.h and change line 347. Replace the 17 in that line with 10. Your code will then build.

**Comment by lwfinger** [comment]
You have found another place where RH's changes break it. In base.c, change the 11 in line 485 to 10.

Now that you have seen the pattern, I will let you fix the rest of them.

**Comment by bryn1u** [comment]
There are so many capabilities. How do u know what kind of line need to be changed ? I don't see it in debug log. 

Thank u for help.

**Comment by lwfinger** [comment]
The line you need to look for are of the type

#if (LINUX_VERSION_CODE >= KERNEL_VERSION(3, XX, 0))

You will need to find a value for XX that causes the code that has an error to not be selected.

Your other option would be to find a distro that does not make these "illegal" changes to the kernel source.

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
