### ISSUE TITLE
Issues with linux-mainline (4.7-rc1)

### ISSUE THREAD

**Issue by Great-Geek** [lwfinger/rtlwifi_new#125]
Due to removal of `enum ieee80211_band` ( https://github.com/torvalds/linux/commit/57fbcce37be7c1d2622b56587c10ade00e96afa3 ) , we have the following build failure:
```
rtlwifi_new/wifi.h:1327:40: error: ‘IEEE80211_NUM_BANDS’ undeclared here (not in a function)
  struct ieee80211_supported_band bands[IEEE80211_NUM_BANDS];
                                        ^~~~~~~~~~~~~~~~~~~
rtlwifi_new/base.c:138:10: error: ‘IEEE80211_BAND_2GHZ’ undeclared here (not in a function)
  .band = IEEE80211_BAND_2GHZ,
          ^~~~~~~~~~~~~~~~~~~
rtlwifi_new/base.c:150:10: error: ‘IEEE80211_BAND_5GHZ’ undeclared here (not in a function)
  .band = IEEE80211_BAND_5GHZ,
          ^~~~~~~~~~~~~~~~~~~
```

Additionally, `ant_sel` is implemented in mainline, but for some odd reason, I need to use `ant_sel=1` on 4.7-rc1 (inbuilt) and `ant_sel=2` on 4.6 (with rtlwifi_new)
I'm using an HP Pavilion 15-ab035ax, which has the rtl8723be card.

**Comment by lwfinger** [comment]
The updates for the kernel API change have been pushed for branches master, rock, rock.new_btcoex and troy.

Your experience regarding ant_sel are strange. When I implemented that module parameter, I effectively reserved the value of 2 for future usage. Both the Realtek engineer and I agreed that in the current code, ant_sel=2 was no different than ant_sel=0 (the default). Apparently we were wrong; however, in all my testing with a single antenna attached to connector 2, then ant_sel=1 was needed.

There are some differences in the BT coexistence code between the rock.new_btcoexist branch and kernels 4.6 and newer; however, I have tried to make the rest of the driver be the same.

**Comment by Great-Geek** [comment]
@lwfinger Built branch master, with kernel 4.7-rc1. `ant_sel` now seems to work as you have described, with values 0 and 2 picking up only the closest router. `ant_sel=1` is what I need for proper functionality on 4.7

I will build against 4.6, test the various values of ant_sel, and report back here in a couple of hours.

**Comment by Great-Geek** [comment]
@lwfinger I've tested the various values of `ant_sel` on both, 4.7-rc1 and 4.6, and here's what I've verified:

|  Kernel | ant_sel=0   | ant_sel=1     | ant_sel=2     |
|:-------:|-------------|---------------|---------------|
|   4.6   | Weak signal | Strong signal | Strong signal |
| 4.7-rc1 | Weak signal | Strong signal | Weak signal   |

I couldn't believe I had discrepancies between values on 4.6 and 4.7-rc1, so i rebuilt both kernels and the master branch without ccache. This did not affect the behavior in any way.

**Comment by CitoplasmaX** [comment]
Where can i change ant_sel value?

**Comment by lwfinger** [comment]
It is a module parameter. Look it up.
