### ISSUE TITLE
RTL8723BE: Wifi always drops after 15/20 mins 

### ISSUE THREAD

**Issue by mscalzotto** [lwfinger/rtlwifi_new#126]
Hello @lwfinger ,

I've bought this laptop (HP Pavilion Notebook - Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz) with Realtek 8723BE wifi card almost three months ago. Then installed Ubuntu 16.04 with dual boot with Win10 and then cloned and installed rtlwifi_new driver.

The driver really improved my connection. I tried many combinations of parameters in rtl8723be.conf (currently have options rtl8723be ant_sel=2 ips=0 msi=1) and read many of the issues posted here in this repo about RTL8723BE card but got no luck: after 15/20 min my connection drops.

Below I'll paste some links of Ubuntu pastebin that I collected:

*Kernel log when I set debug=4 in rtl8723be.conf at the moment that the connection dropped out:*
http://paste.ubuntu.com/17104417/

*Wireless info script before losing the connection*
http://paste.ubuntu.com/17104598/

*Wireless info script after losing the connection*
http://paste.ubuntu.com/17104656/

Hope you can help me to get this working. Please don't hesitate to ask me if you need more information.

Thanks in advance!
Max

**Comment by MrOutput** [comment]
I had the same issue on mine I had to change something like flwps=0

**Comment by mscalzotto** [comment]
@MrOutput I tried it but it didn't work

**Comment by MrOutput** [comment]
strange this was the link that told me to do it btw https://wiki.archlinux.org/index.php/Wireless_network_configuration#rtl8723ae.2Frtl8723be

**Comment by mscalzotto** [comment]
Nope... No connection at all using options rtl8723be fwlps=0

**Comment by MrOutput** [comment]
strange, are you using a network manager? If so which one? Have you tried scanning out with `iw`?

**Comment by mscalzotto** [comment]
Yes, here is the scan report: http://paste.ubuntu.com/17343306/

Now I tried adding ips=0 => *options rtl8723be ant_sel=2 msi=1 ips=0* and I got some improvements on the connection, but if I don't remove and add again the module (sudo modprobe -r rtl8723be && sudo modprobe rtl8723be) after launch the connection lasts about 10min. Doing that my connection lasts very much, but got no connections/networks after suspension.

**Comment by MrOutput** [comment]
All of the signal strengths in that output are *very weak*. It could be an issue with the network and not the driver. Have you tested a wireless connection on the same machine, at the same location?

**Comment by mscalzotto** [comment]
4.4.0-22-generic

Hm, I have the same issue with other connections, and I have other devices (phone, tablet) and another notebook that haven't network problems. Even this network (of this notebook) works fine with windows 10 :/

**Comment by MrOutput** [comment]
Hmm like I said the signal strength is weak. Make sure the antennas are intact on the NIC and if they are try messing w/ the antenna settings. That is really the only issue. It is reading a weak signal.

**Comment by lwfinger** [comment]
The ant_sel=2 option was only included to allow for some future expansion of the algorithm. At the moment, ant_sel=2 does what ant_sel=0 does.

Have you tried ant_sel=1, and what does it do to signal strengths?

**Comment by mscalzotto** [comment]
@lwfinger Yes, I've tried and the result is no connections are available.

**Comment by laugeo** [comment]
There is a new driver since 3 day, try it.
If no luck , read this:  I had a similar problem with hp 250g4 (rtl8723be wifi,  with ant_sel =2  )  : connection was  going slow then not responsive at all, after a variable time (3mn to 2 hours) . I changed a lot of parameter (wifi N to G, reinstall xubuntu 16.04  ). 
From the exact moment where i disabled fastboot in Windows 10 (in energy settings) and reboot once to windows ,   problem totally  disapeared in Linux . It was 2  weeks ago so it seems a stable fix.
Note the wifi was not  good in windows 10 too ( with latest driver).
May be something like the following  where fastboot has bad effect on linux sound:
http://askubuntu.com/questions/464388/no-sound-from-laptop-speakers-in-ubuntu-14-04-after-booting-into-windows-8-1

**Comment by mscalzotto** [comment]
Clap clap clap clap! Amazing @laugeo! I booted with Win 10 and deactivated fast boot (not before reading a little while about it) and voilá! No more dropouts after it! Really, thanks a lot to you, @lwfinger and @MrOutput. You help me out a lot here guys!
