### ISSUE TITLE
RTL8192EU

### ISSUE THREAD

**Issue by karl69942** [lwfinger/rtlwifi_new#128]
I'm not sure about this repo, but the other one I'd used, Hanipouspilot or something of the sort, has a not-so-great driver for it - basically it's been disconnecting every like 2 minutes and its my secondary pc I control via wifi, or putty etc, so this is very pesky.
Would love to get it working right! I heard you guys don't have a driver for it yet, obda:818b

**Comment by lwfinger** [comment]
Thr driver for the RTL8192CU is the only USB device covered here.
