### ISSUE TITLE
rtlwifi_new-rock.new_btcoex/core.c:1809:18: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]

### ISSUE THREAD

**Issue by val0x00ff** [lwfinger/rtlwifi_new#133]
Hi,

So I upgraded my kernel and tried to recompile the rtl8723be driver.  When running `make` and `make install` the following error appears:

```
make -C /lib/modules/4.6.3-300.fc24.x86_64/build M=/home/valentin/Downloads/rtlwifi_new-rock.new_btcoex modules
make[1]: Entering directory '/usr/src/kernels/4.6.3-300.fc24.x86_64'
  CC [M]  /home/valentin/Downloads/rtlwifi_new-rock.new_btcoex/core.o
/home/valentin/Downloads/rtlwifi_new-rock.new_btcoex/core.c:1809:18: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .ampdu_action = rtl_op_ampdu_action,
                  ^~~~~~~~~~~~~~~~~~~
/home/valentin/Downloads/rtlwifi_new-rock.new_btcoex/core.c:1809:18: note: (near initialization for ‘rtl_ops.ampdu_action’)
cc1: all warnings being treated as errors
scripts/Makefile.build:291: recipe for target '/home/valentin/Downloads/rtlwifi_new-rock.new_btcoex/core.o' failed
make[2]: *** [/home/valentin/Downloads/rtlwifi_new-rock.new_btcoex/core.o] Error 1
Makefile:1433: recipe for target '_module_/home/valentin/Downloads/rtlwifi_new-rock.new_btcoex' failed
make[1]: *** [_module_/home/valentin/Downloads/rtlwifi_new-rock.new_btcoex] Error 2
make[1]: Leaving directory '/usr/src/kernels/4.6.3-300.fc24.x86_64'
Makefile:58: recipe for target 'all' failed
make: *** [all] Error 2
```

What is going on?

The kernel I'm using is `4.6.3-300.fc24.x86_64` 

The gcc-*

```
gcc-6.1.1-3.fc24.x86_64
gcc-c++-6.1.1-3.fc24.x86_64
libgcc-6.1.1-3.fc24.x86_64
libgcc-6.1.1-3.fc24.i686
gcc-gdb-plugin-6.1.1-3.fc24.x86_64

```

**Comment by lwfinger** [comment]
For some reason, you do not have the latest code. The line number for .ampdu_action = rtl_op_ampdu_action, is 1821, not 1809. If you used git to clone the source, then just do 'git pull'. If you downloaded a zip, I suggest that you now do the git clone. You will save a lot of effort. Of course, the 4.6.3 kernel has all the features of this repo.

**Comment by val0x00ff** [comment]
@lwfinger Thanks for the quick reply. I indeed did another git clone and everything seems to be compiling fine. I'm really not sure why Fedora hasn't yet done anything in packaging these drivers and providing them upstream.   Thanks again, problem is now solved!

**Comment by lwfinger** [comment]
ALL of these drivers are available upstream!! This repo is mainly for users with kernels that are older than when the drivers were added. In fact, all the drivers have been in mainline since 3,18.
