### ISSUE TITLE
Realtek 3062 wifi b/g/n pci/cb works only intermittently

### ISSUE THREAD

**Issue by ralphldcm** [lwfinger/rtlwifi_new#135]
I have a Realtek (now Mediatek) 3062 wifi b/g/n pci/cb card in my older Dell Latitude D610.  It works only intermittently.  I read https://github.com/lwfinger/rtlwifi_new/issues/34, which describes very similar issues with an RTL8723BE card.  I installed a new version of xubuntu 16.04, updated it, and installed the 4.7rc1 kernel as recommended in https://github.com/lwfinger/rtlwifi_new/issues/34.  I don't know if other drivers/firmware need to be installed for the rt3062. The card still failed intermittently.  I also installed the rt3062 under Windows XP, but xp had the same problems as xubuntu--worked only intermittently.  I opened a thread in ubuntu forums: http://ubuntuforums.org/showthread.php?t=2327616&page=2.  Any help would be appreciated....

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
