### ISSUE TITLE
install

### ISSUE THREAD

**Issue by masiha68** [lwfinger/rtlwifi_new#137]
Hi
how i can install this driver ?

**Comment by manu-chroma** [comment]
https://github.com/lwfinger/rtlwifi_new/pull/74/files

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
