### ISSUE TITLE
modprobe -r rtl8723 is not found

### ISSUE THREAD

**Issue by NikoManiac** [lwfinger/rtlwifi_new#138]
Hi,when i trying to sudo modprobe -r rtl8723,this tell me 

```
modprobe: FATAL: Module RTL8723BE not found.
```

how to go

**Comment by lwfinger** [comment]
You have not built the module. Obviously, something that does not exist cannot re unloaded.

Please explain what you have done and what you want to do. My crystal ball is broken.

**Comment by iphoneseven** [comment]
You have to clone this repository, build the driver, then install it.
You can do that by:
1. Obtaining temporary internet connection
Open a terminal and run in it terminal these commands:
sudo apt-get install git build-essential (build-essential might be different for your distribution, google it)
git clone https://github.com/lwfinger/rtlwifi_new
cd rtlwifi_new
make
sudo make install (type your password when in prompts you)
cd /etc/modprobe.d/
sudo nano rtl8723be.conf, once nano opens, type the following:
"options rtl8723be ips=0 fwlps=0 ant_sel=2"
Okay, now exit out of nano by holding control then pressing x, then typing "y" then pressing enter.
Now reboot, and if network-manager/wicd/whatever you use detects your network you should be good! 

But if they see don't see your network run this command:
sudo nano /etc/modprobe.d/rtl8723be.conf 
Now, you should see the stuff you typed above.  What you want to do is change ant_sel=2 to ant_sel=1. That's the only change necessary. Now you can reboot and everything should work.

**Comment by iphoneseven** [comment]
You have to clone this repository, build the driver, then install it.
You can do that by:
1. Obtaining temporary internet connection
Open a terminal and run in it terminal these commands:
sudo apt-get install git build-essential (build-essential might be different for your distribution, google it)
git clone https://github.com/lwfinger/rtlwifi_new
cd rtlwifi_new
make
sudo make install (type your password when in prompts you)
cd /etc/modprobe.d/
sudo nano rtl8723be.conf, once nano opens, type the following:
"options rtl8723be ips=0 fwlps=0 ant_sel=2"
Okay, now exit out of nano by holding control then pressing x, then typing "y" then pressing enter.
Now reboot, and if network-manager/wicd/whatever you use detects your network you should be good! 

But if they see don't see your network run this command:
sudo nano /etc/modprobe.d/rtl8723be.conf 
Now, you should see the stuff you typed above.  What you want to do is change ant_sel=2 to ant_sel=1. That's the only change necessary. Now you can reboot and everything should work.

**Comment by iphoneseven** [comment]
You have to clone this repository, build the driver, then install it.
You can do that by:
1. Obtaining temporary internet connection
Open a terminal and run in it terminal these commands:
sudo apt-get install git build-essential (build-essential might be different for your distribution, google it)
git clone https://github.com/lwfinger/rtlwifi_new
cd rtlwifi_new
make
sudo make install (type your password when in prompts you)
cd /etc/modprobe.d/
sudo nano rtl8723be.conf, once nano opens, type the following:
"options rtl8723be ips=0 fwlps=0 ant_sel=2"
Okay, now exit out of nano by holding control then pressing x, then typing "y" then pressing enter.
Now reboot, and if network-manager/wicd/whatever you use detects your network you should be good! 

But if they see don't see your network run this command:
sudo nano /etc/modprobe.d/rtl8723be.conf 
Now, you should see the stuff you typed above.  What you want to do is change ant_sel=2 to ant_sel=1. That's the only change necessary. Now you can reboot and everything should work.

**Comment by iphoneseven** [comment]
You have to clone this repository, build the driver, then install it.
You can do that by:
1. Obtaining temporary internet connection
Open a terminal and run in it terminal these commands:
sudo apt-get install git build-essential (build-essential might be different for your distribution, google it)
git clone https://github.com/lwfinger/rtlwifi_new
cd rtlwifi_new
make
sudo make install (type your password when in prompts you)
cd /etc/modprobe.d/
sudo nano rtl8723be.conf, once nano opens, type the following:
"options rtl8723be ips=0 fwlps=0 ant_sel=2"
Okay, now exit out of nano by holding control then pressing x, then typing "y" then pressing enter.
Now reboot, and if network-manager/wicd/whatever you use detects your network you should be good! 

But if they see don't see your network run this command:
sudo nano /etc/modprobe.d/rtl8723be.conf 
Now, you should see the stuff you typed above.  What you want to do is change ant_sel=2 to ant_sel=1. That's the only change necessary. Now you can reboot and everything should work.

**Comment by iphoneseven** [comment]
You have to clone this repository, build the driver, then install it.
You can do that by:
1. Obtaining temporary internet connection
Open a terminal and run in it terminal these commands:
sudo apt-get install git build-essential (build-essential might be different for your distribution, google it)
git clone https://github.com/lwfinger/rtlwifi_new
cd rtlwifi_new
make
sudo make install (type your password when in prompts you)
cd /etc/modprobe.d/
sudo nano rtl8723be.conf, once nano opens, type the following:
"options rtl8723be ips=0 fwlps=0 ant_sel=2"
Okay, now exit out of nano by holding control then pressing x, then typing "y" then pressing enter.
Now reboot, and if network-manager/wicd/whatever you use detects your network you should be good! 

But if they see don't see your network run this command:
sudo nano /etc/modprobe.d/rtl8723be.conf 
Now, you should see the stuff you typed above.  What you want to do is change ant_sel=2 to ant_sel=1. That's the only change necessary. Now you can reboot and everything should work.

**Comment by iphoneseven** [comment]
You have to clone this repository, build the driver, then install it.
You can do that by:
1. Obtaining temporary internet connection
Open a terminal and run in it terminal these commands:
sudo apt-get install git build-essential (build-essential might be different for your distribution, google it)
git clone https://github.com/lwfinger/rtlwifi_new
cd rtlwifi_new
make
sudo make install (type your password when in prompts you)
cd /etc/modprobe.d/
sudo nano rtl8723be.conf, once nano opens, type the following:
"options rtl8723be ips=0 fwlps=0 ant_sel=2"
Okay, now exit out of nano by holding control then pressing x, then typing "y" then pressing enter.
Now reboot, and if network-manager/wicd/whatever you use detects your network you should be good! 

But if they see don't see your network run this command:
sudo nano /etc/modprobe.d/rtl8723be.conf 
Now, you should see the stuff you typed above.  What you want to do is change ant_sel=2 to ant_sel=1. That's the only change necessary. Now you can reboot and everything should work.

**Comment by iphoneseven** [comment]
You have to clone this repository, build the driver, then install it.
You can do that by:
1. Obtaining temporary internet connection
Open a terminal and run in it terminal these commands:
sudo apt-get install git build-essential (build-essential might be different for your distribution, google it)
git clone https://github.com/lwfinger/rtlwifi_new
cd rtlwifi_new
make
sudo make install (type your password when in prompts you)
cd /etc/modprobe.d/
sudo nano rtl8723be.conf, once nano opens, type the following:
"options rtl8723be ips=0 fwlps=0 ant_sel=2"
Okay, now exit out of nano by holding control then pressing x, then typing "y" then pressing enter.
Now reboot, and if network-manager/wicd/whatever you use detects your network you should be good! 

But if they see don't see your network run this command:
sudo nano /etc/modprobe.d/rtl8723be.conf 
Now, you should see the stuff you typed above.  What you want to do is change ant_sel=2 to ant_sel=1. That's the only change necessary. Now you can reboot and everything should work.

**Comment by iphoneseven** [comment]
You have to clone this repository, build the driver, then install it.
You can do that by:
1. Obtaining temporary internet connection
Open a terminal and run in it terminal these commands:
sudo apt-get install git build-essential (build-essential might be different for your distribution, google it)
git clone https://github.com/lwfinger/rtlwifi_new
cd rtlwifi_new
make
sudo make install (type your password when in prompts you)
cd /etc/modprobe.d/
sudo nano rtl8723be.conf, once nano opens, type the following:
"options rtl8723be ips=0 fwlps=0 ant_sel=2"
Okay, now exit out of nano by holding control then pressing x, then typing "y" then pressing enter.
Now reboot, and if network-manager/wicd/whatever you use detects your network you should be good! 

But if they see don't see your network run this command:
sudo nano /etc/modprobe.d/rtl8723be.conf 
Now, you should see the stuff you typed above.  What you want to do is change ant_sel=2 to ant_sel=1. That's the only change necessary. Now you can reboot and everything should work.

**Comment by iphoneseven** [comment]
You have to clone this repository, build the driver, then install it.
You can do that by:
1. Obtaining temporary internet connection
Open a terminal and run in it terminal these commands:
sudo apt-get install git build-essential (build-essential might be different for your distribution, google it)
git clone https://github.com/lwfinger/rtlwifi_new
cd rtlwifi_new
make
sudo make install (type your password when in prompts you)
cd /etc/modprobe.d/
sudo nano rtl8723be.conf, once nano opens, type the following:
"options rtl8723be ips=0 fwlps=0 ant_sel=2"
Okay, now exit out of nano by holding control then pressing x, then typing "y" then pressing enter.
Now reboot, and if network-manager/wicd/whatever you use detects your network you should be good! 

But if they see don't see your network run this command:
sudo nano /etc/modprobe.d/rtl8723be.conf 
Now, you should see the stuff you typed above.  What you want to do is change ant_sel=2 to ant_sel=1. That's the only change necessary. Now you can reboot and everything should work.

**Comment by iphoneseven** [comment]
You have to clone this repository, build the driver, then install it.
You can do that by:
1. Obtaining temporary internet connection
Open a terminal and run in it terminal these commands:
sudo apt-get install git build-essential (build-essential might be different for your distribution, google it)
git clone https://github.com/lwfinger/rtlwifi_new
cd rtlwifi_new
make
sudo make install (type your password when in prompts you)
cd /etc/modprobe.d/
sudo nano rtl8723be.conf, once nano opens, type the following:
"options rtl8723be ips=0 fwlps=0 ant_sel=2"
Okay, now exit out of nano by holding control then pressing x, then typing "y" then pressing enter.
Now reboot, and if network-manager/wicd/whatever you use detects your network you should be good! 

But if they see don't see your network run this command:
sudo nano /etc/modprobe.d/rtl8723be.conf 
Now, you should see the stuff you typed above.  What you want to do is change ant_sel=2 to ant_sel=1. That's the only change necessary. Now you can reboot and everything should work.

**Comment by iphoneseven** [comment]
You have to clone this repository, build the driver, then install it.
You can do that by:
1. Obtaining temporary internet connection
Open a terminal and run in it terminal these commands:
sudo apt-get install git build-essential (build-essential might be different for your distribution, google it)
git clone https://github.com/lwfinger/rtlwifi_new
cd rtlwifi_new
make
sudo make install (type your password when in prompts you)
cd /etc/modprobe.d/
sudo nano rtl8723be.conf, once nano opens, type the following:
"options rtl8723be ips=0 fwlps=0 ant_sel=2"
Okay, now exit out of nano by holding control then pressing x, then typing "y" then pressing enter.
Now reboot, and if network-manager/wicd/whatever you use detects your network you should be good! 

But if they see don't see your network run this command:
sudo nano /etc/modprobe.d/rtl8723be.conf 
Now, you should see the stuff you typed above.  What you want to do is change ant_sel=2 to ant_sel=1. That's the only change necessary. Now you can reboot and everything should work.

**Comment by iphoneseven** [comment]
You have to clone this repository, build the driver, then install it.
You can do that by:
1. Obtaining temporary internet connection
Open a terminal and run in it terminal these commands:
sudo apt-get install git build-essential (build-essential might be different for your distribution, google it)
git clone https://github.com/lwfinger/rtlwifi_new
cd rtlwifi_new
make
sudo make install (type your password when in prompts you)
cd /etc/modprobe.d/
sudo nano rtl8723be.conf, once nano opens, type the following:
"options rtl8723be ips=0 fwlps=0 ant_sel=2"
Okay, now exit out of nano by holding control then pressing x, then typing "y" then pressing enter.
Now reboot, and if network-manager/wicd/whatever you use detects your network you should be good! 

But if they see don't see your network run this command:
sudo nano /etc/modprobe.d/rtl8723be.conf 
Now, you should see the stuff you typed above.  What you want to do is change ant_sel=2 to ant_sel=1. That's the only change necessary. Now you can reboot and everything should work.

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
