### ISSUE TITLE
Rtl8821AE randomly becomes unresponsive

### ISSUE THREAD

**Issue by alexander255** [lwfinger/rtlwifi_new#139]
I have tried a lot of things to debug this, but I think my knowledge is at it's end.

I have bought a new laptop with an `rtl8821ae` wireless PCI chipset and it randomly stops working in managed mode after a short time.
Here is a trace with `debug=5 fwlps=0 ips=0 disable_watchdog=Y`:
http://ipfsbin.xyz/#Qmahsbz48tVCiV9Sq7VNK7MXydpEFiQTmW3hbQv74uvi3u

Using another computer with Wireshark and an Intel Centrino 6xxx chipset in monitor mode, I have verified that no more data is being sent by the wireless hardware (although the logs indicate that the firmware seems to think it is sending stuff). At around the same time no more data is being received either, which will eventually cause a timeout on both the router and the wireless client.

I am pretty sure that this is an error in the wireless card firmware, but I have no idea on how to debug this any further… Please throw some ideas my way!

Wireless drivers tried: Yours and the one shipped with Linux 4.6.0
Firmware: The one shipped in Version `20160110-1` of the Debian [`firmware-realtek` package](https://packages.debian.org/sid/firmware-realtek)

**Comment by alexander255** [comment]
@lwfinger: Please tell me whether you think this is something that can be solved, if not I'll start looking for a different PCI laptop WiFi card.

**Comment by lwfinger** [comment]
First of all, I will never look at a debug=5 log unless I ask for it.

If it is failing with ips=0. then there is little I can do for you. I have no knowledge of the internals of the device. If you were getting kernel oops messages, then I could fix them. There is likely some quirk in your AP that the firmware and/or driver is failing to handle. With my Trendnet and Netgear AP's, I see very few drops when using ips=0.

**Comment by alexander255** [comment]
> First of all, I will never look at a debug=5 log unless I ask for it.

Unfortunately I don't think it will matter, because the only thing the log really shows (in any level > 2) is the fact the driver stops receiving packets for no apparent reason. The linked trace is only an excerpt of were it starts failing, btw.

> If it is failing with ips=0. then there is little I can do for you. I have no knowledge of the internals of the device. If you were getting kernel oops messages, then I could fix them.

I guess it will be a new wireless card then. Any tips/recommendations on this?

> There is likely some quirk in your AP that the firmware and/or driver is failing to handle. With my Trendnet and Netgear AP's, I see very few drops when using ips=0.

I tried this on my home wifi (Atheros chipset) and my mobile phone's wifi hotspot (Samsung device with Qualcom baseband I think). That's obviously not a very huge vendor variety, but if it doesn't work here, why would it work in `$RANDOM_WIFI_NETWORK` out there?
The only thing I noticed when looking at the monitor logs was that this wifi card would always immediately send a (802.11) *Acknowledgement*, while the router would occasionally send out *Block Acknowledgement*s for the client's packets. Until the client suddenly stops transmitting or receiving (including sending ACKs) entirely…
Does your wifi router use *Block Acknowledgements* too?

**Comment by lwfinger** [comment]
I am sure that my 1750AC router uses Block Ack, but I have not specifically looked at the over-the-air packets. I have sent this link to my contact at Realtek, and wait for his answer.

**Comment by apolukhin** [comment]
Hello,

I have exactly the same issue. Hope some of the information could be useful to @lwfinger: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1622293

I'm eager to help, but I'm not good with kernels and drivers, so instructions must be very detailed.

**Comment by alexander255** [comment]
In the mean time I've given up and replaced my Realtek WiFi-Board with an Intel one (that works extremely well). If there is any interest from wireless devs, I'll donate my RTL8821AE wireless card (M.2 2230 connector) for driver development. Just shoot me a mail with your name and postal address (preferably in Europe) and I'll send it to you.

**Comment by rsalvaterra** [comment]
Hi, @lwfinger 

I've also been badly bitten by this chip. I'm on Ubuntu 16.04, running the latest possible kernel (4.8-rc7, as of today). I always get seemingly random connectivity losses and speed oscillations (frequently dropping to nearly 0 kb/s), and most of the time I can only recover from these situations by manually removing/reinserting the rtl8812ae module (modprobe -r/modprobe). It's been so awful, last Friday I exchanged the Wi-Fi module on my laptop with the one on my wife's laptop (AR9485), since she uses Windows and it works perfectly there.
I tried every possible combination of module parameters, but the result was always the same. If it's relevant, I've been using only the 2.4 GHz band with an 802.11n router (a soon-to-be-replaced TG874n-V3, provided by my ISP).
If there's anything I can provide to help you debugging/testing, please let me know.

Best regards,

Rui

**Comment by Aror** [comment]
Hi @lwfinger 
I am experiencing similar disconnection issues as reported by others with the RTL8821AE. I tested it on Windows 7, it works fine but disconnects frequently on Ubuntu 16.04. I tried your driver and the native driver. Neither solve the issue. I have reached out to Realtek semiconductors a few weeks ago and have not heard anything back. 

Do you have any updates? Is this something that can be fixed or should I go and buy a different WLAN card? 

Thank you for you work and contribution to the linux community!

Kind regards,

Ignat.

**Comment by lwfinger** [comment]
There is nothing new at the moment. Realtek is working on some BT coexistence routines, but if you are not using BT, then those changes are unlikely to help you.

**Comment by mishoo** [comment]
Adding my whining here. I'm on Arch (Linux 4.8.7) and getting similar behavior.  Wifi mostly works, but every few minutes the connection freezes (it doesn't disconnect, but no packets are transmitted).  It resumes by itself after some random number of seconds.  It's bearable, if quite annoying.

I've put this in `/etc/modprobe.d/rtl8821ae.conf`, but I see no difference:

```
options rtl8821ae ips=0 swlps=0 fwlps=0
```

Question, does kernel 4.8.7 contain the same driver as here? (in other words, I'm asking if it's worth trying the driver from this very repo)

In any case, I consider buying another PCIe wifi card.

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
