### ISSUE TITLE
rtl8188ee: sometimes after resume from suspend, no scan results (since linux 4.7.0)

### ISSUE THREAD

**Issue by goetzc** [lwfinger/rtlwifi_new#140]
Since linux 4.7.0, sometimes after a resume from suspend, scanning for available access points doesn't show any.  
There are no problems with linux 4.6.4 or earlier (tested since 4.1). Unloading the `rtl8188ee` module and loading it back, makes it work (`rmmod rtl8188ee && modprobe rtl8188ee`), and NetworkManager connects automatically to the default network as usual. This is on Arch Linux.

```bash
lspci:
03:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8188EE Wireless Network Adapter (rev 01)
        Subsystem: Hewlett-Packard Company Device 197d
        Kernel driver in use: rtl8188ee
        Kernel modules: rtl8188ee
```

```bash
$ lsmod | grep rtl8188ee
rtl8188ee              86016  0
rtl_pci                28672  1 rtl8188ee
rtlwifi                65536  2 rtl_pci,rtl8188ee
mac80211              659456  3 rtl_pci,rtlwifi,rtl8188ee
```

```bash
$ ethtool -i wlo1
driver: rtl8188ee
version: 4.7.0-1-ARCH
firmware-version: N/A
expansion-rom-version: 
bus-info: 0000:03:00.0
supports-statistics: yes
supports-test: no
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: no
```

```bash
$ iw dev
phy#2
        Interface wlo1
                ifindex 5
                wdev 0x200000001
                addr b0:10:41:xx:xx:xx
                type managed
                channel 9 (2452 MHz), width: 20 MHz, center1: 2452 MHz
                txpower 20.00 dBm
```

```bash
$ iw dev wlo1 link
Connected to 68:89:c1:xx:xx:xx (on wlo1)
        SSID: Wifi-123
        freq: 2452
        RX: 8342490 bytes (28881 packets)
        TX: 533850 bytes (3894 packets)
        signal: -40 dBm
        tx bitrate: 72.2 MBit/s MCS 7 short GI

        bss flags:      short-preamble short-slot-time
        dtim period:    1
        beacon int:     98
```

When this problem happens, `nmcli dev wifi list` shows nothing, I have not tried with `iw dev wlo1 scan`.

Not sure what other info to provide.

**Comment by goetzc** [comment]
This happened again after a resume, so here is an update. NetworkManager didn't connect to the WiFi network, so I did `iw dev wlo1 link` which showed "Not connected.", then `iw dev` showed:

```bash
$ iw dev
phy#0
        Interface wlo1
                ifindex 3
                wdev 0x1
                addr b0:10:41:xx:xx:xx
                type managed
                txpower 20.00 dBm
```

There was this in dmesg:
`[41950.640442] IPv6: ADDRCONF(NETDEV_UP): wlo1: link is not ready`

But then a `iw dev wlo1 scan` did work, and after that, NetworkManager connected automatically (without my intervention) to the usual network. `nmcli dev wifi list` still shows nothing, only after using iw to scan, it showes networks.

After scanning with iw, this is in dmesg:
```
[42182.166411] wlo1: authenticate with 68:89:c1:xx:xx:xx
[42182.176776] wlo1: send auth to 68:89:c1:xx:xx:xx (try 1/3)
[42182.178423] wlo1: authenticated
[42182.182240] wlo1: associate with 68:89:c1:xx:xx:xx (try 1/3)
[42182.186412] wlo1: RX AssocResp from 68:89:c1:xx:xx:xx (capab=0x1411 status=0 aid=3)
[42182.186693] wlo1: associated
[42182.186792] IPv6: ADDRCONF(NETDEV_CHANGE): wlo1: link becomes ready
[42182.245195] wlo1: Limiting TX power to 30 (30 - 0) dBm as advertised by 68:89:c1:xx:xx:xx
```

Why is this different with kernel 4.7, but only with NetworkManager, and not with iw?

**Comment by cperreault** [comment]
I'm writing here because I think it is my best bet to find help. I used to use a PPA to retrieve rtlwifi as rtlwifi-new-dkms (http://ppa.launchpad.net/hanipouspilot/rtlwifi/ubuntu/pool/main/r/rtlwifi-new-dkms/). The source seems for 16.04 have noot been updated since 2016-03-21 and does not compile on kernel 4.7. I now try to build a DEB from the master branch of this GitHub project, but it fails saying that '/lib/modules/4.7.4-040704-generic/kernel/drivers/net/wireless/realtek/rtlwifi/rtl_pci.ko' already exists and cannot be replaced. I use "make" and "checkinstall", both with sudo. I am no expert. So my question : what is the correct way to build and install (with a .deb ideally) the source code on Ubuntu 16.04 with kernel 4.7? Thanks in advance for any help.

**Comment by lwfinger** [comment]
I am not ever going to support building deb or rpm files. There is too much fiddling required.

With kernel 4.7, you should be using the code in the kernel. It is not different than the rtlwifi_new repo, which is for people with older kernels.

**Comment by goetzc** [comment]
lwfinger, I think you may have confused this last post from @cperreault about packaging a deb, which is not related to the original issue.
