### ISSUE TITLE
opensuse13.2 during make throws an error

### ISSUE THREAD

**Issue by blrk** [lwfinger/rtlwifi_new#141]
I am using opensuse13.2 in hp laptop wifi is not connecting with enterprise wifi
I tried to update the drivers using this repo
the make command throws the following error
make -C /lib/modules/3.16.7-35-desktop/build M=/root/rtlwifi_new modules
make[1]: *** /lib/modules/3.16.7-35-desktop/build: No such file or directory.  Stop.
Makefile:57: recipe for target 'all' failed
make: *** [all] Error 2

Thanks for your help

**Comment by blrk** [comment]
sorry guys.. It worked after installing kernel source

but still I am unable to connect with the enterprise wifi in my office.
when I ran the dmesg command it throwed the following error
--------------------------------------------------------------------------------------------
linux-iwsl:~ # dmesg | grep rtl
[   11.870104] Using firmware rtlwifi/rtl8723befw.bin
[   11.870319] rtlwifi: channel plan 0x20
[   11.870320] rtlwifi: country code 11
[   11.873223] ieee80211 phy0: Selected rate control algorithm 'rtl_rc'
[   11.873454] rtlwifi: wireless switch is on
[   25.980177] rtl8723be 0000:0d:00.0 wlp13s0: disabling HT as WMM/QoS is not supported by the AP
[   25.980181] rtl8723be 0000:0d:00.0 wlp13s0: disabling VHT as WMM/QoS is not supported by the AP

**Comment by lwfinger** [comment]
That is an informational message, not an error. Your AP does not support HT or VHT. To do so, you would need to reconfigure.
