### ISSUE TITLE
rtl8821ae cannot find a created 5ghz AP, 2.4Ghz Works fine

### ISSUE THREAD

**Issue by okiura** [lwfinger/rtlwifi_new#142]
As titled I am unable to find a created a 5ghz AP though 2.4Ghz works fine.

I'm running Debian stretch with a 4.6.0-1-amd64 kernel, I upgraded from Jessie with a 3.16 kernel to try and combat this issue but both have the same problem. 

hostapd fires up with no errors but no device can see the AP.

My card was purchesed in the UK and reports country code  0x25, this was not in regd.c so i added a new case for it. if you need any more info i'll do my best to provide it.

'Iw reg get' shows GB as ETSI so i added

`case 0x25:
            return COUNTRY_CODE_ETSI;
`

In doing so i relised all 5Ghz Channels were now disabled so Created a new 'rtl_regdom_' for etsi and made sure it was called if COUNTRY_CODE_ETSI was used... (think the values meet the ETSI regulations)

`case COUNTRY_CODE_ETSI:
                  return &rtl_regdom_etsi;`

`static const struct ieee80211_regdomain rtl_regdom_etsi = {
    .n_reg_rules = 3,
    .alpha2 = "99",
    .reg_rules = { 
            RTL819x_2GHZ_CH01_11,
            RTL819x_5GHZ_5150_5350,
            RTL819x_5GHZ_5470_5850,
              }
};`

Still no joy with creating a 5ghz AP, 2.4Ghz still works fine.

I have set

`cfg80211_regdom=GB` 

and 

`iw reg set GB`

I have also set all values mentioned to US(FCC) (before i made any source modifications) as i have seen reports of sucessful 5Ghz AP being created on cards used in the States but this didn't work either.

Not sure how usefull this will be but I can create 5Ghz AP's using this driver [http://www.edimax.com/edimax/mw/cufiles/files/download/Driver_Utility/EW-7822PIC_Linux_Driver_v1.0.0.3.zip](url)
i hade to modify it  get it to compile on a 4.5 kernel, though in general the driver is useless.

"cat hostapd.conf"

> interface=wlan0
> driver=nl80211
> bridge=br0
> ssid=test
> hw_mode=a
> channel=36

"dmesg | grep rtl"

> [ 3983.320603] Using firmware rtlwifi/rtl8812aefw.bin
> [ 3983.320786] rtlwifi: channel plan 0x25
> [ 3983.320791] rtlwifi: country code 2
> [ 3983.320974] rtl8821ae 0000:01:00.0: firmware: direct-loading firmware rtlwifi/rtl8812aefw.bin
> [ 3983.325572] ieee80211 phy0: Selected rate control algorithm 'rtl_rc'
> [ 3983.328064] rtlwifi: wireless switch is on

"iw phy"

> Wiphy phy0
>         max # scan SSIDs: 4
>         max scan IEs length: 2243 bytes
>         RTS threshold: 2347
>         Retry short limit: 7
>         Retry long limit: 4
>         Coverage class: 0 (up to 0m)
>         Device supports RSN-IBSS.
>         Supported Ciphers:
>                 \* WEP40 (00-0f-ac:1)
>                 \* WEP104 (00-0f-ac:5)
>                 \* TKIP (00-0f-ac:2)
>                 \* CCMP (00-0f-ac:4)
>                 \* 00-0f-ac:10
>                 \* GCMP (00-0f-ac:8)
>                 \* 00-0f-ac:9
>                 \* CMAC (00-0f-ac:6)
>                 \* 00-0f-ac:13
>                 \* 00-0f-ac:11
>                 \* 00-0f-ac:12
>         Available Antennas: TX 0 RX 0
>         Supported interface modes:
>                  \* IBSS
>                  \* managed
>                  \* AP
>                  \* AP/VLAN
>                  \* monitor
>                  \* mesh point
>                  \* P2P-client
>                  \* P2P-GO
>         Band 1:
>                 Capabilities: 0x1862
>                         HT20/HT40
>                         Static SM Power Save
>                         RX HT20 SGI
>                         RX HT40 SGI
>                         No RX STBC
>                         Max AMSDU length: 7935 bytes
>                         DSSS/CCK HT40
>                 Maximum RX AMPDU length 65535 bytes (exponent: 0x003)
>                 Minimum RX AMPDU time spacing: 16 usec (0x07)
>                 HT TX/RX MCS rate indexes supported: 0-15, 32
>                 Bitrates (non-HT):
>                         \* 1.0 Mbps
>                         \* 2.0 Mbps
>                         \* 5.5 Mbps
>                         \* 11.0 Mbps
>                         \* 6.0 Mbps
>                         \* 9.0 Mbps
>                         \* 12.0 Mbps
>                         \* 18.0 Mbps
>                         \* 24.0 Mbps
>                         \* 36.0 Mbps
>                         \* 48.0 Mbps
>                         \* 54.0 Mbps
>                 Frequencies:
>                         \* 2412 MHz [1](20.0 dBm)
>                         \* 2417 MHz [2](20.0 dBm)
>                         \* 2422 MHz [3](20.0 dBm)
>                         \* 2427 MHz [4](20.0 dBm)
>                         \* 2432 MHz [5](20.0 dBm)
>                         \* 2437 MHz [6](20.0 dBm)
>                         \* 2442 MHz [7](20.0 dBm)
>                         \* 2447 MHz [8](20.0 dBm)
>                         \* 2452 MHz [9](20.0 dBm)
>                         \* 2457 MHz [10](20.0 dBm)
>                         \* 2462 MHz [11](20.0 dBm)
>                         \* 2467 MHz [12](20.0 dBm)
>                         \* 2472 MHz [13](20.0 dBm)
>                         \* 2484 MHz [14](disabled)
>         Band 2:
>                 Capabilities: 0x1862
>                         HT20/HT40
>                         Static SM Power Save
>                         RX HT20 SGI
>                         RX HT40 SGI
>                         No RX STBC
>                         Max AMSDU length: 7935 bytes
>                         DSSS/CCK HT40
>                 Maximum RX AMPDU length 65535 bytes (exponent: 0x003)
>                 Minimum RX AMPDU time spacing: 16 usec (0x07)
>                 HT TX/RX MCS rate indexes supported: 0-15, 32
>                 VHT Capabilities (0x33c019a3):
>                         Max MPDU length: (reserved)
>                         Supported Channel Width: neither 160 nor 80+80
>                         short GI (80 MHz)
>                         TX STBC
>                         SU Beamformer
>                         SU Beamformee
>                         +HTC-VHT
>                         RX antenna pattern consistency
>                         TX antenna pattern consistency
>                 VHT RX MCS set:
>                         1 streams: MCS 0-9
>                         2 streams: MCS 0-9
>                         3 streams: not supported
>                         4 streams: not supported
>                         5 streams: not supported
>                         6 streams: not supported
>                         7 streams: not supported
>                         8 streams: not supported
>                 VHT RX highest supported: 867 Mbps
>                 VHT TX MCS set:
>                         1 streams: MCS 0-9
>                         2 streams: MCS 0-9
>                         3 streams: not supported
>                         4 streams: not supported
>                         5 streams: not supported
>                         6 streams: not supported
>                         7 streams: not supported
>                         8 streams: not supported
>                 VHT TX highest supported: 867 Mbps
>                 Bitrates (non-HT):
>                         \* 6.0 Mbps
>                         \* 9.0 Mbps
>                         \* 12.0 Mbps
>                         \* 18.0 Mbps
>                         \* 24.0 Mbps
>                         \* 36.0 Mbps
>                         \* 48.0 Mbps
>                         \* 54.0 Mbps
>                 Frequencies:
>                         \* 5180 MHz [36](20.0 dBm)
>                         \* 5200 MHz [40](20.0 dBm)
>                         \* 5220 MHz [44](20.0 dBm)
>                         \* 5240 MHz [48](20.0 dBm)
>                         \* 5260 MHz [52](20.0 dBm) (no IR, radar detection)
>                           DFS state: usable (for 3301 sec)
>                           DFS CAC time: 60000 ms
>                         \* 5280 MHz [56](20.0 dBm) (no IR, radar detection)
>                           DFS state: usable (for 3301 sec)
>                           DFS CAC time: 60000 ms
>                         \* 5300 MHz [60](20.0 dBm) (no IR, radar detection)
>                           DFS state: usable (for 3301 sec)
>                           DFS CAC time: 60000 ms
>                         \* 5320 MHz [64](20.0 dBm) (no IR, radar detection)
>                           DFS state: usable (for 3301 sec)
>                           DFS CAC time: 60000 ms
>                         \* 5500 MHz [100](27.0 dBm) (no IR, radar detection)
>                           DFS state: usable (for 3301 sec)
>                           DFS CAC time: 60000 ms
>                         \* 5520 MHz [104](27.0 dBm) (no IR, radar detection)
>                           DFS state: usable (for 3301 sec)
>                           DFS CAC time: 60000 ms
>                         \* 5540 MHz [108](27.0 dBm) (no IR, radar detection)
>                           DFS state: usable (for 3301 sec)
>                           DFS CAC time: 60000 ms
>                         \* 5560 MHz [112](27.0 dBm) (no IR, radar detection)
>                           DFS state: usable (for 3301 sec)
>                           DFS CAC time: 60000 ms
>                         \* 5580 MHz [116](27.0 dBm) (no IR, radar detection)
>                           DFS state: usable (for 3301 sec)
>                           DFS CAC time: 60000 ms
>                         \* 5600 MHz [120](27.0 dBm) (no IR, radar detection)
>                           DFS state: usable (for 3301 sec)
>                           DFS CAC time: 60000 ms
>                         \* 5620 MHz [124](27.0 dBm) (no IR, radar detection)
>                           DFS state: usable (for 3301 sec)
>                           DFS CAC time: 60000 ms
>                         \* 5640 MHz [128](27.0 dBm) (no IR, radar detection)
>                           DFS state: usable (for 3301 sec)
>                           DFS CAC time: 60000 ms
>                         \* 5660 MHz [132](27.0 dBm) (no IR, radar detection)
>                           DFS state: usable (for 3301 sec)
>                           DFS CAC time: 60000 ms
>                         \* 5680 MHz [136](27.0 dBm) (no IR, radar detection)
>                           DFS state: usable (for 3301 sec)
>                           DFS CAC time: 60000 ms
>                         \* 5700 MHz [140](27.0 dBm) (no IR, radar detection)
>                           DFS state: usable (for 3301 sec)
>                           DFS CAC time: 60000 ms
>                         \* 5745 MHz [149](disabled)
>                         \* 5765 MHz [153](disabled)
>                         \* 5785 MHz [157](disabled)
>                         \* 5805 MHz [161](disabled)
>                         \* 5825 MHz [165](disabled)
>         Supported commands:
>                  \* new_interface
>                  \* set_interface
>                  \* new_key
>                  \* start_ap
>                  \* new_station
>                  \* new_mpath
>                  \* set_mesh_config
>                  \* set_bss
>                  \* authenticate
>                  \* associate
>                  \* deauthenticate
>                  \* disassociate
>                  \* join_ibss
>                  \* join_mesh
>                  \* remain_on_channel
>                  \* set_tx_bitrate_mask
>                  \* frame
>                  \* frame_wait_cancel
>                  \* set_wiphy_netns
>                  \* set_channel
>                  \* set_wds_peer
>                  \* probe_client
>                  \* set_noack_map
>                  \* register_beacons
>                  \* start_p2p_device
>                  \* set_mcast_rate
>                  \* Unknown command (104)
>                  \* connect
>                  \* disconnect
>         Supported TX frame types:
>                  \* IBSS: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
>                  \* managed: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
>                  \* AP: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
>                  \* AP/VLAN: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
>                  \* mesh point: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
>                  \* P2P-client: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
>                  \* P2P-GO: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
>                  \* P2P-device: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
>         Supported RX frame types:
>                  \* IBSS: 0x40 0xb0 0xc0 0xd0
>                  \* managed: 0x40 0xd0
>                  \* AP: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
>                  \* AP/VLAN: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
>                  \* mesh point: 0xb0 0xc0 0xd0
>                  \* P2P-client: 0x40 0xd0
>                  \* P2P-GO: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
>                  \* P2P-device: 0x40 0xd0
>         WoWLAN support:
>                  \* wake up on magic packet
>                  \* wake up on pattern match, up to 16 patterns of 13-128 bytes,
>                    maximum packet offset 0 bytes
>         software interface modes (can always be added):
>                  \* AP/VLAN
>                  \* monitor
>         interface combinations are not supported
>         HT Capability overrides:
>                  \* MCS: ff ff ff ff ff ff ff ff ff ff
>                  \* maximum A-MSDU length
>                  \* supported channel width
>                  \* short GI for 40 MHz
>                  \* max A-MPDU length exponent
>                  \* min MPDU start spacing
>         Device supports TX status socket option.
>         Device supports HT-IBSS.
>         Device supports SAE with AUTHENTICATE command
>         Device supports low priority scan.
>         Device supports scan flush.
>         Device supports AP scan.
>         Device supports per-vif TX power setting
>         Driver supports full state transitions for AP/GO clients
>         Driver supports a userspace MPM

**Comment by qiyuey** [comment]
me too

**Comment by lwfinger** [comment]
These drivers only use the regulatory info from cfg80211 in a limited way. Changing the rule to GB can never enable 5 GHz if regd.c is not properly set.

@qiyuey: "me too" tells me nothing other than to ignore your postings.

**Comment by okiura** [comment]
Hi thanks for your responce, 

Please see my 1st post, i have edited regd.c to include my cards country code (0x25) as this was not in the origional file, i have also added  `static const struct ieee80211_regdomain rtl_regdom_etsi` (as `iw reg get` Shows GB as ETSI) with what I beleive is the valid ETSI bands.

my cards conutny code (0x25) is now found by the driver and the correct bands are enabled.

My problem isn't enabling 5Ghz i can see other 5Ghz AP's. my issue is if a create one with host AP other devices cannot see it or connect to it. 

here is copy of my modified regd.c file. a full list of the changes i made are in my 1st post.

[regd.zip](https://github.com/lwfinger/rtlwifi_new/files/425885/regd.zip)

**Comment by lwfinger** [comment]
I am adding country code 0x25. There is no need to define a new ieee80211_regdomain as ETSI is the same as France.

I have no idea why the 5G part of the 8821ae cannot make an AP. I will look at that.

**Comment by okiura** [comment]
Ok, if you require any more information i will be happy to provide

Thanks

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
