### ISSUE TITLE
Possible Errors in code

### ISSUE THREAD

**Issue by jshand2015** [lwfinger/rtlwifi_new#143]
please be aware that these below code issues do not interfere with the build process

/home/jshand/rtlwifi/rtl8192ee/hw.c: In function ‘rtl92ee_set_hw_reg’:
/home/jshand/rtlwifi/rtl8192ee/hw.c:538:4: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
    if (fac > 0xf)
    ^~
/home/jshand/rtlwifi/rtl8192ee/hw.c:540:5: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
     for (i = 0; i < 4; i++) {
     ^~~
/home/jshand/rtlwifi/rtl8192ee/hw.c:544:6: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
      if ((reg[i] & 0x0f) > fac)
      ^~
/home/jshand/rtlwifi/rtl8192ee/hw.c:546:7: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
       rtl_write_byte(rtlpriv,
       ^~~~~~~~~~~~~~
/home/jshand/rtlwifi/rtl8192ee/hw.c: In function ‘_rtl92ee_read_adapter_info’:
/home/jshand/rtlwifi/rtl8192ee/hw.c:2138:14: warning: logical not is only applied to the left hand side of comparison [-Wlogical-not-parentheses]
  if (!hwinfo == true)
              ^~

/home/jshand/rtlwifi/rtl8723ae/hw.c: In function ‘_rtl8723e_read_adapter_info’:
/home/jshand/rtlwifi/rtl8723ae/hw.c:1635:14: warning: logical not is only applied to the left hand side of comparison [-Wlogical-not-parentheses]
  if (!hwinfo == true)
              ^~

/home/jshand/rtlwifi/rtl8821ae/dm.c: In function ‘rtl8821ae_dm_txpower_tracking_callback_thermalmeter’:
/home/jshand/rtlwifi/rtl8821ae/dm.c:2764:3: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
   for (p = RF90_PATH_A; p < MAX_PATH_NUM_8821A; p++)
   ^~~
/home/jshand/rtlwifi/rtl8821ae/dm.c:2767:4: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘for’
    RT_TRACE(rtlpriv, COMP_POWER_TRACKING, DBG_LOUD,
    ^~~~~~~~

**Comment by lwfinger** [comment]
Those are NOT errors, only incorrect indentations. The generated code is correct. I will fix them, but you can ignore these WARNINGS until that happens.

**Comment by jshand2015** [comment]
found one more for you:

/home/jshand/rtlwifi/rtl8192ee/hw.c: In function ‘rtl92ee_set_hw_reg’:
/home/jshand/rtlwifi/rtl8192ee/hw.c:544:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
     if ((reg[i] & 0x0f) > fac)
     ^~
/home/jshand/rtlwifi/rtl8192ee/hw.c:546:6: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
      rtl_write_byte(rtlpriv,
      ^~~~~~~~~~~~~~

many thanks for your hard work
