### ISSUE TITLE
rtl8821ae not working properly in Ubuntu 16.04 and Debian 8.5 

### ISSUE THREAD

**Issue by gokyo** [lwfinger/rtlwifi_new#144]
I just bought this laptop: Lenovo 15.6 Inch Ideapad 110 AMD A8 A8 7410 8GB.
I spent the whole day trying to make my wireless card working on Linux.
Tried two distributions: Ubuntu 16.04 and Debian 8.5
In Ubuntu, it works, but then it drops down after a while. 
In Debian the connection was very very slow.
I tried few things after surfing in the web.
Tried also `rtlwifi_new`, but with no luck :(
Any hint?
I can provide more details (things I tried, logs, etc) if needed.

**Comment by lwfinger** [comment]
What options did you try?

**Comment by gokyo** [comment]
Too many :) 
I was trying anything I could find in the web.
I do not have time to list all of them now, but I could maybe tomorrow or next days.

This is one of the many pages I came across: 
http://askubuntu.com/questions/730430/wifi-connection-keeps-dropping-in-ubuntu-15-10-rtl8821ae 

I created the file _/etc/modprobe.d/rtl8821ae.conf_ and then played (setting 0 or 1) the options (the ones mentioned in the webpage above) in many ways, modifying on-the-fly the file and testing the connection by removing and adding back the module:
> modprobe -r rlt8821ae
> modprobe rlt8821ae

But no luck :)

**Comment by gokyo** [comment]
I installed Ubuntu again on my laptop, but this time an old version: 14.04.1 (the Linux kernel is 3.19.0-66-generic).
This time the wireless connection seems working fine so far, even without installing `rtlwifi_new`.
So, I believe it is a problem in the latest versions of Ubuntu, because they are using the new Linux kernel).

**Comment by gokyo** [comment]
On Ubuntu 14.04.1 the wireless connection seems working fine after having run:
`echo "options rtl8821ae swenc=1 ips=0 fwlps=0" | sudo tee /etc/modprobe.d/rtl8821ae.conf`

**Comment by lwfinger** [comment]
A couple of comments: When you turn off power saving with ips=0, then neither fwlps or swlps are used. Adding them does not hurt.

Do you really need swenc=1? If so, that implies a firmware failure that I would like to know about.

**Comment by gokyo** [comment]
Thanks for the two comments.
I will try with just` ips=0` and see what happens.
I will keep you updated.

**Comment by kenzolo** [comment]
any news?
same issue here using rtl8821ae :(

**Comment by gokyo** [comment]
I tried different things, but I wasn't able to find a solution that made the wi-fi network workng well for long. 
And I have been busy with other things (using another laptp), so I did not follow this issue recently...

**Comment by renejesusgv** [comment]
I have this laptop too, although I have tried with several configurations I cant find a final solution. I hope that soon there is any solution

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.

**Comment by RobinxiangbinNie** [comment]
I am regretful to say that I met the same issue when change into my new ASUS laptop (powerful one). It seems the rtl8821ae wifi problem still not solved even pulled the latest drivers here:-(. Any new solution on this issue..........

**Comment by kollokollo** [comment]
I have the same issue with Ubuntu 17.04 and a lenovo ideapad 110S.
The failure can be triggered using git to upload(!) a big file. Then the connection is lost but can be reconnected after a while.

**Comment by ashish45d** [comment]
I am also having lenovo ideapad 110.  WIFI connection is continuously dropping after sometime of system start.

**Comment by ashish45d** [comment]
is there is any workaround to fix this issue. else which version of ubuntu I can use for proper working?

**Comment by paulsinnett** [comment]
Have you tried using wicd instead of network manager. That "fixed" it for me on Ubuntu / Mint. (The connection problems didn't go away, but it was able to recover by itself after a connection drop.)

**Comment by gauravssnl** [comment]
i am also using Ubuntu OS v16.04.02 and my laptop has rtl8723be wireless adapter and  I was also experiencing  problem that  system failed to failed  many wifi networks due to low signal.But, rtlwifi worked for me and now i can easily use wifi and there is no low wifi signal issue . Thanks a lot to @lwfinger

**Comment by ashish45d** [comment]
Hi,

Can u please suggest how to use rtlwifi.

Regards,
Ashish

On 23-Jun-2017 4:55 PM, "GAURAV SINGH" <notifications@github.com> wrote:

i am also using Ubuntu OS v16.04.02 and my laptop has rtl8723be wireless
adapter and I was also experiencing problem that system failed to failed
many wifi networks due to low signal.But, rtlwifi worked for me and now i
can easily use wifi and there is no low wifi signal issue . Thanks a lot to
@lwfinger <https://github.com/lwfinger>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/lwfinger/rtlwifi_new/issues/144#issuecomment-310641682>,
or mute the thread

**Comment by gauravssnl** [comment]
i have written how to use rtlwifi_new  step-by-step tutorial on my blog .Have a look at it : https://gauravssnl.wordpress.com/2017/06/18/how-to-fix-realtek-rtl8723be-wireless-network-adapter-low-wi-fi-signal-issue-on-ubuntulinux-os/
Which Realtek Wireless Adapter you have ????  @ashish45d

**Comment by ashish45d** [comment]
finally after installing wicd and upgrading kernal to 4.6, wifi is working satisfactory. although it disconnet but connects automatically. thanks a lot. 
Please update if any proper solution is found

**Comment by paulsinnett** [comment]
I think the fixes are already in the newer kernels. At least my Manjaro install has a 4.9 kernel and doesn't suffer this inability to re-connect, at least not as frequently.

**Comment by ashish45d** [comment]
@paulsinnett Thanks, today I will try to install kernal 4.10 in mint. In Manjaro you are using wicd + kernal 4.9 or default NM + Kernal 4.9

**Comment by paulsinnett** [comment]
I am using the stock install of Manjaro which uses NetworkManager v 1.8.2.

**Comment by alvgarvilla** [comment]
I have the same problem... I have tried with Ubuntu 16, Debian 9 and now I have installed Ubuntu 17 with 4.10 kernel version... Every time I try to upload files (git, docker, google drive...) the Internet connection drops for 5 minutes.

**Comment by lucabala** [comment]
After I've installed WICD the wifi conection is more stable, but if I intensely use the wifi conection (for example, a bit torrent application, large download), it drops and I can't restabilish it.

**Comment by andymnc** [comment]
same issue here. kde neon 5.10.x, kde neon 5.11.0, ubuntu 16.04, ubuntu 16.10, ubuntu 17.04. connection drops after few minutes, some times it's not reconnecting till i reboot (no restart to the networking service is usefull)- driver rtl8821ae.
none of the proposed solution worked for me.
the laptop is an asus one.
can u solve this please?

**Comment by cryptid11** [comment]
As an extreme solution i tru fedora and at least on 4.8.6-300.fc25.x86_64
it works!
I will try to move back to debian as soon as I have the time.

**Comment by riper384** [comment]
I have the same problem on ububtu's ones as @andymnc. Help pls

**Comment by gj12** [comment]
Lenovo V110-15AST with Kernel 4.13.0.21-generic under Ubuntu 17.10 has the same issue. Is there a way to debug this?

**Comment by alexeymuranov** [comment]
Lenovo ideapad 310 with RTL8821AE under Linux Mint 18.3 was not initially connecting to WiFi at all.  After installing all updates (as of 2018-02-10), WiFi started connecting without problems, but the download speed was quickly dropping to about 80Kb/s, about 3-5 times slower than when using to the same wireless network from another laptop.

**Comment by caperutxa** [comment]
The same issue with Lenovo ideapad 310 and Ubuntu 18.04
