### ISSUE TITLE
Can't get it to compile on Fedora 24.

### ISSUE THREAD

**Issue by Freddan801** [lwfinger/rtlwifi_new#145]
Hi all.

I recently installed Fedora 24 on my laptop (HP Pavilion, using the rtl8723be chipset but can't get the module to compile on this installation. I should say that I'm rather new to GNU/Linux and even more of a beginner with Fedora.

This is the error-message i got when running 'make':
`[Freddan@ua-85-224-134-239 rtlwifi_new]$ make
make -C /lib/modules/4.6.6-300.fc24.x86_64/build M=/home/Freddan/rtlwifi_new modules
make[1]: Entering directory '/usr/src/kernels/4.6.6-300.fc24.x86_64'
  CC [M]  /home/Freddan/rtlwifi_new/rtl8192ee/hw.o
/home/Freddan/rtlwifi_new/rtl8192ee/hw.c: In function ‘rtl92ee_set_hw_reg’:
/home/Freddan/rtlwifi_new/rtl8192ee/hw.c:539:4: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
    if (fac > 0xf)
    ^~
/home/Freddan/rtlwifi_new/rtl8192ee/hw.c:541:5: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
     for (i = 0; i < 4; i++) {
     ^~~
/home/Freddan/rtlwifi_new/rtl8192ee/hw.c:545:6: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
      if ((reg[i] & 0x0f) > fac)
      ^~
/home/Freddan/rtlwifi_new/rtl8192ee/hw.c:547:7: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
       rtl_write_byte(rtlpriv,
       ^~~~~~~~~~~~~~
cc1: all warnings being treated as errors
scripts/Makefile.build:291: recipe for target '/home/Freddan/rtlwifi_new/rtl8192ee/hw.o' failed
make[3]: *** [/home/Freddan/rtlwifi_new/rtl8192ee/hw.o] Error 1
scripts/Makefile.build:440: recipe for target '/home/Freddan/rtlwifi_new/rtl8192ee' failed
make[2]: *** [/home/Freddan/rtlwifi_new/rtl8192ee] Error 2
Makefile:1433: recipe for target '_module_/home/Freddan/rtlwifi_new' failed
make[1]: *** [_module_/home/Freddan/rtlwifi_new] Error 2
make[1]: Leaving directory '/usr/src/kernels/4.6.6-300.fc24.x86_64'
Makefile:58: recipe for target 'all' failed
make: *** [all] Error 2
[Freddan@ua-85-224-134-239 rtlwifi_new]$ 
`
I really hope someone out i willing and able to help cause I have had nothing but bad luck with my new laptop and GNU/Linux ever since I got this computer a couple of weeks ago. Thanks.

/Fredrik

**Comment by lwfinger** [comment]
Have you done a 'git pull'. A number of these warnings were fixed already.

Who set your compiler to regard all warnings as errors? That is a huge mistake!

**Comment by Freddan801** [comment]
Hi lwfinger and thx for the fast replay.

I did a pull just a minute or so before trying to run the 'make' command. 
I have no clue who set the compiler but it must be the maintainer of the package itsrelf cause I haven't tinkered with it one bit and wouldn't even have a clue how to :). Do ypu know how to reverse it? Thx.

**Comment by lwfinger** [comment]
What branch are you running?

**Comment by Freddan801** [comment]
I haven't changed branch so I believe I'm using main. I haven't used git all that much and when I have I have more or less only used tutorials.

**Comment by lwfinger** [comment]
Why are you even using this repo? Kernel 4.6.6 has everything found in the main branch. If you are doing it because some web site told you to do it, do you believe everything you read?

**Comment by Freddan801** [comment]
Yeah, I read that 4.6.6 should have the ant_sel fixed and that were one of the reason I wanted to try out Fedora after messing with Ubuntu for awhile (your module compiled fine under Ubuntu Gnome). 

I have no clue what the Fedora guys have done with their kernel but it doesn't work with at last my 8723be chipset. I have made your 50-rtl.comf file and have placed it in both /etc/modprobe.d and In /usr/lib/modprobe.d but nothing has worked. and I still don't have wifi.

**Comment by lwfinger** [comment]
You can see if the driver has the ant_sel feature by using the command 'modinfo rtl8723be'. You can check your options file with

sudo modprobe -rv rtl8723be
sudo modprobe -v rtl8723be

**Comment by Freddan801** [comment]
Yeah, you are right. It seems that your fix is already installed with the kernel. 

`[root@ua-85-224-134-239 Freddan]# sudo modprobe -rv rtl8723be
rmmod rtl8723be
rmmod rtl_pci
rmmod rtlwifi
rmmod mac80211
rmmod cfg80211
rmmod rtl8723_common
rmmod btcoexist
[root@ua-85-224-134-239 Freddan]# sudo modprobe -v rtl8723be
insmod /lib/modules/4.6.6-300.fc24.x86_64/kernel/net/wireless/cfg80211.ko.xz 
insmod /lib/modules/4.6.6-300.fc24.x86_64/kernel/net/mac80211/mac80211.ko.xz 
insmod /lib/modules/4.6.6-300.fc24.x86_64/kernel/drivers/net/wireless/realtek/rtlwifi/rtlwifi.ko.xz 
insmod /lib/modules/4.6.6-300.fc24.x86_64/kernel/drivers/net/wireless/realtek/rtlwifi/rtl_pci.ko.xz 
insmod /lib/modules/4.6.6-300.fc24.x86_64/kernel/drivers/net/wireless/realtek/rtlwifi/rtl8723com/rtl8723-common.ko.xz 
insmod /lib/modules/4.6.6-300.fc24.x86_64/kernel/drivers/net/wireless/realtek/rtlwifi/btcoexist/btcoexist.ko.xz 
insmod /lib/modules/4.6.6-300.fc24.x86_64/kernel/drivers/net/wireless/realtek/rtlwifi/rtl8723be/rtl8723be.ko.xz ips=0 ant_sel=2 
[root@ua-85-224-134-239 Freddan]# 
`
Still cant get my wifi to start but this issue seems to be a pure Fedora problem though.

Going to bed now but if upu have any ideas of what could be wrong I would appreciate very much. Thanks for all the help!

/Fredrik

**Comment by jamesarbrown** [comment]
A HP Pavilion 455G2 works out of the box with Fedora using this
/etc/modprobe.d/rtl8723be.conf
options rtl8723be msi=0 ips=0 fwlps=0 swenc=1

**Comment by Freddan801** [comment]
After reading your comment I had to install Fedora again but your conf-file doesn't work for me. I really wanted to revisit the world of Fedora but to no avail , it's back to Debian for me.

**Comment by lwfinger** [comment]
What kernel version was in Fedora. If you typed the conf file correctly and your kernel is new enough, it should have worked.

**Comment by Freddan801** [comment]
A Fedora vanilla install are at kernel 4.5.* but after doing a dnf update I believe Fedora are at 4.7.* so your fix should be in there but somehow it doesn't work for me under Fedora.

**Comment by lwfinger** [comment]
OK. Without a detailed description of any error, I cannot help. Perhaps Fedora's user space is messed up.

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
