### ISSUE TITLE
rtl8192ee error

### ISSUE THREAD

**Issue by jshand2015** [lwfinger/rtlwifi_new#147]
/home/jshand/rtlwifi/rtl8192ee/pwrseqcmd.o: warning: objtool: rtl_hal_pwrseqcmdparsing()+0x109: function has unreachable instruction

**Comment by deveshmehra** [comment]
Hey jshand2015 try to compile the new code ,as the there is removal of dead code from pwrseqcmd.c 3 months ago . It might be helpful for you

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
