### ISSUE TITLE
rtl8188eu cannot spoof mac address

### ISSUE THREAD

**Issue by linuxista** [lwfinger/rtlwifi_new#150]
I have a new Alfa awus034nhv with the rtl8188eu chipset. The firmware and kernel driver you provide seem to work correctly, but the chip is resistant to changing the mac address. I don't know if Realtek burned it into the chip and it is impossible to change, or if the driver or firmware just lacks that capability. If it's the latter case, inserting some code that would allow for mac address changing would be a huge plus and much appreciated. (For me the card is basically a brick without it.)

**Comment by migueldvb** [comment]
@linuxista creating a `.conf` file under `/etc/modprobe.d/` and adding a line like this seems to work:

`options r8188eu rtw_initmac="XX:XX:XX:XX:XX:XX"`

**Comment by bertandzobrist** [comment]
> @linuxista creating a `.conf` file under `/etc/modprobe.d/` and adding a line like this seems to work:
> 
> `options r8188eu rtw_initmac="XX:XX:XX:XX:XX:XX"`

Brother can you please elaborate this what .conf is it rtl8188eu.conf ? and should we put the mac in exactly "XX:XX:XX:XX:XX:XX" or "12:34:56:78:90:01" this way.
Thank You
