### ISSUE TITLE
License

### ISSUE THREAD

**Issue by TvoroG** [lwfinger/rtlwifi_new#151]
Hi! Thanks for drivers! Can you say which license do you use? I see `rtlwifi_new/firmware` has own license. What about the rest of the code?

**Comment by TvoroG** [comment]
I just wanted to make package for nix and it needs license.

**Comment by lwfinger** [comment]
All Linux kernel code is licensed GPLV2. As the source for the firmware is not released, its license is different; however, it is licensed as freely redistributable.

**Comment by TvoroG** [comment]
Thanks!
