### ISSUE TITLE
Wifi not detecting after upgrading to Ubuntu 16.10 Yakkety

### ISSUE THREAD

**Issue by sudeeshr** [lwfinger/rtlwifi_new#155]
HP Laptop with Realtek rtl8723be adapter

```
root@sudeesh-HP:/home/sudeesh# iwconfig
wlp13s0   IEEE 802.11  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=20 dBm   
          Retry short limit:7   RTS thr=2347 B   Fragment thr:off
          Encryption key:off
          Power Management:off
          
enp7s0    no wireless extensions.

lo        no wireless extensions.
```
E: The repository 'http://ppa.launchpad.net/hanipouspilot/rtlwifi/ubuntu yakkety Release' does not have a Release file.

**Comment by lwfinger** [comment]
I have no idea what kernel is in Ubuntu 16.10; however, I do know that under all openSUSE releases, the RTL8723BE works. Thus the problem is something with Ubuntu, probably the network control software. As far as I know, there is nothing for me to fix.

**Comment by sudeeshr** [comment]
ok..thanks..current kernel version - 4.8.0-22-generic

**Comment by lwfinger** [comment]
Check the dmesg output to see if there is a problem there.

**Comment by sudeeshr** [comment]
Some of the output of dmesg 
[dmesg-output.txt](https://github.com/lwfinger/rtlwifi_new/files/531266/dmesg-output.txt)
-

[    3.358497] r8169 0000:07:00.0 enp7s0: renamed from eth0
[    3.363604] [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
[    3.363605] [drm] Driver supports precise vblank timestamp query.
[    3.366256] vgaarb: device changed decodes: PCI:0000:00:02.0,olddecodes=io+mem,decodes=io+mem:owns=io+mem
[    3.404825] [drm:intel_dp_start_link_train [i915]] *ERROR* failed to update link training

[   15.430589] rtl8723be: Using firmware rtlwifi/rtl8723befw.bin
[   15.511864] ieee80211 phy0: Selected rate control algorithm 'rtl_rc'
[   15.512085] rtlwifi: rtlwifi: wireless switch is on
[   15.616528] rtl8723be 0000:0d:00.0 wlp13s0: renamed from wlan0
[   15.724694] kvm: disabled by bios

[ 1714.795323] rtl8723be: Using firmware rtlwifi/rtl8723befw.bin
[ 1714.797401] ieee80211 phy0: Selected rate control algorithm 'rtl_rc'
[ 1714.798760] rtlwifi: rtlwifi: wireless switch is on
[ 1714.801745] rtl8723be 0000:0d:00.0 wlp13s0: renamed from wlan0
[ 1714.830838] IPv6: ADDRCONF(NETDEV_UP): wlp13s0: link is not ready
[ 1715.312856] IPv6: ADDRCONF(NETDEV_UP): wlp13s0: link is not ready
[ 1715.368694] IPv6: ADDRCONF(NETDEV_UP): wlp13s0: link is not ready
[ 2674.274188] r8169 0000:07:00.0 enp7s0: link down
[ 2691.589742] r8169 0000:07:00.0 enp7s0: link up
[ 2691.910689] r8169 0000:07:00.0 enp7s0: link down

**Comment by lwfinger** [comment]
No error there. It seems to be as I stated earlier.

**Comment by sudeeshr** [comment]
ok..thanks

**Comment by lwfinger** [comment]
I cannot install Ubuntu, but I did run Ubuntu Live. It found the RTL8723BE just fine and connected "out of the box". Are you using NetworkManager.

With kernel 4.8, there is no need to use this repo. The kernel drivers are the same.
