### ISSUE TITLE
State of RTL8723be driver in current linux kernel

### ISSUE THREAD

**Issue by thelarabi** [lwfinger/rtlwifi_new#157]
Hello,

I wanted to know what the state of this driver is in the current linux kernel.
My ThinkPad has this wifi card with two antennas, will it work out of the box with Ubuntu 16.10 and kernel 4.8?

Can you maybe keep us up to date how things are going? Did the latest kernel adopt the bug fixes for antenna selection?

Thank you very much.

**Comment by lwfinger** [comment]
I have stated several times in various issues in this repo that the kernel contains the code necessary to handle the cases where only ONE antenna is connected, AND the vendor has misprogrammed the EEPROM. Kernel4.8 has all the changes for these drivers.

With TWO antennas, the whole point is moot.

**Comment by thelarabi** [comment]
So with two antennas there is no problem at all in the first place? Sorry, my bad. Keep up the good work.
