### ISSUE TITLE
rtl8723b_config.bin ? 

### ISSUE THREAD

**Issue by MrOutput** [lwfinger/rtlwifi_new#158]
I cannot find the `rtl8723b_config.bin` in `/libs/firmware` or in this repo. this is an error?

```
[    2.403741] Bluetooth: hci0: rtl: examining hci_ver=06 hci_rev=000b lmp_ver=06 lmp_subver=8723
[    2.403748] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723b_config.bin
[    2.403831] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723b_config.bin failed with error -2
[    2.403839] Bluetooth: hci0: Failed to load rtl_bt/rtl8723b_config.bin
[    2.403844] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723b_fw.bin
[    2.405580] Bluetooth: hci0: rom_version status=0 version=1
[    2.405616] Bluetooth: cfg_sz 0, total size 22496
```

**Comment by lwfinger** [comment]
It is not an error. The latest Realtek BT device needs a "patch" file for the firmware. When the code to load that file was added, the hooks that might be needed in the future were added at the same time. Nothing is wrong as the BT part of the RTL8723BE does not need such a file.

**Comment by MrOutput** [comment]
ah okay, thanks a lot Larry! Have a great weekend

**Comment by danyer** [comment]
Hi Larry, thanks for the driver! One question though? If this not an error, could it be logged as a warning? With kernel 4.9 it seems like all errors are displayed also on console, instead of going only in journal.

Thanks,
Dan.

**Comment by lwfinger** [comment]
That BT_ERR() should have been BT_INFO(). Rather than making that change, I have proposed a change that will only print a missing config file message only if the driver needs such a file. At the moment, only the RTL8822B needs such a file, and I do not think it has been released yet. In any case, the code will be changed soon.

**Comment by danyer** [comment]
Your proposal sounds even better. I will patiently wait. Have a nice weekend!
