### ISSUE TITLE
Makefile - depmod -a -> depmod -a $(KVER)

### ISSUE THREAD

**Issue by thx1111** [lwfinger/rtlwifi_new#161]
For "make install", in the Makefile, add the kernel version to the "depmod" command:
 depmod -a -> depmod -a $(KVER)

**Comment by lwfinger** [comment]
What are the circumstances that this is needed?

**Comment by thx1111** [comment]
I upgraded the kernel, and wanted the wifi module to be available when the system rebooted with the new kernel.  I ran "KVER=4.8.7-1-ARCH make" and then "sudo KVER=4.8.7-1-ARCH make install".

Without the "depmod -a $(KVER)", the install fails with an error when depmod tries to read the new modules from the old modules directory.  The depmod man page says:
"If a version is provided, then that kernel version's module directory is used rather than the current kernel version (as returned by uname -r)."

**Comment by thx1111** [comment]
This has been applied.
Thanks!
