### ISSUE TITLE
Compile on KALI

### ISSUE THREAD

**Issue by grisutheguru** [lwfinger/rtlwifi_new#164]
Ahoi!

I pulled the latest  version and try to compile it on KALI:
root@kali:~/Documents/Sources/rtlwifi_new-master# make
make -C /lib/modules/4.8.0-kali1-amd64/build M=/root/Documents/Sources/rtlwifi_new-master modules
make[1]: Entering directory '/usr/src/linux-headers-4.8.0-kali1-amd64'
  CC [M]  /root/Documents/Sources/rtlwifi_new-master/base.o
/root/Documents/Sources/rtlwifi_new-master/base.c:1:0: error: code model kernel does not support PIC mode
 /******************************************************************************
 
/usr/src/linux-headers-4.8.0-kali1-common/scripts/Makefile.build:294: recipe for target '/root/Documents/Sources/rtlwifi_new-master/base.o' failed
make[4]: *** [/root/Documents/Sources/rtlwifi_new-master/base.o] Error 1
/usr/src/linux-headers-4.8.0-kali1-common/Makefile:1488: recipe for target '_module_/root/Documents/Sources/rtlwifi_new-master' failed
make[3]: *** [_module_/root/Documents/Sources/rtlwifi_new-master] Error 2
Makefile:150: recipe for target 'sub-make' failed
make[2]: *** [sub-make] Error 2
Makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.8.0-kali1-amd64'
Makefile:57: recipe for target 'all' failed
make: *** [all] Error 2

Any idea?

btw: System information:
root@kali:~/Documents/Sources/rtlwifi_new-master# uname -a
Linux kali 4.8.0-kali1-amd64 #1 SMP Debian 4.8.5-1kali1 (2016-11-04) x86_64 GNU/Linux

**Comment by lwfinger** [comment]
My code is not demanding PIC (Position Independent Code). That is something in your user space. Contact KALI Forums, etc. for an explanation/fix.

**Comment by grisutheguru** [comment]
Will do, thnx a lot

--- 
Christoph Gruber

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
