### ISSUE TITLE
Wifi works great but Bluetooth is not working

### ISSUE THREAD

**Issue by deveshmehra** [lwfinger/rtlwifi_new#165]
I have installed rtlwifi_new drivers ,after installing them wifi works great but Bluetooth stopped working.
Earlier when rtlwifi_new driver was not installed it worked fine but now its not working.

I am using HP-15af001Ax with Ubuntu 16.04 LTS
My Linux kernel version is 4.4.0-47-generic
My wireless device is RTL8723BE 

service bluetooth status

  ● bluetooth.service - Bluetooth service
   Loaded: loaded (/lib/systemd/system/bluetooth.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2016-11-29 23:40:30 IST; 1h 49min ago
     Docs: man:bluetoothd(8)
 Main PID: 3286 (bluetoothd)
   Status: "Running"
   CGroup: /system.slice/bluetooth.service
           └─3286 /usr/lib/bluetooth/bluetoothd

Nov 29 23:40:30 linux bluetoothd[3286]: gatt-time-server: Input/output error (5)
Nov 29 23:40:30 linux bluetoothd[3286]: Not enough free handles to register service
Nov 29 23:40:30 linux bluetoothd[3286]: Not enough free handles to register service
Nov 29 23:40:30 linux bluetoothd[3286]: Sap driver initialization failed.
Nov 29 23:40:30 linux bluetoothd[3286]: sap-server: Operation not permitted (1)
Nov 29 23:40:30 linux bluetoothd[3286]: Endpoint registered: sender=:1.66 path=/MediaEndpoint/A2DPSource
Nov 29 23:40:30 linux bluetoothd[3286]: Endpoint registered: sender=:1.66 path=/MediaEndpoint/A2DPSink
Nov 29 23:40:41 linux systemd[1]: Started Bluetooth service.
Nov 29 23:49:48 linux bluetoothd[3286]: Failed to set mode: Blocked through rfkill (0x12)
Nov 30 01:29:40 linux bluetoothd[3286]: Failed to set mode: Failed (0x03)

Thanks

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.

**Comment by deveshmehra** [comment]
Thanks lwfinger
