### ISSUE TITLE
Compilation error of new rtlwifi_new

### ISSUE THREAD

**Issue by deveshmehra** [lwfinger/rtlwifi_new#166]
Errors during sudo make
I am using ubuntu 16.04.1 LTS with linux 4.4.0-51 generic kernel

make -C /lib/modules/4.4.0-51-generic/build M=/home/devesh/rtlwifi_new modules
make[1]: Entering directory '/usr/src/linux-headers-4.4.0-51-generic'
  CC [M]  /home/devesh/rtlwifi_new/base.o
  CC [M]  /home/devesh/rtlwifi_new/cam.o
  CC [M]  /home/devesh/rtlwifi_new/core.o
  CC [M]  /home/devesh/rtlwifi_new/debug.o
  CC [M]  /home/devesh/rtlwifi_new/efuse.o
  CC [M]  /home/devesh/rtlwifi_new/ps.o
  CC [M]  /home/devesh/rtlwifi_new/rc.o
  CC [M]  /home/devesh/rtlwifi_new/regd.o
  CC [M]  /home/devesh/rtlwifi_new/stats.o
  LD [M]  /home/devesh/rtlwifi_new/rtlwifi.o
  CC [M]  /home/devesh/rtlwifi_new/pci.o
/home/devesh/rtlwifi_new/pci.c:49:1: error: redefinition of ‘pci_zalloc_consistent’
 pci_zalloc_consistent(struct pci_dev *hwdev, size_t size,
 ^
In file included from ./arch/x86/include/asm/pci.h:124:0,
                 from include/linux/pci.h:1502,
                 from /home/devesh/rtlwifi_new/pci.h:33,
                 from /home/devesh/rtlwifi_new/pci.c:32:
include/asm-generic/pci-dma-compat.h:17:1: note: previous definition of ‘pci_zalloc_consistent’ was here
 pci_zalloc_consistent(struct pci_dev *hwdev, size_t size,
 ^
scripts/Makefile.build:258: recipe for target '/home/devesh/rtlwifi_new/pci.o' failed
make[2]: *** [/home/devesh/rtlwifi_new/pci.o] Error 1
Makefile:1418: recipe for target '_module_/home/devesh/rtlwifi_new' failed
make[1]: *** [_module_/home/devesh/rtlwifi_new] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.4.0-51-generic'
Makefile:58: recipe for target 'all' failed
make: *** [all] Error 2

Please tell me about the errors and their solutions

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.

**Comment by deveshmehra** [comment]
But this is a new issue

**Comment by lwfinger** [comment]
Ubuntu has backported some fixes. As I have said many times, their policy on this matter is wrong and I cannot keep track of their changes.

Find the offending part in the code from pci.c, line 47, and delete it here. That should fix your issue, but I cannot make that a global change.

**Comment by deveshmehra** [comment]
Still not working

make -C /lib/modules/4.4.0-51-generic/build M=/home/devesh/rtlwifi_new modules
make[1]: Entering directory '/usr/src/linux-headers-4.4.0-51-generic'
  CC [M]  /home/devesh/rtlwifi_new/pci.o
/home/devesh/rtlwifi_new/pci.c:49:1: error: redefinition of ‘pci_zalloc_consistent’
 pci_zalloc_consistent(struct pci_dev *hwdev, size_t size,
 ^
In file included from ./arch/x86/include/asm/pci.h:124:0,
                 from include/linux/pci.h:1502,
                 from /home/devesh/rtlwifi_new/pci.h:33,
                 from /home/devesh/rtlwifi_new/pci.c:32:
include/asm-generic/pci-dma-compat.h:17:1: note: previous definition of ‘pci_zalloc_consistent’ was here
 pci_zalloc_consistent(struct pci_dev *hwdev, size_t size,
 ^
/home/devesh/rtlwifi_new/pci.c:55:2: error: #endif without #if
 #endif
  ^
scripts/Makefile.build:258: recipe for target '/home/devesh/rtlwifi_new/pci.o' failed
make[2]: *** [/home/devesh/rtlwifi_new/pci.o] Error 1
Makefile:1418: recipe for target '_module_/home/devesh/rtlwifi_new' failed
make[1]: *** [_module_/home/devesh/rtlwifi_new] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.4.0-51-generic'
Makefile:58: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lwfinger** [comment]
You needed to delete EVERYTHING from the #ifndef through the following #endif.  It looks as if you only removed the #ifndef line.

**Comment by deveshmehra** [comment]
make works but shows some warnings

/home/devesh/rtlwifi_new/rtl8821ae/trx.c: In function ‘rtl8821ae_rx_query_desc’:
/home/devesh/rtlwifi_new/rtl8821ae/trx.c:550:41: warning: passing argument 1 of ‘ieee80211_is_robust_mgmt_frame’ from incompatible pointer type [-Wincompatible-pointer-types]
if ((!_ieee80211_is_robust_mgmt_frame(hdr)) &&
^
In file included from include/net/mac80211.h:22:0,
from /home/devesh/rtlwifi_new/rtl8821ae/../wifi.h:36,
from /home/devesh/rtlwifi_new/rtl8821ae/trx.c:26:
include/linux/ieee80211.h:2415:20: note: expected ‘struct sk_buff *’ but argument is of type ‘struct ieee80211_hdr *’
static inline bool ieee80211_is_robust_mgmt_frame(struct sk_buff *skb)
^
