### ISSUE TITLE
Compilation error while compiling the new code updated 3 hours ago

### ISSUE THREAD

**Issue by deveshmehra** [lwfinger/rtlwifi_new#167]
I have got these errors while compiling the latest code updated  3 hours ago

make -C /lib/modules/4.4.0-51-generic/build M=/home/devesh/rtlwifi_new modules
make[1]: Entering directory '/usr/src/linux-headers-4.4.0-51-generic'
  CC [M]  /home/devesh/rtlwifi_new/base.o
  CC [M]  /home/devesh/rtlwifi_new/cam.o
  CC [M]  /home/devesh/rtlwifi_new/core.o
  CC [M]  /home/devesh/rtlwifi_new/debug.o
  CC [M]  /home/devesh/rtlwifi_new/efuse.o
  CC [M]  /home/devesh/rtlwifi_new/ps.o
  CC [M]  /home/devesh/rtlwifi_new/rc.o
  CC [M]  /home/devesh/rtlwifi_new/regd.o
  CC [M]  /home/devesh/rtlwifi_new/stats.o
  LD [M]  /home/devesh/rtlwifi_new/rtlwifi.o
  CC [M]  /home/devesh/rtlwifi_new/pci.o
/home/devesh/rtlwifi_new/pci.c:49:1: error: redefinition of ‘pci_zalloc_consistent’
 pci_zalloc_consistent(struct pci_dev *hwdev, size_t size,
 ^
In file included from ./arch/x86/include/asm/pci.h:124:0,
                 from include/linux/pci.h:1502,
                 from /home/devesh/rtlwifi_new/pci.h:33,
                 from /home/devesh/rtlwifi_new/pci.c:32:
include/asm-generic/pci-dma-compat.h:17:1: note: previous definition of ‘pci_zalloc_consistent’ was here
 pci_zalloc_consistent(struct pci_dev *hwdev, size_t size,
 ^
scripts/Makefile.build:258: recipe for target '/home/devesh/rtlwifi_new/pci.o' failed
make[2]: *** [/home/devesh/rtlwifi_new/pci.o] Error 1
Makefile:1418: recipe for target '_module_/home/devesh/rtlwifi_new' failed
make[1]: *** [_module_/home/devesh/rtlwifi_new] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.4.0-51-generic'
Makefile:58: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lwfinger** [comment]
As I said in the other thread, this error is due to Ubuntu's policy of backporting API changes. You need to remove any definition of pci_zalloc_consistent from pci.c. I cannot make this change in the repo as it would break builds for all the other distros that do follow the rules.

**Comment by mladenradev** [comment]
I have the same issue. After wiping this part compile was OK, but after reboot I got kernel panic.
Mint 17.3 
4.4.0-47-generic
checkout rock.new_btcoex , compile and its working again

**Comment by deveshmehra** [comment]
make works but shows some warnings

/home/devesh/rtlwifi_new/rtl8821ae/trx.c: In function ‘rtl8821ae_rx_query_desc’:
/home/devesh/rtlwifi_new/rtl8821ae/trx.c:550:41: warning: passing argument 1 of ‘ieee80211_is_robust_mgmt_frame’ from incompatible pointer type [-Wincompatible-pointer-types]
   if ((!_ieee80211_is_robust_mgmt_frame(hdr)) &&
                                         ^
In file included from include/net/mac80211.h:22:0,
                 from /home/devesh/rtlwifi_new/rtl8821ae/../wifi.h:36,
                 from /home/devesh/rtlwifi_new/rtl8821ae/trx.c:26:
include/linux/ieee80211.h:2415:20: note: expected ‘struct sk_buff *’ but argument is of type ‘struct ieee80211_hdr *’
 static inline bool ieee80211_is_robust_mgmt_frame(struct sk_buff *skb)
                    ^

**Comment by BlackYoup** [comment]
Hi,

I'm experiencing the same problem as above and I'm using Exherbo, a source based distribution.
I upgraded my kernel to `4.8.12` a few minutes ago and my kernel headers are the one for the 4.8 branch.

Here are the logs: https://paste.pound-python.org/raw/uh2Vs2wn7HZi6HG0tu3n/
`uname -a: Linux exherswag 4.8.12+ #5 SMP Fri Dec 2 21:48:00 CET 2016 x86_64 GNU/Linux`

**Comment by lwfinger** [comment]
Do another pull. Both your problems should be fixed. I found some errors.

**Comment by deveshmehra** [comment]
Finally no errors.

Thanks for what you are doing .
