### ISSUE TITLE
Compilation error: passing argument 1 of 'ieee80211_is_robust_mgmt_frame' from incompatible pointer type

### ISSUE THREAD

**Issue by BlackYoup** [lwfinger/rtlwifi_new#168]
Hi,

The compilation fails with this error: `error: passing argument 1 of 'ieee80211_is_robust_mgmt_frame' from incompatible pointer type. expected 'struct sk_buff *' but argument is of type 'struct ieee80211_hdr *'`

Complete log: https://paste.pound-python.org/raw/G1uCHNSFbABBQWRUbkkC/

I'm using GCC 6.2 (same result with GCC 5.4).
Tell me if I can provide any other information.

**Comment by lwfinger** [comment]
Pull again. That one is now fixed.

**Comment by BlackYoup** [comment]
Indeed ! Again, thanks for your work :+1:
