### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by JuanSeabra** [lwfinger/rtlwifi_new#169]
I'm on manjaro 16.10 using kernel 4.7.10-1-MANJARO.
This is the output of the make command

make -C /lib/modules/4.7.10-1-MANJARO/build M=/home/waldomiro/Downloads/rtlwifi_new modules
make[1]: Entering directory '/usr/lib/modules/4.7.10-1-MANJARO/build'
  CC [M]  /home/waldomiro/Downloads/rtlwifi_new/base.o
In file included from /home/waldomiro/Downloads/rtlwifi_new/base.c:26:0:
/home/waldomiro/Downloads/rtlwifi_new/wifi.h:45:27: error: ‘IEEE80211_NUM_BANDS’ undeclared here (not in a function)
 #define NUM_NL80211_BANDS IEEE80211_NUM_BANDS
                           ^
/home/waldomiro/Downloads/rtlwifi_new/wifi.h:1394:40: note: in expansion of macro ‘NUM_NL80211_BANDS’
  struct ieee80211_supported_band bands[NUM_NL80211_BANDS];
                                        ^~~~~~~~~~~~~~~~~
/home/waldomiro/Downloads/rtlwifi_new/wifi.h:43:27: error: ‘IEEE80211_BAND_2GHZ’ undeclared here (not in a function)
 #define NL80211_BAND_2GHZ IEEE80211_BAND_2GHZ
                           ^
/home/waldomiro/Downloads/rtlwifi_new/base.c:137:10: note: in expansion of macro ‘NL80211_BAND_2GHZ’
  .band = NL80211_BAND_2GHZ,
          ^~~~~~~~~~~~~~~~~
/home/waldomiro/Downloads/rtlwifi_new/wifi.h:44:27: error: ‘IEEE80211_BAND_5GHZ’ undeclared here (not in a function)
 #define NL80211_BAND_5GHZ IEEE80211_BAND_5GHZ
                           ^
/home/waldomiro/Downloads/rtlwifi_new/base.c:149:10: note: in expansion of macro ‘NL80211_BAND_5GHZ’
  .band = NL80211_BAND_5GHZ,
          ^~~~~~~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:290: /home/waldomiro/Downloads/rtlwifi_new/base.o] Error 1
make[1]: *** [Makefile:1458: _module_/home/waldomiro/Downloads/rtlwifi_new] Error 2
make[1]: Leaving directory '/usr/lib/modules/4.7.10-1-MANJARO/build'
make: *** [Makefile:58: all] Error 2

**Comment by deveshmehra** [comment]
Hey JuanSeabra do another git pull . lwfinger fixed some errors a few minutes ago

**Comment by JuanSeabra** [comment]
It's alredy up to date

**Comment by lwfinger** [comment]
Now fixed. Pull again.

**Comment by JuanSeabra** [comment]
worked just fine! Thanks!
