### ISSUE TITLE
Coukd not insert rtl8723be.ko : Unknown symbol in module .. and other questions

### ISSUE THREAD

**Issue by willmoss** [lwfinger/rtlwifi_new#17]
# BACKGROUND

I'm aware that the 3.17 kernel includes the rtlwifi drivers by default, but I had a problem with those drivers (that seems already reported on the internet), where my wi-fi drops for no reason. I read that the solution is to upgrade to the latest rtlwifi drivers (from this repo), so that's why I'm doing this.

As an aside, how do I find out the version of the rtlwifi drivers that is included in the kernel?

I downloaded the kernel source (https://www.kernel.org/pub/linux/kernel/v3.x/linux-3.17.tar.xz) but there is no file in the `/kernel/drivers/net/wireless/rtlwifi/rtl8723be/` directory that shows what commit the source was taken from.
# MAIN PROBLEM

Using kernel 3.17.2 , I'm having difficulty getting the latest rtl8723be driver to work. (commit b2928ce)

```
lspci

04:00.0  Network Controller: Realteak Semidonductor Co., Ltd. RTL8723BE PCIe Wireless Network Adapter
```

I downloaded commit `b2928ce` and compiled it using make install in the rtlwifi_new directory:

```
cd rtlwifi_new
make install
```

That compiles the drivers ok, and copies them to the /kernel/drivers directory

Then, I try to insert the module:

```
cd /lib/modules/3.17.2.../kernel/drivers/net/wireless/rtlwifi/rtl8723be/
insmod rtl8723be.ko
```

I get the following error:

```
insmod: ERROR: could not insert module rtl8723be.ko: Unknown symbol in module
```

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
