### ISSUE TITLE
make install: cannot stat './btcoexist/btcoexist.ko': No such file or directory

### ISSUE THREAD

**Issue by BlackYoup** [lwfinger/rtlwifi_new#170]
Some more logs: https://paste.pound-python.org/raw/AeLsbxcEh7KrlE438bLr/

I'm not very familiar with makefiles, but it seems that this module is not in the generated `./modules.order` file (maybe unrelated, I took a quick look before submitting).

And the file does not exist

**Comment by BlackYoup** [comment]
Okay, I think I found how to fix this, I'll try to open a PR :smile:

**Comment by lwfinger** [comment]
Try another pull.

**Comment by BlackYoup** [comment]
Oh, ok, I over complicated things. Nevermind. Then, `CONFIG_RTL8723_COMMON` in `rtl8723com/Makefile` will also make the install fail

**Comment by lwfinger** [comment]
Yes it would/could have caused a problem. Now fixed and pushed.

**Comment by BlackYoup** [comment]
Yes, for me it failed since I didn't activate those options in my kernel config. Thanks !
