### ISSUE TITLE
Rtl8821AE randomly becomes unresponsive

### ISSUE THREAD

**Issue by apolukhin** [lwfinger/rtlwifi_new#172]
Problem from #139 still exists:

rtl8821ae does not loose the connection (at least network manager does not display that), but the speed drops down to 5KB/s really often. Instead of 2.5 MB/s connection speed, I have an average of ~100KB/s, with rare peeks up to 2.5MB/s and common drop-downs to 5KB/s. Latency is huge: if I pause downloading at the speed of 5KB/s and try to download some very simple web page, it may take a few minutes.

Full system information is available here: https://www.spinics.net/lists/linux-wireless/msg154506.html

**Comment by lwfinger** [comment]
I have duplicated your result and reported it to Realtek. I also sent them a test program that I use. We will see what they report. I do not have a Netgear WNDR4000, but I have tested with a WNDR3400. Have you tried 5G or just 2.4G?

**Comment by apolukhin** [comment]
Just 2.4.

I'll test the rtl8821ae with 5G and post the results here.

**Comment by apolukhin** [comment]
Same problems with 5G.

Speed dropped down from 2.6 MB/s to an average of 150KB/s very fast, 5KB/s - worst, latency is huge.

Attaching a screen shot with rtl8821ae 5G: ![screenshot from 2016-12-04 01-07-21](https://cloud.githubusercontent.com/assets/1700098/20862548/230eb474-b9c7-11e6-9885-c781de2a3d44.png)
And a screen shot with USB-stick-wifi-adapter 2.4G using the same WNDR4000 router: ![screenshot from 2016-12-04 01-11-49](https://cloud.githubusercontent.com/assets/1700098/20862547/22c4aa32-b9c7-11e6-9026-f0c3dd6b1b19.png)

**Comment by apolukhin** [comment]
Can I help somehow with this issue?

**Comment by mishoo** [comment]
I have the exact same issue; I didn't try to update the drivers (using an USB wifi dongle for now), but I check this repo every now and then for updates (looks like there's nothing related yet).

@lwfinger could you post your test code for everyone to check?  I'm curious if I can repro the issue reliably (as can be inferred from @apolukhin's description, it occurs rather randomly).

**Comment by rtissera** [comment]
I can confirm same problems exists on both Debian 8 (Jessie) and 9 (Stretch) both using amd64 architecture. Using DLINK DWA-582 PCIe adapters on Intel H170M chipset for one setup, Intel H97M for the other one.
Tested on 4.9.x kernel ranges.
We gave a try to various module options (swenc, ips, ...) without any improvement. Speed drops pretty often, and connection is going up and down randomly and pretty often making it unusable for daily work in IT environment.
We are running those Linux systems in a small office, close enough to our 2.4Ghz/5Ghz D-LINK router, and we are not surrounded with (many) other Wi-Fi networks.

**Comment by mishoo** [comment]
@rtissera I gave up all hope.  This chipset is doomed on Linux, I accepted this condition and keep dragging around an USB dongle.

**Comment by apolukhin** [comment]
One Russian guy investigated the issue [here](https://www.linux.org.ru/forum/desktop/12620193).

He is writing, that rtl8821ae stops responding to ARP. Wireshark shows that ARP replies are send after a few seconds in a huge bunch. Looks like they are buffered for a very long time.

arping under setrace shows the following:
```
sendto(3, "\0\1\10\0\6\4\0\1\334\205\336\3572\343\300\250\0h\377\377\377\377\377\377\300\250\0\1", 28, 0, {sa_family=AF_PACKET, proto=0x806, if3, pkttype=PACKET_HOST, addr(6)={1, ffffffffffff}, 20) = -1 ENOBUFS (No buffer space available)
alarm(1)                                = 0
rt_sigreturn()                          = 45
recvfrom(3, 0x7fffc1646030, 4096, 0, 0x7fffc1645fb0, 0x7fffc1645eac) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGALRM {si_signo=SIGALRM, si_code=SI_KERNEL} ---
sendto(3, "\0\1\10\0\6\4\0\1\334\205\336\3572\343\300\250\0h\377\377\377\377\377\377\300\250\0\1", 28, 0, {sa_family=AF_PACKET, proto=0x806, if3, pkttype=PACKET_HOST, addr(6)={1, ffffffffffff}, 20) = -1 ENOBUFS (No buffer space available)
alarm(1)                                = 0
rt_sigreturn()                          = 45
recvfrom(3, 0x7fffc1646030, 4096, 0, 0x7fffc1645fb0, 0x7fffc1645eac) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGALRM {si_signo=SIGALRM, si_code=SI_KERNEL} ---
sendto(3, "\0\1\10\0\6\4\0\1\334\205\336\3572\343\300\250\0h\377\377\377\377\377\377\300\250\0\1", 28, 0, {sa_family=AF_PACKET, proto=0x806, if3, pkttype=PACKET_HOST, addr(6)={1, ffffffffffff}, 20) = -1 ENOBUFS (No buffer space available)
```

Some info about the system:
```
# uname -a
Linux 4.5.4-calculate #1 SMP PREEMPT Sat May 14 00:30:21 MSK 2016 x86_64 Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz GenuineIntel GNU/Linux

# sudo iwconfig
Password: 
lo        no wireless extensions.

wlan0     IEEE 802.11abgn  ESSID:"XXXXXXXXX"  
          Mode:Managed  Frequency:5.18 GHz  Access Point: XX:XX:XX:XX:XX:XX   
          Bit Rate=150 Mb/s   Tx-Power=20 dBm   
          Retry short limit:7   RTS thr=2347 B   Fragment thr:off
          Encryption key:off
          Power Management:off
          Link Quality=57/70  Signal level=-53 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:8101   Missed beacon:0

eth0      no wireless extensions.

# lspci 
....
03:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8821AE 802.11ac PCIe Wireless Network Adapter
```

Issue is reproduced on different distros but not reproduced on Windows.
