### ISSUE TITLE
Reinstall after kernel update

### ISSUE THREAD

**Issue by kladier** [lwfinger/rtlwifi_new#176]
Hello,
I wonder if there is a way to do not have to reinstall systematically this driver after a kernel update ?
Anyway thank you for this work, it solved my annoying wifi problem !

**Comment by sbstp** [comment]
Yea, you can use [`dkms`](https://wiki.archlinux.org/index.php/Dynamic_Kernel_Module_Support#DKMS_package_creation).

I cloned the repo in `/usr/src/rtlwifi-new-0.6` and used `dkms add rtlwifi-new/0.6`. There's already a dkms.conf file available in the repo, you might need to tweak it a little.

**Comment by kladier** [comment]
I installed it with dmks but how can I know if this driver is indeed used ?
This is the dkms.conf file modified : 
`PACKAGE_NAME="rtlwifi-new"
PACKAGE_VERSION=0.6
MAKE="make -C $kernel_source_dir M=$dkms_tree/$PACKAGE_NAME/$PACKAGE_VERSION/build"
CLEAN="make -C clean"
BUILT_MODULE_NAME[0]="rtl_pci"
BUILT_MODULE_NAME[1]="rtl_usb"
BUILT_MODULE_NAME[2]="rtlwifi"
BUILT_MODULE_NAME[3]="btcoexist"
BUILT_MODULE_NAME[4]="rtl8821ae"
BUILT_MODULE_LOCATION[3]="btcoexist"
BUILT_MODULE_LOCATION[4]="rtl8821ae"
DEST_MODULE_LOCATION[0]="/updates"
DEST_MODULE_LOCATION[1]="/updates"
DEST_MODULE_LOCATION[2]="/updates"
DEST_MODULE_LOCATION[3]="/updates"
DEST_MODULE_LOCATION[4]="/updates"
REMAKE_INITRD=yes
AUTOINSTALL=yes`

Finally I still have latency and random wifi turn off.
Something strange : if I `sudo service network-manager restart` when I've this problem, the command take a few seconds (5-10s) (as if the wifi driver or card is blocked) and finally works and wifi is back.
It's a rtl8821ae and I saw in the issues that I'm not alone to be annoyed by this card..

Thanks for your help

**Comment by lwfinger** [comment]
I have no idea whether DKMS is working for you, or if you are using the standard driver.

We are working on the connectivity issues with the rtl8821ae, whenever there is any time left over from answering comments like yours.

**Comment by sbstp** [comment]
You can check the kernel module's path by using `modinfo <module name>`. For me, the default driver is in `/lib/modules/4.8.0-2-amd64/kernel/drivers/net/wireless/realtek/rtlwifi/rtl8192ee/rtl8192ee.ko`. After using dkms, modinfo says that the driver is in `/lib/modules/4.8.0-2-amd64/updates/dkms/rtl8192ee.ko`, so it looks like it worked.

**Comment by kladier** [comment]
I checked and the path is /lib/modules/4.4.0-53-generic/kernel/drivers/net/wireless/realtek/rtlwifi/rtl8821ae/rtl8821ae.ko
I tried to uninstall with dkms and the path is the same so I guess it didnt worked.

Edit : finally it worked and the path changed when I did dkms install with --force

Thanks for your help and if you need informations for this type of card, please ask me.
