### ISSUE TITLE
Connectivity and Network Speed Issue with rtl8723be

### ISSUE THREAD

**Issue by AakashDabas** [lwfinger/rtlwifi_new#177]
I've installed this version of drivers. But the problem which was with previous versions is still in this version also. I guess that antenna fix needs to be done. I'm using ubuntu 16.10 with kernel version 4.8. My laptop is HP ab032tx. Can you please help me with followings:-
1). Please tell me the procedure for antenna settings as older comments are removed. 
2). Please tell me how to update firmware for rtl8723be to latest.
3). Also, laptop still shows hardblocked on wireless after waking up from sleep mode. I hope that can also be fixed. 
And thanks for helping us.

**Comment by lwfinger** [comment]
1. If you needed the ant_sel parameter before, then you need exactly the same value abain. That is a hardware situation, and no change in the software can permanently fix that.
2. sudo make install
3. That is a function of your distro's user space. You need to take that up with them.

**Comment by AakashDabas** [comment]
Thanks now wifi is working. But the still it goes to hard blocked after suspend or hibernation. But as you have already said many times, this issue is with user space code. But thanks a lot for all the help.

**Comment by mpuels** [comment]
Could you please explain the ant_sel parameter? I'm having connectivity problems with my rtl8723be. On Windows, WiFi works fine. But on Ubuntu 16.04 with Linux Kernel 4.4.0-53-generic, as soon as I move the laptop away from the router more than roughly 4 meters, the connection is lost.

**Comment by lwfinger** [comment]
That parameter is for those computers where the manufacturer only included a single antenna, but coded the EEPROM to state that it was attached to the other connector. Thus, the driver, which uses the EEPROM value, is actually not using the available antenna. The symptoms are that the signal strength from the 'sudo iw dev wlan0 scan | grep signal' is only -70 dBm even for a nearby AP. If your device is not wlan0, adjust the command appropriately.

**Comment by mpuels** [comment]
Hello lwfinger,

thanks for you quick response! When I run your command when the laptop is roughly 1m away from the router, I get the following output:

    signal: -62.00 dBm

As soon as I'm 3m away, the output is

    signal: -78.00 dBm

Could you please tell me how to set the ant_sel parameter so that the driver uses the available antenna? Thanks!

**Comment by mpuels** [comment]
The command

    echo options rtl8723be ant_sel=2 | sudo tee /etc/modprobe.d/rtl8723be.conf

has solved my problem. Thank you very much!

By the way, Is there a document where all the parameters are listed?

**Comment by lwfinger** [comment]
modinfo rtl8723be
