### ISSUE TITLE
Have any one try to using connman tethering mode on 8723be chip set?

### ISSUE THREAD

**Issue by wenij** [lwfinger/rtlwifi_new#180]
hi all,

I using the newest driver and configure the wifi using connman and enable its tether mode.
but never success to using it (I try using macbook and iphone).

ps. using connman to configure as station mode is running very well.
ps. running with "options rtl8723be fwlps=0 swlps=0 msi=1 ips=0"

wenij

**Comment by lwfinger** [comment]
With the new code, you should not need any of the ps options. In fact, with ips=0, you would drain the battery of your phone if you were able to connect.

Are you seeing the probe packets from the RTL8723BE?

**Comment by wenij** [comment]
hi lwfinger,

ok, remove ps option seems work very good in station mode.

for tethering mode issue,
I using macbook to capture the packet, but I can't see any probe packet from RTL8723be.
but my iphone can see the ssid, but always auth fail.
==
I using following command to enable tethering mode
"connmanctl tether wifi on test-ap 1234567890"
==
do you have chance to try it and see if it work on your linux system?

wenij
