### ISSUE TITLE
RTL8723BE drops connection on Elementary OS (Ubuntu 16.04)

### ISSUE THREAD

**Issue by efkan** [lwfinger/rtlwifi_new#184]
I have installed Elementary OS (which is equal to Ubuntu 16.04) about 15 days ago.
Then I downloaded this `rtlwifi_new` and I installed it on the kernel `4.4.0-38-generic`.
Everything was well. But I have never left opened the computer more than 20 hours.

Then my system has gotten a kernel update for `4.4.0-53-generic`. My computer was opened for about 36 hours when it got disconnected. I couldn't connect it without restarting the computer. 

The following message was written in `syslog` file:
`wlp2s0: Connection to AP d0:7a:b5:11:13:f8 lost`

Then I tried to install the latest version of this repository .

Unfortunately the wireless disconnects in a couple of minutes at every time. And again I couldn't connect without restarting the computer.

Then I returned the old `rtlwifi_new` driver again. Now I don't know when my connection would be dropped.

Restarting at every disconnection is so hard when opened the all project windows.

I wonder that is there any way to overcome this issue?

**Comment by efkan** [comment]
Unfortunately today I encountered two times with the same issue.

So, I had to restart two times my computer. I couldn't find any other solution.

**Comment by nickmeet** [comment]
Until kernel 4.11 comes, try the following. This repository has no tags but 


```bash
sudo apt-get install build-essential linux-headers-generic git dkms
git clone http://github.com/lwfinger/rtlwifi_new.git
cd rtlwifi_new/
make
sudo modprobe -rv rtl8723be
sudo make install
sudo rm /etc/modprobe.d/rtl8723be.conf
echo "options rtl8723be debug=5" | sudo tee /etc/modprobe.d/rtl8723be.conf
sudo modprobe -rvf rtl8723be
sudo modprobe rtl8723be
```

```bash
wget "https://dl.dropboxusercontent.com/s/l93ifv397doyvil/wireless-script" -O wireless-script
chmod 755 wireless-script
sudo ./wireless-script
```

**Comment by efkan** [comment]
@nickmeet , I've made some changes in my configuration. If I face with connection drops I'd take your advice. 

Thank you very much..

**Comment by efkan** [comment]
@nickmeet , I've made some changes in my configuration. If I face with connection drops I'd take your advice. (I'd add `debug=5` parameter)

Thank you very much..

**Comment by efkan** [comment]
Unfortunately I've been experiencing disconnections still. 

And I don't know how can I correct wireless connection without a restart. I've been trying a lot of things for days. But nothing works..

My `rtl8723be.conf` file contains the following line:
```
options rtl8723be ips=0 fwlps=0 swlps=0 swenc=Y msi=1 ant_sel=1 debug=5
```


My relevant `syslog` entires:
```
Dec 14 23:20:05 HP-Notebook kernel: [10100.347226] wlp2s0: Connection to AP d0:7a:b5:12:53:f8 lost
Dec 14 23:20:20 HP-Notebook wpa_supplicant[1100]: wlp2s0: CTRL-EVENT-DISCONNECTED bssid=d0:7a:b5:12:53:f8 reason=4 locally_generated=1
Dec 14 23:20:20 HP-Notebook NetworkManager[937]: <warn>  [1481746820.2639] sup-iface[0x1b172a0,wlp2s0]: connection disconnected (reason -4)
Dec 14 23:20:20 HP-Notebook NetworkManager[937]: <info>  [1481746820.2674] device (wlp2s0): supplicant interface state: completed -> disconnected
Dec 14 23:20:20 HP-Notebook gnome-session[1625]: (nm-applet:1884): GLib-CRITICAL **: g_hash_table_remove_all: assertion 'hash_table != NULL' failed
Dec 14 23:20:20 HP-Notebook gnome-session[1625]: (nm-applet:1884): nm-applet-CRITICAL **: nma_icons_free: assertion 'NM_IS_APPLET (applet)' failed
Dec 14 23:20:29 HP-Notebook wpa_supplicant[1100]: wlp2s0: CTRL-EVENT-REGDOM-CHANGE init=CORE type=WORLD
Dec 14 23:20:29 HP-Notebook kernel: [10124.369713] cfg80211: World regulatory domain updated:
Dec 14 23:20:29 HP-Notebook kernel: [10124.369730] cfg80211:  DFS Master region: unset
Dec 14 23:20:29 HP-Notebook kernel: [10124.369737] cfg80211:   (start_freq - end_freq @ bandwidth), (max_antenna_gain, max_eirp), (dfs_cac_time)
Dec 14 23:20:29 HP-Notebook kernel: [10124.369750] cfg80211:   (2402000 KHz - 2472000 KHz @ 40000 KHz), (N/A, 2000 mBm), (N/A)
Dec 14 23:20:29 HP-Notebook kernel: [10124.369760] cfg80211:   (2457000 KHz - 2482000 KHz @ 40000 KHz), (N/A, 2000 mBm), (N/A)
Dec 14 23:20:29 HP-Notebook kernel: [10124.369770] cfg80211:   (2474000 KHz - 2494000 KHz @ 20000 KHz), (N/A, 2000 mBm), (N/A)
Dec 14 23:20:29 HP-Notebook kernel: [10124.369781] cfg80211:   (5170000 KHz - 5250000 KHz @ 80000 KHz, 160000 KHz AUTO), (N/A, 2000 mBm), (N/A)
Dec 14 23:20:29 HP-Notebook kernel: [10124.369793] cfg80211:   (5250000 KHz - 5330000 KHz @ 80000 KHz, 160000 KHz AUTO), (N/A, 2000 mBm), (0 s)
Dec 14 23:20:29 HP-Notebook kernel: [10124.369805] cfg80211:   (5490000 KHz - 5730000 KHz @ 160000 KHz), (N/A, 2000 mBm), (0 s)
Dec 14 23:20:29 HP-Notebook kernel: [10124.369814] cfg80211:   (5735000 KHz - 5835000 KHz @ 80000 KHz), (N/A, 2000 mBm), (N/A)
Dec 14 23:20:29 HP-Notebook kernel: [10124.369823] cfg80211:   (57240000 KHz - 63720000 KHz @ 2160000 KHz), (N/A, 0 mBm), (N/A)
Dec 14 23:20:29 HP-Notebook systemd-udevd[11135]: Process '/sbin/crda' failed with exit code 249.
Dec 14 23:20:35 HP-Notebook NetworkManager[937]: <warn>  [1481746835.5663] device (wlp2s0): link timed out.
Dec 14 23:20:35 HP-Notebook NetworkManager[937]: <info>  [1481746835.5664] device (wlp2s0): state change: activated -> failed (reason 'ssid-not-found') [100 120 53]
Dec 14 23:20:35 HP-Notebook NetworkManager[937]: <info>  [1481746835.5675] manager: NetworkManager state is now CONNECTED_LOCAL
Dec 14 23:20:35 HP-Notebook NetworkManager[937]: <warn>  [1481746835.5740] device (wlp2s0): Activation: failed for connection 'WN'
Dec 14 23:20:35 HP-Notebook dbus[900]: [system] Activating via systemd: service name='org.freedesktop.nm_dispatcher' unit='dbus-org.freedesktop.nm-dispatcher.service'
Dec 14 23:20:35 HP-Notebook NetworkManager[937]: <info>  [1481746835.5795] device (wlp2s0): state change: failed -> disconnected (reason 'none') [120 30 0]
Dec 14 23:20:35 HP-Notebook systemd[1]: Starting Network Manager Script Dispatcher Service...
Dec 14 23:20:35 HP-Notebook dbus[900]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'
Dec 14 23:20:35 HP-Notebook systemd[1]: Started Network Manager Script Dispatcher Service.
Dec 14 23:20:35 HP-Notebook nm-dispatcher: req:1 'down' [wlp2s0]: new request (2 scripts)
Dec 14 23:20:35 HP-Notebook nm-dispatcher: req:1 'down' [wlp2s0]: start running ordered scripts...
Dec 14 23:20:45 HP-Notebook nm-dispatcher[11149]: Dump was interrupted and may be inconsistent.
Dec 14 23:20:45 HP-Notebook kernel: [10139.608891] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
Dec 14 23:20:45 HP-Notebook avahi-daemon[889]: Withdrawing address record for fe80::9653:30ff:fe2a:8c33 on wlp2s0.
Dec 14 23:20:45 HP-Notebook avahi-daemon[889]: Leaving mDNS multicast group on interface wlp2s0.IPv6 with address fe80::9653:30ff:fe2a:8c33.
Dec 14 23:20:45 HP-Notebook NetworkManager[937]: <info>  [1481746845.1127] dns-mgr: Writing DNS information to /sbin/resolvconf
Dec 14 23:20:45 HP-Notebook avahi-daemon[889]: Interface wlp2s0.IPv6 no longer relevant for mDNS.
Dec 14 23:20:45 HP-Notebook avahi-daemon[889]: Withdrawing address record for 192.168.1.26 on wlp2s0.
Dec 14 23:20:45 HP-Notebook avahi-daemon[889]: Leaving mDNS multicast group on interface wlp2s0.IPv4 with address 192.168.1.26.
Dec 14 23:20:45 HP-Notebook avahi-daemon[889]: Interface wlp2s0.IPv4 no longer relevant for mDNS.
Dec 14 23:20:45 HP-Notebook dnsmasq[1341]: setting upstream servers from DBus
Dec 14 23:20:45 HP-Notebook wpa_supplicant[1100]: wlp2s0: Reject scan trigger since one is already pending
Dec 14 23:20:45 HP-Notebook NetworkManager[937]: <info>  [1481746845.1249] device (wlp2s0): supplicant interface state: disconnected -> scanning
Dec 14 23:20:45 HP-Notebook NetworkManager[937]: <info>  [1481746845.1263] policy: auto-activating connection 'WN'
Dec 14 23:20:45 HP-Notebook NetworkManager[937]: <info>  [1481746845.1275] device (wlp2s0): Activation: starting connection 'WN' (d16ff1e0-c288-4d98-9d50-4c7921b8c598)
Dec 14 23:20:45 HP-Notebook NetworkManager[937]: <info>  [1481746845.1276] device (wlp2s0): state change: disconnected -> prepare (reason 'none') [30 40 0]
Dec 14 23:20:45 HP-Notebook NetworkManager[937]: <info>  [1481746845.1277] manager: NetworkManager state is now CONNECTING
Dec 14 23:20:45 HP-Notebook NetworkManager[937]: <info>  [1481746845.1281] device (wlp2s0): state change: prepare -> config (reason 'none') [40 50 0]
Dec 14 23:20:45 HP-Notebook NetworkManager[937]: <info>  [1481746845.1283] device (wlp2s0): Activation: (wifi) access point 'WN' has security, but secrets are required.
Dec 14 23:20:45 HP-Notebook NetworkManager[937]: <info>  [1481746845.1283] device (wlp2s0): state change: config -> need-auth (reason 'none') [50 60 0]
Dec 14 23:20:45 HP-Notebook NetworkManager[937]: <info>  [1481746845.1347] device (wlp2s0): state change: need-auth -> prepare (reason 'none') [60 40 0]
Dec 14 23:20:45 HP-Notebook NetworkManager[937]: <info>  [1481746845.1351] device (wlp2s0): state change: prepare -> config (reason 'none') [40 50 0]
Dec 14 23:20:45 HP-Notebook NetworkManager[937]: <info>  [1481746845.1353] device (wlp2s0): Activation: (wifi) connection 'WN' has security, and secrets exist.  No new s$
Dec 14 23:20:45 HP-Notebook NetworkManager[937]: <info>  [1481746845.1353] Config: added 'ssid' value 'WN'
Dec 14 23:20:45 HP-Notebook NetworkManager[937]: <info>  [1481746845.1354] Config: added 'scan_ssid' value '1'
Dec 14 23:20:45 HP-Notebook NetworkManager[937]: <info>  [1481746845.1354] Config: added 'key_mgmt' value 'WPA-PSK'
Dec 14 23:20:45 HP-Notebook NetworkManager[937]: <info>  [1481746845.1354] Config: added 'psk' value '<omitted>'
Dec 14 23:20:45 HP-Notebook NetworkManager[937]: <info>  [1481746845.1433] sup-iface[0x1b172a0,wlp2s0]: config: set interface ap_scan to 1
Dec 14 23:21:00 HP-Notebook gnome-session[1625]: [6102:6158:1214/232100:ERROR:connection_factory_impl.cc(367)] Failed to connect to MCS endpoint with error -106
Dec 14 23:21:10 HP-Notebook NetworkManager[937]: <warn>  [1481746870.5647] device (wlp2s0): Activation: (wifi) association took too long, failing activation
Dec 14 23:21:10 HP-Notebook NetworkManager[937]: <info>  [1481746870.5647] device (wlp2s0): state change: config -> failed (reason 'ssid-not-found') [50 120 53]
Dec 14 23:21:10 HP-Notebook NetworkManager[937]: <info>  [1481746870.5650] manager: NetworkManager state is now CONNECTED_LOCAL
Dec 14 23:21:10 HP-Notebook NetworkManager[937]: <warn>  [1481746870.5657] device (wlp2s0): Activation: failed for connection 'WN'
Dec 14 23:21:10 HP-Notebook NetworkManager[937]: <info>  [1481746870.5669] device (wlp2s0): state change: failed -> disconnected (reason 'none') [120 30 0]
Dec 14 23:21:15 HP-Notebook wpa_supplicant[1100]: wlp2s0: Reject scan trigger since one is already pending
Dec 14 23:21:15 HP-Notebook kernel: [10170.298858] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
Dec 14 23:21:15 HP-Notebook NetworkManager[937]: <info>  [1481746875.8120] device (wlp2s0): supplicant interface state: scanning -> disconnected
```

**Comment by lwfinger** [comment]
First of all, get rid of EVERY option other than ant_sel, and perhaps msi. Since the recent update, none of the *ps options are needed, and there have been unsubstantiated reports that they are harmful. I have been too busy with other stuff to investigate that. That debug=5 is flooding your logs and that is taking quite a bit of your CPU power for absolutely no gain! In addition, you are forcing the CPU to handle encryption, while the device firmware is likely able to do it. If removing that option causes it to fail, then your device is broken.

When the connection drops, the command 'sudo modprobe -rv rtl8723be && sudo modprobe -v rtl8723be' should restore it. If not, then there is a problem with the user-space network control of your distro.

**Comment by efkan** [comment]
**Thank you** @lwfinger . I'm appreciated for your works. I can wifi thanks to you although it drops connection sometimes. I just sorry about manufacturers of devices and about driver supports of distros.

The last version of drivers of this repository drops the connection often (maybe I do wrong something) on Elementary OS; which is equal to Ubuntu 16.04 LTS. Because of this I use an immediate before version of drivers of this repository . I've tried several times to use new drivers but no chance.

I only could not figure a sentence out of your writing: `In addition, you are forcing the CPU to handle encryption, while the device firmware is likely able to do it.` 

But nothing is important and urgent. Even in the worst scenario I can restart and go on my works :)

**Comment by efkan** [comment]
I've tried again install the latest version of this repository. 

Actually I'm running on kernel `4.4.0-53-generic`.

I've opened my `rtlwifi_old` directory and I run the command of `sudo make uninstall`. The old version is removed from kernel `4.4.0-38-generic`.

Then I opened my `rtlwifi_new` directory and I run the commands below in order: 

`sudo make clean`
`make`
`sudo make install` 
It installed on `4.4.0-53-generic`.
`sudo modprobe rtl8723be -r`
`sudo modprobe rtl8723be ant_sel=2`
`reboot`

After my OS opened I experienced a disconnection in 2 minutes. Then I tried re-install the old driver. So in `rtlwifi_new` directory I run the command of `sudo make unnstall`. It removed from kernel `4.4.0-53-generic`.

Then in `rtlwifi_old` directory I run again:
`sudo make clean`
`make`
`sudo make install` 
It installed on **`4.4.0-53-generic`** which is **the newest** kernel.
`sudo modprobe rtl8723be -r`
`sudo modprobe rtl8723be ant_sel=2`
`reboot`

Now I'm experiences disconnections often. Don't panic I had gotten a backup of my OS when it runs properly :) So I'll back to my old system files to get run my wifi and to continue my works.

ps: I restarted three times the computer to complete and send this entry :)

**Comment by lwfinger** [comment]
What is your signal strength?

I have no idea why you have so much trouble. After rtlwifi_new was updated, I ran rtl8723be for 5 days without a drop. Are you sure ant_sel=2 is the correct option?

**Comment by efkan** [comment]
I've checked my wifi signal strength by using the command of `watch -n1 iwconfig`.

My `link-quality` increases and decreases between 50/70 and 68/70.
And `signal-level` increases and decreases between `-40dBm` and `-60dBm`.

My current `rtl8723be.conf` conatins the line below:

`options rtl8723be ant_sel=1 fwlps=0`

(`ant_sel=2` didn't work for now)

In normal conditions, my wireless card finds about 20 wireless network. Approximately 20 or 30 seconds  before a disconnection my wireless card can find about 5 or 10 wireless network. And immediately before a disconnection my wireless car can find 1-2 network. Then the all networks go...

And also this is my third notebook in the last 20 days. (first notebook had SSD problem, second one had dead-pixel and case defects and the last one has backlight bleeding :smile:  ) The all these the same three notebooks have the same issue with RTL8723BE card on Elementary OS unfortunately.

Maybe the reason is my bad chance :smile: 

Thank you..

**Comment by efkan** [comment]
The output of `iwlist wlp2s0 scan` command like the following:

```
wlp2s0    Scan completed :
          Cell 01 - Address: D0:7A:B5:12:53:F8
                    Channel:9
                    Frequency:2.452 GHz (Channel 9)
                    Quality=68/70  Signal level=-42 dBm  
                    Encryption key:on
                    ESSID:"WN"
                    Bit Rates:1 Mb/s; 2 Mb/s; 5.5 Mb/s; 11 Mb/s; 18 Mb/s
                              24 Mb/s; 36 Mb/s; 54 Mb/s
                    Bit Rates:6 Mb/s; 9 Mb/s; 12 Mb/s; 48 Mb/s
                    Mode:Master
                    Extra:tsf=0000004b95cbe6c9
                    Extra: Last beacon: 68632ms ago
                    IE: Unknown: 0002574E
                    IE: Unknown: 010882848B962430486C
                    IE: Unknown: 030109
                    IE: Unknown: 2A0104
                    IE: Unknown: 2F0104
                    IE: IEEE 802.11i/WPA2 Version 1
                        Group Cipher : TKIP
                        Pairwise Ciphers (2) : CCMP TKIP
                        Authentication Suites (1) : PSK
                    IE: Unknown: 32040C121860
                    IE: Unknown: 2D1AFC181BFFFF000000000000000000000000000000000000000000
                    IE: Unknown: 3D1609000400000000000000000000000000000000000000
                    IE: Unknown: DD800050F204104A0001101044000102103B00010310470010000000000000000000000000000000001021000842726F6164636F6D1023000842726F6164636F6D1024000631323334353610420004313233341054000800060050F20400011011000A42726F6164636F6D4150100800020000103C0001011049000600372A000120
                    IE: Unknown: DD090010180204F02C0000
                    IE: WPA Version 1
                        Group Cipher : TKIP
                        Pairwise Ciphers (2) : CCMP TKIP
                        Authentication Suites (1) : PSK
                    IE: Unknown: DD180050F2020101800003A4000027A4000042435E0062322F00
```

I wonder that which distro do you use? Because, 5 days without a drop is perfect :smiley: 

Thank you again.

**Comment by lwfinger** [comment]
That signal of -42 dBm is good. I use openSUSE Leap 42.2. With their standard kernel, you would need to use this repo.

**Comment by buceqk** [comment]
Hi,
I run openSUSE 42.2 too, but the wifi still not work properly..
I was succesfull install the driver after modifying Makefile:
`SHELL := /bin/sh`
`CC = gcc`
`KVER  ?= $(shell uname -r) `
`KSRC := /lib/modules/4.9.0-2.g6fbc0c0-default/build`
`FIRMWAREDIR := /lib/firmware/`
`PWD := $(shell pwd)`

After reboot, I check in Hardware Information and the driver for RTL8723BE not active (Active:No)
How to activated that driver? (I'm newbie by the way).

The output of `uname -a` command:
`Linux linux-jl3o 4.4.36-8-default #1 SMP Fri Dec 9 16:18:38 UTC 2016 (3ec5648) x86_64 x86_64 x86_64 GNU/Linux`

Thanks.

**Comment by lwfinger** [comment]
As always, check the output of the 'dmesg | less' command. If I had to guess, I suspect that your modification of the definition of KSRC caused you to force a build against the wrong kernel, and the modules cannot load.

**Comment by efkan** [comment]
I change heading of the issue because most of the issues encountered on Ubuntu.

This reason can occurred by two possibility:
1. Most of the Linux users choose Ubuntu distribution.
2. Ubuntu kernel causes to drop connection in a way

**Comment by buceqk** [comment]
Hi,
I don't know what happen, but fortunately, my wifi work perfectly after i did this sequence for several times: `make install` - `reboot` - `make clean` - `make uninstall` - `reboot` - repeat 

Thanks for the information and support guys..

**Comment by efkan** [comment]
I want to specify that I'm on an old version of this repo. 
Current version doesn't work for me. Or I could not manage this operation.

I had tries these commands too. Unfortunately it doesn't work for me.

Also I realized that when trying the command of `make uninstall`, it actually writes the driver files onto `/lib/modules/4.4.0-57-generic/kernel/drivers/net/wireless/realtek/rtlwifi` again. 

To detect this result, I delete the files manually. Then I try `make uninstall` command. Then I saw that the driver files have been written again. 

It may be a normal behave of Linux. Really I don't know...

**Comment by lwfinger** [comment]
If you read the Makefile, you will see that the first time the "install" is run, it saves to driver files. Then when an uninstall is run, it restores those driver files. That is the way I programmed it. If that is not what you want, then you should recode Makefile.

**Comment by efkan** [comment]
@lwfinger thank you. 

Actually I had guessed it when I encountered the driver backup files. But now, I'm sure.

By the way, today I tried this repo again by using the commands below:

```
git clone https://github.com/lwfinger/rtlwifi_new.git
cd rtlwifi_new
make
sudo make install 
```

On my first try, I didn't give any more parameters than `ant_sel=2` on rtl8723be.conf file. About 30 seconds after startup, wifi dropped the connection. 

On my second try, I set the all parameters on the conf file (I know it doesn't need :smile:) like the following:
`options rtl8723be ant_sel=2 fwlps=N ips=N disable_watchdog=Y msi=Y swenc=Y swlps=N debug=0`

About 5 or 6 minutes after startup, wifi dropped the connection.

Then I returned to the old copy of this repo. I wish a long working time :pray: 

I tried the new repo again today because I couldn't bear to disconnections and restarts when running 3 virtual machine and coding :disappointed:  

Details:
* I'm on recent kernel `4.4.0-57-generic` for a couple of days. No any positive situation.
* I use my laptop without battery because of thinking of battery protection.

**Comment by efkan** [comment]
Also I use ping method to awake my wireless card by using the command of `ping google.com -s 0.01 -i 10`.

Unfortunately.. It doesn't work too.

My wireless card dropped the connection and I had to restart my laptop again.

**Comment by lwfinger** [comment]
Have you verified that "ant_sel=2" is the correct choice?

If you do "sudo modprobe -rv rtl8723be && sudo modprobe -v rtl8723be", does that restart the network without rebooting?

**Comment by efkan** [comment]
First of all I have to make a correction. I skipped a word on my previous comment. It should have been "Also I use ping method to **stay** awake my wireless card".

Yes, I did try your combo command after read your comment. Unfortunately. It has not solved my restart need.

I'll try it a couple of minutes later. I would write the result here again.

Thank you really. Should I change my distro, do you have any advice for me?

**Comment by efkan** [comment]
I used `sudo modprobe -rv rtl8723be && sudo modprobe -v rtl8723be` command several minutes ago.

I had to restart my laptop. I added the screenshot with terminal results and wireless settings page. The wireless seems as disabled although it is enabled.

A stubborn and difficult situation :)

![screenshot from 2016-12-22 20 43 07](https://cloud.githubusercontent.com/assets/6974198/21435037/11c7221a-c880-11e6-8387-4f9b669b6f9e.png)

**Comment by efkan** [comment]
The command of `sudo rmmod rtl8723be && sudo modprobe rtl8723be` works today.

In generally, I would re-connect on the settings page and then would try this command. 

But first I try the command without a re-connect try. Now everything seems running.

Note: I've tried the command immediately when I realized that wifi dropping the connection. It worked..

**Comment by efkan** [comment]
At second time `sudo rmmod rtl8723be && sudo modprobe rtl8723be` command doesn't work.

**Comment by lwfinger** [comment]
I am not going to install Elementary, but I downloaded it and ran it live. When I unloaded and reloaded the driver, the network management system did nothing. That is an exceedingly fragile bit of user space code. It reminded me of most distros 5 or 10 years ago. I am afraid there is nothing I can do for uou. Try some other distro!

**Comment by efkan** [comment]
Thank you very much.

I'll try report it to them.

And then probably I'd take your advise.
