### ISSUE TITLE
Problems installing after Ubuntu Xenial Kernel update

### ISSUE THREAD

**Issue by t0ben** [lwfinger/rtlwifi_new#186]
Hello,
I have Problems installing on Ubuntu Xenial after the latest kernel upgrade.

git clone  http://github.com/lwfinger/rtlwifi_new.git 
apt-get install linux-headers-$(uname -r)
uname -r
> 4.4.0-53-generic

make
> make -C /lib/modules/4.4.0-53-generic/build M=/home/tom/Downloads/rtlwifi_new modules
> make[1]: Entering directory '/usr/src/linux-headers-4.4.0-53-generic'
>   Building modules, stage 2.
>   MODPOST 15 modules
> make[1]: Leaving directory '/usr/src/linux-headers-4.4.0-53-generic'
> 

make install
> make -C /lib/modules/4.4.0-53-generic/build M=/home/tom/Downloads/rtlwifi_new modules
> make[1]: Entering directory '/usr/src/linux-headers-4.4.0-53-generic'
>   Building modules, stage 2.
>   MODPOST 15 modules
> make[1]: Leaving directory '/usr/src/linux-headers-4.4.0-53-generic'
> Install rtlwifi SUCCESS
> 

 modprobe -v rtl8723be
> insmod /lib/modules/4.4.0-53-generic/kernel/drivers/net/wireless/realtek/rtlwifi/rtl8723be/rtl8723be.ko ips=0 ant_sel=2 
> modprobe: ERROR: could not insert 'rtl8723be': Invalid argument
> 

dmesg
> [ 3114.717397] rtl8723be: Unknown symbol rtl_get_tx_report (err 0)
> [ 3114.7apt-get install linux-headers-$(uname -r)17422] rtl8723be: disagrees about version of symbol rtl_process_phyinfo
> [ 3114.717424] rtl8723be: Unknown symbol rtl_process_phyinfo (err -22)
> [ 3114.717446] rtl8723be: Unknown symbol rtl_c2hcmd_enqueue (err 0)
> [ 3114.717487] rtl8723be: Unknown symbol rtl_tx_report_handler (err 0)
> [ 3114.717601] rtl8723be: Unknown symbol rtl_get_hwinfo (err 0)
> [ 3114.717625] rtl8723be: disagrees about version of symbol rtl_evm_db_to_percentage
> [ 3114.717627] rtl8723be: Unknown symbol rtl_evm_db_to_percentage (err -22)
> [ 3114.717637] rtl8723be: disagrees about version of symbol rtl_query_rxpwrpercentage
> [ 3114.717639] rtl8723be: Unknown symbol rtl_query_rxpwrpercentage (err -22)
> [ 3114.717645] rtl8723be: disagrees about version of symbol rtl_get_tcb_desc
> [ 3114.717646] rtl8723be: Unknown symbol rtl_get_tcb_desc (err -22)
> [ 3114.717665] rtl8723be: Unknown symbol efuse_power_switch (err 0)
> [ 3114.717674] rtl8723be: disagrees about version of symbol rtl_btc_get_ops_pointer
> [ 3114.717676] rtl8723be: Unknown symbol rtl_btc_get_ops_pointer (err -22)

best regards and thank you !

**Comment by lwfinger** [comment]
I think you failed to unload the old driver  first. Did a reboot help?

**Comment by t0ben** [comment]
A reboot did the trick. Thank you !
