### ISSUE TITLE
Bluetooth doesn't work for rtl8723be on linux 4.9

### ISSUE THREAD

**Issue by InfiniteCoder** [lwfinger/rtlwifi_new#187]
I noticed that the repo was updated, so I cloned it and installed it.

Wifi works as usual, but bluetooth doesn't(as usual)

So when I try to enable bluetooth, it says your bluetooth adapter is powered of.

`dmesg|grep -i bluetooth` shows

    [aditya@aditya-pc ~]$ dmesg|grep -i Bluetooth
    [   14.007361] Bluetooth: Core ver 2.22
    [   14.007381] Bluetooth: HCI device and connection manager initialized
    [   14.007384] Bluetooth: HCI socket layer initialized
    [   14.007387] Bluetooth: L2CAP socket layer initialized
    [   14.007391] Bluetooth: SCO socket layer initialized
    [   14.605200] Bluetooth: HCI UART driver ver 2.3
    [   14.605204] Bluetooth: HCI UART protocol H4 registered
    [   14.605206] Bluetooth: HCI UART protocol BCSP registered
    [   14.605207] Bluetooth: HCI UART protocol LL registered
    [   14.605209] Bluetooth: HCI UART protocol ATH3K registered
    [   14.605210] Bluetooth: HCI UART protocol Three-wire (H5) registered
    [   14.605259] Bluetooth: HCI UART protocol Intel registered
    [   14.605287] Bluetooth: HCI UART protocol Broadcom registered
    [   14.605289] Bluetooth: HCI UART protocol QCA registered
    [   14.605290] Bluetooth: HCI UART protocol AG6XX registered
    [   18.202773] Bluetooth: hci0: rtl: examining hci_ver=06 hci_rev=000b lmp_ver=06     lmp_subver=8723
    [   18.202780] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723b_config.bin
    [   18.202896] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723b_config.bin failed with error -2
    [   18.202901] Bluetooth: hci0: Failed to load rtl_bt/rtl8723b_config.bin
    [   18.202910] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723b_fw.bin
    [   18.336695] Bluetooth: hci0: rom_version status=0 version=1
    [   18.336710] Bluetooth: cfg_sz 0, total size 22496
    [   20.248363] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
    [   20.248364] Bluetooth: BNEP filters: protocol multicast
    [   20.248368] Bluetooth: BNEP socket layer initialized
    [   54.740879] Bluetooth: RFCOMM TTY layer initialized
    [   54.740894] Bluetooth: RFCOMM socket layer initialized
    [   54.740904] Bluetooth: RFCOMM ver 1.11
    [  150.490635] Bluetooth: hci0 urb ffff8cd7b5409d80 failed to resubmit (113)
    [  261.420492] Bluetooth: hci0 urb ffff8cd6b5bcf180 failed to resubmit (113)
    [  271.446815] Bluetooth: hci0 urb ffff8cd7b8d31780 failed to resubmit (113)
    [  281.473363] Bluetooth: hci0 urb ffff8cd7b8d31000 failed to resubmit (113)
    [  560.611981] Bluetooth: hci0 urb ffff8cd7a8712000 failed to resubmit (113)
    [  570.643209] Bluetooth: hci0 urb ffff8cd7b5409600 failed to resubmit (113)

To me, the culprit seems to be

    [   18.202896] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723b_config.bin failed with error -2

The system is

    Linux aditya-pc 4.9.0-1-MANJARO #1 SMP PREEMPT Mon Dec 5 20:22:30 UTC 2016 x86_64 GNU/Linux

**Comment by lwfinger** [comment]
No, that is not the problem. The latest software allows for the addition of a config file, BUT IT IS NOT MANDATORY for anything but a not yet released device.

For me, the RTL8723BE BT part works. I have no idea where the problem lies.

**Comment by InfiniteCoder** [comment]
It seems to work with Debian based distros(tested on Ubuntu, Kali, Deepin), but doesn't work with Arch based ones(tested on Manjaro and another one). Or maybe it is about customisations done to kernel. If you don't know the answer, likely no one does :(

**Comment by InfiniteCoder** [comment]
BTW which distro are you using?

**Comment by lwfinger** [comment]
I use openSUSE. There have been a lot of problems with the user-space stuff on Manjaro.

**Comment by celiapgt** [comment]
How do we ask for attention of rtl8723a develepers? Maybe they have a better clue.
I use Ubuntu 16.04

**Comment by LeandroPessoa** [comment]
Some clue about this problem?

**Comment by InfiniteCoder** [comment]
How did you get bluetooth to work in openSUSE? when I tried live booting it, bluetooth worked out of the box, but now that I have installed it, it's not working. OTOH, I got wifi working properly by simply adding the ant_sel option, so I am not sure if I need to install this driver.

**Comment by lwfinger** [comment]
Do you have the firmware file available? Check the output of dmesg

**Comment by LeandroPessoa** [comment]
@lwfinger how did you get bluetooth work on opensuse with kernel 4.9?

**Comment by lwfinger** [comment]
Make certain that the BT firmware (/lib/firmware/rtl_bt/rtl8723b_fw.bin) is installed, that the BT modules are configured in the kernel, and boot.

**Comment by sunitknandi** [comment]
Remove the tlp package.

If you are on Manjaro with Linux 4.9, a simple
`pacman -Rc tlp tlp-rdw`
and rebooting does the job. Basically you just remove the tlp packages. And voila, BT is working for me.

The number of duplicates on this topic is immense. A tlp conflict is confusing everyone out here.

**Comment by milkice233** [comment]
@sunitknandi Thanks! That solved it
I'm wondering if the uninstall of tlp will case the misbehave of the system,but currently everything is good.

**Comment by deojames** [comment]
had the same issue, problem solved after removing tlp & tlp-drw on ubuntu 17.04, guessing this tlp was messing up

**Comment by karaseek** [comment]
@sunitknandi It really works for me on openSUSE Tumbleweed with kernel v4.11.8-1. Thanks!

**Comment by xavier83** [comment]
people who have problem with tlp don't have to uninstall it completely, just setting USB_BLACKLIST_BTUSB=1 in `/etc/default/tlp` and rebooting solved the problem for me.

**Comment by faultyfuse** [comment]
Same issue with "Kali Linux" hopefully one of these solves it.

**Comment by glats** [comment]
Same issue with kali linux but i don't have installed tlp-drw

**Comment by InfiniteCoder** [comment]
@glats Do you have tlp installed? If both are not there, then it could be some other issue

**Comment by faultyfuse** [comment]
Thanks will try! I do appreciate it!

**Comment by dguerrini** [comment]
I'm using debian stretch 4.9.0.7-amd64 kernel, don't have tlp installed, have already moved rtl8723b_config.bin to proper folder just so i don't see the message while in boot, and my bluetooth does not work. Can someone help?

**Comment by InfiniteCoder** [comment]
@dguerrini bluetooth works to some extent on kernel 4.17(it causes issues for WiFi). Haven't tested 4.18 yet
