### ISSUE TITLE
RTL8723ae slowness/connectivity issues (antenna selection)

### ISSUE THREAD

**Issue by grenzor** [lwfinger/rtlwifi_new#188]
A fix was applied for RTL8723be users who experienced slowness/disconnection/connectivity issues and from my experience RTL8723ae also face the same problems, possibly because of the same antenna issues.

------------------------------------

Some info that could help:

Currently using a laptop connecting wirelessly to a router that is about 5-10m away. Not sure how to see if I have access to the wifi card (I can connect to the internet using my laptop if that is what you mean)

user@user ~ $ iw dev wlan0 station dump
Station dc:1a:41:b6:1c:56 (on wlan0)
inactive time: 124 ms
rx bytes: 6401119
rx packets: 9759
tx bytes: 534841
tx packets: 4490
tx retries: 0
tx failed: 0
signal: -72 dBm
signal avg: -72 dBm
tx bitrate: 72.2 MBit/s MCS 7 short GI
authorized: yes
authenticated: yes
preamble: long
WMM/WME: yes
MFP: no

Some more (maybe) helpful info from iwconfig:

Tx-Power=20 dBm Retry short limit:7 RTS thr=2347 B Fragment thr:off
Power Management:off
Link Quality=38/70 Signal level=-68 dBm

**Comment by lwfinger** [comment]
Have you tried the new code? Yes, your device is the computer or tablet that has the RTL8723AE attached.

**Comment by dkm635** [comment]
i am having the same issue on kali (SMP Debian 4.6.4-1kali1 (2016-07-21)
).
i tried to fix it like ubuntu but make fails, i have tried your 
i have tried it after installing linux headers 
tried ur rock.btco... branch and master as well

please try to fix this for  kali , it's been year waiting please help

**Comment by lwfinger** [comment]
I cannot fix the build on Kali without specific listing of the errors in the build. Were you thinking that I would install Kali and repeat your entire "experiment"? Unless I am getting paid a lot of money, that will never happen!!!!!

**Comment by dkm635** [comment]
hah, got me , got me good , 
well i cant ask for anything more when you have maintained this whole repository . 
it's almost enough for me that it works on ubuntu , but kali is also a good distro .  
////////////////////////////
i think you are right about, build having errors
seems like some basic dependencies are not fulfilled
  please guide me from where i need to start , 
i have read your previous conversations on this same topic , but give it a try once more 
///////////////////////////
if i had that much money i could have bought a different adapter

**Comment by dkm635** [comment]
can i somewhere find the list of libraries needed for compilation of these drivers , my adapter is 8723be

**Comment by lwfinger** [comment]
No libraries are needed other than the ones needed to run make and gcc. What you need are the sources for the kernel headers, and there needs to be a link so that /lib/modules/$(uname -r)/build points to the directory with that "include" directory. On openSUSE, the command "sudo zypper install gcc make kernel-dev" is what you need. On distro xxxxx, similar apt-get, dnf. yum, or ????? commands are needed. You need to consult your distro's documentation and/or forum to get the command that is needed.

**Comment by dkm635** [comment]
so this means, i need to recompile/mod the kernel, so that  "/lib/modules/$(uname -r)/build " can point to "include " directory in your code   
//////please confirm that it's the point, I need to start at http://docs.kali.org/development/recompiling-the-kali-linux-kernel 
thank you for your time.

**Comment by dkm635** [comment]
and what part in kernel i am supposed to edit/add/replace?  kernel headers?

**Comment by dkm635** [comment]
ok ok i  found the include directory under linux-header-xxxx-amd64..
but i dont know if i am supposed to edit only my "rtl8723be.h" or common.h under /rtl8723 
honestly , i dont know how to make the link b/w  "/lib/modules/$(uname -r)/build" and that include directory pls pls pls help

**Comment by lwfinger** [comment]
You should not need to edit any of the files in this repo.

I installed kali on a junk VM that I use to install various distros. After installation, I did the following (as root):

apt-get update
apt-get update
apt-get dist-upgrade
I then rebooted, followed by:
apt-get install linux-headers-$(uname -r)

At that point, I could build rtlwifi_new without any changes to the rtlwifi_new code.

You will need to be running kernel 4.9. Kali does not currently provide kernel headers for any other kernel.

**Comment by dkm635** [comment]
i messed up , later yestrdy night i ran every line of make file manually 
then 
modeprobe -rv rtl8723be 
then on 
modprobe -v 
its giving the "EXEC error " 
its not inserting the adapter

**Comment by dkm635** [comment]
i was runnung latest build 
except i didn't run the command dist-upgrade 
will dist-upgrade fix it

**Comment by dkm635** [comment]
thanx for giving it your time , ihd really appreciate it

**Comment by lwfinger** [comment]
Without dist-upgrade, I was running kernel 4.6, and the kernel headers are only available for kernel 4.9!!!! You figure it out.

**Comment by dkm635** [comment]
it works, ,thank You .
