### ISSUE TITLE
3.16 Kernel panic 

### ISSUE THREAD

**Issue by MT00x** [lwfinger/rtlwifi_new#192]
Immediatly after starting wpa_supplicant I have a kernel panic 
[kernel panic.txt](https://github.com/lwfinger/rtlwifi_new/files/663898/kernel.panic.txt)
The issue seam to be in base.c when from function setup_special_tx  rtl_lps_leave(hw) is called

Driver: rtl8192cu
Kernel: 3.16.1
CPU: Arm
Best regards

**Comment by lwfinger** [comment]
I just pushed a fix for this kernel panic. If it does not fix your system, please let me know. In the meantime, I am closing this issue.

**Comment by MT00x** [comment]
Thanks guy, works perfectly!
