### ISSUE TITLE
Driver Crash

### ISSUE THREAD

**Issue by MT00x** [lwfinger/rtlwifi_new#193]
Hi,

Sometimes happens the driver inexplicably crash and wifi stop working
(I've installed the master version, update to fix this issue "Kernel panic #192"

Driver: rtl8192cu
Kernel: 3.16.1
CPU: Arm
Best regards

[driver_crash_2.txt](https://github.com/lwfinger/rtlwifi_new/files/670470/driver_crash_2.txt)

**Comment by lwfinger** [comment]
I'm not sure if this is specific to ARM architecture, or the IT regulatory domain. I just pushed a change that should fix it if the latter. Please pull and try again.

**Comment by MT00x** [comment]
Hello, I'm starting the with latest, I'll let you know asap

Thanks

**Comment by MT00x** [comment]
Unfortunately same error happened,

If you would like I can make some specific tests.

Let me know

Thanks
[driver_crash_3.txt](https://github.com/lwfinger/rtlwifi_new/files/674046/driver_crash_3.txt)

**Comment by MT00x** [comment]
Calling 
iw reg set XY 
always cause the issue..

(where XY is any region I tried, AL, IT, US, BG... and many more)

Thanks

**Comment by lwfinger** [comment]
That command works fine on my 4.10-rc1 kernel. I will have to see if I can get my hands on a laptop that will run a kernel as old as 3.16. I know that my core i7 would not.

**Comment by MT00x** [comment]
If I can make some more specific test that can help you, please let me kwnow

**Comment by lwfinger** [comment]
I just added some code that might help. Please pull and retest.

**Comment by MT00x** [comment]
Now the problem occurs occasionaly after some hours worked well

`[Wed Jan 18 05:06:36 2017] wlan0: deauthenticated from 00:16:0a:09:a7:3c (Reason: 1=UNSPECIFIED)
[Wed Jan 18 05:06:36 2017] cfg80211: Calling CRDA for country: IT
[Wed Jan 18 05:06:37 2017] ------------[ cut here ]------------
[Wed Jan 18 05:06:37 2017] WARNING: CPU: 0 PID: 13894 at net/wireless/reg.c:1806 reg_process_hint+0x320/0x410()
[Wed Jan 18 05:06:37 2017] Modules linked in: rtl8192cu(O) rtl8192c_common(O) btcoexist(O) rtl_usb(O) rtlwifi(O) uvcvideo ak5702 videobuf2_vmalloc videobuf2_memops videobuf2_core i2c_at91 ohci_at91 ohci_hcd [last unloaded: rtlwifi]
[Wed Jan 18 05:06:37 2017] CPU: 0 PID: 13894 Comm: kworker/0:0 Tainted: G        W  O  3.16.1 #1
[Wed Jan 18 05:06:37 2017] Workqueue: events reg_todo
[Wed Jan 18 05:06:37 2017] Backtrace:
[Wed Jan 18 05:06:37 2017] [<c000c318>] (dump_backtrace) from [<c000c5d8>] (show_stack+0x18/0x1c)
[Wed Jan 18 05:06:37 2017]  r7:c040778c r6:0000070e r5:00000009 r4:00000000
[Wed Jan 18 05:06:37 2017] [<c000c5c0>] (show_stack) from [<c0463ed4>] (dump_stack+0x20/0x28)
[Wed Jan 18 05:06:37 2017] [<c0463eb4>] (dump_stack) from [<c001763c>] (warn_slowpath_common+0x6c/0x8c)
[Wed Jan 18 05:06:37 2017] [<c00175d0>] (warn_slowpath_common) from [<c0017700>] (warn_slowpath_null+0x24/0x2c)
[Wed Jan 18 05:06:37 2017]  r8:c05fd11c r7:cda3af94 r6:c0619c50 r5:c09b0120 r4:cda3af80
[Wed Jan 18 05:06:37 2017] [<c00176dc>] (warn_slowpath_null) from [<c040778c>] (reg_process_hint+0x320/0x410)
[Wed Jan 18 05:06:37 2017] [<c040746c>] (reg_process_hint) from [<c04078dc>] (reg_todo+0x60/0x194)
[Wed Jan 18 05:06:37 2017]  r9:00000000 r8:c05fd11c r7:00000000 r6:cffdd100 r5:cf13f040 r4:c0619c8c
[Wed Jan 18 05:06:37 2017] [<c040787c>] (reg_todo) from [<c002b920>] (process_one_work+0x108/0x42c)
[Wed Jan 18 05:06:37 2017]  r10:ce060030 r9:00000000 r8:c05fd11c r7:00000000 r6:cffdd100 r5:cf13f040
[Wed Jan 18 05:06:37 2017]  r4:c0619c8c
[Wed Jan 18 05:06:37 2017] [<c002b818>] (process_one_work) from [<c002c600>] (worker_thread+0x180/0x610)
[Wed Jan 18 05:06:37 2017]  r10:cf13f040 r9:c05fd11c r8:00000008 r7:cf13f058 r6:c05fd12c r5:ce060000
[Wed Jan 18 05:06:37 2017]  r4:c05fd11c
[Wed Jan 18 05:06:37 2017] [<c002c480>] (worker_thread) from [<c0032118>] (kthread+0xbc/0xd8)
[Wed Jan 18 05:06:37 2017]  r10:00000000 r9:00000000 r8:00000000 r7:c002c480 r6:cf13f040 r5:00000000
[Wed Jan 18 05:06:37 2017]  r4:cf10fda0
[Wed Jan 18 05:06:37 2017] [<c003205c>] (kthread) from [<c00097d0>] (ret_from_fork+0x14/0x24)
[Wed Jan 18 05:06:37 2017]  r7:00000000 r6:00000000 r5:c003205c r4:cf10fda0
[Wed Jan 18 05:06:37 2017] ---[ end trace 24e1b0ffea3b5e3f ]---
[Wed Jan 18 05:06:37 2017] cfg80211: Calling CRDA for country: IT
[Wed Jan 18 05:06:37 2017] wlan0: authenticate with 00:16:0a:09:a7:3c
[Wed Jan 18 05:06:37 2017] wlan0: send auth to 00:16:0a:09:a7:3c (try 1/3)
[Wed Jan 18 05:06:37 2017] wlan0: send auth to 00:16:0a:09:a7:3c (try 2/3)
[Wed Jan 18 05:06:38 2017] wlan0: send auth to 00:16:0a:09:a7:3c (try 3/3)
[Wed Jan 18 05:06:38 2017] wlan0: authentication with 00:16:0a:09:a7:3c timed out
[Wed Jan 18 05:06:51 2017] wlan0: authenticate with 00:16:0a:09:a7:3c
[Wed Jan 18 05:06:51 2017] wlan0: direct probe to 00:16:0a:09:a7:3c (try 1/3)
[Wed Jan 18 05:06:51 2017] wlan0: direct probe to 00:16:0a:09:a7:3c (try 2/3)
[Wed Jan 18 05:06:51 2017] wlan0: direct probe to 00:16:0a:09:a7:3c (try 3/3)
[Wed Jan 18 05:06:51 2017] wlan0: authentication with 00:16:0a:09:a7:3c timed out
[Wed Jan 18 05:06:59 2017] wlan0: authenticate with 00:16:0a:09:a7:3c
[Wed Jan 18 05:06:59 2017] wlan0: direct probe to 00:16:0a:09:a7:3c (try 1/3)
[Wed Jan 18 05:06:59 2017] wlan0: direct probe to 00:16:0a:09:a7:3c (try 2/3)
[Wed Jan 18 05:07:00 2017] wlan0: direct probe to 00:16:0a:09:a7:3c (try 3/3)
[Wed Jan 18 05:07:00 2017] wlan0: authentication with 00:16:0a:09:a7:3c timed out
[Wed Jan 18 05:07:32 2017] uvcvideo: Failed to query (GET_LEN) UVC control 7 on unit 4: -32 (exp. 2).
[Wed Jan 18 05:07:33 2017] uvcvideo: Failed to query (GET_LEN) UVC control 7 on unit 4: -32 (exp. 2).
[Wed Jan 18 05:08:09 2017] wlan0: authenticate with 00:16:0a:09:a7:3c
[Wed Jan 18 05:08:09 2017] wlan0: direct probe to 00:16:0a:09:a7:3c (try 1/3)
[Wed Jan 18 05:08:09 2017] wlan0: direct probe to 00:16:0a:09:a7:3c (try 2/3)
[Wed Jan 18 05:08:09 2017] wlan0: direct probe to 00:16:0a:09:a7:3c (try 3/3)
[Wed Jan 18 05:08:10 2017] wlan0: authentication with 00:16:0a:09:a7:3c timed out
[Wed Jan 18 05:09:17 2017] wlan0: authenticate with 00:16:0a:09:a7:3c
[Wed Jan 18 05:09:17 2017] wlan0: send auth to 00:16:0a:09:a7:3c (try 1/3)
[Wed Jan 18 05:09:17 2017] wlan0: send auth to 00:16:0a:09:a7:3c (try 2/3)
[Wed Jan 18 05:09:17 2017] wlan0: send auth to 00:16:0a:09:a7:3c (try 3/3)
[Wed Jan 18 05:09:17 2017] wlan0: authentication with 00:16:0a:09:a7:3c timed out
[Wed Jan 18 05:10:57 2017] wlan0: authenticate with 00:16:0a:09:a7:3c
[Wed Jan 18 05:10:57 2017] wlan0: direct probe to 00:16:0a:09:a7:3c (try 1/3)
[Wed Jan 18 05:10:57 2017] wlan0: direct probe to 00:16:0a:09:a7:3c (try 2/3)
[Wed Jan 18 05:10:57 2017] wlan0: direct probe to 00:16:0a:09:a7:3c (try 3/3)
[Wed Jan 18 05:10:58 2017] wlan0: authentication with 00:16:0a:09:a7:3c timed out
[Wed Jan 18 05:12:33 2017] wlan0: authenticate with 00:16:0a:09:a7:3c
[Wed Jan 18 05:12:33 2017] wlan0: send auth to 00:16:0a:09:a7:3c (try 1/3)
[Wed Jan 18 05:12:33 2017] wlan0: authenticated
`
