### ISSUE TITLE
Compilation error after changes made four hours ago

### ISSUE THREAD

**Issue by danielgulliver** [lwfinger/rtlwifi_new#194]
I noticed that 4 hours ago, the country code for Italy was added to regd.c on line 35, among other changes. The program failed to compile, but after commenting out the changes, the program compiles successfully. Could it be that there is no corresponding definition of COUNTRY_CODE_ITALY in regd.h? (I have next to no experience programming in C.)

I am running Linux Mint 18 (based on Ubuntu 16.04) with kernel 4.4.0-57-generic.

Running `make` produces the following output:
```
make -C /lib/modules/4.4.0-57-generic/build M=/home/daniel/rtlwifi_new modules
make[1]: Entering directory '/usr/src/linux-headers-4.4.0-57-generic'
  CC [M]  /home/daniel/rtlwifi_new/regd.o
/home/daniel/rtlwifi_new/regd.c:35:3: error: ‘COUNTRY_CODE_ITALY’ undeclared here (not in a function)
  {COUNTRY_CODE_ITALY, "EC"},
   ^
scripts/Makefile.build:258: recipe for target '/home/daniel/rtlwifi_new/regd.o' failed
make[2]: *** [/home/daniel/rtlwifi_new/regd.o] Error 1
Makefile:1420: recipe for target '_module_/home/daniel/rtlwifi_new' failed
make[1]: *** [_module_/home/daniel/rtlwifi_new] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.4.0-57-generic'
Makefile:58: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by lwfinger** [comment]
You are right, there is no COUNTRY_CODE_ITALY. I have reverted the patch for now.
