### ISSUE TITLE
rtl8812AE driver

### ISSUE THREAD

**Issue by sivaswami** [lwfinger/rtlwifi_new#195]
Hi,
I notice my 5 Mhz connections are dropping
I was looking for latest  RTL8812AE driver. But I find rtl8821AE driver in this list. 

can I use rtl8821ae driver in place of rtl8812ae driver ?
If so kindly help me with the steps: 
I tried with make && sudo make install. is it enough ?

any suggestions ?

**Comment by twdkeule** [comment]
Hi,
I had some troubles with my rtl8812AE card (D-link DWA-582). 
I solved them by removing network-manager and installing wicd-gtk instead.
After this I could connect to an AP, but speeds were limited to 2Mbps.
Then I installed the drivers from this repo (make && sudo make install) and added " rtl8821ae"  to /etc/modules and rebooted. Now I'm reaching speeds of 32Mbps. 

As far as I can tell the rtl8812AE-cards use the rtl8821ae driver

**Comment by randreev1321** [comment]
> Hi,
> I had some troubles with my rtl8812AE card (D-link DWA-582).
> I solved them by removing network-manager and installing wicd-gtk instead.
> After this I could connect to an AP, but speeds were limited to 2Mbps.
> Then I installed the drivers from this repo (make && sudo make install) and added " rtl8821ae"  to /etc/modules and rebooted. Now I'm reaching speeds of 32Mbps.
> As far as I can tell the rtl8812AE-cards use the rtl8821ae driver

This works for me too.
