### ISSUE TITLE
RTL8723be unstable Ubuntu

### ISSUE THREAD

**Issue by mindartur** [lwfinger/rtlwifi_new#196]
There is new Acer X541UV laptop and Realtek rtl8723be in it.
On windows 10 wifi works fine, giving ~10 mb/s average downloading speed.
But on Ubuntu (I have tried Ubuntu 14.04, Ubuntu 16.04, Kubuntu 16.04, different kernel versions) wifi is very unstable when I try to download something large. The speed usually goes up with big fluctuations to 2-8 mb/s and  then drops dramatically to zero. Then the wifi disconnects and do not connect until I restart the system or network manager.

Things that I have tried:
1) Install new version of driver from this repository (with every new kernel and with reboot of course)
2) New kernels (now I have Ubuntu 14.04 with 4.9.0-040900 kernel)
3) Trying to choose fixed antenna (ant_sel=1 works better than ant_sel=2)
4) Turn off energy saving (options like fwlps=0 and  ips=0)

In syslog there are usually these lines:

Dec 25 18:53:02 arturm udisksd[2250]: Acquired the name org.freedesktop.UDisks2 on the system message bus
Dec 25 18:55:31 arturm wpa_supplicant[1227]: wlan0: CTRL-EVENT-SCAN-STARTED
Dec 25 18:56:07 arturm kernel: [  237.105241] [drm:intel_pipe_update_end [i915]] *ERROR* Atomic update failure on pipe A (start=14511 end=14512)$
Dec 25 18:56:15 arturm kernel: [  245.088533] [drm:intel_pipe_update_end [i915]] *ERROR* Atomic update failure on pipe A (start=14990 end=14991)$
Dec 25 18:56:24 arturm kernel: [  253.904504] [drm:intel_pipe_update_end [i915]] *ERROR* Atomic update failure on pipe A (start=15519 end=15520)$
Dec 25 18:56:29 arturm kernel: [  258.904224] [drm:intel_pipe_update_end [i915]] *ERROR* Atomic update failure on pipe A (start=15819 end=15820)$
Dec 25 18:56:35 arturm kernel: [  264.704092] [drm:intel_pipe_update_end [i915]] *ERROR* Atomic update failure on pipe A (start=16167 end=16168)$
Dec 25 18:57:31 arturm kernel: [  321.094270] rtlwifi: AP off, try to reconnect now
Dec 25 18:57:31 arturm kernel: [  321.094346] wlan0: Connection to AP 18:a3:e8:35:c3:58 lost
Dec 25 18:57:31 arturm wpa_supplicant[1227]: wlan0: CTRL-EVENT-DISCONNECTED bssid=18:a3:e8:35:c3:58 reason=4 locally_generated=1
Dec 25 18:57:31 arturm NetworkManager[845]: <warn> Connection disconnected (reason -4)
Dec 25 18:57:31 arturm NetworkManager[845]: <info> (wlan0): supplicant interface state: completed -> disconnected
Dec 25 18:57:31 arturm wpa_supplicant[1227]: wlan0: CTRL-EVENT-SCAN-STARTED
Dec 25 18:57:31 arturm NetworkManager[845]: <info> (wlan0): supplicant interface state: disconnected -> scanning
Dec 25 18:57:46 arturm NetworkManager[845]: <warn> (wlan0): link timed out.
Dec 25 18:57:46 arturm NetworkManager[845]: <info> (wlan0): device state change: activated -> failed (reason 'SSID not found') [100 120 53]
Dec 25 18:57:46 arturm NetworkManager[845]: <info> NetworkManager state is now DISCONNECTED
Dec 25 18:57:46 arturm NetworkManager[845]: <warn> Activation (wlan0) failed for connection 'dom5A'
Dec 25 18:57:46 arturm whoopsie[1215]: offline
Dec 25 18:57:46 arturm dbus[790]: [system] Activating service name='org.freedesktop.nm_dispatcher' (using servicehelper)
Dec 25 18:57:46 arturm NetworkManager[845]: <info> (wlan0): device state change: failed -> disconnected (reason 'none') [120 30 0]
Dec 25 18:57:46 arturm NetworkManager[845]: <info> (wlan0): deactivating device (reason 'none') [0]
Dec 25 18:57:46 arturm dbus[790]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'
Dec 25 18:57:46 arturm NetworkManager[845]: <info> (wlan0): canceled DHCP transaction, DHCP client pid 1305
Dec 25 18:57:46 arturm avahi-daemon[833]: Withdrawing address record for 192.168.1.7 on wlan0.
Dec 25 18:57:46 arturm avahi-daemon[833]: Leaving mDNS multicast group on interface wlan0.IPv4 with address 192.168.1.7.
Dec 25 18:57:46 arturm avahi-daemon[833]: Interface wlan0.IPv4 no longer relevant for mDNS.
Dec 25 18:57:46 arturm NetworkManager[845]: <info> Removing DNS information from /sbin/resolvconf

**Comment by lwfinger** [comment]
If you have TWO antennas, then you should not mention that parameter at all. That will let the driver pick the better of the two.

Yes, I know there is a problem with the rate under heavy load. Unfortunately, I know nothing of the chip internals, and the Realtek people have a higher priority project - ordered by their bosses. Of course, patches are welcome.

**Comment by kkoutso** [comment]
Hi, hp-15-ay104nv with RTL8723BE. Mate 16.04.
I cloned and compiled yesterday. Ant-sel had to be the reverse than the original distro setting (2->1) and BLE does not work at all. No scanning, not scanned.

**Comment by lwfinger** [comment]
You need to prove that the ant_sel setting has changed. Use the command 'sudo iw dev wlan0 scan | grep signal' with the various values with ant_sel.

**Comment by kkoutso** [comment]
Thanks a lot for the quick reply. Actually, no further problems with the antenna. I just changed from 1 to 2 when I used the compiled modules and I had again APs detected (when I installed mate 16.04 I had to configure antenna 1 in /etc/modprobe.d/ with the distro driver) . 
My concern stands for some disconnections and low performance but I do not have the complete picture yet. The nm-applet crashes after boot, it might not be relevant but I report it just in case. 
The main problem right now is that the BLE does not seem to work at all. So, "no scanning not scanned" refers to BLE, sorry for the misunderstanding.

**Comment by efkan** [comment]
The issues the same with [mine](https://github.com/lwfinger/rtlwifi_new/issues/184) actually. I could get rid of RTL8723BE issue by buying [a new adapter](http://www.tp-link.com/us/products/details/cat-5520_TL-WN725N.html). Because the issue has taken too much time.

lwfinger's this repo are awesome but unfortunately it might be useless on some devices and distros.

However, I'm sure this is a big work that lwfinger can manage its 99% succesfully. So, that's mean completely perfect! There are lots of distro, machine etc. 
%1 should be RTL8723BE with Ubuntu :)
