### ISSUE TITLE
rtl8723be: Invalid argument under Kernel 4.8.13-1

### ISSUE THREAD

**Issue by AWegner1** [lwfinger/rtlwifi_new#197]
Hello,

first, im using ARCHLINUX. Before updating my kernel from 4.7.x to 4.8.13 everything went fine.
After updating, the kernelmodule rtl8723be_dkms could not be load anymore.
I checked out the newest version of the master-branch, compiled and tried to load, but all i get is the following output:
`$ sudo modprobe rtl8723be_dkms ant_sel=1
modprobe: ERROR: could not insert 'rtl8723be_dkms': Invalid argument
[alex@ALEX-NB-ARCH rtlwifi_new]$ sudo modprobe rtl8723be_dkms ant_sel=1 -vv
modprobe: INFO: custom logging function 0x40a1e0 registered
insmod /lib/modules/4.8.13-1-ARCH/kernel/drivers/net/wireless/rtlwifi/rtlwifi_dkms.ko 
modprobe: INFO: Failed to insert module '/lib/modules/4.8.13-1-ARCH/kernel/drivers/net/wireless/rtlwifi/rtlwifi_dkms.ko': File exists
insmod /lib/modules/4.8.13-1-ARCH/kernel/drivers/net/wireless/rtlwifi/rtl_pci_dkms.ko 
modprobe: INFO: Failed to insert module '/lib/modules/4.8.13-1-ARCH/kernel/drivers/net/wireless/rtlwifi/rtl_pci_dkms.ko': File exists
insmod /lib/modules/4.8.13-1-ARCH/kernel/drivers/net/wireless/rtlwifi/btcoexist/btcoexist_dkms.ko 
modprobe: INFO: Failed to insert module '/lib/modules/4.8.13-1-ARCH/kernel/drivers/net/wireless/rtlwifi/btcoexist/btcoexist_dkms.ko': File exists
insmod /lib/modules/4.8.13-1-ARCH/kernel/drivers/net/wireless/rtlwifi/rtl8723be/rtl8723be_dkms.ko ant_sel=1 ant_sel=1
modprobe: INFO: Failed to insert module '/lib/modules/4.8.13-1-ARCH/kernel/drivers/net/wireless/rtlwifi/rtl8723be/rtl8723be_dkms.ko': Invalid argument
modprobe: ERROR: could not insert 'rtl8723be_dkms': Invalid argument
modprobe: INFO: context 0x26141d0 released`
The last lines of dmesg are:

`[ 1191.971568] rtl8723be: disagrees about version of symbol rtl_process_phyinfo
[ 1191.971570] rtl8723be: Unknown symbol rtl_process_phyinfo (err -22)
[ 1191.971683] rtl8723be: disagrees about version of symbol rtl_get_hwinfo
[ 1191.971684] rtl8723be: Unknown symbol rtl_get_hwinfo (err -22)
[ 1191.971720] rtl8723be: disagrees about version of symbol rtl_evm_db_to_percentage
[ 1191.971720] rtl8723be: Unknown symbol rtl_evm_db_to_percentage (err -22)
[ 1191.971734] rtl8723be: disagrees about version of symbol rtl_query_rxpwrpercentage
[ 1191.971734] rtl8723be: Unknown symbol rtl_query_rxpwrpercentage (err -22)
[ 1191.971747] rtl8723be: disagrees about version of symbol rtl_get_tcb_desc
[ 1191.971748] rtl8723be: Unknown symbol rtl_get_tcb_desc (err -22)
[ 1191.971760] rtl8723be: disagrees about version of symbol rtl_btc_get_ops_pointer
[ 1191.971760] rtl8723be: Unknown symbol rtl_btc_get_ops_pointer (err -22)
`
Something wrong at my system or something wrong with the driver?
Thanks for help
lg Alex

**Comment by lwfinger** [comment]
You have the wrong kernel headers installed.
