### ISSUE TITLE
iw does not see the device

### ISSUE THREAD

**Issue by konstantinmiller** [lwfinger/rtlwifi_new#198]
Hi,

I am using the driver for the TL-WN822N. It works fine but iw does not see the device.

I need iw to see it in order to add a monitor interface to the device.

Is that a problem of the driver or one of my machine?

-- Konstantin

**Comment by lwfinger** [comment]
What is the USB ID for this device as shown by the lsusb command?

**Comment by konstantinmiller** [comment]
ID 2357:0108

**Comment by lwfinger** [comment]
I have no idea what that device that is. The official USB ID archives to not contain that device. It had 2357:0106 and 2357:0109, but not 0108. Similarly, there are no drivers in Linux mainline, nor in my repo that recognize that device.

**Comment by konstantinmiller** [comment]
I double checked. The output is: Bus 001 Device 017: ID 2357:0108.

That's interesting. I bought it on the German Amazon (https://www.amazon.de/dp/B00416Q5KI/ref=cm_sw_em_r_mt_dp_Si9BybFRZ0SMP). I don't think it's a fake.

**Comment by lwfinger** [comment]
It is real. That 2357:0108 device is a V4, which apparently contains an RTL8192EU chip, which is NOT handled by any driver in this repo. I do have some other repos for USB chips, but not that one.

Realtek uses the same basic driver for most of its USB chips by using lots of conditionals in the compilation. Look in a file named autoconf.h to see if CONFIG_IOCTL_CFG80211 is defined. Without that, iw will not work.

One other option is to use a v4.9 kernel which has driver rtl8xxxu. It supports 8192eu, but does not (yet) have the 2357:0108 ID. Apparently, 2357:0109 does work with the driver.

**Comment by mirh** [comment]
Should be in by now
https://github.com/torvalds/linux/commit/c14239f23adb80aa2532909e312986317ba3cd09
