### ISSUE TITLE
RTL8723BE drops the connection on OpenSuse Leap 42.2

### ISSUE THREAD

**Issue by efkan** [lwfinger/rtlwifi_new#199]
Hello,

I have installed OpenSuse 42.2 (Gnome) to able to work with RTL8723BE wifi card.

However the wifi drops connection in a couple of minutes after laptop started.

I'd be appreciated for any help.

I have done these step:
* Cloned this repo 
* Run the commands below 
 in the cloned repo directory `make & sudo make install`
 `sudo modprobe -r rtl8723be`
 `sudo modprobe rtl8723be ant_sel=2`
 `echo "options rtl8723be ant_sel=2 fwlps=0" | sudo tee /etc/modprobe.d/rtl8723be.conf`
 `reboot`

So, current `rtl8723be.conf` file contains the following line.
`options rtl8723be ant_sel=2 fwlps=0`

Also I tried to use it without `fwlps=0` option.

My `uname -a` output is like this:
`Linux linux-wjbb 4.4.36-8-default #1 SMP Fri Dec 9 16:18:38 UTC 2016 (3ec5648) x86_64 x86_64 x86_64 GNU/Linux`

I had encountered a similar issue in ElementaryOS (https://github.com/lwfinger/rtlwifi_new/issues/184).
Also I tried to run on 3 different HP 14-am107nt notebooks.

**Comment by lwfinger** [comment]
Did you verify that ant_sel=2 is the correct value? To test what value should be used, you need to load the driver with ant_sel values of 0, 1, and 2. For each value run the command

sudo /usr/sbin/iw dev wlan0 scan | egrep "SSID|signal"

Adjust wlan0 to be the name of your device. The current version of this repo DOES NOT need to use the fwlps option. In fact, you should not use any options other than the ant_sel one.

**Comment by efkan** [comment]
Yes, I've verified the ant_sel parameter value.

Wifi works good for 1 minute and I can see the all wifi networks around me after the computer starts. Then it drops the connection and I can not connect again.

**Comment by efkan** [comment]
I guess there some different issues with my computer. 

As we can find on the internet, this driver works for people that has tried the driver and been successful, whose number specifies maybe 97% of the total people who tried this repo.

However, it doesn't work for my RTL8723BE because of maybe a new something on motherboard or on other things. 

@lwfinger, thanks for taking your time to review my issues both of on OpenSUSE and ElementaryOS.

**Comment by lwfinger** [comment]
Would it kill you to show the results that prove the ant_sel is correct? I hope you understand why I will not accept your word!

**Comment by efkan** [comment]
Woops! You're right!  :smiley: 

The results of `sudo iw dev wlp2s0 scan | egrep "SSID|signal"`command in Elementary OS

```
	signal: -50.00 dBm
	SSID: WN
	signal: -62.00 dBm
	SSID: cagankartal
	signal: -72.00 dBm
	SSID: Sezen
	signal: -72.00 dBm
	SSID: TP-LINK_935B31
	signal: -46.00 dBm
	SSID: alya
	signal: -50.00 dBm
	SSID: ishak
	signal: -64.00 dBm
	SSID: phd
	signal: -66.00 dBm
	SSID: URUL
	signal: -66.00 dBm
	SSID: mmertaktas
	signal: -64.00 dBm
	SSID: Duygu
	signal: -64.00 dBm
	SSID: dincer
	signal: -70.00 dBm
	SSID: TTNET_ZyXEL_4P7P
	signal: -58.00 dBm
	SSID: SUPERONLINE_WiFi_6073
	signal: -74.00 dBm
	SSID: onur
	signal: -68.00 dBm
	SSID: emircem
	signal: -50.00 dBm
	SSID: nurkam
	signal: -70.00 dBm
	SSID: gozde
	signal: -70.00 dBm
	SSID: KaraKartal
	signal: -68.00 dBm
	SSID: TTNET_ZyXEL_U7KN

```

I returned to my last ElementaryOS backup.

**Comment by lwfinger** [comment]
Ok, -46 dBm is probably right. With other antenna options, what value did you get for your AP, and which one is yours?

**Comment by efkan** [comment]
The other one  cannot found any wireless network. 

"ant_sel=2" works for me. But not now. The connection has been dropped. 

However, sometimes I have to change "ant_sel" option as "1" because with value "2", I cannot find any network.

**Comment by cristianquaglio** [comment]
Hi, people. I've the same problem. How do you resolve it, efkan? Thanks in advance.

**Comment by efkan** [comment]
Unfortunately @cristianquaglio  . I could not overcome this issue. 

(I had bought a nano wifi dongle `TP-LINK TL-WN725N` and I'm using it for now)

Which laptop/desktop do you use? 
I ask for only gathering some statistical data for to figure out that why this driver doesn't work for us.
I use HP with i5-7200U cpu.

**Comment by cristianquaglio** [comment]
Thanks for your response. The mine is a Lenovo with Intel Core i3-4005U CPU @ 4x 1.7GHz
OpenSUSE Leap 42.2 and I'm using NetworkManager.

**Comment by efkan** [comment]
@cristianquaglio , I use linux as my desktop for a couple of months.

However, I recommend thinking of the two clause below:

1. You've read this issue. Also [this](https://github.com/lwfinger/rtlwifi_new/issues/184) is the first issue I've informed. Try to read other issue too. Then if you think these issues the same with yours, don't waste time.

2. Otherwise open a new issue about your case with its details. I believe `lwfinger` or other contributors help you to figure it out. 

Good luck..

**Comment by dguerrini** [comment]
Hi, I have exactly the same laptop as @efkan (hp i5 7200) and I'm using Debian 9.5 right now, and am having the exact same problem. Sometimes it takes longer, sometimes its one restart of rtl8723be after another. I was using Elementary OS, and had it functioning alright with ant_sel=2, but now, only ant=1 works and not for very long. My kernel is 4.9.0-7.

**Comment by lwfinger** [comment]
I understand why your optimum ant_sel value changes from 2 to 1, but once you make that change, you should not have problems. Are you running the software from this repo? If not, then try the extended branch here. Otherwise, you need to verify that you are not having a NetworkManager problem. Version 1.11.x seems to be probalematic. I am using 1.5.10.

**Comment by dguerrini** [comment]
Ok. So NetworkManager is 1.6.2 and when I download this repo and run "make install" I get:
> Entering directory '/lib/modules/4.9.0-7-amd64/build'
> make[1]: *** No rule to make target 'modules'.  Stop.

I have kernel headers, have build-essentials, gcc and git, still, this is the message I get.
Thank you for helping!

**Comment by lwfinger** [comment]
You have not done the header preparation step correctly. You will need to find out how to build external kernel modules for your distribution, For me, all I need to do is install kernel-devel, but that is for openSUSE. I know nothing of Ubuntu!

**Comment by efkan** [comment]
Hello @dguerrini ,

Actually, thanks to @lwfinger 's driver (this repo), I can use HP laptop's wifi adapter for a couple of months.
I had tracked [this solution](https://github.com/lwfinger/rtlwifi_new/issues/317#issuecomment-367107291).
But be careful. If you choose one of the latest kernel versions, you may encounter different problems because your OS has not been designed to work for the kernel version you evaluated (On my ElementaryOS Wing Panel didn't work properly etc).
I recommend of trying kernel 4.15.3. And never delete your old kernel. If you have another issue you can return former kernel by using the same way.

Sometimes () my OS gets kernel update then I have to re-install the driver by running the commands below from its folder:

```
sudo make install
sudo modprobe -r <<YOUR WIRELESS DRIVER CODE>>
sudo modprobe <<YOUR WIRELESS DRIVER CODE>>
```

It takes my just one minute.

Hope this helps..

**Comment by dguerrini** [comment]
Yes it helped! I found the way through building external kernel modules in debian. But would you guys happen to know why I still have to restart rtl8723be every time I boot? I tried editing grub file with ant_sel=2 fwlps=0 ips=0, but it only works when i restart it manually in terminal after initializing. Of course I'm happy to have a good connection now, but it would be nice to have this working automatically...

**Comment by efkan** [comment]
On the solution I've recommended, you don't need to make anything after running the commands of `sudo modprobe -r <<YOUR WIRELESS CODE>>` and `sudo modprobe <<YOUR WIRELESS CODE>>`.

Unfortunately I cannot comment to your solution. I have never built external kernel modules in Debian.

**Comment by lwfinger** [comment]
@dguerrini - You do not put those options in a grub file. You need to create a file (as root) named /etc/modprobe.d/50-rtl8723be.conf with a line that says "options rtl8723be ant_sel=2" That will set the option on startup. I do not think you need either of the "ps" options.

**Comment by dguerrini** [comment]
@lwfinger yes, it works perfectly. No need of "ps" options, as you said. Thank you very much.
