### ISSUE TITLE
Error while executing 'make': No rule to make target 'modules'

### ISSUE THREAD

**Issue by vyeshwanth** [lwfinger/rtlwifi_new#205]
***rtl8723be***
This is the complete output of 'make'
make -C /lib/modules/4.4.39-1-MANJARO/build M=/home/yeshwanth/rtlwifi_new modules
make[1]: Entering directory '/usr/lib/modules/4.4.39-1-MANJARO/build'
make[1]: *** No rule to make target 'modules'.  Stop.
make[1]: Leaving directory '/usr/lib/modules/4.4.39-1-MANJARO/build'
make: *** [Makefile:58: all] Error 2
P.S I have installed proper linux headers

**Comment by Deus-Rex** [comment]
How did you solve this?
