### ISSUE TITLE
Unable to get bluetooth working RTL8821AE on Ubuntu 16.04.1

### ISSUE THREAD

**Issue by seppi91** [lwfinger/rtlwifi_new#207]
I just can't get bluetooth to work properly. 
I can't discover any devices, and they also can't discover me.
Bluetooth service is also giving some errors on upstart.

I've installed this package by cloning the master branch as it seems to be the most recent, and do a 'make' and 'sudo make install'. After this i've rebooted.

I've created a gist with some debugging information
https://gist.github.com/seppi91/2ecb065e7e3f109ef46b9e5d85d8c0d8

**Comment by lwfinger** [comment]
If you are going to post unsolicited dmesg output, then post the ENTIRE output. Who knows what might be important?

The BT driver does not create any files, thus I'm pretty sure it is not consuming all the file handles. There is something wrong with the rest of your system.

**Comment by lwfinger** [comment]
I do not have a kernel as old as 4.4. Using 4.10-rc5, I was able to pair with my cell phone, which is the only BT device I have.

Perhaps, you need a newer kernel.
