### ISSUE TITLE
RTL8723BE refuses to change power state

### ISSUE THREAD

**Issue by mesanu** [lwfinger/rtlwifi_new#211]
Hey

I've been having some issues using the driver. If I manage to get a wifi connection, it lasts all of 30 seconds after boot before i get disconnected and my no wifi networks show up as available (either through network manager or iwlist scan). Unloading and reloading the kernel module doesn't seem to help, neither does restarting NetworkManager or killing wpa_supplicant

Modprobe rtl8723be produces the following output in dmesg
```
[ 5486.395681] rtl8723be 0000:03:00.0: Refused to change power state, currently in D3
[ 5486.396110] rtlwifi: RTL8XXX did not boot from eeprom, check it !!
[ 5486.396160] rtl8723be: Using firmware rtlwifi/rtl8723befw_36.bin
[ 5486.398434] ieee80211 phy6: Selected rate control algorithm 'rtl_rc'
[ 5486.399642] rtl8723be 0000:03:00.0: firmware: direct-loading firmware rtlwifi/rtl8723befw_36.bin
[ 5486.410968] rtlwifi: rtlwifi: wireless switch is on
[ 5486.417279] rtl8723be 0000:03:00.0 wlp3s0f0: renamed from wlan0
[ 5486.498942] rtl8723be: Init MAC failed
[ 5486.566077] rtl8723be: Init MAC failed
[ 5486.619499] rtl8723be: Init MAC failed
[ 5497.048206] rtl8723be: Init MAC failed
[ 5497.102064] rtl8723be: Init MAC failed
```

Here are the contents of my /etc/modprobe.d/rtl8723be.conf file
`options rtl8723be fwlps=0 ips=0 swlps=0`

I'm running Debian 9 right now, but this problem has persisted since I was on Debian 8.6

**Comment by supersaeyan** [comment]
I am also facing this exact issue with identical dmesg.

Why is no one even looking into this.

**Comment by Pant** [comment]
See #324.

**Comment by finnoleary** [comment]
#324 did not fix my problem. I have pulled and remade drivers for my rtl8723be from the latest branch, and I am still encountering the problem above.

**Comment by lwfinger** [comment]
Which branch were you using? I am getting tired of always having to ask this question.

**Comment by finnoleary** [comment]
master branch, I cloned three hours ago. dmesg is almost identical to above (i.e. it displays the `"refused to change power state, currently in D3"`, `"RTL8XXX did not boot from eeprom, check it !!"` and `"Init MAC failed"` along the usual messages).
I'm on Arch Linux, and I've built it (`make && sudo make install`) for both `4.14.33-1-lts` and `4.15.15-1-ARCH`, both of which display the same dmesg output.

**Comment by finnoleary** [comment]
Four hours later, and I reset and reloaded the module, and reconnected to the network fine. That is, until it died 19 seconds later ("AP off, try to reconnect now"). Reloading with the previous options and a blank options file both cause it to log the "XXX did not boot from eeprom" errors, etc.

FYI the options I use (And have used for about 2 months before the errors reoccurred):
```
options rtl8723be fwlps=N swlps=N ips=N ant_sel=1
```

**Comment by lwfinger** [comment]
I do not recommend getting a tarball from GitHub. Doing a 'git clone' gets you so many more options.

You should not need to use any of the *ps options. At one time, there was an error in the handling of power save, but that was fixed a couple of years ago.

The latest commit to the master branch is a fix for the "AP off ..." message.

Which version of the driver was used for 2 months before the errors reoccurred? Note that whatever is causing the device not to be detected is outside the driver, which presents a table of devices that are handled. As long as the device is seen in a PCI bus scan, then the driver will be loaded. Similarly, I have no idea why the device cannot boot from EEPROM.

**Comment by lwfinger** [comment]
If you get a firmware crash when using the default for fwlps, my conclusion would be either faulty firmware or hardware. The problem with device detection tips the scale toward a hardware problem. To isolate a problem with the firmware, the md5sums should be
1850c1308fbcd95e9f6a7f58ede1e35f  /lib/firmware/rtlwifi/rtl8723befw_36.bin
bc828ddc6cd700abb79a8df5794bcf04  /lib/firmware/rtlwifi/rtl8723befw.bin

I am not sure how a misconfigured UEFI could cause these problems. When the device is detected, please post the section of output for the rtl8723be from the command 'sudo lspci -nn -vvv".

**Comment by finnoleary** [comment]
The results of those show:
```
$ md5sum /lib/firmware/rtlwifi/rtl8723be*
1850c1308fbcd95e9f6a7f58ede1e35f  /lib/firmware/rtlwifi/rtl8723befw_36.bin
1850c1308fbcd95e9f6a7f58ede1e35f  /lib/firmware/rtlwifi/rtl8723befw.bin
```

```
$ sudo lspci -nn -vvv
[...]
08:00.0 Network controller [0280]: Realtek Semiconductor Co., Ltd. RTL8723BE PCIe Wireless Network Adapter [10ec:b723] (rev ff) (prog-if ff)
        !!! Unknown header type 7f
        Kernel driver in use: rtl8723be
        Kernel modules: rtl8723be
[...]
```

I also have records of the results of `lspci -nn` from when the wireless was working, but because it wasn't ultraverbose it doesn't contain any interesting information. I do have an `lspci -xxxx` dump from when it was working, and when it presents failure, if that is of use to you.

**Comment by finnoleary** [comment]
Yeah, I performed that previously to no avail, I'll try it again when I have access to the machine.

**Comment by lwfinger** [comment]
One thing that occurred to me on the way to work this morning is that you may have flaky connections to the wifi card. If possible, open up the computer and remove and reinstall the card.

It seems that the repo has the wrong firmware for _36.bin. I will replace it.

**Comment by lwfinger** [comment]
Actually, the _36.bin file is OK. The other one is wrong.

**Comment by finnoleary** [comment]
> One thing that occurred to me on the way to work this morning is that you may have flaky connections to the wifi card. If possible, open up the computer and remove and reinstall the card.

:-) The same thing occurred to me, I did that and things seem to be working again. I finally have a dmesg from a working and non-working state and there's considerable difference. The memory map wasn't returning the addresses with the wireless firmware.

> It seems that the repo has the wrong firmware for _36.bin. I will replace it.
:+1: I restored Arch Linux's version and things seem to be working with a blank (well, commented out) options file. Thanks for your help.

**Comment by lwfinger** [comment]
Actually, the _36.bin file is OK. The other one is wrong.
