### ISSUE TITLE
rtl8723ae : CPU at 100%

### ISSUE THREAD

**Issue by Pole4** [lwfinger/rtlwifi_new#216]
Hello,

Regularly my system becomes unusable : I can see around 100 000 interrupts/s on rtl_pci, and then the process kworker/ksoftirq/watchdog start working at basically 100 % of the core.
It is unclear what exactly starts this behavior.

Another issue is that I need sometimes to reboot or the wifi won't connect.

lspci :
05:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8723AE PCIe Wireless Network Adapter
I am using ubuntu 16.10,
Linux  4.8.0-41-generic #44-Ubuntu SMP Fri Mar 3 15:27:17 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Thanks for helping me,
Paul.

**Comment by r0ck3r** [comment]
Have this bug too. Any solutions?

**Comment by KoWu** [comment]
I now have this bug as well, also using RTL8723AE. I think it appeared after a recent linux kernel upgrade, but this could also be uncorrelated. WIFI is still working. Issue appears after some (1-2h) uptime. Has anyone solved this issue?

**Comment by lwfinger** [comment]
No. In fact, I have never duplicated the issue.

Since you say that a recent kernel upgrade may have caused it, I would appreciate your doing a bisection to find the offending commit.

**Comment by KoWu** [comment]
Ok so far I could trace it down to the 4.15.0 release, the 4.14.15 was unaffected. I am running on arch.
The changes made between those versions are related to interrupts as well. However I havent digged deeper into it.

removing and reinserting the modules does not help btw, a reboot is required.
If I shall test / compile something else just let me know, the bug is getting triggered pretty fast.

**Comment by KoWu** [comment]
`[ 1032.031048] rtlwifi: :<0> come in
[ 1032.031058] rtlwifi: :<0> Write element_id box_reg( 1d0) =  1
[ 1032.031082] rtlwifi: :<0> pHalData->last_hmeboxnum  = 1
[ 1032.031083] rtlwifi: :<0> go out
[ 1032.476717] rtlwifi: :<10000> Rx ok interrupt!
[ 1032.476725] rtlwifi: :<10000> regaddr(0x824), bitmask(0x200)
[ 1032.476735] rtlwifi: :<10000> BBR MASK=0x200 Addr[0x824]=0x80390004
[ 1032.988775] rtlwifi: :<10000> Rx ok interrupt!
[ 1032.988782] rtlwifi: :<10000> regaddr(0x824), bitmask(0x200)
[ 1032.988792] rtlwifi: :<10000> BBR MASK=0x200 Addr[0x824]=0x80390004
[ 1033.500642] rtlwifi: :<10000> Rx ok interrupt!
[ 1033.500650] rtlwifi: :<10000> regaddr(0x824), bitmask(0x200)
[ 1033.500661] rtlwifi: :<10000> BBR MASK=0x200 Addr[0x824]=0x80390004
[ 1034.079036] rtlwifi: :<0> Enter 802.11 power save mode...
[ 1034.079039] rtlwifi: :<0> FW LPS enter ps_mode:3
[ 1034.079042] rtlwifi: :<0> FW LPS mode = 3
[ 1034.079043] rtlwifi: In process "kworker/4:2" (pid 179): rtl8723e_set_fw_rsvdpagepkt(): u1_h2c_set_pwrmode`

**Comment by lwfinger** [comment]
That does not help. You need to get a source that has all the commits and use the 'git bisect' operation to find the one that is wrong. As I cannot duplicate the result, YOU will need to do it.

**Comment by KoWu** [comment]
I think thats not needed anymore. I compiled and tested the current master branch on kernel ver. 4.14.15 and 4.15.0. It seems like the issue only occurs on 4.15.0. How can I debug this further? I assume it's not a rtlwifi problem then.

The affected core just spents 75% of its time in irq mode.

**Comment by lwfinger** [comment]
Bisect the kernel between 4.15 (bad) and 4.14 (good) using the mainline repository for kernel source. That should show which kernel change is causing the problem.

**Comment by KoWu** [comment]
Okay I found out that it was not because of the used kernel version, but because some options in the .config changed in the arch repo, leading to high cpu if there are a lot of interrupts. I am trying to trace down wich option leads to this behaviour. But this is not the main problem!
The main problem is that there are generated 50k Interrupts per second after some time. Happens faster if the card is used. This issue exists as long as I can think, because whenever that happens the CPU will not throttle down even if there is no load. Now I know at least the reason for this behaviour...
So is there anything I can do  besides buying a newer network card?

**Comment by lwfinger** [comment]
What interrupt is being triggered?

I am running using the driver in kernel 4.16-rc1, and I see no high interrupt usage. At this point, the only thing I can suggest is to use the "msi=1" module parameter when you load it.

**Comment by KoWu** [comment]
What du you mean by what interrupt is being triggered?
I am seeing a lot of IO-APIC on 17-fasteoi on one core (the one with the high cpu).
With msi=1 I am having the same issue as well, on PCI-MSI 2621440-edge this time.
But the CPU load is at 100% then (mpstat shows 50% irq time). Even worse, after some amount of time the whole system freezes. So sadly this didn't solve the problem.

**Comment by lwfinger** [comment]
Choosing msi=1 was just a guess.

On my system, the rtl_pci interrupt is
 17:          0       7358       5585        882  IR-IO-APIC  17-fasteoi   rtl_pci

That one has been running for about 2 hours.

Unfortunately, I cannot duplicate your problem, and I have no further ideas.

**Comment by KoWu** [comment]
Okay. Maybe I am going to dig deeper. Or just buy a new card. I really want to know the origin / content of the interrupt. Nevertheless thanks for your support. This is how it typically looks when affected:
https://pastebin.com/raw/s5hRAx3L

**Comment by KoWu** [comment]
On all the interrupts I get `inta` and `intb` just reads zero. The handling code for this case states `Shared IRQ`. I don't think thats the case... Is there any documentation about the differenty types of Firmware?

**Comment by lwfinger** [comment]
My code says
        /*Shared IRQ or HW disappared */
        if (!inta || inta == 0xffff)
That is the case where inta is zero, or all ones. It says nothing about intb. Not all devices have anything in intb. Others have inta, intb, and intd.

Please switch to the extended branch. That way I will only have to debug code that is actually live.

**Comment by KoWu** [comment]
I logged all read / write operations but could not find out what the problem was. At some point it will just read 0x04110000 from 0x3a0, and thats when the trouble begins. The Interrupts won't stop. If i have received some of them, I will just stop handling interrupts at all, just return IRQ_HANDLED. After some time they will stop. But the Problem continues as soon as I start interacting with the card again...

I assume that the card is really sending those interrupts, because it happens in msi mode as well.

It would be really helpful to have a documentation about the firmware, or at least some reset possibility.

This is a huge problem, If I download sth on a fast connection it doesn't even take a second for the bug to trigger. I am btw running on 4.16.0-rc1 as well.
```
Feb 16 22:20:51 KARCH kernel: rtl_pci:_rtl_pci_interrupt [rtl_pci]:<10000-1> a=0x00000001
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_write32_async [rtl_pci]:<10000-1>  write 0x23000cff to 0x03a8
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10000-1>    read  0x23000cff fr 0x03a8
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_write32_async [rtl_pci]:<10000-1>  write 0x00000100 to 0x03ac
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10000-1>    read  0x00000100 fr 0x03ac
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_write16_async [rtl_pci]:<400-1>    write 0x0002 to 0x0300
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_write32_async [rtl_pci]:<10000-1>  write 0x00000000 to 0x03a8
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10000-1>    read  0x00000000 fr 0x03a8
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_write32_async [rtl_pci]:<10000-1>  write 0x00000000 to 0x03ac
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10000-1>    read  0x00000000 fr 0x03ac
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10000-1>    read  0x04110011 fr 0x03a0
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_write32_async [rtl_pci]:<10000-1>  write 0x00000011 to 0x03a0
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10000-1>    read  0x04110000 fr 0x03a0
Feb 16 22:20:51 KARCH kernel: rtl_pci:_rtl_pci_interrupt [rtl_pci]:<10000-1> a=0x00000011
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_write32_async [rtl_pci]:<10000-1>  write 0x23000cff to 0x03a8
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10000-1>    read  0x23000cff fr 0x03a8
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_write32_async [rtl_pci]:<10000-1>  write 0x00000100 to 0x03ac
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10000-1>    read  0x00000100 fr 0x03ac
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_write16_async [rtl_pci]:<400-1>    write 0x0002 to 0x0300
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_write32_async [rtl_pci]:<10000-1>  write 0x00000000 to 0x03a8
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10000-1>    read  0x00000000 fr 0x03a8
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_write32_async [rtl_pci]:<10000-1>  write 0x00000000 to 0x03ac
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10000-1>    read  0x00000000 fr 0x03ac
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10000-1>    read  0x04110010 fr 0x03a0 //read inta
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_write32_async [rtl_pci]:<10000-1>  write 0x00000010 to 0x03a0 //write inta
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10000-1>    read  0x04110001 fr 0x03a0 //readback, normal i guess
Feb 16 22:20:51 KARCH kernel: rtl_pci:_rtl_pci_interrupt [rtl_pci]:<10000-1> a=0x00000010
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_write32_async [rtl_pci]:<10000-1>  write 0x23000cff to 0x03a8
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10000-1>    read  0x23000cff fr 0x03a8
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_write32_async [rtl_pci]:<10000-1>  write 0x00000100 to 0x03ac
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10000-1>    read  0x00000100 fr 0x03ac
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_write32_async [rtl_pci]:<10000-1>  write 0x00000000 to 0x03a8
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10000-1>    read  0x00000000 fr 0x03a8
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_write32_async [rtl_pci]:<10000-1>  write 0x00000000 to 0x03ac
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10000-1>    read  0x00000000 fr 0x03ac
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10000-1>    read  0x04110001 fr 0x03a0
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_write32_async [rtl_pci]:<10000-1>  write 0x00000001 to 0x03a0
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10000-1>    read  0x04110000 fr 0x03a0
Feb 16 22:20:51 KARCH kernel: rtl_pci:_rtl_pci_interrupt [rtl_pci]:<10000-1> a=0x00000001
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_write32_async [rtl_pci]:<10000-1>  write 0x23000cff to 0x03a8
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10000-1>    read  0x23000cff fr 0x03a8
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_write32_async [rtl_pci]:<10000-1>  write 0x00000100 to 0x03ac
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10000-1>    read  0x00000100 fr 0x03ac
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_write32_async [rtl_pci]:<10100-1>  write 0x00000000 to 0x03a8
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10100-1>    read  0x00000000 fr 0x03a8
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_write32_async [rtl_pci]:<10100-1>  write 0x00000000 to 0x03ac
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10100-1>    read  0x00000000 fr 0x03ac
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10100-1>    read  0x04110001 fr 0x03a0
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_write32_async [rtl_pci]:<10100-1>  write 0x00000001 to 0x03a0
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10100-1>    read  0x04110000 fr 0x03a0
Feb 16 22:20:51 KARCH kernel: rtl_pci:_rtl_pci_interrupt [rtl_pci]:<10100-1> a=0x00000001
// leave irq, enable interrupts
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_write32_async [rtl_pci]:<10100-1>  write 0x23000cff to 0x03a8 // write en irq
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10100-1>    read  0x23000cff fr 0x03a8 // readback
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_write32_async [rtl_pci]:<10100-1>  write 0x00000100 to 0x03ac // write en irq
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10100-1>    read  0x00000100 fr 0x03ac // readback
// enter irq, disable interrupts
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_write32_async [rtl_pci]:<10300-1>  write 0x00000000 to 0x03a8 // write dis irq
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10300-1>    read  0x00000000 fr 0x03a8 // readback
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_write32_async [rtl_pci]:<10300-1>  write 0x00000000 to 0x03ac // write dis irq
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10300-1>    read  0x00000000 fr 0x03ac // readback
// read inta
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10300-1>    read  0x04110000 fr 0x03a0 // read inta ERROR!!!
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_write32_async [rtl_pci]:<10300-1>  write 0x00000000 to 0x03a0 // write readback
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10300-1>    read  0x04110000 fr 0x03a0 // read writeback
Feb 16 22:20:51 KARCH kernel: rtl_pci:_rtl_pci_interrupt [rtl_pci]:<10300-1> a=0x00000000
// reenable interrupts
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_write32_async [rtl_pci]:<10300-1>  write 0x23000cff to 0x03a8
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10300-1>    read  0x23000cff fr 0x03a8
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_write32_async [rtl_pci]:<10300-1>  write 0x00000100 to 0x03ac
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10300-1>    read  0x00000100 fr 0x03ac
//...
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_write32_async [rtl_pci]:<10300-1>  write 0x00000000 to 0x03a8
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10300-1>    read  0x00000000 fr 0x03a8
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_write32_async [rtl_pci]:<10300-1>  write 0x00000000 to 0x03ac
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10300-1>    read  0x00000000 fr 0x03ac
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10300-1>    read  0x04110000 fr 0x03a0
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_write32_async [rtl_pci]:<10300-1>  write 0x00000000 to 0x03a0
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10300-1>    read  0x04110000 fr 0x03a0
Feb 16 22:20:51 KARCH kernel: rtl_pci:_rtl_pci_interrupt [rtl_pci]:<10300-1> a=0x00000000
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_write32_async [rtl_pci]:<10300-1>  write 0x23000cff to 0x03a8
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10300-1>    read  0x23000cff fr 0x03a8
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_write32_async [rtl_pci]:<10300-1>  write 0x00000100 to 0x03ac
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10300-1>    read  0x00000100 fr 0x03ac
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_write32_async [rtl_pci]:<10100-1>  write 0x00000000 to 0x03a8
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10100-1>    read  0x00000000 fr 0x03a8
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_write32_async [rtl_pci]:<10100-1>  write 0x00000000 to 0x03ac
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10100-1>    read  0x00000000 fr 0x03ac
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10100-1>    read  0x04110000 fr 0x03a0
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_write32_async [rtl_pci]:<10100-1>  write 0x00000000 to 0x03a0
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10100-1>    read  0x04110000 fr 0x03a0
Feb 16 22:20:51 KARCH kernel: rtl_pci:_rtl_pci_interrupt [rtl_pci]:<10100-1> a=0x00000000
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_write32_async [rtl_pci]:<10100-1>  write 0x23000cff to 0x03a8
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10100-1>    read  0x23000cff fr 0x03a8
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_write32_async [rtl_pci]:<10100-1>  write 0x00000100 to 0x03ac
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_read32_sync [rtl_pci]:<10100-1>    read  0x00000100 fr 0x03ac
Feb 16 22:20:51 KARCH kernel: rtl_pci:pci_write16_async [rtl_pci]:<400-1>    write 0x0002 to 0x0300
Feb 16 22:20:51 KARCH kernel: rtl_pci:_rtl_pci_interrupt [rtl_pci]:<10000-1> LIMIT REACHED! IGNORE FURTHER IRQs.
// a lot of inta=0 interrupts...
```

**Comment by EugeneBas9** [comment]
Hi, i have the same problem. I'm running 4.15.14-300.fc27.x86_64 Anyone fixed this?

**Comment by lwfinger** [comment]
The following was posted a few days ago in Issue #345.

That chip is relatively rare and has not had the in-field testing of the rtl8723be. You might try the following options (not necessarily at the same time): msi=1 aspm=0 disable_watchdog=1 Those are the things that might lead to runaway interrupts. My guess would be the msi change.
--

**Comment by koopafou** [comment]
I also have this problem, it started when I moved into the city. Rolling back to a previous kernel where it was fine when I was in the contryside still triggered the CPU usage. I suspected at some point it was due to the dozens of other wifi signals, but I can't correlate the moment it happens with the moment when I guess a lot of people must use wifi.

Unfortunately I don't have time to go back to the countryside to check if it's really because of the city.
 
I tried every combination of the above, msi=1 prevents the chipset from working altogether and the system is somewhat unstable (can't reboot or shutdown the normal way, netctl hangs, rmmod hangs).
aspm=0 and/or disable_watchdog=1 don't seem to have any effect and the interrupts are still spammed.

**Comment by KoWu** [comment]
I can test it in the countryside. I thought it only occurs with high bandwidth. Also I think it does not happen with the windows driver.

**Comment by imShara** [comment]
Same here https://bbs.archlinux.org/viewtopic.php?pid=1833959

**Comment by koopafou** [comment]
I'm still living in a city but clearly not as densely populated as before, and the IRQs barely panic anymore since then. Actually I didn't know if it was fixed or not at some point, but it just happened right now out of nowhere so I figured I would give an update of my experience. 
I can say with more confidence that it really could depend on how much wifi is used around me. The more populated the area, the more frequently it suddenly hogs a CPU core. 
Or it's really a coincidence and it depends on the wifi router but I can't make sense of what could set them apart (it's not the ISP, models vary wildly, and I can't just fiddle around with people's configuration of their router), so ... meh. Just take it as a possible random way to reproduce the bug.

**Comment by KoWu** [comment]
I also experienced that in areas with less "noise" the issue does not appear that frequent, it's not imagination.

I guess it's not worth spending more time on debugging this Issue, the Chip is anyways outdated. Firmware bug with weird timing conditions is my best guess. It's impossible to debug this without the right tools.

Whenever it happens I just rmmod the rtl kernel module, put my laptop in mem power state (so the module is powered off, this is necessary), wake up and modprobe again. Takes < 1min.

**Comment by Raizon94** [comment]
I have just fixed!!! I have a toshiba laptop with a rtl8723ae wifi card and i had tested lots of linux distros. All of them gave me the same issue. One cpu core at 100% after an hour. I **just change the parameter "msi" of the wifi card from 0 to 1**. Now it's perfectly working. I hope I can help you because I was very confused with this issue.

**Comment by koopafou** [comment]
@Raizon94 this has already been suggested above, it doesn't work for everyone.
