### ISSUE TITLE
RTL8192EE - Kernel 4.8.0 - Low connection speed and sporadic connection drops

### ISSUE THREAD

**Issue by christianpinto** [lwfinger/rtlwifi_new#217]
Hello,

I have recently switched to ubuntu 16.04 that comes with a 4.8.0 kernel. With the in-driver kernel I have experienced low connection speed and connection drops. I have a thinkpad T440s with a PCI-e RTL8192EE.

After installing the drivers from this repository (master branch) everything went definitely better, and I now get same speed as other machines in my network. I was already using the drivers from this repo with my previous Ubuntu 14.04 installation with kernel 3.19, and I was hoping things to get better with newer kernels.
Is the code in master already upstream in newer Kernels (> 4.8.0)? Is there any difference between master and the other branches such as rock?

Thanks,

Christian

**Comment by lwfinger** [comment]
As far as I know, everything in the master branch is in kernel 4.9 or newer.

The other branches are mostly used for transferring patches from Realtek to the kernel. I try to keep them updated with any changes going the other way, but that has low priority. In general, I would not recommend using any of them.
