### ISSUE TITLE
rtl8723be with ant_sel and wpa2

### ISSUE THREAD

**Issue by LorenzoMarsicano** [lwfinger/rtlwifi_new#218]
Using the ant_sel parameter, if I set it to `ant_sel=1` I can connect to my wifi network, but the signal is very weak and the connections is really slow.
If I set it to `ant_sel=2` I get strong signal, but I can't connect to the network:
nmcli says that it could not activate connection and if I try manually with wpa_supplicant, it says the the key is wrong.

If I remove the wpa2 password from my network I can connect to it so I have to guess that the error is given by the fact that I'm using wpa2?

**Comment by lwfinger** [comment]
To me, this set of observations make no sense. First of all, do you really need to use any ant_sel parameter? Please provide the signal strength from the command "sudo iw dev wlan0 scan" for your AP, and for each of the cases where ant_sel = 0, 1, and 2.

**Comment by InfiniteCoder** [comment]
@lwfinger  ant_sel in necessary for rtl8723be. But in my case, I don't get any issues as mentioned by OP.

**Comment by LorenzoMarsicano** [comment]
Apparently it was an issue with my powerlinks that were duplicating my network.
For some reason, using ant_sel=1 I could intercept the signal from the power link but it couldn't connect to it.

By the way:

Using ant_sel=1 I get 
-8dBm

Using ant_sel=2 I get
-64dBm

Using ant_sel=0 scanning doesn't show anything.

**Comment by lwfinger** [comment]
OK, you do need ant_sel=1; however, the problem was not the driver.
