### ISSUE TITLE
Makefile:57: recipe for target 'all' failed make: *** [all] Error 2

### ISSUE THREAD

**Issue by marcvannieuwenhuijzen** [lwfinger/rtlwifi_new#219]
I'm trying to run make on Fedora 25 when I get the error: Makefile:57: recipe for target 'all' failed make: *** [all] Error 2

**Comment by lwfinger** [comment]
What are the rest of the error messages? I think you probably have not installed the kernel headers.

**Comment by marcvannieuwenhuijzen** [comment]
The symbolic link in /lib/modules/4.8.6-300.fc25.x86_64 is broken (i think)

**Comment by marcvannieuwenhuijzen** [comment]
I ran: sudo dnf install kernel-devel kernel-headers

**Comment by lwfinger** [comment]
That should be sufficient as long as you are running the latest kernel, i.e. the one that matches the kernel headers that were installed. What do the commands "uname -r" and "ls -l /lib/modules/$(uname -r)/build"?

**Comment by LeoCenturion** [comment]
The same happened to me. When i ran the commands "uname -r" and "ls -l /lib/modules/$(uname -r)/build I got 4.10.5-200.fc25.x86_64"  and "lrwxrwxrwx. 1 root root 39 Mar 22 17:50 /lib/modules/4.10.5-200.fc25.x86_64/build -> /usr/src/kernels/4.10.5-200.fc25.x86_64". But once I "ls /usr/src/kernels/" there was no  "4.10.5-200.fc25.x86_64" file but "4.10.6-200.fc25.x86_64" instead.
So i changed in the makefile the line 
                      KSRC := /lib/modules/$(KVER)/build
for
                   KSRC := /usr/src/kernels/4.10.6-200.fc25.x86_64
and it compiled.

**Comment by lwfinger** [comment]
Makefile assumes that you are building for the kernel that is actually running. If that is not the case, then it will fail. If I were to make the change you made, then it would fail for everyone, and it will fail for you when your base kernel changes.
