### ISSUE TITLE
Failure to Authenticate With 5GHz Network W/ 8812ae Chipset Card

### ISSUE THREAD

**Issue by warrenpw** [lwfinger/rtlwifi_new#221]
Hello there!

Before posting this, I looked through the current issues listed; but I didn't see anything fitting my situation exactly, so here we are. Apologies if this issue has already been posted.

Anyway, the details to this problem are as follows:
I'm currently running Fedora 25 with kernel version 4.10.5-200.fc25.x86_64 and using a PCIe wireless card with the 8812ae chipset (HiRO 11ac Dual Band Wireless Adapter PCIe x1). I've tried both the builtin and git-built rtlwifi-new modules, but both seem to produce an error stating that authentication to my target wireless ac network timed out. I've double and triple checked to make sure this isn't me mistyping the passphrase, and I can also connect to my target network with my phone.

In addition to this, my target network does show up in the gui selector after waiting for about 2 minutes with both drivers, but I don't see it in the output for iwlist scanning. Is there a better method to use to list networks?
And finally, the git-built driver throws a warning about the EEPROM indicating an invalid country code, while the builtin does not, though the output of iw reg get appears to be consistent.

Command outputs for builtin driver are in *_bultin.txt, and *_rtlwifi-new for the git-built driver.

Let me know if you need more information!

[dmesg_auth_error.txt](https://github.com/lwfinger/rtlwifi_new/files/886633/dmesg_auth_error.txt)
[dmesg_output_builtin.txt](https://github.com/lwfinger/rtlwifi_new/files/886634/dmesg_output_builtin.txt)
[dmesg_output_rtlwifi-new.txt](https://github.com/lwfinger/rtlwifi_new/files/886636/dmesg_output_rtlwifi-new.txt)
[iwlist_freq_output_builtin.txt](https://github.com/lwfinger/rtlwifi_new/files/886635/iwlist_freq_output_builtin.txt)
[iwlist_freq_output_rtlwifi-new.txt](https://github.com/lwfinger/rtlwifi_new/files/886637/iwlist_freq_output_rtlwifi-new.txt)
[iw_reg_output_builtin.txt](https://github.com/lwfinger/rtlwifi_new/files/886640/iw_reg_output_builtin.txt)
[iw_reg_output_rtlwifi-new.txt](https://github.com/lwfinger/rtlwifi_new/files/886639/iw_reg_output_rtlwifi-new.txt)

**Comment by lwfinger** [comment]
When posting in-line, an excerpt from the dmesg log is OK. When posting information separately, the whole log is better. I may ask for that later, but for now, post the output of

rfkill list all
sudo iw dev wlp6s0 scan

**Comment by warrenpw** [comment]
Ah, sorry about that. The following are on the git-built driver.

$ rfkill list all
1: phy0: Wireless LAN
	Soft blocked: no
	Hard blocked: no

$ sudo iw dev wlp6s0 scan
[sudo] password for warren: 
BSS e4:f4:c6:02:e9:81(on wlp6s0) -- associated
	TSF: 2687902402705 usec (31d, 02:38:22)
	freq: 2442
	beacon interval: 100 TUs
	capability: ESS Privacy ShortSlotTime RadioMeasure (0x1411)
	signal: -36.00 dBm
	last seen: 172 ms ago
	Information elements from Probe Response frame:
	SSID: Chromecast
	Supported rates: 1.0* 2.0* 5.5 11.0 18.0 24.0 36.0 54.0 
	DS Parameter set: channel 7
	ERP: Barker_Preamble_Mode
	Extended supported rates: 6.0 9.0 12.0 48.0 
	RSN:	 * Version: 1
		 * Group cipher: CCMP
		 * Pairwise ciphers: CCMP
		 * Authentication suites: PSK
		 * Capabilities: 16-PTKSA-RC 1-GTKSA-RC (0x000c)
	BSS Load:
		 * station count: 3
		 * channel utilisation: 31/255
		 * available admission capacity: 0 [*32us]
	HT capabilities:
		Capabilities: 0x9ad
			RX LDPC
			HT20
			SM Power Save disabled
			RX HT20 SGI
			TX STBC
			RX STBC 1-stream
			Max AMSDU length: 7935 bytes
			No DSSS/CCK HT40
		Maximum RX AMPDU length 65535 bytes (exponent: 0x003)
		Minimum RX AMPDU time spacing: 4 usec (0x05)
		HT RX MCS rate indexes supported: 0-23
		HT TX MCS rate indexes are undefined
	HT operation:
		 * primary channel: 7
		 * secondary channel offset: no secondary
		 * STA channel width: 20 MHz
		 * RIFS: 1
		 * HT protection: nonmember
		 * non-GF present: 1
		 * OBSS non-GF present: 1
		 * dual beacon: 0
		 * dual CTS protection: 0
		 * STBC beacon: 0
		 * L-SIG TXOP Prot: 0
		 * PCO active: 0
		 * PCO phase: 0
	Overlapping BSS scan params:
		 * passive dwell: 20 TUs
		 * active dwell: 10 TUs
		 * channel width trigger scan interval: 300 s
		 * scan passive total per channel: 200 TUs
		 * scan active total per channel: 20 TUs
		 * BSS width channel transition delay factor: 5
		 * OBSS Scan Activity Threshold: 0.25 %
	Extended capabilities: HT Information Exchange Supported, Extended Channel Switching, BSS Transition, 6
	WPS:	 * Version: 1.0
		 * Wi-Fi Protected Setup State: 2 (Configured)
		 * AP setup locked: 0x01
		 * Response Type: 3 (AP)
		 * UUID: 57807981-410d-9ac5-efab-60c1459fc747
		 * Manufacturer: NETGEAR, Inc.
		 * Model: R7000
		 * Model Number: R7000
		 * Serial Number: 32
		 * Primary Device Type: 6-0050f204-1
		 * Device name: R7000
		 * Config methods: Display
		 * RF Bands: 0x3
		 * Unknown TLV (0x1049, 6 bytes): 00 37 2a 00 01 20
	WMM:	 * Parameter version 1
		 * u-APSD
		 * BE: CW 15-1023, AIFSN 3
		 * BK: CW 15-1023, AIFSN 7
		 * VI: CW 7-15, AIFSN 2, TXOP 6016 usec
		 * VO: CW 3-7, AIFSN 2, TXOP 3264 usec
BSS cc:5d:4e:48:41:87(on wlp6s0)
	TSF: 2694399900153 usec (31d, 04:26:39)
	freq: 2442
	beacon interval: 100 TUs
	capability: ESS Privacy ShortSlotTime (0x0411)
	signal: -76.00 dBm
	last seen: 171 ms ago
	Information elements from Probe Response frame:
	SSID: ZyXEL
	Supported rates: 1.0* 2.0* 5.5* 11.0* 6.0 9.0 12.0 18.0 
	DS Parameter set: channel 7
	TIM: DTIM Count 0 DTIM Period 1 Bitmap Control 0x0 Bitmap[0] 0x4
	ERP: Barker_Preamble_Mode
	Extended supported rates: 24.0 36.0 48.0 54.0 
	WMM:	 * Parameter version 1
		 * BE: CW 15-1023, AIFSN 3
		 * BK: CW 15-1023, AIFSN 7
		 * VI: CW 7-15, AIFSN 2, TXOP 3008 usec
		 * VO: CW 3-7, AIFSN 2, TXOP 1504 usec
	WPS:	 * Version: 1.0
		 * Wi-Fi Protected Setup State: 2 (Configured)
		 * Device name: ZyXEL NBG-418N AP Router
		 * Config methods: Ethernet, Label, PBC
BSS ac:3a:7a:77:91:7b(on wlp6s0)
	TSF: 2694431744058 usec (31d, 04:27:11)
	freq: 2442
	beacon interval: 100 TUs
	capability: ESS Privacy SpectrumMgmt ShortSlotTime (0x0511)
	signal: -53.00 dBm
	last seen: 151 ms ago
	Information elements from Probe Response frame:
	SSID: \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
	Supported rates: 6.0* 9.0 12.0* 18.0 24.0* 36.0 48.0 54.0 
	DS Parameter set: channel 7
	TIM: DTIM Count 0 DTIM Period 3 Bitmap Control 0x0 Bitmap[0] 0x0
	Country: US	Environment: Indoor/Outdoor
		Channels [1 - 11] @ 30 dBm
	Power constraint: 0 dB
	TPC report: TX power: 18 dBm
	ERP: <no flags>
	ERP D4.0: <no flags>
	RSN:	 * Version: 1
		 * Group cipher: CCMP
		 * Pairwise ciphers: CCMP
		 * Authentication suites: PSK
		 * Capabilities: 4-PTKSA-RC 1-GTKSA-RC (0x0008)
	HT capabilities:
		Capabilities: 0x193c
			HT20
			SM Power Save disabled
			RX Greenfield
			RX HT20 SGI
			RX STBC 1-stream
			Max AMSDU length: 7935 bytes
			DSSS/CCK HT40
		Maximum RX AMPDU length 32767 bytes (exponent: 0x002)
		Minimum RX AMPDU time spacing: 4 usec (0x05)
		HT RX MCS rate indexes supported: 0-15
		HT TX MCS rate indexes are undefined
	HT operation:
		 * primary channel: 7
		 * secondary channel offset: no secondary
		 * STA channel width: 20 MHz
		 * RIFS: 1
		 * HT protection: nonmember
		 * non-GF present: 0
		 * OBSS non-GF present: 1
		 * dual beacon: 0
		 * dual CTS protection: 0
		 * STBC beacon: 0
		 * L-SIG TXOP Prot: 0
		 * PCO active: 0
		 * PCO phase: 0
	Extended capabilities: Extended Channel Switching, 6
	WMM:	 * Parameter version 1
		 * u-APSD
		 * BE: CW 15-1023, AIFSN 3
		 * BK: CW 15-1023, AIFSN 7
		 * VI: CW 7-15, AIFSN 2, TXOP 3008 usec
		 * VO: CW 3-7, AIFSN 2, TXOP 1504 usec
	WPS:	 * Version: 1.0
		 * Wi-Fi Protected Setup State: 2 (Configured)
		 * UUID: 22210203-0405-0607-0809-ac3a7a77917b
		 * Unknown TLV (0x1049, 6 bytes): 00 37 2a 00 01 20
		 * Primary Device Type: 6-0050f204-1
		 * Device name: DIRECT-roku-771-FA5DA2
	P2P:	 * Group capa: 0x27, Device capa: 0x2b
		 * Unknown TLV (0x03, 6 bytes): 3a 7a 77 91 79 dd
BSS 14:cf:e2:61:5d:30(on wlp6s0)
	TSF: 1475029355647 usec (17d, 01:43:49)
	freq: 2412
	beacon interval: 100 TUs
	capability: ESS Privacy ShortSlotTime (0x0411)
	signal: -45.00 dBm
	last seen: 11630 ms ago
	Information elements from Probe Response frame:
	SSID: HOME-5D32
	Supported rates: 1.0* 2.0* 5.5* 11.0* 9.0 18.0 36.0 54.0 
	DS Parameter set: channel 1
	ERP: Barker_Preamble_Mode
	Extended supported rates: 6.0* 12.0* 24.0* 48.0 
	HT capabilities:
		Capabilities: 0x11ee
			HT20/HT40
			SM Power Save disabled
			RX HT20 SGI
			RX HT40 SGI
			TX STBC
			RX STBC 1-stream
			Max AMSDU length: 3839 bytes
			DSSS/CCK HT40
		Maximum RX AMPDU length 65535 bytes (exponent: 0x003)
		Minimum RX AMPDU time spacing: 4 usec (0x05)
		HT RX MCS rate indexes supported: 0-15, 32
		HT TX MCS rate indexes are undefined
	HT operation:
		 * primary channel: 1
		 * secondary channel offset: no secondary
		 * STA channel width: 20 MHz
		 * RIFS: 0
		 * HT protection: 20 MHz
		 * non-GF present: 1
		 * OBSS non-GF present: 0
		 * dual beacon: 0
		 * dual CTS protection: 0
		 * STBC beacon: 0
		 * L-SIG TXOP Prot: 0
		 * PCO active: 0
		 * PCO phase: 0
	Secondary Channel Offset: above (1)
	WPA:	 * Version: 1
		 * Group cipher: TKIP
		 * Pairwise ciphers: TKIP CCMP
		 * Authentication suites: PSK
	RSN:	 * Version: 1
		 * Group cipher: TKIP
		 * Pairwise ciphers: TKIP CCMP
		 * Authentication suites: PSK
		 * Capabilities: 1-PTKSA-RC 1-GTKSA-RC (0x0000)
	WMM:	 * Parameter version 1
		 * BE: CW 15-1023, AIFSN 3
		 * BK: CW 15-1023, AIFSN 7
		 * VI: CW 7-15, AIFSN 2, TXOP 3008 usec
		 * VO: CW 3-7, AIFSN 2, TXOP 1504 usec
	BSS Load:
		 * station count: 1
		 * channel utilisation: 0/255
		 * available admission capacity: 31250 [*32us]
	Overlapping BSS scan params:
		 * passive dwell: 20 TUs
		 * active dwell: 10 TUs
		 * channel width trigger scan interval: 300 s
		 * scan passive total per channel: 200 TUs
		 * scan active total per channel: 20 TUs
		 * BSS width channel transition delay factor: 5
		 * OBSS Scan Activity Threshold: 0.25 %
	Extended capabilities: HT Information Exchange Supported
	Country: US	Environment: Indoor/Outdoor
		Channels [1 - 11] @ 16 dBm
	WPS:	 * Version: 1.0
		 * Wi-Fi Protected Setup State: 2 (Configured)
		 * Response Type: 3 (AP)
		 * UUID: 28802880-2880-1880-a880-14cfe2615d30
		 * Manufacturer: ARRIS
		 * Model: TG862G
		 * Model Number: RT2860
		 * Serial Number: 12345678
		 * Primary Device Type: 6-0050f204-1
		 * Device name: ARRIS TG862 Router
		 * Config methods: Keypad
		 * RF Bands: 0x1
		 * Unknown TLV (0x1049, 6 bytes): 00 37 2a 00 01 20
BSS 16:cf:e2:61:5d:30(on wlp6s0)
	TSF: 1475029358072 usec (17d, 01:43:49)
	freq: 2412
	beacon interval: 100 TUs
	capability: ESS ShortSlotTime (0x0401)
	signal: -46.00 dBm
	last seen: 11626 ms ago
	Information elements from Probe Response frame:
	SSID: xfinitywifi
	Supported rates: 1.0* 2.0* 5.5* 11.0* 9.0 18.0 36.0 54.0 
	DS Parameter set: channel 1
	ERP: Barker_Preamble_Mode
	Extended supported rates: 6.0* 12.0* 24.0* 48.0 
	HT capabilities:
		Capabilities: 0x11ee
			HT20/HT40
			SM Power Save disabled
			RX HT20 SGI
			RX HT40 SGI
			TX STBC
			RX STBC 1-stream
			Max AMSDU length: 3839 bytes
			DSSS/CCK HT40
		Maximum RX AMPDU length 65535 bytes (exponent: 0x003)
		Minimum RX AMPDU time spacing: 4 usec (0x05)
		HT RX MCS rate indexes supported: 0-15, 32
		HT TX MCS rate indexes are undefined
	HT operation:
		 * primary channel: 1
		 * secondary channel offset: no secondary
		 * STA channel width: 20 MHz
		 * RIFS: 0
		 * HT protection: 20 MHz
		 * non-GF present: 1
		 * OBSS non-GF present: 0
		 * dual beacon: 0
		 * dual CTS protection: 0
		 * STBC beacon: 0
		 * L-SIG TXOP Prot: 0
		 * PCO active: 0
		 * PCO phase: 0
	Secondary Channel Offset: above (1)
	WMM:	 * Parameter version 1
		 * BE: CW 15-1023, AIFSN 3
		 * BK: CW 15-1023, AIFSN 7
		 * VI: CW 7-15, AIFSN 2, TXOP 3008 usec
		 * VO: CW 3-7, AIFSN 2, TXOP 1504 usec
	BSS Load:
		 * station count: 1
		 * channel utilisation: 0/255
		 * available admission capacity: 31250 [*32us]
	Overlapping BSS scan params:
		 * passive dwell: 20 TUs
		 * active dwell: 10 TUs
		 * channel width trigger scan interval: 300 s
		 * scan passive total per channel: 200 TUs
		 * scan active total per channel: 20 TUs
		 * BSS width channel transition delay factor: 5
		 * OBSS Scan Activity Threshold: 0.25 %
	Extended capabilities: HT Information Exchange Supported
	Country: US	Environment: Indoor/Outdoor
		Channels [1 - 11] @ 16 dBm
BSS 12:cf:e2:61:5d:30(on wlp6s0)
	TSF: 1475030019010 usec (17d, 01:43:50)
	freq: 2412
	beacon interval: 100 TUs
	capability: ESS Privacy ShortSlotTime (0x0411)
	signal: -60.00 dBm
	last seen: 11628 ms ago
	Information elements from Probe Response frame:
	SSID: 
	Supported rates: 1.0* 2.0* 5.5* 11.0* 9.0 18.0 36.0 54.0 
	DS Parameter set: channel 1
	Extended supported rates: 6.0* 12.0* 24.0* 48.0 
	Country: US	Environment: Indoor/Outdoor
		Channels [1 - 11] @ 20 dBm
	TIM: DTIM Count 0 DTIM Period 1 Bitmap Control 0x0 Bitmap[0] 0x0
	ERP: Barker_Preamble_Mode
	HT capabilities:
		Capabilities: 0x11ee
			HT20/HT40
			SM Power Save disabled
			RX HT20 SGI
			RX HT40 SGI
			TX STBC
			RX STBC 1-stream
			Max AMSDU length: 3839 bytes
			DSSS/CCK HT40
		Maximum RX AMPDU length 65535 bytes (exponent: 0x003)
		Minimum RX AMPDU time spacing: 4 usec (0x05)
		HT RX MCS rate indexes supported: 0-15, 32
		HT TX MCS rate indexes are undefined
	HT operation:
		 * primary channel: 1
		 * secondary channel offset: no secondary
		 * STA channel width: 20 MHz
		 * RIFS: 0
		 * HT protection: 20 MHz
		 * non-GF present: 1
		 * OBSS non-GF present: 0
		 * dual beacon: 0
		 * dual CTS protection: 0
		 * STBC beacon: 0
		 * L-SIG TXOP Prot: 0
		 * PCO active: 0
		 * PCO phase: 0
	Overlapping BSS scan params:
		 * passive dwell: 20 TUs
		 * active dwell: 10 TUs
		 * channel width trigger scan interval: 300 s
		 * scan passive total per channel: 200 TUs
		 * scan active total per channel: 20 TUs
		 * BSS width channel transition delay factor: 5
		 * OBSS Scan Activity Threshold: 0.25 %
	Extended capabilities: HT Information Exchange Supported
	RSN:	 * Version: 1
		 * Group cipher: CCMP
		 * Pairwise ciphers: CCMP
		 * Authentication suites: PSK
		 * Capabilities: 1-PTKSA-RC 1-GTKSA-RC (0x0000)
	WMM:	 * Parameter version 1
		 * BE: CW 15-1023, AIFSN 3
		 * BK: CW 15-1023, AIFSN 7
		 * VI: CW 7-15, AIFSN 2, TXOP 3008 usec
		 * VO: CW 3-7, AIFSN 2, TXOP 1504 usec
	BSS Load:
		 * station count: 1
		 * channel utilisation: 0/255
		 * available admission capacity: 31250 [*32us]
BSS 94:c1:50:c2:98:fe(on wlp6s0)
	TSF: 4736614812 usec (0d, 01:18:56)
	freq: 2457
	beacon interval: 100 TUs
	capability: ESS Privacy ShortSlotTime (0x0411)
	signal: -74.00 dBm
	last seen: 9290 ms ago
	Information elements from Probe Response frame:
	SSID: ATT871
	Supported rates: 1.0* 2.0* 5.5* 11.0* 18.0 24.0 36.0 54.0 
	DS Parameter set: channel 10
	TIM: DTIM Count 1 DTIM Period 3 Bitmap Control 0x0 Bitmap[0] 0x0
	Country: US	Environment: Indoor/Outdoor
		Channels [1 - 11] @ 30 dBm
	ERP: <no flags>
	ERP D4.0: <no flags>
	RSN:	 * Version: 1
		 * Group cipher: TKIP
		 * Pairwise ciphers: CCMP TKIP
		 * Authentication suites: PSK
		 * Capabilities: 16-PTKSA-RC 1-GTKSA-RC (0x000c)
	Extended supported rates: 6.0 9.0 12.0 48.0 
	BSS Load:
		 * station count: 1
		 * channel utilisation: 25/255
		 * available admission capacity: 0 [*32us]
	HT capabilities:
		Capabilities: 0x181c
			HT20
			SM Power Save disabled
			RX Greenfield
			No RX STBC
			Max AMSDU length: 7935 bytes
			DSSS/CCK HT40
		Maximum RX AMPDU length 65535 bytes (exponent: 0x003)
		Minimum RX AMPDU time spacing: 16 usec (0x07)
		HT RX MCS rate indexes supported: 0-15
		HT TX MCS rate indexes are undefined
	HT operation:
		 * primary channel: 10
		 * secondary channel offset: no secondary
		 * STA channel width: 20 MHz
		 * RIFS: 0
		 * HT protection: no
		 * non-GF present: 1
		 * OBSS non-GF present: 0
		 * dual beacon: 0
		 * dual CTS protection: 0
		 * STBC beacon: 0
		 * L-SIG TXOP Prot: 0
		 * PCO active: 0
		 * PCO phase: 0
	Extended capabilities: BSS Transition
	WPA:	 * Version: 1
		 * Group cipher: TKIP
		 * Pairwise ciphers: CCMP TKIP
		 * Authentication suites: PSK
		 * Capabilities: 16-PTKSA-RC 1-GTKSA-RC (0x000c)
	WMM:	 * Parameter version 1
		 * u-APSD
		 * BE: CW 15-1023, AIFSN 3
		 * BK: CW 15-1023, AIFSN 7
		 * VI: CW 7-15, AIFSN 2, TXOP 3008 usec
		 * VO: CW 3-7, AIFSN 2, TXOP 1504 usec
BSS e4:f4:c6:02:e9:80(on wlp6s0)
	TSF: 2687916134474 usec (31d, 02:38:36)
	freq: 5765
	beacon interval: 100 TUs
	capability: ESS Privacy RadioMeasure (0x1011)
	signal: -40.00 dBm
	last seen: 1018 ms ago
	Information elements from Probe Response frame:
	SSID: R&RLabs
	Supported rates: 6.0* 9.0 12.0* 18.0 24.0* 36.0 48.0 54.0 
	TIM: DTIM Count 1 DTIM Period 2 Bitmap Control 0x0 Bitmap[0] 0x0
	RSN:	 * Version: 1
		 * Group cipher: CCMP
		 * Pairwise ciphers: CCMP
		 * Authentication suites: PSK
		 * Capabilities: 16-PTKSA-RC 1-GTKSA-RC (0x000c)
	BSS Load:
		 * station count: 5
		 * channel utilisation: 4/255
		 * available admission capacity: 0 [*32us]
	HT capabilities:
		Capabilities: 0x9ef
			RX LDPC
			HT20/HT40
			SM Power Save disabled
			RX HT20 SGI
			RX HT40 SGI
			TX STBC
			RX STBC 1-stream
			Max AMSDU length: 7935 bytes
			No DSSS/CCK HT40
		Maximum RX AMPDU length 65535 bytes (exponent: 0x003)
		Minimum RX AMPDU time spacing: 4 usec (0x05)
		HT RX MCS rate indexes supported: 0-23
		HT TX MCS rate indexes are undefined
	HT operation:
		 * primary channel: 153
		 * secondary channel offset: below
		 * STA channel width: any
		 * RIFS: 1
		 * HT protection: no
		 * non-GF present: 1
		 * OBSS non-GF present: 0
		 * dual beacon: 0
		 * dual CTS protection: 0
		 * STBC beacon: 0
		 * L-SIG TXOP Prot: 0
		 * PCO active: 0
		 * PCO phase: 0
	Extended capabilities: Extended Channel Switching, BSS Transition, 6
	VHT capabilities:
		VHT Capabilities (0x0f8259b2):
			Max MPDU length: 11454
			Supported Channel Width: neither 160 nor 80+80
			RX LDPC
			short GI (80 MHz)
			TX STBC
			SU Beamformer
			SU Beamformee
		VHT RX MCS set:
			1 streams: MCS 0-9
			2 streams: MCS 0-9
			3 streams: MCS 0-9
			4 streams: not supported
			5 streams: not supported
			6 streams: not supported
			7 streams: not supported
			8 streams: not supported
		VHT RX highest supported: 0 Mbps
		VHT TX MCS set:
			1 streams: MCS 0-9
			2 streams: MCS 0-9
			3 streams: MCS 0-9
			4 streams: not supported
			5 streams: not supported
			6 streams: not supported
			7 streams: not supported
			8 streams: not supported
		VHT TX highest supported: 0 Mbps
	VHT operation:
		 * channel width: 1 (80 MHz)
		 * center freq segment 1: 155
		 * center freq segment 2: 0
		 * VHT basic MCS set: 0x0000
	WPS:	 * Version: 1.0
		 * Wi-Fi Protected Setup State: 2 (Configured)
		 * AP setup locked: 0x01
		 * UUID: 57807981-410d-9ac5-efab-60c1459fc747
		 * RF Bands: 0x3
		 * Unknown TLV (0x1049, 6 bytes): 00 37 2a 00 01 20
	WMM:	 * Parameter version 1
		 * u-APSD
		 * BE: CW 15-1023, AIFSN 3
		 * BK: CW 15-1023, AIFSN 7
		 * VI: CW 7-15, AIFSN 2, TXOP 6016 usec
		 * VO: CW 3-7, AIFSN 2, TXOP 3264 usec

**Comment by lwfinger** [comment]
Your scan shows a 5G channel with sufficient strength. The only thing I find that is strange is the "&" in the SSID, but that should not be a problem. Are there any such characters in the passphrase as well? At one time I had to escape a dollar sign when using openSUSE.

**Comment by warrenpw** [comment]
That's a good thought, but the passphrase is alphanumeric; no special
characters.

**Comment by max7255** [comment]
Hi!

Got the similiar problem (auth timed out for 5ghz network, though 2ghz net works ok) with Asus PCE-AC51 also equipped with rtl8812ae on 4.8.0-45 kernel (Ubuntu).

i've monitored radio using airodump-ng on other device and it turns out that AP just does not respond on adapter probe or repeatable (48 retransmit rounds for each of 3 auth frame SN) adapter authentication requests on 5 Ghz band.

I've also managed to connect to 5GHz AP using driver available on asus website, but it cannot be built on kernel > 4.4.

Here is my iw dev scan output just in case
[iw_scan.txt](https://github[Uploading iw_scan.txt…]().com/lwfinger/rtlwifi_new/files/891637/iw_scan.txt)

**Comment by max7255** [comment]
Turns out that tx power set by rtlwifi was too low - the AP just cpuldn't receive frames from adapter.

Also I've noticed that constants for e.g. RA_RFE_PINMUX or RA_RFE_PINMUX are for RFE type 2 or 4 only, however my adapter has RFE type 1 (rtl8821ae/phy.c : 617).

So I just used RFE 1 values from http://dlcdnet.asus.com/pub/ASUS/wireless/PCE-AC51/DR_PCE_AC51_20232801152016.zip (linux_driver/driver/hal/rtl8812a/rtl8812a_phycfg.c : 1200) sources  - and 5GHz band starts working OK.

Unfortunately, I don't know for sure what "RFE type" actually mean, just was lucky discovering this.

There are also other rfe types with their own values, so probably the same switch should be implemented in rtlwifi. I can submit a pull request, if it will be useful.

**Comment by lwfinger** [comment]
Either submit a pull request or post a "git diff". I do not have an RTL8812AE card, thus I cannot verify the low power for the 5G radio. Your result is sufficient for me.

**Comment by warrenpw** [comment]
Hello there!

Sorry I haven't checked in on this in a while; life got rather busy.

That being said, I saw that @max7255 submitted [commit 56909b026c5a5b7521627018f87e295db8d8f92a](https://github.com/lwfinger/rtlwifi_new/commit/56909b026c5a5b7521627018f87e295db8d8f92a) to add the RFE value changes he mentioned.
After syncing the repo and building the new drivers, it appears to work flawlessly; I can connect without issue to the 5GHz network that was previously giving me trouble. As such, I'm closing this issue as fixed.

Thanks!

Warren
