### ISSUE TITLE
ant_sel for wifi is good, but not for bluetooth rtl8723be

### ISSUE THREAD

**Issue by iwaniwaniwan012** [lwfinger/rtlwifi_new#222]
I use debian stretch, use you driver, when i use conf with ant_sel=1 wifi begin works good, but BT low, only near laptop(0,2 - 0,3 m), when use ant_sel=2, BT works good, but wifi not, only near switch. What try to do?

**Comment by InfiniteCoder** [comment]
In my case, bluetooth works near the laptop in either case. Wifi works properly only if ant_sel=1

**Comment by mirh** [comment]
#263
