### ISSUE TITLE
concurrent modes

### ISSUE THREAD

**Issue by taner1** [lwfinger/rtlwifi_new#223]
there is no such thing as autoconf.h so how can i edit sources to enable concurrent mode with 8723be, 8188eu or 8192cu drivers? its for ap+sta configuration

**Comment by lwfinger** [comment]
For rtl8723be and rtl8723cu, concurrent modes are covered by mac80211, cfg80211, and nl80211. You only need to set up the configuration there, not change the driver. For rtl8188eu, I recommend a new kernel (4.10) and the usage of driver rtl8xxxu. With it, concurrent mode is handled by *80211.

**Comment by taner1** [comment]
I tried to add virtual interface but when i try command "ifconfig ap0 up" it says name not unique on network so i changed mac address with ip link set ap0 addr xx:.. last 1 octet down and it was done but then i got "SIOCSIFFLAGS: Device or resource busy" error. If i down first interface then i'm able to up ap0 interface but this time with wlan0 i get same error. long story short i cant find a way to get two interfaces up same time :confused: also iw phy command output "no interface combinations are supported". i tried both rtl8723be and 8192cu with latest compiled drivers on 4.4.0-66 kernel - ubuntu 16.04.2 no luck.
