### ISSUE TITLE
rtl8723be & speed difference at linux and windows

### ISSUE THREAD

**Issue by ghost** [lwfinger/rtlwifi_new#225]
Lenovo 100-15iby laptop with rtl8723be wireless card with one soldered to it antenna connector. Ubuntu 16.10 with latest driver from this repo. Windows 10 with driver version 2023.47.1115.2016. Laptop location and AP the same. Why so much speed difference ?
![image_2017-04-06_11-45-36](https://cloud.githubusercontent.com/assets/1379437/24746522/0e5eb806-1ac2-11e7-96b3-0540bb850f63.png)
![image_2017-04-06_11-57-15](https://cloud.githubusercontent.com/assets/1379437/24746523/0e5f3b78-1ac2-11e7-9ada-94e5e5644bf0.png)

**Comment by amtlib-dot-dll** [comment]
I have a similar problem, my card is RTL8188EE, the Windows driver version is 2023.30.301.2016, running on Windows 10 build 14393, and the Linux kernel version is 4.9.0-2 on Debian Sid, with the driver compiled from the master branch. The maximum downloading speed on Windows (~3 MiB/s) is nearly three times of the one on Linux (~1 MiB/s)

**Comment by gauravssnl** [comment]
I am using Ubuntu 16.04.2 with rtl8723be wireless card   and after installing rtlwifi_new ,my wifi works fine and i get good speed on Ubuntu similar to windows

**Comment by amtlib-dot-dll** [comment]
Ah, sorry but on my Fedora 25 it is all okay. The kernel version is 4.11 now, so I uninstalled my Debian

**Comment by gauravssnl** [comment]
ok.it is good then @amtlib-dot-dll

**Comment by mirh** [comment]
Check #263
