### ISSUE TITLE
Ubuntu 16.04 rtl8723be system hangs at login

### ISSUE THREAD

**Issue by rediflex** [lwfinger/rtlwifi_new#228]
After instaliing latest driver available on repository system hangs at login screen.

**Comment by pawojciechowski** [comment]
I have the same issue. Can't copy logs, but it's something about watchdog... :(

**Comment by lwfinger** [comment]
Try a new pull. I just pushed a fix.

**Comment by pawojciechowski** [comment]
It works for me ;) Thanks ;)
