### ISSUE TITLE
could you please provide driver for rtl8812au?

### ISSUE THREAD

**Issue by myljimcia** [lwfinger/rtlwifi_new#230]

**Comment by lwfinger** [comment]
Does not https://github.com/gnab/rtl8812au work?

**Comment by luffare** [comment]
https://github.com/gnab/rtl8812au didn't work with my chip.
But https://github.com/Grawp/rtl8812au_rtl8821au worked for me.
The second one that worked for me i based on a fork of v4.3.20 where as the first is based on v4.2.2.
I recommend everyone to try https://github.com/Grawp/rtl8812au_rtl8821au/tree/4.3.20 
It says it's primarily for Arch Linux but it should work for everyone, I'm no arch user and it worked for me.

**Comment by lwfinger** [comment]
This repo is strictly for the drivers in drivers/net/wireless/realtek/rtlwifi, and is provided to backport the latest versions to people that run older kernels. It has never been, and will never be, used to provide drivers for random Realtek USB devices.
