### ISSUE TITLE
Wifi signal range decreased after todays update for rtl8723be on ubuntu16.04.2

### ISSUE THREAD

**Issue by YUDHPK** [lwfinger/rtlwifi_new#231]
Wifi catching range reduced to less than half of what i used to get previously with same configurations

**Comment by lwfinger** [comment]
Please provide the output of 
sudo iw dev wlan0 scan | egrep "SSID|signal"

for both the versions that work and the one that fails.

Do you need to use ant_sel? If so, does changing the number make a difference?

**Comment by YUDHPK** [comment]
previously i had to set ant_sel=2 then it caught signal properly but now it doesnt work
i don't know how to revert to last version but i am giving the output of the current version

Output:
command failed: No such device (-19)

**Comment by lwfinger** [comment]
You need to adjust the "wlan0" to match the name of your wifi device. Please make that adjustment and post the output.

Use "git checkout 53bb57d665221ddf". That should get you back to what you had before. After a make and make install sequence, the rerun the scan again and post it as well.

**Comment by YUDHPK** [comment]
My wifi device name is Kothari_Modem i changed wlan0 to it but i had the same output

**Comment by lwfinger** [comment]
I think your device is wlp19s0. Use that instead of wlan0. To determine for sure, use "iw dev | grep Interface". I will try to discover what went wrong.

**Comment by YUDHPK** [comment]
<h4>For properly working driver scenario</h4>
<code>iw dev | grep Interface</code>
<samp>	Interface wlp19s0</samp>

<code>sudo iw dev wlp19s0 scan | egrep "SSID|signal"</code>
<samp>
<pre>	signal: -36.00 dBm
	SSID: sk
	signal: -64.00 dBm
	SSID: mehta
	signal: -72.00 dBm
	SSID: syshah100
	signal: -42.00 dBm
	SSID: Kothari_Modem
	signal: -68.00 dBm
	SSID: TP-LINK_JAYESH504
	signal: -50.00 dBm
	SSID: NIRAV
	signal: -70.00 dBm
	SSID: Joispot-wifi
	signal: -52.00 dBm
	SSID: BHARATI
	signal: -62.00 dBm
	SSID: NS_WIRE
	signal: -74.00 dBm
	SSID: Aayushi
</pre></samp>

**Comment by juanlatorre** [comment]
I had the same issue, confirmed, the workaround works amazingly.

Thanks !

**Comment by resilar** [comment]
I can also confirm the issue (Ubuntu Gnome 17.04). Reverting back to 53bb57d solved the problem.

**Comment by ajaybhatia** [comment]
. Reverting back to [53bb57d](https://github.com/lwfinger/rtlwifi_new/commit/53bb57d665221ddf9b6adbf08100483a9235cd2c) too solved the problem for me.

**Comment by PeaceAlways** [comment]
I cannnot revert back. I don't know why. But until now everything is working perectly. Now changing ant_sel to 0,1,2 nothing is working. I have same problem as above. Guide me how to get older zip. So, that I can compile and use it again.

**Comment by lwfinger** [comment]
I just reverted the repo back to 53bb57d. The Realtek engineers are working on the problem.
