### ISSUE TITLE
Would rtlwifi_new provide a driver for Realtek RTL8822BE?

### ISSUE THREAD

**Issue by mori97** [lwfinger/rtlwifi_new#233]

**Comment by lwfinger** [comment]
It will as soon as Realtek releases the driver to me.

**Comment by jeremyb31** [comment]
What about https://github.com/rtlwifi-linux/rtlwifi-next
It appears to have code for the rtl8822be

**Comment by lwfinger** [comment]
rtlwifi_new will have an rtl8822be driver as soon as Realtek releases it to me. You will need to fix the compile errors yourself or get the owner of that repo to help. It is not mine.

**Comment by jeremyb31** [comment]
The owner claims to be Realtek and it does compile with a few warnings with the 4.8 kernel.
Is it possible as the latest commit comes from Yan-Hsuan Chuang <yhchuang@realtek.com>

**Comment by lwfinger** [comment]
I am sure the owner is Realtek, but I do not know who Yan-Hsuan Chang is. He is not one of the engineers with whom I work. As I stated before, I will merge the new driver into rtlwifi_new as soon as it is merged into wireless-drivers-next, which is on the way to the kernel.

**Comment by shartrec** [comment]
I have been able to make and install the driver from https://github.com/rtlwifi-linux/rtlwifi-next, unfortunately at this stage it doesn't work very well.
is there a place I can provide feedback (logs etc) to assist in the development of this driver?

**Comment by okpatil4u** [comment]
+1

**Comment by yangfangs** [comment]
I also try to install driver from  [rtlwifi-next](https://github.com/rtlwifi-linux/rtlwifi-next) , but it's not work very well

**Comment by gothicman02** [comment]
the driver in rtlwifi-new now works.  Larry has added instructions in the notes for the driver set.  Thanks Larry!  I got these working on the HP envy ryzen laptop with the realtek rtl8822be wireless/bluetooth chipset running Kali Linux

**Comment by avinal** [comment]
I tried the instruction as given ....but it is still not working for me in HP-Pavilion x360 cd-0087-tu. Please help

**Comment by avinal** [comment]
Thanks Its working.

**Comment by iansamz** [comment]
Hey @avinal can you show me the commmands you used to add as a dkms 

Would really love to get rid of this problem and get back to work

**Comment by JoshRomero** [comment]
hey @gothicman02, I have the same Hp as you and i am having trouble using the built in Realtek wireless card on my Ubuntu system. Can you please advise me what you did to fix this?

**Comment by zhangsd20** [comment]
Hi，
.....
[   10.829016] rtlwifi: HALMAC_RET_CHIP_NOT_SUPPORT
[   10.833727] rtl8822be: RTL8822B Not boot from efuse!!
[   10.834544] rtl8822be: Using firmware rtlwifi/rtl8822befw.bin
[   10.851095] rtlwifi: rtlwifi: wireless switch is on
.....

This driver seems to be problematic, who can help me?

**Comment by iansamz** [comment]
I switched to Ubuntu

**Comment by zhangsd20** [comment]
Can you provide a log of successful drive?
