### ISSUE TITLE
Upstream all this stuff?

### ISSUE THREAD

**Issue by yoshimo** [lwfinger/rtlwifi_new#234]
Are there efforts to push all these drivers from the various rt repos here into the mailine kernel?

**Comment by lwfinger** [comment]
Of course. Why did you think that not to be the case. As new material is ready for upstream, it is placed here so that users of older kernels have access to it.

**Comment by yoshimo** [comment]
Because for mt7610un & mt7662u that are needed for certain AVM devices people get still referred to this repository and a ppa that builds from it and the 4.11 kernel doesn't enable either of these devices.

**Comment by lwfinger** [comment]
If you look carefully, there are no drivers for any mt76xx devices here. If someone incorrectly references this repo, then fix them. If you want drivers for those devices in the mainline kernel, you will need to do the work. If I had not made an effort, there might not be any Realtek drivers in any kernel.

I work very hard at making the Realtek drivers be as good as possible and I have little time for responding to anyone with questions like this.
