### ISSUE TITLE
[Solved] RTL8723BE bluetooth broken, Can't read local name on hci0: Connection timed out (110)

### ISSUE THREAD

**Issue by DFOXpro** [lwfinger/rtlwifi_new#237]
### Solution
Edit driver variable `ant_sel` to 1 and disable `tls` if any
`cat /etc/modprobe.d/rtl8723be.conf`

    options rtl8723be ant_sel=1 fwlps=0 swlps=0

### Note

I already unistall `tlp` but get the same error

### Enviorement

 - Hardware: Lenovo Yoga 2 pro
 - Network controller: Realtek Semiconductor Co., Ltd. RTL8723BE PCIe Wireless Network Adapter
 - Distro: Ubuntu(mate) 16.10
 - Driver: rtlwifi_new fetch and installed from May 4 2017

`cat /etc/modprobe.d/rtl8723be.conf`

    options rtl8723be ant_sel=2 fwlps=0 swlps=0 ips=0 swenc=1

`lsmod | grep -i rtl`

    btrtl                  16384  1 btusb
    bluetooth             520192  39 bnep,btbcm,btrtl,btusb,rfcomm,btintel
    rtl8723be              98304  0
    btcoexist             167936  1 rtl8723be
    rtl8723_common         24576  1 rtl8723be
    rtl_pci                32768  1 rtl8723be
    rtlwifi               102400  3 btcoexist,rtl_pci,rtl8723be
    mac80211              737280  3 rtl_pci,rtlwifi,rtl8723be
    cfg80211              565248  2 mac80211,rtlwifi

`dmesg | grep -i blue`

    [    3.142045] usb 2-7: Product: Bluetooth Radio 
    [    4.055401] Bluetooth: Core ver 2.21
    [    4.055418] Bluetooth: HCI device and connection manager initialized
    [    4.055422] Bluetooth: HCI socket layer initialized
    [    4.055425] Bluetooth: L2CAP socket layer initialized
    [    4.055431] Bluetooth: SCO socket layer initialized
    [    4.063451] Bluetooth: hci0: rtl: examining hci_ver=06 hci_rev=000b lmp_ver=06 lmp_subver=8723
    [    4.063453] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723b_fw.bin
    [    4.065463] Bluetooth: hci0: rom_version status=0 version=1
    [    5.206315] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
    [    5.206319] Bluetooth: BNEP filters: protocol multicast
    [    5.206324] Bluetooth: BNEP socket layer initialized
    [   10.613719] Bluetooth: RFCOMM TTY layer initialized
    [   10.613727] Bluetooth: RFCOMM socket layer initialized
    [   10.613733] Bluetooth: RFCOMM ver 1.11
    [   12.605421] Bluetooth: hci0 command 0x0c24 tx timeout
    [   14.609522] Bluetooth: hci0 command 0x0c52 tx timeout
    [   27.266360] Bluetooth: hci0 command 0x0c14 tx timeout  #Note this timeout launch every time I use hciconfig -a

`hciconfig -a`

    hci0:	Type: BR/EDR  Bus: USB
    	BD Address: 10:08:B1:73:91:5A  ACL MTU: 820:8  SCO MTU: 255:16
    	UP RUNNING 
    	RX bytes:1297 acl:0 sco:0 events:134 errors:0
    	TX bytes:24821 acl:0 sco:0 commands:140 errors:0
    	Features: 0xff 0xff 0xff 0xfe 0xdb 0xff 0x7b 0x87
    	Packet type: DM1 DM3 DM5 DH1 DH3 DH5 HV1 HV2 HV3 
    	Link policy: RSWITCH HOLD SNIFF PARK 
    	Link mode: SLAVE ACCEPT 
    Can't read local name on hci0: Connection timed out (110)

**Comment by DFOXpro** [comment]
how can I help to improve the debug data for you @lwfinger @rtlwifi-linux

**Comment by lwfinger** [comment]
Does your machine really need ant_sel=2? In addition, if you are using this repo, then the Xps options and swenc should not be needed.

If you really do need the ant_sel option, does BT work with ant_sel=1?

**Comment by DFOXpro** [comment]
as @lwfinger changing ant_sel to 1 (and in other post disabling tls) start to work the bluetooth

Mark as solved
Sidenote 1: thanks @lwfinger it was fast
Sidenote 1: it's the fist time(in 3 years of ownership) that I'm using the bluetooth withi this adapter :heart:

**Comment by begonaalfonso** [comment]
Hello DFOXpro
I am facing the same problem and trying to follow your solution. However, I am not sure how to disable tls. Could you please elaborate or point me at the other post where that was explained.

thanks in advance.

**Comment by DFOXpro** [comment]
The fastest way is to uninstall tls package or disable tls service
In Ubuntu I did:
sudo chmod -xv /etc/init.d/tls*
then restart and test
I recommend doing this via nautilus (properties > permission uncheck exec checkbox)to prevent any naming error

**Comment by begonaalfonso** [comment]
Hello Dfoxpro,
I am guessing you meant /etc/init.d/tlp. I changed it to non executable znd restart but still no device is discovered. So frustrating...

**Comment by DFOXpro** [comment]
@begonaalfonso what is the content of /etc/modprobe.d/rtl8723be.conf

**Comment by begonaalfonso** [comment]
all seems fine. I reinstalled the system. No tlp is to be found. Howeever the problem persists.
bego@pc-bego:~$ cat /etc/modprobe.d/rtl8723be.conf
options rtl8723be ant_sel=1 fwlps=0 swlps=0
bego@pc-bego:~$ sudo bluetoothctl
[NEW] Controller 28:C2:DD:AA:85:AE pc-bego [default]
[bluetooth]# show
Controller 28:C2:DD:AA:85:AE
	Name: pc-bego
	Alias: pc-bego
	Class: 0x0c010c
	Powered: yes
	Discoverable: no
	Pairable: yes
	UUID: Audio Sink                (0000110b-0000-1000-8000-00805f9b34fb)
	UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
	UUID: Audio Source              (0000110a-0000-1000-8000-00805f9b34fb)
	UUID: A/V Remote Control        (0000110e-0000-1000-8000-00805f9b34fb)
	UUID: PnP Information           (00001200-0000-1000-8000-00805f9b34fb)
	UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
	UUID: A/V Remote Control Target (0000110c-0000-1000-8000-00805f9b34fb)
	Modalias: usb:v1D6Bp0246d0525
	Discovering: no
[bluetooth]#

**Comment by begonaalfonso** [comment]
however it looks like the driver is not taking the added parameters into account;
bego@pc-bego:~$ sudo modprobe rtl8723be ant_sel=1 fwlps=0 swlps=0
bego@pc-bego:~$ sudo modinfo rtl8723be 
filename:       /lib/modules/4.8.0-53-generic/kernel/drivers/net/wireless/realtek/rtlwifi/rtl8723be/rtl8723be.ko
firmware:       rtlwifi/rtl8723befw.bin
description:    Realtek 8723BE 802.11n PCI wireless
license:        GPL
author:         Realtek WlanFAE	<wlanfae@realtek.com>
author:         PageHe	<page_he@realsil.com.cn>
srcversion:     1520FD8B69687790125304A
alias:          pci:v000010ECd0000B723sv*sd*bc*sc*i*
depends:        rtlwifi,rtl8723-common,rtl_pci,btcoexist,mac80211
intree:         Y
vermagic:       4.8.0-53-generic SMP mod_unload modversions 
parm:           swenc:Set to 1 for software crypto (default 0)
 (bool)
parm:           ips:Set to 0 to not use link power save (default 1)
 (bool)
parm:           swlps:Set to 1 to use SW control power save (default 0)
 (bool)
parm:           fwlps:Set to 1 to use FW control power save (default 1)
 (bool)
parm:           msi:Set to 1 to use MSI interrupts mode (default 0)
 (bool)
parm:           debug:Set debug level (0-5) (default 0) (int)
parm:           disable_watchdog:Set to 1 to disable the watchdog (default 0)
 (bool)
parm:           ant_sel:Set to 1 or 2 to force antenna number (default 0)
 (int)

**Comment by lwfinger** [comment]
modinfo gets its parameters from the driver built into the kernel. It will not be affected by the actual parameters used to load the driver. Look at the dmesg output to see if the parameter is accepted.

**Comment by begonaalfonso** [comment]
thanks lwfinger. In the meantime I installed 17.04 with no success on this front (i just added some more issues to this one). So I am back to 16.04. I have followed this instructions to install the driver after creating the rtl8723be.conf with the mentioned options. 
sudo apt-get install linux-headers-generic build-essential git
git clone https://github.com/lwfinger/rtlwifi_new.git
cd rtlwifi_new
make
sudo make install
sudo modprobe rtl8723be
There is no tlp installed.
however, bluetooth still not functioning (not discovering, not visible in other devices).

This are the dmesg outputs:
bego@pc-bego:~$ dmesg | grep -i rtl
[    9.666037] rtlwifi: loading out-of-tree module taints kernel.
[    9.666138] rtlwifi: module verification failed: signature and/or required key missing - tainting kernel
[   10.009250] rtl8723be 0000:02:00.0: enabling device (0000 -> 0003)
[   10.034245] rtl8723be: Using firmware rtlwifi/rtl8723befw_36.bin
[   10.208044] ieee80211 phy0: Selected rate control algorithm 'rtl_rc'
[   10.208483] rtlwifi: rtlwifi: wireless switch is on
[   11.744748] rtl8723be 0000:02:00.0 wlp2s0: renamed from wlan0
bego@pc-bego:~$ dmesg | grep -i blue
[    1.930538] usb 1-2: Product: Bluetooth Radio 
[    8.666221] Bluetooth: Core ver 2.21
[    8.666244] Bluetooth: HCI device and connection manager initialized
[    8.666249] Bluetooth: HCI socket layer initialized
[    8.666252] Bluetooth: L2CAP socket layer initialized
[    8.666261] Bluetooth: SCO socket layer initialized
[    8.843958] toshiba_bluetooth: Toshiba ACPI Bluetooth device driver
[    8.905468] Bluetooth: HCI UART driver ver 2.3
[    8.905472] Bluetooth: HCI UART protocol H4 registered
[    8.905473] Bluetooth: HCI UART protocol BCSP registered
[    8.905474] Bluetooth: HCI UART protocol LL registered
[    8.905474] Bluetooth: HCI UART protocol ATH3K registered
[    8.905475] Bluetooth: HCI UART protocol Three-wire (H5) registered
[    8.905523] Bluetooth: HCI UART protocol Intel registered
[    8.905545] Bluetooth: HCI UART protocol BCM registered
[    8.905546] Bluetooth: HCI UART protocol QCA registered
[    8.905547] Bluetooth: HCI UART protocol AG6XX registered
[   21.540846] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   21.540848] Bluetooth: BNEP filters: protocol multicast
[   21.540853] Bluetooth: BNEP socket layer initialized
[   30.210988] Bluetooth: RFCOMM TTY layer initialized
[   30.210998] Bluetooth: RFCOMM socket layer initialized
[   30.211014] Bluetooth: RFCOMM ver 1.11

bego@pc-bego:~$ cat  /etc/modprobe.d/rtl8723be.conf
options rtl8723be ant_sel=1 fwlps=0 swlps=0

**Comment by s3rvant** [comment]
I too am getting the -110 error even with antenna set to 1 and no tls in my /etc/init.d/
I'm on a HP 15-da0002dx with RTL8723DE running Ubuntu 19.10 on kernel 5.3.0-24

$ dmesg | grep -i bluetooth

Bluetooth: Core ver 2.22
Bluetooth: HCI device and connection manager initialized
Bluetooth: HCI socket layer initialized
Bluetooth: L2CAP socket layer initialized
Bluetooth: SCO socket layer initialized
Bluetooth: BNEP (Ethernet Emulation) ver 1.3
Bluetooth: BNEP filters: protocol multicast
Bluetooth: BNEP socket layer initialized
Bluetooth: hci0: command 0x1001 tx timeout
Bluetooth: hci0: RTL: HCI_OP_READ_LOCAL_VERSION failed (-110)

Any help would be much appreciated

**Comment by lwfinger** [comment]
I do not do BT, but I do not know of any cases where ant_sel=1 is correct. If your device has 2 antennas, then the default of 0 is best, and if you have only 1 antenna, then ant_sel=2 has always been correct! Error -110 means that the connection timed out. Setting the correct antenna may fix that.

**Comment by s3rvant** [comment]
> I do not do BT, but I do not know of any cases where ant_sel=1 is correct. If your device has 2 antennas, then the default of 0 is best, and if you have only 1 antenna, then ant_sel=2 has always been correct! Error -110 means that the connection timed out. Setting the correct antenna may fix that.

Set antenna to 0 and restarted, then got:

Bluetooth: Core ver 2.22
Bluetooth: HCI device and connection manager initialized
Bluetooth: HCI socket layer initialized
Bluetooth: L2CAP socket layer initialized
Bluetooth: SCO socket layer initialized
Bluetooth: hci0: RTL: rtl: examining hci_ver=08 hci_rev=000d lmp_ver=08 lmp_subver=8723
Bluetooth: hci0: RTL: rom_version status=0 version=2
Bluetooth: hci0: RTL: rtl: loading rtl_bt/rtl8723d_fw.bin
bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_fw.bin failed with error -2
Bluetooth: hci0: RTL: firmware file rtl_bt/rtl8723d_fw.bin not found
Bluetooth: BNEP (Ethernet Emulation) ver 1.3
Bluetooth: BNEP filters: protocol multicast
Bluetooth: BNEP socket layer initialized

Grabbed the missing firmware files from linux-firmware, placed in /lib/firmware/rtl_bt/ and restarted and now getting -110 again with different wording:

Bluetooth: Core ver 2.22
Bluetooth: HCI device and connection manager initialized
Bluetooth: HCI socket layer initialized
Bluetooth: L2CAP socket layer initialized
Bluetooth: SCO socket layer initialized
Bluetooth: hci0: RTL: rtl: examining hci_ver=08 hci_rev=000d lmp_ver=08 lmp_subver=8723
Bluetooth: hci0: RTL: rom_version status=0 version=2
Bluetooth: hci0: RTL: rtl: loading rtl_bt/rtl8723d_fw.bin
Bluetooth: hci0: RTL: rtl: loading rtl_bt/rtl8723d_config.bin
Bluetooth: hci0: RTL: cfg_sz 10, total sz 33266
Bluetooth: BNEP (Ethernet Emulation) ver 1.3
Bluetooth: BNEP filters: protocol multicast
Bluetooth: BNEP socket layer initialized
Bluetooth: hci0: command 0xfc20 tx timeout
Bluetooth: hci0: RTL: download fw command failed (-110)
