### ISSUE TITLE
wifi is hunging up on my laptop with rtl8821ae

### ISSUE THREAD

**Issue by ztutberidze** [lwfinger/rtlwifi_new#238]
when I power on my laptop wifi stuck's and it keeps un available about 5 minute, while it stuck I can't disable enable it, after 5 minute it is becomes working and I see >>>
[  351.669264] r8169 0000:01:00.0: invalid short VPD tag 00 at offset 1
<<< in dmesg.

**Comment by lwfinger** [comment]
The r8169 message is for a wired ethernet device, not wireless.

There is nothing in the wireless driver that can hang for more than a few ms. The kind of hang you describe is more likely caused by some part of user space controlling the network. As you did not state what distro you are using, and how you are controlling the network, I cannot speculate any further.

**Comment by ztutberidze** [comment]
Thank you for answer. I have lenovo idepad 310 laptop. I have tryied opensuse, fedora and ubuntu, all of them have same problem.

At this moment I am using kubuntu 16.04.2 with NetworkManager

**Comment by lwfinger** [comment]
I have no idea what is causing the problem. If you can post the entire dmesg in some pastebin and place the link here, I will take a look, I do not know what I will find. Some part of your userspace code is locking up. I really doubt that it is the kernel.

**Comment by paulsinnett** [comment]
I have the same laptop. Actually I have 10, and they all do this. The best result I've had so far is with Manjaro.

**Comment by ggramaize** [comment]
Hi, I have the same issue with the same chipset on an Asus E202S with Debian Stretch. 
Tested and reproducible with kernel shipped in stretch repository, and on a 4.11 kernel.

**Comment by lwfinger** [comment]
If someone sends me one of these offending models, then I'll take a look. Without having my hands on the hardware, it is impossible to tell what is happening.

**Comment by ggramaize** [comment]
lwfinger, I can send you a sample once I've received the replacement NIC for my laptop (I expect to receive it next Friday). I'll PM you when I'm ready to send it.

**Comment by lwfinger** [comment]
Sounds good. BTW, I'm in the US. I hope that does not cause any problems in the shipping.

**Comment by fleyer** [comment]
Same problem here with my lenovo ideapad 310. As paulsinnett, manjaro gives the best wifi even if it's a little buggy

**Comment by epassaro** [comment]
I have an Ideapad310 too.

Kernel 4.8.0-56-generic works great (no flwps=0 or ips=0 needed).
Kernel 4.8.0-58-generic hungs up again (with or without ps options disabled).
Kernel 4.10.x is almost unusable.

**Comment by kladier** [comment]
Did you finally receive the hardware ?
I'm on Linux Mint 18.2 kernel 4.10.0 and still have the same problem for months (I already opened an issue in this repo some months ago).
If you need help for anything, I'm dev and can help.
