### ISSUE TITLE
RTL8821AE: upload speed almost always slower than it should be.

### ISSUE THREAD

**Issue by stuart-mclaren** [lwfinger/rtlwifi_new#240]
I have a laptop with a mini PCIe half height card which has this chipset:

```
03:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8821AE 802.11ac PCIe Wireless Network Adapter
```

My router is a Virgin Media Hub 3.0.

With my other Linux devices (different chip sets) I can max out my broadband upload speed (25Mbps).
If I boot my laptop to another OS, I also reliably get 25Mbps upload speed out of the 8821ae.

When I boot to Linux (Debian 8) with the rtl8821e, I usually only get *5Mbps* -- not enough to max out my broadband.

I have -- very, very rarely -- got the full 25Mbps available from Linux/the 8821ae. So clearly it's possible. But 95% of the time it's just 5Mbps.

I've done some digging, but haven't found anything to explain the (seemingly random) upload speed difference between reboots.

I have permanently switched off the 5GHz band on the router since I found connecting to it with the 8821ae wasn't very stable.

I've tried switching the 2.4GHz channel that the router is on (from 11 to 6 to 1) to rule out interference with other hotspots. Doing this didn't reliably give good upload speed. I also tried changing the 20-40MHz setting ... again to no avail.

I also changed the regulatory domain -- no luck.

I also tried upgrading to the latest 4.11.0 kernel with the latest firmare from Debian's Jessie Backports which didn't change things.

I don't see any obvious differences when I'm getting 25Mbps versus 5Mbps.

For example, from a rare case where I was getting 25Mbps, the iwconfig output is:

```
wlan0     IEEE 802.11  ESSID:"XXXXX"  
          Mode:Managed  Frequency:2.412 GHz  Access Point: XX:XX:XX:99:9A:8F   
          Bit Rate=150 Mb/s   Tx-Power=20 dBm   
          Retry short limit:7   RTS thr=2347 B   Fragment thr:off
          Encryption key:off
          Power Management:on
          Link Quality=70/70  Signal level=-26 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0
```

which is the same as the usual 5Mbps case

```
wlan0     IEEE 802.11  ESSID:"XXXXX"  
          Mode:Managed  Frequency:2.412 GHz  Access Point: XX:XX:XX:99:9A:8F   
          Bit Rate=150 Mb/s   Tx-Power=20 dBm   
          Retry short limit:7   RTS thr=2347 B   Fragment thr:off
          Encryption key:off
          Power Management:on
          Link Quality=70/70  Signal level=-30 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:10   Missed beacon:0
```

The output of "iw dev wlan0 link" for the 25Mbps case is:

```
Connected to XX:XX:XX:99:9a:8f (on wlan0)
        SSID: XXXXX
        freq: 2412
        RX: 397625 bytes (2549 packets)
        TX: 23565 bytes (158 packets)
        signal: -28 dBm
        tx bitrate: 150.0 MBit/s MCS 7 40MHz short GI

        bss flags:      short-slot-time
        dtim period:    1
        beacon int:     100
```

again, the same as for the 5Mbps case:

```
Connected to XX:XX:XX:99:9a:8f (on wlan0)
        SSID: XXXXX
        freq: 2412
        RX: 198334892 bytes (147031 packets)
        TX: 24977082 bytes (81774 packets)
        signal: -32 dBm
        tx bitrate: 150.0 MBit/s MCS 7 40MHz short GI

        bss flags:      short-slot-time
        dtim period:    1
        beacon int:     100
```

I've compiled rtl8821ae.ko from the latest commit (https://github.com/lwfinger/rtlwifi_new) in debug mode.
I'll attach the 'dmesg' output in the case of a "5Mbps" connection. The "25Mbps" connection happens so rarely
that I don't have debug logs for that case.

Let me know if there is more info I can provide.

Thanks!

**Comment by stuart-mclaren** [comment]
dmesg log: Usual 5Mbps case, with debug:
[dmesg-5Mbps.txt](https://github.com/lwfinger/rtlwifi_new/files/1016304/dmesg-5Mbps.txt)

dmesg log: Rare 25Mbps case, no debug:
[dmesg-25Mbps.txt](https://github.com/lwfinger/rtlwifi_new/files/1016305/dmesg-25Mbps.txt)

**Comment by stuart-mclaren** [comment]
(In case anyone else is hitting this.)

I replaced the Realtek card with an Intel Wireless-N 7260. The new card/driver combination gives reliable performance.

**Comment by jatindhankhar** [comment]
I am having the same since the last upgrade.

Machine - `ideapad 310-15IKB` running Arch Linux with default kernel.

System Info

` Linux archbox 4.11.9-1-ARCH #1 SMP PREEMPT Wed Jul 5 18:23:08 CEST 2017 x86_64 GNU/Linux  `

`iwconfig`

```bash
wlp2s0    IEEE 802.11  ESSID:"XXXXXXXXXXX"  
          Mode:Managed  Frequency:2.447 GHz  Access Point: XX:XX:XX:XX:XX:XX   
          Bit Rate=150 Mb/s   Tx-Power=20 dBm   
          Retry short limit:7   RTS thr=2347 B   Fragment thr:off
          Power Management:on
          Link Quality=70/70  Signal level=10 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:926   Missed beacon:0

```

I can achieve max upload on other devices, as well as on the same machine with a different OS (Windows 10)

**Comment by lwfinger** [comment]
Since it happened "since the last upgrade", then you are in a perfect position to bisect the problem.

**Comment by jatindhankhar** [comment]
@lwfinger  I can try to downgrade to a known working configuration. How can I bisect the problem ? I am willing to help, do tell me the instructions, and log files to attach.

**Comment by lwfinger** [comment]
git bisect --help

**Comment by jatindhankhar** [comment]
@lwfinger  I was using the same version of rtlwifi to make modules for my card (rtl8821ae) 
Issue is with the latest kernel (I suppose). You sure git bisect will help ?

**Comment by lwfinger** [comment]
I was not the one that said that it worked better with a previous version. Of course, what constituted "a previous version" was not specified. You need to decide if you can clearly state what was changed, and reproducing the output of arbitrary commands is useless.

A final question is why you are using rtlwifi_new if you are running kernel 4.11.9. That version is newer than rtlwifi_new.

**Comment by jatindhankhar** [comment]
I am really sorry to create confusion. 

> A final question is why you are using rtlwifi_new if you are running kernel 4.11.9. That >version is newer than rtlwifi_new.
After every kernel upgrade I used to make and install rtlwifi_new. 
I removed the module from the kernel and upload speed is back to normal.

Sorry for wasting everybody's time, that was never my intention
