### ISSUE TITLE
Try to rtl8723be in qubes os

### ISSUE THREAD

**Issue by kpl0** [lwfinger/rtlwifi_new#241]
I installed Qubes OS on my laptop HP ac121br, with realtek RTL8723be. The signal of wifi is very weak. I downloaded rtlwifi_new but I can't make the Makefile. Can anyone help me? I've already installed kernel-devel and kernel-headers.

**Comment by lwfinger** [comment]
First of all, it is a lot easier to help when we get specific information. I could look to see what kernel Qubes uses, but I do not know if there is more than one version (likely). Please provide the output of the command 'uname -r'.

Secondly, you likely have one of those HP units with only one antenna, AND the misprogrammed EFUSE. You likely need to use the 'ant_sel=X' module option for rtl8723be. It was created specifically to handle HP's mistake.

Thirdly, how are we to know why you cannot "make the Makefile".

**Comment by danielcapello** [comment]
Lwfinger, 

Thank you for your comment and concern.
Before using Qubes, I had the same problem with ubuntu. I fixed it using these instructions (ant_sel=2).
http://askubuntu.com/questions/635625/how-do-i-get-a-realtek-8723be-wireless-card-to-work

But now, I can't do the same on qubes.
uname = 4.4.67-12.pvops.qubes.x86_64

When I follow the instructions after clonning rtlwifi_new, there is an error:
[user@sys-net rtlwifi_new]$ make
make -C /lib/modules/4.4.67-12.pvops.qubes.x86_64/build M=/home/user/rtlwifi_new modules
make[1]: *** /lib/modules/4.4.67-12.pvops.qubes.x86_64/build: No such file or directory. Stop.
Makefile:58: recipe for target 'all' failed
make:*** [all] Error 2

**Comment by lwfinger** [comment]
Kernel 4.4 is too old to have the ant_sel fix.

The error message indicates that you have not installed all the packages needed to build external modules. As I have no experience with Qubes, I can offer no further help.

**Comment by danielcapello** [comment]
Thank you, anyway. So, if qubes update its kernel, the problem can be solved? Am I correct? I don't have deep knowledge in computer science.

**Comment by lwfinger** [comment]
Yes, but that might take a long time for them to reach 4.9. You need to find out what it takes to build an external kernel module in Qubes. I know what it takes in openSUSE, which I use. You will need to do the research for Qubes.
