### ISSUE TITLE
Ubuntu 16.04 LTS issue with rtl8723be and the make-command

### ISSUE THREAD

**Issue by DaveMitHut** [lwfinger/rtlwifi_new#242]
I'm running into an issue with the rtl8723be driver while trying to install it. I'm fairly new to installing via console, so I'm sorry if my questions seem dumb to you.

First, the uname -r output:
4.8.0-53-generic

Now my issue:
When I've changed into the directory of the rtl8723be and execute the 'make' command, it tells me the following:
make: *** No target. Ending. (Or similar, my console output is in german)

If I execute 'make Makefile' it tells me:
make: Nothing to do for the target "Makefile".

So where am I going wrong? Help would be greatly appreciated, I can only use my notebook at home with a cable for a network connection at the moment.

**Comment by lwfinger** [comment]
The system is not configured to make only a single rtlwifi driver. You will need to change directory to the rtlwifi_new directory and do the "make" and "sudo make install" from there.

**Comment by DaveMitHut** [comment]
Thank you for the fast reply! I did that and now it says:
make[1]: *** /lib/modules/4.8.0-53-generic/build: File or Directory not found.
Makefile:58: The rule or for target "all" failed.

Did I miss anything?

**Comment by lwfinger** [comment]
Yes, you have not installed the kernel headers or the kernel development package.

**Comment by DaveMitHut** [comment]
Thanks a lot! The installation worked after downloading the kernel headers. I now have the drivers installed! My wifi still doesn't work though, but I'm not sure why. The on-button keeps on sliding back in the off-position, and I really don't know why. If you know a fix for this, let me know, if not, thanks anyway! It's great that you help people with this.

**Comment by DaveMitHut** [comment]
It worked now, thank you!

**Comment by kanhaji** [comment]
**uname -r**
4.9.0-kali3-amd64

**apt-get install linux-headers***
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'linux-headers-4.15.0-kali3-cloud-amd64' for glob 'linux-headers*'
Note, selecting 'linux-headers-generic' for glob 'linux-headers*'
Note, selecting 'linux-headers-4.15.0-kali3-common' for glob 'linux-headers*'
Note, selecting 'linux-headers-686-pae' for glob 'linux-headers*'
Note, selecting 'linux-headers-4.15.0-kali3-amd64' for glob 'linux-headers*'
Note, selecting 'linux-headers-4.15.0-kali3-all-amd64' for glob 'linux-headers*'
Note, selecting 'linux-headers-amd64' for glob 'linux-headers*'
Note, selecting 'linux-headers' for glob 'linux-headers*'
Note, selecting 'linux-headers-4.15.0-kali3-all' for glob 'linux-headers*'
Note, selecting 'linux-headers-cloud-amd64' for glob 'linux-headers*'
linux-headers-4.15.0-kali3-all is already the newest version (4.15.17-1kali1).
linux-headers-4.15.0-kali3-all-amd64 is already the newest version (4.15.17-1kali1).
linux-headers-4.15.0-kali3-amd64 is already the newest version (4.15.17-1kali1).
linux-headers-4.15.0-kali3-cloud-amd64 is already the newest version (4.15.17-1kali1).
linux-headers-4.15.0-kali3-common is already the newest version (4.15.17-1kali1).
linux-headers-amd64 is already the newest version (4.15+92+kali1).
linux-headers-cloud-amd64 is already the newest version (4.15+92+kali1).
0 upgraded, 0 newly installed, 0 to remove and 480 not upgraded.

**root@Bakhtawar:~/Downloads/rtlwifi_new# make**
make -C /lib/modules/4.9.0-kali3-amd64/build M=/root/Downloads/rtlwifi_new modules
make[1]: *** /lib/modules/4.9.0-kali3-amd64/build: No such file or directory.  Stop.
Makefile:58: recipe for target 'all' failed
make: *** [all] Error 2


can anyone help me with this.. i have installed latest headers as well but still ir says no module...

**Comment by lwfinger** [comment]
You have a 4.9i kernel, but are installing the 4.15 headers. They MUST match.
