### ISSUE TITLE
Is there any solution?

### ISSUE THREAD

**Issue by jsroyal** [lwfinger/rtlwifi_new#243]
My laptop disconnected wifi in random time.
![image](https://cloud.githubusercontent.com/assets/10773353/26667268/e8664318-46c1-11e7-9e0a-c72b09acb91e.png)

jsroyal@HP:~$ lspci -knn | grep Net -A2
01:00.0 Network controller [0280]: Qualcomm Atheros AR9485 Wireless Network Adapter [168c:0032] (rev 01)
	DeviceName: Atheros 802.11b/g/n WiFi/BT Combo
	Subsystem: Hewlett-Packard Company AR9485 Wireless Network Adapter [103c:1785]
	Kernel driver in use: ath9k
	Kernel modules: ath9k

**Comment by lwfinger** [comment]
Why are you asking about an Atheros card in a repo that ONLY contains Realtek drivers?

**Comment by jsroyal** [comment]
Sorry I got refer this repo from lots question related and my keyword search.
I thought it would be worth it if I get related solution.
Sorry I don't know too much about it networking and hardware configuration.
By way thank you.
