### ISSUE TITLE
ant_sel issues with using bluetooth and wifi at same time for rtl8723be

### ISSUE THREAD

**Issue by InfiniteCoder** [lwfinger/rtlwifi_new#244]
I found out that other than the usual `rtl8723be.conf` file, we can also use `rtlbtcoex.conf` file.
Trying to use bluetooth and wifi together has some big issues though,

1. If I use `ant_sel=1` option in `rtlbtcoex.conf` file, I get full signal for wifi, but bluetooth does not work for more than few feet. Transmit power is 50% and **signal strength 34%** while link quality is 10%.
2. If I use `ant_sel=2` option in `rtlbtcoex.conf` file, wifi signal is very low, but bluetooth works for expected distance(about 20 feet), even though transmit power still is 50% and **signal strength 46%** while link quality is 10%.

Is there someway I can use both at the same time, with full signal for both? btw I have already removed tlp.

**Comment by PRESFIL** [comment]
i have same problem. core: 4.10.0-26-generic. srcversion: 0BB42E4C7EBEC81FFE99621

**Comment by InfiniteCoder** [comment]
@PRESFIL Can you provide details about your OS and hardware so that we could pin down the problem?

**Comment by InfiniteCoder** [comment]
@lwfinger Is this related to [this patch of your's?](https://patchwork.kernel.org/patch/9937493/). I Installed 4.14 on my Manjaro OS, but it seems it doesn't fix any issues, rather, I could get bluetooth to work as I used to do as mentioned in first post.

**Comment by mirh** [comment]
https://github.com/lwfinger/rtlwifi_new/issues/259#issuecomment-327005167
Yes it \*should\* be supposed to.

**Comment by PRESFIL** [comment]
@InfiniteCoder I want to try Linux Mint Cinnamon 18.3 soon, will take a >=4.12 kernel and report the results

**Comment by InfiniteCoder** [comment]
@PRESFIL Let me know what you find

**Comment by PRESFIL** [comment]
The default driver linux mint 18.3 + core 4.13.0-32-generic is not working properly. Put a fresh rtlwifi - as before wifi works fine and bluetooth only when wifi is enabled.
```
cat /etc/modprobe.d/rtl8723be.conf 
options rtl8723be ant_sel=2 fwlps=0 swlps=0 ips=0 swenc=1
```

**Comment by lwfinger** [comment]
Why do you turn off power saving and hardware encryption? If you read that somewhere, that author had not the slightest clue. You are merely draining your battery quicker and making your CPU work harder.

I do not deal with BT. You are on your own.
