### ISSUE TITLE
Fails to compile

### ISSUE THREAD

**Issue by FreelancePoliceman** [lwfinger/rtlwifi_new#245]
This fails to compile with the latest version of cmake.

**Comment by lwfinger** [comment]
What errors do you get? I'm actually surprised that you are using cmake. Ordinary make is sufficient.

**Comment by FreelancePoliceman** [comment]
Whoops. I meant make! The issue seems to have stopped for some reason, so it was likely a problem with my system. Apologies for the trouble.
