### ISSUE TITLE
Possible issue with new kernels

### ISSUE THREAD

**Issue by FreelancePoliceman** [lwfinger/rtlwifi_new#247]
I apologize for my previous issue; I have no idea what I was thinking. It's entirely possible I'm overlooking something stupid, but when using Linux 4.12.0-rc5, this fails to compile. The given error message is

    /home/nil/Downloads/rtlwifi_new/rtl8188ee/trx.c: In function ‘rtl88ee_rx_query_desc’:    
    /home/nil/Downloads/rtlwifi_new/rtl8188ee/trx.c:447:22: error: ‘RX_FLAG_40MHZ’ undeclared   first use in this function)
       rx_status->flag |= RX_FLAG_40MHZ;
                      ^~~~~~~~~~~~~
    /home/nil/Downloads/rtlwifi_new/rtl8188ee/trx.c:447:22: note: each undeclared identifier is reported only once for each function it appears in /home/nil/Downloads/rtlwifi_new/rtl8188ee/trx.c:450:22: error: ‘RX_FLAG_HT’ undeclared (first use in this function); did you mean ‘RX_FLAG_40MHZ’?
       rx_status->flag |= RX_FLAG_HT;
                          ^~~~~~~~~~
                          RX_FLAG_40MHZ
    make[3]: *** [scripts/Makefile.build:303: /home/nil/Downloads/rtlwifi_new/rtl8188ee/trx.o] Error      
    make[2]: *** [scripts/Makefile.build:561: /home/nil/Downloads/rtlwifi_new/rtl8188ee] Error 2
    make[1]: *** [Makefile:1512: _module_/home/nil/Downloads/rtlwifi_new] Error 2
    make[1]: Leaving directory '/home/nil/build/linux-stable'
    make: *** [Makefile:58: all] Error 2

I've seen similar issues caused by not having the appropriate kernel headers. To be sure this wasn't the issue, I went overboard and installed headers for all architectures, so I doubt it's the problem.

The drivers compile perfectly on previous "stable" kernels. I've used many testing kernels in the past as well, and never encountered an issue with them either. Any ideas?

**Comment by snaunton** [comment]
Same issue too.

Kernal 4.12.0 on compiled with config from linux-image-4.9.0-3-amd64 on debian 9.0/stretch.

**Comment by Sacrifice** [comment]
Same problem too... cant compile without show errors. With `ubuntu server Xenial Xerus (16.04.2)`...

Also if is possible... add a `Read.me` file with basic instructions for install the driver.

**Comment by stephenl42** [comment]
yeah, a few fields were changed around recently. cannot seem to upload to github, so here is zip of repo with fix for v4.12: http://keno.landamore.com/rtlwifi_new_stephenl42.zip

if anyone cares then please feel free to push/merge/whatever

somewhat frustratingly, the whole ant_sel thing appears not to work in linux 4.12. i've no idea if/when that regressed (did it ever work properly in mainline?), as i've only previously used this out-of-tree driver against devuan jessie (relatively ancient kernel iirc)

s.

**Comment by Sacrifice** [comment]
Thank you @stephenl42 ilI will try with your zip if is better or not...

Concretly the issue is:
When compiling the driver it seems that it does not find a field itself. It does not stop the compilation and it continues until the end, after I finish compiling, I install the driver, I modify my `/etc/network/interfaces`, restart the server and I see that the interface is linked, but if I physically disconnect the lan interface I notice that I can not use the wifi. It's as if it's linked, but I do not navigate, nor can I do `sudo apt update` or anything like that across the wifi. If I observe the connection of devices on my router at the wifi level, I see the mac is connected to the wifi interface, so the SSID and password is correct.

**Comment by snaunton** [comment]
Thanks @stephenl42. Working well.

**Comment by Sacrifice** [comment]
Its possible to merge @lwfinger ?

**Comment by akhileshsarda** [comment]
This is how, i could  fix the issue. Follow the three steps:

step 1: sudo vim /usr/src/linux-headers-$(uname -r)/include/net/mac80211.h
(Note: taking backup of the file is recommended).

step 2 : comment this enum: "enum mac80211_rx_flags { }"

step 3 : Add the following instead:
enum mac80211_rx_flags {
        RX_FLAG_MMIC_ERROR              = BIT(0),
        RX_FLAG_DECRYPTED               = BIT(1),
        RX_FLAG_MACTIME_PLCP_START      = BIT(2),
        RX_FLAG_MMIC_STRIPPED           = BIT(3),
        RX_FLAG_IV_STRIPPED             = BIT(4),
        RX_FLAG_FAILED_FCS_CRC          = BIT(5),
        RX_FLAG_FAILED_PLCP_CRC         = BIT(6),
        RX_FLAG_MACTIME_START           = BIT(7),
        RX_FLAG_SHORTPRE                = BIT(8),
        RX_FLAG_HT                      = BIT(9),
        RX_FLAG_40MHZ                   = BIT(10),
        RX_FLAG_SHORT_GI                = BIT(11),
        RX_FLAG_NO_SIGNAL_VAL           = BIT(12),
        RX_FLAG_HT_GF                   = BIT(13),
        RX_FLAG_AMPDU_DETAILS           = BIT(14),
        RX_FLAG_PN_VALIDATED            = BIT(15),
        RX_FLAG_DUP_VALIDATED           = BIT(16),
        RX_FLAG_AMPDU_LAST_KNOWN        = BIT(17),
        RX_FLAG_AMPDU_IS_LAST           = BIT(18),
        RX_FLAG_AMPDU_DELIM_CRC_ERROR   = BIT(19),
        RX_FLAG_AMPDU_DELIM_CRC_KNOWN   = BIT(20),
        RX_FLAG_MACTIME_END             = BIT(21),
        RX_FLAG_VHT                     = BIT(22),
        RX_FLAG_LDPC                    = BIT(23),
        RX_FLAG_ONLY_MONITOR            = BIT(24),
        RX_FLAG_SKIP_MONITOR            = BIT(25),
        RX_FLAG_STBC_MASK               = BIT(26) | BIT(27),
        RX_FLAG_10MHZ                   = BIT(28),
        RX_FLAG_5MHZ                    = BIT(29),
        RX_FLAG_AMSDU_MORE              = BIT(30),
        RX_FLAG_RADIOTAP_VENDOR_DATA    = BIT(31),
        RX_FLAG_MIC_STRIPPED            = BIT_ULL(32),
        RX_FLAG_ALLOW_SAME_PN           = BIT_ULL(33),
};

**Comment by lwfinger** [comment]
I just generated a set of these modules using kernel 4.12.0 from mainline with no errors. Note that wifi.h has the following code:

#if (LINUX_VERSION_CODE >= KERNEL_VERSION(4, 12, 0))
#define RX_FLAG_40MHZ RATE_INFO_BW_40
#define RX_FLAG_HT RX_ENC_HT
#endif
Thus, RX_FLAG_40MHZ is defined for kernel 4.12.0 or newer.

I have no idea what is causing your problem. Please post the contents of include/generated/uapi/linux/version.h in your source tree.

**Comment by sailee18dalvi** [comment]
The main repo at https://github.com/rtlwifi-linux/rtlwifi-next did not compile. I used https://github.com/synthtc/rtlwifi-next which was one commit ahead and compiled.
Now Fedora recognizes the wireless device. We can also list the networks around us using lsmod.
Use the below commands to fix this issue:

$ git clone https://github.com/synthtc/rtlwifi-next
$ cd rtlwifi-next
$ make
$ sudo make install
$ sudo modprobe rtl8822be

**Comment by lwfinger** [comment]
I have no idea what https://github.com/rtlwifi-linux/rtlwifi-next is. Mine is .../lwfinger/rtlwifi-next.  If mine has the error, then you should tell me what it is so that I can fix it. Why is that important? Because my repo is the only one that I guarantee will get fixes from the kernel and Realtek.
