### ISSUE TITLE
no private ioctls for iwpriv command

### ISSUE THREAD

**Issue by madonwifi** [lwfinger/rtlwifi_new#249]
Hello lwfinger 
I want  to use iwpriv command. When I issued "iwpriv wlano"  command , it gave me a message saying "wlan0 no private ioctls "
Please suggest me a solution.

Chipset: RTL8723BE PCIe Wireless Network Adapter
OS: Ubuntu 16.04 LTS
Kernel: 4.4.0-31-generic

> $sudo modinfo rtl8723be
filename:       /lib/modules/4.4.0-31-generic/kernel/drivers/net/wireless/realtek/rtlwifi/rtl8723be/rtl8723be.ko
firmware:       rtlwifi/rtl8723befw_36.bin
firmware:       rtlwifi/rtl8723befw.bin
description:    Realtek 8723BE 802.11n PCI wireless
license:        GPL
author:         Realtek WlanFAE	<wlanfae@realtek.com>
author:         PageHe	<page_he@realsil.com.cn>
srcversion:     2C82AEBD843DD8F2598579A
alias:          pci:v000010ECd0000B723sv*sd*bc*sc*i*
depends:        rtlwifi,rtl8723-common,rtl_pci,btcoexist,mac80211
vermagic:       4.4.0-31-generic SMP mod_unload modversions 
parm:           swenc:Set to 1 for software crypto (default 0)
 (bool)
parm:           ips:Set to 0 to not use link power save (default 1)
 (bool)
parm:           swlps:Set to 1 to use SW control power save (default 0)
 (bool)
parm:           fwlps:Set to 1 to use FW control power save (default 1)
 (bool)
parm:           msi:Set to 1 to use MSI interrupts mode (default 0)
 (bool)
parm:           debug:Set debug level (0-5) (default 0) (int)
parm:           disable_watchdog:Set to 1 to disable the watchdog (default 0)
 (bool)
parm:           ant_sel:Set to 1 or 2 to force antenna number (default 0)
 (int)

**Comment by lwfinger** [comment]
Use utility iw, which is the modern equivalent of iwpriv, iwlist, iwconfig, etc.

**Comment by madonwifi** [comment]
As part of testing I want to set STA in b only/gonly/nonly/bgn modes. Using iwpriv it can be achieved by  
$iwpriv wlan0 bandcfg<value>
Can you suggest its equivalent for iw or a link/resource maybe?

**Comment by lwfinger** [comment]
Your request is unusual. I asked about ways to set a specific band using iw. It is not possible. In iwlwifi, there is a module parameter. We could possibly take that route with rtlwifi; however, we already have too many such parameters, and I would be reluctant to add more.

One user has created a set of patches that implement this type of action at https://github.com/greearb; however, his comment is "I have some patches for wpa_supplicant and the wifi stack (and ath10k) that lets this work, but it is fairly invasive, somewhat tricky to configure the supplicant properly, and the kernel related patches were rejected some time back, so it will only live in my trees for the foreseeable future."

The simplest way would be to set up an extra AP that could be switched to B or G mode as needed. Certainly an AP running in N mode is likely your default case. On E-Bay, there are a number of Linksys WRT54G or WRT54GL devices for $20 or less that would meet your need.
