### ISSUE TITLE
there is some error in make file

### ISSUE THREAD

**Issue by itzpranav** [lwfinger/rtlwifi_new#251]
there is some error in make file..  

make -C /lib/modules/4.9.0-kali4-amd64/build M=/home/xxxxxx/Downloads/rtlwifi_new-rock.new_btcoex (1)/rtlwifi_new-rock.new_btcoex modules
/bin/sh: 1: Syntax error: "(" unexpected
Makefile:57: recipe for target 'all' failed.

seems like some one edited the make file. which was working earlier.

**Comment by lwfinger** [comment]
My copy has not been changed since April 26. Is the damage self-inflicted?

My last change is commit 71c7a51b2366 ("rtlwifi_new: Add country_code 0x26 for Belgium").

You should also check "git diff".
