### ISSUE TITLE
Add rtl8812au repository?

### ISSUE THREAD

**Issue by MilhouseVH** [lwfinger/rtlwifi_new#255]
First of all apologies for contacting you this way - not sure how else to do it!

Would you be interested in adding one of the _many_ rtl8812au repositories to your list of supported repositories (if not in this repo, then as a separate stand-alone repo)?

This particular driver has several repositories on github, eg.

https://github.com/astsam/rtl8812au (v5.1.5)
https://github.com/paspro/rtl8812au  (v5.1.5)
https://github.com/Grawp/rtl8812au_rtl8821au  (v4.3.20)

and there are many more, but often with even older drivers.

The problem is that the owners of most of these repos have either given up supporting their repo, or only update their repo once in a while. And since many recent changes have been due to kernel build failures, that often has fixes in unmerged pull requests, this makes using these stale repositories very frustrating.

If you have the time it would be great if you could fork one of these repos as you seem to be taking good care of your repositories.

I guess if I were to choose, the astsam repo would be the most suitable (then bringing the 5.1.5 branch up to date with latest kernel fixes, some of which have been PRd or could be quite quickly from myself and others).

I'm pretty sure there are a number of other github users that would willingly help out ensuring this repo is kept up to date - the problem is finding a repo owner that cares!

Many thanks
Milhouse
(Direct email: milhouse at kodi dot tv)

**Comment by lwfinger** [comment]
I'm sorry, but I will not be adding any new repos for Realtek hardware. I am very frustrated about having to answer the same questions over and over and over. I do not need any more of this aggravation.

**Comment by MilhouseVH** [comment]
Totally understood @lwfinger, totally understood. Many thanks for what you are able to do, it is appreciated.
