### ISSUE TITLE
Compile error on Arch Linux 4.11.9-1 ARCH

### ISSUE THREAD

**Issue by juicetin** [lwfinger/rtlwifi_new#256]
When running `make` in the project's root directory, it produces the following error:

make -C /lib/modules/4.11.9-1-ARCH/build M=/home/me/programs/rtlwifi-next modules 
make[1]: Entering directory /usr/lib/modules/4.11.9-1-ARCH/build 
make[1]: *** No rule to make target 'modules'. Stop. 
make[1]: Leaving directory '/usr/lib/modules/4.11.9-1-ARCH/build 
make: *** [Makefile:100: all] Error 2

If it helps, the only file in my /usr/lib/modules/4.11.9-1-ARCH/build folder is vmlinux. The /usr/lib/modules/4.11.9-1-ARCH/ directory itself has files such as modules.alias, modules.alias.bin, and many others, while the kernel folder in this directory has a directory with the full path /usr/lib/modules/4.11.9-1-ARCH/kernel/drivers/net/wireless/realtek/rtlwifi - this seems like it may be more relevant. Each rtlxxxxx folder in this directory has a ko.gz file. I tried substituting in some possibly related in directories into the KSRC variable, but with the same error related to no rule to make target modules each time.

Are there further steps I could take to debug why this issue is occurring?

**Comment by lwfinger** [comment]
You have not installed the kernel headers. That ..../build entry should be a link to a directory that contains a directory named include. As I am not an Arch user, I cannot tell you which packages are needed, but I am sure there are a lot of such instructions on the web. Search for "Arch external kernel modules".

All of those *.ko.gz files are the standard modules, which for kernel 4.11.9 are essentially the same as those on this repo. In fact, what are you hoping to accomplish by using this out-of-kernel set of drivers?

**Comment by juicetin** [comment]
Hi lwfinger,

Thanks for the feedback, rookie mistake on my end.

I actually originally logged this issue here (https://github.com/rtlwifi-linux/rtlwifi-next/issues/4) but noticed that this repo has the same/a functionally similar Makefile and is the more recently active one.

I was actually after the RTL8822BE driver which isn't currently in the official Arch Linux repo, but in the rtlwifi-next one linked above. I'll close this issue that's otherwise unrelated to this repo itself.

**Comment by juicetin** [comment]
Brief follow up in case anyone runs into the same mistake I did:

For arch, `linux-headers` needs to be installed via `sudo pacman -S linux-headers` or similar. I took for granted my setup scripts had set them up and it totally did not occur to me that this was the cause of the error.
