### ISSUE TITLE
Latest commit a24cb56 21 hours ago 

### ISSUE THREAD

**Issue by ghost** [lwfinger/rtlwifi_new#257]
Thank you lwfinger!
with the last commit the dkms-rtlwifi package-building and installing works exactly.
Please excuse me for the mail, now i have github-free, and will post next issues on this right way.

**Comment by ohquait** [comment]
Thank you !
Today i build rpm's from your latest git rtlwifi_new and rtlwifi_new///extended on kernel 4.15.6-pclos1.
Installation of dkms-rtlwifi, then update to dkms-rtlwifi-extended, then downgrade back to rtlwifi...
all works exactly and clean, just i can't test the drivers self, i will provide the srpm and rpm's to testing on
the forum - developer/packager-sections on pclinuxos.com so peoples there can test it.
If you would see complete outpout's while installation from terminal, they are on https://www.qua-it.org 
under "SOURCES" in few minutes...
Thank YOU!
