### ISSUE TITLE
"This branch is abandoned. Please do not use" when compiling

### ISSUE THREAD

**Issue by juanefren** [lwfinger/rtlwifi_new#258]
Hi, when I try to compile using make I get this message:

juan@juan-HP-Laptop-15-bw0xx:~/rtlwifi_new$ make
make -C /lib/modules/4.10.0-27-generic/build M=/home/juan/rtlwifi_new modules
make[1]: Entering directory '/usr/src/linux-headers-4.10.0-27-generic'
  CC [M]  /home/juan/rtlwifi_new/base.o
In file included from /home/juan/rtlwifi_new/base.c:26:0:
/home/juan/rtlwifi_new/wifi.h:43:2: error: #error "This branch is abandoned. Please do not use"
 #error "This branch is abandoned. Please do not use"
  ^
scripts/Makefile.build:294: recipe for target '/home/juan/rtlwifi_new/base.o' failed
make[2]: *** [/home/juan/rtlwifi_new/base.o] Error 1
Makefile:1524: recipe for target '_module_/home/juan/rtlwifi_new' failed
make[1]: *** [_module_/home/juan/rtlwifi_new] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.10.0-27-generic'
Makefile:57: recipe for target 'all' failed
make: *** [all] Error 2

Any ideas about this?
lsusb shows this for my wifi card:
Bus 001 Device 004: ID 0bda:b008 Realtek Semiconductor Corp.

**Comment by juanefren** [comment]
Forgot to specify I am using Lubuntu 16.04.

**Comment by juanefren** [comment]
Sorry I was using incorrect branch.

**Comment by vishal-g** [comment]
How could you resolve it? I am facing the same issue.

**Comment by lwfinger** [comment]
Switch to either the master branch, or use a 4.12 kernel. Those old branches of this repo are no longer supported. Of course, you can always remove the #error line from wifi.h, but if you do that, you will be on your own with no support from me.

**Comment by vishal-g** [comment]
Thanks for prompt reply. Deleted #error line from wifi.h, and it worked for me! :+1:

**Comment by nicholashq** [comment]
Hi. I'm having the same issue. How did you fix it

**Comment by lwfinger** [comment]
Read the previous comment CAREFULLY!!!!!!!

**Comment by KaloyanGrancharov** [comment]
@vishal-g to switch to the master branch means that you need to go here: https://github.com/lwfinger/rtlwifi_new and to download the driver files as .zip, or to download them directly by clicking this link: https://github.com/lwfinger/rtlwifi_new/archive/master.zip
Then extract the fiels and compile them in the same way as before. For me the master branch works fine.
In this way you do not need to delete anything in the file "wifi.h".

**Comment by lwfinger** [comment]
I recommend that you do not use the zip files, rather use "git clone http://github.com/lwfinger/rtlwifi_new.git". Why? If you use the zip version, then if a single character in the entire sources is changed, you need to download everything again. The other way, a simple "git pull" gets the changes in a very compact manner. There are many other benefits to git, but the ease of updating is the most important for users.
