### ISSUE TITLE
Build instructions for this repo

### ISSUE THREAD

**Issue by sreyan32** [lwfinger/rtlwifi_new#260]
I am facing some compilation problems while building this driver. How do you use the firmware folder in the repo ?

Do you copy it to /lib/firmware ? 

Can an example of a sample build procedure be shared?

**Comment by stephenl42** [comment]
0. make sure you have headers installed for the kernel you are running. these normally live in /lib/modules/*/build. if you compiled your own kernel they should have been put there when you did the make install. or refer to support for whatever distribution you are using (probably something along the lines of "apt-get install linux-headers-`uname -r`")

1. clone repo / download and unzip

2. in that directory: make

3. as root: make install
(this last step will copy the firmware files)
