### ISSUE TITLE
No scan results error (RTL8723AE on MSI laptop)

### ISSUE THREAD

**Issue by AA1978** [lwfinger/rtlwifi_new#262]
Dear lwfinger,
 I have installed latest version of the driver (master branch) and the system couldn't find any wireless networks.

aa@MSI:~$ iwlist scan
wlp1s0    No scan results

Can you help me? The system is Ubuntu with 4.10.0-28 kernel.

**Comment by lwfinger** [comment]
As you provide almost no information about your problem, I can provide about the same amount of help.

**Comment by AA1978** [comment]
Please tell, what kind of information should I provide.
