### ISSUE TITLE
Realtek RTL8723DE

### ISSUE THREAD

**Issue by IlyaBizyaev** [lwfinger/rtlwifi_new#265]
Hello! :D I have a problem with Wi-Fi not working on my laptop under Linux. 

As Windows sees it:
![default](https://user-images.githubusercontent.com/11175213/29361325-23c289fa-8298-11e7-942d-977fa94c43a7.png)

As Linux 4.4 (latest openSUSE Leap) does:
![spectacle sa5221](https://user-images.githubusercontent.com/11175213/29361383-7b5e7cd2-8298-11e7-826e-e1abbba74748.png)

I tried installing drivers from the master branch of this repository, but they don't get used automatically on boot and don't have any effect when inserted manually with `modprobe`.

How can I fix the issue?

**Comment by lwfinger** [comment]
AS far as I know, a driver for this device does not exist for Linux yet, there is nothing you can do. BTW, 'lspci -nn' is a lot more useful than 'lspci' as it shows the vendor and device PCI codes, which are the critical pieces of info used to decide which driver to load. I would expect your device to show 10ec:d723 as its codes.

**Comment by IlyaBizyaev** [comment]
Yeah, exactly. Is that a new device? And can I expect the drivers in the future?

**Comment by lwfinger** [comment]
Yes. Yes.

**Comment by IlyaBizyaev** [comment]
Thank you! :D

**Comment by vlukovni** [comment]
Hello. What about this driver? I cannot find this driver for your repo.

**Comment by lwfinger** [comment]
Have you read thiis thread?? It says everything!!!!!!!!!!

**Comment by 160300140** [comment]
fuuuuuck, i need the driver

**Comment by lwfinger** [comment]
You an idiot. Use git to clone this repo and switch to the "extended" branch. You will then have the driver. Now fuck off!!
