### ISSUE TITLE
rtl8723de

### ISSUE THREAD

**Issue by abhishekd08** [lwfinger/rtlwifi_new#267]
hello, there is no driver for RTL8723DE, WiFi card not working on Ubuntu 16.04 LTS , can anyone help ?

**Comment by lwfinger** [comment]
At this time, no. Realtek is working on a driver that needs some code that is currently awaiting inclusion in the kernel. I have no idea how long it will be. In the meantime, you will need to use a USB stick.

**Comment by abhishekd08** [comment]
Thanks for the information. Although it is a disappointment but at least I got a solid answer. I'll wait for the driver to come.

**Comment by mixailshaulsky** [comment]
still no good news... :-(

**Comment by lwfinger** [comment]
No news at all.

**Comment by mohdomama** [comment]
I have the same issue. I tried using ndiswrapper to install windows driver in ubuntu. But it dosent work. I even updated to kernel 4.10.0-35-generic hoping it might have  support for rtl8723de but it dosen't :(

**Comment by shwetaahuja123** [comment]
+1 waiting list

**Comment by anshulgoyal15** [comment]
Lw fingure said that it will be available by the end of this year

**Comment by AvirahJ** [comment]
Thanks to Larry for all the good work. Hope the driver support module will be available for RealTek RTL8723DE before the end of this year. Meanwhile, I'm going to try Ndiswrapper or any other options working.

**Comment by BumbleBrice** [comment]
waiting list !

**Comment by lwfinger** [comment]
I already said that it will be available by the end of the year. Nagging me only gets me pissed off!!

**Comment by jcatala** [comment]
on waiting list, hp 250 with no wlan at all :D
thanks for everything, bless!

**Comment by vlukovni** [comment]
waiting to for hp 17-ak025ur

**Comment by lwfinger** [comment]
And you will have to continue to wait. Realtek has not yet released a driver for this device yet.

**Comment by adityakmr** [comment]
when will be driver available for rtl8723DE.how much more time will it take

**Comment by djhayes1994** [comment]
@adityakmr Realtek has still not released a driver and it is coming Q4 of this year. Just be patient.

Bothering @lwfinger  will not make it come faster, if you'd like to expedite it your best way to do that would be to annoy the manufacturer not somebody trying to help the community in their spare time.

**Comment by lwfinger** [comment]
Amen.

**Comment by samuels410** [comment]
Waiting list

**Comment by srpatcha** [comment]
by when it is getting released...on Q4

**Comment by fmoralesc** [comment]
@srpatcha Check this https://github.com/lwfinger/rtlwifi_new/issues/298#issuecomment-353261978

It seems to work fine. Bluetooth support seems to be a work in progress still, though.

**Comment by carbodb** [comment]
@abhishekd08 
Follow this  [https://github.com/lwfinger/rtlwifi_new/issues/270](url)

**Comment by BIGDROP** [comment]
Add me to waiting list...

**Comment by lwfinger** [comment]
What are you waiting for? The driver has been in the extended branch of this repo for nearly a month. If you are waiting for a BT driver, that is beyond my control.

**Comment by BIGDROP** [comment]
That's ok. And thankyou for your very awesome job. 

PS. Are you planning to mainline this driver to kernel.org

**Comment by lwfinger** [comment]
I'm not as this is Realtek's driver. They are working on that step.

**Comment by BIGDROP** [comment]
Are you aware of how much time it would take for the same? Because it seems driver is ready since at least a month, would it get in 4.17 cycle??

**Comment by lwfinger** [comment]
No. Publishing a driver on GitHub requires nothing more than posting the code. Getting that same code into the kernel requires passing very critical reviews. Realtek is still converting the rtl8822be driver from staging into mainline. 

Everything new for 4.17 is already in Linux-next, and rtl8723de is not in that category. I would not expect it in mainline until 4.20, or 5.0, whichever Linus decides to call it. This slow pace of development is the price of having stability in the kernel. Implement dkms, and the drivers will be automatically rebuilt for each new kernel.
