### ISSUE TITLE
rtl8192ce - every 10 seconds: "kernel: rtlwifi: AP off, try to reconnect now"  and "kernel: wlp2s0: associated"

### ISSUE THREAD

**Issue by thx1111** [lwfinger/rtlwifi_new#268]
- enslaving the wired and wireless interfaces to the bond interface, with the bond interface enslaved to the bridge interface,
- then disconnecting and then reconnecting the ethernet cable,

the network connection seems to work perfectly well, moving between the wired and wireless interfaces, but subsequently, when the wired interface is active, and the wireless interface is inactive, in the log file, and in dmesg, every 10 seconds, there is a repeating warning:

rtlwifi: AP off, try to reconnect now

The interface works, but the warnings and disconnects are annoying.

This warning does not occur when bonding is first started with the wired interface active, but only after cycling - moving from the wired interface to the wireless interface, and then back to the wired interface.

This warning does not occur when the wireless interface is active.

Also, the warning does not occur when the wireless interface is associated to the AP, but not enslaved to the bonding interface.

Also, this warning does not occur when the wired and wireless interfaces are enslaved to the bond interface, but the bond interface is not enslaved to the bridge interface.

Also, this warning does not occur when the wired and wireless interfaces are simply enslaved to the bridge interface.

This warning only seems to occur when the wired and wireless interfaces are enslaved to the bond interface, and the bond interface is itself enslaved to the bridge interface.

This warning occurs with both the stock rtl8192ce driver and with the rtlwifi_new driver.

This warning occurs with both Arch Linux kenels, linux 4.11.9-1 and linux 4.12.8-2, so it seems to have nothing to do with any changes in kernel 4.12.  This warning also occurs with    linux-lts 4.9.44-1 and the stock driver.

However, I do not remember ever seeing this warning with the rtlwifi_new rtl8192ce driver from earlier this year, so I'm confused.  The linux-lts 4.9.44-1 stock driver does not emit the "AP off, try to reconnect now" warning, but the wireless interface still disconnects every 10 seconds, which is why I started using the rtlwifi_new driver in the first place, to eliminate these repeating disconnects.

Maybe something changed in the rtlwifi_new driver?  My sense is that there is a regression, but I have not proven that.

Regardless, could the problem have something to do with the way the bonding module communicates with the bridge module?

The warning is from base.c:

                        /* if we can't recv beacon for 10s,
                         * we should reconnect this AP
                         */
                        if (rtlpriv->link_info.roam_times >= 5) {
                                pr_err("AP off, try to reconnect now\n");
                                rtlpriv->link_info.roam_times = 0;
                                ieee80211_connection_loss(
                                        rtlpriv->mac80211.vif);
                        }

It would seem that, with the wireless interface enslaved to the bond interface, and the bond interface enslaved to the bridge interface, and after the bonding interface moves from the wired interface to the wireless interface, that the reported "roam_times" is wrong, where it appears that the wireless interface is actually still associated and communicating with the AP.

But the beacon goes straight to the wireless radio, and does not pass through the bonding interface or the bridge interface.  So why would the reported "roam_times" be dependent upon how the wireless interface is enslaved?  There must be some more general problem with "rtlpriv", yes?

The cycle in the log file has this after reconnecting the wired interface:

 kernel: atl1c 0000:03:00.0: atl1c: enp3s0 NIC Link is Up<100 Mbps Full Duplex>
 kernel: bond0: link status definitely up for interface enp3s0, 100 Mbps full duplex
 kernel: bond0: making interface enp3s0 the new active one
 lapis kernel: device wlp2s0 left promiscuous mode
 lapis kernel: device enp3s0 entered promiscuous mode

but, 10 seconds later:

 kernel: rtlwifi: AP off, try to reconnect now 
 kernel: wlp2s0: Connection to AP 48:f8:b3:xx:xx:xx lost
 kernel: bond0: link status definitely down for interface wlp2s0, disabling it 
 sh[3624]: wlp2s0: CTRL-EVENT-DISCONNECTED bssid=48:f8:b3:xx:xx:xx reason=4 locally_generated=1
 sh[3624]: wlp2s0: CTRL-EVENT-REGDOM-CHANGE init=CORE type=WORLD 
 sh[3624]: wlp2s0: CTRL-EVENT-REGDOM-CHANGE init=USER type=COUNTRY alpha2=US
 kernel: wlp2s0: authenticate with 48:f8:b3:xx:xx:xx
 sh[3624]: wlp2s0: SME: Trying to authenticate with 48:f8:b3:xx:xx:xx (SSID='homewifi' freq=2437 MHz)
 kernel: wlp2s0: send auth to 48:f8:b3:xx:xx:xx (try 1/3)
 kernel: wlp2s0: authenticated
 sh[3624]: wlp2s0: Trying to associate with 48:f8:b3:xx:xx:xx (SSID='homewifi' freq=2437 MHz)
 kernel: wlp2s0: associate with 48:f8:b3:xx:xx:xx (try 1/3)
 sh[3624]: wlp2s0: Associated with 48:f8:b3:xx:xx:xx
 kernel: wlp2s0: RX AssocResp from 48:f8:b3:xx:xx:xx (capab=0x431 status=0 aid=1)
 kernel: wlp2s0: associated
 sh[3624]: wlp2s0: CTRL-EVENT-SUBNET-STATUS-UPDATE status=0
 sh[3624]: wlp2s0: CTRL-EVENT-REGDOM-CHANGE init=COUNTRY_IE type=COUNTRY alpha2=US
 kernel: bond0: link status definitely up for interface wlp2s0, 0 Mbps full duplex
 sh[3624]: wlp2s0: WPA: Key negotiation completed with 48:f8:b3:xx:xx:xx [PTK=CCMP GTK=CCMP]
 sh[3624]: wlp2s0: CTRL-EVENT-CONNECTED - Connection to 48:f8:b3:xx:xx:xx completed [id=0 id_str=]
 sh[3624]: wlp2s0: WPA: EAPOL-Key Replay Counter did not increase - dropping packet

And then it repeats:

 kernel: rtlwifi: AP off, try to reconnect now 
 kernel: wlp2s0: Connection to AP 48:f8:b3:xx:xx:xx lost
 ...

**Comment by thx1111** [comment]
It occurs to me that, if the value "rtlpriv->link_info.roam_times" becomes corrupted, somehow, as a result of the bonding module moving the active interface, from wired to wireless and back to wired, and that value is not actually reset with ",rtlpriv->link_info.roam_times = 0", and always has some other value, then the function will simply act as a 10 second timer, breaking down the connection repeatedly, which then is automatically rebuilt.

Maybe the reference to rtlpriv or link_info gets trashed somewhere - so there are two different versions of "rtlpriv->link_info.roam_times", say - when the wireless interface is enslaved and then moved from active to inactive, or when the enslaved active interface is moved from wireless to wired?  Could the function repeatedly be entered with a reference to the  wrong "rtlpriv->link_info"?  Can there exist more than one "rtlpriv->link_info" when bonding and bridging are used together, or when the wireless interface is enslaved along with a wired interface?

**Comment by thx1111** [comment]
This is still an issue in Arch, linux 4.13.1-1.  Just saying...  I haven't had time to work on it more yet.

**Comment by eisterman** [comment]
Issue still present

**Comment by thx1111** [comment]
I have discovered another way to set this off, this repeating "kernel: rtlwifi: AP off, try to reconnect now" cycle, which is to release an Access Point associated wireless slave from a bridge master.

A more conventional network configuration, will have the IP addresses on the bond interface, rather than on the bridge interface, assuming that there is a hierarchy of bridge and bond interfaces, because, with the wireless interface "always connected", plugging-in a wired interface  to that same subnet - in the above example, connecting a second wired interface from the top-level bridge - could leave the bridge interface with two connections to the subnet, and a bridge loop.

Instead, suppose that the wireless interface is enslaved to one bridge interface, and that the wired interface is enslaved to a different bridge interface, and that these two bridge interfaces are enslaved to a "top-level" bond interface, which is given IP addresses.  Now, incidentally, when the wireless interface is enslaved to a bridge interface, "wpa_supplicant" must be run with the "-b bridgeN" option, or otherwise wpa_supplicant will itself repeatedly re-associate with the AP.

In this configuration, with the physical network interfaces enslaved to the bridge interfaces, and the bridges enslaved to the bond interface, there is no problem with the rtlwifi driver when disconnecting and reconnecting the wired interface.  There is no "AP off, try to reconnect now" cycling, and every thing works fine.  However, if the wireless interface is then un-enslaved from its bridge interface, as with "ip link set wlp2s0 nomaster", then again there is the 10 second " rtlwifi: AP off, try to reconnect now" cycling.  And the cycling stops, if the wireless interface is again enslaved to the bridge interface.  It makes no difference if the wired interface is connected or not.

So now, here are two different configurations which can trigger this reconnect cycling, though the first example is not a typical configuration, and this second example is contrived.  These examples may provide some additional insight into this cycling mechanism.  Perhaps, with the wireless->bond->bridge configuration, the wireless interface finds itself "disconnected" from the bridge interface, in some sense, after the bridged second wired interface is disconnected and then reconnected.  I'm still dabbling...

Obviously, though, wrtlwifi again finds `rtlpriv->link_info.roam_times >= 5`, which implies that `rtlpriv->link_info.bcn_rx_inperiod + rtlpriv->link_info.num_rx_inperiod) == 0`, and that `bcn_rx_inperiod` and `num_rx_inperiod` are not being incremented.  It is not immediately obvious why this would have anything to do with whether or not the wireless interface had been enslaved, or with which slave might be, or might have been, "active".

$ grep -s '_rx_inperiod++' * */*
base.c: rtlpriv->link_info.bcn_rx_inperiod++;
pci.c:                                  rtlpriv->link_info.num_rx_inperiod++;
usb.c:                          rtlpriv->link_info.num_rx_inperiod++;
usb.c:                          rtlpriv->link_info.num_rx_inperiod++;

On my machine, the wireless interface is on a pci bus, and the wired interface is on a usb bus.  Maybe that makes a difference.  The function that increments `bcn_rx_inperiod` says "this function is used for roaming", which I presume means *not* when the wireless interface is associated, and then `bcn_rx_inperiod` is going to be zero anyway.  So maybe need to follow code in pci.c.

Hmm - I am noticing also that taking the wireless interface down, and then up, ends the reconnect cycling.

Hmm - I notice that enslaving to the bond interface, and then releasing the slave from the bond interface, the released wireless interface is always automatically set "down".  With the bridge interface, releasing the slave from the bridge interface, the wireless interface is *not* automatically set "down".  Of course, terminating wpa_supplicant will also end the reconnect cycling.

Anyway, "thinking out loud" here...

**Comment by lwindolf** [comment]
Experiencing the same on Ubuntu 17.10 kernel 4.13.0-16-generic and rtl8723be
Example dmesg

    [ 1039.338133] rtlwifi: AP off, try to reconnect now
    [ 1039.338156] wlp1s0: Connection to AP 34:31:c4:e7:07:cc lost
    [ 1040.441786] wlp1s0: authenticate with 34:31:c4:e7:07:cc
    [ 1040.464636] wlp1s0: send auth to 34:31:c4:e7:07:cc (try 1/3)
    [ 1040.469907] wlp1s0: authenticated
    [ 1040.473176] wlp1s0: associate with 34:31:c4:e7:07:cc (try 1/3)
    [ 1040.484926] wlp1s0: RX AssocResp from 34:31:c4:e7:07:cc (capab=0x431 status=0 aid=3)
    [ 1040.486504] wlp1s0: associated
    [ 1049.418753] rtlwifi: AP off, try to reconnect now
    [ 1049.418807] wlp1s0: Connection to AP 34:31:c4:e7:07:cc lost
    [ 1050.521829] wlp1s0: authenticate with 34:31:c4:e7:07:cc
    [ 1050.544053] wlp1s0: send auth to 34:31:c4:e7:07:cc (try 1/3)
    [ 1050.551802] wlp1s0: authenticated
    [ 1050.553010] wlp1s0: associate with 34:31:c4:e7:07:cc (try 1/3)
    [ 1050.656973] wlp1s0: associate with 34:31:c4:e7:07:cc (try 2/3)
    [ 1050.665576] wlp1s0: RX AssocResp from 34:31:c4:e7:07:cc (capab=0x431 status=0 aid=3)

Make rtlfwifi unusable for me :-(

**Comment by thx1111** [comment]
@lwindolf, what is the structure of your IP network layer?  Do you have just an IP address on your wireless interface?  Or, are you enslaving the wireless interface?  Do the "AP off ..." errors continue if you bring the wireless interface "down" and then "up" again, "sudo ip link set wlxxxx down/up"?

These "AP off ..." errors are triggered when the wireless driver cannot recognize beacon frames.  I am still investigating *why* the driver sometimes fails to recognize these beacon frames.

**Comment by Harrison97** [comment]
Has anyone found a solution? Currently getting the same feedback with rtl8192se on 4.14.9-1-ARCH

**Comment by thx1111** [comment]
@Harrison97 

Hey - so, I've tracked down part of the problem to what looks to me like two bugs.

In one part of the code, which "listens" for wireless packets, the variable for packet counts is cleared before it is checked.  Of course, then, the value is always "zero wireless packets", the test fails, and the "reconnect" is initiated every ten seconds.  Fixing that bug alone would eliminate the problem, but it would also "hide" a second bug.

The second part of the problem is in the code that counts beacon packets.  In some circumstance - which I have not yet isolated - the packet header for beacon packets is returned with the IEEE80211_STYPE_BEACON" flag not set.  I need some help tracking that down, but I have not yet followed-up.

For now, I worked-around my problem by reconfiguring the bond and bridge interfaces, which seems to avoid the beacon flag not set issue.

If you are seeing these ten second reconnects, and you are absolutely sure that these are "false", and not caused by some other configuration error, then you could describe here your interface configuration in detail, and maybe we can suggest an alternative configuration, as a work-around.

**Comment by finnoleary** [comment]
I too am getting the same problem, with driver rtl8723be, under 4.14.19-1-lts.

**Comment by lwfinger** [comment]
Are you using this repo? If so, what branch?

**Comment by finnoleary** [comment]
I'm using this repo, on branch master.

**Comment by mbacilieri** [comment]
I'm affected too, I noticed the issue involves all kernel >= 4.13.
A workaround is to reset the wifi architecture after the boot. Just place this in /etc/rc.local, before exit0:

service network-manager stop
modprobe -r rtl8723be
modprobe -r rtl8723_common rtl_pci
modprobe -r rtlwifi
killall -9 wpa_supplicant
modprobe rtlwifi
modprobe rtl_pci rtl8723_common
modprobe rtl8723be
service network-manager start

To me this solve every problem, after this the wifi works flawlessy. It's not elegant but works.

**Comment by finnoleary** [comment]
Since cleaning (commenting out) my options file and updating the driver I no longer experience this error. Commenting out your options (esp. `*wlps=N`) if you have any might be worth a try for you.

Sidenote:
> `killall -9 wpa_supplicant`

Please, please, please do not advise people to use `killall -9`. You should use `killall -15`, if that fails then step down to `killall -2` and `killall -1`.

[r/linux: Don't use kill -9](https://www.reddit.com/r/linux/comments/1xvr25/linux_tip_dont_use_kill_9/)

["Why should I not use 'kill -9' / SIGKILL" - SuperUser](https://unix.stackexchange.com/a/281440)

**Comment by maxkremer** [comment]
Have the same issue with rtl8822be

**Comment by rigred** [comment]
Affirmative @maxkremer 
Still present even in `r8822be` on Kernel 5.0.7 Arch Linux.

**Comment by Clovel** [comment]
Hi ! I also have this issue with Kubuntu 19.04, using the `5.0.0-36-generic` kernel. 

Using `dmesg`, I found this, which resembles the logs some of you posted earlier in this thread : 
```
...
[97162.439155] wlp2s0: associated
[97171.100303] rtlwifi: AP off, try to reconnect now
[97171.100346] wlp2s0: Connection to AP a4:3e:51:ba:75:d6 lost
[97178.964611] wlp2s0: authenticate with a4:3e:51:ba:75:d6
[97178.997087] wlp2s0: send auth to a4:3e:51:ba:75:d6 (try 1/3)
[97179.100097] wlp2s0: send auth to a4:3e:51:ba:75:d6 (try 2/3)
[97179.101731] wlp2s0: authenticated
[97179.104111] wlp2s0: associate with a4:3e:51:ba:75:d6 (try 1/3)
[97179.117700] wlp2s0: RX AssocResp from a4:3e:51:ba:75:d6 (capab=0x411 status=0 aid=2)
[97179.123382] wlp2s0: associated
[97190.236350] rtlwifi: AP off, try to reconnect now
[97190.236390] wlp2s0: Connection to AP a4:3e:51:ba:75:d6 lost
[97191.480847] wlp2s0: authenticate with a4:3e:51:ba:75:d6
[97191.513153] wlp2s0: send auth to a4:3e:51:ba:75:d6 (try 1/3)
[97191.517239] wlp2s0: authenticated
[97191.520090] wlp2s0: associate with a4:3e:51:ba:75:d6 (try 1/3)
[97191.529557] wlp2s0: RX AssocResp from a4:3e:51:ba:75:d6 (capab=0x411 status=0 aid=2)
[97191.535185] wlp2s0: associated
[97200.320241] rtlwifi: AP off, try to reconnect now
...
```

I am not very familiar with this repository nor it's code. All I can give you is the list of modules loaded related to this issue : 
```
$ lsmod | grep rtl

rtl8192ee             110592  0
btcoexist             151552  1 rtl8192ee
rtl_pci                28672  1 rtl8192ee
rtlwifi                90112  3 rtl_pci,btcoexist,rtl8192ee
mac80211              819200  3 rtl_pci,rtlwifi,rtl8192ee
cfg80211              688128  2 rtlwifi,mac80211
```

If I can help with more information or with a fix, I would be happy to. I am just not sure I my distro uses the code from this repository (My guess is that it does.). BTW, how could I check that ? 

Many thanks.

**Comment by lwfinger** [comment]
Your distro does NOT use code from this repository. None do. You are using drivers from the kernel. For those drivers, you should report a bug to linux-wireless@vger.kernel.org.

It is strange that you should have this problem as I have recently been testing the kernel driver rtl8192ee, and I did not see the problem. I suspect something with your particular AP. You need to report as much as you can about the AP if you post to the mailing list cited above.

By the way, you have an RTL8192EE, not an RTL8192CE.
