### ISSUE TITLE
rtl8192ee report error 'init MAC failed' while bringing up the wireless interface

### ISSUE THREAD

**Issue by t57root** [lwfinger/rtlwifi_new#269]
I'm using rtlwifi_new on a thinkpad x240 laptop with 4.12.8-2-ARCH kernel.
When I executing `ip link set WIRELESS_IFACE up`, this error shows up.
The rtlwifi_new is the lasted version. 

Thanks

**Comment by lwfinger** [comment]
I cannot debug this based on this little information.

Do you have the firmware installed?

Please post at least the relevant section of the output of the dmesg command.

**Comment by t57root** [comment]
dmesg shows nothing but a single line shows `rtl8192ee: init MAC failed`.
I install rtlwifi_new using `make && make install`.

**Comment by lwfinger** [comment]
That is absolute BULL****. There is a lot more stuff in dmesg, but if you are unwilling to share, I cannot help.

**Comment by t57root** [comment]
That's a misunderstanding. I thought you mean the dmesg output when this error pops up. There's no reason for me not to share the dmesg log. `dmesg|grep rtl8192` shows:

rtl8192ee: Using firmware rtlwifi/rtl8192eefw.bin
rtl8192ee: 0000:03:00.0 wlp3s0: renamed from wlan0
rtl8192ee: init MAC failed

not sure if this helps, thanks

**Comment by lwfinger** [comment]
I installed the driver rtl8192ee from this repo, and all is OK. My base kernel is 4.13-rc4 from wireless-drivers-next. Perhaps you have a hardware problem.

**Comment by t57root** [comment]
But the hardware functions normally on windows OS. 
And when using the stock driver from arch kernel, the bringing up operation could be done successfully and I could perform `iw dev wlp3s0 scan` at the first time, but then it would fail at the following operations. The stock driver doesn't give anything in dmesg log about this failure.

**Comment by lwfinger** [comment]
If you are having the INIT MAC FAILURE issue with the RTL8192EE, I have a different driver for you to test. Please send E-mail to Larry.Finger@lwfinger.net to get a copy. At the moment, that driver will only build with kernel 4.14 and older, but I am working on that issue.

**Comment by lwfinger** [comment]
The new driver now builds with kernels up to 4.20.

**Comment by lwfinger** [comment]
The rtlwifi_new repo now has a file named rtl8192ee_revised.tar.bz2. Pull that, untar it, build, and install it. You will need to blacklist rtl8192ee.
