### ISSUE TITLE
'rtl8723Be': Exec format error

### ISSUE THREAD

**Issue by ShadowOne333** [lwfinger/rtlwifi_new#273]
Good day.

I installed the latest source of rtlwifi_new in a Linux - Gentoo machine (64 bit) with kernel 4.12.12.
make and make install ran fine and everything, but when I try to modprobe rtl8723be, I get the following error:

`modprobe ERROR: could not insert 'rtl8723be': Exec format error`

I am assuming this has something to do with the fact that I am running a 64 bit machine and for some reason it cannot execute said module.

Is there any way to force the installation to 64 bits?

**Comment by lwfinger** [comment]
64-bits has nothing to do with the problem. That message means that something about your build of the modules does not match the running kernel. It could be that the headers are for a different version, or that you used a different version of the compiler than was used by Gentoo. EVERYTHING MUST MATCH!

Check the output of the dmesg command get more information.

**Comment by retrazil** [comment]
Can you show your dmesg output ?

**Comment by surajitbasak109** [comment]
Hello I got this message:
rtlwifi: version magic '4.15.0-20-generic SMP mod_unload ' should be '4.15.0-33-generic SMP mod_unload ' when running dmesg

**Comment by lwfinger** [comment]
The driver and kernel headers do not match the running kernel. They must!
