### ISSUE TITLE
8723be Not installed properly

### ISSUE THREAD

**Issue by gagankhanijau** [lwfinger/rtlwifi_new#274]
dmesg |grep 'rtl'
[   14.806621] Bluetooth: hci0: rtl: examining hci_ver=08 hci_rev=000d lmp_ver=08 lmp_subver=8723
[   14.806622] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723b_config.bin
[   14.895823] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723b_config.bin failed with error -2
[   14.895825] Bluetooth: hci0: Failed to load rtl_bt/rtl8723b_config.bin
[   14.895849] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723b_fw.bin
[   16.388619] Bluetooth: hci0: rtl: examining hci_ver=08 hci_rev=000d lmp_ver=08 lmp_subver=8723
[   16.388620] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723b_config.bin
[   16.388628] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723b_config.bin failed with error -2
[   16.388629] Bluetooth: hci0: Failed to load rtl_bt/rtl8723b_config.bin
[   16.388652] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723b_fw.bin

**Comment by lwfinger** [comment]
That missing config file is not critical for 8723b. The message is changed in newer kernels so as to not confuse users.

**Comment by gagankhanijau** [comment]
But my wlan is still not showing up .. It gets successfully installed from the master branch and after restarting network card is still not recognized.
my kernel version is 4.10.x and following are the further details..I have just created an dual boot for ubuntu 16.04 with windows 10(all network adapters work fine there)
----------------------------------------
*-network
                description: Ethernet interface
                product: RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
                vendor: Realtek Semiconductor Co., Ltd.
                physical id: 0
                bus info: pci@0000:01:00.0
----------------------------------------------
Bus 001 Device 006: ID 0bda:b009 Realtek Semiconductor Corp. 
----------------------------------------------
iwconfig
eno1      no wireless extensions.

lo        no wireless extensions.


--------------------------------------

lspci -vvnn | grep -A 9 Network 
02:00.0 Network controller [0280]: Realtek Semiconductor Co., Ltd. Device [10ec:d723]
	DeviceName: Hanksville Gbe Lan Connection
	Subsystem: Hewlett-Packard Company Device [103c:8319]
------------------------------------------------------------------
lshw -C network

  *-network               
       description: Ethernet interface
       product: RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
       vendor: Realtek Semiconductor Co., Ltd.
       physical id: 0
       bus info: pci@0000:01:00.0
       logical name: eno1
       version: 15
       serial: 18:60:24:b8:27:22
       size: 1Gbit/s
       capacity: 1Gbit/s
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress msix bus_master cap_list ethernet physical tp mii 10bt 10bt-fd 100bt 100bt-fd 1000bt 1000bt-fd autonegotiation
       configuration: autonegotiation=on broadcast=yes driver=r8169 driverversion=2.3LK-NAPI duplex=full firmware=rtl8168h-2_0.0.2 02/26/15 ip=192.168.0.26 latency=0 link=yes multicast=yes port=MII speed=1Gbit/s
       resources: irq:126 ioport:4000(size=256) memory:b1104000-b1104fff memory:b1100000-b1103fff
  *-network UNCLAIMED
       description: Network controller
       product: Realtek Semiconductor Co., Ltd.
       vendor: Realtek Semiconductor Co., Ltd.
       physical id: 0
       bus info: pci@0000:02:00.0
       version: 00
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress cap_list
       configuration: latency=0
       resources: ioport:3000(size=256) memory:b1000000-b100ffff

-----------------------------------------------------------------------


In my windows the same driver is installed i.e. rtl8723be which works fine.
ANy suggestions . please help me out?

**Comment by lwfinger** [comment]
The PCI ID of 10ec:d723 means your card is an RTL8723DE. Thus far, Linux does not support that device. Windows may use the same driver as for the RTL8723BE, but there are changes to support the new chip that are not apparent from the outside. If you want, you could add that ID to the PCI_DEVICE table in rtl8723be/sw.c, which would cause Linux to recognize the device; however, the best outcome would be for it not to work. In the worst case, it would crash the system on boot. I am told that the two devices are very different under the hood. Sorry, but you will need to wait

**Comment by gagankhanijau** [comment]
Sure.. Thanks.. I will wait then.. So only option for me as of now is to get new network card.. Is it?

**Comment by lwfinger** [comment]
Yes. a USB card will fix your problem.

**Comment by gagankhanijau** [comment]
Sure Thanks.

**Comment by gagankhanijau** [comment]
https://www.amazon.com/dp/B003MTTJOY/ref=psdc_13983731_t1_B008IFXQFU 
will this one be sufficient and easy for running .. in windows10 and linux
also, do i need to get rid of the internal card?
Just plugging this in, would it work ? or do i need to install any supportable softwares?

**Comment by lwfinger** [comment]
That one will work. You do not need to remove the internal card. The only thing that will be needed is the firmware, which will be part of any distro's firmware package.

**Comment by gagankhanijau** [comment]
Sure Thanks a lot  👍 .. @lwfinger  you gave a great helping hand  👍 . Kudos to your work in the open source :)
