### ISSUE TITLE
Make errors for variable definitions

### ISSUE THREAD

**Issue by OedipusR3x** [lwfinger/rtlwifi_new#275]
I'm attempting to compile in CentOT 7 but when I run make I get the following output showing errors:

`make -C /lib/modules/3.10.0-514.26.2.el7.x86_64/build M=/home/Trent/Downloads/rtlwifi_new modules`
`make[1]: Entering directory '/usr/src/kernels/3.10.0-514.26.2.el7.x86_64'`
 `CC [M]  /home/Trent/Downloads/rtlwifi_new/pci.o`
`In file included from /home/Trent/Downloads/rtlwifi_new/pci.c:30:0:`
`/home/Trent/Downloads/rtlwifi_new/wifi.h:45:27: error: ‘IEEE80211_NUM_BANDS’ undeclared here (not in a function)`
 `#define NUM_NL80211_BANDS IEEE80211_NUM_BANDS`
`                                           ^`

`/home/Trent/Downloads/rtlwifi_new/wifi.h:1399:40: note: in expansion of macro ‘NUM_NL80211_BANDS’`
 `struct ieee80211_supported_band bands[NUM_NL80211_BANDS];`
 `                                       ^`
`/home/Trent/Downloads/rtlwifi_new/pci.c:49:1: error: redefinition of ‘pci_zalloc_consistent’`
` pci_zalloc_consistent(struct pci_dev *hwdev, size_t size,`
` ^`
`In file included from ./arch/x86/include/asm/pci.h:128:0,`
                ` from include/linux/pci.h:1484,`
              `   from /home/Trent/Downloads/rtlwifi_new/pci.h:33,`
                ` from /home/Trent/Downloads/rtlwifi_new/pci.c:32:`
`include/asm-generic/pci-dma-compat.h:23:1: note: previous definition of ‘pci_zalloc_consistent’ was here`
` pci_zalloc_consistent(struct pci_dev *hwdev, size_t size,`
` ^`
`make[2]: *** [/home/Trent/Downloads/rtlwifi_new/pci.o] Error 1`
`make[1]: *** [_module_/home/Trent/Downloads/rtlwifi_new] Error 2`
`make[1]: Leaving directory '/usr/src/kernels/3.10.0-514.26.2.el7.x86_64'`
`make: *** [all] Error 2`

Any help would be appreciated.

**Comment by lwfinger** [comment]
I am no longer supporting kernels as old as 3.10. You need to upgrade. There have been at least 34 new kernel versions released since that one was new.

**Comment by OedipusR3x** [comment]
Oh gotcha. You might want to update the info text file. It says 3.0 kernels
or newer.
