### ISSUE TITLE
Issue regarding my wifi drop

### ISSUE THREAD

**Issue by VibhavChaddha** [lwfinger/rtlwifi_new#277]
Sorry, but this issue is not related to this code, but I am facing an issue with my wifi and I had no other options but to ask it here.
I wrote a command in my terminal to check the currently installed Wifi drivers (sudo lshw -C network).
Under 'description: wireless interface' it is showing 'product: Intel Corporation' instead of any 'rtl' number.
So how can I use this [https://askubuntu.com/questions/939758/wifi-drops-after-5-minutes-with-rtl8821ae](url) for resolving my issue?
Kindly help me.
And sorry again for asking it here, but I don't have a reputation to ask it on the above-mentioned link.

**Comment by lwfinger** [comment]
Every driver is different. That issue with an RTL8821AE is not applicable to problems with any Intel device.

Why do you think you do not have a reputation needed to pose a question on askubuntu? Have you been banned from there?

**Comment by VibhavChaddha** [comment]
lwfinger Okay. Thank you.

I can ask a new question, but I can't write a comment on any question/answer because of my reputation.

I am attaching a screenshot if you can help me out with my issue I'll be really grateful.
Thanks.
![screenshot from 2017-10-10 11-49-11](https://user-images.githubusercontent.com/23036740/31372101-cca3bd98-adb1-11e7-9d42-dc4689d26b26.png)
