### ISSUE TITLE
problem in kali linux

### ISSUE THREAD

**Issue by jitupundir** [lwfinger/rtlwifi_new#278]
firmware: failed to load rtl_bt/rtl8723b_config.bin (-2) in kali linux
hci0: didn't find patch for chip id 2

**Comment by lwfinger** [comment]
Ignore that firmware message. It is changed upstream. I know nothing of the other. I only provide the BT driver - I do not maintain it.

Kali Linux is not a very detailed descrip0tion of your system! What kernel are you running?

**Comment by jitupundir** [comment]
sir some info of my kali linux are as foliowing
Linux rana 4.13.0-kali1-amd64 #1 SMP Debian 4.13.4-1kali1 (2017-10-03)
x86_64 GNU/Linux
root@rana:~#
root@rana:~# lsb_release -a
No LSB modules are available.
Distributor ID:    Kali
Description:    Kali GNU/Linux Rolling
Release:    kali-rolling
Codename:    kali-rolling
pl give me some help

**Comment by jitupundir** [comment]
root@rana:~# ifconfig wlan0 up
wlan0: ERROR while getting interface flags: No such device
Sir wifi not work
