### ISSUE TITLE
Not an issue, just a question from a newbie

### ISSUE THREAD

**Issue by ArtyomFR** [lwfinger/rtlwifi_new#279]
Hello there,
I had to use your driver on my laptop wich is a ASUS X550V (rtl8821ae) and after a general update of the system (I don't really remind me what was inside) the driver seemed to not work anymore...
I readed on a website that offer a tutoriel to install this driver that we  shoud not update the kernel if we want the driver to work and I think that's what happen to me (I did some manipualtions to get it work again and wrecked up my ubuntu so now its a fresh install and all run just fine).

My question is: Does a kernel update break the driver and if yes how to prevent it?
Thanks!

**Comment by lwfinger** [comment]
Every out-of-kernel driver needs to be compiled against the running kernel. There is no getting around that fact. You change the kernel, you rebuild the driver.
