### ISSUE TITLE
[rtl8821ae] Issue with CRDA

### ISSUE THREAD

**Issue by Kra1o5** [lwfinger/rtlwifi_new#281]
Hi @lwfinger ,

When I set ES (Spain) as CRDA REGDOMAIN the upload/download speed gets worse.

Tested with clean install of Ubuntu 14.04.5 (Kernel 4.4) and Ubuntu 16.04.3 (Kernel 4.10) using kernel_version branch of this repo.

Greetings

**Comment by lwfinger** [comment]
What is the REGDOMAIN when you do not set ES?

**Comment by Kra1o5** [comment]
@lwfinger,

None.
