### ISSUE TITLE
About 8812au

### ISSUE THREAD

**Issue by taleru** [lwfinger/rtlwifi_new#286]
Hi, currently none driver for 8812au works fine on USB 3.0. You could include that chip in your driver?

PLEASE, S.O.S

**Comment by lwfinger** [comment]
I have not written a driver. What I do is make available the drivers from Realtek. There has been a GitHub driver for the RTL8812au available from git://github.com/gnab/rtl8812au.git; however, that version fails to build on the latest kernels.

I have created git://github.com/lwfinger/rtl8812au.git, which will build on kernels up to 4.14.

**Comment by taleru** [comment]
Thanks u so much.
