### ISSUE TITLE
Slow speeds and high pings under network load using RTL8723be

### ISSUE THREAD

**Issue by niekie** [lwfinger/rtlwifi_new#29]
Hello,

I am currently experiencing an issue quite similar to #28. I am currently getting slow and heavily fluctuating speeds on my wifi connection, however the issue seems to be more affected by network load than distance (not that I can test the distance issue very well in my small apartment). Since the issue did not seem distance-related here and the issue already had some possibly unrelated comments, I decided to open a new ticket. If you would prefer me to share my findings in the original ticket instead, please let me know :-)

I have taken the liberty of running a few ping tests to my local access point.

The first test was during no real network load: http://pastebin.com/xLJcDKQC
The second test was while running "wget download.xs4all.nl/test/100MB.bin", downloading a 100MB file: http://pastebin.com/GPdywBAx

It was suggested in the above ticket that the issue might be related to the rate control algorithm. On a hunch, I decided to make sure mac80211 loads with the following parameters:

mac80211 ieee80211_default_rc_algo=minstrel

and neutered the rtl rate control algorithm by changing the following line:

if ( rtl_rate_control_register())

to:

if ( false && rtl_rate_control_register())

This caused the system to revert to the minstrel rate control algorithm as verified by dmesg output. What followed was still a slow connection and high pings under network load, however both did not seem to fluctuate as wildly anymore.

I currently use the rtl8723be module with the following parameters: rtl8723be fwlps=N swlps=N ips=N

If you have any debugging steps I could go through to help fix this issue, I'd be happy to oblige!

**Comment by lwfinger** [comment]
Interesting that minstrel gives more stable rates, but I have no idea how the firmware handles rate control. The problem with making this change is that the firmware never tells the driver how many retries were needed. Thus, minstrel is not getting good information. I'm surprised that it works at all. It likely always uses a 1 Mbps rate. You would need to capture the over-the-air packets to verify that.

I do not know anything of how the device works, thus I can only debug issues that involve the driver interface with the rest of the kernel. The firmware and wifi hardware are a black box to me.

**Comment by niekie** [comment]
@lwfinger: Thanks for your quick reply!

First off, you are right, running iwconfig seems to mostly show the interface at 1Mbps (except on some rare invocations where it will spike up a little). During my download tests, I would still get a download over 1Mb/s though.

I did some more debugging, as this issue drove me mad, and actually managed to find out my local wireless environment is quite saturated! And as it turns out, changing the channel seemed to have improved everything by a lot (after recompiling the driver to use the rtl rate control algorithm again). Oddly enough, I was not experiencing such severe issues on other wifi devices connected to my network.

I am currently running the driver with "options rtl8723be fwlps=Y swlps=N ips=Y" and am able to get a good speed going, and the ping does not change quite as dramatically anymore after starting a huge download. I still occasionally get high ping peaks once in a while, but I suppose they might be part of a different issue.

Thanks again for your quick reply, and my apologies for the presuming that it was a driver issue too quickly. Also, if I have more information about those occasional high ping peaks, I'll make sure to report back!
