### ISSUE TITLE
RTL8821ae unusable under Ubuntu 17.10 

### ISSUE THREAD

**Issue by skywalker89** [lwfinger/rtlwifi_new#290]
Thank you so much for creating these drivers for all of us... 

have a huge issue with my Realtek RTL8821AE

not sure it is about Ubuntu 17.10, but with the Realtek rtl8821ae (using newest kernel 4.13) I have drops and or/very slow connections every few  minutes :(

basically unusable

any idea ?? 

Thx Dan

**Comment by christianmtr** [comment]
Yes, in my Ubuntu Mate 26.04 I solve it with `sudo modprobe -r rtl8821ae && sudo modprobe rtl8821ae`.

**Comment by hhg7** [comment]
this solution only works for a few minutes, the WiFi dies.  Is there a more permanent solution?

**Comment by averyre** [comment]
Issue persists under Ubuntu 16.04 and kernel version 4.15
