### ISSUE TITLE
Unknown symbol _rtl_dbg_trace in Arch Linux Kernel 4.13.12

### ISSUE THREAD

**Issue by udiboy1209** [lwfinger/rtlwifi_new#292]
I cannot modprobe `rtl8723be` because the symbol `_rtl_dbg_trace` wasn't found in `rtl8723_common`. Exact dmesg error is:

```
rtl8723_common: disagrees about version of symbol _rtl_dbg_trace
rtl8723_common: Unknown symbol _rtl_dbg_trace (err -22)
```

I have tried re-installing both `master` and `kernel_verison` branches but both give the same error.

OS: Arch Linux
Kernel: 4.13.12

**Comment by lwfinger** [comment]
For kernel 4.13.12, you should not be using rtlwifi_new. Use the in-kernel version instead.

As to the error, what is the setting for CONFIG_RTLWIFI_DEBUG in your distros configuration. You should be able to find it in /boot/config****.

**Comment by udiboy1209** [comment]
I should have played around with `ant_sel` option, the kernel module works fine! Thank you! Strangely a different `ant_sel` value worked for me on Arch than what I had used on a previously installed Ubuntu (different kernel versions too).

I can't find any /boot/config*** on my install, maybe the kernel config is placed somewhere else. I'll post it as soon as I find it.

**Comment by abrolmrinal** [comment]
@udiboy1209 How did you resolve the `_rtl_bug_trace` issue? I'm still unable to load the `rtl8723be` module.

**Comment by lwfinger** [comment]
I do not have this problem. I suspect something is wrong with you kernel configuration. You need to have CONFIG_RTLWIFI_DEBUG=y.

**Comment by abrolmrinal** [comment]
@lwfinger my kernel configuration file has `CONFIG_RTLWIFI_DEBUG=y`.

I'll try too look into it; Thanks for your time. 

But just in case, other information is same as @udiboy1209's: 

Output for `sudo modprobe -v rtl8723be`:

```
insmod /lib/modules/4.13.12-1-ARCH/kernel/drivers/net/wireless/realtek/rtlwifi/rtl8723com/rtl8723-common.ko 
modprobe: ERROR: could not insert 'rtl8723be': Invalid argument
```

dmesg output: 

```
rtl8723_common: disagrees about version of symbol _rtl_dbg_trace
rtl8723_common: Unknown symbol _rtl_dbg_trace (err -22)
```

Distro: Arch Linux
Kernel Version: `4.13.12-1-ARCH`

**Comment by abrolmrinal** [comment]
@lwfinger after some poking around, I found that when I compile the `kernel_version` branch, it doesn't build the `rtl8723-common` modules. The Makefile for that branch doesn't have a recipe for building `rtl8723b-common` either. 

The `rtl8723-common` module being used instead comes from a previous `master` branch make. (Basically, everything gets replaced in `/lib/modules/...` when I make the `kernel_version` branch project except for the `rtl8723-common` directory)

(I'm not sure if any of this makes sense -- I'm sorry for wasting your time if it doesn't)

**Comment by udiboy1209** [comment]
@abrolmrinal I followed lwfinger's advice and removed the `rtlwifi_new` module from my kernel. The original module shipped with the kernel worked for me well, I just had to switch to a different antenna (using `ant_sel`).

**Comment by lwfinger** [comment]
@abrolmrinal: I fixed the lack of build for rtl8723com. It was missed when I created the kernel branch.

@udiboy1209: You will need to ask on the Arch forum if you need to find the config in the future.

**Comment by TOTBWF** [comment]
I'm experiencing something similar to this right now.
```
uname -r: 4.14.47-1-MANJARO
```
I've checked my kernel config, both CONFIG_RTLWIFI_DEBUG and CONFIG_RTLWIFI_DEBUG_ST are set.

**Comment by lwfinger** [comment]
There was a patch that came through stable where the required value of ant_sel changed. This problem happened because the driver and the BT coexistence code are maintained by two separate groups. One introduced a change that broke the driver code!

I do not understand the missing _rtl_dbg_trace(). If CONFIG_RTLWIFI_DEBUG is defined in the kernel configuration, then this routine is built.

**Comment by TOTBWF** [comment]
Yeah, WRT to the missing _rtl_dbg_trace(), I have no idea what could be causing it. Luckily, I seem to not need it, but just let me know if you want me to mess around a bit to get a better repro/some more information.
