### ISSUE TITLE
Will any of these drivers work with RTL8191SU USB dongles?

### ISSUE THREAD

**Issue by sabexx** [lwfinger/rtlwifi_new#293]
It seems there's a lot of overlap within the mainline kernel modules with regards to which driver supports which cards, so I thought I'd check.

Do any of these drivers support the RTL8191SU based USB devices? I'm getting 20% packet loss with the drivers in kernel 4.4.88.

**Comment by lwfinger** [comment]
No. All of these drivers use a mini-driver named rtlwifi. Your device does not. This repo is only to provide the latest versions for people that have not yet implemented a recent kernel.

I am afraid you are on your own.
