### ISSUE TITLE
RTL8821CE driver support

### ISSUE THREAD

**Issue by msilberg** [lwfinger/rtlwifi_new#295]
Can you please tell when the support of **_rtl8821ce_** wireless network driver will be added to upstream kernel as well as support for Bluetooth firmware.

Meanwhile I have to use this one https://github.com/endlessm/linux/tree/master/drivers/net/wireless/rtl8821ce and compile it each time I update a kernel, however it lacks Bluetooth support.

Thanks.

**Comment by lwfinger** [comment]
I have never heard of the device, and I have no idea when, or even if, it will be submitted to the kernel. Please note that I am (1) not an employee of Realtek, and (2) I am not privy to their plans.

As long as you use an out-of-kernel driver, it will be necessary to rebuild with every kernel update. There is no way around that fact.

In general, I am completely unaware of BT matters. Are you sure your device has BT capability? If so, then YOU will need to add the appropriate device IDs to btusb.c in order for the kernel to recognize the device.

**Comment by msilberg** [comment]
I assume you're not an employee of Realtek ;) and don't have strict obligations.
Here's an [update plans](https://www.spinics.net/lists/linux-wireless/msg166957.html) I found regarding rtl8821ce driver support by the upstream kernel.
According to this, the driver should be patched on 2018 Q1.
