### ISSUE TITLE
Can't install on Mint 18.3

### ISSUE THREAD

**Issue by pjc123** [lwfinger/rtlwifi_new#297]
I am a long time user of your drivers on Linux Mint 18.2, but I am getting errors installing on Linux Mint 18.3.  The procedure I normally use:

[
git clone git://github.com/lwfinger/rtlwifi_new.git
cd rtlwifi_new
git checkout rock.new_btcoex
make
sudo make install
Reboot. After the system comes up:
sudo modprobe -rv rtl8723be
sudo modprobe -v rtl8723be ant_sel=2
](url)

**However on Linux Mint 18.3, at the "make" command above I get:**

[
mint@mint ~/Desktop/rtlwifi_new/rtlwifi_new $ make
make -C /lib/modules/4.10.0-38-generic/build M=/home/mint/Desktop/rtlwifi_new/rtlwifi_new modules
make[1]: Entering directory '/usr/src/linux-headers-4.10.0-38-generic'
  CC [M]  /home/mint/Desktop/rtlwifi_new/rtlwifi_new/base.o
In file included from /home/mint/Desktop/rtlwifi_new/rtlwifi_new/base.c:26:0:
/home/mint/Desktop/rtlwifi_new/rtlwifi_new/wifi.h:43:2: error: #error "This branch is abandoned. Please do not use"
 #error "This branch is abandoned. Please do not use"
  ^
scripts/Makefile.build:294: recipe for target '/home/mint/Desktop/rtlwifi_new/rtlwifi_new/base.o' failed
make[2]: *** [/home/mint/Desktop/rtlwifi_new/rtlwifi_new/base.o] Error 1
Makefile:1524: recipe for target '_module_/home/mint/Desktop/rtlwifi_new/rtlwifi_new' failed
make[1]: *** [_module_/home/mint/Desktop/rtlwifi_new/rtlwifi_new] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.10.0-38-generic'
Makefile:57: recipe for target 'all' failed
make: *** [all] Error 2
](url)

**Comment by lwfinger** [comment]
How plain could I make it?

/home/mint/Desktop/rtlwifi_new/rtlwifi_new/wifi.h:43:2: error: #error "This branch is abandoned. Please do not use"
#error "This branch is abandoned. Please do not use"

In case you do not understand, that branch is abandoned. Please do not use. You need to checkout the "kernel" branch.

**Comment by pjc123** [comment]
I saw the error, just didn't know what to change it to.  I know nothing about how git or make or any of this software works.  All I know is someone posted the above commands and my WiFi reception was fixed because my laptop uses the proper non-empty antenna port.

So, should

git checkout rock.new_btcoex

be

git checkout kernel?

**Comment by pjc123** [comment]
@LingMan.  After searching around git I did find that branch yesterday.  I also assumed that is what is needed; I am Installing Mint today so thanks for verifying that.
