### ISSUE TITLE
Rtl8821ae endless error loop on start up after reboot

### ISSUE THREAD

**Issue by Clowcadia** [lwfinger/rtlwifi_new#300]
I followed all steps and the step that creates this error is disable boot security I think. Running ubuntu 16.4 under asusx541uv

**Comment by Titokhan** [comment]
Do you have Secure Boot turned on in your firmware?

**Comment by Clowcadia** [comment]
i turned it off in the bios and i believe also on installing ubuntu

**Comment by lwfinger** [comment]
With no error messages posted, what help can you possibly expect?

**Comment by Clowcadia** [comment]
![20171222_115453](https://user-images.githubusercontent.com/6701661/34306135-95f8eac4-e70f-11e7-8a75-2d33977762cf.jpg)
Sorry it's just to reproduce I have to reinstall ubuntu ...bit of a hassle did it 5+ times now

**Comment by Clowcadia** [comment]
Also happens just before reboot

**Comment by lwfinger** [comment]
Bus errors like that are usually a hardware problem. It is NOT a secure boot problem. Unfortunately, the reason has rolled off the end of the screen.

Please post the output of 'lspci -nn'. That will identify the device on bus 1c.5. If it is the RTL8821AE that is causing the problem, then there are two load options that might help. In /etc/modprobe.d/, create a file named 50-rtl8821ae.conf with a single line "blacklist rtl8821ae". That should allow you to get booted without the error.

Once you reach that point, then try the command "sudo modprobe -v rtl8821ae aspm=0".

If that fixes the problem, then change the line in the file created earlier to "options rtl8821ae aspm=0". That will make the option be set at every load.

If the aspm option does not fix the problem, then try the command "sudo modprobe -v rtl8821ae msi=0". This one is less likely to be a problem, but if it does fix the problem, then again change the file /etc/modprobe.d/50-rtl8821ae.conf.

**Comment by Clowcadia** [comment]
ok i got this for 'lspci -nn'
`00:00.0 Host bridge [0600]: Intel Corporation Sky Lake Host Bridge/DRAM Registers [8086:1904] (rev 08)
00:02.0 VGA compatible controller [0300]: Intel Corporation Sky Lake Integrated Graphics [8086:1916] (rev 07)
00:04.0 Signal processing controller [1180]: Intel Corporation Skylake Processor Thermal Subsystem [8086:1903] (rev 08)
00:14.0 USB controller [0c03]: Intel Corporation Sunrise Point-LP USB 3.0 xHCI Controller [8086:9d2f] (rev 21)
00:14.2 Signal processing controller [1180]: Intel Corporation Sunrise Point-LP Thermal subsystem [8086:9d31] (rev 21)
00:15.0 Signal processing controller [1180]: Intel Corporation Sunrise Point-LP Serial IO I2C Controller [8086:9d60] (rev 21)
00:15.1 Signal processing controller [1180]: Intel Corporation Sunrise Point-LP Serial IO I2C Controller [8086:9d61] (rev 21)
00:16.0 Communication controller [0780]: Intel Corporation Sunrise Point-LP CSME HECI [8086:9d3a] (rev 21)
00:17.0 SATA controller [0106]: Intel Corporation Sunrise Point-LP SATA Controller [AHCI mode] [8086:9d03] (rev 21)
00:1c.0 PCI bridge [0604]: Intel Corporation Device [8086:9d10] (rev f1)
00:1c.4 PCI bridge [0604]: Intel Corporation Sunrise Point-LP PCI Express Root Port [8086:9d14] (rev f1)
00:1c.5 PCI bridge [0604]: Intel Corporation Sunrise Point-LP PCI Express Root Port [8086:9d15] (rev f1)
00:1f.0 ISA bridge [0601]: Intel Corporation Sunrise Point-LP LPC Controller [8086:9d48] (rev 21)
00:1f.2 Memory controller [0580]: Intel Corporation Sunrise Point-LP PMC [8086:9d21] (rev 21)
00:1f.3 Audio device [0403]: Intel Corporation Sunrise Point-LP HD Audio [8086:9d70] (rev 21)
00:1f.4 SMBus [0c05]: Intel Corporation Sunrise Point-LP SMBus [8086:9d23] (rev 21)
01:00.0 3D controller [0302]: NVIDIA Corporation Device [10de:134f] (rev a2)
02:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTS5286 PCI Express Card Reader [10ec:5286] (rev 01)
02:00.2 Ethernet controller [0200]: Realtek Semiconductor Co., Ltd. RTL8101/2/6E PCI Express Fast/Gigabit Ethernet controller [10ec:8136] (rev 06)
03:00.0 Network controller [0280]: Realtek Semiconductor Co., Ltd. RTL8821AE 802.11ac PCIe Wireless Network Adapter [10ec:8821]
`

**Comment by Clowcadia** [comment]
that was before the install of rtlwifi_new

**Comment by Clowcadia** [comment]
after install
`00:00.0 Host bridge [0600]: Intel Corporation Sky Lake Host Bridge/DRAM Registers [8086:1904] (rev 08)
00:02.0 VGA compatible controller [0300]: Intel Corporation Sky Lake Integrated Graphics [8086:1916] (rev 07)
00:04.0 Signal processing controller [1180]: Intel Corporation Skylake Processor Thermal Subsystem [8086:1903] (rev 08)
00:14.0 USB controller [0c03]: Intel Corporation Sunrise Point-LP USB 3.0 xHCI Controller [8086:9d2f] (rev 21)
00:14.2 Signal processing controller [1180]: Intel Corporation Sunrise Point-LP Thermal subsystem [8086:9d31] (rev 21)
00:15.0 Signal processing controller [1180]: Intel Corporation Sunrise Point-LP Serial IO I2C Controller [8086:9d60] (rev 21)
00:15.1 Signal processing controller [1180]: Intel Corporation Sunrise Point-LP Serial IO I2C Controller [8086:9d61] (rev 21)
00:16.0 Communication controller [0780]: Intel Corporation Sunrise Point-LP CSME HECI [8086:9d3a] (rev 21)
00:17.0 SATA controller [0106]: Intel Corporation Sunrise Point-LP SATA Controller [AHCI mode] [8086:9d03] (rev 21)
00:1c.0 PCI bridge [0604]: Intel Corporation Device [8086:9d10] (rev f1)
00:1c.4 PCI bridge [0604]: Intel Corporation Sunrise Point-LP PCI Express Root Port [8086:9d14] (rev f1)
00:1c.5 PCI bridge [0604]: Intel Corporation Sunrise Point-LP PCI Express Root Port [8086:9d15] (rev f1)
00:1f.0 ISA bridge [0601]: Intel Corporation Sunrise Point-LP LPC Controller [8086:9d48] (rev 21)
00:1f.2 Memory controller [0580]: Intel Corporation Sunrise Point-LP PMC [8086:9d21] (rev 21)
00:1f.3 Audio device [0403]: Intel Corporation Sunrise Point-LP HD Audio [8086:9d70] (rev 21)
00:1f.4 SMBus [0c05]: Intel Corporation Sunrise Point-LP SMBus [8086:9d23] (rev 21)
01:00.0 3D controller [0302]: NVIDIA Corporation Device [10de:134f] (rev a2)
02:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTS5286 PCI Express Card Reader [10ec:5286] (rev 01)
02:00.2 Ethernet controller [0200]: Realtek Semiconductor Co., Ltd. RTL8101/2/6E PCI Express Fast/Gigabit Ethernet controller [10ec:8136] (rev 06)
03:00.0 Network controller [0280]: Realtek Semiconductor Co., Ltd. RTL8821AE 802.11ac PCIe Wireless Network Adapter [10ec:8821]
`

**Comment by Clowcadia** [comment]
ok it did the same thin just before it restarted but i am booted in

**Comment by Clowcadia** [comment]
and now there is no wifi option

**Comment by Clowcadia** [comment]
restarted after setting the option in config, and wifi appears

**Comment by Clowcadia** [comment]
i got a window 'Sorry, Ubuntu 16.04 has experienced  an internal error'

![screenshot from 2017-12-22 13-16-35](https://user-images.githubusercontent.com/6701661/34308347-05d1de72-e71b-11e7-90bf-6d5a010673c6.png)
![screenshot from 2017-12-22 13-16-46](https://user-images.githubusercontent.com/6701661/34308348-05ded6e0-e71b-11e7-8e80-680be5bd3628.png)
![screenshot from 2017-12-22 13-17-01](https://user-images.githubusercontent.com/6701661/34308349-05eb1ef0-e71b-11e7-90b7-b76e10ed31ee.png)
![screenshot from 2017-12-22 13-17-09](https://user-images.githubusercontent.com/6701661/34308350-05fad12e-e71b-11e7-9e7f-18d1f8822053.png)
![screenshot from 2017-12-22 13-17-20](https://user-images.githubusercontent.com/6701661/34308351-060a21ba-e71b-11e7-8c4f-29b7d7016e27.png)
![screenshot from 2017-12-22 13-17-29](https://user-images.githubusercontent.com/6701661/34308352-061af512-e71b-11e7-8f9a-3d0f077d3f06.png)
![screenshot from 2017-12-22 13-17-37](https://user-images.githubusercontent.com/6701661/34308353-0627e894-e71b-11e7-9382-1a61998d720f.png)
![screenshot from 2017-12-22 13-17-42](https://user-images.githubusercontent.com/6701661/34308354-063499a4-e71b-11e7-943a-47a55defcc52.png)
![screenshot from 2017-12-22 13-17-48](https://user-images.githubusercontent.com/6701661/34308355-0643db44-e71b-11e7-93b1-c89399210724.png)
![screenshot from 2017-12-22 13-18-11](https://user-images.githubusercontent.com/6701661/34308356-0654618a-e71b-11e7-9d94-72db66eebe5e.png)
![screenshot from 2017-12-22 13-18-15](https://user-images.githubusercontent.com/6701661/34308357-066237a6-e71b-11e7-85d9-4d864a7f1954.png)
![screenshot from 2017-12-22 13-18-19](https://user-images.githubusercontent.com/6701661/34308358-0671458e-e71b-11e7-9fc1-ef4600877cbc.png)
![screenshot from 2017-12-22 13-18-26](https://user-images.githubusercontent.com/6701661/34308359-0688d668-e71b-11e7-845f-13abd22dcb9b.png)
![screenshot from 2017-12-22 13-18-31](https://user-images.githubusercontent.com/6701661/34308360-0698c226-e71b-11e7-9b6b-cf93548cafe8.png)
![screenshot from 2017-12-22 13-18-34](https://user-images.githubusercontent.com/6701661/34308361-06a58e48-e71b-11e7-8c79-5b285b54b6a3.png)
![screenshot from 2017-12-22 13-18-50](https://user-images.githubusercontent.com/6701661/34308362-06b220d6-e71b-11e7-970c-4442880a2d3a.png)
![screenshot from 2017-12-22 13-18-57](https://user-images.githubusercontent.com/6701661/34308363-06c0df36-e71b-11e7-92f8-17e2e3f4131a.png)
![screenshot from 2017-12-22 13-19-02](https://user-images.githubusercontent.com/6701661/34308364-06d07284-e71b-11e7-944b-ba95957a023a.png)
![screenshot from 2017-12-22 13-19-08](https://user-images.githubusercontent.com/6701661/34308365-06e6115c-e71b-11e7-9a04-b0798cc27583.png)
![screenshot from 2017-12-22 13-19-15](https://user-images.githubusercontent.com/6701661/34308366-06f3853a-e71b-11e7-88d5-da62645f65f8.png)
![screenshot from 2017-12-22 13-19-29](https://user-images.githubusercontent.com/6701661/34308367-07050a9e-e71b-11e7-94d7-f01b266692c1.png)
![screenshot from 2017-12-22 13-19-34](https://user-images.githubusercontent.com/6701661/34308368-07131292-e71b-11e7-9dc4-d22a116fcaba.png)
![screenshot from 2017-12-22 13-19-39](https://user-images.githubusercontent.com/6701661/34308369-0727bdd2-e71b-11e7-9401-56a832edc8c2.png)
![screenshot from 2017-12-22 13-19-45](https://user-images.githubusercontent.com/6701661/34308370-0734c61c-e71b-11e7-9a36-4c4091b21ac0.png)
![screenshot from 2017-12-22 13-19-54](https://user-images.githubusercontent.com/6701661/34308371-074342aa-e71b-11e7-8051-a0c931e3da2d.png)
![screenshot from 2017-12-22 13-20-00](https://user-images.githubusercontent.com/6701661/34308372-075685fe-e71b-11e7-9321-db255a9dc943.png)
![screenshot from 2017-12-22 13-20-07](https://user-images.githubusercontent.com/6701661/34308373-07646016-e71b-11e7-8d14-a9ed7f3d1bc4.png)
![screenshot from 2017-12-22 13-20-12](https://user-images.githubusercontent.com/6701661/34308374-0776fd16-e71b-11e7-9844-363cee974f20.png)
![screenshot from 2017-12-22 13-20-18](https://user-images.githubusercontent.com/6701661/34308375-0788f4a8-e71b-11e7-806f-94166546809d.png)
![screenshot from 2017-12-22 13-20-28](https://user-images.githubusercontent.com/6701661/34308376-0795c1b0-e71b-11e7-9071-841c99636347.png)

**Comment by Clowcadia** [comment]
ok this option may be the one that works for me, 'options rtl8821ae aspm=0' running wifi to do this so we will see in couple minutes

**Comment by Clowcadia** [comment]
ok so far wireless works great, no disconnect not really slow downs but that error report is still apearing

**Comment by Clowcadia** [comment]
glad i didnt give up on this solution, thank you. i was gonna go lower ubuntu distros

**Comment by Clowcadia** [comment]
ok yea that problem is occuring like every 15 minutes though, currently doing this 'sudo upt upgrade' hopefully it will fix issues, and will change that file soon

**Comment by Clowcadia** [comment]
Ok that made the black error screen error reaccur

**Comment by Clowcadia** [comment]
So aspm work but what do I do about reoccurring problem window

**Comment by Clowcadia** [comment]
And the black error screen on shutdown

**Comment by Clowcadia** [comment]
![1513971746771-630858869](https://user-images.githubusercontent.com/6701661/34310607-78a67efc-e726-11e7-8522-0dddfca100aa.jpg)
Nvm this happens on regular boot. I can boot in I'm special options of booting but not default

**Comment by Clowcadia** [comment]
![1513971896321-31382014](https://user-images.githubusercontent.com/6701661/34310651-b6a909ae-e726-11e7-9592-c71660c18d19.jpg) that one works

**Comment by Clowcadia** [comment]
ok with my problem, leaving ipv6 on the network seams to be good, and i feel i should have a script on shudown to black list it and ons tart up to do both aspm and msi not sure if that is a solution

**Comment by lwfinger** [comment]
This is so disorganized, I have no idea what you did. Note that your wifi card is on bus 03:00.0, not 00:1c.5, which is the one with the error.

If you need aspm=0, I told you how to do that!!!! You do not need a script.

**Comment by Clowcadia** [comment]
Sorry I was trying to fix the issue with  your guiding. In summary aspm is the best solution msi I think. I'll double check. But since this update on my rtl8821ae using your files and methods I had that Linux error report displayed above. And if either aspm and msi are configured in the conference file I can't boot in so I have to blacklist it in configuration for boot and use the terminal on startup to enable network. Still have disconnects but sometimes good network. Network service command doesn't do any thing but the sudo mod probe -r and back on works

**Comment by Clowcadia** [comment]
ok found this in kern,log and the damn file is 150 gigs
`Dec 22 13:03:59 andrei-X541UV kernel: [ 2161.211301] pcieport 0000:00:1c.5: AER: Corrected error received: id=00e5
Dec 22 13:03:59 andrei-X541UV kernel: [ 2161.211305] pcieport 0000:00:1c.5: PCIe Bus Error: severity=Corrected, type=Physical Layer, id=00e5(Receiver ID)
Dec 22 13:03:59 andrei-X541UV kernel: [ 2161.211307] pcieport 0000:00:1c.5:   device [8086:9d15] error status/mask=00000001/00002000
Dec 22 13:03:59 andrei-X541UV kernel: [ 2161.211308] pcieport 0000:00:1c.5:    [ 0] Receiver Error        `

**Comment by Clowcadia** [comment]
How do I fix the pci slot issue

**Comment by Clowcadia** [comment]
ok so in grub file 'pcie_aspm=off' stablizes the connection, but i still have that black screen errors of wrong pci port and constant ubuntu problem window

**Comment by Clowcadia** [comment]
ok this maybe my last post here, and its only maybe help others who have issues with rtl8821ae
'/etc/default/grub' should be edited at 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"' with 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash pcie_aspm=off"' with warning that 'pcie_aspm=off' will turn off power management/saving of the wireless card, making system runner hotter and use more power(not sure if this is dangerous like over clocking.
next is to disable the apport error report thing of ubuntu or other distros, by editing '/etc/default/apport' where 'enabled=1' to 'enabled=0'
these are my research findings, based on searching my issues and errors on different forums, i am not sure if i am correct at all, and if i am please let me know. otherwise i hope this can help to notify others who have issues like mine

**Comment by mainmachine** [comment]
@Clowcadia - You are recommending that people turn off error reporting as a solution...?
This is irresponsible and irrelevenat to the initial issue anyway. Please close this issue.
