### ISSUE TITLE
Different installation instructions?

### ISSUE THREAD

**Issue by scud3r1a** [lwfinger/rtlwifi_new#302]
Hey,

I found multiple sites - like this one: https://medium.com/@elmaxx/rtl8821ae-wifi-drivers-in-ubuntu-16-04-4c1286524afa - purposing to install your code with "make" instead of make clean.

Furthermore, they leave out the option configuration and do not remove the module before loading it again. Is this necessary?

Concerning the options, I found the following suggestion for rtl8821ae:
options rtl8821ae  fwlps=N swlps=Y
...instead of the code you wrote down. Which one is better?

Finally, one question left, do one has to name the conf file after the driver's name in whole or without the ending like "ae", ..., so for example
rtl8821ae.conf or rtl8821.conf?

Thanks!

**Comment by lwfinger** [comment]
It is not necessary, in general, to use "make clean". I removed it when I updated your changes.

Removal of the modules is necessary if any version was already loaded. Your version was correct; however, the removal/reload is not needed if you reboot immediately.

As those Xps options are never needed now, I removed them.

The name of the xx.conf file is arbitrary. Thus using the full name or some abbreviation is immaterial. On the other hand, using the full name lets you know which device is involved with no ambiguity.

**Comment by scud3r1a** [comment]
Okay, thank you!

I see your changes. But I cannot see where one can find the configuration (.conf) steps that are necessary (now)...
Still a line like this?

options rtl8821ae fwlps=N swlps=Y

Thanks.

**Comment by scud3r1a** [comment]
Because I only read this:
options <<YOUR WIRELESS DRIVER CODE>> <<driver_option_name>>=<value>`

And I do not no the option and its value.

**Comment by lwfinger** [comment]
`options <<YOUR WIRELESS DRIVER CODE>> <<driver_option_name>>=<value>` is what it actually says. I took out the xxxps options because they are wrong in ofer 99.999% of cases.Putting them here would lead readers to think they needed to be used.

**Comment by scud3r1a** [comment]
Okay, so I can leave the options out if I just want that it simply works?

And what abound make - now only (sudo) make install, is that enough?

**Comment by lwfinger** [comment]
You should NEVER use sudo with make. None of the operations involved in building the driver need to be privileged. When you install, then you are writing into directories where only root has write privilege, thus that step needs to use sudo.

At one point in the past, the kernel build setup had a mistake that generated a trivial message if you were a non-privileged user. If you were root, it wiped out /dev/null and destroyed the system! That kind of error is the reason you never want to run with more privilege than is absolutely necessary.
