### ISSUE TITLE
Realtek wifi interface disabled fedora 27

### ISSUE THREAD

**Issue by suman-kr** [lwfinger/rtlwifi_new#304]
*-network DISABLED        
       description: Wireless interface
       product: RTL8723BE PCIe Wireless Network Adapter
       vendor: Realtek Semiconductor Co., Ltd.
       physical id: 0
       bus info: pci@0000:08:00.0
       logical name: wlo1
       version: 00
       serial: 70:77:81:c0:28:67
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress bus_master cap_list ethernet physical wireless
       configuration: broadcast=yes driver=rtl8723be driverversion=4.14.8-300.fc27.x86_64 firmware=N/A latency=0 link=no multicast=yes wireless=IEEE 802.11
       resources: irq:18 ioport:5000(size=256) memory:c6100000-c6103fff
  *-network
       description: Ethernet interface
       product: RTL8101/2/6E PCI Express Fast Ethernet controller
       vendor: Realtek Semiconductor Co., Ltd.
       physical id: 0
       bus info: pci@0000:09:00.0
       logical name: eno1
       version: 0a
       serial: 3c:a8:2a:bc:25:72
       size: 10Mbit/s
       capacity: 100Mbit/s
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress msix bus_master cap_list ethernet physical tp mii 10bt 10bt-fd 100bt 100bt-fd autonegotiation
       configuration: autonegotiation=on broadcast=yes driver=r8169 driverversion=2.3LK-NAPI duplex=half firmware=rtl8107e-2_0.0.2 02/26/15 latency=0 link=no multicast=yes port=MII speed=10Mbit/s
       resources: irq:49 ioport:4000(size=256) memory:c6004000-c6004fff memory:c6000000-c6003fff
  *-network
       description: Ethernet interface
       physical id: 3
       bus info: usb@1:2
       logical name: enp0s20u2c4i2
       serial: f2:79:60:61:14:e3
       capabilities: ethernet physical
       configuration: broadcast=yes driver=ipheth ip=172.20.10.2 link=yes multicast=yes

**Comment by lwfinger** [comment]
I have no idea why your network is disabled. It is the distro-supplied user-space code, not the driver, that does the disabling. You need to consult with the Fedora forums to discover the cause. Do you have the firmware installed? The output of dmesg will answer that question.

As you are using kernel 4.14.8, there is absolutely no need for you to use any out-of-kernel driver for the rtl8723be!!!! The kernel in 4.14.x contains everything that you might find here.
