### ISSUE TITLE
ibkmod: ERROR ../libkmod/libkmod-config.c:656 kmod_config_parse: /etc/modprobe.d/50-rtl8723be.conf line 1: ignoring bad line starting with 'modprobe'

### ISSUE THREAD

**Issue by alimatunnisa123** [lwfinger/rtlwifi_new#305]

**Comment by lwfinger** [comment]
That is not my problem. You created file /etc/modprobe.d/50-rtl8723be.conf with incorrect content. There should be only one line in that file that says "options rtl8723be xxxx". Replace xxxx with the desired option(s). Note that "modprobe" does NOT belong on that line.
