### ISSUE TITLE
modprobe search can't find rtl8723de module

### ISSUE THREAD

**Issue by abhishek181297** [lwfinger/rtlwifi_new#306]
My wireless card has rtl8723de. I have cloned from [https://github.com/lwfinger/rtlwifi_new.git] but while doing 
`$ sudo modprobe -r rtl8723de`
it is showing-
 modprobe: FATAL: Module rtl8723de not found.
In the Readme file you have mentioned about extended version for rtl8723de 
> git checkout origin/extended -b extended

could you explain about this extended thing and how to remove the not found problem

**Comment by lwfinger** [comment]
DO THE COMMAND I TOLD YOU TO.

While it is building, read about git branches.

**Comment by abhishek181297** [comment]
Ok thanks problem solved :):)
