### ISSUE TITLE
RTL8821AE: very high ping.

### ISSUE THREAD

**Issue by Marshality** [lwfinger/rtlwifi_new#308]
# Ubuntu 16.04
On the Ubuntu 16.04 LTS driver didn't work at all, couldn't make it work.
# Ubuntu 17.10
After the switch to 17.10, the disconnections were over, but now there is often a very high ping.
Internet speed sometimes decreases significantly. This manifests itself in the long loading of web pages or the long downloading of something even of a small size.
However, on my PC or another half of the hard drive of my laptop (both have Windows OS) everything is fine.
# Some information
![ths2](https://user-images.githubusercontent.com/29520081/34871921-46addca8-f7a0-11e7-8866-b3d16321535a.png)
![this1](https://user-images.githubusercontent.com/29520081/34871969-620ac254-f7a0-11e7-938d-e3cb41894923.png)
![modinfo](https://user-images.githubusercontent.com/29520081/34871978-68ffa49e-f7a0-11e7-9a96-ed30034aa27d.png)
![this](https://user-images.githubusercontent.com/29520081/34871987-6edd2936-f7a0-11e7-997f-910046973f06.png)

**Comment by Marshality** [comment]
@lwfinger please help

**Comment by Marshality** [comment]
# Once again...
![onceagain](https://user-images.githubusercontent.com/29520081/34882940-1b6fe7f6-f7c9-11e7-98ce-1f4aea7ef4e5.png)

**Comment by alexeymuranov** [comment]
I think i have encountered the same or related issue.

Lenovo  ideapad 310 with RTL8821AE under Linux Mint 18.3 was not initially connecting to WiFi at all (after fresh installation without internet connection).  After installing all updates (as of  2018-02-10), WiFi started connecting without problems, but the download  speed was quickly dropping down to about 80kB/s, about 3-5 times slower than when using the same wireless network from another laptop. I tried installing the latest driver from this repository following the instructions, but it did not help.
