### ISSUE TITLE
RTL8814AE driver

### ISSUE THREAD

**Issue by hardiksingh-rathore** [lwfinger/rtlwifi_new#309]
Is there any driver available for RTL8814AE PCIe card ?

**Comment by lwfinger** [comment]
Not to my knowledge.

**Comment by fernandosanchezjr** [comment]
Chiming in here asking for support for a RTL8814AE PCIe card. Hardware ID from lspci is `10ec:8813`. Windows 10 reports it as a RTL8812AE for some reason.

**Comment by fernandosanchezjr** [comment]
Hey, @lwfinger! So I still have the RTL8814AE PCIe card hanging around my place. I got another wifi AC adapter that works on linux, so the RTL card is just sitting here doing nothing. Would you like to have the card?

I would mail it to you for free, if you ever care to get one to mess with.

**Comment by lwfinger** [comment]
If you are sure you do not want it, I would be happy to accept it. Please send E-mail to Larry.Finger@lwfinger.net, and I will send you my postal address.

**Comment by ImedJ** [comment]
Hello,
I am looking for the same driver: RTL8814AE PCIe card ?
Who can help please? it is urgent :)
