### ISSUE TITLE
Bluetooth extremly throttles WiFi speed

### ISSUE THREAD

**Issue by janfromdd** [lwfinger/rtlwifi_new#31]
Hey guys, the last days I experienced a slow Wifi connections from time to time and today I found out that it is related to the use of bluetooth audio stream(!):
- with 5m router distance I reach 15 ~ 16 MBit WiFi speed
- with a BT audio receiver paired I still have ~ 6 MBit WiFi speed
- when streaming music to the BT audio device, the WiFi drops to 0.5 ~ 0.9 MBit

(According to this, I sometimes lost BT connection when opening a website, like BT and WiFi are fighting for the overall bandwidth.)

I am currently running rtlwifi_new from the master branch, latest version on a RTL8823BE onboard chip under ubuntu 14.04 LTS. My AP is a fritz.box Cable 6340.

The BT audio receiver is described here:
https://www.hama.com/00053174/hama-bluetooth-audio-receiver
At the moment I have no other device for testing.

Do you have any ideas what is the reason for this behavior?

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
