### ISSUE TITLE
rtl8723de unstable in kernel 4.14.13-300.fc27.x86_64

### ISSUE THREAD

**Issue by andreseliseo** [lwfinger/rtlwifi_new#311]
Hi @lwfinger,
First of all, thanks for your work. It is great for all of us. 
I used git to clone extended branch and load de module rtl8723de for my new laptop under Fedora 27. The wifi works great but some times the kernel hungs while booting os. If i try many times to shutdown laptop and turn it on again, eventually it boots. But one thing allways work is to edit grub file and adding modprobe.blacklist=rtl8723de.
Is there anyone with same problem?

**Comment by lwfinger** [comment]
Be aware that I do not have one of these devices, thus I cannot test.

Unless you can provide some diagnostics regarding the boot problem, then we will be unable to fix them.

**Comment by alukin** [comment]
First of all, let me say thank you for your work!
I have HP Laptop 15-bw0xx with rtl8723de. OS is Fedora 27 with latest kernel (4.15.6-300.fc27) I tried driver from extended branch, it loads OK and creates "wlo1" device. Then OS tries to rename it to "wlan0" without success and then no more messages related to driver in dmesg output. Obviously, I can not "iwconfig" interface...  So... my best guess that some common modules for this repository do not work correct with 4.15 kernel.
I'm not good at wifi drivers but anyway I'm trying to compare what is different in 4.15 mainline kernel and in this repository and going to compile rtl8723de driver alone with mainline infrasrtucture... 
I'd be glad to help with testing and share my results if I'll have some  success.

**Comment by lwfinger** [comment]
Are you sure that renaming goes from "wlo1" to "wlan0". Usually it is the other way. Please post the contents of file /etc/udev/rules.d/70-persistent-net.rules.

There is no driver for the rtl8723de in any mainline kernel, thus I do not understand your last paragraph.

I do not have an RTL8723DE device, thus all I can do is check that the driver compiles and loads correctly.

**Comment by lwfinger** [comment]
This module will never go to the mainline kernel. Realtek is currently working to make it compatible with the other rtlwifi drivers. That is the form that will be submitted to the kernel. This form is made available so that people with new laptops can use the device now.

**Comment by alukin** [comment]
Could you please point me to GIT with Realtkc's work? I cloned  URL found in MAINTAINERS file: git://git.kernel.org/pub/scm/linux/kernel/git/linville/wireless-testing.git
but there's no rtl8723de code yet

**Comment by lwfinger** [comment]
git://github.com/lwfinger/rtlwifi_new.git. Check out the "extended" branch. It will likely take some time before the 8723de code reaches that point.
