### ISSUE TITLE
Problem with rtl8723be driver

### ISSUE THREAD

**Issue by PainKKKiller** [lwfinger/rtlwifi_new#316]
First of all thanks for this repo, you doing exellent work!
I have ASUS ROG GL753VD-GC138 laptop, I installed Linux Mint 18.2 64bit (firstly cinnamon, after that xfce) on it. Depends on distro, enabled bluetooth, version of kernel (I've tried from 4.8 to 4.13) and other factors wifi works from 10 minutes to 1 hour, then it loses network and see no available networks at all. Restart network manager doesn't help, only system reboot enables wifi again. Started to think it's hardware problem, but in windows 10 it works without any problems. Read and tried some recipes like this http://seyferseed.ru/en/life-en/ubuntu-realtek-rtl8723ae-driver-fix-slow-wifi-speed-fix.html#sthash.S8zi3ZB4.UYQ0GM6L.dpbs it didn't helped either. Please give me any clue how to solve this issue, I'll provide any additional info you'll need.

**Comment by lwfinger** [comment]
Without additional information, I can only ignore your comment.

Are you running code from this repo, or the driver built into the kernel. If the latter, you need at least 4.14.

If you are using this repo, which branch are you using? The "extended" branch is the latest, "kernel-version" is next newest, and "master" is the oldest.

Are you using any module options with rtl8723be?

When the failure happens, is anything logged in the dmesg output?

Does the sequence "sudo modprobe -r rtl8723be && sudo modprobe rtl8723be" restore the network, or do you still need to reboot.

In addition, run the command "iw dev". Using the interface name for your wifi, run the command
sudo iw dev wlp4s0 scan | egrep "SSID|signal"
Post the output. Replace the wlp4s0 in the above line with your interface name.

**Comment by PainKKKiller** [comment]
Thanks alot for your detailed answer, I did research on my own and now can provide some information.
I installed Linux Cinnamon 18.2 again (it comes with 4.8 kernel) and found that everything works fine, I had listen internet radio for several hours without any brake.
sudo lshw -C network did show this information:

```
*-network               
       description: Wireless interface
       product: RTL8723BE PCIe Wireless Network Adapter
       vendor: Realtek Semiconductor Co., Ltd.
       physical id: 0
       bus info: pci@0000:02:00.0
       logical name: wlp2s0
       version: 00
       serial: 64:6e:69:3c:57:9c
       width: 64 bits
       clock: 33MHz
       capabilities: bus_master cap_list ethernet physical wireless
       configuration: broadcast=yes driver=rtl8723be driverversion=4.8.0-53-generic firmware=N/A ip=192.168.1.29 latency=0 link=yes multicast=yes wireless=IEEE 802.11
       resources: irq:18 ioport:d000(size=256) memory:df300000-df303fff

```
Then I installed latest kernel (4.15 amd64 http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.15/) and situation I'd described in my previous post happen again.

sudo lshw -C network after wifi crash show this:
```
*-generic DISABLED      
       description: Wireless interface
       product: Illegal Vendor ID
       vendor: Illegal Vendor ID
       physical id: 0
       bus info: pci@0000:02:00.0
       logical name: wlp2s0f0
       version: ff
       serial: 00:e0:4c:81:92:9f
       width: 32 bits
       clock: 66MHz
       capabilities: bus_master vga_palette cap_list ethernet physical wireless
       configuration: broadcast=yes driver=rtl8723be driverversion=4.15.0-041500-generic firmware=N/A latency=255 link=no maxlatency=255 mingnt=255 multicast=yes wireless=IEEE 802.11
```

Commands `sudo modprobe -r rtl8723be && sudo modprobe rtl8723be`
 and `sudo ifconfig wlp2s0f0 up` didn't change situation, only reboot restores wifi.

Next commands when wifi failed show this info:
```
sudo iw dev wlp2s0f0 scan | egrep "SSID|signal" 

command failed: Network is down (-100)

dmesg | grep wlp2s0f0

[ 7737.453899] rtl8723be 0000:02:00.0 wlp2s0f0: renamed from wlan0
[ 7737.486971] IPv6: ADDRCONF(NETDEV_UP): wlp2s0f0: link is not ready
```
Then I cloned your repo, checkout to extended branch and installed driver as in your instuctions. All remains the same, but dmesg is different:

```
dmesg | grep wlp2s0
[    4.951130] rtl8723be 0000:02:00.0 wlp2s0: renamed from wlan0
[    5.875622] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
[    6.630726] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
[    6.755787] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
[    9.179261] wlp2s0: authenticate with 60:45:cb:ca:76:c8
[    9.210283] wlp2s0: send auth to 60:45:cb:ca:76:c8 (try 1/3)
[    9.214726] wlp2s0: authenticated
[    9.216036] wlp2s0: associate with 60:45:cb:ca:76:c8 (try 1/3)
[    9.221497] wlp2s0: RX AssocResp from 60:45:cb:ca:76:c8 (capab=0x411 status=0 aid=4)
[    9.223454] wlp2s0: associated
[    9.253079] IPv6: ADDRCONF(NETDEV_CHANGE): wlp2s0: link becomes ready
[ 1440.508860] wlp2s0: Connection to AP 60:45:cb:ca:76:c8 lost
[ 1457.336202] wlp2s0: Connection to AP 00:00:00:00:00:00 lost
[ 1472.915048] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
[ 1521.977100] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
```

At least now I have working wifi with 4.8 kernel.

**Comment by jastisriradheshyam** [comment]
Hey @PainKKKiller , I think you are **only updating the kernel** and **not kernel headers** to corresponding kernel version and also **not compiling again** after the kernel update to make the driver compatible to new kernel.

**Comment by PainKKKiller** [comment]
Sorry for silence, I can do my laptop only on weekends. I don't know what I am doing wrong, all known to me ways to check installed linux headers shows that I have 4.15 version (same as kernel). When I install driver from extended branch I see that headers are correct:
`painkiller@painkiller-PC ~/rtlwifi_new $ sudo make installmake -C /lib/modules/4.15.0-041500-generic/build M=/home/painkiller/rtlwifi_new modules
make[1]: Entering directory '/usr/src/linux-headers-4.15.0-041500-generic'
  Building modules, stage 2.
  MODPOST 19 modules
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-041500-generic'
Install rtlwifi SUCCESS
painkiller@painkiller-PC ~/rtlwifi_new $ sudo modprobe -r rtl8723be
painkiller@painkiller-PC ~/rtlwifi_new $ sudo modprobe`

But problem still exists.

**Comment by PainKKKiller** [comment]
and modeinfo shows this:
`painkiller@painkiller-PC ~ $ modinfo rtl8723be
filename:       /lib/modules/4.15.0-041500-generic/kernel/drivers/net/wireless/realtek/rtlwifi/rtl8723be/rtl8723be.ko
firmware:       rtlwifi/rtl8723befw_36.bin
firmware:       rtlwifi/rtl8723befw.bin
description:    Realtek 8723BE 802.11n PCI wireless
license:        GPL
author:         Realtek WlanFAE	<wlanfae@realtek.com>
author:         PageHe	<page_he@realsil.com.cn>
srcversion:     FF0F3E3B747BFAD8076CDEC
alias:          pci:v000010ECd0000B723sv*sd*bc*sc*i*
depends:        rtlwifi,rtl8723-common,rtl_pci,btcoexist,mac80211
name:           rtl8723be
vermagic:       4.15.0-041500-generic SMP mod_unload 
`

**Comment by lwfinger** [comment]
We recently made a change to rtl8821ae that fixed a loss of signal problem. Just in case the same problem is affecting rtl8723be and/or rtl8723de, I just committed a similar fix for them.

**Comment by PainKKKiller** [comment]
Today I pulled b54c550ad39a1916583c5754d5cc5360ed0be194 commit and installed driver again. Seems that it solved my problem - all day my wifi worked like a charm! Thanks for your excellent work!

**Comment by lwfinger** [comment]
Good to hear. I need to push that change up to mainline.

**Comment by mirh** [comment]
Can be closed now?

**Comment by mirh** [comment]
Try 4.16 or 4.17 first of all?

**Comment by nikcodes** [comment]
Thanks  for replying. As I have stated I am currently on kernel 4.15
