### ISSUE TITLE
RTL8723de driver is not workin

### ISSUE THREAD

**Issue by shebinraphel** [lwfinger/rtlwifi_new#319]
i have tried to install the driver.

but make command gives me the following error

make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.13.9-300.fc27.x86_64/build M=/home/shebin/rtl8723de-4.11-up  modules
make[1]: *** /lib/modules/4.13.9-300.fc27.x86_64/build: No such file or directory.  Stop.
make: *** [Makefile:1884: modules] Error 2

Fedora 27
kernel 4.13.9-300

**Comment by jastisriradheshyam** [comment]
Hey, you also need **kernel-devel and kernel-headers** modules for compiling a driver.
For this to work use this command in fedora:

> dnf install kernel-devel kernel-headers

Then try to use make command.

**Comment by shebinraphel** [comment]
thanks for your kind attention..
I have tried the command but again the same error appears.

[root@shebin rtl8723de-4.11-up]# dnf install kernel-devel kernel-headers
Last metadata expiration check: 0:04:27 ago on Mon 05 Feb 2018 10:20:39 PM IST.
Package kernel-devel-4.14.14-300.fc27.x86_64 is already installed, skipping.
Package kernel-headers-4.13.9-300.fc27.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!

[root@shebin rtl8723de-4.11-up]# make
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.13.9-300.fc27.x86_64/build M=/home/shebin/rtl8723de-4.11-up  modules
make[1]: *** /lib/modules/4.13.9-300.fc27.x86_64/build: No such file or directory.  Stop.
make: *** [Makefile:1884: modules] Error 2
[root@shebin rtl8723de-4.11-up]#

**Comment by lwfinger** [comment]
I do not use Fedora, but what I read suggests that those two packages should be sufficient.

I suggest that you ask on the Fedora forums as to what steps are necessary to build an out-of-kernel driver.

**Comment by shebinraphel** [comment]
i am looking forward for the issue fix..

**Comment by jastisriradheshyam** [comment]
Hi,
    [https://ask.fedoraproject.org/en/question/117145/rtl8723de-driver-is-not-workin/](https://ask.fedoraproject.org/en/question/117145/rtl8723de-driver-is-not-workin/), Does the answer provided in the forum helped you to resolve your problem ?
