### ISSUE TITLE
Wireless interface disappeared in NetworkManager on 3.18.5-201.fc21.x86_64

### ISSUE THREAD

**Issue by jflory7** [lwfinger/rtlwifi_new#32]
A week ago or so, there was a new kernel update in the Fedora 21 repositories, `3.18.5-201.fc21.x86_64`. I updated and started using that kernel, cloned the drivers from this repo, compiled, and installed them, like I always do with every kernel update.

However, even after doing `make` and `sudo make install` for the drivers and rebooting, my wireless functionality has completely disappeared. In the GNOME Network interface, the Wireless option is no longer present, whereas before using the drivers, my only issue would be unreliable connectivity to whatever WiFi networks I was connected to. Now, after this latest kernel update and installing the drivers, my wireless functionality has been rendered completely useless.

During my startup process, I did notice something relating to `rtlwifi_new` fly across my screen, but I am unsure where I can open that log on my computer for referencing. I think it was something about the two different kernel versions installed on my computer, but it was difficult for me to read.

If I can provide any other information to help, please let me know, and I will find it. I've never had an issue like this before nor do I know what kind of information might be needed, but anything I can retrieve to help, I will provide.

*EDIT*: Forgot to include my actual Realtek card. Oops. According to `lspci`, my laptop is using `Realtek Semiconductor Co., Ltd. RTL8188EE Wireless Network Adapter (rev 01)`.

**Comment by lwfinger** [comment]
Your question of where to find the logs may be better asked on the Fedora Forum. I am not a user of that distro, but dmesg shows the current log, and /var/log/messages usually shows the saved messages, but YMMV.

If you have correctly installed the rtlwifi_new drivers, they completely replace the existing ones, and there should be no mention of rtlwifi_new unless you modified something in the startup.

By the way, the RTL8188EE driver in 3.18.5 is exactly like the one in rtlwifi_new. You should not need to use this repo any more.

**Comment by jflory7** [comment]
@lwfinger 
To follow up, I've been using the latest kernel for the past three weeks without noticing any issues on my laptop. It's awesome to finally see support in the Linux kernel! Anyways, seeing as it seems my issue is resolved, I will close this ticket.
