### ISSUE TITLE
Testing out FreeBSD... 

### ISSUE THREAD

**Issue by Jakecheslekov** [lwfinger/rtlwifi_new#326]
Hello everyone, I'm giving FreeBSD a shot & I was wondering if anyone could tell me what I'm missing in order to make this driver compile... Or can I just not do that?

sudo gmake -j4
gmake -C /lib/modules/11.1-RELEASE/build M=/usr/home/kzn/Compiles/rtlwifi_new modules
gmake[1]: Entering directory '/lib/modules/11.1-RELEASE/build'
gmake[1]: *** No rule to make target 'modules'.  Stop.
gmake[1]: Leaving directory '/lib/modules/11.1-RELEASE/build'
gmake: *** [Makefile:58: all] Error 2

I get different errors with pmake/bmake

**Comment by lwfinger** [comment]
The system calls for FreeBSD and Linux are different. You could probably convert the Linux driver, but it would be a lot of work. There might also be licensing problems. It does not sound as if you have a real reason to do this, thus the work is probably not worth the effort.

**Comment by eisterman** [comment]
You need to recompile with the LINUX-BSD compatibility layer activated, this adapt the syscall. It's a method used for give to BSD driver that no one would instead write for it.
