### ISSUE TITLE
problem when put instruction make install

### ISSUE THREAD

**Issue by Feitan07** [lwfinger/rtlwifi_new#331]
error: #error "This branch is abandoned. Please do not use"
 #error "This branch is abandoned. Please do not use"
  ^~~~~
/usr/src/linux-headers-4.14.0-kali3-common/scripts/Makefile.build:325: fallo en las instrucciones para el objetivo '/root/Descargas/Rl9823be-Drivers-master/rtlwifi_new/base.o'
make[4]: *** [/root/Descargas/Rl9823be-Drivers-master/rtlwifi_new/base.o] Error 1
/usr/src/linux-headers-4.14.0-kali3-common/Makefile:1525: fallo en las instrucciones para el objetivo '_module_/root/Descargas/Rl9823be-Drivers-master/rtlwifi_new'
make[3]: *** [_module_/root/Descargas/Rl9823be-Drivers-master/rtlwifi_new] Error 2
Makefile:146: fallo en las instrucciones para el objetivo 'sub-make'
make[2]: *** [sub-make] Error 2
Makefile:8: fallo en las instrucciones para el objetivo 'all'
make[1]: *** [all] Error 2
make[1]: se sale del directorio '/usr/src/linux-headers-4.14.0-kali3-amd64'
Makefile:57: fallo en las instrucciones para el objetivo 'all'
make: *** [all] Error 2

HELP ME PLEASE I NEED TO USE KALI LINUX FOR THE SCHOOL AND I CANT USE THE WIFI CARD

**Comment by lwfinger** [comment]
It is not necessary to shout at me. As the error says, that branch has been abandoned. You could remove the source statement, and continue to use this branch, but it is no longer maintained. I wouod ignore any errors in that branch.

A 'git branch -a' command on this repo shows the following:
  remotes/origin/extended
  remotes/origin/kernel_version
  remotes/origin/master
  remotes/origin/rock
  remotes/origin/rock.new_btcoex
  remotes/origin/test
  remotes/origin/troy

Of these, the last 4 are abandoned. I would recommend that you checkout kernel_version using the command 'git checkout origin/kernel_version -b kernel_version'. That will get you source that will build.

**Comment by Feitan07** [comment]
sorry =). i do it  and the installation is succes but.... the network card still does not appear =( what is the problem? or what could i do for resolv the problem, thanks dude

**Comment by lwfinger** [comment]
I am not called "dude"!

Are you sure what network card you have? Post the output of "lspci -nn"

**Comment by Feitan07** [comment]
sorry again lwfinger

i have dual boot, windows and kali and i check the netwoork card on windows and appear the controller Rl9823DE but in linux appear  Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller

what is the true controller?

**Comment by lwfinger** [comment]
It is not the RTL8111 as that is a wired Ethernet controller.

Unless you post the output of 'lspci -nn', I cannot tell you what wireless device you have.

**Comment by heartbreakkid58** [comment]
@lwfinger same issue for me. Here is the output of 'lspci -nn'.

00:00.0 Host bridge [0600]: Intel Corporation Device [8086:5914] (rev 08)
00:02.0 VGA compatible controller [0300]: Intel Corporation Device [8086:5917] (rev 07)
00:04.0 Signal processing controller [1180]: Intel Corporation Skylake Processor Thermal Subsystem [8086:1903] (rev 08)
00:14.0 USB controller [0c03]: Intel Corporation Sunrise Point-LP USB 3.0 xHCI Controller [8086:9d2f] (rev 21)
00:14.2 Signal processing controller [1180]: Intel Corporation Sunrise Point-LP Thermal subsystem [8086:9d31] (rev 21)
00:15.0 Signal processing controller [1180]: Intel Corporation Sunrise Point-LP Serial IO I2C Controller #0 [8086:9d60] (rev 21)
00:15.1 Signal processing controller [1180]: Intel Corporation Sunrise Point-LP Serial IO I2C Controller #1 [8086:9d61] (rev 21)
00:16.0 Communication controller [0780]: Intel Corporation Sunrise Point-LP CSME HECI #1 [8086:9d3a] (rev 21)
00:17.0 SATA controller [0106]: Intel Corporation Sunrise Point-LP SATA Controller [AHCI mode] [8086:9d03] (rev 21)
00:1c.0 PCI bridge [0604]: Intel Corporation Sunrise Point-LP PCI Express Root Port #5 [8086:9d14] (rev f1)
00:1c.5 PCI bridge [0604]: Intel Corporation Sunrise Point-LP PCI Express Root Port #6 [8086:9d15] (rev f1)
00:1d.0 PCI bridge [0604]: Intel Corporation Device [8086:9d1b] (rev f1)
00:1f.0 ISA bridge [0601]: Intel Corporation Device [8086:9d4e] (rev 21)
00:1f.2 Memory controller [0580]: Intel Corporation Sunrise Point-LP PMC [8086:9d21] (rev 21)
00:1f.3 Audio device [0403]: Intel Corporation Device [8086:9d71] (rev 21)
00:1f.4 SMBus [0c05]: Intel Corporation Sunrise Point-LP SMBus [8086:9d23] (rev 21)
01:00.0 Ethernet controller [0200]: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller [10ec:8168] (rev 15)
02:00.0 Network controller [0280]: Realtek Semiconductor Co., Ltd. Device [10ec:c821]
03:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTS522A PCI Express Card Reader [10ec:522a] (rev 01)

**Comment by lwfinger** [comment]
The device 10ec:c821 is an RTL8821CE. At the moment, there are no Linux drivers for it. Driver rtl8821ae is in the mainline kernel, rtl8821be is in staging, but no rtl8821ce yet. I will check with Realtek to get a schedule, but do not expect it immediately.

**Comment by heartbreakkid58** [comment]
@lwfinger thanks for the response. I just have tried below link, and it worked for me. 

https://bbs.deepin.org/forum.php?mod=viewthread&tid=152205
