### ISSUE TITLE
rtl8723de kernel 4.15.4-300.fc27.x86_64 modprobe error

### ISSUE THREAD

**Issue by deth047** [lwfinger/rtlwifi_new#332]
Hi,
I'm experiencing an issue while inserting the module after install by dkms for kernel 4.15.4-300.fc27.x86_64
```
sudo dkms build rtlwifi-new/0.6
sudo dkms install rtlwifi-new/0.6
sudo modprobe -v rtl8723de
modprobe: ERROR: could not insert 'rtl8723de': Unknown symbol in module, or unknown parameter (see dmesg)
```
and dmesg says:
...
Kernel: phydm_mod: Unknown symbol show_it_bb (err 0)
kernel: phydm_mod: Unknown symbol _rtl_dbg_trace (err 0)
kernel: phydm_mod: Unknown symbol show_it_mac (err 0)
...
on kernel 4.15.6-300.fc27.x86_64 it happen too
but on kernel 4.15.3-300.fc27.x86_64 it works fine

Can you give me any pointers to determine what could be going wrong?
Thanks

**Comment by lwfinger** [comment]
You need to make sure that all rtl* modules are unloaded BEFORE you try to load one of these.

'lsmod | grep rtl' must not show any of the modules. You can also reboot after you do 'sudo make install'.

**Comment by deth047** [comment]
I don't know what happens but another one (actually - twice, last one by power button) reboot solved the problem...
Maybe you're right - root cause is unloaded modules.
thanks for the help

**Comment by Hummel95** [comment]
Hi all,
I'm facing problems with rtl8723de as well. I installed latest 17.10 Ubuntu (I think 4.13 kernel) and followed a tutorial in a forum.
`sudo apt-get install git build-essential dkms linux-headers-$(uname -r)
git clone -b extended https://github.com/lwfinger/rtlwifi_new.git
sudo dkms add ./rtlwifi_new
sudo dkms install rtlwifi-new/0.6
sudo cp /usr/src/rtlwifi-new-0.6/firmware/rtlwifi/* /lib/firmware/rtlwifi/ `

Sadly WiFi doesn't work afterwards (tried several reboots).
modinfo rtl8723de shows WiFi driver

lsmod | grep rtl shows rtlwifi, can't unload it because it is still in use though.

**Comment by lwfinger** [comment]
The wifi driver is not loading due to the unknown symbol error. The global is exported in rtl8723com/fw_common.c, thus it does exist. Your problem may be that an older version of rtl8723-common is already loaded. If you had provided the full output from the 'lsmod | grep rtl' command, then I could have told you what needs to be unloaded. 
There is also a possibility that the dkms script has an error. I do not use it myself. For the FIRST time, I highly recommend that you use
make
sudo make install
You need to do those commands now. They build the drivers, install the drivers, and copy the firmware.Those commands ALSO provide the necessary info to be able to uninstall the revised drivers in case that is ever necessary. Of course, once you have done the dkms stuff, the original drivers are now gone. To uninstall these drivers, you will need to use your package manager and reinstall the kernel.

**Comment by Hummel95** [comment]
Thanks for your reply lwfinger.

I managed to get the wifi chip working.
I uninstalled rtlwifi-new using
```
sudo dkms remove rtlwifi-new/0.6 --all
sudo rm -r /usr/src/rtlwifi-new-0.6 
```
and installed the realtek chip driver by itself
```
sudo apt-get install --reinstall build-essential dkms linux-headers-$(uname -r) git
git clone -b 4.11-up https://github.com/smlinux/rtl8723de.git
sudo dkms add ./rtl8723de
sudo dkms install rtl8723de/5.1.1.8_21285.20171026_COEX20170111-1414 
```
which makes WiFi working. Maybe Ubuntu was causing some issues as well (I was using extended branch).
Thanks for your help anyway. 👍

**Comment by abinrajkb** [comment]
@Hummel95 
 I followed your method and the last command throws up an error.
Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'make' all KVER=4.15.0-32-generic...(bad exit status: 2)
ERROR (dkms apport): binary package for rtl8723de: 5.1.1.8_21285.20171026_COEX20170111-1414 not found
Error! Bad return status for module build on kernel: 4.15.0-32-generic (x86_64)
Consult /var/lib/dkms/rtl8723de/5.1.1.8_21285.20171026_COEX20170111-1414/build/make.log for more information.
what to do..?  
( Im running ubuntu 18.04 )

**Comment by gauravsethia08** [comment]
> The wifi driver is not loading due to the unknown symbol error. The global is exported in rtl8723com/fw_common.c, thus it does exist. Your problem may be that an older version of rtl8723-common is already loaded. If you had provided the full output from the 'lsmod | grep rtl' command, then I could have told you what needs to be unloaded.
> There is also a possibility that the dkms script has an error. I do not use it myself. For the FIRST time, I highly recommend that you use
> make
> sudo make install
> You need to do those commands now. They build the drivers, install the drivers, and copy the firmware.Those commands ALSO provide the necessary info to be able to uninstall the revised drivers in case that is ever necessary. Of course, once you have done the dkms stuff, the original drivers are now gone. To uninstall these drivers, you will need to use your package manager and reinstall the kernel.

Output of 'lsmod | grep rtl' is :
rtl8723_common         24576  0
rtl_pci                32768  0
rtlwifi                98304  2 rtl_pci,btcoexist
btrtl                  16384  1 btusb
mac80211              778240  3 rtl_pci,rtlwifi,brcmsmac
bluetooth             548864  43 btrtl,btintel,btbcm,bnep,btusb,rfcomm
cfg80211              622592  3 rtlwifi,mac80211,brcmsmac

Can you please tell what needs to be unloaded.

**Comment by poo17nam** [comment]
Wifi suddenly stopped appearing after reboot.

lsmod | grep rtl gives this
rtl8723_common         28672  0
rtl_pci                32768  0
rtlwifi               110592  2 rtl_pci,btcoexist
mac80211              970752  2 rtl_pci,rtlwifi
btrtl                  24576  1 btusb
cfg80211              831488  2 rtlwifi,mac80211
bluetooth             626688  41 btrtl,btintel,btbcm,bnep,btusb,rfcomm
How do I unload it?

**Comment by lwfinger** [comment]
Unload what?

**Comment by arcajufe** [comment]
my driver Enviado desde mi Samsung Mobile de Claro
-------- Original message --------From: lwfinger <notifications@github.com> Date: 1/10/20  12:39  (GMT-05:00) To: lwfinger/rtlwifi_new <rtlwifi_new@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [lwfinger/rtlwifi_new] rtl8723de kernel 4.15.4-300.fc27.x86_64 modprobe error (#332) Unload what?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/lwfinger/rtlwifi_new/issues/332?email_source=notifications\u0026email_token=AKF7REHC6C5LQKBN572B2GLQ5CXERA5CNFSM4ETN5XZKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIUVFZA#issuecomment-573133540",
"url": "https://github.com/lwfinger/rtlwifi_new/issues/332?email_source=notifications\u0026email_token=AKF7REHC6C5LQKBN572B2GLQ5CXERA5CNFSM4ETN5XZKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIUVFZA#issuecomment-573133540",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by lwfinger** [comment]
You win today's prize for the longest message with exactly NO content.

**Comment by rizmut** [comment]
> @Hummel95
> I followed your method and the last command throws up an error.
> Kernel preparation unnecessary for this kernel. Skipping...
> 
> Building module:
> cleaning build area...
> 'make' all KVER=4.15.0-32-generic...(bad exit status: 2)
> ERROR (dkms apport): binary package for rtl8723de: 5.1.1.8_21285.20171026_COEX20170111-1414 not found
> Error! Bad return status for module build on kernel: 4.15.0-32-generic (x86_64)
> Consult /var/lib/dkms/rtl8723de/5.1.1.8_21285.20171026_COEX20170111-1414/build/make.log for more information.
> what to do..?
> ( Im running ubuntu 18.04 )

Hai,  I'm facing exact output here.

**Comment by lwfinger** [comment]
That message does NOT come from anywhere within my code!

If you do 'make && sudo make install' from the rtlwifi_new directory, what happens? By the way, that is my method.
I suspect you are having trouble with dkms, which I do not support.

**Comment by rizmut** [comment]
> That message does NOT come from anywhere within my code!
> 
> If you do 'make && sudo make install' from the rtlwifi_new directory, what happens? By the way, that is my method.
> I suspect you are having trouble with dkms, which I do not support.
make && sudo make install are successfull, but modprobe failed
https://justpaste.it/5e1xx

**Comment by rizmut** [comment]
I've a solution, more likely a workaround. Just downgraded my kernel to `4.20.17-042017-generic` with help ukuu and then run `make && sudo make install` successfully, and `sudo modprobe -v rtl8723de ant_sel=2` run without error.

I've tried also DKMS (yes I know it should another option)
```
insmod /lib/modules/4.20.17-042017-generic/kernel/net/wireless/cfg80211.ko 
insmod /lib/modules/4.20.17-042017-generic/kernel/net/mac80211/mac80211.ko 
insmod /lib/modules/4.20.17-042017-generic/kernel/drivers/net/wireless/realtek/rtlwifi/rtlwifi.ko 
insmod /lib/modules/4.20.17-042017-generic/kernel/drivers/net/wireless/realtek/rtlwifi/rtl_pci.ko 
insmod /lib/modules/4.20.17-042017-generic/kernel/drivers/net/wireless/realtek/rtlwifi/rtl8723com/rtl8723-common.ko 
insmod /lib/modules/4.20.17-042017-generic/kernel/drivers/net/wireless/realtek/rtlwifi/btcoexist/btcoexist.ko 
insmod /lib/modules/4.20.17-042017-generic/kernel/drivers/net/wireless/realtek/rtlwifi/phydm/phydm_mod.ko 
insmod /lib/modules/4.20.17-042017-generic/kernel/drivers/net/wireless/realtek/rtlwifi/rtl8723de/rtl8723de.ko ant_sel=2
```
rizmut@dtc-jkt-rizalmq:~/Dokumen/Rizmut/Github$ sudo dkms add rtlwifi_new

Creating symlink /var/lib/dkms/rtlwifi-new/0.6/source ->
                 /usr/src/rtlwifi-new-0.6

DKMS: add completed.
rizmut@dtc-jkt-rizalmq:~/Dokumen/Rizmut/Github$ sudo dkms install rtlwifi-new/0.6

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area.........
make -j4 KERNELRELEASE=4.20.17-042017-generic -C /lib/modules/4.20.17-042017-generic/build M=/var/lib/dkms/rtlwifi-new/0.6/build..........................
cleaning build area....

DKMS: build completed.

rtl_pci.ko:
Running module version sanity check.

Good news! Module version  for rtl_pci.ko
exactly matches what is already found in kernel 4.20.17-042017-generic.
DKMS will not replace this module.
You may override by specifying --force.

rtl_usb.ko:
Running module version sanity check.

Good news! Module version  for rtl_usb.ko
exactly matches what is already found in kernel 4.20.17-042017-generic.
DKMS will not replace this module.
You may override by specifying --force.

rtlwifi.ko:
Running module version sanity check.

Good news! Module version  for rtlwifi.ko
exactly matches what is already found in kernel 4.20.17-042017-generic.
DKMS will not replace this module.
You may override by specifying --force.

btcoexist.ko:
Running module version sanity check.

Good news! Module version  for btcoexist.ko
exactly matches what is already found in kernel 4.20.17-042017-generic.
DKMS will not replace this module.
You may override by specifying --force.

halmac.ko:
Running module version sanity check.

Good news! Module version  for halmac.ko
exactly matches what is already found in kernel 4.20.17-042017-generic.
DKMS will not replace this module.
You may override by specifying --force.

phydm_mod.ko:
Running module version sanity check.

Good news! Module version  for phydm_mod.ko
exactly matches what is already found in kernel 4.20.17-042017-generic.
DKMS will not replace this module.
You may override by specifying --force.

rtl8188ee.ko:
Running module version sanity check.

Good news! Module version  for rtl8188ee.ko
exactly matches what is already found in kernel 4.20.17-042017-generic.
DKMS will not replace this module.
You may override by specifying --force.

rtl8192c-common.ko:
Running module version sanity check.

Good news! Module version  for rtl8192c-common.ko
exactly matches what is already found in kernel 4.20.17-042017-generic.
DKMS will not replace this module.
You may override by specifying --force.

rtl8192ce.ko:
Running module version sanity check.

Good news! Module version  for rtl8192ce.ko
exactly matches what is already found in kernel 4.20.17-042017-generic.
DKMS will not replace this module.
You may override by specifying --force.

rtl8192cu.ko:
Running module version sanity check.

Good news! Module version  for rtl8192cu.ko
exactly matches what is already found in kernel 4.20.17-042017-generic.
DKMS will not replace this module.
You may override by specifying --force.

rtl8192de.ko:
Running module version sanity check.

Good news! Module version  for rtl8192de.ko
exactly matches what is already found in kernel 4.20.17-042017-generic.
DKMS will not replace this module.
You may override by specifying --force.

rtl8192ee.ko:
Running module version sanity check.

Good news! Module version  for rtl8192ee.ko
exactly matches what is already found in kernel 4.20.17-042017-generic.
DKMS will not replace this module.
You may override by specifying --force.

rtl8192se.ko:
Running module version sanity check.

Good news! Module version  for rtl8192se.ko
exactly matches what is already found in kernel 4.20.17-042017-generic.
DKMS will not replace this module.
You may override by specifying --force.

rtl8723ae.ko:
Running module version sanity check.

Good news! Module version  for rtl8723ae.ko
exactly matches what is already found in kernel 4.20.17-042017-generic.
DKMS will not replace this module.
You may override by specifying --force.

rtl8723be.ko:
Running module version sanity check.

Good news! Module version  for rtl8723be.ko
exactly matches what is already found in kernel 4.20.17-042017-generic.
DKMS will not replace this module.
You may override by specifying --force.

rtl8723de.ko:
Running module version sanity check.

Good news! Module version  for rtl8723de.ko
exactly matches what is already found in kernel 4.20.17-042017-generic.
DKMS will not replace this module.
You may override by specifying --force.

rtl8723-common.ko:
Running module version sanity check.

Good news! Module version  for rtl8723-common.ko
exactly matches what is already found in kernel 4.20.17-042017-generic.
DKMS will not replace this module.
You may override by specifying --force.

rtl8821ae.ko:
Running module version sanity check.

Good news! Module version  for rtl8821ae.ko
exactly matches what is already found in kernel 4.20.17-042017-generic.
DKMS will not replace this module.
You may override by specifying --force.

rtl8822be.ko:
Running module version sanity check.

Good news! Module version  for rtl8822be.ko
exactly matches what is already found in kernel 4.20.17-042017-generic.
DKMS will not replace this module.
You may override by specifying --force.

depmod...

DKMS: install completed.

```
