### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by Rda007** [lwfinger/rtlwifi_new#334]
I was trying to install the driver for rtl8723de using the rtlwifi_new but during the installation fatal error occured and it was indicating that the extended repository is not found. Please suggest the solution.
-------------*-------------*-------------*-------------*-------------*-------------*-------------*-------------*-------------*
 ~ $  sudo apt-get install linux-headers-generic build-essential git
[sudo] password for shiv: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.1ubuntu2).
git is already the newest version (1:2.7.4-0ubuntu1.3).
linux-headers-generic is already the newest version (4.4.0.116.122).
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.
~ $ git clone https://github.com/lwfinger/rtlwifi_new.git
Cloning into 'rtlwifi_new'...
remote: Counting objects: 5770, done.
remote: Total 5770 (delta 0), reused 0 (delta 0), pack-reused 5770
Receiving objects: 100% (5770/5770), 9.54 MiB | 134.00 KiB/s, done.
Resolving deltas: 100% (4765/4765), done.
Checking connectivity... done.
~ $ git checkout origin/extended -b extended
fatal: Not a git repository (or any of the parent directories): .git

**Comment by lwfinger** [comment]
I assume you closed this when you found that you had missed the 'cd rtlwifi_new' command.

**Comment by Rda007** [comment]
No i had also tried it it was showing the same error than also.Actually i didn't figure out the problem but i closed this issue because I manually downloaded the repository from github.com
