### ISSUE TITLE
Driver unstable

### ISSUE THREAD

**Issue by Rda007** [lwfinger/rtlwifi_new#335]
I have installed the driver for rtl8723de. But every time I restart the laptop I have to run
sudo modprobe rtl8723de in order to have wifi.
please suggest any permanent fix for this.

**Comment by lwfinger** [comment]
I guess you closed this when you discovered that you had not issued the 'sudo make install' command.

**Comment by Rda007** [comment]
No actually the problem was that I had ndiswrapper installed in my system and it was blocking the installation.
