### ISSUE TITLE
Error for wireless request "Set Mode" (8B06) :

### ISSUE THREAD

**Issue by fire-fly** [lwfinger/rtlwifi_new#336]
Hi
I had the error above when executing 
iwconfig wlx7c8bca0afb2b mode Monitor
Error for wireless request "Set Mode" (8B06) :
    SET failed on device wlx7c8bca0afb2b ; Invalid argument.

I am using TP-Link WN722N on
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

Linux ubuntu 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

I tried iwconfig wlx7c8bca0afb2b mode monitor, the errors were the same.

Please help

**Comment by lwfinger** [comment]
The utility iwconfig is obsolete, and these drivers do not support it. The modern utility is iw, which can be difficult to use, but it is what you need to use.
