### ISSUE TITLE
Error with modprobe rtl8821ae @4.15.7 & 4.15.8

### ISSUE THREAD

**Issue by skywalker89** [lwfinger/rtlwifi_new#337]
Dear lwfinger,

your drivers work great (rtl8821ae) for me until kernel 4.15.7 ... am no linux crack, so perhaps I miss something (am on fedora and to get all the software I needfor make install was aready a guess game for me)
So, all works all fine on 4.15.6 (using right now)
but when updating to 4.15.7, the RTL8821ae stopped working. And modprobe gives me an error I don't understand

.... rtlwifi_new]# make install
make -C /lib/modules/4.15.8-300.fc27.x86_64/build M=/home/dan/rtlwifi_new modules
make[1]: Entering directory '/usr/src/kernels/4.15.8-300.fc27.x86_64'
  Building modules, stage 2.
  MODPOST 15 modules
make[1]: Leaving directory '/usr/src/kernels/4.15.8-300.fc27.x86_64'
Install rtlwifi SUCCESS
[root@asus-f555 rtlwifi_new]# modprobe -r rtl8821ae
[root@asus-f555 rtlwifi_new]# modprobe rtl8821ae
modprobe: ERROR: could not insert 'rtl8821ae': Exec format error

any idea?
THank you so much
Dan

**Comment by skywalker89** [comment]
since no one seems to have an idea, I deleted all and restarted the process ... now it work with 4.15.8

**Comment by lwfinger** [comment]
No one has an idea because if you do it right, it works.
