### ISSUE TITLE
git checkout origin/extended -b extended fails

### ISSUE THREAD

**Issue by tkalfaoglu** [lwfinger/rtlwifi_new#339]
The command that README states gives the following error:
$ git checkout origin/extended -b extended
warning: refname 'origin/extended' is ambiguous.
warning: refname 'origin/extended' is ambiguous.
fatal: Ambiguous object name: 'origin/extended'.

**Comment by lwfinger** [comment]
What does 'git branch -a' yield?

**Comment by tkalfaoglu** [comment]
$ git branch -a
* extended
  master
  origin/extended
  remotes/origin/HEAD -> origin/master
  remotes/origin/extended
  remotes/origin/kernel_version
  remotes/origin/master
  remotes/origin/rock
  remotes/origin/rock.new_btcoex
  remotes/origin/test
  remotes/origin/troy

**Comment by lwfinger** [comment]
You have checked out the correct branch. Just "make && sudo make install:.
