### ISSUE TITLE
Kernel 4.13.9-300: Unknown symbols

### ISSUE THREAD

**Issue by tkalfaoglu** [lwfinger/rtlwifi_new#340]
After compiling and installing the rtl8822be module I attempted to use it, and I get:
$ sudo modprobe rtl8822be
modprobe: ERROR: could not insert 'rtl8822be': Unknown symbol in module, or unknown parameter (see dmesg)

dmesg:
[ 2847.762107] phydm_mod: Unknown symbol show_it_bb (err 0)
[ 2847.762122] phydm_mod: Unknown symbol rtl_get_hal_edca_param (err 0)
[ 2847.762150] phydm_mod: Unknown symbol _rtl_dbg_trace (err 0)
[ 2847.762159] phydm_mod: Unknown symbol show_it_mac (err 0)

PS: I'm currently unable to switch to newer kernels due to display driver issue.

**Comment by lwfinger** [comment]
Did you reboot?

**Comment by alukin** [comment]
You should unload all rtl* modules  because some "old" modules are loaded insteda of "new" ones and those modules do not have required symbols. Or better reboot

**Comment by tkalfaoglu** [comment]
I did a "make install" in rtlwifi_new and rtlwifi_new-extended folders. It completed successfully. 
I rebooted, and noticed that the wifi was absent from NetworkManager as before.
A manual modprobe rtl8822be resulted in the same error message.

**Comment by lwfinger** [comment]
For some reason, you have a stale versions of rtlwifi and rtl_pci loaded. Do you have any other wifi devices? This problem has been reported, but I cannot duplicate it.

Please tell me that you did NOT do the make as root. That is a very bad idea!!!!

Please do  the following as your normal user:
make clean
make
sudo make install
find /lib/modules -name rtl8822be*

Post the resulting output. If the "make clean" fails because of privilege errors, then you m\will need to "sudo make clean" to fix the mistake of running "make" as root.

**Comment by tkalfaoglu** [comment]
Many thanks.. Ooops, I sometimes do things as root whereas I shouldn't.
sudo chown -R turgut:turgut *
make clean
make 
sudo make install
make -C /lib/modules/4.13.9-300.fc27.x86_64/build M=/home/turgut/rtlwifi_new modules
make[1]: Entering directory '/usr/src/kernels/4.13.9-300.fc27.x86_64'
  Building modules, stage 2.
  MODPOST 19 modules
make[1]: Leaving directory '/usr/src/kernels/4.13.9-300.fc27.x86_64'
Making backups
Install rtlwifi SUCCESS
$ find /lib/modules -name rtl8822be*
/lib/modules/4.13.9-300.fc27.x86_64/kernel/drivers/net/wireless/realtek/rtlwifi/rtl8822be

Rebooting to test it now..

**Comment by tkalfaoglu** [comment]
DONE, thank you so much! This time success.. the wireless is working!
Thank you all so much for your help!

**Comment by lwfinger** [comment]
That "Making backups" line in your output tells me that you had never run the "sudo make install" before.

At one time in the past, the Linux kernel build system had a bug that did no damage if you were a normal user, but it destroyed /dev/null if you were building as root. The possibility of such happenings quickly taught me NEVER to run at higher privilege than absolutely necessary. As I told my class this week, "sudo" is the most dangerous command in Linux.
