### ISSUE TITLE
Ubuntu 16.04 LTS - rtl8723be - Kernel 4.15.3

### ISSUE THREAD

**Issue by LumiteDubbz** [lwfinger/rtlwifi_new#349]
Hi,
I am having difficulties with my WiFi. In a different issue opened by another user, I read that I should install from the `extended` branch, which I did and finally got WiFi; but with incredibly horrible range (approx. 2.5m before disconnection). You said to update the Kernel to 4.15.3 and use the driver pre-installed in that version and specifically not to use this repo's drivers. I updated but still do not have wireless connection. Can you please offer any support?

Thanks in advance.

**Comment by LumiteDubbz** [comment]
Yes, I did try changing the selected antenna to 1 and 2 but neither affected my outcome.

**Comment by lwfinger** [comment]
Did you do a cold reboot between tests of ant_sel values?  Unless the power is removed from the chip, you will get incorrect readings.

**Comment by LumiteDubbz** [comment]
Yes, I ran `sudo modprobe rtl8723be ant_sel=1` and then `sudo reboot`. Same with 2. I managed to get the WiFi working by just pulling the repo again, cleaning and making but with still bad signal. I can get about 5m away before disconnect.

**Comment by lwfinger** [comment]
It must be a cold reboot. Do a shutdown, let the machine set for 15 seconds, and then reboot. In addition, you either need to blacklist rtl723be so that it cannot load, or you need to create a conf file in /etc/modprobe.d/ that contains the ant_sel option. The key is that the driver must not load with an incorrect setting. If it does, then the test will not be conclusive.

**Comment by LumiteDubbz** [comment]
Holy guacamole! I gave up and just dealt with only being able to use my laptop in my living room and only via ethernet in school but by pure chance, this exact issue was in my 'frequently visited' section on Firefox. I decided to open it and I read the fix by @YUDHPK and it worked! <3
