### ISSUE TITLE
rtl8723de on a HP Notebook, hp17bs086nf

### ISSUE THREAD

**Issue by Pskalou** [lwfinger/rtlwifi_new#350]
Hello, 
when I start my laptop, I have, some time to time, this error : 
  ```
[   24.460063] rtl8723de: error H2C cmd because of Fw download fail!!!
[   24.460075] WARNING: CPU: 0 PID: 185 at /home/sylviegege/rtlwifi_new/rtl8723de/fw.c:233 rtl8723de_fill_h2c_cmd+0x1bd/0x640 [rtl8723de]
```

And then, I have to wait 2 minutes before the boot stops.

Do you have any idea ?

Thanks a lot for your job,
PsKalou

**Comment by lwfinger** [comment]
As I provide this driver as a service, but I do not have an example of this device, I'm not sure how much help I can be.

The message indicates that you do not have the correct firmware available. What is the output of 
md5sum /lib/firmware/rtlwifi/*8723de
On my system, I get
984e05af120b2e080e4bd5ac65dcf4f9  /lib/firmware/rtlwifi/rtl8723defw.bin

**Comment by Pskalou** [comment]
it's the same : 
```
# md5sum /lib/firmware/rtlwifi/rtl8723defw.bin 
984e05af120b2e080e4bd5ac65dcf4f9  /lib/firmware/rtlwifi/rtl8723defw.bin
```

**Comment by lwfinger** [comment]
Then I have no further suggestions. You will need to debug this yourself.

**Comment by lwfinger** [comment]
Be aware that you will have a long wait. I would not expect rtl8723de in the kernel for at least a year.

If you can set up your laptop on a wired connection and enable ssh so that I could log into it, then I might be able to help.

**Comment by st2135** [comment]
I have the same problem. Here is some information from dmesg which may be related to the issue.
[dmesg.log](https://github.com/lwfinger/rtlwifi_new/files/1944793/dmesg.log)

**Comment by lwfinger** [comment]
Unfortunately, you started the dmesg output after the problem happened. Pleas post the entire output of the dmesg command.

**Comment by lwfinger** [comment]
The Realtek engineer tested the extended branch and found no problems with his computer and device. To see what might be wrong with yours, he has requested additional information. Please post the output of
sudo lspci -s 03:00.0 -xxxx

In addition, please do the following:
sudo modprobe -rv rtl8723de
sudo modprobe -v rtl8723de.ko debug_level=3

Post the console output for those two and the new output of the dmesg command.

Thanks.

**Comment by st2135** [comment]
```
$ sudo modprobe -rv rtl8723de
rmmod rtl8723de
rmmod rtl_pci
rmmod rtl8723_common
rmmod btcoexist
rmmod phydm_mod
rmmod rtlwifi
rmmod mac80211
rmmod cfg80211

$ sudo modprobe -v rtl8723de debug_level=3
insmod /lib/modules/4.16.2-gentoo/kernel/net/wireless/cfg80211.ko 
insmod /lib/modules/4.16.2-gentoo/kernel/net/mac80211/mac80211.ko 
insmod /lib/modules/4.16.2-gentoo/kernel/drivers/net/wireless/realtek/rtlwifi/rtlwifi.ko 
insmod /lib/modules/4.16.2-gentoo/kernel/drivers/net/wireless/realtek/rtlwifi/rtl_pci.ko 
insmod /lib/modules/4.16.2-gentoo/kernel/drivers/net/wireless/realtek/rtlwifi/rtl8723com/rtl8723-common.ko 
insmod /lib/modules/4.16.2-gentoo/kernel/drivers/net/wireless/realtek/rtlwifi/btcoexist/btcoexist.ko 
insmod /lib/modules/4.16.2-gentoo/kernel/drivers/net/wireless/realtek/rtlwifi/phydm/phydm_mod.ko 
insmod /lib/modules/4.16.2-gentoo/kernel/drivers/net/wireless/realtek/rtlwifi/rtl8723de/rtl8723de.ko ant_sel=2 debug_level=3 
```
[dmesg.log](https://github.com/lwfinger/rtlwifi_new/files/1945769/dmesg.log)
[lspci.log](https://github.com/lwfinger/rtlwifi_new/files/1945770/lspci.log)

**Comment by lwfinger** [comment]
The Realtek person added some debugging statements in branch debug. Check it out, build and run it, and post the dmesg output again.

Thanks.

**Comment by AvirahJ** [comment]
RTL8723DE Bluetooth support seems to be working with kernel 4.17-rc2. I guess the fix is pulled to the kernel. Currently, I'm away from the machine, will report, if BT is working with latest kernel 4.17-rc* : https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=907f84990924bf3a8d248c040dabeb5127ae6938

**Comment by Pskalou** [comment]
Hello again and thanks for your answers

> RTL8723DE Bluetooth support seems to be working with kernel 4.17-rc2. I guess the fix is pulled to the kernel. Currently, I'm away from the machine, will report, if BT is working with latest kernel 4.17-rc* : https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=907f84990924bf3a8d248c040dabeb5127ae6938

Do you think it could debug my `rtl8723de: error H2C cmd because of Fw download fail!!!` error ?

@lwfinger said : 
> The Realtek person added some debugging statements in branch debug. Check it out, build and run it, and post the dmesg output again.

I can do that. But i need help : 
 * where is the realtek debug branch ?
 * should I uninstall anything before building and running ?

Thanks
PsKalou

**Comment by st2135** [comment]
Sorry for the late response. Here is the log you requested.
[dmesg3.log](https://github.com/lwfinger/rtlwifi_new/files/1958119/dmesg3.log)

**Comment by pkshih** [comment]
You may try ips=0 to check if it's helpful to avoid BUG message.
$ sudo modprobe -v rtl8723de debug_level=3 ips=0
