### ISSUE TITLE
Is the driver still working for rtl8723be?

### ISSUE THREAD

**Issue by shafique-md18** [lwfinger/rtlwifi_new#355]
First of all thanks for all your hardwork. I recently updated my machine to Ubuntu 18.04 and suddenly I lost my wifi signal. The settings show that wifi adapter not found, I tried reinstalling many times. The wifi shows up for some boots and then suddenly goes away. I have this similar issue on linux mint 18.03 when I updated the machine this morning. Is it just me who is having this problem or the wifi card isn't supported anymore?
I have not modified any system/Kernal. This issue persists even if I do a fresh install and update the machine. `lspci` does not show my wifi card anymore. Even after installing your driver the issue does not go away. Please help.

**Comment by lwfinger** [comment]
Yes, the driver is still in the kernel. It is extremely rare that a driver is taken out of the kernel, and then only if it is no longer maintained by someone. That is not the case here.

If your device no longer shows up in lspci, then you have hardware problems. It may be as simple as a contact problem in the base connector of the wireless card, or as complicated as a defective motherboard. Opening the case and re-seating the card will check the first option.

For your information: At startup, the kernel does a bus scan similar to the one performed by lspci to find the devices. For each one it finds, it installs the driver that has that PCI ID in its tables. If the device is not seen, or if some error causes the card to readout the wrong PCI ID, then the driver will never be loaded. Even manually loading the driver does nothing.

**Comment by shafique-md18** [comment]
Thanks for your time. I recovered from the issue. I was on a stable release of the kernel and hadn't updated it. I dont know how but after updating the kernel to some later release than the os release itself and then installing the drivers made my adapter recognizable again.
