### ISSUE TITLE
Make it available through AUR

### ISSUE THREAD

**Issue by Kompwu** [lwfinger/rtlwifi_new#358]
It's a pain to reinstall the drivers every time the kernel gets updated.
I know there is already one available but it only install/update driver for rtl8812ae.

**Comment by lwfinger** [comment]
WTF is AUR, and why should I support it. If you want the drivers rebuilt automatically, then implement dkms. The configuration file is already available.

**Comment by Kompwu** [comment]
@lwfinger AUR is Arch linux's repository.
Can you give me instructions to install it via dkms ?

**Comment by lwfinger** [comment]
I know nothing of Arch. Check with their experts.

**Comment by Kompwu** [comment]
@lwfinger dkms is the same as a normal "linux"...
Can you give me instructions to install it via dkms ?
I tried but i failed.
