### ISSUE TITLE
RTL8723DE installed without errors, but it has small radius

### ISSUE THREAD

**Issue by deadunicorn666** [lwfinger/rtlwifi_new#359]
There's my installation commands:

git clone https://github.com/lwfinger/rtlwifi_new.git
cd rtlwifi_new
git checkout extended
sudo make install
sudo modprobe -r rtl8723de
sudo modprobe rtl8723de

Please, help me

**Comment by lwfinger** [comment]
If you really did a 'sudo make install' without doing a "make", you have a lot of files in your directories that belong to root. If you get permissions problems in the future, that is the reason.

 Is this an HP laptop? If so, they have a habit of supplying laptops with only one antenna, which is OK, except that the programming in the EFUSE selects the wrong connector.

Please run the command 
sudo iw dev wlan0 scan | egrep "SSID|signal"

If your wireless device is not called wlan0, then substitute the correct value.

Next, run "sudo edit /etc/modprobe.d/50-rtl8723de.conf' and add a line that says "options rtl8723de ant_sel=1". After you create this file, do a complete shutdown. The power MUST be off!! Then reboot, and rerun the scan command above. If the signal improves from less than -70 to something bigger than -40, then you are done. If the signal does not improve, edit /etc/modprobe.d/50-rtl8723de.conf and change the selected antenna to 2. Repeat. If that does not help, post the output of the scan commands for your AP.

**Comment by deadunicorn666** [comment]
It works with ant_sel=2. Thanks a lot!
