### ISSUE TITLE
make install doesn't work properly on Fedora 21

### ISSUE THREAD

**Issue by vatral** [lwfinger/rtlwifi_new#36]
I compiled, ran make install, depmod -a, and got this:

    $ sudo modprobe rtl8723be
    modprobe: ERROR: could not insert 'rtl8723be': Unknown symbol in module, or unknown parameter (see  dmesg)

dmesg said:

    [   87.689767] rtl_pci: Unknown symbol rtl_proc_remove_one (err 0)
    [   87.689970] rtl_pci: Unknown symbol rtl_proc_add_one (err 0)

Looking at what modprobe is doing shows the problem:

    $ sudo modprobe --show-depends rtl8723be
    insmod /lib/modules/3.18.7-200.fc21.x86_64/kernel/net/rfkill/rfkill.ko.xz 
    insmod /lib/modules/3.18.7-200.fc21.x86_64/kernel/net/wireless/cfg80211.ko.xz 
    insmod /lib/modules/3.18.7-200.fc21.x86_64/kernel/net/mac80211/mac80211.ko.xz 
    insmod /lib/modules/3.18.7-200.fc21.x86_64/kernel/drivers/net/wireless/rtlwifi/rtlwifi.ko.xz 
    insmod /lib/modules/3.18.7-200.fc21.x86_64/kernel/drivers/net/wireless/rtlwifi/rtl_pci.ko 
    insmod /lib/modules/3.18.7-200.fc21.x86_64/kernel/drivers/net/wireless/rtlwifi/btcoexist/btcoexist.ko.xz 
    insmod /lib/modules/3.18.7-200.fc21.x86_64/kernel/drivers/net/wireless/rtlwifi/rtl8723be/rtl8723be.ko 

There is a mix of different versions of the modules. This is because Fedora 21 turns out to ship compressed module files, and make install fails to overwrite them:

    $ rpm -ql kernel-modules-3.17.4-301.fc21.x86_64 | head
    /lib/modules/3.17.4-301.fc21.x86_64/kernel/drivers/atm/atmtcp.ko.xz
    /lib/modules/3.17.4-301.fc21.x86_64/kernel/drivers/atm/eni.ko.xz

So "make install" needs getting fixed to detect this, and install .ko.xz versions instead when running on Fedora 21, at least.

**Comment by lwfinger** [comment]
What branch of rtlwifi_new are you using?

The Makefile already tests for the presence of the compressed modules in the destination directory and sets a flag. The only possibility is that Fedora uses some other shell than /bin/sh. I just committed a change that will force that shell, at least for the master branch.

**Comment by vatral** [comment]
Oh, I see now. Fixed it for you
