### ISSUE TITLE
AUR package for extended branch

### ISSUE THREAD

**Issue by Feanor1397** [lwfinger/rtlwifi_new#360]
Created AUR package for easy installation of extended version of drivers with fix for 8723de low signal. Check it out [rtlwifi_new-extended-dkms](https://aur.archlinux.org/packages/rtlwifi_new-extended-dkms)

**Comment by Kompwu** [comment]
@Feanor1397 Hi, can you do the same thing for the master branch please ?

**Comment by Feanor1397** [comment]
@Kompwu , There is already rtlwifi_new-dkms package for master branch.

**Comment by Feanor1397** [comment]
@Kompwu, ok I'll make new one when I will be at home

**Comment by Kompwu** [comment]
@Feanor1397 Thanks mate !

**Comment by Feanor1397** [comment]
@Kompwu, try this one. https://github.com/Feanor1397/rtlwifi_new-dkms

**Comment by Feanor1397** [comment]
What is lplot working? Making package? Dkms? Loading module? Post any
errors here. Also what wifi have you?

пт, 1 июня 2018, 2:26 Kompwu <notifications@github.com>:

**Comment by Kompwu** [comment]
@Feanor1397 `makepkg` fail on blacklist-rtlwifi_new-dkms.conf
No more error, it just fail...

**Comment by Feanor1397** [comment]
Err, Its not my pkgbuild. Clone my repo from link above and run makepkg frome there.
```
git clone https://github.com/feanor1397/rtlwifi_new-dkms.git
cd rtlwifi_new-dkms
makepkg -si

**Comment by Kompwu** [comment]
@Feanor1397 Nothing works with your.
Even unistall is broken. but install pass.

**Comment by Kompwu** [comment]
@Feanor1397 We should debug [this](https://github.com/WBad/rtlwifi_new-dkms) one instead.
