### ISSUE TITLE
rtl8723be on Ubuntu 18.04

### ISSUE THREAD

**Issue by GitPaean** [lwfinger/rtlwifi_new#363]
Thanks for the great contribution to providing the fix for the annoying wifi problem related to Realtek wireless chips. 

My laptop is Lenovo Y50-10. I used to use the drivers in this repo under ubuntu 16.04. Recently, it installed ubuntu 18.04, it looks like it does not work as good as before. I tried a lot of options, so far, with the drivers on the master branch of this repo, the following options
```
options rtl8723be fwlps=N ips=N 
```
work the best. Wifi will be okay after waking up from sleep/suspend, while the wifi might disconnect from time to time, then I either reboot the computer or `sudo service network-manager restart`. 

It is not terrible, and it is still a problem, since I work a lot remotely connecting to the workstation in my office, imagining a long programming running interrupted by a disconnected internet. 

Any comments or suggestions will be much appreciated.  If the problem continues, I might have to reinstall the ubuntu 16.04.

**Comment by lwfinger** [comment]
Most of the problems with RTRL8723BE are actually the fault of the computer manufacturers. Those changes in the "ps"  settings are giving you the placebo effect! Measure the signal strength using

sudo iw wlan0 scan | egrep "SSID|signal"

If your device is not wlan0, adjust accordingly. If the signal is smaller than -60, then Lenove screwed you. You need to search for rtl8723be + ant_sel.

**Comment by GitPaean** [comment]
> sudo iw wlan0 scan | egrep "SSID|signal"

This command looks like showing the wifi in the range, the one I am connected to is -14 dbm, it should be okay, right?

`iwconfig` also show the connection is -14dbm.

**Comment by GitPaean** [comment]
I tried with `ant_sel` to be 0, 1 and 2. It does not looks like it causes big difference in the signal level.

**Comment by GitPaean** [comment]
Maybe something different from Ubuntu 18.04 causes my problem. I will try a little bit more, if the problem persists, I might install the 16.04 back. Thanks for the response.

**Comment by EnverOsmanov** [comment]
@GitPaean  
If you are still using Ubuntu 18.04, could you please run `service wpa_supplicant status` and check if you have log as this one every second:

> июл 10 09:31:19 enver-W65-67SB wpa_supplicant[18178]: wlp3s0: CTRL-EVENT-SCAN-FAILED ret=-95 retry=1
> июл 10 09:31:20 enver-W65-67SB wpa_supplicant[18178]: wlp3s0: CTRL-EVENT-SCAN-FAILED ret=-95 retry=1
> июл 10 09:31:21 enver-W65-67SB wpa_supplicant[18178]: wlp3s0: CTRL-EVENT-SCAN-FAILED ret=-95 retry=1
My issues are fixed by restarting wpa_supplicant service, but this logs are annoying.

**Comment by Lewiscowles1986** [comment]
Just a note. The readme suggests I shouldn't compile this, but it is the only thing that rescued my WiFi in Ubuntu 18.04 running 4.18 kernel. I even made a StackOverflow post on it to signpost others. Thank you for publishing this. Would you be open to receiving a PR for the docs?

**Comment by Lewiscowles1986** [comment]
I also got this

```
sudo iw wlp3s0 scan | egrep "SSID|signal"
	signal: -34.00 dBm
	SSID: VM856309-2G
	signal: -62.00 dBm
	SSID: SKY88D62
	signal: -86.00 dBm
	SSID: TALKTALKA37108
	signal: -64.00 dBm
	SSID: TNCAP4A5ABF
	signal: -70.00 dBm
	SSID: ITALK-059984
	signal: -70.00 dBm
	SSID: powe067215
	signal: -68.00 dBm
	SSID: VM5105635
		 * SSID List
	signal: -66.00 dBm
	SSID: belkin.dba
```

Funny thing is that my signal is showing full-bars.

**Comment by lwfinger** [comment]
With kernel 4.18, it should not be necessary to use an external driver.

Note that -34 dBm is quite a strong signal. The power approximately doubles for every increase of 3 dBm.. Given that the noise level is -90 dBm, the signal should be about 400 times more powerful than the noise. Why would you not get full bars? Which AP are you wanting to use?
