### ISSUE TITLE
can not use git checkout extended

### ISSUE THREAD

**Issue by Feitan07** [lwfinger/rtlwifi_new#365]
git checkout extended
fatal: Not a git repository (or any of the parent directories): .git

what can i do?

**Comment by lwfinger** [comment]
Did you do a "git clone" followed by a "cd" to the correct directory?

**Comment by taskmaster2502** [comment]
Try 
**git clone https://github.com/lwfinger/rtlwifi_new.git -b extended
Make
Sudo make install 
Reboot
