### ISSUE TITLE
rtl8723be + 4.16.13-2 gives "error H2C cmd because of Fw download fail!!" on boot

### ISSUE THREAD

**Issue by fireio** [lwfinger/rtlwifi_new#367]
Otherwise the internet works fine.
OS: Archlinux
[dmesg.txt](https://github.com/lwfinger/rtlwifi_new/files/2086618/dmesg.txt)

**Comment by pkshih** [comment]
I sent patches applied to v4.17, and they will be expected to fix this error.
Maybe, you can help to try v4.17-rc1 on next Sunday.

**Comment by fireio** [comment]
Do you mean that I should test v4.18-rc1?

**Comment by pkshih** [comment]
Oops! You're right.

**Comment by fireio** [comment]
I didn't try 4.18rc1 yet, but now my system fails to boot with 4.17.2
It is due to kernel oops, I think this is related to realtek drivers

[journal.txt](https://github.com/lwfinger/rtlwifi_new/files/2116642/journal.txt)

Can you please take a look and confirm if this is the case? Thanks

**Comment by fireio** [comment]
I can boot with 4.18rc1 Although there is an oops due to rtl here too, but this one seems different.
[dmesg.txt](https://github.com/lwfinger/rtlwifi_new/files/2117152/dmesg.txt)
[journalctl.txt](https://github.com/lwfinger/rtlwifi_new/files/2117153/journalctl.txt)

**Comment by pkshih** [comment]
This issue is very similar to rtl8723de in another thread.
Can you build rtlwifi by yourself? 
If so, please apply following [sync.patch](https://github.com/lwfinger/rtlwifi_new/files/2117439/sync.txt) to v18-rc1.

**Comment by fireio** [comment]
It seems this patch doesn't apply to v4.18-rc1.
$ git checkout v4.18-rc1
...
HEAD is now at ce397d215ccd Linux 4.18-rc1
$ git apply /tmp/sync.txt
error: patch failed: drivers/net/wireless/realtek/rtlwifi/base.c:484
error: drivers/net/wireless/realtek/rtlwifi/base.c: patch does not apply
error: patch failed: drivers/net/wireless/realtek/rtlwifi/base.h:121
error: drivers/net/wireless/realtek/rtlwifi/base.h: patch does not apply
error: patch failed: drivers/net/wireless/realtek/rtlwifi/core.c:196
error: drivers/net/wireless/realtek/rtlwifi/core.c: patch does not apply
error: patch failed: drivers/net/wireless/realtek/rtlwifi/pci.c:2377
error: drivers/net/wireless/realtek/rtlwifi/pci.c: patch does not apply
error: patch failed: drivers/net/wireless/realtek/rtlwifi/ps.c:71
error: drivers/net/wireless/realtek/rtlwifi/ps.c: patch does not apply
error: patch failed: drivers/net/wireless/realtek/rtlwifi/usb.c:1132
error: drivers/net/wireless/realtek/rtlwifi/usb.c: patch does not apply

Could you give me a different patch?

**Comment by pkshih** [comment]
Try to rename "sync.txt" to "sync.patch", and remove "apply.orig" and "apply.rej" if exist in root of kernel tree.
Then, try git apply again.

It seems that "sync.txt" isn't correctly processed by git, but suddenly I try again, it works!? I am not clear why.

**Comment by fireio** [comment]
The patch which you've sent also unintentionally tries to patch /scripts/depmod.sh
If I remove line 108 to 117 of the patch, the diff for the depmod.sh script. It works!
Will let you know what happens once I compile with this.

**Comment by fireio** [comment]
It worked. I tested twice just to be sure.
[dmesg.1.txt](https://github.com/lwfinger/rtlwifi_new/files/2118763/dmesg.1.txt)
[journalctl.1.txt](https://github.com/lwfinger/rtlwifi_new/files/2118765/journalctl.1.txt)
[dmesg.2.txt](https://github.com/lwfinger/rtlwifi_new/files/2118769/dmesg.2.txt)
[journalctl.2.txt](https://github.com/lwfinger/rtlwifi_new/files/2118768/journalctl.2.txt)
Thanks for the help!

**Comment by pkshih** [comment]
Thank you!
Could you provide your name and e-mail to attach "Tested-by: your_name <your_email>" in footer of commit log?

**Comment by fireio** [comment]
Name: Shivam Kakkar
Email: shivam543@gmail.com
