### ISSUE TITLE
Driver needed for rtl8821ce

### ISSUE THREAD

**Issue by divyanksingh** [lwfinger/rtlwifi_new#368]
When can we expect the driver for rtl8821ce to come out.

**Comment by aliyoge** [comment]
I also have this problem. 
Someone had provide one, but the bluetooth in rtl8821ce can't drived in linux.

**Comment by wavilen** [comment]
https://github.com/endlessm/linux/tree/master/drivers/net/wireless/rtl8821ce

but 5Ghz and bluetooth don't work

**Comment by lwfinger** [comment]
Why did you post this here? That is not my repo. Complain there.
