### ISSUE TITLE
rtl8723be: fix driver in upstream (can't establish connection)

### ISSUE THREAD

**Issue by AltS1** [lwfinger/rtlwifi_new#369]
I have a problem which is sort of similar to "rtl8821ae keep alive not set, connection lostlogin". With kernel <=4.9 it's possible to connect to specific WiFi AP but on 4.10 - 4.17-rc7 NetworkManager tries, than gives up. Tested ib Ubuntu 18.04 & Debian 9 with kernel 4.15.
At the moment driver from here works perfectly while it contains almost the same code (compared folder rtl8723be from this repo and Ubuntu's 4.15), and both contain that latency workaround. So probably something is still missing.
I tried to apply rest of the changes from commit 196972510a4d4280b6773398f7f43609c66f8c35 (rtl8723be: Add L1 latency to rtl8723be) but that didn't help.
Could you please tell me what else can I test? I'd like to have this problem fixed in upstream.

**Comment by pkshih** [comment]
Try module parameter ant_sel=0, 1, 2. 
So you have to edit a file called /etc/modprobe.d/50-rtl8723be.conf whose content looks like "options rtl8723be ant_sel=X".

Once you change value of ant_sel, reboot your laptop before next step.

Then, check AP's signals by shell command
`sudo iw dev wlp2s0 scan | egrep "SSID|signal"`

You will know which ant_sel is suitable for you.

**Comment by AltS1** [comment]
`sudo modprobe -rf rtl8723be`
`sudo modprobe rtl8723be ant_sel=2 `- don't see most AP
ant_sel=0, ant_sel=1, fwlps=0 and other options - accepts password but can't connect.
So I believe it's a different issue.
With driver from this repo connects instantly & works well without any options.

**Comment by pkshih** [comment]
To diagnose this issue, you need to do some experiments and report results and logs.
Without any information, I can't say it's different or not.
Or you decide to use this repo. That is ok for me.

**Comment by AltS1** [comment]
Please explain, what I need to provide.

**Comment by pkshih** [comment]
As I mentioned, try ant_sel=0, 1, 2 and report your results.

You can follow the steps of wiki page:
[How to choose ant_sel for weak signal?](https://github.com/lwfinger/rtlwifi_new/wiki/How-to-choose-ant_sel-for-weak-signal%3F)

**Comment by AndrewVanAllen** [comment]
I am also having issues with this specific card. I am getting connectivity, but upon loading anything, it cannot resolve the URL or IP address. I will attempt to see if using the various `ant_sel` options makes a difference and report back.

**Comment by AltS1** [comment]
Tried Ubuntu's mainline 4.17.3 and WiFi connects now with ant_sel=0 & ant_sel=2.
On 4.15 & 4.16 AP didn't even show up with ant_sel=2 (now they don't show up with ant_sel=1).

**Comment by lwfinger** [comment]
The reason for the change in ant_sel has been discussed many times.

**Comment by AltS1** [comment]
Ok, as this issue was fixed upstream &  this discussion came to the dead, can we at least have hope for this changes to land into major distros that don't use LTS kernel (Ubuntu, SUSE)?

**Comment by lwfinger** [comment]
The fix was annotated with a "Cc: Stable", which is what is needed for it to be backported to older kernels. If your distro does not pick up those fixes, that is not my problem. BTW, my distro, openSUSE, does have this fix.I do not know about what happens with the SLE versions controlled by SUSE. Those are not in my radar.
