### ISSUE TITLE
RTL8822BE LEDs for HP Probook 455 G5 aren't behaving as expected

### ISSUE THREAD

**Issue by ryu0** [lwfinger/rtlwifi_new#374]
I am using a kernel with the staging version of this driver, and the LED for the wireless toggle key is either always on or blinking. I am guessing that the driver is using it as an activity light of sorts. I was expecting it to behave the same as the Windows version of the driver for this ProBook, which causes the LED to only turn on if the wireless is toggled off. Is there a way to make the LED behavior configurable for these types of machines? Thanks.

**Comment by pkshih** [comment]
There is no way to configure LED behavior currently. 
I'm curious that toggle wireless key would turn on/off wireless devices including wifi and BT, right?
Why do you need LED indicates the status? Just expect the behave the same as Windows?

**Comment by ryu0** [comment]
I don't really *need* it to do this, but it is what several other drivers are already doing. The intel and atheros drivers have module parameters to control how the wireless LED is used. It just seemed like something that would be nice to have for the sake of consistency.

**Comment by lwfinger** [comment]
That is the benefit of open source. If you want some feature, then prepare a patch for the mainline kernel and submit it through the usual process as outlined in the Documents tree of the kernel source.

As none of my machines even have an active LED for their PCIe devices, I would have no means of testing such code.
