### ISSUE TITLE
kernal heade not found

### ISSUE THREAD

**Issue by faisal29** [lwfinger/rtlwifi_new#375]
Hello, I get an error on the code : dkms build rtlwifi-new/0.6

Error! echo
Your kernel headers for kernel 4.17.6-1.el7.elrepo.x86_64 cannot be found at
/lib/modules/4.17.6-1.el7.elrepo.x86_64/build or /lib/modules/4.17.6-1.el7.elrepo.x86_64/source.

Help.......

**Comment by lwfinger** [comment]
You absolutely MUST install the headers before you can build any external modules. As you do not state what distro you are using, I have no suggestions. Consult the distro's forums for help on this/

**Comment by faisal29** [comment]
Hi I'm using centos7

**Comment by lwfinger** [comment]
http://ask.xmodulo.com/install-kernel-headers-linux.html seems to be a start.
