### ISSUE TITLE
Small issue in the readme

### ISSUE THREAD

**Issue by kitesurf** [lwfinger/rtlwifi_new#377]
the correct name for the option configuration file is 

 /etc/modprobe.d/<<YOUR WIRELESS DRIVER CODE>>_options.conf

For my Ubuntu 18.04 on an HP - Pavillon with rtl8723be works the next line:

`options rtl8723be swenc=0 ips=1 swlps=0 fwlps=1 msi=0 ant_sel=2`

this is all on default and just forcing the use of the antenna number 2.
Thanks a lot for this fine work

**Comment by imyxh** [comment]
I don't think this is true. The modprobe.d manpage states that "**all files** underneath the /etc/modprobe.d directory which with the .conf extension specify those options as required."

As far as I know, the filename does not matter as long as it is valid and ends in .conf.
