### ISSUE TITLE
No WiFi networks show up

### ISSUE THREAD

**Issue by taskmaster2502** [lwfinger/rtlwifi_new#380]
I  the driver for rtl8723de on my arch Linux with kernel 4.17 . I got the WiFi option but no active connections show up.

**Comment by pkshih** [comment]
Follow the wiki page [How-to-choose-ant_sel-for-weak-signal%3F](https://github.com/lwfinger/rtlwifi_new/wiki/How-to-choose-ant_sel-for-weak-signal%3F) to see if it works for you.

**Comment by KaushikDutta1984** [comment]
If ur getting wifi option this means driver is working...may be ur providing wrong credentials.

**Comment by taskmaster2502** [comment]
Thanks for the help . It's working now.
