### ISSUE TITLE
Kali Linux stuck after installing rtl8723de drivers

### ISSUE THREAD

**Issue by KaushikDutta1984** [lwfinger/rtlwifi_new#381]
Hi

iv installed kali linux with on HP 15bs-180tx laptop default 4.15 kernel.i update kernel to 4.16 n installed wifi drivers in it.Now kernel 4.16 is stuck just before login screen while kernel 4.15 is working fine.Only difference between the two kernel is wifi driver.i v tried debian 9, parrot, n kali all have the same issue.only ubuntu is working with rtl8723de drivers.
please help as i am stuck in this issue for few months.

Regards
Kaushik Dutta

**Comment by lwfinger** [comment]
Without an error message associated with being "stuck", there is little I can do.

Have you done a new 'git pull'? Some problems are fixed there.

**Comment by KaushikDutta1984** [comment]
i m using 3 months old code ..ok ill pull new source.. n then update
you..actually thr are none errors shown as bootlogd hav been removed from
debian..only the x session hangs n m not able to log in...even termimal
session are not available..anyways ill update you after installing new code

Thanks
