### ISSUE TITLE
Low signal Strength of WiFi for rtl8723de drivers on HP Notebook - 15-bs180tx and Centos 7

### ISSUE THREAD

**Issue by nileshcool** [lwfinger/rtlwifi_new#383]
The installation of the driver on HP Notebook - 15-bs180tx Laptop was successful, and now the WiFi is working fine, even I can switch the laptop in Airoplane Mode also, no problem their.
But the problem is that, the signal strength on the Laptop is very low, I have to keep my Mobile within centimetre's (not Metre) range for the laptop to catch the signal.
I have tested the signal strength on Windows 10, with drivers available from HP site, with those drivers the signal strength is very good, so the problem should be with drivers. Please suggest how this problem can be solved.

**Comment by lwfinger** [comment]
You need to read https://github.com/lwfinger/rtlwifi_new/wiki/How-to-choose-ant_sel-for-weak-signal%3F. This problem arises because HP only installed a single antenna but encoded the EFUSE to indicate that it is connected to the other connector.
