### ISSUE TITLE
spam of kern.log with pcieport errors, link with RTL8723BE?

### ISSUE THREAD

**Issue by Naziel** [lwfinger/rtlwifi_new#386]
Hello,

We notice that many ubuntu users (it seems that's not specific to Ubuntu but I'm on Ubuntu French forum) with RTL8723BE card have this in their kern.log and syslog:
`[ 2127.064322] pcieport 0000:00:1c.4:    [ 0] Receiver Error         (First)
[ 2127.064360] pcieport 0000:00:1c.4: PCIe Bus Error: severity=Corrected, type=Physical Layer, id=00e4(Receiver ID)
[ 2127.064363] pcieport 0000:00:1c.4:   device [8086:9d14] error status/mask=00000001/00002000
[ 2127.064366] pcieport 0000:00:1c.4:    [ 0] Receiver Error         (First)
[ 2127.064445] pcieport 0000:00:1c.4: PCIe Bus Error: severity=Corrected, type=Physical Layer, id=00e4(Receiver ID)
[ 2127.064448] pcieport 0000:00:1c.4:   device [8086:9d14] error status/mask=00000001/00002000
[ 2127.064451] pcieport 0000:00:1c.4:    [ 0] Receiver Error         (First)
[ 2127.064505] pcieport 0000:00:1c.4: PCIe Bus Error: severity=Corrected, type=Physical Layer, id=00e4(Receiver ID)
[ 2127.064508] pcieport 0000:00:1c.4:   device [8086:9d14] error status/mask=00000001/00002000
[ 2127.064515] pcieport 0000:00:1c.4:    [ 0] Receiver Error         (First)
[ 2127.064555] pcieport 0000:00:1c.4: PCIe Bus Error: severity=Corrected, type=Physical Layer, id=00e4(Receiver ID)
[ 2127.064559] pcieport 0000:00:1c.4:   device [8086:9d14] error status/mask=00000001/00002000
[ 2127.064562] pcieport 0000:00:1c.4:    [ 0] Receiver Error         (First)
[ 2127.064589] pcieport 0000:00:1c.4: PCIe Bus Error: severity=Corrected, type=Physical Layer, id=00e4(Receiver ID)
[ 2127.064592] pcieport 0000:00:1c.4:   device [8086:9d14] error status/mask=00000001/00002000
[ 2127.064595] pcieport 0000:00:1c.4:    [ 0] Receiver Error         (First)`

8086:9d14 is the intel bridge and 0000:00:1c.4 is the RTL8723BE card. So we think that RTL8723BE driver sends many errors fastly which fill hard drives. 
Until this bug is fixed, we use pci=noaer or pci_aspm=off but it has drawbacks
We tried with the driver of rtlwifi_new and with the driver included in the kernel, the same problem appears.
I don't know if it's specific to RTL8723BE card or if it's more general. 
I'm on 4.4 kernels (so Ubuntu 16.04.1) and I have no problems and I have the RTL8723BE card.
So maybe it's related with 4.13 or 4.15 kernels (I didn't noticed this problem on French Ubuntu forum with 4.4 kernels)

**Comment by Naziel** [comment]
We tried with aspm=0, there is no change. We also tried with theses couples of parameters: 
ips=0 fwlps=0 swlps=0 msi=1
ips=0 fwlps=0 swlps=0 msi=0

When we do
`sudo modprobe -r rtl8723be`
the problem totally disappears. So this is this module which sends these errors.

On my pc, I tried Ubuntu 16.04.3 and 18.04.1 and I have no errors logged, and there is a RTL8723BE card but not the 8086:9d14 intel bridge. All of the persons on the Ubuntu French forum which have the problem have a skylake architecture, I have a Haswell architecture. 

Another problem is that we can't go to a live session of Ubuntu 18.04.1 because of these errors. Maybe we could boot with modprobe.blacklist=rtl8723be on 18.04.1, we will try today

**Comment by lwfinger** [comment]
I provide this repo as a service; however, it does not appear that you are even using these drivers, but are using the ones in the Ubuntu distribution.

This problem, with a complete description including exact kernel version, should be posted to the linux-kernel@vger.kernel.org and linux-wireless@vger.kernel.org. That way the experts on Skylake architecture and Realtek wireless hardware will see the report.

**Comment by Naziel** [comment]
Ok, I will send a mail to theses two groups. 
Thank you for your help and all your work on Realtek card's (especially for the rtl8723be card)!

**Comment by rafaeldalbosco** [comment]
I have the same problem besides that error the CPU stays at 100% when loading the RTL8723BE
