### ISSUE TITLE
rtl8192ee very slow with hostapd

### ISSUE THREAD

**Issue by kanyck** [lwfinger/rtlwifi_new#387]
Hi!
Trying to set up AP on a PCI-E realtek card...
Throughput is only about 1.2 Mbit/s
kernel 4.14.52-0-vanilla 64bit, driver is upstream (I guess it's the same here)
What is strange -- I cannot set fwlps to 0 (I guess it may help): modprobe -v passes the parameter, but modinfo says
```
filename:       /lib/modules/4.14.52-0-vanilla/kernel/drivers/net/wireless/realtek/rtlwifi/rtl8192ee/rtl8192ee.ko                                                                     
firmware:       rtlwifi/rtl8192eefw.bin
description:    Realtek 8192EE 802.11n PCI wireless
license:        GPL
author:         Larry Finger    <Larry.Finger@lwfinger.net>
author:         Realtek WlanFAE <wlanfae@realtek.com>
alias:          pci:v000010ECd0000818Bsv*sd*bc*sc*i*
depends:        rtlwifi,rtl_pci,btcoexist,mac80211
retpoline:      Y
intree:         Y
name:           rtl8192ee
vermagic:       4.14.52-0-vanilla SMP mod_unload modversions
parm:           swenc:Set to 1 for software crypto (default 0)
 (bool)
parm:           ips:Set to 0 to not use link power save (default 1)
 (bool)
parm:           swlps:Set to 1 to use SW control power save (default 0)
 (bool)
parm:           fwlps:Set to 1 to use FW control power save (default 1)
 (bool)
parm:           msi:Set to 1 to use MSI interrupts mode (default 1)
 (bool)
parm:           debug_level:Set debug level (0-5) (default 0) (int)
parm:           debug_mask:Set debug mask (default 0) (ullong)
parm:           disable_watchdog:Set to 1 to disable the watchdog (default 0)
```
Any suggestions?

**Comment by lwfinger** [comment]
Why do you think that passing a parameter should change modinfo? That information comes from macros defined in the driver. That is what you get whether the driver is loaded, or not! It is fixed at build time.

I also have questions as to why you think that fwlps should affect the speed. If you think link power save is causing a slowdown in the setup, you would be much better off setting ips=0 and turning power save completely off. Your AP and clients will use more power that way.

**Comment by kanyck** [comment]
Oh! Thanks for your  reply! 
Passing ips=0 fwlps=0 is the most common advice I could find on the web about realtek driver. ips=0 did work for me, raising speed from ~60kbps to ~1.2mbps, but it is still way too slow.
I don't really care about power consumption, but I wander if I'm able to get a decent speed on this chip.
I specifically bought TP-Link TL-WN881ND card hoping it is still Atheros-based as it used to be and as stated on wikidevi, but unfortunately it appears realtek-based.
Could you suggest how can I squeeze the max out of 8192, or should I opt for some used Atheros card instead?

**Comment by lwfinger** [comment]
Are you talking about a Realtek USB chip? If so, then it is not an RTL8192EE, which is strictly a PCIe chip. The device designation is RTLuuuumb. The unit type (uuuu) and the model (m) tell the chip type, and the "b" tells the bus type: E for PCI, U for USB, and S for SDIO.

**Comment by kanyck** [comment]
No, it's a PCI-E board, so RTL8192EE is accurate and that's what I see in lspci output.

**Comment by kanyck** [comment]
Double-checked everything I could, including wired connection to make sure there's no interference.
The device:
```
03:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8192EE PCIe Wireless Network Adapter
        Subsystem: Realtek Semiconductor Co., Ltd. Device 8196
        Kernel driver in use: rtl8192ee
```
Station dump from the server side while doing a speed check (server -> client):
```
Station 14:d6:4d:49:68:a4 (on wlan0)                                                                                                                                                   
        inactive time:  0 ms                                                                                                                                                           
        rx bytes:       363005                                                                                                                                                         
        rx packets:     2229                                                                                                                                                           
        tx bytes:       27878793                                                                                                                                                       
        tx packets:     19755                                                                                                                                                          
        tx retries:     0                                                                                                                                                              
        tx failed:      0                                                                                                                                                              
        rx drop misc:   2                                                                                                                                                              
        signal:         10 dBm                                                                                                                                                         
        signal avg:     -42 dBm                                                                                                                                                        
        tx bitrate:     300.0 MBit/s MCS 15 40MHz short GI                                                                                                                             
        rx bitrate:     1.0 MBit/s                                                                                                                                                     
        authorized:     yes                                                                                                                                                            
        authenticated:  yes                                                                                                                                                            
        associated:     yes                                                                                                                                                            
        preamble:       long                                                                                                                                                           
        WMM/WME:        yes                                                                                                                                                            
        MFP:            no                                                                                                                                                             
        TDLS peer:      no                                                                                                                                                             
        DTIM period:    2                                                                                                                                                              
        beacon interval:100
        short slot time:yes
        connected time: 3049 seconds
```
300Mbit channel is kept permanently as long as the transmission persist, yet the real data speed is still at least 15-20 times less -- never exceeds 1.2Mbps. What surprises me is no tx retries are listed at all (I never seen one during 2-days experiments). 
Another strange things are that ping times are varied from 2 to 2000ms and signal strength measurements vary a lot as you can see, including even positive values while normally about -35dB.

**Comment by harish2309** [comment]
I have the exact same issue with the same device TP-Link TL-WN881ND. After troubleshooting for the better part of my day I just gave up. I have tried everything  the OP has done and more and it did not work.

Windows 10 mobile Hotspot gives me 40mbit on a 50mbit connection while Linux is at 5mbps. It never ever crosses that. Welp guess I'm stuck to using Doze for now.

I know it's 4 months old, but I'll be glad if someone can take a look at this.

Driver - RTL8192EE.

**Comment by lwfinger** [comment]
What speed do you get from the RTL8192EE working as an STA?

**Comment by kanyck** [comment]
As for me, I never managed to get above 1.2 Mbit/s, while station dump reports 300:))

**Comment by harish2309** [comment]
Okay, thanks for looking into it. I know it's not a paid product I'm using, so I appreciate all the help I can get. If I ever find a way to fix this issue I'll share it here. 

Thank you and keep doing your great work with the drivers.

**Comment by yagoplx** [comment]
Hello. I just bought the WN881ND device to use as an AP and ran into this problem. 

I want to try with the vendor drivers (8192eu.ko) but they don't seem to compile.

**Comment by lwfinger** [comment]
This thread is about the RTL8192EE, which is a PCI device, Why are you asking questions about the RTL8192EU, which is a USB device? That last letter in the device name is the key.

All of the drivers in the repo came from the vendor and have been modified to build with current kernels.

**Comment by yagoplx** [comment]
I am talking about the RTL8192EE device, TP-Link just uses the 8192e driver from realtek compiled with PCI support. It still ends up being called 8192eu.ko

**Comment by yagoplx** [comment]
Wait, what?
Looks like the docs were just examples... oops. Nevermind, I don't know what I am talking about.

**Comment by lwfinger** [comment]
:)

**Comment by MrKich** [comment]
Why was that issue closed?

**Comment by lwfinger** [comment]
Because the conversation got way off topic. In addition, the last on-topic conversation was almost one year ago. Re-open it again if the complaint is still valid; however, I need some numbers. A +1 comment is not useful.

**Comment by xDShot** [comment]
Have TP-Link wifi card with the chipset having too slow hotspot speed.
