### ISSUE TITLE
Building in tree can cause issues

### ISSUE THREAD

**Issue by samnazarko** [lwfinger/rtlwifi_new#39]
Hi

I am using this repository to build in tree with a Raspberry Pi. 

While I notice no Kconfig, I wanted to still highlight a few things that could be improved to facilitate kernel building:
- Makefile -- the current Makefile seems to always build PCI support. If this isn't enabled in the kernel (no need to for Pi), this can cause issues at the LD stage.

The upstream Makefile in the kernel tree works better as it is adapted for this.
- Warnings as errors -- to build I must turn off implicit function declaration warnings and implicit integer warnings. These are both defaults in the kernel.

**Comment by lwfinger** [comment]
This repo is not designed for in-kernel building for several reasons.

1. No RPi has PCI buses and most of these drivers are for PCI devices.
2. The intent of this repo is for the PCI devices.
3. We do not have access to the kernel configuration variables.
4. The only USB driver has very few changes from the kernel version.

If you want to build this rtl8192cu driver in the Pi's kernel, then copy all the .c and .h files in the rpos root directory into drivers/net/wireless/rtlwifi/. Then copy the .c and .h found in rtl8192c*/ into the corresponding directories in drivers/net/wireless/rtlwifi/.

**Comment by samnazarko** [comment]
I am building for more than just Raspberry Pi, and some of these platforms do have PCI, so we will benefit from those changes.

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
