### ISSUE TITLE
RTL8821ae failed to detect

### ISSUE THREAD

**Issue by satishwagh** [lwfinger/rtlwifi_new#391]
Hello, 

I am using kernel version 4.17. This kernel detects and loads module **rtl8821ae**. Wireless device works perfectly fine. But after certain reboots, this device fails to "**UP**". It always remains in "**DOWN**" state. 
**dmesg** says

> rtl8821ae: Init MAC failed (Multiple lines)
> rtl8821ae 0000:02:00.0: Refused to change power state. Currently in D3
> rtlwifi: RTL8XXX not boot from eeprom. Check it!
> 

On next reboot, this device even fails to detect into "**lspci**".
I need to unplug and plug the power cable of system to make this device work again.

I had used many kernel version from _4.15 _till_ 4.18.2._
Also used github tarball and git clone, but all of them showing same issue.

Do I have to set any specific parameter while loading relevant kernel module ? (aspm=0)

**Comment by lwfinger** [comment]
No, but any error messages in the output of dmesg are critical. When it happens, please post that output in some pastebin location and report the URL here.

If lspci cannot see  the device, that means that the basic low-level scan of the PCI busses is failing, which will prevent loading this driver. No module parameter can possibly have an effect! That hints of a hardware fault caused by something not initializing correctly. Have you done a motherboard update recently?

If you do a cold boot - complete shutdown for a minute or so - without unplugging the power cable, does that fix the problem?

Does this problem happen with 4.18.5?

**Comment by satishwagh** [comment]
Sure. I will post the dmesg output.

No. Motherboard is as clean as it is from factory.

No. Even we have waited for 8+ hours after cold boot-complete shutdown.

I have to try with 4.18.5. I will update you immediately after I conduct the test.

**Comment by satishwagh** [comment]
I tried with 4.18.5 but with no difference. Still having same issue. dmesg output is attached [here](https://pastebin.com/raw/89UpTrmy)

**Comment by lwfinger** [comment]
The error message was not terribly informative, but I did see a couple of other things:

You should probably fix the seqfault arising from
udevd[370]: IMPORT{builtin}: 'firmware' unknown /lib/udev/rules.d/50-udev-default.rules:88

I have no idea what is wrong with the touchscreen driver to cause this, but crashing udevd is not a good idea.
 
 While I figure out what sort of debug options should be used, I have a couple of other options to try by doing the following:

sudo modprobe -rv rtl8821ae
sudo modprobe -v rtl8821ae aspm=0 msi=1

I have seen some other instances where Lenovo motherboards have required tweaking. The msi parameter may not change anything as your boot line has "pci=nomsi". Is that something you added? If not, where did that come from?

**Comment by satishwagh** [comment]
I had tried above commands way before.

When the said error occurred, I removed the module and inserted again with **"aspm=0"** only.
if I do this then on next reboot, I do not have to power-off and power-on the machine again and wifi device starts working as normal.

But when this error occur, wifi device will not work till I reboot with either
**(1) Module removal and insertion again OR
(2) Power-off and Power-on the system again.**

_Touchscreen_ is an in-house component, which I think we can ignore for time being. 

_UDEV segfault_ was caused by missing firmware binary. I will try to rectify it. But I am sure, that has nothing to do with wifi problem.

**Comment by lwfinger** [comment]
You need to make an options file in /etc/modprobe.d/50-rtl8821ae.conf with one line saying
"options rtl8821ae aspm=0" and reboot. Then the aspm will be set every time.

**Comment by satishwagh** [comment]
Yes. This is my current configuration since last two week. 
But still after certain reboot (say 12), this **Init MAC Failed** error occurs and then if I do __cat /sys/module/rtl8821ae/parameters/aspm__, it returns **1**.
And rest of the time, when wifi device works normally, aspm returns **0**

None is doing anything to Rtl8821ae except udev/kernel. 

Is there any way to track down this sudden change in file?

**Comment by lwfinger** [comment]
I have no idea what could be overriding the options file. You might ask this kind of question in the linux kernel mailing list.
