### ISSUE TITLE
RTL8723BE is unable to connect to certain WiFi networks in Manjaro

### ISSUE THREAD

**Issue by ayan-b** [lwfinger/rtlwifi_new#392]
I use an HP laptop having Manjaro Deepin OS running in kernel 4.18.1. After changing the ant_set to 1 the signal is restored, but now it is unable to connect to certain WiFi networks. It may be noted that -
- I dual boot this with Windows 10, and there is no problem with WiFi connections in Windows 10.
- For certain WiFi connections, the WiFi never gets connected, and for others even if it gets connected the speed is slow.

Please guide me in solving this issue. Let me know if any additional information is required.

**Comment by lwfinger** [comment]
You need to provide any information that appears in the dmesg output when it fails.

**Comment by ayan-b** [comment]
I get the following output:
```
[  679.050900] wlo1: authenticate with a0:63:91:b4:ca:c0
[  679.540394] wlo1: send auth to a0:63:91:b4:ca:c0 (try 1/3)
[  679.643209] wlo1: send auth to a0:63:91:b4:ca:c0 (try 2/3)
[  679.646311] wlo1: authenticated
[  679.649893] wlo1: associate with a0:63:91:b4:ca:c0 (try 1/3)
[  679.655494] wlo1: RX AssocResp from a0:63:91:b4:ca:c0 (capab=0x421 status=0 aid=2)
[  679.655703] wlo1: associated
[  679.656191] IPv6: ADDRCONF(NETDEV_CHANGE): wlo1: link becomes ready
[  725.085433] wlo1: deauthenticating from a0:63:91:b4:ca:c0 by local choice (Reason: 3=DEAUTH_LEAVING)
```
PS: The connection I am trying to connect to is Open and in I get `Unable to connect to [connection name], please keep closer to the router`, although the network strength is close to 100%.

**Comment by lwfinger** [comment]
I'm not sure why you need to obfuscate the SSID of a connection. There are a lot of reasons why you get a Reason 3 disconnect. To verify that you do indeed have a strong signal, please run the following command:

sudo iw dev wlo1 scan | egrep "SSID|signal"

Post the output for the AP you are trying to connect to.

**Comment by lwfinger** [comment]
OK, the TP-LINK_7COE strength is -26 dBm, which is quite good.

Why does NETGEAR-11ng show up twice? One has strength -40 dBm, which is satisfactory, and one with -64 dBm. Connecting to the latter would show the disconnects you are seeing.

Please run this command

sudo iw dev wlo1 scan | egrep "\(on|SSID|signal"

That will show the MAC addresses of those two AP's. If you would rather not post those on an open list, send them to Larry.Finger@lwfinger.net.

**Comment by ayan-b** [comment]
@lwfinger I have sent you the mail.

**Comment by lwfinger** [comment]
OK. If you are using NetworkManager, then the system should settle on the strongest signal for that SSID. Have you forced a particular BSSID? If so, that would prevent roaming to the best AP.

As far as I can tell, this is not a problem with the driver, but there is something wrong with your user-space code. You could verify this by running a recent live version of either Fedora or openSUSE. I recommend those two as I have had several reports of the Debian-based systems having NetworkManager problems.

**Comment by ayan-b** [comment]
Ok, thanks a lot! :blush:
