### ISSUE TITLE
Exec format error on Ubuntu.

### ISSUE THREAD

**Issue by ediasep** [lwfinger/rtlwifi_new#393]
After applying update on Ubuntu, the wifi often not working. The solution is simply re-install the rtlwifi_new. 

`cd ~/rtlwifi_new && sudo make install && sudo modprobe -r rtl8723de && sudo modprobe`

But currently i cannot get it working because of this error when installing it. 

`make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-33-generic'
Making backups
Install rtlwifi SUCCESS
modprobe: ERROR: could not insert 'rtl8723de': Exec format error`

**Comment by lwfinger** [comment]
If you update the kernel, the old version of an out-of-kernel driver will not work. That is known!

The "Exec format error" result from building the driver with kernel headers that do not match the running kernel. Why is that? I see you doing a "sudo make install" without doing a "make". Thus, you are installing and trying to load drivers for the old kernel, not the new one. You cannot skip a step.

**Comment by lwfinger** [comment]
If you want me to pay any more attention to this, you must provide actual computer output for the commands, and what errors are listed in the output of the dmesg command!

**Comment by lwfinger** [comment]
You should install one of the set of "install libelf-dev, libelf-devel or elfutils-libelf-devel", whichever is available on your distro.

I would also like to see the output of 'uname -r', lsmod, and 'lspci -nn'.

You should always use 'sudo modprobe -v xxxx' when installing modules xxxx. The resulting output shows which kernel directory is being used when inserting the module.

If you have installed the module, and have not blacklisted it, then the module should already be loaded after boot. A modprobe should not be needed at that point.

**Comment by ediasep** [comment]
@igagankalra Try to use fresh clone of the `rtlwifi_new` folder, then execute all those commands again. It is working for me now.

**Comment by igagankalra** [comment]
I tried all these commands again and this time I get error `sudo modprobe -v rtl8723de
insmod /lib/modules/4.15.0-43-generic/kernel/drivers/net/wireless/realtek/rtlwifi/rtl8723de/rtl8723de.ko ant_sel=X 
modprobe: ERROR: could not insert 'rtl8723de': Invalid argument
`
Still I can't install it @ediasep 
And here is the output you want @lwfinger 
[lsmod output.txt](https://github.com/lwfinger/rtlwifi_new/files/2724464/lsmod.output.txt)

![lspci-nn](https://user-images.githubusercontent.com/22219148/50648038-2adfba00-0fa0-11e9-88c0-7c74de8ee327.png)

` uname -r
4.15.0-43-generic
`

**Comment by lwfinger** [comment]
Your lsmod shows the following modules loaded:
btcoexist             434176  0
phydm_mod             856064  0
rtl8723_common         24576  0
rtl_pci                32768  0
rtlwifi               163840  4 rtl_pci,btcoexist,phydm_mod,rtl8723_common

BUT, 'modprobe -v' does not show these being loaded!!! Run the command
find /lib/modules/$(uname) -name rtl_pci.ko

If you see this file in any other directory than /lib/modules/4.15.0-43-generic/kernel/drivers/net/wireless/realtek/rtlwifi/, then you need to delete the one that is in a different directory, as well as any other of the list above in that same directory.

**Comment by niranjan7777** [comment]
basically you have to reinstall rtlwifi_new.
so first you have to remove it 
use following commands

 rm -rf rtlwifi_new/  or  sudo rm -rf rtlwifi_new/

next get it clone   : 

git clone https://github.com/lwfinger/rtlwifi_new.git

change directory:

cd rtlwifi_new/

now change branch: 

git checkout origin/extended -b extended 

next:

sudo make install 

sudo modprobe -r rtl8723de

sudo modprobe rtl8723de

(you will see wifi is running here)

if signal is weak 

sudo modprobe -r rtl8723de && sleep 5 && sudo modprobe rtl8723de ant_sel=2

**Comment by lwfinger** [comment]
I have a couple of comments. You can replace two commands:
git clone https://github.com/lwfinger/rtlwifi_new.git
git checkout origin/extended -b extended

with
git clone https://github.com/lwfinger/rtlwifi_new.git -b extended

"sudo modprobe -r rtl8723de && sleep 5 && sudo modprobe rtl8723de ant_sel=2" may not work. Some chips need to be powered down to accept a new value for ant_sel. Better to create a file /etc/modprobe.d/50-rtl8723de.conf containing a single line "options rtl8723de ant_sel=2". and then do a shutdown for 15 sec and then restart.

**Comment by raxraj** [comment]
All you have to do is reinstall the package.
this happens because you updated ubuntu !!
Just reinstall it , Start from removing it !!

**Comment by skeletonkey** [comment]
You can also simply run `sudo make clean` instead of have to delete the repo and checking it out again.  Then move onto the rest of the steps.

Thanks for the information - should have thought of that, however, I needed to be reminded ... again :P
