### ISSUE TITLE
Installing issues

### ISSUE THREAD

**Issue by elkface** [lwfinger/rtlwifi_new#396]
I'm trying to install the driver for my kali linux dual boot (My machine is an asus k570UD-ES76)  and after getting the extended repository and running the make install without any errors:

make -C /lib/modules/4.17.0-kali1-amd64/build M=/root/rtlwifi_new modules
make[1]: Entering directory '/usr/src/linux-headers-4.17.0-kali3-amd64'
  Building modules, stage 2.
  MODPOST 19 modules
make[1]: Leaving directory '/usr/src/linux-headers-4.17.0-kali3-amd64'
Install rtlwifi SUCCESS

 when I try to use modprobe:

modprobe rtl882be

I get this:

modprobe: ERROR: could not insert 'rtl8822be': Invalid argument

Any way to fix this?

**Comment by lwfinger** [comment]
That depends on what the error is. You can find that in the dmesg output.
