### ISSUE TITLE
RTL8822BE Slow Speed [Debian/Kali]

### ISSUE THREAD

**Issue by uplusion23** [lwfinger/rtlwifi_new#399]
I've been suffering for a while trying to get through this. I've followed the steps on the README.md for the RTL8822BE on the extended branch. My wireless adapter is onboard my Asus motherboard, listed here. I'm on kernel `4.17.0-kali-amd64' which according to online, comes standard with support for RTL8822BE, but no luck. I am able to start monitor mode on wlan0, but when attempting to monitor with the aircrack-ng suite's airmon-ng, One-Two networks will appear, when there are many more in proximity. I've noticed after installation of the drivers, txpower will always be 0, unless I perform `ip link set wlan0 up` which I do not know if that is normal behavior.

**iwconfig**
```
wlan0     IEEE 802.11  ESSID:off/any  
Mode:Managed  Access Point: Not-Associated   Tx-Power=0 dBm   
Retry short limit:7   RTS thr=2347 B   Fragment thr:off
Encryption key:off
Power Management:on
```

**Motherboard**
```
Manufacturer: ASUSTeK COMPUTER INC.
Product Name: ROG MAXIMUS X HERO (WI-FI AC)
Version: Rev 1.xx
```

`lscpi` shows 
```
04:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8822BE 802.11a/b/g/n/ac WiFi adapter
```

**Comment by lwfinger** [comment]
I do not have much experience with the RTL8822BE. The first thing is to discover how strong is the received signal. Run the following command and post the output without any monitor mode, etc.:
sudo iw dev wlan0 scan | egrep "SSID|signal"

I am informed that there will be a totally new driver for RTL8822B and RTL8822C chips. As soon as it is ready, I will add it to a new branch of this repo.

**Comment by uplusion23** [comment]
Sorry for the long delay, I can't hop on too often due to lack of network. I've been able to get the drivers working now, with a fairly average signal. Most of the AP's around me are through one or two layers of wall, and my personal router is through two also, so I never expected great signal, just enough to connect. After a reboot, the driver must be re-added [via modprobe] in order to function again, but that's a just a configuration issue on my side. I'm able to scan on all channels, and I will be testing a connection shortly when I download an alternative distro, considering many resources are saying Kali is an unstable version.
