### ISSUE TITLE
rtl8188ee slow speed

### ISSUE THREAD

**Issue by Yomi0** [lwfinger/rtlwifi_new#4]
Firstly, I wasn't sure if I should have reported this on the Linux Bugzilla, since I wasn't sure if Roger was using the drivers in the kernel or from here. 

The connection speed is often very slow. 
Often times, it'll get around 250K (or higher) but usually it hovers around 30 to 70 K (or lower) 

I'm using the drivers from here, commit : 5ee581a (master)

Kernel Version : 3.16.2-1-ARCH

Here's the output from `iwconfig` : https://gist.github.com/Yomi0/d088b4c291d5d6cc8fc7#file-iwconfig

Is there any more information I can provide?

**Comment by woldie** [comment]
I am an unfortunate owner of the rtl8188ee, and I just wanted to add that switching my wireless router to 802.11g only, where previously it was 802.11g or 802.11n, seemed to do the trick for me and now I am getting stable connections that run at an okay speed with nominal signal strength.

I am running with the troy branch and not master, not sure if that was important to my success or not.  Hope this helps someone out.

**Comment by RainbowDashDC** [comment]
Let me add that I do seem to get randomly better connection speeds with my rtl8188ee. However, I still have horrible speeds at, say, my school. This has forced me into uses Windows which sucks as I prefer to not use it.

**Comment by RainbowDashDC** [comment]
The big issue is the random drops in speed, I'll be getting 5mb/s then all of a sudden nothing for a good 3-4 minutes.

**Comment by jaredallard** [comment]
This is still a major issue for me, anyone else encountering this?

**Comment by capitanbatata** [comment]
I haven't measured my connection speed. Wireless is usable, but the connection drops after using the computer for a while, and then it never connects again. However this is a separate issue.

**Comment by amenzhinsky** [comment]
ASUS UX501, RTL8192EE PCIe Wireless Network Adapter, Linux 4.4 and 4.5rc2

I had the same issue, connection was horrible, tested using `ping google.com` and it was like `30ms, 900ms, 30ms, 900ms...`, now it's stable.

Installed https://aur.archlinux.org/packages/rtlwifi_new-dkms/ and disabled powersaving 
```
$ cat /etc/modprobe.d/rtl8192ee_dkms.conf 
options rtl8192ee_dkms swlps=0 fwlps=0 ips=0
```

Is it going to be merged into mainline?

**Comment by lwfinger** [comment]
It is in mainline.

**Comment by amenzhinsky** [comment]
@lwfinger maybe I'm a little paranoid, but I've checked it twice and I see the difference clearly.
One thing that I've noticed is when using `_dkms` modules firmware is not loaded

```
Feb 04 19:08:04 homebook kernel: Using firmware rtlwifi/rtl8192eefw_new.bin
Feb 04 19:08:04 homebook kernel: rtl8192ee 0000:03:00.0: Direct firmware load for rtlwifi/rtl8192eefw_new.bin failed with error -2
Feb 04 19:08:04 homebook kernel: Firmware rtlwifi/rtl8192eefw_new.bin not available
```

Vanila Linux 4.4.
```
Feb 04 19:01:42 homebook kernel: rtl8192ee: Using firmware rtlwifi/rtl8192eefw.bin
```

**Comment by amenzhinsky** [comment]
I'll try to remove firmware and use the mainline module a little bit later.

**Comment by lwfinger** [comment]
The dkms routine, which I did not write, has a bug. It is failing to copy rtl8192eefw_new.bin to the firmware directory. To do it manually, change directory to rtlwifi_new and

sudo cp firmware/rtlwifi/rtl8192ee* /lib/firmware/rtlwifi/.

That will provide the firmware you need.

**Comment by amenzhinsky** [comment]
I have two laptops of front of me using the same access point and the difference is obvious, for example when I use ssh on the one that uses rtl8192ee I just wanna kill myself.

```
03:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8192EE PCIe Wireless Network Adapter
	Subsystem: Lite-On Communications Inc Device 8193
	Flags: bus master, fast devsel, latency 0, IRQ 136
	I/O ports at d000 [size=256]
	Memory at dd200000 (64-bit, non-prefetchable) [size=16K]
	Capabilities: [40] Power Management version 3
	Capabilities: [50] MSI: Enable+ Count=1/1 Maskable- 64bit+
	Capabilities: [70] Express Endpoint, MSI 00
	Capabilities: [100] Advanced Error Reporting
	Capabilities: [140] Device Serial Number 01-91-81-fe-ff-4c-e0-00
	Capabilities: [150] Latency Tolerance Reporting
	Capabilities: [158] L1 PM Substates
        Kernel driver in use: rtl8192ee
	Kernel modules: rtl8192ee, rtl8192ee_dkms
```

**Comment by mmstick** [comment]
Chiming in from a Gentoo laptop using rtl8188ee and Linux 4.8.0. Wifi speed is terrible, with 21% packet loss, and every second boot simply fails to detect a SSID. Seems I'm going to have to search for a USB wifi adapter, because it's the same issue every year with Realtek hardware.

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.

**Comment by sirnicholasevan** [comment]
Thank you so much!  The new drivers work great for my rtl8188ee!

**Comment by lavaed** [comment]
I use rtl8192 as an access point with hostapd. But the speed of downloaded traffic on clients does not rise more than 80kbps, and the uploaded traffic is 2Mbps. How can I fix this in the rtlwifi driver?

**Comment by lavaed** [comment]
The device on the chipset realtek rtl8192ee
