### ISSUE TITLE
installation successful, but the interface can't be rendered UP

### ISSUE THREAD

**Issue by ertosns** [lwfinger/rtlwifi_new#400]
installed rtl8723de for d723 module, it's installed in the kernel, interface mounted under /sys/class/net, and listed by ip link, but doesn't get up using ip link set interface up, the state is always DOWN, for more details https://unix.stackexchange.com/questions/469809/wireless-module-state-cant-be-rendered-up 
kernel is 4.18.8-arch1-1-ARCH, any idea why it doesn't work?

**Comment by lwfinger** [comment]
As was pointed out in the link, you need to look at the output of dmesg to find the problem.

One question - which driver are you using? That link pointed to a different GitHub repo.

**Comment by ertosns** [comment]
dmesg https://pastebin.com/yZcDmJXw, this repo ofcourse.

**Comment by lwfinger** [comment]
Are you sure that was with debug=0? Your ring buffer has wrapped and destroyed all the useful information. Reboot and regenerate the dmesg output before the early information is lost.

**Comment by ertosns** [comment]
i generated dmesg for 5 levels, and that was output to level 0, the problem seems to be with the regulatory file, but still can't resolve it.

**Comment by lwfinger** [comment]
I have no idea what you are talking about.

**Comment by ertosns** [comment]
i generated dmesg for 5 levels, and that was output to level 0, the problem seems to be with regulatory file, but still can't resolve it.

**Comment by ertosns** [comment]
follow comment discussion with telcoM here https://unix.stackexchange.com/questions/469809/wireless-module-state-cant-be-rendered-up

**Comment by ertosns** [comment]
apologies, https://pastebin.com/Q5WEwV57

**Comment by lwfinger** [comment]
That was better. The only problem is that the network connection was made through en01, the Ethernet connection, not the wireless.

I now know that the firmware is being loaded correctly, and that the driver starts without any errors.

One thing you might try is the following:
sudo modprobe -rv rtl8723de
sudo modprobe -v rtl8723de aspm=0

Some motherboards have trouble with ASPM. That option will turn it off.

**Comment by ertosns** [comment]
cfg80211, mac80211, rtlwifi, rtl_pci, rtl8723-common, phydm_mod, btcoexist, rtl8723de  are insmoded in that order, just in case.

**Comment by lwfinger** [comment]
They load in order based on their dependence. If they were out of order, you would get unsatisfied globals.

I still have not seen the dmesg output with failures. That debug info earlier is useless to me. I am not a Realtek engineer.

**Comment by ertosns** [comment]
what do you suggest, i must solve this problem, any thing to read, something to investigate, don't know what to do?

**Comment by lwfinger** [comment]
Post me the dmesg output where you actually told NetworkManager to make a connection.

**Comment by ertosns** [comment]
ip link set <interface> down && ip link set <interface> up && dmesg > /tmp/dmesg  only addes one  line [xx.xx] IPv6: ADDCONF(NETDEV_UP): wlo1 link in not ready, there is no any deauthenticaiton, and authentication going one!!

**Comment by lwfinger** [comment]
Network control is a lot easier if you let NetworkManager run the show. If you are using ip to control it, then you need the appropriate control file for wpa_supplicant, etc.

Do you have a reason not to use NM?

**Comment by ertosns** [comment]
there is absolutely no related messages in the kernel buffer ring except the same previous message "[xx.xx] IPv6: ADDCONF(NETDEV_UP): wlo1 link in not ready" between other command relating to systemd-networkd being executed, and wpa_applicant isn't effective at all, and cli scan return CTRL_EVENT_NETWORK_NOT_FOUND, currently trying different kernel, will check the difference, if there is any.
