### ISSUE TITLE
RTL8723BE still has low signal after following all the installation instructions on Hp Ubuntu 16.04

### ISSUE THREAD

**Issue by fasemoreakinyemi** [lwfinger/rtlwifi_new#404]
sudo modprobe -rv rtl8723be
rmmod rtl8723be
rmmod rtl_pci
rmmod rtl8723_common
rmmod btcoexist
rmmod rtlwifi
rmmod mac80211
rmmod cfg80211

sudo modprobe -v rtl8723be ant_sel=2
insmod /lib/modules/4.15.0-34-generic/kernel/net/wireless/cfg80211.ko 
insmod /lib/modules/4.15.0-34-generic/kernel/net/mac80211/mac80211.ko 
insmod /lib/modules/4.15.0-34-generic/kernel/drivers/net/wireless/realtek/rtlwifi/rtlwifi.ko 
insmod /lib/modules/4.15.0-34-generic/kernel/drivers/net/wireless/realtek/rtlwifi/rtl_pci.ko 
insmod /lib/modules/4.15.0-34-generic/kernel/drivers/net/wireless/realtek/rtlwifi/rtl8723com/rtl8723-common.ko 
insmod /lib/modules/4.15.0-34-generic/kernel/drivers/net/wireless/realtek/rtlwifi/btcoexist/btcoexist.ko 
insmod /lib/modules/4.15.0-34-generic/kernel/drivers/net/wireless/realtek/rtlwifi/rtl8723be/rtl8723be.ko ant_sel=2 ant_sel=2

Thanks in advance

**Comment by lwfinger** [comment]
To get an accurate reading, you MUST put the ant_sel option in /etc/modprobe.d/50-rtl8723be.conf as "options rtl8723be ant_sel=2" and then do a COLD reboot. Leave the power off for at least 15 sec. Without the reboot, the chip may not get the new parameter. Unloading and reloading the driver asyou did may not work.

You can test the strength with the following:

sudo iw dev wlan0 scan | egrep "SSID|signal"

Change "wlan0" to whatever your system is using gor the device name. If the signal for your AP is less than -70, then you have the wrong value.

**Comment by fasemoreakinyemi** [comment]
less /etc/modprobe.d/rtl8723be.conf
options rtl8723be ant_sel=2

sudo iw dev wlan0 scan | egrep "SSID|signal"
	signal: -68.00 dBm
	SSID: TP-LINK_52436E
I restarted my pc.
I don't have 50-rtl8723be.conf in my /etc/modprobe.d directory but the rtl8723be.conf

**Comment by fasemoreakinyemi** [comment]
Thanks for your support so far. I have renamed although the load options was listed with the previous name nevertheless to leave no loose ends. the condition still remains the same. I have tried ant_sel=1 but there was no change in signal quality. 

I did a very cold reboot. Shutdown the Linux logged in to windows and spent the night there only returned the next day

**Comment by lwfinger** [comment]
Did you do a cold reboot when shutting down Windows? If not, it will leave the chip ion the wrong state. That is something you will need to do EVERY time you switch from one to the other.

In the future, please provide the signal levels from every test.
