### ISSUE TITLE
modprobe: ERROR: could not insert 'rtl8822be': Exec format error in UBUNTU 18.04.1

### ISSUE THREAD

**Issue by ray26** [lwfinger/rtlwifi_new#408]
`ray@ray:~/rtlwifi_new$ sudo make install
make -C /lib/modules/4.15.0-34-generic/build M=/home/ray/rtlwifi_new modules
make[1]: 进入目录“/usr/src/linux-headers-4.15.0-34-generic”
  Building modules, stage 2.
  MODPOST 19 modules
make[1]: 离开目录“/usr/src/linux-headers-4.15.0-34-generic”
Making backups
Install rtlwifi SUCCESS
ray@ray:~/rtlwifi_new$ sudo modprobe -r rtl8822be
ray@ray:~/rtlwifi_new$ sudo modprobe rtl8822be
modprobe: ERROR: could not insert 'rtl8822be': Exec format error
`
I have seen others' issues , my step was followed by the README ,but it still occurs

**Comment by lwfinger** [comment]
You need to look at the output of dmesg to see the exact reason. The most common is not having turned off secure boot. With this repo, it is not possible to sign the module, thus if your kernel demands it, loading will fail.

**Comment by lwfinger** [comment]
man dmesg

**Comment by ray26** [comment]
I have got `exports duplicate symbol rtl_phydm_get_ops_pointer (owned by r8822be)
`

**Comment by ray26** [comment]
I have seen my Netwok cotronller was  Realtek Semiconductor Co., Ltd. Device b822 , i don't know  wheather it is the same with r8822be.
In my settings , It was said that the system can't find the network cotronller

**Comment by lwfinger** [comment]
Who said?

**Comment by ray26** [comment]
My system

**Comment by ray26** [comment]
With ifconfig
enp0s20f0u2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.42.190  netmask 255.255.255.0  broadcast 192.168.42.255
        inet6 fe80::ff79:5c1:5471:6a16  prefixlen 64  scopeid 0x20<link>
        ether 0a:06:a1:f1:b4:9c  txqueuelen 1000  (以太网)
        RX packets 418823  bytes 607102969 (607.1 MB)
        RX errors 6  dropped 0  overruns 0  frame 6
        TX packets 237662  bytes 29633122 (29.6 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

enp8s0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 8c:16:45:f1:24:db  txqueuelen 1000  (以太网)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (本地环回)
        RX packets 3701  bytes 323929 (323.9 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 3701  bytes 323929 (323.9 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by lwfinger** [comment]
On your system, type the command "dmesg | grep 8822". In addition, post the output of "lspci -nn".

**Comment by lwfinger** [comment]
I learned a little more. If you have r8822be installed, then trying to load rtl8822be from tthis repo causes the duplicate symbol. If you want to use this repo, then you need to blacklist r8822be.

**Comment by lwfinger** [comment]
That works, but it is the wrong fix. By doing that, you are giving up all the other changes/fixes in the kernel. Besides, if your kernel is new enough to contain r8822be, then there is not need for this repo and you do not have to fool around with an out-of-kernel driver.

To all the owners of RTL8822BE/CE devices: The Realtek group has written an entirely new driver for these devices. It has finished the first round of reviews. Assuming all goes well, it will be part of kernel 4.21. When it is ready, there will be a new branch here.

**Comment by pardaloupa** [comment]
Hello @lwfinger 

I have some issues with the RTL8822BE/CE Bluetooth driver on my new Thinkpad [A485](https://pcsupport.lenovo.com/uu/en/products/laptops-and-netbooks/thinkpad-a-series-laptops/thinkpad-a485-type-20mu-20mv/documentation) on Arch Linux with the latest kernel 4.18. 

Although the WiFi works out of the box the Bluetooth does not turn on at all. Any idea if it is related to Kernel fixes/changes or? I am happy to see that a new driver is being worked on, hopefully it will resolve all the issues.

Please have a look at these posts ([Lenovo forums](https://forums.lenovo.com/t5/Linux-Discussion/Thinkpad-A485-Bluetooth-not-turning-on-Linux/m-p/4219759#U4219759) & [Arch forumus](https://bbs.archlinux.org/viewtopic.php?id=240615) for some more background information.

Thank you for your time.

**Comment by gardotd426** [comment]
I have a rtl8188ee and am on Arch and updated today to kernel version 5.2.14-arch2-1-ARCH, from 5.2.14-arch1-1-ARCH. Next time I booted, the interface wasn't detected, so I tried modprobe rtlwifi, and was given an exec format error output. I ran modprobe -f, with no error message, then followed that with modprobe rtl8188ee, same error, so I ran the -f again, again no error message, iwconfig showed the interface again, pinged google and got a response, and was working as normal. I checked dmesg and it showed "rtlwifi: version magic '5.2.14-arch1-1-ARCH SMP preempt mod_unload ' should be '5.2.14-arch2-1-ARCH SMP preempt mod_unload. '" No such error message with the rtl8188ee module, just rtlwifi, but I checked modinfo and sure enough both modules showed vermagic of '5.2.14-arch1-1-ARCH SMP preempt mod_unload ' for both rtlwifi and rtl8188ee. This did not occur when upgrading from 5.2.13, just from 5.2.14-arch1-1 to 2-1. This being Arch (and only having been installed for a couple weeks), there is no option of using an earlier kernel until it's fixed or I find a fix myself, the only other kernel I have is the lts which is 4.19, and as you said just using that one for now would be the wrong solution anyway. I'm currently downloading the 5.3 release-candidate kernel to see how it works with that.

I understand that Arch is the bloodiest of the bleeding edge and that stuff like this happens. But as I said, it's not happened on any other kernel point version update, and I also run Manjaro on another partition which is a mere couple weeks behind Arch, and this has never happened in the months I've had that install running as my daily driver. I don't know jack about compiling modules, but if nothing else could you at least point me to the file/part of the source code that sets the vermagic? Failing that, I assume there's no way to edit the modinfo of the currently installed driver?

**Comment by lwfinger** [comment]
your "stream of conscious" reporting makes it extremely difficult to understand what you are reporting but the one ting i notice is that your kernel headers do not match the running kernel which is a nono for all distros not only arch.

**Comment by redopm** [comment]
> On your system, type the command "dmesg | grep 8822". In addition, post the output of "lspci -nn".

![15750381180335085979287436048955](https://user-images.githubusercontent.com/36072815/69875654-ad254b00-12e3-11ea-87d9-97c4db7d227e.jpg)

**Comment by redopm** [comment]
I have the same problems but I use rtl8723be. Send the screenshot because of laptop h no connection neither WiFi nor Ethernet cable work. Please help me

**Comment by lwfinger** [comment]
Obviously, you have the rtl8723be device. Look at the lspci output. Why are you even doing anything with rtl8822be??

**Comment by lwfinger** [comment]
Actually, if your wired connection does not work, then your networking is completely scred up. I suggest that you fix that first as the same problem will likely affect wireless. Fixing it with wireless will be a lot harder.

**Comment by redopm** [comment]
> with rtl8822be

I am trying to find maybe I have

**Comment by redopm** [comment]
> Actually, if your wired connection does not work, then your networking is completely scred up. I suggest that you fix that first as the same problem will likely affect wireless. Fixing it with wireless will be a lot harder.

how

**Comment by lwfinger** [comment]
That is a Ubuntu question. I do not answer those.
