### ISSUE TITLE
r8822be wireless network hangs once in a while, kernel 4.18.12

### ISSUE THREAD

**Issue by zerthimon** [lwfinger/rtlwifi_new#409]
In some networks it hangs once or twice a day in other networks a lot more often, like 2 times an hour. No networks can be listed when this happens. I have to disable and re-enable wifi, then it works again until it hangs. I think it happens only with 5GHz networks, but I'm not sure.

**Comment by tycho** [comment]
I'm having this same issue on 5.0.3. It seems to happen for me when doing package updates, in the middle of downloading a large-ish file.

**Comment by lwfinger** [comment]
Driver r8822be is being phased out. Please checkout branch rtw88 from this repo and test with the new driver. I have run netperf tests for many hours without a single drop.

**Comment by tycho** [comment]
@lwfinger Is it scheduled for inclusion in Linus tree?

**Comment by lwfinger** [comment]
It is in review now. Inclusion in 5.2 is a possibility, but backporting to older kernels is not a high priority, other than here.

**Comment by zerthimon** [comment]
Thanks @lwfinger I've built and installed from rtw88 branch, will report after some testing.
