### ISSUE TITLE
Changing driver Linux Backport rtlwifi and 

### ISSUE THREAD

**Issue by moxou** [lwfinger/rtlwifi_new#41]
Hello Larry
I have a Brix pro (Core i7-4770R with a pci rtl882ae wifi card (dual card wifi+bluetooth)
Using a clean ubuntu 14.04.1 Ubuntu (Linux 3.16.0-33-generic)
I've updated the rtlwifi driver with the backport version 3.19-rc1-1
I'm using the wifi to create a AP network and have the following known bug (my computer is freezing after about an hour of use)
- rtl8821ae 0000:02:00.0: swiotlb buffer is full (sz: 9100 bytes)
- DMA: Out of SW-IOMMU space for 9100 bytes at device 0000:02:00.0

It seem to work fine in infrastructure mode

I've seen that you fixed it 21 days ago (in pci.c - Unmap IOMMU after beacon transmitted)
I've tried to change the backport driver with the rtlwifi_new driver but not succeed.

(make install don't change the driver in use)

As I'm not very familiar with Linux (about 1 month of use) I just looking for some help.

Tks for working on the driver
Guillaume

**Comment by lambertdw** [comment]
If you happen to know which driver is current and which driver you want 
to use,

sudo modprobe -r driver_to_remove && sudo modprobe new_driver

I find the current driver with command
lshw

the output of which shows as follows, on the penultimate line starting 
with configuration: I see my current driver is rtl8192ee but you'll see 
the name of yours.

...
            *-network
                 description: Wireless interface
                 product: RTL8192EE PCIe Wireless Network Adapter
                 vendor: Realtek Semiconductor Co., Ltd.
                 physical id: 0
                 bus info: pci@0000:03:00.0
                 logical name: wlan0
                 version: 00
                 serial: 74:29:af:9a:21:cb
                 width: 64 bits
                 clock: 33MHz
                 capabilities: bus_master cap_list ethernet physical 
wireless
                 configuration: broadcast=yes driver=rtl8192ee 
driverversion=3.16.0-33-generic firmware=N/A ip=192.168.0.195 latency=0 
link=yes multicast=yes wireless=IEEE 802.11bgn
                 resources: irq:46 ioport:4000(size=256) 
memory:b2800000-b2803fff
...

**Comment by lwfinger** [comment]
I was here to give the same advice, but 'sudo make install' does update the version on disk. Then doing the modprobe pair will get you the new version in memory. Of course, you can also reboot.

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
