### ISSUE TITLE
makefile install targed wrong?

### ISSUE THREAD

**Issue by ohquait** [lwfinger/rtlwifi_new#410]
> all:
> 	$(MAKE) -C $(KSRC) M=$(PWD) modules
> install: all
> 	**@mkdir -p $(MODDESTDIR)/rtwlan**
> 	**@install -p -D -m 644 rtwlan.ko $(MODDESTDIR)**
> ifeq ($(COMPRESS_GZIP), y)
> 	@gzip -f **$(MODDESTDIR)/*.ko**
> endif
> ifeq ($(COMPRESS_XZ), y)
> 	@xz -f **$(MODDESTDIR)/*.ko**
> endif

mkdir -p $(MODDESTDIR)/rtwlan   --> empty folder rtwlan
install -p -D -m 644 rtwlan.ko $(MODDESTDIR) --> installing .ko to MODDESTDIR/rtwlan.ko but not to MODDESTDIR/rtwlan/rtwlan.ko

**Comment by lwfinger** [comment]
If you want a driver for RTL8723DE, you are in the wrong branch! You shoul;d be using the extended branch.
