### ISSUE TITLE
Problem with kernel 4.15.0-34 and 4.15.0-36

### ISSUE THREAD

**Issue by Paride1** [lwfinger/rtlwifi_new#412]
Hi,
I use ubuntu 16.04.01. I installed driver in my Hp with RTL8723BE PCIe Wireless Network Adapter. It works fine with kernel 4.15.0-33 but it don't work after recent update to the new kernels on the object.
I tried to recompile and install the driver but I haven't solved. 
Thanks

**Comment by KnoxZZ** [comment]
I had the same problem with Ubuntu 18.04.01. The fix i found was to update my kernel to 4.19.

**Comment by jeremyb31** [comment]
@Paride1 What errors are you seeing, Ubuntu caused their own problems in that kernel that this repo will fix, do you see any errors in results for `dmesg | grep rtl8723`

**Comment by lwfinger** [comment]
Can you point me to some repository that shows the differences between 4.15.0-33 and 4.15.0-35? It would be even better if you were to bisect between those changes and point to the exact commit that caused the problem.

There have been no changes in the driver that would cause this problem. It is a problem with the Ubuntu kernel. As such, I cannot fix it; however, it would be best if we could point to what is causing the problem.

**Comment by jeremyb31** [comment]
There is an issue with dkms.conf for the master branch as it doesn't include the rtl8723-common.ko module and it causes issues.  Might be easier to merger the extended branch to master as extended branch is correct

**Comment by Paride1** [comment]
So now is fixed in which version of kernel?

**Comment by jeremyb31** [comment]
Paride1 you should be able to use this github repo to fix the wireless now.  If you already have a rtlwifi_new folder in home just open the folder in terminal and `git pull` should incorporate the latest fixes.  Then you can install using make && sudo make install or use dkms

**Comment by Paride1** [comment]
Perfect. Now it works fine! Thank you
