### ISSUE TITLE
Wi-Fi connection drops after ~1 hour

### ISSUE THREAD

**Issue by krlk89** [lwfinger/rtlwifi_new#42]
My wifi/bt chipset is Realtek 8723BE.
I am using Ubuntu 15.04 with mainline kernel 4 and I compiled the wifi driver using the "troy" branch (I have also compiled the driver for bluetooth using the kernel branch).

Wifi used to work well with the previous Ubuntu version, but after upgrading, the connection drops about 1 hour after I connect and I have to relog to the wifi network in order to get it working again.

I have added "options rtl8723be fwlps=N ips=N to" (without quotes) to /etc/modbrobe.d/rtl8723be.conf as i did with Ubuntu 14.10.

**Comment by lwfinger** [comment]
I have no idea what Ubuntu is doing with their kernels and why it is now failing; however, some of Ubuntu's practices have caused me to stop supporting anyone that uses Ubuntu. Sorry, but they were wasting too much of my time. As a volunteer, I could see no reason to continue beating my head against the wall. Switch back to the older version of Ubintu's kernel.

**Comment by Dale-M** [comment]
I'm seeing this problem (at least one with the same symptoms) on kernel 4.1.0+. against this branch head the stand-apart rtlwifi_new head won't build at all.

**Comment by lwfinger** [comment]
Are you also a Ubuntu user? Kernel 4.1 should have the latest code; however, you should load the driver with the "ips=0" option.

**Comment by Dale-M** [comment]
Thanks for the quick reply; I am impressed.  I'm using Debian Wheezy as a base, but there is much DIY piled on top, including the kernel (the machine is Lenovo Yoga 2 13" non-pro).  I added the options the OP showed and the loss of connectivity problems have gone away.

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
