### ISSUE TITLE
RTL8723de exec format error

### ISSUE THREAD

**Issue by Lillievela** [lwfinger/rtlwifi_new#420]
I have updated various parts on my Kubuntu 18.04.1 LTS distro and after rebooting My wifi driver RTL8723DE does not work. I have tried everything to fix it but nothing seems to work

**Comment by lwfinger** [comment]
Alway report what dmesg has to say. This error usually means that the driver was not compiled with the headers and compiler used to build the kernel. Did you try 'make'?

**Comment by Lillievela** [comment]
It seems that the Headers have updated and the rtl8723de is not working with it

~/rtlwifi_new$ make
make -C /lib/modules/4.15.0-39-generic/build M=/home/lillie/rtlwifi_new modules
make[1]: Entering directory '/usr/src/linux-headers-4.15.0-39-generic'
Makefile:975: "Cannot use CONFIG_STACK_VALIDATION=y, please install libelf-dev, libelf-devel or elfutils-libelf-devel"
rm: cannot remove '/home/lillie/rtlwifi_new/.tmp_versions/btcoexist.mod': Permission denied
rm: cannot remove '/home/lillie/rtlwifi_new/.tmp_versions/rtl8188ee.mod': Permission denied
rm: cannot remove '/home/lillie/rtlwifi_new/.tmp_versions/rtl8192c-common.mod': Permission denied
rm: cannot remove '/home/lillie/rtlwifi_new/.tmp_versions/rtl8192ce.mod': Permission denied
rm: cannot remove '/home/lillie/rtlwifi_new/.tmp_versions/rtl8192cu.mod': Permission denied
rm: cannot remove '/home/lillie/rtlwifi_new/.tmp_versions/rtl8192de.mod': Permission denied
rm: cannot remove '/home/lillie/rtlwifi_new/.tmp_versions/rtl8192ee.mod': Permission denied
rm: cannot remove '/home/lillie/rtlwifi_new/.tmp_versions/rtl8192se.mod': Permission denied
rm: cannot remove '/home/lillie/rtlwifi_new/.tmp_versions/rtl8723-common.mod': Permission denied
rm: cannot remove '/home/lillie/rtlwifi_new/.tmp_versions/rtl8723ae.mod': Permission denied
rm: cannot remove '/home/lillie/rtlwifi_new/.tmp_versions/rtl8723be.mod': Permission denied
rm: cannot remove '/home/lillie/rtlwifi_new/.tmp_versions/rtl8821ae.mod': Permission denied
rm: cannot remove '/home/lillie/rtlwifi_new/.tmp_versions/rtl_pci.mod': Permission denied
rm: cannot remove '/home/lillie/rtlwifi_new/.tmp_versions/rtl_usb.mod': Permission denied
rm: cannot remove '/home/lillie/rtlwifi_new/.tmp_versions/rtlwifi.mod': Permission denied
Makefile:1538: recipe for target 'crmodverdir' failed
make[1]: *** [crmodverdir] Error 1
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-39-generic'
Makefile:87: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Lillievela** [comment]
I have managed to get back to kernel 4.15.0-38 and get wifi working again until update

**Comment by lwfinger** [comment]
You needed to install one of those three packages mentioned. The correct one will depend on how your distro packaged things.

The permission proglem arises because you have done a 'sudo make'. That is a no-no. You need to 'sudo make install', but NEVER, NEVER 'sudo make'. To recover do a 'sudo make clean', and do it right in the future.
