### ISSUE TITLE
RTL8723DE very slow or nothing at all

### ISSUE THREAD

**Issue by Lillievela** [lwfinger/rtlwifi_new#421]
No matter what i Do i am getting very low or nothing at when i use wireless connections, I have a fresh install of Kubuntu 18.04.1.

**Comment by lwfinger** [comment]
RTL8723DE also suffers from the single-antenna with an incorrectly encoded EFUSE problem. For the most part, this situation happens on HP laptops, but some other vendors are guilty. To test if this problem, please do the following command:
iw dev | grep Interface
Using the name listed such as "wlan0", enter the following:
sudo iw dev wlan0 scan | egrep "SSID|signal|\(on "
If your device is not "wlan0", make the appropriate change. Post the output from the above command.

**Comment by lwfinger** [comment]
I have written several times on how to check for antenna mismanagement caused mostly by HP. I will not do it again. You search for the instructions.

**Comment by Hyperion101010** [comment]
Hi there, sir, first of all, you are doing an amazing work with working on all these drivers and keeping them up to date. 
I do understand that you have to answer these questions time and again but mine is a bit different. I updated my kali linux to kernel 5.2 (amd64) at the same time I have Ubuntu running with same kernel in parallel (as a kernel contributor have to keep it up to date). 
So I have no problems with ubuntu but with kali my connection is flickering (always asking for password but no connection in end). This the op of my signal strength:
root@hype:/usr/bin# sudo iw dev wlan0 scan | egrep "SSID|signal| on"
	signal: -81.00 dBm
	SSID: iBall-Baton
	signal: -58.00 dBm
	SSID: Hyperions hotspot
It be really helpful if you can help me here,
good day.  keep up the good work.

**Comment by Hyperion101010** [comment]
I also tried antenna selection but no luck

**Comment by lwfinger** [comment]
Your signals are weak. How far are you from the AP? Do any walls need to be penetrated?
What signal do you get with Ubuntu?

**Comment by Hyperion101010** [comment]
No, I am holding it close to the laptop (Hyperion hotspot).  So it is working with Ubuntu and not with Kali.
Signals are same with both just in Kali the logs say time out. 
In ubuntu : 
Linux hyperion 5.4.0-rc6+ #1 SMP Tue Nov 12 01:11:31 IST 2019 x86_64 x86_64 x86_64 GNU/Linux

in kali : 
kernel 5.2 amd64

**Comment by lwfinger** [comment]
Your ant_sel tests were likely flawed. Create a file in /etc/modprobe.d/50-rtl8723de.conf with a single line "options rtl8723de ant_sel=2". After creating that file, then do

sudo modprobe -rv rtl8723de
sudo modprobe -v rtl8723de

Send me the output. Then do a complete shutdown and wait for at least 15 s with the power off. Then boot the machine and rerun the signal strength tests. At a distance of 2m, you should see a signel of -40 dBm.

**Comment by Hyperion101010** [comment]
I tried this config and is now working like charm. Thanks a lot you are the best.

**Comment by lwfinger** [comment]
Good.
