### ISSUE TITLE
rtl8723be driver issue.

### ISSUE THREAD

**Issue by harshabilla** [lwfinger/rtlwifi_new#422]
I don't know how to state my problem. I removed my windows and shifted to ubuntu recently. I got this wifi issue solved when I used ubuntu 16.04 but then I installed a update and whole thing gone. Now, I'm using ubuntu 18.10. The problem is I'm getting connected to wifi, if only my laptop is near to wifi. And in avaiable networks, I couldn't see any other wifi connections except the one which I got connected. 
I have been looking for the solution since three days. Here are the results of lshw,iwconfig and signal strength.
Please help me solve the issue. If needed anything, let me know. Thank you in advance.
harsha@harsha-HP-Notebook:~$ sudo lshw -c network
  *-network                 
       description: Ethernet interface
       product: RTL810xE PCI Express Fast Ethernet controller
       vendor: Realtek Semiconductor Co., Ltd.
       physical id: 0
       bus info: pci@0000:01:00.0
       logical name: enp1s0
       version: 07
       serial: 40:b0:34:04:f6:b5
       size: 10Mbit/s
       capacity: 100Mbit/s
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress msix vpd bus_master cap_list ethernet physical tp mii 10bt 10bt-fd 100bt 100bt-fd autonegotiation
       configuration: autonegotiation=on broadcast=yes driver=r8169 driverversion=2.3LK-NAPI duplex=half firmware=rtl8106e-1_0.0.1 06/29/12 latency=0 link=no multicast=yes port=MII speed=10Mbit/s
       resources: irq:124 ioport:4000(size=256) memory:b1200000-b1200fff memory:b1000000-b1003fff
  *-network
       description: Wireless interface
       product: RTL8723BE PCIe Wireless Network Adapter
       vendor: Realtek Semiconductor Co., Ltd.
       physical id: 0
       bus info: pci@0000:02:00.0
       logical name: wlo1
       version: 00
       serial: 3c:a0:67:79:10:3b
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress bus_master cap_list ethernet physical wireless
       configuration: broadcast=yes driver=rtl8723be driverversion=4.18.0-11-generic firmware=N/A ip=192.168.1.102 latency=0 link=yes multicast=yes wireless=IEEE 802.11
       resources: irq:17 ioport:3000(size=256) memory:b1100000-b1103fff
harsha@harsha-HP-Notebook:~$ iwconfig
enp1s0    no wireless extensions.

wlo1      IEEE 802.11  ESSID:"Yashoda2nd floor"  
          Mode:Managed  Frequency:2.412 GHz  Access Point: 0C:80:63:13:F9:9E   
          Bit Rate=150 Mb/s   Tx-Power=18 dBm   
          Retry short limit:7   RTS thr=2347 B   Fragment thr:off
          Power Management:off
          Link Quality=46/70  Signal level=-64 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:549   Missed beacon:0

lo        no wireless extensions.

harsha@harsha-HP-Notebook:~$ iwlist scan | egrep -i 'ssid|quality'
enp1s0    Interface doesn't support scanning.

lo        Interface doesn't support scanning.

                    Quality=46/70  Signal level=-64 dBm  
                    ESSID:"Yashoda2nd floor"
harsha@harsha-HP-Notebook:~$

**Comment by lwfinger** [comment]
The standard problem with HP laptops and RTL8723BE or RTL8723DE wireless devices is that HP only installs a single antenna. That would not be a problem; however, they incorrectly encode the ROM that indicates which connector they used.

I have grown very tired of repeating the same advice over and over and over and over. Do a Google search for "rtl8723be ant_sel" to find many hundreds of suggestions. If your Ubuntu version is a late one, then "ant_sel=2" is likely the correct one. The clue is the weak signal. Within a distance of 2 or 3m, the strength should be bigger than -40 dBm. Although the difference between -64 and -40 dBm may not seem like a lot, remember that it is a logarithmic scale. Each change of 10 in dBm is a fator of 10 in the power.

**Comment by harshabilla** [comment]
I actually messed with default network files. I reseted my ubuntu using this command:"dconf reset -f /" and deleted my exising "rtlwifi_new" and re-install it.
It's totally working fine!
Thank you so much, Mr Lwfinger.
and thank you for responding in time.

**Comment by Lillievela** [comment]
Another issue with drivers and Linux is that so far this is one of the only few drivers that actually work and is sometimes only limited to one kernel. The last Linux OS that i was using (Kubuntu 18.04.1 LTS) had updated and the new kernel 4.15.0-38 was the only kernel in the list that  had worked, nothing newer, nothing older. I had tried a fedora 28 install but got the same result. Its really dependent on the kernel and if you on Laptops or desktops

**Comment by lwfinger** [comment]
I do not know/care about other out-of-kernel drivers. These drivers I build and test with each new kernel version using openSUSE. If it does not work for a particular kernel and/or distro, look at the distro for problems.

**Comment by jastisriradheshyam** [comment]
> Another issue with drivers and Linux is that so far this is one of the only few drivers that actually work and is sometimes only limited to one kernel. The last Linux OS that i was using (Kubuntu 18.04.1 LTS) had updated and the new kernel 4.15.0-38 was the only kernel in the list that had worked, nothing newer, nothing older. I had tried a fedora 28 install but got the same result. Its really dependent on the kernel and if you on Laptops or desktops

Hey @Lillievela , I think when you change the kernel or update the kernel you are not recompiling the source and install it.
Drivers has to be recompiled for every major kernel version (also minor version sometimes) change for them to work.

**Comment by Lillievela** [comment]
I have tried to compile, I even tried different Distros and reinstalling, it just didn't work for me specifically.

**Comment by lwfinger** [comment]
Did you post any specific cases? If so, I missed them. "It doesn't work'" is almost always ignored as there is nothing to do.

**Comment by lwfinger** [comment]
As I have no idea what you did and you seem unwilling to provide any details, then I will just ignore you.
