### ISSUE TITLE
Bluetooth range issue rtl8723de after installing wifi driver

### ISSUE THREAD

**Issue by Harshdeep4295** [lwfinger/rtlwifi_new#425]
HI Everyone, I am facing an issue not able to get the solution yet.
I install rl8723de driver for wifi as it was unclaimed on my ubuntu machine. Now, if I work with the only Bluetooth it works perfectly fine. But if I use wifi with blue tooth my Bluetooth stops working. its like if I put my Bluetooth device on laptop keyboard it gets connected but if it goes like ~3m it stops working.

**Comment by lwfinger** [comment]
Is your laptop from HP? If so, you are likely having the problem where they only installed a single antenna, but failed to encode the ROM correctly. To determine this, run the following commands:

iw dev
sudo iw dev wlan0 scan | egrep "SSID|signal|\(on"

If the first one shows the wifi to be other than wlan0, then use that value in the 2nd command. If the signal levels are below -50 dBm, then you have the problem.

**Comment by Harshdeep4295** [comment]
If @lwfinger  when I use iw dev :- it shows me below information
phy#0
	Interface wlo1
		ifindex 3
		wdev 0x1
		addr d0:c5:d3:58:f6:8d
		ssid Abode1st spectra_2.4G
		type managed
		channel 1 (2412 MHz), width: 40 MHz, center1: 2422 MHz
		txpower 20.00 dBm
and when i execute the second one, it dowsnt do anything i guess other than making wifi signal range strong. still my bluetooth get disconnected as i connect the wifi on my device.

**Comment by wioo** [comment]
In my case download on wifi  drops by half when using bluetooth. My card is rtl8723be (hp brand laptop). Looks like hp really messed things up with the wifi card.

signal (about 4 meters away from router)
	signal: -32.00 dBm

**Comment by Harshdeep4295** [comment]
that means no solution to it...
can i change the frequency band for WiFi like for 5ghz... and Bluetooth be
remain same at it is? if it possible,?

Regards,
harshdeep singh

**Comment by wioo** [comment]
@lwfinger, I did some tests with active bluetooth (listening to some music on a2dp sink) and run speedtest.net . On linux dl speed drops as expected (becase only one antenna is available?), but the same test on windows doesnt show any drop in dl. I know you are not here for windows stuff, but how is this possible?

**Comment by lwfinger** [comment]
Obviously, we do not have all of the single-antenna issues worked out; however, I am so tired of covering for your miserable vendor that I will only handle the wifi case.

If you open your case, move the single antenna wire to the other connector, and load rtl8723de without the ant_sel option, then both wifi and BT should work. With one radio and one antenna, they will interfere, but it should not be too bad. Of course, once you move that connector, Window wifi will not work, but as you say, that is not my problem.

**Comment by wioo** [comment]
Thanks for reply. I wasnt asking for solution or anything like that (i tried both wire combinations before and it is a little better on second connector), i was just curious if  HP has some tricks implemented in their win driver. Sorry for bothering you (and I agree with you about HP).

**Comment by lwfinger** [comment]
Yes, there are tricks in the Windows driver. No, I do not know what they are.

I will never buy another HP or Lenovo laptop. Only Dell or Toshiba for me.
