### ISSUE TITLE
rtl8723be could not insert error

### ISSUE THREAD

**Issue by Abhishek-31** [lwfinger/rtlwifi_new#426]

**Comment by Abhishek-31** [comment]
Whenever I unload the modules using modprobe -r rtl8723be and then again loading it by modprobe rtl8723be, it is coming modprobe error: rtl8723be could not be inserted.

**Comment by lwfinger** [comment]
You need to tell why. That will be found in the output of dmesg. Most likely, the kernel you are running differs from the kernel headers that you compiled against.

**Comment by mahsoommoosa42** [comment]
You can disable secure boot. Otherwise, you have to generate a key. Import it using mokutil. and sign the rtlwifi Kernel modules. I've successfully managed to do this. I'm writing a bash script which would allow anyone to do the same.

**Comment by Abhishek-31** [comment]
Okay. Thanks

**Comment by mahsoommoosa42** [comment]
So, I have a found a solution. Hopefully, Larry can, later on, integrate this into the project. 

First steps first, you need to create a private key (.priv) and a certificate file (.der). I'm very new to secure boot signing. So, I apologise for my crude use of terminologies. 

Creating a certificate for use in UEFI Secure Boot is relatively simple. openssl can do it by running a few SSL commands. Now, we needs to create a SSL certificate for module signing…

First, let’s create some config to let openssl know what we want to create (let’s call it `‘openssl.cnf’):
`# This definition stops the following lines choking if HOME isn't
# defined.
HOME                    = .
RANDFILE                = $ENV::HOME/.rnd 
[ req ]
distinguished_name      = req_distinguished_name
x509_extensions         = v3
string_mask             = utf8only
prompt                  = no

[ req_distinguished_name ]
countryName             = CA
stateOrProvinceName     = Quebec
localityName            = Montreal
0.organizationName      = cyphermox
commonName              = Secure Boot Signing
emailAddress            = example@example.com

[ v3 ]
subjectKeyIdentifier    = hash
authorityKeyIdentifier  = keyid:always,issuer
basicConstraints        = critical,CA:FALSE
extendedKeyUsage        = codeSigning,1.3.6.1.4.1.311.10.3.6,1.3.6.1.4.1.2312.16.1.2
nsComment               = "OpenSSL Generated Certificate"0`

**Comment by mahsoommoosa42** [comment]
So, I have a found a solution. Hopefully, Larry can, later on, integrate this into the project. 

First steps first, you need to create a private key (.priv) and a certificate file (.der). I'm very new to secure boot signing. So, I apologise for my crude use of terminologies. 

Creating a certificate for use in UEFI Secure Boot is relatively simple. openssl can do it by running a few SSL commands. Now, we needs to create a SSL certificate for module signing…

First, let’s create some config to let openssl know what we want to create (let’s call it `‘openssl.cnf’):
`# This definition stops the following lines choking if HOME isn't
# defined.
HOME                    = .
RANDFILE                = $ENV::HOME/.rnd 
[ req ]
distinguished_name      = req_distinguished_name
x509_extensions         = v3
string_mask             = utf8only
prompt                  = no

[ req_distinguished_name ]
countryName             = CA
stateOrProvinceName     = Quebec
localityName            = Montreal
0.organizationName      = cyphermox
commonName              = Secure Boot Signing
emailAddress            = example@example.com

[ v3 ]
subjectKeyIdentifier    = hash
authorityKeyIdentifier  = keyid:always,issuer
basicConstraints        = critical,CA:FALSE
extendedKeyUsage        = codeSigning,1.3.6.1.4.1.311.10.3.6,1.3.6.1.4.1.2312.16.1.2
nsComment               = "OpenSSL Generated Certificate"0`

**Comment by lwfinger** [comment]
I tried your script and have come comments, plus I am reporting an error.

When you prompt for a country, your either need to specify that you want the name spelled out, or you need to accept the ISO code. I had to read country.sh to see what you need. Not all of us run a Debian derivative, thus your suggestion for installing mokutil should include something like ", or whatever command is used to install a new package."

The log file for my error is as follows:
unable to write 'random state'
writing new private key to '/home/finger/bin/RTLMOK.priv'
-----
problems making Certificate Request
140204033263424:error:0D07A098:asn1 encoding routines:ASN1_mbstring_ncopy:string too short:crypto/asn1/a_mbstr.c:102:minsize=1
Exiting Script

**Comment by olumydot** [comment]
I have the same issue. Says "exec format error"

**Comment by lwfinger** [comment]
That message tells me nothing. You need to post any applicable information from the output of the dmesg command.

It is likely that you are either booting in secure mode, which is not supported, or your distro has stored some stale versions of files such as btcoex.ko, rtl_pci.ko, or rtlwifi.ko in the wrong directories. To check the latter case, run the command

sudo find /lib/modules/$(uname -r) -name rtl_pci.ko

If it reports that file in a directory not ending in kernel/drivers/net/wireless/realtek/rtlwifi/, then the other one MUST be deleted. Repeat for all the files listed above.

**Comment by olumydot** [comment]
oh thank you for your prompt response.. I just followed the steps all over again re-downloading the repo. It works fine. Thank you so much
