### ISSUE TITLE
IEEE80211_AMPDU_ERR

### ISSUE THREAD

**Issue by olethrosdc** [lwfinger/rtlwifi_new#427]
I am getting regular error messages of the form:
rtlwifi: IEEE80211_AMPDU_ERR for action 569408824!!!!:
rtlwifi: IEEE80211_AMPDU_ERR for action 419003704!!!!

Attached is the dmesg output. I used to have r8192ee blacklisted in modprobe, but this actually caused problems. Right now is it not blacklisted, but seems unused anyway:

rtl8192ee             110592  0
btcoexist             176128  1 rtl8192ee
rtl_pci                32768  1 rtl8192ee
rtlwifi               102400  3 btcoexist,rtl_pci,rtl8192ee
mac80211              737280  3 rtl_pci,rtlwifi,rtl8192ee

[mdesg.txt](https://github.com/lwfinger/rtlwifi_new/files/2666875/mdesg.txt)

**Comment by lwfinger** [comment]
I do not know where r8192ee would have come from.

The value for "action" is very strange. If you feel comfortable applying a patch, please apply the one below and post the new output from dmesg. I only need the part with the AMPDU_ERR messages.

[debug_ampdu.txt](https://github.com/lwfinger/rtlwifi_new/files/2668407/debug_ampdu.txt)

If you are not comfortable with applying a patch, then we will find some other way.

**Comment by olethrosdc** [comment]
Sure thing! Here is the current output. It does seem to work, overall,
but it is very flakey and sometimes it forces my router to stop
responding to any other device.

[    8.744932] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[    8.772717] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[    9.009037] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[    9.837176] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   10.416072] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   10.534289] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   12.965976] wlan0: authenticate with ec:43:f6:37:33:a4
[   12.999097] wlan0: send auth to ec:43:f6:37:33:a4 (try 1/3)
[   13.046776] wlan0: authenticated
[   13.049328] wlan0: associate with ec:43:f6:37:33:a4 (try 1/3)
[   13.088121] wlan0: RX AssocResp from ec:43:f6:37:33:a4 (capab=0xc11
status=0 aid=1)
[   13.098670] wlan0: associated
[   13.098683] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[   13.102442] cfg80211: Regulatory domain changed to country: SE
[   13.102446] cfg80211:  DFS Master region: ETSI
[   13.102447] cfg80211:   (start_freq - end_freq @ bandwidth),
(max_antenna_gain, max_eirp), (dfs_cac_time)
[   13.102450] cfg80211:   (2402000 KHz - 2482000 KHz @ 40000 KHz),
(N/A, 2000 mBm), (N/A)
[   13.102452] cfg80211:   (5170000 KHz - 5250000 KHz @ 80000 KHz,
160000 KHz AUTO), (N/A, 2000 mBm), (N/A)
[   13.102454] cfg80211:   (5250000 KHz - 5330000 KHz @ 80000 KHz,
160000 KHz AUTO), (N/A, 2000 mBm), (0 s)
[   13.102456] cfg80211:   (5490000 KHz - 5710000 KHz @ 160000 KHz),
(N/A, 2700 mBm), (0 s)
[   13.102458] cfg80211:   (57000000 KHz - 66000000 KHz @ 2160000 KHz),
(N/A, 4000 mBm), (N/A)
[   13.268183] rtlwifi: IEEE80211_AMPDU_ERR for action 433749304!!!!:
[   13.268191] CPU: 3 PID: 6 Comm: kworker/u16:0 Tainted: G           OE
  4.4.0-140-generic #166-Ubuntu
[   13.268194] Hardware name: LENOVO 20ATCTO1WW/20ATCTO1WW, BIOS
J4ET67WW(1.67) 08/13/2014
[   13.268225] Workqueue: phy0 ieee80211_iface_work [mac80211]
[   13.268228]  0000000000000286 dfe76b198ec98730 ffff880119da7c88
ffffffff814055d3
[   13.268233]  ffff8800357f0300 ffff880034ba6840 ffff880119da7c98
ffffffffc0465179
[   13.268236]  ffff880119da7cd0 ffffffffc0554c52 ffff8800357f0300
0000000000000000
[   13.268240] Call Trace:
[   13.268247]  [<ffffffff814055d3>] dump_stack+0x63/0x90
[   13.268257]  [<ffffffffc0465179>] rtl_op_ampdu_action+0x99/0xa0 [rtlwifi]
[   13.268275]  [<ffffffffc0554c52>] drv_ampdu_action+0x72/0x190 [mac80211]
[   13.268294]  [<ffffffffc0561ddd>]
__ieee80211_start_rx_ba_session+0x31d/0x650 [mac80211]
[   13.268312]  [<ffffffffc056216e>]
ieee80211_process_addba_request+0x5e/0x60 [mac80211]
[   13.268328]  [<ffffffffc0567808>] ieee80211_iface_work+0x3a8/0x3e0
[mac80211]
[   13.268332]  [<ffffffff8185337d>] ? __schedule+0x30d/0x7f0
[   13.268335]  [<ffffffff81853371>] ? __schedule+0x301/0x7f0
[   13.268339]  [<ffffffff8109ee4b>] process_one_work+0x16b/0x490
[   13.268342]  [<ffffffff8109f1bb>] worker_thread+0x4b/0x4d0
[   13.268345]  [<ffffffff8109f170>] ? process_one_work+0x490/0x490
[   13.268349]  [<ffffffff810a5587>] kthread+0xe7/0x100
[   13.268352]  [<ffffffff81853371>] ? __schedule+0x301/0x7f0
[   13.268355]  [<ffffffff810a54a0>] ? kthread_create_on_node+0x1e0/0x1e0
[   13.268360]  [<ffffffff81857eb5>] ret_from_fork+0x55/0x80
[   13.268363]  [<ffffffff810a54a0>] ? kthread_create_on_node+0x1e0/0x1e0
[   16.279007] rtlwifi: IEEE80211_AMPDU_ERR for action 419331384!!!!:
[   16.279015] CPU: 0 PID: 155 Comm: kworker/u16:4 Tainted: G
OE   4.4.0-140-generic #166-Ubuntu
[   16.279017] Hardware name: LENOVO 20ATCTO1WW/20ATCTO1WW, BIOS
J4ET67WW(1.67) 08/13/2014
[   16.279052] Workqueue: phy0 ieee80211_iface_work [mac80211]
[   16.279056]  0000000000000286 2afc108aa49afbc8 ffff880118fe7c88
ffffffff814055d3
[   16.279061]  ffff8800a1c65700 ffff880034ba6840 ffff880118fe7c98
ffffffffc0465179
[   16.279064]  ffff880118fe7cd0 ffffffffc0554c52 ffff8800a1c65700
0000000000000000
[   16.279068] Call Trace:
[   16.279077]  [<ffffffff814055d3>] dump_stack+0x63/0x90
[   16.279087]  [<ffffffffc0465179>] rtl_op_ampdu_action+0x99/0xa0 [rtlwifi]
[   16.279103]  [<ffffffffc0554c52>] drv_ampdu_action+0x72/0x190 [mac80211]
[   16.279120]  [<ffffffffc0561ddd>]
__ieee80211_start_rx_ba_session+0x31d/0x650 [mac80211]
[   16.279135]  [<ffffffffc056216e>]
ieee80211_process_addba_request+0x5e/0x60 [mac80211]
[   16.279149]  [<ffffffffc0567808>] ieee80211_iface_work+0x3a8/0x3e0
[mac80211]
[   16.279153]  [<ffffffff8185337d>] ? __schedule+0x30d/0x7f0
[   16.279156]  [<ffffffff81853371>] ? __schedule+0x301/0x7f0
[   16.279161]  [<ffffffff8109ee4b>] process_one_work+0x16b/0x490
[   16.279164]  [<ffffffff8109f1bb>] worker_thread+0x4b/0x4d0
[   16.279167]  [<ffffffff8109f170>] ? process_one_work+0x490/0x490
[   16.279171]  [<ffffffff810a5587>] kthread+0xe7/0x100
[   16.279174]  [<ffffffff81853371>] ? __schedule+0x301/0x7f0
[   16.279177]  [<ffffffff810a54a0>] ? kthread_create_on_node+0x1e0/0x1e0
[   16.279181]  [<ffffffff81857eb5>] ret_from_fork+0x55/0x80
[   16.279184]  [<ffffffff810a54a0>] ? kthread_create_on_node+0x1e0/0x1e0
[   18.160709] rtlwifi: IEEE80211_AMPDU_ERR for action 433749304!!!!:
[   18.160717] CPU: 0 PID: 6 Comm: kworker/u16:0 Tainted: G           OE
  4.4.0-140-generic #166-Ubuntu
[   18.160719] Hardware name: LENOVO 20ATCTO1WW/20ATCTO1WW, BIOS
J4ET67WW(1.67) 08/13/2014
[   18.160766] Workqueue: phy0 ieee80211_iface_work [mac80211]
[   18.160769]  0000000000000286 dfe76b198ec98730 ffff880119da7c88
ffffffff814055d3
[   18.160773]  ffff880119b85400 ffff880034ba6840 ffff880119da7c98
ffffffffc0465179
[   18.160777]  ffff880119da7cd0 ffffffffc0554c52 ffff880119b85400
0000000000000005
[   18.160780] Call Trace:
[   18.160789]  [<ffffffff814055d3>] dump_stack+0x63/0x90
[   18.160799]  [<ffffffffc0465179>] rtl_op_ampdu_action+0x99/0xa0 [rtlwifi]
[   18.160816]  [<ffffffffc0554c52>] drv_ampdu_action+0x72/0x190 [mac80211]
[   18.160837]  [<ffffffffc0561ddd>]
__ieee80211_start_rx_ba_session+0x31d/0x650 [mac80211]
[   18.160856]  [<ffffffffc056216e>]
ieee80211_process_addba_request+0x5e/0x60 [mac80211]
[   18.160874]  [<ffffffffc0567808>] ieee80211_iface_work+0x3a8/0x3e0
[mac80211]
[   18.160880]  [<ffffffff8185337d>] ? __schedule+0x30d/0x7f0
[   18.160883]  [<ffffffff81853371>] ? __schedule+0x301/0x7f0
[   18.160888]  [<ffffffff8109ee4b>] process_one_work+0x16b/0x490
[   18.160891]  [<ffffffff8109f1bb>] worker_thread+0x4b/0x4d0
[   18.160895]  [<ffffffff8109f170>] ? process_one_work+0x490/0x490
[   18.160899]  [<ffffffff810a5587>] kthread+0xe7/0x100
[   18.160901]  [<ffffffff81853371>] ? __schedule+0x301/0x7f0
[   18.160904]  [<ffffffff810a54a0>] ? kthread_create_on_node+0x1e0/0x1e0
[   18.160909]  [<ffffffff81857eb5>] ret_from_fork+0x55/0x80
[   18.160912]  [<ffffffff810a54a0>] ? kthread_create_on_node+0x1e0/0x1e0
[   18.521064] ip_tables: (C) 2000-2006 Netfilter Core Team
[   18.592357] ip6_tables: (C) 2000-2006 Netfilter Core Team
