### ISSUE TITLE
Antenna selection

### ISSUE THREAD

**Issue by ArcEye** [lwfinger/rtlwifi_new#429]
Not a problem per se , but a peculiarity I noted today.

On my HP Pavillion with this pesky chip (8723BE), I upgraded Debian Stretch and had the usual issues of having to recompile the driver for the new kernel.

I used a fresh pull of the repo and all built and installed fine.

However the signal strength was low ( -63dBm ) even when next to the router.

This laptop has always required `ant_sel=2`
I experimented removing all configs, swapping them and testing signal strength etc.

To my surprise, I found that I now needed `ant_sel=1`, whereon I had indicated 100% signal strength in Wicd and a signal strength from iw of -18dBm.

Driver works perfectly with new antenna selection and does not require the `ips=1 swenc=1` I previously needed for best signal.
In fact the signal strength away from the router in other rooms of the house is the best it has been.

Happy New Year and keep up the good work

**Comment by lwfinger** [comment]
The chip is not the pesky part. It is your vendor who saved a few pennies by only putting in a single antenna, but refused to program the ROM correctly.

There is a long list of postings that explained why the ant_sel value changed from 1 to 2. I have no idea what kernel Debian Stretch uses, but you may need to switch back in the future. The ips and swenc parameters were never needed to get a good signal. A long time ago, there was a bug in the power-save code. Before that was fixed, ips=0 was needed. ips=1 is the default.

Yes, the signal is greatly improved when you actually connect an antenna, or in your case, tell the driver to use the antenna port with an antenna connected. :)
