### ISSUE TITLE
OS Freezing in Ad-Hoc Mode

### ISSUE THREAD

**Issue by mrj** [lwfinger/rtlwifi_new#43]
I have a Fedora 21 machine. With F21's current 3.19 kernels I get an OS freeze after about an hour, with out of SW-IOMMU messages that point to Issue #30. Changing to 3.18 kernels instead result in a consistent kernel panic after a longer time (for which I have no evidence the Wi-Fi driver is the cause).

Because a fix for Issue #30 made Linux 4.0, I tried kernel-4.0.0-1.fc22.x86_64. This works OK when talking to an AP hotspot (though the connection regularly drops, perhaps relating to Issue #42). However as soon as I connect to a printer via an ad-hoc network, the machine freezes. Despite the other problems mentioned above, there was no such freeze with the older kernels.

This machine is in a different continent, and I access it through a remote desktop running on the Wi-Fi connection, so this problem is difficult for me to diagnose. But a local person has verified that the machine becomes unresponsive as soon as the Wi-Fi connection is switched to the printer. Can anyone therefore suggest any tests or log data that would help pinpoint the problem?

Thanks.

**Comment by lwfinger** [comment]
The SW-IOMMU leak is fixed in 3.19.5 and 4.0. It should have been queued for 3.18.X, but has apparently not yet been applied. That version does have that bug.

The best diagnostic would be to set up a netconsole link to log that data (a PITA), or to have the local person switch to the logging console (CTRL-ALT-F10 on my openSUSE system) before you try to connect to the printer. She/he can then take a photo of the screen with the crash information.

I will try to set up an ad-hoc link here as soon as you tell me which Realtek chip is involved.

**Comment by mrj** [comment]
Thanks for the reply.

Do you know in what kernel the #30 bug started manifesting? I've now gone back to kernel-3.17.4-301.fc21.x86_64.rpm, the F21 release kernel, to see how things go. This connects to the printer without the freeze we were getting with 4.0.0-1.fc22.x86_64, but we're currently seeing whether it stays up without a freeze or panic.

The local operator needs to use X to switch the Wi-Fi to the printer, so we can't probably use the logging console.

I have however downloaded all the /var/log/messages* files.  Here's the log for 4.0.0-1.fc22.x86_64 just before the freeze caused by switching to the ad-hoc printer link:

```
Apr 21 14:53:28 localhost NetworkManager[769]: <info>  Activation (wlp3s0) Stage 2 of 5 (Device Configure) complete.
Apr 21 14:53:28 localhost NetworkManager[769]: <info>  Config: set interface ap_scan to 2
Apr 21 14:53:29 localhost kernel: wlp3s0: Selected IBSS BSSID 9a:78:58:79:3c:35 based on configured SSID
Apr 21 14:53:29 localhost kernel: BUG: unable to handle kernel NULL pointer dereference at 0000000000000006
```

The Wi-Fi chip is an RTL8188EE.

As well as freezing as soon as an attempt is made to connect to the ad-hoc printer link, 4.0.0-1.fc22.x86_64 was also frozen when we started work this morning, after we had left the Wi-Fi link disconnected. But there's nothing telling in the last logged messages of the day (before messages about the next morning's reboot):

```
Apr 21 15:11:03 localhost kernel: wlp3s0: Connection to AP 66:b4:73:43:33:65 lost
Apr 21 15:11:03 localhost NetworkManager[753]: <warn>  Connection disconnected (reason -4)
Apr 21 15:11:03 localhost kernel: cfg80211: Calling CRDA to update world regulatory domain
Apr 21 15:11:03 localhost NetworkManager[753]: <info>  (wlp3s0): supplicant interface state: completed -> disconnected
Apr 21 15:11:03 localhost kernel: cfg80211: World regulatory domain updated:
Apr 21 15:11:03 localhost kernel: cfg80211:  DFS Master region: unset
Apr 21 15:11:03 localhost kernel: cfg80211:   (start_freq - end_freq @ bandwidth), (max_antenna_gain, max_eirp), (dfs_cac_time)
Apr 21 15:11:03 localhost kernel: cfg80211:   (2402000 KHz - 2472000 KHz @ 40000 KHz), (N/A, 2000 mBm), (N/A)
Apr 21 15:11:03 localhost kernel: cfg80211:   (2457000 KHz - 2482000 KHz @ 40000 KHz), (N/A, 2000 mBm), (N/A)
```

**Comment by lwfinger** [comment]
I was able to duplicate your problem, which is a kernel page fault in rtlwifi.ko. As such, it will affect all the Realtek drivers. That is the bad news. The good news is that the "rock" and probably the "troy" branches of this repo do not have the problem, and you should be able to fix your system while I'm trying to find the bug in the kernel code. Checkout the "rock" branch, make and "sudo make install" and the problem should go away.

**Comment by mrj** [comment]
Thanks very much for looking into this.

So far I've found kernel-3.17.4-301.fc21.x86_64.rpm to be both stable and functional, so I'm sticking with it on our production machines. But I'll use "rock" to build kernels for development. Is "rock" just a re-rewritten set of drivers?

**Comment by lwfinger** [comment]
This repo is the means for Realtek to send me their newest code, and for me to feed back any changes. The "rock" branch is the one maintained by the Realtek engineer currently assigned to the Linux PCI drivers. This repo was created when Realtek sent me rewritten drivers that were incorporated in the 3.18 kernel.

**Comment by mrj** [comment]
3.18 was giving me kernel panics rather than freezes, though I don't have evidence to hand that they were caused by the Wi-Fi driver. So do you think "rock" compiled against the newly-released kernel-3.19.5-200.fc21 would give me the best chance of a stable and functional system (like 3.17.4 seems to be), even though you say the 3.18 drivers are either "rock" or a close derivative of "rock"?

**Comment by lwfinger** [comment]
For me, rock did not give the error. Yes, rock is a close derivative of the kernel, but there are still differences. It is certainly possible that the kernel has the bug, but rock does not. We will only know if you try it.

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
