### ISSUE TITLE
show a message when compiling. this is the issue?

### ISSUE THREAD

**Issue by ginting** [lwfinger/rtlwifi_new#432]
make[1]: Entering directory '/usr/src/linux-headers-4.15.0-43-generic'
  CC [M]  /home/ginting/gmtdev/library/rtlwifi_new-20190115/base.o
  CC [M]  /home/ginting/gmtdev/library/rtlwifi_new-20190115/cam.o
  CC [M]  /home/ginting/gmtdev/library/rtlwifi_new-20190115/core.o
  CC [M]  /home/ginting/gmtdev/library/rtlwifi_new-20190115/debug.o
  CC [M]  /home/ginting/gmtdev/library/rtlwifi_new-20190115/efuse.o
  CC [M]  /home/ginting/gmtdev/library/rtlwifi_new-20190115/ps.o
symbolmap: 00000001: invalid section
  CC [M]  /home/ginting/gmtdev/library/rtlwifi_new-20190115/rc.o
  CC [M]  /home/ginting/gmtdev/library/rtlwifi_new-20190115/regd.o
  CC [M]  /home/ginting/gmtdev/library/rtlwifi_new-20190115/stats.o
  LD [M]  /home/ginting/gmtdev/library/rtlwifi_new-20190115/rtlwifi.o
  CC [M]  /home/ginting/gmtdev/library/rtlwifi_new-20190115/pci.o
symbolmap: 00000001: invalid section

my os as follows:
4.15.0-43-generic #46~16.04.1-Ubuntu SMP Fri Dec 7 13:31:08 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by lwfinger** [comment]
That is a problem with your copy of gcc. Talk to your distro, not here.
