### ISSUE TITLE
RTL8821AE has a very weak signal level

### ISSUE THREAD

**Issue by nik3212** [lwfinger/rtlwifi_new#433]
Hello!

RTL8821AE has a very weak signal level (about 55%) and very slow speed (2-3 Mbps) in Ubuntu, if I use 5GHz network. 

On the same computer installed Windows. It has signal 90% and speed about 60-70 Mbps.

What could be the problem?

**System**: Ubuntu 18.04
**Kernel**: 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Output from `iwconfig`:

> wlp5s0    IEEE 802.11  ESSID:"mts_5G"  
>           Mode:Managed  Frequency:5.2 GHz  Access Point: B0:BE:76:81:8D:D7   
>           Bit Rate=200 Mb/s   Tx-Power=30 dBm   
>           Retry short limit:7   RTS thr=2347 B   Fragment thr:off
>           Power Management:on
>           Link Quality=57/70  Signal level=-53 dBm  
>           Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
>           Tx excessive retries:0  Invalid misc:1   Missed beacon:0

**Comment by lwfinger** [comment]
When you report low signal, it is not of much interest to report the Link Quality. The Signal level is what counts; however, your value of -53 dBm should be sufficient.

Are you using the driver from this repo? If using the one built into your kernel, then you might try the extended branch from here.

Please run the following command, and post the results:

sudo iw dev wlp5s0 scan | egrep "SSID|signal|\(on|freq"

**Comment by nik3212** [comment]
Yes, I'm using the driver from this repo.

> BSS 88:5d:90:e0:82:7f(on wlp5s0)
> 	freq: 2427
> 	signal: -60.00 dBm
> 	SSID: Skylink-827D
> BSS d0:60:8c:21:46:ec(on wlp5s0)
> 	freq: 2442
> 	signal: -56.00 dBm
> 	SSID: MTSRouter_2146EC
> BSS a0:ab:1b:0f:9f:67(on wlp5s0)
> 	freq: 2452
> 	signal: -62.00 dBm
> 	SSID: MTSRouter-0F9F67
> BSS 58:d5:6e:65:19:83(on wlp5s0)
> 	freq: 2472
> 	signal: -46.00 dBm
> 	SSID: MTS_Router_001314
> BSS 74:b5:7e:13:da:50(on wlp5s0)
> 	freq: 2412
> 	signal: -74.00 dBm
> 	SSID: WiFi-DOM.ru-0584
> BSS e8:65:d4:71:d8:e1(on wlp5s0)
> 	freq: 2412
> 	signal: -60.00 dBm
> 	SSID: AppleAirportExtreme
> BSS 58:d5:6e:65:19:81(on wlp5s0)
> 	freq: 5180
> 	signal: -77.00 dBm
> 	SSID: MTS_Router_5_001314
> 		 * center freq segment 1: 42
> 		 * center freq segment 2: 0
> BSS b0:be:76:81:8d:d6(on wlp5s0)
> 	freq: 2412
> 	signal: -28.00 dBm
> 	SSID: mts
> BSS b0:be:76:81:8d:d7(on wlp5s0) -- associated
> 	freq: 5180
> 	signal: -68.00 dBm
> 	SSID: mts_5G
> 		 * center freq segment 1: 0
> 		 * center freq segment 2: 0
> BSS 10:0d:7f:2f:b7:fa(on wlp5s0)
> 	freq: 2437
> 	signal: -72.00 dBm
> 	SSID: WiFi-DOM.ru-8384
> BSS 34:4d:eb:e7:84:97(on wlp5s0)
> 	freq: 2457
> 	signal: -74.00 dBm
> 	SSID: WiFi-DOM.ru-7536
> BSS 00:0e:8f:c8:d8:48(on wlp5s0)
> 	freq: 2412
> 	signal: -58.00 dBm
> 	SSID: dagestan 05
> BSS e8:65:d4:71:d8:e5(on wlp5s0)
> 	freq: 5180
> 	signal: -65.00 dBm
> 	SSID: AppleAirportExtreme_5G
> 		 * center freq segment 1: 38
> 		 * center freq segment 2: 0
> BSS 00:0e:8f:c8:d8:46(on wlp5s0)
> 	freq: 2412
> 	signal: -58.00 dBm
> 	SSID: dagestan 05
> BSS 70:79:90:aa:5f:3c(on wlp5s0)
> 	freq: 2462
> 	signal: -76.00 dBm
> 	SSID: Rostelecom_5F2E
> BSS 74:d0:2b:2c:f0:14(on wlp5s0)
> 	freq: 2462
> 	signal: -74.00 dBm
> 	SSID: 52362
> BSS ec:08:6b:de:71:f2(on wlp5s0)
> 	freq: 2472
> 	signal: -76.00 dBm
> 	SSID: SweetHome

**Comment by nik3212** [comment]
The laptop is located in 5 meters from the AP. Two cables connected. The signal level is constantly changing.

If I change the channel from 36 to any other, then the notebook cannot connect to the network. 

I had tried to use the range extender and the signal has become stronger but the speed was also slow.

**Comment by lwfinger** [comment]
Is that 5 m in air, or are there obstacles. The 5G range is a lot lower than for 2.4G - it has very low penetrating power. My computer is about 2m from my APs, and I get about 10 dBm stronger signals from the 2.4G radios than for the 5G ones. You are seeing about 40 dBm difference between "mts" and "mts-5G".

The channel must be changed in the AP. The STA must use the APs channel.

I only volunteer to help Realtek. I have no knowledge of the chip internals. Essentially, the only thing I can fix are build errors, and those problems that cause kernel oops.

My suggestion is that you switch to the 2,4G AP with ssid "mts".

**Comment by nik3212** [comment]
5 meters by air. It is strange that the same Windows computer has a good signal.

It seems I have to use the 2.4G.

Thanks for the help.

**Comment by carloscmaleno** [comment]
I have the same issue since few days/weeks with 5G
I tried to upgrade the driver but nothing changed... (speed on Windows in same pc and mobile phone at same distance have 100% velocity...)

Tested on: Kubuntu 18.04: 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Card:
```
07:00.0 Network controller [0280]: Realtek Semiconductor Co., Ltd. RTL8812AE 802.11ac PCIe Wireless Network Adapter [10ec:8812] (rev 01)
	Subsystem: ASUSTeK Computer Inc. RTL8812AE 802.11ac PCIe Wireless Network Adapter [1043:86dd]
	Kernel driver in use: rtl8821ae
	Kernel modules: rtl8821ae
```

dmesg
```[ 1502.228458] wlp7s0: Connection to AP 00:00:00:00:00:00 lost
[ 1516.665497] wlp7s0: authenticate with 34:57:60:6b:65:7e
[ 1522.276882] wlp7s0: send auth to 34:57:60:6b:65:7e (try 1/3)
[ 1522.278543] wlp7s0: authenticated
[ 1522.280369] wlp7s0: associate with 34:57:60:6b:65:7e (try 1/3)
[ 1522.283157] wlp7s0: RX AssocResp from 34:57:60:6b:65:7e (capab=0x511 status=0 aid=95)
[ 1522.283322] wlp7s0: associated
[ 1522.356738] wlp7s0: Limiting TX power to 23 (23 - 0) dBm as advertised by 34:57:60:6b:65:7e
[ 1535.728353] rtlwifi: AP off, try to reconnect now
[ 1535.728367] wlp7s0: Connection to AP 34:57:60:6b:65:7e lost
[ 1545.808350] rtlwifi: AP off, try to reconnect now
[ 1552.600443] wlp7s0: Connection to AP 00:00:00:00:00:00 lost
[ 1567.940703] IPv6: ADDRCONF(NETDEV_UP): wlp7s0: link is not ready
[ 1607.089830] wlp7s0: authenticate with 34:57:60:6b:65:7e
[ 1612.720856] wlp7s0: send auth to 34:57:60:6b:65:7e (try 1/3)
[ 1612.721294] wlp7s0: aborting authentication with 34:57:60:6b:65:7e by local choice (Reason: 3=DEAUTH_LEAVING)
[ 1618.331713] IPv6: ADDRCONF(NETDEV_UP): wlp7s0: link is not ready
[ 1638.405448] wlp7s0: authenticate with 34:57:60:6b:65:7e
[ 1644.032866] wlp7s0: send auth to 34:57:60:6b:65:7e (try 1/3)
[ 1644.033967] wlp7s0: authenticated
[ 1644.036360] wlp7s0: associate with 34:57:60:6b:65:7e (try 1/3)
[ 1644.039124] wlp7s0: RX AssocResp from 34:57:60:6b:65:7e (capab=0x511 status=0 aid=96)
[ 1644.039299] wlp7s0: associated
[ 1644.111190] wlp7s0: Limiting TX power to 23 (23 - 0) dBm as advertised by 34:57:60:6b:65:7e
[ 1644.173161] IPv6: ADDRCONF(NETDEV_CHANGE): wlp7s0: link becomes ready
```

Can we do something?

**Comment by praveenojha33** [comment]
I am also having the same problem, the internet on same computer on Windows works very fast but on Ubuntu the speed is very slow. The signal is also very weak, I tried changing antenna but still the signal is very weak and internet works slowly.
Quality=33/70  Signal level=-77 dBm

**Comment by lwfinger** [comment]
Does your computer have one or two antennas?

**Comment by praveenojha33** [comment]
Yes

**Comment by lwfinger** [comment]
Which band are you using, 2.4 or 5 G? How far to your AP? Please run the following command and post the output:

sudo iw dev wlan0 scan | egrep "SSID|signal|freq|\(on"

You will likely need to change the wlan0 to match your system. "iw dev" will list the device name.

**Comment by praveenojha33** [comment]
I am using 2.4 GHz band. The AP is 4 meters far. I get good signal on my phone and in Windows.
The command says `command failed: No such device (-19)`

**Comment by lwfinger** [comment]
I told you that you needed to change the "wlan0" to match the exact name of your wireless device. Use 'iw dev' to see what that name is.

**Comment by praveenojha33** [comment]
`freq: 2462
	signal: -72.00 dBm
	SSID: MMMUT_Raman
	freq: 2462
	signal: -35.00 dBm
	SSID: DESKTOP-CRSPDI5 8137
	freq: 2462
	signal: -71.00 dBm
	SSID: MMMUT_Raman
	freq: 2437
	signal: -78.00 dBm
	SSID: MMMUT_Raman
	freq: 2462
	signal: -73.00 dBm
	SSID: MMMUT_Raman
`

**Comment by lwfinger** [comment]
Interesting. Why do you have 5 SSIDs listed, but only 4 frequencies?

It looks as though I missed a \ in front of the "on". Please re-run so that I can see which of the APs you are actually connected to..

Obviously, you are getting a -35 dBm from the SSID "DESKTOP-CRSPDI5 8137", thus your device is capable of receiving strong signals. Are you sure that is not the one at 4m? With that one available, why are you connecting to one of the "MMMUT_Raman" APs?

**Comment by praveenojha33** [comment]
Actually, I live in a hostel and "DESKTOP-CRSPDI5 8137" was a temporary Private AP created from the just next room. I do not have permission to connect to that. "MMMUT_Raman" are Public APs which are available to us the nearest one is around 4m-5m away. Here is the output which you wanted
```
BSS 90:4c:81:22:03:b0(on wlp2s0) -- associated
	freq: 5785
	signal: -79.00 dBm
	SSID: MMMUT_Raman
		 * center freq segment 1: 155
		 * center freq segment 2: 0
BSS 90:4c:81:21:84:20(on wlp2s0)
	freq: 2462
	signal: -72.00 dBm
	SSID: MMMUT_Raman
BSS 90:4c:81:21:bf:60(on wlp2s0)
	freq: 2437
	signal: -75.00 dBm
	SSID: MMMUT_Raman
BSS 90:4c:81:22:03:a0(on wlp2s0)
	freq: 2462
	signal: -72.00 dBm
	SSID: MMMUT_Raman
```

**Comment by lwfinger** [comment]
OK. Note that you are actually using the worst of the available APs. The AP with BSS 90:4c:81:22:03:a0 (the last in the list) is the 2.4 G band from the 5 G AP you are using. That 7 dBm increase will help.

I'm still confused about your signal strengths on the 2.4 G band. With my 8821AE, I have 2 APs at about 2 m with no walls in the way.. I get -52 dBM (5 G) and -48 dBm (2.4 G) for the first, and -45 dBm (5 G) and -36 dBm (2.4 G) for the second. These readings have a variability of 2-3 dBm, and were all made with the two antennas in a laptop.

What obstructions are there between your computer and the AP at 4-5 m distance?

**Comment by praveenojha33** [comment]
There are walls between the AP and my computer. But the main point to note is that I have a dual booted system and the signal from same AP is good on Windows. Also the internet speed is very fine on Windows.

**Comment by lwfinger** [comment]
Yes, the Windows driver is a distinct product.

Note that I did not write any of these drivers. My role has been to help with the glue part between the driver and Linux, and handle the API changes that come from Linux kernel updates.

Obviously, there is little I can do for you. If you have sufficient resources, you could run your Linux instance as a virtual machine and boot that VM from Windows. I did that about 10 years ago when the only wifi adapter that I had did not work with Linux. I booted Windows and then booted Linux from within VirtualBox. I am not sure that current versions of Windows and VirtualBox will allow using the raw hard disk as a virtual disk as described in Chapter 9 of the VB manual.

Good luck.
