### ISSUE TITLE
rtl8723de : breaks my system

### ISSUE THREAD

**Issue by Lalks** [lwfinger/rtlwifi_new#434]
Hello,

I am facing a critical issue while trying to use the RTL8723DE on my HP laptop. I had already this issue on an other version (you can find my post here : [https://github.com/smlinux/rtl8723de/issues/21](https://github.com/smlinux/rtl8723de/issues/21)).
The problem is this one : after the successful installation of the driver from the extended branch and by carefully reading the readme, when I try to connect to an SSID (from the XFCE's applet, I've got a list of SSIDs around) my computer starts to be very very slow then freezes within few seconds. Then I am unable to open an other tty or anything. After several minutes I force the shutdown by holding the power button. When I try to reboot, there is the grub rescue prompt that appears. When I try to reboot from the prompt, it is written that no system is installed on the disk.
I tried multiple times (see my oldest issue on smlinux's github page) with different distros and kernels. Today I tried on Manjaro Linux, with a brand new kernel 4.20, the right linux-headers and a fully updated system. The issue is always here, no matter the versions I'm using. I also had some mini freezes while trying to get the signals received from the module (as written in the readme to check which option we need for sel_ant). There were no other issue during the installation / configuration steps present in the readme. 

I don't know what the problem is, really. The Wi-Fi works perfectly on Windows 10. I can share information about my computer if needed.

What should I do ? Is this issue known ?

Thanks.

**Comment by lwfinger** [comment]
As you really want to use someone else's port, why should I even bother to answer your questions?

No, this is NOT a known problem. It is something unique about your computer. If you had provided some concrete information from your logs, then I would be in a better position to help, but I'll give it a try.

Your symptoms sound as if there is something wrong with interrupt processing. There are two module options that might have an effect. Try the following:

sudo modprobe -rv rtl8723de
sudo modprobe -v rtl9823de msi=0

Does that help? If not, then try

sudo modprobe -rv rtl8723de
sudo modprobe -v rtl9823de aspm=0

If that does not help, then try

sudo modprobe -rv rtl8723de
sudo modprobe -v rtl9823de msi=0 aspm=0

If none of the above help, I have just added a new module parameter. You will need to use the "extended" branch, do a "git pull", rebuild the driver with "make" and "sudo make install" Then

sudo modprobe -rv rtl8723de
sudo modprobe -v rtl9823de int_clear=1

If that does not fix the problem, then I am afraid there is little I can do from here.

**Comment by gestory** [comment]
I have the very same problem with rtl8723de and HP. 

With aspm=0 (as well as with int_clear=1) system is stable, though there is still no working device in both cases ("device is not ready" according to nm). 

In dmesg I see this:
rtl8723de: Init MAC failed.

I will provide any logs you need.

**Comment by lwfinger** [comment]
If you are seeing "Init MAC failed", then your system is not stable - at least driver rtl8723de is not starting correctly.

With my system, I have seen that happen only once, and that seemed to be a power-on problem.

Please port the output of the dmesg command in some pastebin account.

**Comment by lwfinger** [comment]
I just committed a change to delay for 1 sec before the system starts downloading any firmware. Do a 'git pull', 'make' and 'sudo make install' to see if this helps.

**Comment by gestory** [comment]
There is a dmesg output:
https://pastebin.com/P2etx4W1

Delay didn't help, I see the same behavior:
https://pastebin.com/RKSfQA0c

There is a difference in the end of second try: I removed module and inserted it back.

**Comment by lwfinger** [comment]
I pushed some additional debugging statements. Please try again and post the output of dmesg starting at the line where rtl8723de loaded the firmware. I won't need the rest.

**Comment by gestory** [comment]
https://pastebin.com/gvdjBCh3

**Comment by lwfinger** [comment]
Thanks. The logic is very convoluted, and it may take a while to untangle it. In the meantime, a case of Init MAC failures on warm reboot was fixed by setting bit 0 of register 0x75. I pushed a change to try it here.

**Comment by lwfinger** [comment]
The new driver for RTL8723DE is now in the wireless_drivers_next repo. To make it easier for users here, it is now in the rtw88 branch. Do the following:

git checkout origin/rtw88 -b rtw88
make
sudo make install

This version should build on kernels 4.5 or newer.

Please be aware that on June 1, 2020, all branches in this repo will be deleted except for rtw88. If you really need the other drivers for old kernels, use the "backports" project. These old drivers have been taking too much of my time!
