### ISSUE TITLE
RTL8723BE modprobe: ERROR: could not insert 'rtl8723be': Exec format error

### ISSUE THREAD

**Issue by umutozdemir97** [lwfinger/rtlwifi_new#437]
When I try to issue the command `sudo modprobe rtl8723be`, I see this output:

`modprobe: ERROR: could not insert 'rtl8723be': Exec format error`

Dmesg output:

`[  731.589288] rtlwifi: version magic '4.15.0-44-generic SMP mod_unload ' should be '4.15.0-45-generic SMP mod_unload '
`
I learned from older issues that there is a header and kernel mismatch. How can I solve this problem? I searched everywhere and couldn't solve this problem. Driver expects a different header? I think I already installed the '4.15.0-45' kernel header because I see: 

`$ sudo apt search linux-headers-$(uname -r)
Sorting... Done
Full Text Search... Done
linux-headers-4.15.0-45-generic/bionic-updates,bionic-security,now 4.15.0-45.48 amd64 [installed]
  Linux kernel headers for version 4.15.0 on 64 bit x86 SMP
`

`$ sudo uname  -r 
4.15.0-45-generic
`

**Comment by umutozdemir97** [comment]
Successfully installed after running `sudo make clean`. After then, I was able to compile and install again. And the modprobe command did not fail. Run clean command. Problem is not related to kernel headers.

**Comment by lwfinger** [comment]
No, the problem was related to the kernel headers. They MUST MATCH EXACTLY the kernel that is running. You posted "rtlwifi: version magic '4.15.0-44-generic SMP mod_unload ' should be '4.15.0-45-generic SMP mod_unload ' `". You had built the drivers with the 4.15.0-44 headers, but were running a 4.15.0-45 kernel. That difference between 44 and 45 is exactly what caused the error. There is no tolerance.

**Comment by umutozdemir97** [comment]
I wasn't intended to build it that way. The error inside my build process. I know that there is no tolerance. But the error is not the headers, everything about headers were just intended to be the way it was, the error is the driver being built for old headers again and again without any intention to do so. I think default make task should clear since we don't compile it a lot of times a day, we do it once a month when kernel headers are changed. Because old .obj files of the old build were around, make did not recompile them. They were from a time when the headers were 4.15.0-44.
