### ISSUE TITLE
rtl8723be wifi range has become poor again

### ISSUE THREAD

**Issue by djrscally** [lwfinger/rtlwifi_new#438]
Hey

The out-of-box range for an rtl8723be operating on most Linux distros I have tried has always been terrible. Your driver fixed that with the `ant_sel=2` option set. There seems to have been a semi-recent update to _something_ that's re-broken that however, and now the range is terrible again. 

Apologies; I've not really any experience diagnosing issues of this kind so I don't particularly know where to begin. I'm using elementary OS 5.0 June, Kernel version is 4.15.0-42-generic; guide me on what to look for and I'll do what I can

Cheers!

**Comment by lwfinger** [comment]
We did not change anything. I'll try to find out what happened on your end. Please run the 2 commands below and post the output:

sudo modprobe -rv rtl8723be
sudo modprobe -v rtl8723be

**Comment by djrscally** [comment]
@lwfinger  thanks for the reply, sorry for the delay replying.

>me@HP-Stream-11:~$ sudo modprobe -rv rtl8723be
>rmmod rtl8723be
>rmmod rtl_pci
>rmmod rtl8723be_common
>rmmod btcoexist
>rmmod rtlwifi
>rmmod mac80211
>rmmod cfg80211
>  
>me@HP-Stream-11:~$ sudo modprobe -v rtl8723be
>insmod /lib/modules/4.15.0-42-generic/kernel/net/wireless/cfg80211.ko
>insmod /lib/modules/4.15.0-42-generic/kernel/net/mac80211/mac80211.ko
>insmod /lib/modules/4.15.0-42-generic/kernel/drivers/net/wireless/realtek/rtlwifi/rtlwifi/rtlwifi.ko
>insmod /lib/modules/4.15.0-42-generic/kernel/drivers/net/wireless/realtek/rtlwifi/rtlwifi/rtl_pci.ko
>insmod /lib/modules/4.15.0-42-generic/kernel/drivers/net/wireless/realtek/rtlwifi/rtlwifi/rtl8723com/rtl8723-common.ko
>insmod /lib/modules/4.15.0-42-generic/kernel/drivers/net/wireless/realtek/rtlwifi/rtlwifi/btcoexist/btcoexist.ko
>insmod /lib/modules/4.15.0-42-generic/kernel/drivers/net/wireless/realtek/rtlwifi/rtlwifi/rtl8723be/rtl8723be.ko ant_sel=1

Ignore the ant_sel=1 there; I've been switching it around trying to make it work: it's still not working with ant_sel=2. This sorta implied to me it was back to using generic drivers so I tried reinstalling yours and alas, still no dice.

**Comment by djrscally** [comment]
Hmm yeah OK. I initially reinstalled thusly:
```

For all distros:
git clone https://github.com/lwfinger/rtlwifi_new.git
cd rtlwifi_new
make
sudo make install
sudo modprobe -r <<YOUR WIRELESS DRIVER CODE>>
sudo modprobe <<YOUR WIRELESS DRIVER CODE>>
```

And that didn't work. However, when I followed that up with this:

```
sudo rm /lib/modules/4.15.0-42-generic/kernel/drivers/net/wireless/realtek/rtlwifi/rtlwifi/rtl8723be/rtl8723be.ko
sudo mv ~/Installs/rtlwifi_new/rtl8723be/rtl8723be.ko /lib/modules/4.15.0-42-generic/kernel/drivers/net/wireless/realtek/rtlwifi/rtlwifi/rtl8723be/rtl8723be.ko
```

Then the wifi starts working. So, for some reason it lost the right driver and the install process didnt stick it back.

I guess you can close this since, although I still think there's a problem somewhere, it obviously isn't with your driver!

Thanks
