### ISSUE TITLE
Problem with latest kernel 4.15.0-45 (RTL8723be)

### ISSUE THREAD

**Issue by victorkamoto** [lwfinger/rtlwifi_new#439]
After updating the kernel, the drivers do not seem to work anymore despite countless re-installations. Please help.
Product: HP notebook 15 - ay076nia
OS: Ubuntu 18.04

**Comment by lwfinger** [comment]
Did you do a git pull? I have used those drivers for kernels up through 5.0.0.

Are you getting any error messages?

**Comment by faraazahmad** [comment]
> I have used those drivers for kernels up through 5.0.0.

so what did you mean by `IF YOU RUN UBUNTU, YOU CAN BE ASSURED THAT THE APIs HAVE CHANGED. NO, I WILL NOT MODIFY THE SOURCE FOR YOU. YOU ARE ON YOUR OWN!!!!!`

**Comment by lwfinger** [comment]
Ubuntu has a habit of backporting API changes from the newest kernels to older ones. In that case, it is not sufficient to test the kernel version, but one also needs to know the Ubuntu version. I do not support that kind of backporting, and  do not have time to find all the critical information to write patches that will allow the drivers to build on all versions of all distros. I guarantee that the drivers will build on the vanilla kernels, and nothing more. That is what I meant.

**Comment by faraazahmad** [comment]
Thank you

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by victorkamoto** [comment]
I did a git pull. Everything is up to date. The only error I received earlier was for the linux header files and I fixed that. Nothing changes even after antennae switching. Please help

**Comment by lwfinger** [comment]
Well, from what I see above, you have only said "the drivers don't work"! That statement provides me no information at all. That level of non-information just wastes my time, and makes me angry.

Do the drivers load? Please tell me something useful, otherwise, I must ignore you.
