### ISSUE TITLE
RTL8723DE: Init MAC failed error

### ISSUE THREAD

**Issue by Feanor1397** [lwfinger/rtlwifi_new#440]
Error appeared after updating from e898a691b80cac1a341d82d6dbcc09b4a3696537 to 6f99b4991d489a27fe177fa98a41981a284556cb. This happens after reboot only, normal shutdown and start does not cause error.
[dmesg](https://pastebin.com/NNHqq2Xy)

**Comment by lwfinger** [comment]
As you are the one with the problem, you get to help debug it. Please run a git bisect with commit e898a69 as the bad one, and 6f99b49 as the good one. Your results will help narrow the bad code.

**Comment by Feanor1397** [comment]
well, after bisecting i found that problem appeared on all commits, so it's probably kernel regression, not module. one strange thing, it's appeared only after module update, not kernel update.
[There](https://pastebin.com/X0w18agV) is some logs with debug_level=5

**Comment by lwfinger** [comment]
So you lied when you said it worked with e898a69?
