### ISSUE TITLE
trx.c: GET_RX_STATUS_DESC_PATTERN_MATCH is used right only in rtl8821

### ISSUE THREAD

**Issue by ValZapod** [lwfinger/rtlwifi_new#442]
As you can see in rtl8821ae we have:
https://github.com/lwfinger/rtlwifi_new/blob/00c04849dbb3585dc646bd14d489d34064a49d58/rtl8821ae/trx.c#L500-L508

While in rtl8188ee (and others) we have:
https://github.com/lwfinger/rtlwifi_new/blob/b63c4a3efc19495eed00d8b481104a6685e77648/rtl8188ee/trx.c#L425-L432
So I suppose it is a mistake as you can't use GET_RX_STATUS_DESC_MAGIC_MATCH twice: looks like a copy/paste. Also please look at linux kernel tree... https://github.com/torvalds/linux/search?q=GET_RX_STATUS_DESC_MAGIC_MATCH&unscoped_q=GET_RX_STATUS_DESC_MAGIC_MATCH

**Comment by lwfinger** [comment]
Thanks for alerting me to this bug. Please note that the only affect is to log the wrong number in a debug statement. I have no idea why wake_match is part of a struct as it is not used in any part of any of the drivers.
