### ISSUE TITLE
RTL8723de doesn't build in master

### ISSUE THREAD

**Issue by plater** [lwfinger/rtlwifi_new#443]
RTL8723de's folder has only one file and doesn't build, it still exists in the extended branch and either it or the 4.20.10 kernel has fixed an issue I had with my wifi extender not locking on.

**Comment by lwfinger** [comment]
Driver rtl8723de has never been in the master branch. If you have ever checked out the extended branch, then the rtl8723de directory will exist, but the source files will not be there.

As to the recent "fix", without any documentation of why it didn't work, I have no clue. I only got one of the RTL8723DE cards recently, thus I have little experience with it.

**Comment by plater** [comment]
You need to update README.md to" git clone -b extended https://github.com/lwfinger/rtlwifi_new.git" for the rtl8723de driver. I found it via HP support and Ubuntu and originally cloned this git in June last year to use with the 4.17 kernel and (one git pull 2/2/2019 which had rtl8723de) because I accidentally corrupted it I deleted and recloned, that's when I noticed the missing rtl8723de driver and then found it in extended.
I have a huawei lte router and a tplink extender, my laptop, under linux, refused to lock on to the tplink extender, with no errors and even though it had a stronger signal, for a few kernels after I'd upgraded the laptop to openSUSE:Tumbleweed. No problems with windows 10. I have a kmp in home:plater

**Comment by plater** [comment]
I'm going to open a new issue to deal with tplink/huawei
