### ISSUE TITLE
Internet connection drops after random time intervals

### ISSUE THREAD

**Issue by int-main** [lwfinger/rtlwifi_new#444]
Please have a look at here for a detailed description of the bug: https://askubuntu.com/q/1122683/925252

**Comment by lwfinger** [comment]
The comment about using the in-kernel driver is NOT correct. My info is that 18.04 comes with a 4.15 kernel, whereas the "final" fix for the ant_sel code was merged with kernel 4.17. The kernel ant_sel value is likely 1 to get wifi strength, but the value in this repo would be 2 as you noted.

Is anything logged in dmesg or journalctl when this problem happens? Note that turning the wifi off and turning it back on does nothing to the driver as long as the driver is not unloaded. The sequence does have significant effect on the rest of the wifi control software. How are you controlling networking?

I test the various drivers using openSUSE and NetworkManager. My system has maintained a wifi connection with the RTL8723BE for several days without a drop.

**Comment by int-main** [comment]
I did not install any extra software for networking. I use whatever came pre-installed with Ubuntu 18.04. I will let you know about dmesg and journalctl status once I re-encounter this problem.

**Comment by int-main** [comment]
The event re-occurred. After closely examining the logs I found that the DHCP lease renewal process is causing the problem (See: https://bugs.launchpad.net/ubuntu/+source/isc-dhcp/+bug/1743998). Hence, I am closing this thread.
