### ISSUE TITLE
Can I delete the folders of the cards that are not mine for faster compile time?

### ISSUE THREAD

**Issue by adalvigi** [lwfinger/rtlwifi_new#445]
Title

**Comment by lwfinger** [comment]
If you delete the directories (folders is a Windows term), the build would fail.

You could edit Makefile to remove the parts you do not want, but that would be tricky to get right.

Even easier would be to use "make -jX", where X is 2 times the number of CPUs + 1. I have a quad core CPU, thus I use "make -j9".
