### ISSUE TITLE
RTL8812AE Cannot detect 5Ghz networks

### ISSUE THREAD

**Issue by bmath1123** [lwfinger/rtlwifi_new#446]
My rtl8812ae card using the 8821ae drivers can detect and connect to 2.4Ghz networks but not 5Ghz. When I first installed the driver, I could connect and had no issue, but after a restart it stopped working.

**Comment by lwfinger** [comment]
What kernel version are you using?
Which branch of this repo are you using?
Did you do a 'sudo make install'?
What is the output of
iw dev | grep Interface
sudo iw dev wlan0 scan | egrep "SSID|signal|freq:"

If the first output shows your device to be something other than "wlan0", use that name in the second.

**Comment by bmath1123** [comment]
I ended up just purchasing a different wireless card as the HiRO card this post is about had given me issues on other OSes as well. Thank you for your time, and I will close this issue.
