### ISSUE TITLE
RTL8723BE on Debian 3.67.7 lost signal / no signal / loss packets

### ISSUE THREAD

**Issue by bagage** [lwfinger/rtlwifi_new#45]
On a home wifi, normal use-case (10 m from box), I lost connection from every 30 secs to every 5 minutes. I'd like to help making this firmware better but I don't know where to start so here are some questions:

1) Is there any "wifi test-report program" to compare firmware quality depending on antenna parameters? Not necessarly in `rtlwifi_new` but do you use @lwfinger anything like this to quantify firmware quality?
2) Can you confirm me that only `rtlwifi_new` firmware is responsible for WifI quality? Eg. kernel version won't change anything? 
3) What would be useful to help making the firmware more stable in my use case? There are many different logs (`dmesg`, `NetworkManager`, etc.), which ones are valuable to diagnose such general issue?
4) I may want to put a $25 bounty of this issue if this can help motivation. I don't know if it might interest other people, but if @lwfinger you are interested in, maybe we can try it  [a bounty on freedomsponsors](https://freedomsponsors.org/) for instance?

**Comment by lwfinger** [comment]
Start by learning the difference between firmware and driver!

The only log of interest is what appears in the output of the dmesg command at the point the connection is lost.

Please be careful with kernel versions. They go up to 3.19, and then skip to 4.0. What is kernel 3.67?

The wireless connectivity will depend on the wireless driver, *and* the 802.11 software stack. The latter changes with kernel version, but is not changed in rtlwifi_new! The answer to #3 is an emphatic "no".

Try loading rtl8723be with the "ips=0" option. Does that help?

**Comment by bagage** [comment]
>>> Start by learning the difference between firmware and driver!

Got it. Should have checked before posting! 

My kernel is not `3.16.7`, this is only my Debian version. I am using a `3.16.0` kernel. Even if I would like to avoid upgrading kernel to 4.0 if not necessary (I'm absolutely not comfortable in this area :)), upgrading kernel could change wifi performances?

I currently use the following parameters `options rtl8723be fwlps=N ips=N` since it is giving the best overall performances. 

When wifi disconnects, I get:

>>> wlan0: Connection to AP XX:XX:XX:XX:XX:XX lost
>>> cfg80211: Calling CRDA to update world regulatory domain
>>> cfg80211: World regulatory domain updated:
>>> cfg80211:  DFS Master region: unset
>>> cfg80211:   (start_freq - end_freq @ bandwidth), (max_antenna_gain, max_eirp), (dfs_cac_time)
>>> cfg80211:   (2402000 KHz - 2472000 KHz @ 40000 KHz), (N/A, 2000 mBm), (N/A)
>>> cfg80211:   (2457000 KHz - 2482000 KHz @ 40000 KHz), (N/A, 2000 mBm), (N/A)
>>> cfg80211:   (2474000 KHz - 2494000 KHz @ 20000 KHz), (N/A, 2000 mBm), (N/A)
>>> cfg80211:   (5170000 KHz - 5250000 KHz @ 80000 KHz, 160000 KHz AUTO), (N/A, 2000 mBm), (N/A)
>>> cfg80211:   (5250000 KHz - 5330000 KHz @ 80000 KHz, 160000 KHz AUTO), (N/A, 2000 mBm), (0 s)
>>> cfg80211:   (5490000 KHz - 5730000 KHz @ 160000 KHz), (N/A, 2000 mBm), (0 s)
>>> cfg80211:   (5735000 KHz - 5835000 KHz @ 80000 KHz), (N/A, 2000 mBm), (N/A)
>>> cfg80211:   (57240000 KHz - 63720000 KHz @ 2160000 KHz), (N/A, 0 mBm), (N/A)

**Comment by bagage** [comment]
I edited my previous comment, but I readd it there. Installing kernel version 4.0.0 did actually change wifi stability a lot! System has been running for 15 minutes now without any disconnections!

**Comment by emilio-aburto** [comment]
I'm also interested in this driver (I even mailed lwfinger) but I don't even know where to start reading the code or if is there any book or something that teach me the basics of wireless driver on linux kernels. 

So, lwfinger, if you could give us some directives, please

**Comment by lwfinger** [comment]
For general information on Linux device drivers, you should read http://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0CB8QFjAA&url=http%3A%2F%2Ffree-electrons.com%2Fdoc%2Fbooks%2Fldd3.pdf&ei=shFEVYKrKNbpoAT_9YCQCw&usg=AFQjCNFCvstFu-NyeaqJMr_54WhLo_3vuQ&sig2=m_VnIkiYvfdbt6zSgOsw7Q&bvm=bv.92291466,d.cGU.

The specific details on how the wireless chip works is Realtek's secret. I do not have any of this information, and I do not want it.

**Comment by jamesarbrown** [comment]
Hi, Sorry to jump in here as also having issues with RTL8723be, Ubuntu 15.04 (3.19kernel) HP455G2 all seems ok with system, firmware loaded, no significant errors, but no networks visible.

I have tried many "rmmod rtl8723be" and options like "modprobe fwlps=N ips=N msi=0" but nothing. iwlist scan shows "No Scan Results"

The only discernable issues I can see are -
1) NM reports a "<warn> could not get interface properties: no readable properties for this interface"

2) Whilst modprobe the module the Kernel gives a "AMD-Vi: Event logged [INVALID_DEVICE_REQUEST device=00:00.1 address 0x000000fdf80c0020 flags=0x0a00]

Definitely triggered by the module, but on this machine the device appears to be 00:03.2 if I understand correctly from /sys/devices/pci00000:00/0000:00:03.2/0000:02:00.0/net/wlan0

**Comment by bagage** [comment]
I'll close the issue seems using kernel 4.0 seems to fix most of the issues I encountered since then.
