### ISSUE TITLE
Speed up compile time

### ISSUE THREAD

**Issue by adalvigi** [lwfinger/rtlwifi_new#451]
I was wondering: can we delete the folders of the chips that are not ours in order to save compile time? Should it result in any error? If that's the case, what should we do instead? I'm sure it's wasted time and space compiling everything every time.

**Comment by lwfinger** [comment]
Yes you can, but you will then break future git pulls. The space is insignificant - my tree uses less than 500 MB. You can speed up the compiles by using 'make -jX'. For X, substitute 2 times your number of CPUs. I have a dual core with hyperthreading, thus I use -j9.
