### ISSUE TITLE
HP 15-bs0xx laptop using rtl8723de has difficulty with TL-WA850RE extender.

### ISSUE THREAD

**Issue by plater** [lwfinger/rtlwifi_new#452]
I have a Huawei E5573c-609 Lte wifi router supplying my internet and a TP-link TL-WA850RE extender which supplies the household. The laptop which uses Tumbleweed is regularly updated from home:plater/rtlwifi_new.
The laptop has no problem connecting with the Huawei E5573c-609's SSID but although it used to work just as well with the TP-link the second kernel update in Tumbleweed brought about this problem, it won't connect with the TP-link after a boot. I can "modprobe -r rtl8723de" and then "modprobe -r rtl8723de" and the laptop will connect to the TP-link after about 30 seconds.
[tplinkfailjourn.txt](https://github.com/lwfinger/rtlwifi_new/files/3141852/tplinkfailjourn.txt)
[iwscanandhwinfowlan.txt](https://github.com/lwfinger/rtlwifi_new/files/3141881/iwscanandhwinfowlan.txt)
tplinkfailjourn.txt is journalctl -f output when tplink should connect.

iwscanandhwinfowlan.txt is hwinfo --wlan output and iw wlo1 scan output when tplink ssid:DRIVE1 should connect, the hidden ssid is the Huawei I've excluded the neighbor's ssid's
After modprobe -r / modprobe ssid:DRIVE1 associates .

**Comment by lwfinger** [comment]
The problem is
May 03 14:15:06 ArbutnothL kernel: wlo1: deauthenticating from 70:4f:57:cc:9c:ab by local choice (Reason: 1=UNSPECIFIED)

I have no idea why it is disconnecting, nor any idea why the Tumbleweed kernel update caused the problem. An unspecified deauthentication is hard to debug without having the over-the-air analysis of the radio traffic. Does the same thing happen if you use NetworkManager to control the wifi instead of wicked? I have never been a fan of wicked on any system.

**Comment by plater** [comment]
I changed from NetworkManager because of this problem. I really can't specifically say it was a particular Tumbleweed kernel but it definitely worked with Leap:15.0 and a 4.17 kernel.
Is there a NetworkManager method I can use to debug this? I couldn't connect to the TP-link at all with NetworkManager but I never tried the remove/add module method.

**Comment by plater** [comment]
Changed to NetworkManager, prior to remove/add module it gets to the stage of enter passphrase twice and then gives up. After removing rtl8723de and reinstalling it connects as normal. I'll look for the log.

**Comment by plater** [comment]
[rtl8723debug.txt](https://github.com/lwfinger/rtlwifi_new/files/3144162/rtl8723debug.txt)
The above log is the journal from boot to NetworkManager failing to connect then connecting automatically after I've removed/added module. The next one contains a reboot with a successful connection to the normally hidden Huawei (ARBUTH33) without any module manipulation.
[rtl8723debug2.txt](https://github.com/lwfinger/rtlwifi_new/files/3144182/rtl8723debug2.txt)
I suspect that this is something to do with security. The reason for hiding the Huawei ssid is my neighbors kept on hacking it but have never hacked the TP-link.
Here is the entire NetworkManager log:
[NetworkManager.txt](https://github.com/lwfinger/rtlwifi_new/files/3144186/NetworkManager.txt)

**Comment by plater** [comment]
This might help: The TL-WA850RE says it's mac address is 70:4F:57:CC:9C:AA. The Huawei E5573Cs-609 lists two connections to the TP-link 72:4F:56:CC:9C:AB and 70:4F:56:CC:9C:AA the latter of which connected 1 second earlier.
Huawei's mac address 0c:70:4a:d5:92:a0

**Comment by plater** [comment]
@lwfinger would a debug kernel help or do I need to look for debug firmware for the TL-WA850RE, it's logs are useless atm. How do I get an over the air analysis?

**Comment by plater** [comment]
My main pc has a wired connection to the TL-WA850RE. Is there anyway I can use that? I have a raspberry pi on the network, maybe I can use that?

**Comment by lwfinger** [comment]
That Android app looks very nice; however, it does not provide what we need. The TL-WA850RE is sending something that rtl8723de is not expecting. Until we can independently capture what it is actually sending, then I have no way of fixing the problem. The $20 cost is not very high, but my spouse is already upset with the amount I have spent on various adapters and other hardware.

**Comment by plater** [comment]
My last update was from c73ddb6f66d9e2e08c3ee9feda75a005070e42cd so somewhere between then and the latest Tumbleweed kernel, this problem appears to have gone away using Network manager. I'll check further as network manager slows the time making the connection down.

**Comment by plater** [comment]
This must have been an earlier kernel issue, I haven't had a problem since
