### ISSUE TITLE
Can't install in kernel 5.

### ISSUE THREAD

**Issue by Navayuvan-SB** [lwfinger/rtlwifi_new#454]
I tried to install this driver in ubuntu 19 with kernel 5. But I can't be able to install this throws an error. Can anyone help me out of this?

```
make -C /lib/modules/5.0.0-050000-generic/build M=/home/ns/rtlwifi_new modules
make[1]: *** /lib/modules/5.0.0-050000-generic/build: No such file or directory.  Stop.
make: *** [Makefile:87: all] Error 2

```

**Comment by lwfinger** [comment]
You doi not have the kernel headers for "5.0.0-050000-generic" installed.

**Comment by Navayuvan-SB** [comment]
Yeah, I solved it.  Great work btw : )
