### ISSUE TITLE
No module rtl8822be

### ISSUE THREAD

**Issue by Fudoka** [lwfinger/rtlwifi_new#455]
Downloaded rtlwifi-new-master.zip, unzipped etc.
Ran make, make install without any error messages
`modprobe rtl8822be` returns module not found
I searched kernel modules directories but no sign of rtl8821be
Source directory rtl8822be contains only `trx.c`
Does this mean that rtl882e is not available at the moment?

**Comment by lwfinger** [comment]
I do not ever recommend that you use the zip version. You should install git and get the source with 'git clone'. From then, a source update is just a 'git pull'. No explicit file downloads, or unzipping, AND the source is correct.

On my system, rtl8822be builds correctly and contains files def.h  fw.c  fw.h  hw.c  hw.h  led.c  led.h  Makefile  phy.c  phy.h  reg.h  sw.c  sw.h  trx.c  trx.h

**Comment by Fudoka** [comment]
Excuse my ignorance here, I'm not used to using git. 
I tried `git clone https://github.com/lwfinger/rtlwifi_new`  but the rtl8822be directory still only contains trx.c. I assume I'm cloning the master branch - which branch should I use?
I tried to clone the extended branch (`git clone -b extended https://github.com/lwfinger/rtlwifi_new`) which does seem to have some content in rtl8822be but make throws up `rtlwifi_new/wifi.h:67:21: error: redefinition of ‘skb_put_data’`

**Comment by Fudoka** [comment]
Sorry, clicked on close & comment by accident

**Comment by lwfinger** [comment]
You should use the extended branch. Master is some real old code that is kept around for reasosns I do not remember.

What is the output of the command "uname -r"?

**Comment by Fudoka** [comment]
4.12.14-lp150.12.61-default

**Comment by lwfinger** [comment]
The routine skb_put_data() was added to the kernel in v4.13. The fact that you are seeing this message means that your distro backported that API change to kernel 4.12. Unfortunately, I cannot handle all such changes, thus my code is guaranteed to compile for mainline kernels, but not distro-modified ones.

To fix your code, edit file wifi.h and find the line that says
`#if (LINUX_VERSION_CODE < KERNEL_VERSION(4, 13, 0))`
It will be at line 66. Change the "4, 13, 0" to "4, 12, 14". Once you do that, this error will be fixed.

By the way, this repo has a newer driver for the RTL8822BE. To use it enter the command
"git checkout origin/rtw88 -b rtw88"
This driver will appear in kernel 5.2.

**Comment by Fudoka** [comment]
Thanks - the edit to wifi.h was the charm. Since I've got it working and I'm about to go on holiday I'll leave the origin branch for the moment. Sorry it took 2 days to get back but my main workstation suddenly refused to boot so fixing that took priority.
