### ISSUE TITLE
rtw88: rfe 3 isn't supported

### ISSUE THREAD

**Issue by schelmo** [lwfinger/rtlwifi_new#457]
my card is a M.2 card
is it already supported ?
what does rfe mean?

uname -a:
Linux zora 5.2.0-rc2-mainline #1 SMP PREEMPT Sun Jun 2 15:02:04 CEST 2019 x86_64 GNU/Linux

from dmesg:
[    7.941572] rtw_pci 0000:04:00.0: rfe 3 isn't supported                                                                                                                                                                                     
[    7.944175] rtw_pci 0000:04:00.0: failed to setup chip efuse info                                                                                                                                                                           
[    7.946761] rtw_pci 0000:04:00.0: failed to setup chip information 

lspci:
04:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTL8822BE 802.11a/b/g/n/ac WiFi adapter
        Subsystem: Lenovo RTL8822BE 802.11a/b/g/n/ac WiFi adapter
        Flags: fast devsel, IRQ 19
        I/O ports at c000 [size=256]
        Memory at 81200000 (64-bit, non-prefetchable) [size=64K]
        Capabilities: [40] Power Management version 3
        Capabilities: [50] MSI: Enable- Count=1/1 Maskable- 64bit+
        Capabilities: [70] Express Endpoint, MSI 00
        Capabilities: [100] Advanced Error Reporting
        Capabilities: [148] Device Serial Number 00-e0-4c-ff-fe-b8-22-01
        Capabilities: [158] Latency Tolerance Reporting
        Capabilities: [160] L1 PM Substates
        Kernel modules: rtwpci

**Comment by lwfinger** [comment]
With kernel 5.2, the RTL8822BE and RTL8822CE are supported with an in-kernel driver. You should not be using a driver from this repo. If you have installed it, uninstall it now.

If the problem persists, you need to report is at linux-wireless@vger.kernel.org, which is where problems with in-kernel drivers are handled.

**Comment by schelmo** [comment]
alright, will report the issue there. thanx
