### ISSUE TITLE
Problem with kernel version 4.15.0-50-generic (RTL8723be) for Ubuntu

### ISSUE THREAD

**Issue by sashankmodali** [lwfinger/rtlwifi_new#458]
Hi,
   I recently upgraded to ubuntu 18.04.2 LTS and the wifi signals were very low. Your drivers worked  well for ubuntu 16.04 with the ant_sel=2 option set. But after the upgrade, they don't seem to work at all.

  I read that you don't guarantee that the drivers would work for Ubuntu, but I don't have any experience in solving this issue. Could you suggest what I could do to fix this? My kernel version is 4.15.0-50-generic.

**Comment by lwfinger** [comment]
I do not guarantee that the drivers will build on any distro that backports kernel APIs so that testing the kernel version is not sufficient. Ubuntu is such a distro.

Are you using the in-kernel driver, or the one from this repo? If still this repo, then ant_sel should work. Are you sure that an update did not remove the configuration? What does this command sequence yield?
```
sudo modprobe -r rtl8723be
sudo modprobe -v rtl8723be
```

**Comment by sashankmodali** [comment]
hi,
I'm using the one from the repo. 

The command sequence yields : -

insmod /lib/modules/4.15.0-50-generic/kernel/net/wireless/cfg80211.ko 
insmod /lib/modules/4.15.0-50-generic/kernel/net/mac80211/mac80211.ko 
insmod /lib/modules/4.15.0-50-generic/updates/dkms/rtlwifi.ko 
insmod /lib/modules/4.15.0-50-generic/updates/dkms/rtl_pci.ko 
insmod /lib/modules/4.15.0-50-generic/updates/dkms/rtl8723-common.ko 
insmod /lib/modules/4.15.0-50-generic/updates/dkms/btcoexist.ko 
insmod /lib/modules/4.15.0-50-generic/updates/dkms/rtl8723be.ko

**Comment by lwfinger** [comment]
insmod /lib/modules/4.15.0-50-generic/updates/dkms/rtl8723be.ko 

That does not say that you have an ant_sel option in use.

**Comment by sashankmodali** [comment]
Hi, 
 Actually I was just playing around with all options to see if any was performing better. At the time I forgot to change it back. Even if I use ant_sel=2, the wifi signals are still weak. 

Here is the updated command sequence result :- 
```
insmod /lib/modules/4.15.0-50-generic/kernel/net/wireless/cfg80211.ko 
insmod /lib/modules/4.15.0-50-generic/kernel/net/mac80211/mac80211.ko 
insmod /lib/modules/4.15.0-50-generic/updates/dkms/rtlwifi.ko 
insmod /lib/modules/4.15.0-50-generic/updates/dkms/rtl_pci.ko 
insmod /lib/modules/4.15.0-50-generic/updates/dkms/rtl8723-common.ko 
insmod /lib/modules/4.15.0-50-generic/updates/dkms/btcoexist.ko 
insmod /lib/modules/4.15.0-50-generic/updates/dkms/rtl8723be.ko ant_sel=2
```

**Comment by lwfinger** [comment]
Did you do a full power-off before testing? With a warm reboot, or a simple module unload/load, the chip may ignore the new settings.

If that answer is yes, then you need to test ant_sel of 1 and 2 using the 'iw dev xxxx scan | egrep "signal|SSID"' test. xxxx should be the actual name of your device as seen in an 'iw dev' command.

**Comment by sashankmodali** [comment]
Hi,
Yeah, I powered off the device. I also tried the scan tests. all of these showed -60 to -80 db for a mobile hotspot less than 5m away depending on where I placed them, sometimes it used to show around -57 for short while, after which again it dropped to -66 db (average).

**Comment by sashankmodali** [comment]
sorry, actually it was less than 2m.

**Comment by sashankmodali** [comment]
Hi, could you give any suggestions?

**Comment by lwfinger** [comment]
No. If you did the signal strength tests correctly, including changing the file in /etc/modprobe.d, AND turning the computer completely off before making the test, then there is nothing I can do. I have tested the code, and it will correctly handle a single antenna.
