### ISSUE TITLE
How can I install rtl8723de on Solus Linux ? I have so many difficulties like building dependecies

### ISSUE THREAD

**Issue by cata0309** [lwfinger/rtlwifi_new#459]

**Comment by lwfinger** [comment]
The requirements are to have make, gcc and the kernel headers installed. As you do not provide any listing of the missing dependencies, I have no idea what is missing. I have never used Solus. A quick check of the Solus Forum shows that you need to install the linux-current-headers package in addition to gcc and make.

**Comment by cata0309** [comment]
I did that but when I do sudo modprobe - r rtl8723de it says Fatal error module not found, the rest of rtls are found but the rtl8723de is not
I downloaded the extended branch and worked with it to not have any doubt I forgot something.
Please do support me in finding a solution. I really appreciate your work!

**Comment by lwfinger** [comment]
Did you do 'sudo make install'?

What is the output of 'ls rtl8723de/*.ko'?

**Comment by cata0309** [comment]
I did, something I have to say is that I did this before on ubuntu based distro and worked like charm. I do not have the distro anymore to say, but I remember that there was a .ko file in all folders but the sudo modprobe was not showing me rtl8723 as a completition option, but I will reinstall it if it helps

**Comment by lwfinger** [comment]
You have not answered my question, thus I am closing the issue.
