### ISSUE TITLE
openSUSE Leap 15.1 RTL8723de can't be installed

### ISSUE THREAD

**Issue by Poncho09** [lwfinger/rtlwifi_new#460]
uname -r: 4.12.14-lp151.28.4-default

Hello i tried install the rtl8723de from the branch extended, but i got the next error:

`#` make
make -C /lib/modules/4.12.14-lp151.28.4-default/build M=/root/extended modules
make[1]: Entering directory '/usr/src/linux-4.12.14-lp151.28.4-obj/x86_64/default'
  CC [M]  /root/extended/base.o
In file included from /root/extended/base.c:26:0:
/root/extended/wifi.h:67:21: error: redefinition of ‘skb_put_data’
 static inline void *skb_put_data(struct sk_buff *skb, const void *data,
                     ^~~~~~~~~~~~
In file included from /usr/src/linux-4.12.14-lp151.28.4/include/linux/if_ether.h:23:0,
                 from /usr/src/linux-4.12.14-lp151.28.4/include/linux/etherdevice.h:25,
                 from /root/extended/wifi.h:33,
                 from /root/extended/base.c:26:
/usr/src/linux-4.12.14-lp151.28.4/include/linux/skbuff.h:1952:21: note: previous definition of ‘skb_put_data’ was here
 static inline void *skb_put_data(struct sk_buff *skb, const void *data,
                     ^~~~~~~~~~~~
In file included from /root/extended/base.c:26:0:
/root/extended/wifi.h:77:21: error: redefinition of ‘skb_put_zero’
 static inline void *skb_put_zero(struct sk_buff *skb, unsigned int len)
                     ^~~~~~~~~~~~
In file included from /usr/src/linux-4.12.14-lp151.28.4/include/linux/if_ether.h:23:0,
                 from /usr/src/linux-4.12.14-lp151.28.4/include/linux/etherdevice.h:25,
                 from /root/extended/wifi.h:33,
                 from /root/extended/base.c:26:
/usr/src/linux-4.12.14-lp151.28.4/include/linux/skbuff.h:1943:21: note: previous definition of ‘skb_put_zero’ was here
 static inline void *skb_put_zero(struct sk_buff *skb, unsigned int len)
                     ^~~~~~~~~~~~
make[4]: *** [/usr/src/linux-4.12.14-lp151.28.4/scripts/Makefile.build:325: /root/extended/base.o] Error 1
make[3]: *** [/usr/src/linux-4.12.14-lp151.28.4/Makefile:1565: _module_/root/extended] Error 2
make[2]: *** [Makefile:152: sub-make] Error 2
make[1]: *** [Makefile:24: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-4.12.14-lp151.28.4-obj/x86_64/default'
make: *** [Makefile:87: all] Error 2

later i tried doing the next:

clone the master and the extended and merge the rtl8723de from extended to master and modify the Makefile from master to recognize the rtl8723de folder, but when i did the make again, got the same error.

a little help here, and thank you.

**Comment by lwfinger** [comment]
You should be using the extended branch. Do not try to merge them.

Your problem is that your disto is backporting kernel APIs from newer kernels into an older kernel. That breaks the tests that depend on the kernel version.

In wifi.h, you will find definitions of skb_put_data() and skb_put_zero() surrounded by
```
#if (LINUX_VERSION_CODE < KERNEL_VERSION(4, 13, 0))
...
#endif 
```
You will need to manually change that 13 to a 12. Then that part of the build will work. If I were to make that change, it would break the code for a lot of users, including me.
