### ISSUE TITLE
broadcom 43228 chipset firmware update

### ISSUE THREAD

**Issue by jshand2015** [lwfinger/rtlwifi_new#461]
i know this is not where to place this issue, but i can't find any other way to contact you.  can you please give me your email address so i can send you the new firmware update from broadcom?

**Comment by jshand2015** [comment]
[hybrid-v35_64-nodebug-pcoem-6_30_223_271.tar.gz](https://github.com/lwfinger/rtlwifi_new/files/3283625/hybrid-v35_64-nodebug-pcoem-6_30_223_271.tar.gz)

hopefully you have the new file for this firmware

**Comment by lwfinger** [comment]
I got the firmware. Thanks. I am now looking at implementing it.
