### ISSUE TITLE
bluetooth not working

### ISSUE THREAD

**Issue by faheemq** [lwfinger/rtlwifi_new#463]
(Bluetooth )i have tried to connect my controller but it will not work and so i was looking  to check if it was Bluetooth was on i i came across a website Ubuntu one to use   dmesg | grep -i blue to check and i got this :

faheem@faheem-HP-Laptop-15-db0xxx:~$ dmesg | grep -i blue
[   36.811664] Bluetooth: Core ver 2.22
[   36.811696] Bluetooth: HCI device and connection manager initialized
[   36.811701] Bluetooth: HCI socket layer initialized
[   36.811705] Bluetooth: L2CAP socket layer initialized
[   36.811713] Bluetooth: SCO socket layer initialized
[   36.901126] Bluetooth: hci0: rtl: examining hci_ver=08 hci_rev=000d lmp_ver=08 lmp_subver=8723
[   36.901130] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_config.bin
[   37.311173] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_config.bin failed with error -2
[   37.311180] Bluetooth: Necessary config file rtl_bt/rtl8723d_config.bin not found
[   37.311187] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_fw.bin
[   37.311207] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_fw.bin failed with error -2
[   37.311209] Bluetooth: hci0: Failed to load rtl_bt/rtl8723d_fw.bin
[   37.324089] Bluetooth: hci0: rtl: examining hci_ver=08 hci_rev=000d lmp_ver=08 lmp_subver=8723
[   37.324094] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_config.bin
[   37.324121] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_config.bin failed with error -2
[   37.324125] Bluetooth: Necessary config file rtl_bt/rtl8723d_config.bin not found
[   37.324132] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_fw.bin
[   37.324142] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_fw.bin failed with error -2
[   37.324144] Bluetooth: hci0: Failed to load rtl_bt/rtl8723d_fw.bin
[   42.201962] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   42.201966] Bluetooth: BNEP filters: protocol multicast
[   42.201973] Bluetooth: BNEP socket layer initialized
[ 2538.487898] Bluetooth: hci0: rtl: examining hci_ver=08 hci_rev=000d lmp_ver=08 lmp_subver=8723
[ 2538.487902] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_config.bin
[ 2538.487934] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_config.bin failed with error -2
[ 2538.487937] Bluetooth: Necessary config file rtl_bt/rtl8723d_config.bin not found
[ 2538.487944] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_fw.bin
[ 2538.487954] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_fw.bin failed with error -2
[ 2538.487955] Bluetooth: hci0: Failed to load rtl_bt/rtl8723d_fw.bin
[ 2538.601874] Bluetooth: hci0: rtl: examining hci_ver=08 hci_rev=000d lmp_ver=08 lmp_subver=8723
[ 2538.601879] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_config.bin
[ 2538.601909] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_config.bin failed with error -2
[ 2538.601912] Bluetooth: Necessary config file rtl_bt/rtl8723d_config.bin not found
[ 2538.601919] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_fw.bin
[ 2538.601931] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_fw.bin failed with error -2
[ 2538.601933] Bluetooth: hci0: Failed to load rtl_bt/rtl8723d_fw.bin
[ 2540.436276] Bluetooth: hci0: rtl: examining hci_ver=08 hci_rev=000d lmp_ver=08 lmp_subver=8723
[ 2540.436282] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_config.bin
[ 2540.436316] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_config.bin failed with error -2
[ 2540.436320] Bluetooth: Necessary config file rtl_bt/rtl8723d_config.bin not found
[ 2540.436326] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_fw.bin
[ 2540.436338] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_fw.bin failed with error -2
[ 2540.436340] Bluetooth: hci0: Failed to load rtl_bt/rtl8723d_fw.bin
[ 2540.472642] Bluetooth: hci0: rtl: examining hci_ver=08 hci_rev=000d lmp_ver=08 lmp_subver=8723
[ 2540.472648] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_config.bin
[ 2540.472685] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_config.bin failed with error -2
[ 2540.472689] Bluetooth: Necessary config file rtl_bt/rtl8723d_config.bin not found
[ 2540.472696] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_fw.bin
[ 2540.472709] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_fw.bin failed with error -2
[ 2540.472710] Bluetooth: hci0: Failed to load rtl_bt/rtl8723d_fw.bin
[ 2545.501855] Bluetooth: hci0: rtl: examining hci_ver=08 hci_rev=000d lmp_ver=08 lmp_subver=8723
[ 2545.501862] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_config.bin
[ 2545.501901] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_config.bin failed with error -2
[ 2545.501906] Bluetooth: Necessary config file rtl_bt/rtl8723d_config.bin not found
[ 2545.501915] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_fw.bin
[ 2545.501929] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_fw.bin failed with error -2
[ 2545.501932] Bluetooth: hci0: Failed to load rtl_bt/rtl8723d_fw.bin
[ 2550.533177] Bluetooth: hci0: rtl: examining hci_ver=08 hci_rev=000d lmp_ver=08 lmp_subver=8723
[ 2550.533182] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_config.bin
[ 2550.533220] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_config.bin failed with error -2
[ 2550.533224] Bluetooth: Necessary config file rtl_bt/rtl8723d_config.bin not found
[ 2550.533232] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_fw.bin
[ 2550.533247] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_fw.bin failed with error -2
[ 2550.533249] Bluetooth: hci0: Failed to load rtl_bt/rtl8723d_fw.bin
[ 2555.563454] Bluetooth: hci0: rtl: examining hci_ver=08 hci_rev=000d lmp_ver=08 lmp_subver=8723
[ 2555.563458] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_config.bin
[ 2555.563485] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_config.bin failed with error -2
[ 2555.563488] Bluetooth: Necessary config file rtl_bt/rtl8723d_config.bin not found
[ 2555.563495] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_fw.bin
[ 2555.563507] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_fw.bin failed with error -2
[ 2555.563509] Bluetooth: hci0: Failed to load rtl_bt/rtl8723d_fw.bin
[ 2560.595953] Bluetooth: hci0: rtl: examining hci_ver=08 hci_rev=000d lmp_ver=08 lmp_subver=8723
[ 2560.595977] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_config.bin
[ 2560.596026] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_config.bin failed with error -2
[ 2560.596029] Bluetooth: Necessary config file rtl_bt/rtl8723d_config.bin not found
[ 2560.596036] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_fw.bin
[ 2560.596047] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_fw.bin failed with error -2
[ 2560.596048] Bluetooth: hci0: Failed to load rtl_bt/rtl8723d_fw.bin
[ 2565.627083] Bluetooth: hci0: rtl: examining hci_ver=08 hci_rev=000d lmp_ver=08 lmp_subver=8723
[ 2565.627087] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_config.bin
[ 2565.627119] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_config.bin failed with error -2
[ 2565.627123] Bluetooth: Necessary config file rtl_bt/rtl8723d_config.bin not found
[ 2565.627130] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_fw.bin
[ 2565.627143] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_fw.bin failed with error -2
[ 2565.627145] Bluetooth: hci0: Failed to load rtl_bt/rtl8723d_fw.bin
[ 2570.662615] Bluetooth: hci0: rtl: examining hci_ver=08 hci_rev=000d lmp_ver=08 lmp_subver=8723
[ 2570.662619] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_config.bin
[ 2570.662650] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_config.bin failed with error -2
[ 2570.662653] Bluetooth: Necessary config file rtl_bt/rtl8723d_config.bin not found
[ 2570.662659] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_fw.bin
[ 2570.662668] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_fw.bin failed with error -2
[ 2570.662670] Bluetooth: hci0: Failed to load rtl_bt/rtl8723d_fw.bin
[ 2575.695937] Bluetooth: hci0: rtl: examining hci_ver=08 hci_rev=000d lmp_ver=08 lmp_subver=8723
[ 2575.695944] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_config.bin
[ 2575.695980] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_config.bin failed with error -2
[ 2575.695984] Bluetooth: Necessary config file rtl_bt/rtl8723d_config.bin not found
[ 2575.695993] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_fw.bin
[ 2575.696008] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_fw.bin failed with error -2
[ 2575.696010] Bluetooth: hci0: Failed to load rtl_bt/rtl8723d_fw.bin
[ 2580.726037] Bluetooth: hci0: rtl: examining hci_ver=08 hci_rev=000d lmp_ver=08 lmp_subver=8723
[ 2580.726041] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_config.bin
[ 2580.726065] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_config.bin failed with error -2
[ 2580.726068] Bluetooth: Necessary config file rtl_bt/rtl8723d_config.bin not found
[ 2580.726075] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_fw.bin
[ 2580.726086] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_fw.bin failed with error -2
[ 2580.726088] Bluetooth: hci0: Failed to load rtl_bt/rtl8723d_fw.bin
[ 2585.768407] Bluetooth: hci0: rtl: examining hci_ver=08 hci_rev=000d lmp_ver=08 lmp_subver=8723
[ 2585.768411] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_config.bin
[ 2585.768448] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_config.bin failed with error -2
[ 2585.768452] Bluetooth: Necessary config file rtl_bt/rtl8723d_config.bin not found
[ 2585.768461] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_fw.bin
[ 2585.768472] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_fw.bin failed with error -2
[ 2585.768473] Bluetooth: hci0: Failed to load rtl_bt/rtl8723d_fw.bin
[ 2590.801715] Bluetooth: hci0: rtl: examining hci_ver=08 hci_rev=000d lmp_ver=08 lmp_subver=8723
[ 2590.801720] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_config.bin
[ 2590.801742] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_config.bin failed with error -2
[ 2590.801745] Bluetooth: Necessary config file rtl_bt/rtl8723d_config.bin not found
[ 2590.801751] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_fw.bin
[ 2590.801760] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_fw.bin failed with error -2
[ 2590.801761] Bluetooth: hci0: Failed to load rtl_bt/rtl8723d_fw.bin
[ 2595.835243] Bluetooth: hci0: rtl: examining hci_ver=08 hci_rev=000d lmp_ver=08 lmp_subver=8723
[ 2595.835248] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_config.bin
[ 2595.835312] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_config.bin failed with error -2
[ 2595.835317] Bluetooth: Necessary config file rtl_bt/rtl8723d_config.bin not found
[ 2595.835342] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_fw.bin
[ 2595.835352] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_fw.bin failed with error -2
[ 2595.835353] Bluetooth: hci0: Failed to load rtl_bt/rtl8723d_fw.bin
[ 2600.866586] Bluetooth: hci0: rtl: examining hci_ver=08 hci_rev=000d lmp_ver=08 lmp_subver=8723
[ 2600.866590] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_config.bin
[ 2600.866620] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_config.bin failed with error -2
[ 2600.866623] Bluetooth: Necessary config file rtl_bt/rtl8723d_config.bin not found
[ 2600.866630] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_fw.bin
[ 2600.866640] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_fw.bin failed with error -2
[ 2600.866641] Bluetooth: hci0: Failed to load rtl_bt/rtl8723d_fw.bin
[ 2605.894683] Bluetooth: hci0: rtl: examining hci_ver=08 hci_rev=000d lmp_ver=08 lmp_subver=8723
[ 2605.894687] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_config.bin
[ 2605.894709] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_config.bin failed with error -2
[ 2605.894712] Bluetooth: Necessary config file rtl_bt/rtl8723d_config.bin not found
[ 2605.894718] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_fw.bin
[ 2605.894729] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_fw.bin failed with error -2
[ 2605.894730] Bluetooth: hci0: Failed to load rtl_bt/rtl8723d_fw.bin
[ 2610.927237] Bluetooth: hci0: rtl: examining hci_ver=08 hci_rev=000d lmp_ver=08 lmp_subver=8723
[ 2610.927241] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_config.bin
[ 2610.927273] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_config.bin failed with error -2
[ 2610.927276] Bluetooth: Necessary config file rtl_bt/rtl8723d_config.bin not found
[ 2610.927282] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_fw.bin
[ 2610.927293] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_fw.bin failed with error -2
[ 2610.927294] Bluetooth: hci0: Failed to load rtl_bt/rtl8723d_fw.bin
[ 3779.015212] Bluetooth: RFCOMM TTY layer initialized
[ 3779.015224] Bluetooth: RFCOMM socket layer initialized
[ 3779.015240] Bluetooth: RFCOMM ver 1.11
faheem@faheem-HP-Laptop-15-db0xxx:~$

**Comment by faheemq** [comment]
rtl8723de

**Comment by faheemq** [comment]
i did a pastebin since the one above has lines through it

https://pastebin.com/1yhGt5hr

**Comment by lwfinger** [comment]
The messages say that you do not have the firmware. It is a standard part of the linux-firmware packages, and should be present in /lib/modules/rtl_bt/. If your system is fully updated and the file is not present, then your distro should be notified. Both files listed as missing are needed.

**Comment by yaliv** [comment]
My bluetooth isn't working too.

```
$ sudo modprobe -r btusb
$ lsmod | grep btusb

$ lsusb -t
/:  Bus 05.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/2p, 480M
    |__ Port 1: Dev 2, If 0, Class=Video, Driver=uvcvideo, 480M
    |__ Port 1: Dev 2, If 1, Class=Video, Driver=uvcvideo, 480M
    |__ Port 2: Dev 3, If 0, Class=Human Interface Device, Driver=usbhid, 1.5M
/:  Bus 04.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/4p, 10000M
/:  Bus 03.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/4p, 480M
    |__ Port 4: Dev 2, If 0, Class=Wireless, Driver=, 12M
    |__ Port 4: Dev 2, If 1, Class=Wireless, Driver=, 12M
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/4p, 10000M
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/2p, 480M
$ sudo modprobe btusb
$ lsmod | grep btusb
btusb                  57344  0
btrtl                  20480  1 btusb
btbcm                  16384  1 btusb
btintel                28672  1 btusb
bluetooth             688128  12 btrtl,btintel,btbcm,bnep,btusb
$ lsusb -t
/:  Bus 06.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/1p, 10000M
/:  Bus 05.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/2p, 480M
    |__ Port 1: Dev 2, If 0, Class=Video, Driver=uvcvideo, 480M
    |__ Port 1: Dev 2, If 1, Class=Video, Driver=uvcvideo, 480M
    |__ Port 2: Dev 3, If 0, Class=Human Interface Device, Driver=usbhid, 1.5M
/:  Bus 04.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/4p, 10000M
/:  Bus 03.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/4p, 480M
    |__ Port 4: Dev 2, If 0, Class=Wireless, Driver=btusb, 12M
    |__ Port 4: Dev 2, If 1, Class=Wireless, Driver=btusb, 12M
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/4p, 10000M
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/2p, 480M
$ lsusb
Bus 006 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 005 Device 003: ID 09da:c10a A4Tech Co., Ltd. 
Bus 005 Device 002: ID 13d3:56a2 IMC Networks 
Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 002: ID 13d3:3537 IMC Networks 
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

There I see the device `13d3:3537` is using the `btusb` driver.
But it doesn't work with `bluetoothctl`:

```
$ sudo bluetoothctl
[sudo] password for yahya: 
Agent registered
[bluetooth]# list
[bluetooth]# show
No default controller available
[bluetooth]# power on
No default controller available
```

Nothing is blocked:

```
$ rfkill list
0: phy0: Wireless LAN
	Soft blocked: no
	Hard blocked: no
2: hci0: Bluetooth
	Soft blocked: no
	Hard blocked: no
```

**Comment by DLandDS** [comment]
i got same here in my laptop FX505DT
