### ISSUE TITLE
Stackoverflow question

### ISSUE THREAD

**Issue by user-name-is-taken** [lwfinger/rtlwifi_new#464]
I found [this stackoverflow issue](https://askubuntu.com/questions/1071299/how-to-install-wi-fi-driver-for-realtek-rtl8821ce-on-ubuntu-18-04) about using the rtl8821ce. I saw some issues in this repo saying that the rtw88 branch works for that antenna. I couldn't get it to work, and I don't have the reputation to answer that question. If you answered that question, I and many other 8821ce users would probably switch to your repo.

**Comment by LinuxDonald** [comment]
Official driver https://github.com/alanfox2000/realtek-linux

**Comment by lwfinger** [comment]
Driver rtw88 works for RTL8822BE and RTL8822CE, but not RTL8821CE. I have no drivers for the latter chip.
