### ISSUE TITLE
Question: Why is rtl8822 its own codebase

### ISSUE THREAD

**Issue by ruabmbua** [lwfinger/rtlwifi_new#465]
Hi!

I noticed, that the rtl8822 driver is in its own branch, and that the other drivers are not included within it. Is there any particular reason for that?

I want to know that, because I will try to make rtl8822bu based USB3 wifi sticks work with that driver.

Best Regards,
Roland

**Comment by lwfinger** [comment]
The 8822 driver is completely different from the rtlwifi family. In the mainline kernel, it is in the rtl88 directory and now handled 8822BE and 8822CE. Realtek has said that rtw88 should handle USB, SDIO, and PCI, but for the moment they only have PCI.

I wish you a lot of luck getting RTL8822BU working. Is there some reason that you do not want to use one of the 3 GitHub projects containing that driver?

You might post a request on linux-wireless@vger.kernel.org and to yhchuang@realtek.com asking if there is any progress on the rtw88 driver for 8822BU.
