### ISSUE TITLE
RTL8723DE BLUETOOTH PROBLEM

### ISSUE THREAD

**Issue by pandey246** [lwfinger/rtlwifi_new#466]
<pre><font color="#EF2929"><b>root@pandeyji</b></font>:<font color="#729FCF"><b>~/Downloads/compat-wireless-2010-06-26-p</b></font># sudo make unload
/bin/sh: 1: [: -gt: argument expected
/bin/sh: 1: test: -ge: unexpected operator
/sbin/modprobe: invalid option -- &apos;l&apos;
/sbin/modprobe: invalid option -- &apos;l&apos;
Stoping bluetooth service..
[<font color="#4E9A06"> ok </font>] Stopping bluetooth (via systemctl): bluetooth.service.
● bluetooth.service - Bluetooth service
   Loaded: loaded (/lib/systemd/system/bluetooth.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
     Docs: man:bluetoothd(8)

Jul 27 22:11:17 pandeyji bluetoothd[1575]: Terminating
Jul 27 22:11:17 pandeyji systemd[1]: Stopping Bluetooth service...
Jul 27 22:11:17 pandeyji bluetoothd[1575]: Endpoint unregistered: sender=:1…urce
Jul 27 22:11:17 pandeyji bluetoothd[1575]: Endpoint unregistered: sender=:1…Sink
Jul 27 22:11:17 pandeyji bluetoothd[1575]: Endpoint unregistered: sender=:1…urce
Jul 27 22:11:17 pandeyji bluetoothd[1575]: Endpoint unregistered: sender=:1…Sink
Jul 27 22:11:17 pandeyji bluetoothd[1575]: Stopping SDP server
Jul 27 22:11:17 pandeyji bluetoothd[1575]: Exit
Jul 27 22:11:17 pandeyji systemd[1]: bluetooth.service: Succeeded.
Jul 27 22:11:17 pandeyji systemd[1]: Stopped Bluetooth service.
Hint: Some lines were ellipsized, use -l to show in full.
Unloading mac80211...
modprobe: FATAL: Module mac80211 is in use.
Unloading cfg80211...
modprobe: FATAL: Module cfg80211 is in use.
Unloading rfcomm...
Unloading bnep...
Unloading btusb...
Unloading bluetooth...
modprobe: FATAL: Module bluetooth is in use.
<font color="#EF2929"><b>root@pandeyji</b></font>:<font color="#729FCF"><b>~/Downloads/compat-wireless-2010-06-26-p</b></font># sudo make load
/bin/sh: 1: [: -gt: argument expected
/bin/sh: 1: test: -ge: unexpected operator
/sbin/modprobe: invalid option -- &apos;l&apos;
/sbin/modprobe: invalid option -- &apos;l&apos;
Stoping bluetooth service..
[<font color="#4E9A06"> ok </font>] Stopping bluetooth (via systemctl): bluetooth.service.
● bluetooth.service - Bluetooth service
   Loaded: loaded (/lib/systemd/system/bluetooth.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
     Docs: man:bluetoothd(8)

Jul 27 22:11:17 pandeyji bluetoothd[1575]: Terminating
Jul 27 22:11:17 pandeyji systemd[1]: Stopping Bluetooth service...
Jul 27 22:11:17 pandeyji bluetoothd[1575]: Endpoint unregistered: sender=:1…urce
Jul 27 22:11:17 pandeyji bluetoothd[1575]: Endpoint unregistered: sender=:1…Sink
Jul 27 22:11:17 pandeyji bluetoothd[1575]: Endpoint unregistered: sender=:1…urce
Jul 27 22:11:17 pandeyji bluetoothd[1575]: Endpoint unregistered: sender=:1…Sink
Jul 27 22:11:17 pandeyji bluetoothd[1575]: Stopping SDP server
Jul 27 22:11:17 pandeyji bluetoothd[1575]: Exit
Jul 27 22:11:17 pandeyji systemd[1]: bluetooth.service: Succeeded.
Jul 27 22:11:17 pandeyji systemd[1]: Stopped Bluetooth service.
Hint: Some lines were ellipsized, use -l to show in full.
Unloading mac80211...
modprobe: FATAL: Module mac80211 is in use.
Unloading cfg80211...
modprobe: FATAL: Module cfg80211 is in use.
Unloading bluetooth...
modprobe: FATAL: Module bluetooth is in use.
/sbin/modprobe: invalid option -- &apos;l&apos;
/sbin/modprobe: invalid option -- &apos;l&apos;
Loading ipw2100...
modprobe: FATAL: Module ipw2100 not found in directory /lib/modules/4.19.0-kali5-amd64
Loading ipw2200...
Loading libertas_cs...
Loading usb8xxx...
Loading p54pci...
Loading p54usb...
Loading adm8211...
Loading zd1211rw...
Loading rtl8180...
modprobe: FATAL: Module rtl8180 not found in directory /lib/modules/4.19.0-kali5-amd64
Loading rtl8187...
Loading p54pci...
Loading p54usb...
Loading iwl3945...
Loading iwlagn...
modprobe: FATAL: Module iwlagn not found in directory /lib/modules/4.19.0-kali5-amd64
Loading ath...
Loading ar9170usb...
Loading rtl8180...
modprobe: FATAL: Module rtl8180 not found in directory /lib/modules/4.19.0-kali5-amd64
Loading rtl8187...
Loading rt2400pci...
Loading rt2500pci...
Loading rt61pci...
Loading rt2500usb...
Loading rt73usb...
Loading rndis_wlan...
Loading at76_usb...
modprobe: FATAL: Module at76_usb not found in directory /lib/modules/4.19.0-kali5-amd64
Loading mwl8k...
Loading mac80211_hwsim...
Loading at76c50x_usb...
Loading bluetooth...
Loading btusb...
Loading l2cap...
modprobe: FATAL: Module l2cap not found in directory /lib/modules/4.19.0-kali5-amd64
Loading sco...
modprobe: FATAL: Module sco not found in directory /lib/modules/4.19.0-kali5-amd64
Loading hidp...
Loading rfcomm...
Loading bnep...
./scripts/load.sh: line 21: athload: command not found
./scripts/load.sh: line 23: b43load: command not found
Starting bluetooth service..
[<font color="#4E9A06"> ok </font>] Starting bluetooth (via systemctl): bluetooth.service.
<font color="#8AE234"><b>●</b></font> bluetooth.service - Bluetooth service
   Loaded: loaded (/lib/systemd/system/bluetooth.service; disabled; vendor preset: disabled)
   Active: <font color="#8AE234"><b>active (running)</b></font> since Sat 2019-07-27 22:11:29 IST; 98ms ago
     Docs: man:bluetoothd(8)
 Main PID: 3250 (bluetoothd)
   Status: &quot;Running&quot;
    Tasks: 1 (limit: 4915)
   Memory: 1.0M
   CGroup: /system.slice/bluetooth.service
           └─3250 /usr/lib/bluetooth/bluetoothd

Jul 27 22:11:29 pandeyji bluetoothd[3250]: Starting SDP server
Jul 27 22:11:29 pandeyji bluetoothd[3250]: Bluetooth management interface 1…ized
Jul 27 22:11:29 pandeyji bluetoothd[3250]: <font color="#EF2929"><b>Sap driver initialization failed.</b></font>
Jul 27 22:11:29 pandeyji bluetoothd[3250]: <font color="#EF2929"><b>sap-server: Operation not permit… (1)</b></font>
Jul 27 22:11:29 pandeyji bluetoothd[3250]: Endpoint registered: sender=:1.6…urce
Jul 27 22:11:29 pandeyji bluetoothd[3250]: Endpoint registered: sender=:1.6…Sink
Jul 27 22:11:29 pandeyji bluetoothd[3250]: Endpoint registered: sender=:1.4…urce
Jul 27 22:11:29 pandeyji bluetoothd[3250]: Endpoint registered: sender=:1.4…Sink
Jul 27 22:11:29 pandeyji bluetoothd[3250]: <font color="#EF2929"><b>RFCOMM server failed for Headset…(98)</b></font>
Jul 27 22:11:29 pandeyji bluetoothd[3250]: <font color="#EF2929"><b>RFCOMM server failed for :1.62/P…(98)</b></font>
Hint: Some lines were ellipsized, use -l to show in full.
<font color="#EF2929"><b>root@pandeyji</b></font>:<font color="#729FCF"><b>~/Downloads/compat-wireless-2010-06-26-p</b></font># 
</pre>

in  above code the problem is not solved as only my phone is able to  connect with my laptop.My headphone is not able to connect with  laptop.and the problem is that after reboot bluetooth becomes inactive  and i need to follow the above steps again,everytime.I have rtl8723de  chipset.Plz help me.
--

**Comment by lwfinger** [comment]
I'm not sure that I can solve your problem!!!!!!!!! Your scripts are not any that I am familiar with, and are clearly buggy. It appears that they are unloading all the wifi drivers. You might try blacklisting the rtl8723de driver. The real problem is that Bluetooth coexistence is not built into the wifi driver, and that is not anything that I can fix. All I can say is that Realtek is working on the problem, and that when they have a better driver, it will be made available.
