### ISSUE TITLE
Arch linux 5.2.3-1 dmesg error

### ISSUE THREAD

**Issue by lucenera** [lwfinger/rtlwifi_new#467]
I use Archlinux, I'm on linux-ck-bulldozer, but I assure you that it also happens with the linux version of the distro. When I activate the module, but only when I activate it, I get a series of errors from dmesg. I saw something similar in an old, closed issue. What can be? The kernel without this dirver does not report anything at all.
Look to Sun Jul 28 11:07:12 2019. https://paste.rs/cZc

**Comment by lwfinger** [comment]
What device are you trying to use? The first error in your log is a context switch problem. I have never seen anything likel this.

**Comment by lucenera** [comment]
I try to use this:
Network controller: Realtek Semiconductor Co., Ltd. RTL8822BE 802.11a / b / g / n / ac WiFi adapter
Subsystem: AzureWave RTL8822BE 802.11a / b / g / n / ac WiFi adapter
Flags: bus master, fast devsel, latency 0, IRQ 34
I / O ports at e000 [size = 256]
Memory at fea00000 (64-bit, non-prefetchable) [size = 64K]
Capabilities: <access denied>
Kernel driver in use: rtl8822be
Kernel modules: rtwpci, rtl8822be

The beauty is that everything works, I think. But those strange writings don't convince me. I only happen by uploading this driver.

**Comment by lwfinger** [comment]
With kernel 5.2.3, you do not need to use any code from this repo as the driver is built into the kernel. If you still get these warnings, then you should report them to yhchuang@realtek.com with a Cc to linux-wireless@vger.kernel.org. He is the maintainer for the driver, and that is the official mailing list for kernel wireless driver issues.

**Comment by lucenera** [comment]
With the drivers in the kernel I have no errors indeed.  But there is a known bug whereby with that chip the WiFi is active, but it sees no network on any frequency.  So I'm forced to use this repo.

**Comment by lwfinger** [comment]
As I know nothing of the chip internals, the only change I could make here would be to copy the code from the kernel. That wouldn't help here; however, I think you should report the kernel driver problems on the linux-wireless mailing list.
