### ISSUE TITLE
RTL8821AE on Shuttle WiFi Kit WLN-M on AsRock Deskmini 310 -  WARNING: CPU: 5 PID: 780 at net/mac80211/rx.c:790 ieee80211_rx_napi+0xa91/0xb10 [mac80211]

### ISSUE THREAD

**Issue by vrodic** [lwfinger/rtlwifi_new#468]
Hi, I had some problems with RTL8821AE on Shuttle WiFi Kit WLN-M (AzureWave AW-CB209NF) on AsRock Deskmini 310 associating with APs. 

Latest ubuntu 19.04 kernel (5.0.0-23-generic). As far as I can tell it has the latest code from this repo. 

I've had these symptoms: 

**1.** 
12:23:57 vedran-pc kernel: rtl8821ae: Init MAC failed
12:23:57 vedran-pc NetworkManager[758]: <warn>  [1564741437.9864] device (wlp2s0): device not up after timeout!
12:23:57 vedran-pc NetworkManager[758]: <warn>  [1564741437.9899] Error: failed to open /run/network/ifstate

and the

***2.***
 WARNING: CPU: 5 PID: 0 at net/mac80211/rx.c:790 ieee80211_rx_napi+0xa91/0xb10 [mac80211]
(more details in attached dmesg output file)

I've turned off aspm with aspm=0 parameter in modprobe.d (verified it's set by looking at /sys/module/rtl8821ae/parameters/aspm) and it seems it made the associations more reliable, but the second symptom still appears. 

[dmesg.wifi.txt](https://github.com/lwfinger/rtlwifi_new/files/3475799/dmesg.wifi.txt)
[lspci.txt](https://github.com/lwfinger/rtlwifi_new/files/3475801/lspci.txt)

The second problem doesn't happen on every boot (cold or hot).

EDIT:

unfortunately, the Wifi connection isn't stable, it randomly disconnects from AP, takes time to reconnect a dmesg snippet attached to see the timings
[wifi-unstable.txt](https://github.com/lwfinger/rtlwifi_new/files/3476078/wifi-unstable.txt)

**Comment by wight554** [comment]
dmesg spam seems to be killed with msi=0 (with aspm=0 obv)

**Comment by lwfinger** [comment]
Not all motherboards are the same, which is why those module parameters exist. Good that you fixed things.

**Comment by vrodic** [comment]
Sorry, this was actually not fixed with aspm=0, I edited the issue: 


unfortunately, the Wifi connection isn't stable, it randomly disconnects from AP, takes time to reconnect a dmesg snippet attached to see the timings
