### ISSUE TITLE
Wlan not found at all

### ISSUE THREAD

**Issue by iadegbola** [lwfinger/rtlwifi_new#470]
I can't even find my WLAN after typing iwconfig and following all necessary instructions, it was working before but just started showing adapter not found some few days ago.
![wifinotworking](https://user-images.githubusercontent.com/29735258/63226605-97c45f00-c1d3-11e9-94b4-970124efdcbe.png)

**Comment by iadegbola** [comment]
any help will be appreciated.

**Comment by iadegbola** [comment]
![wifi](https://user-images.githubusercontent.com/29735258/63226620-de19be00-c1d3-11e9-9c76-1b28a743bf51.png)

Wifi adapter is still not found even after trying all necessary methods online.

**Comment by lwfinger** [comment]
iwconfig is obsolete. For it to give accurate results, your kernel needs a special configuration variable that is likely not present. Use 'iw dev' instead.

If your device uses USB to interface, you first need to post the output of 'lsusb'.
If your device uses PCI, Then post the output of 'lspci -nn'.
If you don't know, then post both.
Finally, check the output of the 'dmesg | less' and page through to see if there are any error messages regarding your wirele3ss device.

**Comment by baguzwahyu** [comment]
and my laptop too ???

**Comment by lwfinger** [comment]
@baguzwahyu - Is it possible for you to actually supply information? A "me too" statement does not help.

What make and model of the computer is involved? What operating system?

**Comment by baguzwahyu** [comment]
my laptop is Lenovo b41-35, os ubuntu v18.04, and my wifi driver is RTL8111 / 8168/8411, does not work, you can help...

**Comment by lwfinger** [comment]
Those RTL numbers are for Ethernet, not wifi! Please post the output of 'lspci -nn'.

**Comment by baguzwahyu** [comment]
![Screenshot from 2019-08-21 22-58-47](https://user-images.githubusercontent.com/30652609/63448031-4af8b680-c467-11e9-9803-c462125db53a.png)
this

**Comment by lwfinger** [comment]
Your wifi device is a Broadcom BCM43162. There is no built-in Linux driver. It probably is supported by the hybrid WL driver.

As you probably suspect, I cannot support it.

**Comment by baguzwahyu** [comment]
ohh okay thanks for the response,
I will look for another solution...

**Comment by iadegbola** [comment]
@lwfinger My Wifi started working again today, I did not have to do anything at all, guess it was an Ubuntu Bug, thanks for your help, you can now close this issue.
