### ISSUE TITLE
rtl8192ee driver dies / Init MAC failed

### ISSUE THREAD

**Issue by desuwa** [lwfinger/rtlwifi_new#471]
Hello,

This might be related to other init mac failed issues.
What happens for me is that the driver (or maybe the firmware) crashes shortly after the interface is brought up. Not really sure how to call it but by *crash* I mean that lshw starts returning the following:

```
  *-generic
       description: Wireless interface
       product: Illegal Vendor ID
       vendor: Illegal Vendor ID
       physical id: 0
       bus info: pci@0000:03:00.0
       logical name: wlp3s0
       version: ff
       serial: b8:ee:65:d2:1c:4f
       width: 32 bits
       clock: 66MHz
       capabilities: bus_master vga_palette cap_list ethernet physical wireless
       configuration: broadcast=yes driver=rtl8192ee driverversion=5.0.0-23-generic firmware=N/A latency=255 link=no maxlatency=255 mingnt=255 multicast=yes wireless=IEEE 802.11
       resources: irq:48 ioport:3000(size=256) memory:e0400000-e0403fff
```
lspci -x:
```
03:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8192EE PCIe Wireless Network Adapter (rev ff)
00: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
10: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
20: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
30: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
```
Then, sometimes the driver tries to re-init the hardware back up and I get the Init MAC failed error in dmesg. Otherwise, there are no other error messages. The only way to bring the hardware back up is to reboot.
Kernel version is `5.0.0-23-generic`. PC is a Thinkpad x240 laptop.

I tried to see a bit what could be happening and it seems that if the `interrupt_recognized` function doesn't get called here https://github.com/lwfinger/rtlwifi_new/blob/00c04849dbb3585dc646bd14d489d34064a49d58/pci.c#L974 the driver stays alive.
Fore example, this doesn't crash:
```
static irqreturn_t _rtl_pci_interrupt(int irq, void *dev_id)
{
	// ...
	spin_lock_irqsave(&rtlpriv->locks.irq_th_lock , flags);
	//rtlpriv->cfg->ops->disable_interrupt(hw);
	//rtlpriv->cfg->ops->interrupt_recognized(hw, &inta, &intb);
	//rtlpriv->cfg->ops->enable_interrupt(hw);
	spin_unlock_irqrestore(&rtlpriv->locks.irq_th_lock, flags);
	return ret;
}
```
But this does:
```
static irqreturn_t _rtl_pci_interrupt(int irq, void *dev_id)
{
	// ...
	spin_lock_irqsave(&rtlpriv->locks.irq_th_lock , flags);
	rtlpriv->cfg->ops->disable_interrupt(hw);
	rtlpriv->cfg->ops->interrupt_recognized(hw, &inta, &intb);
	rtlpriv->cfg->ops->enable_interrupt(hw);
	spin_unlock_irqrestore(&rtlpriv->locks.irq_th_lock, flags);
	return ret;
}
```
Same happens if I use the other (_new) firmware.
Also, the alternative driver which is in the extended branch works fine.

Any ideas about what could cause this?

**Comment by lwfinger** [comment]
Well, ignoring interrupts does not seem like a really good way to prevent crashes, other than one essentially turns the device off.

What happens if you comment out the disable and enable lines, but keep the interrupt_recognized call?

The drivers in the extended branch should be used. The master branch has not really been maintained.

**Comment by desuwa** [comment]
> What happens if you comment out the disable and enable lines, but keep the interrupt_recognized call?
Same thing happens.

The driver from the extended branch I was talking about was the one from this archive rtl8192ee_revised.tar.bz2
That one does work so I guess it's not a hardware issue, but it has trouble with libpcap.

**Comment by desuwa** [comment]
> That driver is completely different. I provide the source, but I do not support it.

Oh sure, I know. I'm using it right now, it works fine.
But I was trying to see if there was a way to make the actual rtlwifi driver from this repo work too.

**Comment by lwfinger** [comment]
I am working on that, but it may take a while.
