### ISSUE TITLE
RTL8822BE & Ubuntu 19.04 (kernel 5.0.0.25)

### ISSUE THREAD

**Issue by Maziar123** [lwfinger/rtlwifi_new#472]
Hi 
I have asus gl702z with wireless & Bluetooth RTL8822BE

default boot wireless works but after update gone. no find any AP.

seems master of this repo  not install for this pci wireless

as other comment this forum i try install trw88 branch after make  & install :
sudo modprobe -r r8822be
sudo modprobe rtw88

no any help :-(

restart dmesg | grep rtw88 
module verification failed: signature and/or  required key missing - tainting kernel

**Comment by lwfinger** [comment]
If you want to use ANY external driver module, you absolutely must turn OFF secure boot, or you must find a way to sign the module after if finishes building.

**Comment by Maziar123** [comment]
But secure but disabled in bios !!!

**Comment by lwfinger** [comment]
Did the module load? Perhaps that was just a warning, not an actual error.

**Comment by Maziar123** [comment]
modinfo rtw88
filename:       /lib/modules/5.0.0-25-generic/kernel/drivers/net/wireless/realtek/rtw88/rtw88.ko
license:        GPL
description:    Realtek 802.11ac wireless core module
author:         Realtek Corporation
firmware:       rtw88/rtw8822b_fw.bin
firmware:       rtw88/rtw8822c_fw.bin
srcversion:     AE46566D2EAB6AAE10020DA
depends:        mac80211,cfg80211
retpoline:      Y
name:           rtw88
vermagic:       5.0.0-25-generic SMP mod_unload 
parm:           support_lps:Set Y to enable LPS support (bool)
parm:           debug_mask:Debugging mask (uint)

**Comment by lwfinger** [comment]
Did you mean "not" when you wrote "now"? If so, please run the following:

iw dev
sudo iw dev wlan0 scan | egrep "SSID|signal"

If the first command uses a name other then "wlan0", use that one in the second. Please post the output, and indicate the AP you want to use.
