### ISSUE TITLE
how to use concurrent mode in 8723be

### ISSUE THREAD

**Issue by visbs** [lwfinger/rtlwifi_new#473]
Hi ,
I just wanted to know how to use concurrent_mode(wlan0+p2p-dev-wlan0) for p2p operations, that is presently a single interface named wlan0 is working, but is it possible to use another p2p interface for independent p2p operations without obstructing wlan0.
presently if am using wifi, I'm not able to use p2p operations and if I'm using p2p operations I'm not able to use internet(with wifi).

Any support or tips would be appreciated 

Thanks
Vishal

**Comment by lwfinger** [comment]
Any concurrent mode operations need to be set up with NetworkManager using their ad-hoc method in addition to the one in managed mode.

**Comment by visbs** [comment]
@lwfinger  can you please give me some suggestions to do the same :beginner:
