### ISSUE TITLE
modprobe: ERROR: could not insert 'rtl8723de': Unknown symbol in module, or unknown parameter (see dmesg)

### ISSUE THREAD

**Issue by Pratham19Feb** [lwfinger/rtlwifi_new#476]
i am trying to install wifi driver on HP laptop

sudo modprobe rtl8723de

after this command i got this error

modprobe: ERROR: could not insert 'rtl8723de': Unknown symbol in module, or unknown parameter (see dmesg)

uname -v
#26-Ubuntu SMP Mon Jun 24 09:32:08 UTC 2019

**Comment by alexdev1984** [comment]
same error:
`modprobe: ERROR: could not insert 'rtl8723de': Unknown symbol in module, or unknown parameter (see dmesg)`
if you disable security boot in bios:
`modprobe: ERROR: could not instert 'rtl8723de': Exec format error`

**Comment by lwfinger** [comment]
With that many missing symbols, you have done something quite wrong. I have no idea what it is.

Please redo the "make" and post the first few lines. Also run 'uname -r' and post that result.

**Comment by Pratham19Feb** [comment]
make

make -C /lib/modules/4.18.0-25-generic/build M=/home/prathamesh/rtlwifi_new modules
make[1]: Entering directory '/usr/src/linux-headers-4.18.0-25-generic'
Makefile:970: "Cannot use CONFIG_STACK_VALIDATION=y, please install libelf-dev, libelf-devel or elfutils-libelf-devel"
  Building modules, stage 2.
  MODPOST 19 modules

**Comment by lwfinger** [comment]
Your source version matches the running kernel. A disagreement here is a common reason for modules failing to load.

I recommend that you install the appropriate libelf package so that CONFIG_STACK_VALIDATION works. I do not know what Ubuntu calls the package, but it should be one of the packages listed. If not, a Ubuntu forum would be the correct place to ask.

Did 'sudo make install' work OK?

**Comment by alexdev1984** [comment]
many missing symbols when insmod
[log.insmod_dmesg.txt](https://github.com/lwfinger/rtlwifi_new/files/3632295/log.insmod_dmesg.txt)
[log.insmod.txt](https://github.com/lwfinger/rtlwifi_new/files/3632296/log.insmod.txt)
[log.make_install.txt](https://github.com/lwfinger/rtlwifi_new/files/3632297/log.make_install.txt)
[log.make.txt](https://github.com/lwfinger/rtlwifi_new/files/3632298/log.make.txt)
[log.modprobe_dmesg.txt](https://github.com/lwfinger/rtlwifi_new/files/3632299/log.modprobe_dmesg.txt)
[log.modprobe.txt](https://github.com/lwfinger/rtlwifi_new/files/3632300/log.modprobe.txt)

**Comment by Pratham19Feb** [comment]
sudo make install 

it's working fine.

sudo make install
make -C /lib/modules/4.18.0-25-generic/build M=/home/prathamesh/rtlwifi_new modules
make[1]: Entering directory '/usr/src/linux-headers-4.18.0-25-generic'
  Building modules, stage 2.
  MODPOST 19 modules
make[1]: Leaving directory '/usr/src/linux-headers-4.18.0-25-generic'
Install rtlwifi SUCCESS

**Comment by Pratham19Feb** [comment]
> many missing symbols when insmod
> [log.insmod_dmesg.txt](https://github.com/lwfinger/rtlwifi_new/files/3632295/log.insmod_dmesg.txt)
> [log.insmod.txt](https://github.com/lwfinger/rtlwifi_new/files/3632296/log.insmod.txt)
> [log.make_install.txt](https://github.com/lwfinger/rtlwifi_new/files/3632297/log.make_install.txt)
> [log.make.txt](https://github.com/lwfinger/rtlwifi_new/files/3632298/log.make.txt)
> [log.modprobe_dmesg.txt](https://github.com/lwfinger/rtlwifi_new/files/3632299/log.modprobe_dmesg.txt)
> [log.modprobe.txt](https://github.com/lwfinger/rtlwifi_new/files/3632300/log.modprobe.txt)

can just please explain what we have to do with this file ?

**Comment by alexdev1984** [comment]
> can just please explain what we have to do with this file ?
for @lwfinger
modprobe dmesg error: module: x86/modules: Skipping invalid relocation target, existing value is nonzero for type 1, loc 0000000090ba3dff, val ffffffffc14a3d28

**Comment by lwfinger** [comment]
@Pratham19Feb  - When you use "insmod" to load a module, the system cannot find the dependent modules - they have to be loaded before the others. "modprobe" handles these dependencies but requires that the modules be installed.

When you are posting a large file, then including it as a file is OK, but when you have only a few lines, adding them as a file causes me a lot of work.

Is it possible for me to get ssh access to either of your machines? If so, send me the IP and login credentials to Larry.Finger@lwfinger.net.

**Comment by Pratham19Feb** [comment]
@lwfinger  - I had sent you details, please check your email.
Thanks for your support.

**Comment by lwfinger** [comment]
To both of you, I have made some updates. Please do a 'git pull', 'make',  'sudo make install', and sudo modprobe -v rtl8723de'. If you still get errors, please post the output from the last command, and the error messages from the end of the dmesg output.

**Comment by Pratham19Feb** [comment]
@lwfinger

 insmod /lib/modules/4.18.0-25-generic/kernel/drivers/net/wireless/realtek/rtlwifi/phydm/phydm_mod.ko 
modprobe: ERROR: could not insert 'rtl8723de': Unknown symbol in module, or unknown parameter (see dmesg)














dmseg




[   56.391087] [drm] ring test on 0 succeeded in 1 usecs
[   56.391092] [drm] ring test on 1 succeeded in 1 usecs
[   56.391096] [drm] ring test on 2 succeeded in 1 usecs
[   56.391104] [drm] ring test on 3 succeeded in 4 usecs
[   56.391111] [drm] ring test on 4 succeeded in 4 usecs
[   56.391226] [drm] ib test on ring 0 succeeded in 0 usecs
[   56.391253] [drm] ib test on ring 1 succeeded in 0 usecs
[   56.391327] [drm] ib test on ring 2 succeeded in 0 usecs
[   56.391340] [drm] ib test on ring 3 succeeded in 0 usecs
[   56.391352] [drm] ib test on ring 4 succeeded in 0 usecs
[   69.855581] [drm] probing gen 2 caps for device 8086:9d10 = 1724043/e
[   69.855588] [drm] PCIE gen 3 link speeds already enabled
[   69.876852] [drm] PCIE GART of 2048M enabled (table at 0x0000000000040000).
[   69.876988] radeon 0000:01:00.0: WB enabled
[   69.876990] radeon 0000:01:00.0: fence driver on ring 0 use gpu addr 0x0000000080000c00 and cpu addr 0x00000000c8767277
[   69.876992] radeon 0000:01:00.0: fence driver on ring 1 use gpu addr 0x0000000080000c04 and cpu addr 0x00000000a78da999
[   69.876993] radeon 0000:01:00.0: fence driver on ring 2 use gpu addr 0x0000000080000c08 and cpu addr 0x000000000170d77c
[   69.876994] radeon 0000:01:00.0: fence driver on ring 3 use gpu addr 0x0000000080000c0c and cpu addr 0x00000000d44d625b
[   69.876995] radeon 0000:01:00.0: fence driver on ring 4 use gpu addr 0x0000000080000c10 and cpu addr 0x000000007a921d72
[   70.071945] [drm] ring test on 0 succeeded in 1 usecs
[   70.071950] [drm] ring test on 1 succeeded in 1 usecs
[   70.071954] [drm] ring test on 2 succeeded in 1 usecs
[   70.071962] [drm] ring test on 3 succeeded in 4 usecs
[   70.071969] [drm] ring test on 4 succeeded in 4 usecs
[   70.072003] [drm] ib test on ring 0 succeeded in 0 usecs
[   70.072030] [drm] ib test on ring 1 succeeded in 0 usecs
[   70.072147] [drm] ib test on ring 2 succeeded in 0 usecs
[   70.072162] [drm] ib test on ring 3 succeeded in 0 usecs
[   70.072175] [drm] ib test on ring 4 succeeded in 0 usecs
[   92.846741] Bluetooth: RFCOMM TTY layer initialized
[   92.846754] Bluetooth: RFCOMM socket layer initialized
[   92.846768] Bluetooth: RFCOMM ver 1.11
[  100.727413] rfkill: input handler disabled
[  894.868489] usb 1-1: new high-speed USB device number 4 using xhci_hcd
[  894.996536] usb 1-1: device descriptor read/64, error -32
[  895.232531] usb 1-1: device descriptor read/64, error -32
[  895.468487] usb 1-1: new high-speed USB device number 5 using xhci_hcd
[  895.596518] usb 1-1: device descriptor read/64, error -32
[  895.832514] usb 1-1: device descriptor read/64, error -32
[  895.940515] usb usb1-port1: attempt power cycle
[  897.424087] usb 1-1: new high-speed USB device number 6 using xhci_hcd
[  897.445801] usb 1-1: New USB device found, idVendor=22b8, idProduct=2e82, bcdDevice= 3.18
[  897.445807] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  897.445811] usb 1-1: Product: Moto G (5) Plus
[  897.445814] usb 1-1: Manufacturer: motorola
[  897.445817] usb 1-1: SerialNumber: ZY22446TR5
[  919.588496] usb 1-2: new low-speed USB device number 7 using xhci_hcd
[  919.741308] usb 1-2: New USB device found, idVendor=10c4, idProduct=8108, bcdDevice= 0.00
[  919.741315] usb 1-2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[  919.741319] usb 1-2: Product: USB OPTICAL MOUSE
[  919.741323] usb 1-2: Manufacturer: YSPRINGTECH
[  920.308834] hidraw: raw HID events driver (C) Jiri Kosina
[  920.400147] usbcore: registered new interface driver usbhid
[  920.400148] usbhid: USB HID core driver
[  920.428747] input: YSPRINGTECH USB OPTICAL MOUSE as /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.0/0003:10C4:8108.0001/input/input16
[  920.428877] hid-generic 0003:10C4:8108.0001: input,hidraw0: USB HID v1.11 Mouse [YSPRINGTECH USB OPTICAL MOUSE] on usb-0000:00:14.0-2/input0
[  928.992882] usb 1-1: USB disconnect, device number 6
[  929.424496] usb 1-1: new high-speed USB device number 8 using xhci_hcd
[  929.577695] usb 1-1: New USB device found, idVendor=22b8, idProduct=2e24, bcdDevice= 3.18
[  929.577702] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  929.577706] usb 1-1: Product: Moto G (5) Plus
[  929.577709] usb 1-1: Manufacturer: motorola
[  929.577712] usb 1-1: SerialNumber: ZY22446TR5
[  930.463915] usbcore: registered new interface driver cdc_ether
[  930.515630] rndis_host 1-1:1.0 usb0: register 'rndis_host' at usb-0000:00:14.0-1, RNDIS device, 82:d1:bd:f6:ea:aa
[  930.515782] usbcore: registered new interface driver rndis_host
[  930.537346] rndis_host 1-1:1.0 enp0s20f0u1: renamed from usb0
[  930.588911] IPv6: ADDRCONF(NETDEV_UP): enp0s20f0u1: link is not ready
[ 1251.572898] phydm_mod: Unknown symbol show_it_bb (err 0)
[ 1251.573001] phydm_mod: Unknown symbol rtl_get_hal_edca_param (err 0)
[ 1251.573138] phydm_mod: Unknown symbol show_it_mac (err 0)

**Comment by alexdev1984** [comment]
@lwfinger
```
$ git log -1
commit c73ddb6f66d9e2e08c3ee9feda75a005070e42cd (HEAD -> extended, origin/extended)
Author: Larry Finger <Larry.Finger@lwfinger.net>
Date:   Thu Sep 19 18:52:16 2019 -0500

    rtlwifi: Fix build when CONFIG-RTLWIFI-DEBUG is not set
    
    Signed-off-by: Larry Finger <Larry.Finger@lwfinger.net>

$ make
make -C /lib/modules/4.19.0-5-amd64/build M=/home/aces/Soft/rtlwifi_new modules
make[1]: вход в каталог «/usr/src/linux-headers-4.19.0-5-amd64»
  Building modules, stage 2.
  MODPOST 19 modules
make[1]: выход из каталога «/usr/src/linux-headers-4.19.0-5-amd64»

# make install
make -C /lib/modules/4.19.0-5-amd64/build M=/home/aces/Soft/rtlwifi_new modules
make[1]: вход в каталог «/usr/src/linux-headers-4.19.0-5-amd64»
  Building modules, stage 2.
  MODPOST 19 modules
make[1]: выход из каталога «/usr/src/linux-headers-4.19.0-5-amd64»
Install rtlwifi SUCCESS

# modprobe -v rtl8723de
insmod /lib/modules/4.19.0-5-amd64/kernel/drivers/net/wireless/realtek/rtlwifi/rtlwifi.ko 
modprobe: ERROR: could not insert 'rtl8723de': Exec format error

# dmesg | tail -n 5
[  125.594031] bridge: filtering via arp/ip/ip6tables is no longer available by default. Update your scripts to load br_netfilter if you need this.
[  125.595289] Bridge firewalling registered
[  125.886050] Initializing XFRM netlink socket
[  125.971858] IPv6: ADDRCONF(NETDEV_UP): docker0: link is not ready
[  236.340091] module: x86/modules: Skipping invalid relocation target, existing value is nonzero for type 1, loc 00000000505b8fd1, val ffffffffc13b6f18
```

**Comment by lwfinger** [comment]
@alexdev1984 - This problem may be a kernel problem. See https://lore.kernel.org/patchwork/patch/1091248/ for details. Is it possible for you to try a newer kernel?

One other explanation I have seen is an interaction between gcc and clang. Do you have clang installed?

@Pratham19Feb - My changes fixed the missing _rtl_dbg_trace. That was a real bug and was found in the mainline kernel and is fixed in both places. The other missing globals do not make any sense unless you are getting the rtl_pci module from mainline, where those globals do not exist. If you do a reboot, are the modules loaded correctly?

**Comment by Pratham19Feb** [comment]
Thanks for your reply but I did reboot. But I don't know how to check
whether all the module are working or not.

Can you just please help me with this?

**Comment by alexdev1984** [comment]
i updated from 4.19.0-5 to 4.19.0-6 (newest kernel in debian buster) and get another error:
```
modprobe: ERROR: could not insert 'rtl8723de': Unknown symbol in module, or unknown parameter (see dmesg)
insmod /lib/modules/4.19.0-6-amd64/kernel/drivers/net/wireless/realtek/rtlwifi/phydm/phydm_mod.ko 
[  287.273859] phydm_mod: Unknown symbol show_it_bb (err -2)
[  287.273904] phydm_mod: Unknown symbol show_it_mac (err -2)

```

**Comment by lwfinger** [comment]
@alexdev1984 - that was a kernel problem.

Now you both have the same problem - a stale copy of rtl_pci is being loaded. Try the following:
sudo rm /lib/modules/`uname -r`/kernel/drivers/net/wireless/realtek/rtlwifi/
sudo make install
then reboot. In that first command, the characters that surround the uname are back ticks - a backward single quote. On the English keyboard is under the ~.

**Comment by Pratham19Feb** [comment]
sudo rm /lib/modules/`uname -r`/kernel/drivers/net/wireless/realtek/rtlwifi

rm: cannot remove
'/lib/modules/4.18.0-25-generic/kernel/drivers/net/wireless/realtek/rtlwifi':

 Is a directory

**Comment by Pratham19Feb** [comment]
I remove directory by :

sudo rm -rf  /lib/modules/`uname
-r`/kernel/drivers/net/wireless/realtek/rtlwifi/

And then

sudo make install

make -C /lib/modules/4.18.0-25-generic/build M=/home/prathamesh/rtlwifi_new
modules
make[1]: Entering directory '/usr/src/linux-headers-4.18.0-25-generic'
  Building modules, stage 2.
  MODPOST 19 modules
make[1]: Leaving directory '/usr/src/linux-headers-4.18.0-25-generic'
Install rtlwifi SUCCESS

and then reboot my machine


sudo modprobe -v rtl8723de

insmod
/lib/modules/4.18.0-25-generic/kernel/drivers/net/wireless/realtek/rtlwifi/phydm/phydm_mod.ko

modprobe: ERROR: could not insert 'rtl8723de': Unknown symbol in module, or
unknown parameter (see dmesg)

**Comment by lwfinger** [comment]
Sorry, I missed the closing /.

Are the same globals still missing? Could you start TeamViewer for me to get back on?

**Comment by lwfinger** [comment]
The missing global problem is because you have dkms enabled; however, it is not generating the updated modules. I do not use dkms, nor do I have the expertise to make it work, or to fix it for you.

At a minimum, you need to remove the modules at /lib/modules/`uname -r`/dkms/ and then redo the make install from rtlwifi_new.

**Comment by alexdev1984** [comment]
it works after deleting the directory (kernel/drivers/net/wireless/realtek/rtlwifi). thanks

**Comment by Pratham19Feb** [comment]
@lwfinger 
Now it's working fine.
Thank you for your assistance.

**Comment by AbhishekGoudaSH** [comment]
@lwfinger @Pratham19Feb  
How to remove/disable dkms

**Comment by lwfinger** [comment]
Can anyone help here? I do not use dkms.

**Comment by DanBrown47** [comment]
> @lwfinger @Pratham19Feb
> How to remove/disable dkms

dkms uninstall -k <Kernal Version> <Model of Driver>

**Comment by DanBrown47** [comment]
> @lwfinger @Pratham19Feb
> How to remove/disable dkms

dkms uninstall -k "kernal version" "model number"
