### ISSUE TITLE
rtl8822be: halmac_init_hal failed

### ISSUE THREAD

**Issue by OscarFernandezBatalla** [lwfinger/rtlwifi_new#478]
I have a new HP laptop with Windows and I recently installed Kali Linux 5.2.0
In windows my WiFi works great but not in Linux, I followed the instructions of the README.md file but nothing works.

I read that I should but `aspm=0` in `/etc/modprobe.d/rtl8822be.conf` and so I did but it doesn't work.

When I boot linux I get this error:  `rtl8822be: halmac_init_hal failed`

Any idea? 
Thanks

**Comment by pfagurel** [comment]
Same issue for Debian 10 kernel 4.19.0-6-amd64 on Lenovo Yoga 730 15"

**Comment by lwfinger** [comment]
Please tell me ALL the errors in dmesg. When you just supply the one, I have no idea what might be causing it.

**Comment by OscarFernandezBatalla** [comment]
This are all the errors:

`Sep 20 18:11:08 oscar kernel: [   11.003950] bluetooth hci0: firmware: direct-loading firmware rtl_bt/rtl8822b_fw.bin
Sep 20 18:11:08 oscar kernel: [   11.003985] Bluetooth: hci0: RTL: rtl: loading rtl_bt/rtl8822b_config.bin
Sep 20 18:11:08 oscar kernel: [   11.003985] 
Sep 20 18:11:08 oscar kernel: [   11.093464] bluetooth hci0: firmware: direct-loading firmware rtl_bt/rtl8822b_config.bin
Sep 20 18:11:08 oscar kernel: [   11.093501] Bluetooth: hci0: RTL: cfg_sz 14, total sz 20270
Sep 20 18:11:08 oscar kernel: [   11.093501] 
Sep 20 18:11:08 oscar kernel: [   11.149853] snd_hda_codec_realtek hdaudioC0D0: autoconfig for ALC295: line_outs=1 (0x14/0x0/0x0/0x0/0x0) type:speaker
Sep 20 18:11:08 oscar kernel: [   11.149857] snd_hda_codec_realtek hdaudioC0D0:    speaker_outs=0 (0x0/0x0/0x0/0x0/0x0)
Sep 20 18:11:08 oscar kernel: [   11.149859] snd_hda_codec_realtek hdaudioC0D0:    hp_outs=1 (0x21/0x0/0x0/0x0/0x0)
Sep 20 18:11:08 oscar kernel: [   11.149861] snd_hda_codec_realtek hdaudioC0D0:    mono: mono_out=0x0
Sep 20 18:11:08 oscar kernel: [   11.149862] snd_hda_codec_realtek hdaudioC0D0:    inputs:
Sep 20 18:11:08 oscar kernel: [   11.149864] snd_hda_codec_realtek hdaudioC0D0:      Mic=0x19
Sep 20 18:11:08 oscar kernel: [   11.149866] snd_hda_codec_realtek hdaudioC0D0:      Internal Mic=0x12
Sep 20 18:11:08 oscar kernel: [   11.426703] input: HDA Intel PCH Mic as /devices/pci0000:00/0000:00:1f.3/sound/card0/input17
Sep 20 18:11:08 oscar kernel: [   11.426740] input: HDA Intel PCH Headphone as /devices/pci0000:00/0000:00:1f.3/sound/card0/input18
Sep 20 18:11:08 oscar kernel: [   11.426774] input: HDA Intel PCH HDMI/DP,pcm=3 as /devices/pci0000:00/0000:00:1f.3/sound/card0/input19
Sep 20 18:11:08 oscar kernel: [   11.426805] input: HDA Intel PCH HDMI/DP,pcm=7 as /devices/pci0000:00/0000:00:1f.3/sound/card0/input20
Sep 20 18:11:08 oscar kernel: [   11.426835] input: HDA Intel PCH HDMI/DP,pcm=8 as /devices/pci0000:00/0000:00:1f.3/sound/card0/input21
Sep 20 18:11:08 oscar kernel: [   11.426864] input: HDA Intel PCH HDMI/DP,pcm=9 as /devices/pci0000:00/0000:00:1f.3/sound/card0/input22
Sep 20 18:11:08 oscar kernel: [   11.426894] input: HDA Intel PCH HDMI/DP,pcm=10 as /devices/pci0000:00/0000:00:1f.3/sound/card0/input23
Sep 20 18:11:08 oscar kernel: [   11.627069] rtl8822be: unknown parameter 'ant_sel' ignored
Sep 20 18:11:08 oscar kernel: [   11.627738] halmac: chip_id 0xa, chip_version 0x3
Sep 20 18:11:08 oscar kernel: [   11.647006] rtl8822be: Using firmware rtlwifi/rtl8822befw.bin
Sep 20 18:11:08 oscar kernel: [   11.674694] ieee80211 phy1: Selected rate control algorithm 'rtl_rc'
Sep 20 18:11:08 oscar kernel: [   11.675205] rtlwifi: rtlwifi: wireless switch is on
Sep 20 18:11:08 oscar kernel: [   11.701273] rtl8822be 0000:02:00.0: firmware: direct-loading firmware rtlwifi/rtl8822befw.bin
Sep 20 18:11:08 oscar kernel: [   12.171583] Adding 12468220k swap on /dev/sda7.  Priority:-2 extents:1 across:12468220k FS
Sep 20 18:11:10 oscar kernel: [   17.522692] r8169 0000:04:00.0: firmware: direct-loading firmware rtl_nic/rtl8168h-2.fw
Sep 20 18:11:10 oscar kernel: [   17.522838] Generic Realtek PHY r8169-400:00: attached PHY driver [Generic Realtek PHY] (mii_bus:phy_addr=r8169-400:00, irq=IGNORE)
Sep 20 18:11:10 oscar kernel: [   17.633069] r8169 0000:04:00.0 eth0: Link is Down
Sep 20 18:11:10 oscar kernel: [   17.735473] rtl8822be: halmac_init_hal failed
Sep 20 18:11:10 oscar kernel: [   17.736697] rtl8822be: halmac_init_hal failed
Sep 20 18:11:11 oscar kernel: [   18.176287] rtl8822be: halmac_init_hal failed
Sep 20 18:11:11 oscar kernel: [   18.179683] rtl8822be: halmac_init_hal failed
Sep 20 18:11:13 oscar kernel: [   20.734795] r8169 0000:04:00.0 eth0: Link is Up - 1Gbps/Full - flow control rx/tx
Sep 20 18:11:13 oscar kernel: [   20.734810] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
Sep 20 18:11:17 oscar kernel: [   24.259635] fuse: init (API version 7.31)
Sep 20 18:11:21 oscar kernel: [   27.999848] rtl8822be: halmac_init_hal failed
Sep 20 18:11:21 oscar kernel: [   28.000161] rtl8822be: halmac_init_hal failed
Sep 20 18:11:31 oscar kernel: [   38.002336] rtl8822be: halmac_init_hal failed
Sep 20 18:11:31 oscar kernel: [   38.002982] rtl8822be: halmac_init_hal failed
Sep 20 18:11:41 oscar kernel: [   48.002256] rtl8822be: halmac_init_hal failed
Sep 20 18:11:41 oscar kernel: [   48.002899] rtl8822be: halmac_init_hal failed
Sep 20 18:11:44 oscar kernel: [   51.627740] rfkill: input handler disabled
Sep 20 18:11:51 oscar kernel: [   58.003230] rtl8822be: halmac_init_hal failed
Sep 20 18:11:51 oscar kernel: [   58.004015] rtl8822be: halmac_init_hal failed
Sep 20 18:12:01 oscar kernel: [   68.005197] rtl8822be: halmac_init_hal failed
Sep 20 18:12:01 oscar kernel: [   68.005842] rtl8822be: halmac_init_hal failed`

**Comment by OscarFernandezBatalla** [comment]
Sep 20 18:11:08 oscar kernel: [   11.003950] bluetooth hci0: firmware: direct-loading firmware rtl_bt/rtl8822b_fw.bin
Sep 20 18:11:08 oscar kernel: [   11.003985] Bluetooth: hci0: RTL: rtl: loading rtl_bt/rtl8822b_config.bin
Sep 20 18:11:08 oscar kernel: [   11.003985] 
Sep 20 18:11:08 oscar kernel: [   11.093464] bluetooth hci0: firmware: direct-loading firmware rtl_bt/rtl8822b_config.bin
Sep 20 18:11:08 oscar kernel: [   11.093501] Bluetooth: hci0: RTL: cfg_sz 14, total sz 20270
Sep 20 18:11:08 oscar kernel: [   11.093501] 
Sep 20 18:11:08 oscar kernel: [   11.149853] snd_hda_codec_realtek hdaudioC0D0: autoconfig for ALC295: line_outs=1 (0x14/0x0/0x0/0x0/0x0) type:speaker
Sep 20 18:11:08 oscar kernel: [   11.149857] snd_hda_codec_realtek hdaudioC0D0:    speaker_outs=0 (0x0/0x0/0x0/0x0/0x0)
Sep 20 18:11:08 oscar kernel: [   11.149859] snd_hda_codec_realtek hdaudioC0D0:    hp_outs=1 (0x21/0x0/0x0/0x0/0x0)
Sep 20 18:11:08 oscar kernel: [   11.149861] snd_hda_codec_realtek hdaudioC0D0:    mono: mono_out=0x0
Sep 20 18:11:08 oscar kernel: [   11.149862] snd_hda_codec_realtek hdaudioC0D0:    inputs:
Sep 20 18:11:08 oscar kernel: [   11.149864] snd_hda_codec_realtek hdaudioC0D0:      Mic=0x19
Sep 20 18:11:08 oscar kernel: [   11.149866] snd_hda_codec_realtek hdaudioC0D0:      Internal Mic=0x12
Sep 20 18:11:08 oscar kernel: [   11.426703] input: HDA Intel PCH Mic as /devices/pci0000:00/0000:00:1f.3/sound/card0/input17
Sep 20 18:11:08 oscar kernel: [   11.426740] input: HDA Intel PCH Headphone as /devices/pci0000:00/0000:00:1f.3/sound/card0/input18
Sep 20 18:11:08 oscar kernel: [   11.426774] input: HDA Intel PCH HDMI/DP,pcm=3 as /devices/pci0000:00/0000:00:1f.3/sound/card0/input19
Sep 20 18:11:08 oscar kernel: [   11.426805] input: HDA Intel PCH HDMI/DP,pcm=7 as /devices/pci0000:00/0000:00:1f.3/sound/card0/input20
Sep 20 18:11:08 oscar kernel: [   11.426835] input: HDA Intel PCH HDMI/DP,pcm=8 as /devices/pci0000:00/0000:00:1f.3/sound/card0/input21
Sep 20 18:11:08 oscar kernel: [   11.426864] input: HDA Intel PCH HDMI/DP,pcm=9 as /devices/pci0000:00/0000:00:1f.3/sound/card0/input22
Sep 20 18:11:08 oscar kernel: [   11.426894] input: HDA Intel PCH HDMI/DP,pcm=10 as /devices/pci0000:00/0000:00:1f.3/sound/card0/input23
Sep 20 18:11:08 oscar kernel: [   11.627069] rtl8822be: unknown parameter 'ant_sel' ignored
Sep 20 18:11:08 oscar kernel: [   11.627738] halmac: chip_id 0xa, chip_version 0x3
Sep 20 18:11:08 oscar kernel: [   11.647006] rtl8822be: Using firmware rtlwifi/rtl8822befw.bin
Sep 20 18:11:08 oscar kernel: [   11.674694] ieee80211 phy1: Selected rate control algorithm 'rtl_rc'
Sep 20 18:11:08 oscar kernel: [   11.675205] rtlwifi: rtlwifi: wireless switch is on
Sep 20 18:11:08 oscar kernel: [   11.701273] rtl8822be 0000:02:00.0: firmware: direct-loading firmware rtlwifi/rtl8822befw.bin
Sep 20 18:11:08 oscar kernel: [   12.171583] Adding 12468220k swap on /dev/sda7.  Priority:-2 extents:1 across:12468220k FS
Sep 20 18:11:10 oscar kernel: [   17.522692] r8169 0000:04:00.0: firmware: direct-loading firmware rtl_nic/rtl8168h-2.fw
Sep 20 18:11:10 oscar kernel: [   17.522838] Generic Realtek PHY r8169-400:00: attached PHY driver [Generic Realtek PHY] (mii_bus:phy_addr=r8169-400:00, irq=IGNORE)
Sep 20 18:11:10 oscar kernel: [   17.633069] r8169 0000:04:00.0 eth0: Link is Down
Sep 20 18:11:10 oscar kernel: [   17.735473] rtl8822be: halmac_init_hal failed
Sep 20 18:11:10 oscar kernel: [   17.736697] rtl8822be: halmac_init_hal failed
Sep 20 18:11:11 oscar kernel: [   18.176287] rtl8822be: halmac_init_hal failed
Sep 20 18:11:11 oscar kernel: [   18.179683] rtl8822be: halmac_init_hal failed
Sep 20 18:11:13 oscar kernel: [   20.734795] r8169 0000:04:00.0 eth0: Link is Up - 1Gbps/Full - flow control rx/tx
Sep 20 18:11:13 oscar kernel: [   20.734810] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
Sep 20 18:11:17 oscar kernel: [   24.259635] fuse: init (API version 7.31)
Sep 20 18:11:21 oscar kernel: [   27.999848] rtl8822be: halmac_init_hal failed
Sep 20 18:11:21 oscar kernel: [   28.000161] rtl8822be: halmac_init_hal failed
Sep 20 18:11:31 oscar kernel: [   38.002336] rtl8822be: halmac_init_hal failed
Sep 20 18:11:31 oscar kernel: [   38.002982] rtl8822be: halmac_init_hal failed
Sep 20 18:11:41 oscar kernel: [   48.002256] rtl8822be: halmac_init_hal failed
Sep 20 18:11:41 oscar kernel: [   48.002899] rtl8822be: halmac_init_hal failed
Sep 20 18:11:44 oscar kernel: [   51.627740] rfkill: input handler disabled
Sep 20 18:11:51 oscar kernel: [   58.003230] rtl8822be: halmac_init_hal failed
Sep 20 18:11:51 oscar kernel: [   58.004015] rtl8822be: halmac_init_hal failed
Sep 20 18:12:01 oscar kernel: [   68.005197] rtl8822be: halmac_init_hal failed
Sep 20 18:12:01 oscar kernel: [   68.005842] rtl8822be: halmac_init_hal failed

**Comment by OscarFernandezBatalla** [comment]
Sep 20 18:11:08 oscar kernel: [   10.777246] Bluetooth: hci0: RTL: rtl: examining hci_ver=07 hci_rev=000b lmp_ver=07 lmp_subver=8822
Sep 20 18:11:08 oscar kernel: [   10.777246] 
Sep 20 18:11:08 oscar kernel: [   10.778219] Bluetooth: hci0: RTL: rom_version status=0 version=2
Sep 20 18:11:08 oscar kernel: [   10.778219] 
Sep 20 18:11:08 oscar kernel: [   10.778222] Bluetooth: hci0: RTL: rtl: loading rtl_bt/rtl8822b_fw.bin
Sep 20 18:11:08 oscar kernel: [   10.778222] 
Sep 20 18:11:08 oscar kernel: [   10.851395] snd_hda_intel 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
Sep 20 18:11:08 oscar kernel: [   10.856540] rtw_pci 0000:02:00.0: firmware: failed to load rtw88/rtw8822b_fw.bin (-2)
Sep 20 18:11:08 oscar kernel: [   10.856615] firmware_class: See https://wiki.debian.org/Firmware for information about missing firmware
Sep 20 18:11:08 oscar kernel: [   10.856692] rtw_pci 0000:02:00.0: Direct firmware load for rtw88/rtw8822b_fw.bin failed with error -2
Sep 20 18:11:08 oscar kernel: [   10.856698] rtw_pci 0000:02:00.0: failed to request firmware
Sep 20 18:11:08 oscar kernel: [   10.856768] rtw_pci 0000:02:00.0: failed to load firmware
Sep 20 18:11:08 oscar kernel: [   10.856843] rtw_pci 0000:02:00.0: failed to setup chip efuse info
Sep 20 18:11:08 oscar kernel: [   10.856910] rtw_pci 0000:02:00.0: failed to setup chip information
Sep 20 18:11:08 oscar kernel: [   10.858881] rtw_pci: probe of 0000:02:00.0 failed with error -22
Sep 20 18:11:08 oscar kernel: [   10.972049] rtlwifi: loading out-of-tree module taints kernel.
Sep 20 18:11:08 oscar kernel: [   10.985105] uvcvideo: Found UVC 1.00 device HP Wide Vision HD Camera (04ca:707f)
Sep 20 18:11:08 oscar kernel: [   10.988900] uvcvideo 1-5:1.0: Entity type for entity Extension 4 was not initialized!
Sep 20 18:11:08 oscar kernel: [   10.988905] uvcvideo 1-5:1.0: Entity type for entity Processing 2 was not initialized!
Sep 20 18:11:08 oscar kernel: [   10.988908] uvcvideo 1-5:1.0: Entity type for entity Camera 1 was not initialized!
Sep 20 18:11:08 oscar kernel: [   10.989186] input: HP Wide Vision HD Camera: HP Wi as /devices/pci0000:00/0000:00:14.0/usb1/1-5/1-5:1.0/input/input16
Sep 20 18:11:08 oscar kernel: [   10.989476] usbcore: registered new interface driver uvcvideo
Sep 20 18:11:08 oscar kernel: [   10.989479] USB Video Class driver (1.1.1)
Sep 20 18:11:08 oscar kernel: [   11.003950] bluetooth hci0: firmware: direct-loading firmware rtl_bt/rtl8822b_fw.bin
Sep 20 18:11:08 oscar kernel: [   11.003985] Bluetooth: hci0: RTL: rtl: loading rtl_bt/rtl8822b_config.bin
Sep 20 18:11:08 oscar kernel: [   11.003985] 
Sep 20 18:11:08 oscar kernel: [   11.093464] bluetooth hci0: firmware: direct-loading firmware rtl_bt/rtl8822b_config.bin
Sep 20 18:11:08 oscar kernel: [   11.093501] Bluetooth: hci0: RTL: cfg_sz 14, total sz 20270
Sep 20 18:11:08 oscar kernel: [   11.093501] 
Sep 20 18:11:08 oscar kernel: [   11.149853] snd_hda_codec_realtek hdaudioC0D0: autoconfig for ALC295: line_outs=1 (0x14/0x0/0x0/0x0/0x0) type:speaker
Sep 20 18:11:08 oscar kernel: [   11.149857] snd_hda_codec_realtek hdaudioC0D0:    speaker_outs=0 (0x0/0x0/0x0/0x0/0x0)
Sep 20 18:11:08 oscar kernel: [   11.149859] snd_hda_codec_realtek hdaudioC0D0:    hp_outs=1 (0x21/0x0/0x0/0x0/0x0)
Sep 20 18:11:08 oscar kernel: [   11.149861] snd_hda_codec_realtek hdaudioC0D0:    mono: mono_out=0x0
Sep 20 18:11:08 oscar kernel: [   11.149862] snd_hda_codec_realtek hdaudioC0D0:    inputs:
Sep 20 18:11:08 oscar kernel: [   11.149864] snd_hda_codec_realtek hdaudioC0D0:      Mic=0x19
Sep 20 18:11:08 oscar kernel: [   11.149866] snd_hda_codec_realtek hdaudioC0D0:      Internal Mic=0x12
Sep 20 18:11:08 oscar kernel: [   11.426703] input: HDA Intel PCH Mic as /devices/pci0000:00/0000:00:1f.3/sound/card0/input17
Sep 20 18:11:08 oscar kernel: [   11.426740] input: HDA Intel PCH Headphone as /devices/pci0000:00/0000:00:1f.3/sound/card0/input18
Sep 20 18:11:08 oscar kernel: [   11.426774] input: HDA Intel PCH HDMI/DP,pcm=3 as /devices/pci0000:00/0000:00:1f.3/sound/card0/input19
Sep 20 18:11:08 oscar kernel: [   11.426805] input: HDA Intel PCH HDMI/DP,pcm=7 as /devices/pci0000:00/0000:00:1f.3/sound/card0/input20
Sep 20 18:11:08 oscar kernel: [   11.426835] input: HDA Intel PCH HDMI/DP,pcm=8 as /devices/pci0000:00/0000:00:1f.3/sound/card0/input21
Sep 20 18:11:08 oscar kernel: [   11.426864] input: HDA Intel PCH HDMI/DP,pcm=9 as /devices/pci0000:00/0000:00:1f.3/sound/card0/input22
Sep 20 18:11:08 oscar kernel: [   11.426894] input: HDA Intel PCH HDMI/DP,pcm=10 as /devices/pci0000:00/0000:00:1f.3/sound/card0/input23
Sep 20 18:11:08 oscar kernel: [   11.627069] rtl8822be: unknown parameter 'ant_sel' ignored
Sep 20 18:11:08 oscar kernel: [   11.627738] halmac: chip_id 0xa, chip_version 0x3
Sep 20 18:11:08 oscar kernel: [   11.647006] rtl8822be: Using firmware rtlwifi/rtl8822befw.bin
Sep 20 18:11:08 oscar kernel: [   11.674694] ieee80211 phy1: Selected rate control algorithm 'rtl_rc'
Sep 20 18:11:08 oscar kernel: [   11.675205] rtlwifi: rtlwifi: wireless switch is on
Sep 20 18:11:08 oscar kernel: [   11.701273] rtl8822be 0000:02:00.0: firmware: direct-loading firmware rtlwifi/rtl8822befw.bin
Sep 20 18:11:08 oscar kernel: [   12.171583] Adding 12468220k swap on /dev/sda7.  Priority:-2 extents:1 across:12468220k FS
Sep 20 18:11:10 oscar kernel: [   17.522692] r8169 0000:04:00.0: firmware: direct-loading firmware rtl_nic/rtl8168h-2.fw
Sep 20 18:11:10 oscar kernel: [   17.522838] Generic Realtek PHY r8169-400:00: attached PHY driver [Generic Realtek PHY] (mii_bus:phy_addr=r8169-400:00, irq=IGNORE)
Sep 20 18:11:10 oscar kernel: [   17.633069] r8169 0000:04:00.0 eth0: Link is Down
Sep 20 18:11:10 oscar kernel: [   17.735473] rtl8822be: halmac_init_hal failed
Sep 20 18:11:10 oscar kernel: [   17.736697] rtl8822be: halmac_init_hal failed
Sep 20 18:11:11 oscar kernel: [   18.176287] rtl8822be: halmac_init_hal failed
Sep 20 18:11:11 oscar kernel: [   18.179683] rtl8822be: halmac_init_hal failed
Sep 20 18:11:13 oscar kernel: [   20.734795] r8169 0000:04:00.0 eth0: Link is Up - 1Gbps/Full - flow control rx/tx
Sep 20 18:11:13 oscar kernel: [   20.734810] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
Sep 20 18:11:17 oscar kernel: [   24.259635] fuse: init (API version 7.31)
Sep 20 18:11:21 oscar kernel: [   27.999848] rtl8822be: halmac_init_hal failed
Sep 20 18:11:21 oscar kernel: [   28.000161] rtl8822be: halmac_init_hal failed
Sep 20 18:11:31 oscar kernel: [   38.002336] rtl8822be: halmac_init_hal failed
Sep 20 18:11:31 oscar kernel: [   38.002982] rtl8822be: halmac_init_hal failed
Sep 20 18:11:41 oscar kernel: [   48.002256] rtl8822be: halmac_init_hal failed
Sep 20 18:11:41 oscar kernel: [   48.002899] rtl8822be: halmac_init_hal failed
Sep 20 18:11:44 oscar kernel: [   51.627740] rfkill: input handler disabled
Sep 20 18:11:51 oscar kernel: [   58.003230] rtl8822be: halmac_init_hal failed
Sep 20 18:11:51 oscar kernel: [   58.004015] rtl8822be: halmac_init_hal failed
Sep 20 18:12:01 oscar kernel: [   68.005197] rtl8822be: halmac_init_hal failed
Sep 20 18:12:01 oscar kernel: [   68.005842] rtl8822be: halmac_init_hal failed

**Comment by lwfinger** [comment]
The log says that firmware /lib/firmware/rtw88/rtw8822b_fw.bin is not available. Do a 'git pull' followed by 'sudo make install'. I just added the firmware to the repo.

**Comment by OscarFernandezBatalla** [comment]
Done, but when I do sudo make install it shows this error (sorry for the spanish):

`make -C /lib/modules/5.2.0-kali2-amd64/build M=/root/rtlwifi_new modules
make[1]: se entra en el directorio '/usr/src/linux-headers-5.2.0-kali2-amd64'
  Building modules, stage 2.
  MODPOST 2 modules
make[1]: se sale del directorio '/usr/src/linux-headers-5.2.0-kali2-amd64'
Making backups
cp: el objetivo '/lib/firmware/rtw88/.' no es un directorio
make: *** [Makefile:58: install] Error 1
`
It says that /lib/firmware/rtw88/. its not a directory, what can I do?

**Comment by lwfinger** [comment]
There was a typo in my changes. Do a 'git pull' and 'sudo make install' again.

**Comment by OscarFernandezBatalla** [comment]
I can't believe it, days looking for that solution, networking working great, any error booting.

Thank you so so much.

**Comment by OscarFernandezBatalla** [comment]
Oh my god, days looking for this solution, networking working great, any error booting.
Thank you so so much.

**Comment by lwfinger** [comment]
When something goes wrong, ALWAYS look at the dmesg output and find the FIRST place that shows trouble. All kinds of errors may show up later, but the first one will be the most important.

**Comment by d3m0git** [comment]
Sorry to post in a previous post but would you mind if you note on the exact lines as i am still getting the same error as above?  @OscarFernandezBatalla

**Comment by OscarFernandezBatalla** [comment]
> Sorry to post in a previous (aged) thread but would you mind if you note on the exact lines as i am still getting the same error as above?  @OscarFernandezBatalla

Sorry I don't understand, what do you need exactly?

**Comment by d3m0git** [comment]
> > Sorry to post in a previous (aged) thread but would you mind if you note on the exact lines as i am still getting the same error as above?  @OscarFernandezBatalla
> 
> Sorry I don't understand, what do you need exactly?

As you did, I am receiving /lib/firmware/rtw88/. its not a directory; If you have some time, could you please note on your exact lines you put in your terminal?

**Comment by OscarFernandezBatalla** [comment]
> > > Sorry to post in a previous (aged) thread but would you mind if you note on the exact lines as i am still getting the same error as above?  @OscarFernandezBatalla
> > 
> > Sorry I don't understand, what do you need exactly?
> 
> As you did, I am receiving /lib/firmware/rtw88/. its not a directory; If you have some time, could you please note on your exact lines you put in your terminal? 

I just did what lwfinger told me to do, there was a typo in the script, with a new git pull and sudo make install the problem was resolved.

It's the only thing I can tell you... But maybe I can help you with another thing: Your problem is that Linux don't recognize WiFi? If that is the case I can tell you how I managed to make it work in another computer.

**Comment by d3m0git** [comment]
> > > > Sorry to post in a previous (aged) thread but would you mind if you note on the exact lines as i am still getting the same error as above?  @OscarFernandezBatalla
> > > 
> > > 
> > > Sorry I don't understand, what do you need exactly?
> > 
> > 
> > As you did, I am receiving /lib/firmware/rtw88/. its not a directory; If you have some time, could you please note on your exact lines you put in your terminal?
> 
> I just did what lwfinger told me to do, there was a typo in the script, with a new git pull and sudo make install the problem was resolved.
> 
> It's the only thing I can tell you... But maybe I can help you with another thing: Your problem is that Linux don't recognize WiFi? If that is the case I can tell you how I managed to make it work in another computer.

I have the latest Debian installed and the error in this thread won't allow me to boot into the desktop environment.  To make up for this I have purchased (an upgrade) to Intel WiFi 6 AX200 AX200NGW with the hope that this will go away.  I think it beneficial not just for me but for everyone to have any solution to such issues so i would encourage you to outline the steps into how you resolved the issue at hand?  Many thanks.

**Comment by OscarFernandezBatalla** [comment]
> > > > > Sorry to post in a previous (aged) thread but would you mind if you note on the exact lines as i am still getting the same error as above?  @OscarFernandezBatalla
> > > > 
> > > > 
> > > > Sorry I don't understand, what do you need exactly?
> > > 
> > > 
> > > As you did, I am receiving /lib/firmware/rtw88/. its not a directory; If you have some time, could you please note on your exact lines you put in your terminal?
> > 
> > I just did what lwfinger told me to do, there was a typo in the script, with a new git pull and sudo make install the problem was resolved.
> > 
> > It's the only thing I can tell you... But maybe I can help you with another thing: Your problem is that Linux don't recognize WiFi? If that is the case I can tell you how I managed to make it work in another computer.
> 
> I have the latest Debian installed and the error in this thread won't allow me to boot into the desktop environment.  To make up for this I have purchased (an upgrade) to Intel WiFi 6 AX200 AX200NGW with the hope that this will go away.  I think it beneficial not just for me but for everyone to have any solution to such issues so i would encourage you to outline the steps into how you resolved the issue at hand?  Many thanks.



What worked for me was this: (tried in Kali Linux):

(You must reinstall Debian!)

1) Download the firmware of this repo and put the folders in the root of an empty usb.

2) reinstall Debian, with the usb connected, when asks for keyboard configuration do a ctrl + alt + F2. A terminal will pop up.

3) mount the usb and put them in a new folder 'firmware' in tmp folder. (There are tutorials in YouTube)

4) copy the folder created in /lib

5) ctrl + F5 to continue with the installation

Tell me if this resolved your issue!
