### ISSUE TITLE
Rtl8822be not found, kali linux

### ISSUE THREAD

**Issue by TamburiniAlberto** [lwfinger/rtlwifi_new#479]
Hi,

I have installed Kali Linux with kernel 5.2.9 (this information went from `uname -v` which response is: `#1 SMP Debian 5.2.9-2kali1 (2019-08-22)`.

Using `lspci | grep Wireless` i found nothing, so i used `lspci | grep Network` and i fuond:
`02:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8822BE 802.11a/b/g/n/ac WiFi adapter`.

I downloaded the git, start `make` and `make install`, everything correct. So, i wrote `modprobe -r rtl8822be`, response `modprobe: FATAL: Module rtl8822be not found` (no difference with upper case). Then i wrote `modprobe rtl8822be` with response `modprobe: FATAL: Module rtl8822be not found in directory /lib/modules/5.2.0-kali2-amd64`.

Before all that i blacklisted rtw88 and rtwpci.

**Comment by lwfinger** [comment]
Why did you blacklist those two drivers?

The driver for rtw8822be is in kernel 5.2. Use the one from your kernel!!

**Comment by TamburiniAlberto** [comment]
Because those two never worked. So i searched a solution in internet, and a thread suggested to remove them and install rtl.

**Comment by lwfinger** [comment]
You need the rtw88 branch. Without it, no 8822X drivers.

**Comment by TamburiniAlberto** [comment]
I remove the blacklist, nothing is changed.
So, i installed the previous version of kali (2019.2, with older kernel) and now the wifi driver is ok. 
Thank you very much for the support!

**Comment by lwfinger** [comment]
You do not show me a problem. I think the rtw88 driver from the kernel is installed.
