### ISSUE TITLE
firmware load for rtw88/rtw8822b_fw.bin failed

### ISSUE THREAD

**Issue by scorchedo** [lwfinger/rtlwifi_new#480]
[   14.789589] rtw_pci 0000:3d:00.0: firmware: failed to load rtw88/rtw8822b_fw.bin (-2)
[   14.789664] rtw_pci 0000:3d:00.0: Direct firmware load for rtw88/rtw8822b_fw.bin failed with error

**Comment by lwfinger** [comment]
So? Does firmware file exist in /lib/firmware/rtw88? If it does, your distro is crap. If not, do you have the latest firmware update? That file is part of the official firmware package.
