### ISSUE TITLE
rtw88: Incorrect bit rate reported

### ISSUE THREAD

**Issue by adatum** [lwfinger/rtlwifi_new#484]
Ever since the linux kernel switched to the rtw88 driver, bit rate has been incorrectly reported for my RT8822BE. Network Manager shows "Speed 6 Mb/s" and `iwconfig` reports "Bit Rate=6.5 Mb/s", constantly without any change in values. 

However, the performance is not affected. `iperf3` shows 40-60 Mb/s (reasonable given the device's location). It is just the reported bit rate that seems wrong.

Fedora 30, currently on kernel 5.2.17.

**Comment by lwfinger** [comment]
This repo only follows mainline, but lags behind as I have limited time. Any bugs for this driver that can be duplicated with mainline should be reported to linux-wireless@vger.kernel.org.
