### ISSUE TITLE
Bluetooth stuttering issue on RTL8822BE

### ISSUE THREAD

**Issue by mkykadir** [lwfinger/rtlwifi_new#485]
I have Ubuntu 19.04 with Kernel 5.0.0-31 version. I have stuttering issues with my aptX supporting Headphones. I switched from Windows 10 due to same issue and I am having this problem, again, on Ubuntu as well. I have Lenovo Legion Y530 machine with RTL8822BE WiFi/Bluetooth adapter on it and [Lenovo support team replied this issue for Windows 10](https://forums.lenovo.com/t5/Gaming-Laptops/Legion-Y530-bluetooth-stuttering-on-headphones/m-p/4469492#M28775) as Microsoft's issue but it also happens on Ubuntu; I think it is driver or device related issue. Headphones are fine by the way. Are there any investigations or any other reports for RTL8822BE's about Bluetooth stuttering issues?

**Comment by shyamjos** [comment]
I am also facing this issue on ubuntu 19.10, have you able to fix it? My bluetooth speaker disconnects after every few seconds and shuttering and audio loss issue with my bluetooth headset

**Comment by mkykadir** [comment]
I've switched to Windows 10 with latest updates and problem still happens on, I tried different headphones without aptX capability there is no stuttering issue on them but with my head phones that support aptX, I have stuttering issues

**Comment by mkykadir** [comment]
Actually it seems problem is solved when I disable Nvidia GeForce device from device manager, I had Nvidia's GeForce device drivers installed on the system also.

**Comment by mkykadir** [comment]
I have installed Linux Mint 19.2 with Linux Kernel 5.3.0-24 and I don't have stuttering issues any more. I think problem is highly related with Windows 10 or driver of Realtek for Windows 10.

**Comment by lwfinger** [comment]
I do not do Bluetooth, but I emphatically do not do Windows!!!!! Glad that the newer kernels make your situation better.

**Comment by mkykadir** [comment]
I was having this issue on Ubuntu 19.04, I couldn't remember de kernel version, but it should be default which is provided with Ubuntu 19.04.
