### ISSUE TITLE
make fails with: fail to inizialize plugin structleak

### ISSUE THREAD

**Issue by Zamundaaa** [lwfinger/rtlwifi_new#487]
If I try to make the extended branch then it fails with the output:

> make -C /lib/modules/5.3.4-1-MANJARO/build M=/home/xaver/git/rtlwifi_new modules
make[1]: Entering directory '/usr/lib/modules/5.3.4-1-MANJARO/build'
  CC [M]  /home/xaver/git/rtlwifi_new/btcoexist/halbtc8192e2ant.o
cc1: error: incompatible gcc/plugin versions
cc1: error: fail to initialize plugin ./scripts/gcc-plugins/structleak_plugin.so
make[3]: *** [scripts/Makefile.build:281: /home/xaver/git/rtlwifi_new/btcoexist/halbtc8192e2ant.o] Error 1
make[2]: *** [scripts/Makefile.build:497: /home/xaver/git/rtlwifi_new/btcoexist] Error 2
make[1]: *** [Makefile:1624: _module_/home/xaver/git/rtlwifi_new] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.3.4-1-MANJARO/build'
make: *** [Makefile:85: all] Error 2

The same error also appears when trying to compile with gcc 8 instead of 9.2.
I'm on Manjaro and this has been like this for a long time, tried the manual install just now only. Before that I simply used the AURpkg rtlwifi_new-extended-dkms and it would always work for kernel 4.19 but with kernel 5.3 and 5.4rc1 it fails to compile.

**Comment by lwfinger** [comment]
This is a gcc error in your Manjaro installation. It is nothing I can fix.

**Comment by Zamundaaa** [comment]
With the kernels recompiled with gcc 9.2 it indeed works again
