### ISSUE TITLE
rtl8723de folder is empty

### ISSUE THREAD

**Issue by aruone** [lwfinger/rtlwifi_new#488]
there is only one trx.c file in this folder inside the repository

**Comment by Feanor1397** [comment]
rtl8723de code is in extended branch
https://github.com/lwfinger/rtlwifi_new/tree/extended

**Comment by lwfinger** [comment]
He gave you the right answer. You always need to be aware of the branch you are using:

master - code that essentially matches the kernel
extended - the only one with rtl8723de
rtw88 - code for 8822be and 8822ce
