### ISSUE TITLE
rtl8723de - Can't connect to a PEAP wifi network - "Driver Doesn't support TDLS Channel switching"

### ISSUE THREAD

**Issue by mahesh-hegde** [lwfinger/rtlwifi_new#489]
Relatively noob here. I have an RTL8723DE and trying to connect to a wifi network (PEAP & then mschapv2)

It fails & wpa_supplicant falls to state DORMANT

I don't know what is wrong - if it is driver not support TDLS channel switching or some above layer.

```
wlp3s0: RSN: flushing PMKID list in the driver
nl80211: flush PMKIDs
wlp3s0: Setting scan request: 0.100000 sec
TDLS: TDLS operation not supported by driver
TDLS: Driver uses internal link setup
TDLS: Driver does not support TDLS channel switching
wlp3s0: WPS: UUID based on MAC Address: 028cb22c-2155-553a-8653-37b93818a94c
ENGINE: Loading dynamic engine
ENGINE: Loading dynamic engine
EAPOL: SUPP_PAE entering state DISCONNECTED
EAPOL: Supplicant port status: Unauthorized
nl80211: Skip set_supp_port (unauthorized) while not associated.
EAPOL: KEY_RX entering state NO_KEY_RECEIVE
EAPOL: SUPP_BE entering state INITIALIZE
EAP: EAP entering state DISABLED
P2P: Add operating class 81
P2P: Channels - hexdump (len=13) 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d
P2P: Own listen channel: 81:11
P2P: Random operating channel: 81:6
P2P: Initialized
P2P: channels: 81:1,2,3,4,5,6,7,8,9,10,11,12,13
P2P: cli_channels:
wlp3s0: Added interface wlp3s0
wlp3s0: State: DISCONNECTED -> DISCONNECTED
nl80211: Set wlp3s0 operstate 0->0 (DORMANT)
netlink: Operstate: ifindex=3 linkmode=-1 (no change), operstate=5 (IF_OPER_DORMANT)
Daemonize...
```

**Comment by lwfinger** [comment]
This driver does not support TDLS (802.11z). As there is no indication that the firmware will support such operations, it would make little sense for any modifications to the driver. PEAP should not require that feature. Is it being requested is any of your configuration files?

**Comment by mahesh-hegde** [comment]
Recently I have tried switching distributions to connect properly to university AP but could not. But others have told that these distros are working with same configuration given by authorities. Don't know if it is the reason. But it boils down to the driver I think. I couldn't get any information from network staff regarding this.
