### ISSUE TITLE
Better than latest stock Ubuntu 15.04 kernel, but still unstable on HP Probook 450G2

### ISSUE THREAD

**Issue by AlainTH** [lwfinger/rtlwifi_new#49]
HP Probook 450G2 notebook with Ubuntu 15.04 here (RTL8723BE wlan chip), running Ubunto 15.04 32-bits fully updated.

This new source has significantly improved network throughput under very optimal conditions (right next to the access point). FTP transfers now at > 1 MByte/s compared to 600-800 kBytes/s with the default, fully updated kernel module.

However I am sorry to report that in real-life conditions, performance still is very poor, signal drops to 1Mb/s speed only 20 meters away from AP in direct view (hospital corridor). Roaming between APs is slow and unstable as well and connection drops completely sometimes. Same notebook under Windows 7 gives very decent speed and connection stability in the same places. A whole world of difference... Any hopes for more improvement to come? are issues known and worked on or is it still quite shady at this time? I need to make a decision as to the deployment of these nootebooks and I'd hate having to push them out with Windows aboard (they're being used as thin clients for Citrix-published apps).

**Comment by lwfinger** [comment]
If you are getting error messages logged, I can help. If solving the problem requires knowledge of the internals of the chip, then I am as lost as you.

I will pass your posting on to the Realtek engineer.

**Comment by AlainTH** [comment]
I'll do some more testing and try gathering kernel messages if any. 
Will followup here if anything significant comes up.

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
