### ISSUE TITLE
rtl8822be on Kali Linux - https://termbin.com/pt6t

### ISSUE THREAD

**Issue by tennerty** [lwfinger/rtlwifi_new#490]
Dear lwfinger,

Here is yet another issue with rtl8822be - https://termbin.com/pt6t.

Tried all the guidances I could find on the web (almost 2 straight days spent on that), starting with your guidance for cloning git and making/installing drivers. Unsuccessfully.

Would be glad for any hint.

Thank you in advance

P.S. is that OK that the folder https://github.com/lwfinger/rtlwifi_new/tree/master/rtl8822be contains only one file?

**Comment by lwfinger** [comment]
It is OK that it contains only 1 file because the rtl8822be driver does not exist in THAT branch. What branch are you trying to use?

Does the firmware file /lib/firmware/rtw88/rtw8822b_fw.bin exist? The dmesg output shows that it does not.

**Comment by Feanor1397** [comment]
> P.S. is that OK that the folder https://github.com/lwfinger/rtlwifi_new/tree/master/rtl8822be contains only one file?
It's because code for this module are in extended branch. And looks like driver can't load firmware for this chip. Try to install firmware-realtek or firmware-nonfree packages

**Comment by Feanor1397** [comment]
This firmware are in firmware-nonfree/20190717-1 package or newer

**Comment by lwfinger** [comment]
There was a bug in the Makefile. Do a 'git pull' followed by 'sudo make install'.

**Comment by tennerty** [comment]
> There was a bug in the Makefile. Do a 'git pull' followed by 'sudo make install'.

Thank you, lwfinger! It worked perfectly.

P.S. is there a way for an outside person like me or any other to contribute for all your efforts?

**Comment by tennerty** [comment]
Dear lwfinger, Feanor1397,

Thank you once more very much for your input.

I managed to install the driver and was eventually able to connect to my WiFi network.

However I noticed the connection is not stable. On an occasional basis, sometimes in 3 minutes, sometimes in 20 minutes, depending on the actual WiFi card usage activity, the connection drops, and the WiFi connection options get completely blanked out (no wireless networks could be seen/searched, like if the WiFi card was plugged out from the system).

I also noticed that this happens 100% of the time when I try to connect to a hidden WiFi network.
I also noticed that if I log out and after that instantly log in the system, I get WiFi connection back. But it is the same, unstable, WiFi.

I wonder, is that telling you anything you could suggest me to look into? Anything with the Linux networkmanager?

P.S. is there a way to contribute for all your efforts?

**Comment by lwfinger** [comment]
I can only help you with problems in building the drivers on your system, and when the errors are logged. I do need to update the rtw88 branch to match the kernel version. Watch for a significant update when you pull. Note that I am NOT the author of the code.

If you still have problems with performance and stability, then you need to report such problems to linux-wireless@vger.kernel.org. Be aware, however, that you will need to document your complaint a lot more fully that you have been doing here. You need logs, signal strengths, and as much information as you can provide.

**Comment by lwfinger** [comment]
I just pushed the changes to the rtw88 branch.

**Comment by tennerty** [comment]
thanks for the feedback. much appreciated!
