### ISSUE TITLE
rtl8723be network adapter not working properly(very low signal strength) after upgrading from Ubuntu 19.04 to 19.10

### ISSUE THREAD

**Issue by AllenKVarghese** [lwfinger/rtlwifi_new#491]
Hey, thanks a lot for providing this fix. It worked perfectly while I ran Ubuntu 19.04. But now, for some reason, the make, sudo make install, and those series of commands is not fixing the range issues. Please help me out as I can't stay online without having to sit very close to my modem. Pretty much a noob at this, so if I'm missing some info that you require to diagnose this ieeue, please do let me know.

**Comment by lwfinger** [comment]
When you upgraded, you lost the options file that had the ant_sel information.

**Comment by AllenKVarghese** [comment]
Is there a way to fix this?

**Comment by Feanor1397** [comment]
В письме от пятница, 25 октября 2019 г. 21:24:35 +04 пользователь Allen K. 
Varghese написал:
> Is there a way to fix this?
Just create file in /etc/modprobe.d/rtl8723be.conf and paste this to it

options rtl8723be ant_sel=2

you can try also ant_sel=1 if 2 give no result.
Oh and you need to make full poweroff. sometimes this option not working with 
simple reboot

**Comment by AllenKVarghese** [comment]
> Just create file in /etc/modprobe.d/rtl8723be.conf and paste this to it
> options rtl8723be ant_sel=2

Thanks for the reply @Feanor1397 . But that isn't working either :/
rtl8723be.conf file was already written with options rtl8723be ant_sel=2 when I opened maybe because of the commands I executed earlier:
`sudo tee /etc/modprobe.d/rtl8723be.conf <<< "options rtl8723be ant_sel=2"
`
I don't know why these are not working now. They used to work earlier :/ Please reopen the issue as it's still unresolved. I've attached the codes I ran while inside rtlwifi_new.
https://askubuntu.com/questions/1183785/rtl8723be-network-adapter-not-working-properlyvery-low-signal-strength-after-u

**Comment by Feanor1397** [comment]
Just to be clear what result gives this command?

cat /sys/module/rtl8723be/parameters/ant_sel

**Comment by AllenKVarghese** [comment]
> Just to be clear what result gives this command? cat /sys/module/rtl8723be/parameters/ant_sel

1

**Comment by Feanor1397** [comment]
Ok, try to change ant_sel option to 2 in config file and do complete power off of pc26 окт. 2019 г. 16:43 пользователь "Allen K. Varghese" <notifications@github.com> написал:
Just to be clear what result gives this command? cat /sys/module/rtl8723be/parameters/ant_sel

1

**Comment by AllenKVarghese** [comment]
Changed ant_sel to 2 and then powered off. Logged back in, checked my ant_sel stat and it's returning ant_sel = 2 now. Went back to room away from wifi and the range issue still persists :/

**Comment by lwfinger** [comment]
If neither 1 nor 2 for ant_sel works, then there is little we can do for you. It may be that your walls are too absorbing.

To check the signal being received, please do the following in the room with the AP and the away room::
iw dev
Note the device name in the output above and use it to replace <DEV_NAME> below.
sudo iw <DEV_NAME> scan | egrep "signal|SSID"

Do those commands for both ant_sel of 1 and 2. Post the output.

**Comment by AllenKVarghese** [comment]
> Do those commands for both ant_sel of 1 and 2. Post the output.
ant_sel = 1:
Wifi(near) : signal: -58.00 dBm
Wifi(room): signal: -70.00 dBm

ant_sel = 2:
Wifi(near) : signal: -58.00 dBm
Wifi(room): signal: -76.00 dBm

**Comment by AllenKVarghese** [comment]
> Do those commands for both ant_sel of 1 and 2. Post the output.

ant_sel = 1:
Wifi(near): signal: -58.00 dBm
Wifi(room): signal: -70.00 dBm

ant_sel = 2:
Wifi(near): signal: -58.00 dBm
Wifi(room): signal: -76.00 dBm

**Comment by AllenKVarghese** [comment]
Hey, I think the issue arose due to a corrupt installation of my Ubuntu releases(as I had localized bugs since 18.10 as well). Today I did a fresh install of Ubuntu 19.10 and finally my wifi is working as it should be(max range inside room as well). So thanks for bearing with me and the assistance you guys gave me @lwfinger @Feanor1397  :)

**Comment by AllenKVarghese** [comment]
Wifi issue resolved itself after reinstalling Ubuntu 19.10.
