### ISSUE TITLE
ERROR: could not insert 'rtl8723de': Invalid argument

### ISSUE THREAD

**Issue by pg30** [lwfinger/rtlwifi_new#496]
Few days ago, i dual booted my windows10 machine with ubuntu 18.04 LTS, Since i have a HP laptop ubuntu did'nt recognized wifi hardware so after searching on the internet i installed rtlwifi driver and at first it worked flawlessly. After a day my wifi icon disappeared and it started showing No Wi-Fi adpater plugged, then i deleted the rtlwifi_new folder and tried installing it again but now it is showing this ERROR: could not insert 'rtl8723de': Invalid argument
Plz help me, i have already searched a lot on the internet and i am not getting any solution

These were steps which i followed both the times
git clone https://github.com/lwfinger/rtlwifi_new.git
cd rtlwifi_new
git checkout extended
sudo make install
sudo modprobe -r rtl8723de
sudo modprobe rtl8723de
then Error
ERROR: could not insert 'rtl8723de': Invalid argument

Thanks in advance for help!

**Comment by lwfinger** [comment]
Your kernel source probably does not match the running kernel.
You should never need to delete the existing source. Just do a 'git pull' and you will have the latest.
Whenever the kernel changes, you will need to redo the 'make' and 'make install'.
When you do the make command, the first line will be something like
make -C /lib/modules/<KERNEL VERSION>/build M=/home/finger/rtlwifi_new1 modules
When you do a command 'uname -r', the output line MUST match what you see in the <KERNEL VERSION> of the make output!!

When you report an error, you should also report and pertinent messages from the dmesg command.

**Comment by pg30** [comment]
Sorry since i am a new user i was not aware about this.
My demsg error is:
r8169 0000:01:00.0 eth0: RTL8168h/8111h, 10:e7:c6:7e:d9:e9, XID 541, IRQ 126
[   14.375974] rtlwifi: loading out-of-tree module taints kernel.
[   14.376065] rtlwifi: module verification failed: signature and/or required key missing - tainting kernel
[   14.396155] Bluetooth: hci0: RTL: rtl: examining hci_ver=08 hci_rev=826c lmp_ver=08 lmp_subver=8873
[   14.396156] Bluetooth: hci0: RTL: rtl: unknown IC info, lmp subver 8873, hci rev 826c, hci ver 0008
[   14.396157] Bluetooth: hci0: RTL: rtl: assuming no firmware upload needed
[   15.759337] rtl8723de: `sudo' invalid for parameter `ant_sel'
[   15.759340] rtl8723de: unknown parameter 'modprobe' ignored
[   15.759341] rtl8723de: unknown parameter '-r' ignored
[   15.759342] rtl8723de: unknown parameter 'rtl8723de' ignored
[   15.759342] rtl8723de: unknown parameter '&&' ignored
[   15.759343] rtl8723de: unknown parameter 'sleep' ignored
[   15.759343] rtl8723de: unknown parameter '5' ignored
[   15.759344] rtl8723de: unknown parameter '&&' ignored
[   15.759345] rtl8723de: unknown parameter 'sudo' ignored
[   15.759345] rtl8723de: unknown parameter 'modprobe' ignored
[   15.759346] rtl8723de: unknown parameter 'rtl8723de' ignored

Plz if you could tell me the further steps to fix this issue and install the driver correctly

**Comment by lwfinger** [comment]
You have messed up an options file in directory /etc/modprobe.d.

**Comment by pg30** [comment]
How can I correct it to make it work properly?

**Comment by lwfinger** [comment]
It should contain ONLY one line. "options rtl8723de ant_sel=2" if you need to select the antenna. If not, then the file should be deleted.

**Comment by pg30** [comment]
I installed the driver using : 
git clone https://github.com/smlinux/rtl8723de.git -b 5.0-up
dkms add ./rtl8723de
dkms install rtl8723de/5.1.1.8_21285.20171026_COEX20170111-1414
depmod -a
reboot

but now the wifi connects after rebooting but gives error connecting to any network after sleep or if restart wifi from settings. What can i do for this?

**Comment by pg30** [comment]
Can you tell me how to completely remove your drive so that i can install it again from the scratch, so that all the inconsistencies and incompatibility might be resolved. Will it do?
