### ISSUE TITLE
Can't connect to a WPA2-PEAP-MSCHAPV2 network: other driver (USB adapter) works perfectly fine

### ISSUE THREAD

**Issue by mahesh-hegde** [lwfinger/rtlwifi_new#497]
I have an **rtl8723de**, laptop: **hp 14q-cy0004au** have compiled driver from extended branch.

PC can connect to my personal hotspots just fine. which are WPA2 PSK or similar.

My university AP uses following config:
SSID: STUDENT
Encryption: WPA2-PEAP
Inner Authentication: MSCHAPV2

No module parameters changed. Signal is OK although not as strong as Ralink MT7601U adapter.

But Ralink adapter connects instantaneously while in case of rtl8723de driver only one dot of network manager widget turns green and other doesn't. And it times out.

I am quite new to linux and don't know how to get debug output for networkmanager. If someone tell how, I can provide debug output also.

Thanks..

**Comment by lwfinger** [comment]
There has been a problem with all versions of rtl8192de since kernel v3.18.
It took a while, but I have now found the problems that prevented connection with any AP. If you do a 'git pull', you will get the updated code. Both branches master and extended have been fixed. Patches for the kernel will be sent soon.

**Comment by mahesh-hegde** [comment]
In my case actually it was rtl8723de and it painlessly connects to my
personal APs using wpa2-psk. Problem only exists if I use rtl8723de driver
with the ab ove mentioned university AP. I believe it is a different
problem.

**Comment by lwfinger** [comment]
Sorry that I misread your device type. I was working on the rtl8192de to fix its problems, and I got confused.

I do not have access to a PEAP setup, but I will send this thread to my contact at Realtek.

**Comment by lwfinger** [comment]
Another driver that you might try is at https://github.com/rtlwifi-linux/rtw88_8723de.
