### ISSUE TITLE
RTL8723DE: no bluetooth

### ISSUE THREAD

**Issue by Ev1lbl0w** [lwfinger/rtlwifi_new#501]
May be related to #496 

I believe this already happened with kernel 5.3.8. On kernel 3.8.10, I receive the following kernel messages:

```
$ journalctl -b | grep hci0
Nov 11 20:03:55 ricardo kernel: Bluetooth: hci0: command 0x1001 tx timeout
Nov 11 20:03:56 ricardo kernel: Bluetooth: hci0: RTL: HCI_OP_READ_LOCAL_VERSION failed (-110)
```

Bluetooth has stopped working:
 - Blueman simply crashes
 - `systemctl restart bluetooth.service` runs successfully and the service is active and running
 - rfkill output:
```
ID TYPE      DEVICE      SOFT      HARD
 0 wlan      phy0   unblocked unblocked
 1 bluetooth hci0   unblocked unblocked
```
 - `bluetoothctl list` returns nothing

**Comment by ohbus** [comment]
I have got the same error after upgrading my kernel to 5.3.0

Seems to be working fine until 5.2.0

**Comment by lwfinger** [comment]
I do not do Bluetooth; however, if I had this problem, I would bisect the kernel to see what change there causes the problem.

**Comment by ohbus** [comment]
> I do not do Bluetooth; however, if I had this problem, I would bisect the kernel to see what change there causes the problem.

Rip 5.3.0 Please

**Comment by Ev1lbl0w** [comment]
Thanks @lwfinger, I've filled a [bug report](https://bugzilla.kernel.org/show_bug.cgi?id=205531) to the linux team

**Comment by Ev1lbl0w** [comment]
The latest update to the kernel *(5.4.2-arch1-1)* has fixed this problem, I suggest you update as well @ohbus. Closing this
