### ISSUE TITLE
No Network on rtl8822be

### ISSUE THREAD

**Issue by bijoyd019** [lwfinger/rtlwifi_new#502]
I've done every as per your advice, but the thing is that there is no visible network on my Kali Linux after installing the driver from rtl_new -b extended, also there is no rtl8822be driver in rtw88 zip. Please tell if anything could be done this issue and also I'm new to linux. please help! My Laptop Model is HP 15-BC406TX.

**Comment by lwfinger** [comment]
Excerpted from the make for the extended branch:

 LD [M]  /home/finger/rtlwifi_new1/rtl8822be/rtl8822be.ko
 
The driver's name is rtl8822be, and it is most certainly there. In the rtw88 branch, drivers for the rtl8822be and rtl8822ce are both folded into rtw88.ko. The PCI driver is rtwpci.ko. There should not be rtl8822be.ko.

Please post the output of 'lspci -nn' to verify what device you have.

**Comment by bjo81** [comment]
Should rtwpci (currently from Kernel 5.4) work better than the old r8822be?

**Comment by lwfinger** [comment]
Yes it should. The old r8822be was merely a stop-gap measure to provide a driver before rtw88 became available.

Why have you not provided the info I requested?

**Comment by bjo81** [comment]
I did not open that issue.
