### ISSUE TITLE
Extremely slow AP on rtl8192ee

### ISSUE THREAD

**Issue by yagoplx** [lwfinger/rtlwifi_new#503]
This is on a new TP-Link TL-WN881ND V2, apparently the V1 had an atheros chipset that led to pretty good speeds, but now with the rtl8192ee, it's showing very bad performance when used as an AP.

With my phone connected to the AP and positioned close to the antennas, I get:
550Kbps downlink and 10Mbps uplink.
The expected speeds are:
~100Mbps downlink and ~20Mbps uplink.

I submitted a support email to TP-Link to see if they get on this issue. Their driver was last updated in 2017 so i'm not very hopeful...

**Comment by lwfinger** [comment]
Well, are you using the driver from this repo, or the one from TP-Link? The two are very different!

**Comment by yagoplx** [comment]
I only tried the one in the kernel and the one in this repo. I have no idea how to compile their drivers.

**Comment by yagoplx** [comment]
Damn, I just want my new card to work alright...

**Comment by lwfinger** [comment]
I have a newer version of the 8192ee (vendor) driver on my system that I just pushed to http://github.com/lwfinger/rtl8192ee.git. Clone it and follow the instructions in README.md. It may, or may not, improve your throughput. This one is v5.2.19_xxxx.20171221_beta, whereas the one provided by TP-Link is v4.3.15.1_r19180.20160824_beta. I would expect a v5 driver to be improved over a v4 one, but in case it is not, I will fix the compile problems with the TP-Link one and add it as a separate branch to the repo when I get time.

**Comment by yagoplx** [comment]
Will test.

Thanks for spending your time on this. Bless you.

**Comment by yagoplx** [comment]
Where did you get this? It compiles and installs just fine.
`lspci ` indicates the new driver 8192ee is applicable for my wireless card. But upon inserting the driver, it never shows that the 8192ee driver is in use.

Here be some debugging info:
```
#output of dmesg
[  199.770765] RTW: rtl8192ee v5.2.19_xxxx.20171221_beta
[  199.771203] RTW: CHIP TYPE: RTL8192EE
[  199.786288] RTW: rtl8192ee_init_tx_ring entries num:128
[  199.786295] RTW: rtl8192ee_init_tx_ring entries num:128
[  199.786300] RTW: rtl8192ee_init_tx_ring entries num:128
[  199.786306] RTW: rtl8192ee_init_tx_ring entries num:128
[  199.786311] RTW: rtl8192ee_init_tx_ring entries num:2
[  199.786349] RTW: rtl8192ee_init_tx_ring entries num:128
[  199.786356] RTW: rtl8192ee_init_tx_ring entries num:128
[  199.786361] RTW: rtl8192ee_init_tx_ring entries num:2
[  226.587347] RTW: rtl8192ee v5.2.19_xxxx.20171221_beta
[  226.587856] RTW: CHIP TYPE: RTL8192EE
[  226.603656] RTW: rtl8192ee_init_tx_ring entries num:128
[  226.603691] RTW: rtl8192ee_init_tx_ring entries num:128
[  226.603696] RTW: rtl8192ee_init_tx_ring entries num:128
[  226.603701] RTW: rtl8192ee_init_tx_ring entries num:128
[  226.603704] RTW: rtl8192ee_init_tx_ring entries num:2
[  226.603708] RTW: rtl8192ee_init_tx_ring entries num:128
[  226.603714] RTW: rtl8192ee_init_tx_ring entries num:128
[  226.603717] RTW: rtl8192ee_init_tx_ring entries num:2
```
```
lspci -vv
04:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8192EE PCIe Wireless Network Adapter
        Subsystem: Realtek Semiconductor Co., Ltd. RTL8192EE PCIe Wireless Network Adapter
        Flags: fast devsel, IRQ 18
        I/O ports at c000 [size=256]
        Memory at ef100000 (64-bit, non-prefetchable) [size=16K]
        Capabilities: [40] Power Management version 3
        Capabilities: [50] MSI: Enable- Count=1/1 Maskable- 64bit+
        Capabilities: [70] Express Endpoint, MSI 00
        Capabilities: [100] Advanced Error Reporting
        Capabilities: [140] Device Serial Number 01-91-81-fe-ff-4c-e0-00
        Capabilities: [150] Latency Tolerance Reporting
        Capabilities: [158] L1 PM Substates
        Kernel modules: rtl8192ee, 8192ee

```

**Comment by yagoplx** [comment]
If RIP means what I think it means, the driver seems to be failing at registering something right while starting up. Same thing happens if my brandless usb dongle and 8192eu are not in the system, and if the system is allowed to clean boot with 8192ee in the initramfs.

**Comment by lwfinger** [comment]
Did you blacklist rtl8192ee? What does 'lsmod | grep 8192" show?

**Comment by yagoplx** [comment]
It's blacklisted.
```
8192ee               2039808  0
8192eu               1748992  0
mei                    81920  3 mei_hdcp,mei_me
cfg80211              417792  2 8192eu,8192ee
```

I found a driver called r8192e_pci, it's a staging kernel driver, but loading it does nothing.

**Comment by lwfinger** [comment]
That staging driver is for a completely different device, the RTL8192E. That is an unfortunate name.

I found a couple of problems with the driver and just pushed an update. This driver has about the same performance for upload as rtl8192ee (~78 Mbps) but considerably better download (93 Mbps vs 36). Try a pull and rebuild.

**Comment by yagoplx** [comment]
Pulled the changes, alright. Gonna build it with dkms this time around so I can test the other kernels as well.

**Comment by yagoplx** [comment]
It works!! Thank you so much. The speed is pretty nice too. I care more about range, though, and the signal is stable, covering the entire house. There is still room for improvement regarding raw speed, but I am happy with what I have. 

You know, I could have just used a regular router. But that's no fun, so I build a router instead. That is the beauty of the world of Linux.

Good luck with the rtlwifi project, many Mbit/s are ahead of you lwfinger.

**Comment by yagoplx** [comment]
Might wanna label this as solved. If you use labels that is.
