### ISSUE TITLE
unknown pseudo-op

### ISSUE THREAD

**Issue by capnhawkbill** [lwfinger/rtlwifi_new#504]
When running make I get this error
```
/tmp/cco4FYt1.s:10674: Error: unknown .loc sub-directive `view'
/tmp/cco4FYt1.s:10674: Error: unknown pseudo-op: `.lvu1'
```
up to this one
```
/tmp/cco4FYt1.s:10674: Error: unknown .loc sub-directive `view'
/tmp/cco4FYt1.s:10674: Error: unknown pseudo-op: `.lvu2697'
```
with every number in between

full make log: http://ix.io/23is
uname -r
5.3.13_1
I'm running void linux
I have the newest version of binutils installed
I'm trying to install rtl8723de but I don't think that matters

**Comment by lwfinger** [comment]
Those are all assembler messages. If you use gcc, the assembler is part of it. I do not know what clang uses for an assembler as I have never used it.

I recommend reinstalling the compiler, switching to gcc if you are using clang. If that does not fix it, perhaps the forums at void Linux might have an answer.
