### ISSUE TITLE
Unable to build in Archlinux 

### ISSUE THREAD

**Issue by cesmoef** [lwfinger/rtlwifi_new#51]
Hello, I've been searching somehow I could solve the problem with the Network disconnection under Ubuntu 14.04. I've got a lenovo z40 70 and I can't tell actually the exact model of my realtek wifi card, the thing is that I installed it on ubuntu and It works perfectly, but now I'm using Archlinux and I've got the same problem. When I try to make the installation as I do on Ubuntu, it gives me "error 2". I tried a lot to find a way to solve it but I couldn't by myself. I would really appreciate your help.

Here is the message error.

make -C /lib/modules/4.0.4-2-ARCH/build M = / home / cesmoef / rtlwifi_new modules
make [ 1] : enter the ' /usr/lib/modules/4.0.4-2-ARCH/build ' directory
make [ 1 ] : **\* No rule to build the ' modules' goal. Stop.
make [ 1] : Leaving ' /usr/lib/modules/4.0.4-2-ARCH/build ' directory
Makefile : 53 : error in the instructions to the target 'all'
make: **\* [ all] Error 2

**Comment by lwfinger** [comment]
When you build an out-of-kernel module, you must have access to the kernel headers. Ubuntu installs these automatically, but most other distros do not. As I am not an Archlinux user, I cannot advise you on what is needed. You should go to the forums for your distro. Most call the necessary package as kernel-headers, kernel-devel or some similar name.

**Comment by cesmoef** [comment]
Thanks! Problem solved, the package is called "linux-headers" and it's available from the official repositories.

**Comment by JuanSeabra** [comment]
Hi guys, even after installing the package "linux-headers", I'm having the same problem @cesmoef posted here (I think)

make -C /lib/modules/4.1.2-2-ARCH/build M=/home/juan/wififix modules
make[1]: Entering directory '/usr/lib/modules/4.1.2-2-ARCH/build'
make[1]: *** No rule to make target 'modules'.  Pare.
make[1]: Leaving directory '/usr/lib/modules/4.1.2-2-ARCH/build'
Makefile:53: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lwfinger** [comment]
The headers package may not be enough for Arch. Does 'ls /lib/modules/4.1.2-2-ARCH/build' show a directory named "include"? That is an absolute minimum. I did a bit of searching, but I did not find any web sites that said do a, b, etc. to build an out-of-kernel module.

**Comment by JuanSeabra** [comment]
actually after update the kernel, "sudo pacman -S linux", the make works just fine

**Comment by ddulic** [comment]
Using Arch, downloading only linux-headers does not work.
@lwfinger the ls does show a folder "include"
Any tips on how I can get this working in Arch?
Thanks.

**Comment by lwfinger** [comment]
I am not an ARCH user, thus I am not familiar with the exact commands you need. The ls command that needs to show the include file is
ls /lib/modules/$(uname -r)/build/

If there is still a problem, then you need to contact the ARCH forum.

**Comment by ddulic** [comment]
Tried editing /$(uname -r)/build/ to /4.2.5-1-ARCH/build/ and this did not go well xD totally broke the wifi :/ luckily a make uninstall fixed it :+1:

**Comment by jaredallard** [comment]
If you had a not-installed linux-headers package for the linux kernel you are currently *running* then you were to update linux then the linux-headers would be in a different directory than the current kernel you're running. So, rebooting might fix that @ddulic.

**Comment by ddulic** [comment]
My /lib/modules/ shows 2 karnels: 
4.1.12-1-lts and 4.2.5-1-ARCH
In LTS the build folder only has 1 file in it - vmlinux.
In ARCH it shows a bunch of folders leading me to believe this is the correct one. However doing a "uname -r" reveals I am using the LTS karnel, NOT the ARCH one. This is due to me using Antergos Linux which is based on Arch, and on installation I choose to install the LTS version of the karnel.
Maybe this will give more insight into the problem. Maybe a simlink to link the 2 build folders? But not sure if that will cause problems.

**Comment by lwfinger** [comment]
Artificially linking the way you describe might let your system build the modules; however, you probably would not be able to load the modules. If you did get them loaded, then you would get mysterious crashes. IT IS ABSOLUTELY NECESSARY TO HAVE THE HEADERS FOR THE RUNNING KERNEL. Sorry for shouting, but it is an important point. The "include" directory inside the build directory is the important one.

I know nothing of Antergos, but you absolutely must install the headers for the kernel you are running.

Why not use the drivers that are built into the kernel in both 4.1 and 4.2? There are no important differences between those and the drivers in this repo, and you do not need to worry about the headers.

**Comment by ddulic** [comment]
I think I would the problem. Can't test it out tho. When using "yaourt" as the package manager in Linux and when you search 2 files are available. Linux-Headers and Linux-Headers-LTS. If you are using a lts you need the lts. I have reinstalled Arch without the lts and now just installing Linux-Headers works. Sorry for the trouble.

**Comment by jaredallard** [comment]
Had I known you were on LTS, I would've suggested installing that ;P

**Comment by ddulic** [comment]
@jaredallard Kinda of a newbie at Linux, only had it for a couple of months. But I find it awesome and quite fun, finding out things on my own is fine to me ^^ Thanks for all your help :)

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.

**Comment by ddulic** [comment]
I just bought a new wifi card :'(
Jokes aside, good work!
