### ISSUE TITLE
RTL8723DE does not work on kernel 5.3.x

### ISSUE THREAD

**Issue by kanito73** [lwfinger/rtlwifi_new#510]
Hello

I've been using this driver (RTL8723DE) on Fedora 29 with kernels 4.x and Fedora 30 with kernels 5.0-5.2 very successfully. Today I installed Fedora 31 that comes with kernel 5.3.7, downloaded latest version of "rtlwifi_new" using git and tried to install as usually but does not work. Then upgraded all packages and new kernel is 5.3.15 but it still does not work. The driver compiles, installs and (aparently) loads (at boot time or with modprobe) with no errors or problems, but when starting KDE Plasma it simply does not detect any network, as if there was any wireless device available.

NOTE: Latest kernel on repositories is 5.3.15 (kernel and kernel-devel) BUT kernel-headers is 5.3.11 and THERE IS NO OTHER PACKAGE AVAILABLE. I don't know if the problem is the the version of the kernel-headers (different from kernel version) or the KDE network manager or some actualzation to the rtlwifi_new driver, the previous version I have does not compile and the latest version compiles but does not work.

By now I restored my old Fedora 30 backup to work while I can get my RTL8723DE working on Fedora 31, I have backup of Fedora 30 and 31 so I can restore a ready-to-use installation to try setting up rtlwifi_new again...

Any recommendation to discover if the problem is the kernel & kernel-headers version or the wifi driver or the KDE? Maybe a set of console commands (which ones) to check the status of the driver and the wifi hardware?

Thanks!

**Comment by lwfinger** [comment]
If the kernel headers are for a different version than the kernel, then they will build without problems, but will not load. You should see that is the output of the dmesg command.

Ask on a Fedora forum about the missing headers. That seems to be a mistake.

The driver will build and work with kernels up through 5.5.0-rc1, which is what I am using.

**Comment by kanito73** [comment]
Thanks a lot for your fast response. I already asked at fedora forums about the wireless error but it will be better to open a new topic related to the kernel-headers version, surely when getting the same version for kernel + devel + headers it will compile and run as always.

Take care and thanks again 8-)

**Comment by lwfinger** [comment]
The new driver for RTL8723DE is now in the wireless_drivers_next repo. To make it easier for users here, it is now in the rtw88 branch. Do the following:

git checkout origin/rtw88 -b rtw88
make
sudo make install

This version should build on kernels 4.5 or newer.

Please be aware that on June 1, 2020, all branches in this repo will be deleted except for rtw88. If you really need the other drivers for old kernels, use the "backports" project. These old drivers have been taking too much of my time!
