### ISSUE TITLE
AP performance analysis (rtl8192ee)

### ISSUE THREAD

**Issue by yagoplx** [lwfinger/rtlwifi_new#511]
Tests below conducted in an area with uncongested Wi-Fi channels and no bluetooth devices anywhere.
```
Driver is built with extra CFLAGS -> "-Ofast -frename-registers -mtune=native"
But you will get the same results with the defaults.
Driver is running with ips=1.

Tested on Linux 5.2 with RT patchset.

IPERF3 TEST
PHONE = CLIENT
LINUX SERVER = AP
(PHONE SENDS, SERVER RECIEVES)
(TESTING RTL8192EE DOWNLOAD SPEED)
--- Mean 8192EE DL ---
[  5]   0.00-10.97  sec  12.4 MBytes  9.48 Mbits/sec
--- Mean 8192EE DL ---

^ Sender and reciever experience same speed, 9.48Mbits/sec. Phone did not have to retry sending.

IPERF3 TEST
PHONE = CLIENT
LINUX SERVER = AP
(PHONE RECIEVES, SERVER SENDS)
(TESTING RTL8192EE UPLOAD SPEED)
--- Mean 8192EE UL ---
[  5]   0.00-10.04  sec  1.36 MBytes  1.13 Mbits/sec    2 retries
--- Mean 8192EE UL ---

^ Reciever experienced a loss in throughput to 877Kbits/sec mean due to retries.

DMESG OUTPUT DURING TESTS:
[28351.682336] rtl8192ee: Using firmware rtlwifi/rtl8192eefw.bin
[28351.692393] rtl8192ee 0000:04:00.0 wlp4s0: renamed from wlan0

Not very informative, huh? Let's retry the tests this time with the driver being more verbose. I'll also have Hostapd spit out what it's doing.
Driver now with ips=1 debug_level=5.

Well, dmesg didn't show anything new. Hostapd doesn't care about data, it just handles Wi-Fi protocol stuff.
Anyway, something interesting was that, despite the AP considering the signal strength as -18dBm, the phone only registers -33dBm. (short distance).
That may be due to high gain antennas on the AP improving reception, or just the transmission being weak? I don't know. 

The phone also reports the maximum speed of the link as 65Mbps at close range. During transmission, 8192ee claims to run at 300M bitrate (max)
I even enforced it with "sudo iwconfig wlp4s0 bit 300Mbps" after the first test

But the actual bandwidth ends up being a measly 700Kbits/sec, and the iperf3 server reports a bitrate of 1.23Mbits/sec.

Driver was from latest commit in rtlwifi_new extended branch.
Now, despite disabling Link Power Save on the driver increasing performance by a little bit, this should not be necessary, as it shows the implementation of lps is faulty.

DEVICE DATA:
LSPCI: 04:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8192EE PCIe Wireless Network Adapter
NAME: TP-Link TL-WN881ND V2
VARIANT: RTL8192EE-CG

USEFUL LINKS
Alternate (vendor, beta) driver for 8192ee: https://github.com/lwfinger/rtl8192ee
Alternate (vendor) driver for 8192ee: https://www.tp-link.com/us/support/download/tl-wn881nd/#Driver

```
Is there a way to have the driver be more verbose? Perhaps collecting more runtime information would lead to the cause of the issue. I'm interested in debugging this device for rtlwifi_new.

**Comment by yagoplx** [comment]
I think I will contact that wlanfae person from realtek about this... Maybe they can help?

**Comment by yagoplx** [comment]
Sometimes, this driver also fails to send out beacons. So even if the system reports the AP and interface as up, no devices can actually interact with it.

**Comment by kimocoder** [comment]
Oooh I'm well aware of most issues regarding Realtek drivers of these kinds, it's lots of issues all over the place.

![Screenshot_20191219-223938](https://user-images.githubusercontent.com/4252297/71212004-b1280580-22b0-11ea-89e8-cae24d6278ea.jpg)

**Comment by yagoplx** [comment]
It is a mess everywhere. WiFi only really became reliable in my eyes since the ac and ax standards.

Just the absolute gap in functionality between, say, ath9k and rtlwifi, suggests that something is, or was wrong.

Unfortunately this is the only PCI card they sell round these parts, and I had to go with it to build a custom router.

**Comment by yagoplx** [comment]
Still no response from wlanfae. RIP.

**Comment by yagoplx** [comment]
@lwfinger , after all, are these issues caused by crappy drivers or does the 8192ee-cg chip just suck? 

After contacting wlanfae failed, who should I talk to about getting performance improvements on the driver? I mean, I have the chip and would like to help the kernel devs.

**Comment by yagoplx** [comment]
linux-wireless@vger.kernel.org is the answer. I will be forwarding this issue to them, and closing it here.
