### ISSUE TITLE
ubuntu 19.10 kernel 5.3.0-24 8822be wifi very slow connection

### ISSUE THREAD

**Issue by devang1993** [lwfinger/rtlwifi_new#512]
It has very high ping. However works perfectly with windows 10. Any ideas on how to get it to work on Ubuntu too?

**Comment by lwfinger** [comment]
You need to switch to a v5.4 kernel and use the driver that is built in. It that is still slow, then describe the problem at linux-wireless@vger.kernel.org. My fixes are strictly limited to build problems, and some kernel oops instances.

**Comment by bjo81** [comment]
I have better experiences with @lwfinger's rtw88 module than with the 5.4. built-ins.

**Comment by devang1993** [comment]
@bjo81 rtw88 is working well for now. If there are further issues, I'll proceed with @lwfinger

**Comment by lwfinger** [comment]
The 8822be and 8822ce drivers in the rtw88 branch are just copies of the kernel version. The only difference is that those from this repo will build on older kernels.

**Comment by bjo81** [comment]
@lwfinger But there seems to be a difference: Your version is not stuck at 6.5.Mbit TX bitrate, and the rx drop counter does not increase nearly every second. And with your module I get 200-300Mbit throughput instead of 20-30Mbit (compared to rtw88 of 5.4.5).

**Comment by devang1993** [comment]
I still have the same issue with rtw88. I'm switching to v5.4.5 and if it still persists, I'll describe it at  linux-wireless@vger.kernel.org.

**Comment by bjo81** [comment]
@devang1993 Does your issue still persist with 5.4.5?

**Comment by devang1993** [comment]
@bjo81 it's a lot better with v5.4.5. However there are issues when I use Bluetooth and WiFi at the same time, eg. music playing over my Bluetooth speaker, the speaker disconnects/drops and WiFi drops. Unless i disconnect the Bluetooth connection the WiFi doesn't restore.
