### ISSUE TITLE
rtl8192ee igb Detected Tx Unit Hang

### ISSUE THREAD

**Issue by Gnoale** [lwfinger/rtlwifi_new#513]
Hello, first thanks for the great work on those drivers.

My kernel version : `Linux 5.4.5-arch1-1`

I try to use this card : `Realtek Semiconductor Co., Ltd. RTL8192EE PCIe Wireless` 

Whenever I try to interact  with it , I get those cryptic kernel messages and it 'break' my built in NIC  `Intel Corporation I211 Gigabit Network Connection (rev 03)` )
The only workaround I have is to reboot at this point.
```
kernel: igb 0000:06:00.0: Detected Tx Unit Hang
                                 Tx Queue             <1>
                                 TDH                  <0>
                                 TDT                  <5>
                                 next_to_use          <5>
                                 next_to_clean        <0>
                               buffer_info[next_to_clean]
                                 time_stamp           <ffff5672>
                                 next_to_watch        <00000000f41c7a99>
                                 jiffies              <ffff5d80>
                                 desc.status          <168000>
```
I've build the driver from this repository as explained in the README and the behavior stays the same.
I'm sure it's not an hardware issue because under Windows everything works find with the realtek driver.
 
Do you have any idea where should I start looking ?

**Comment by calvinreu** [comment]
I think your kernel is to new because a lot of drivers just stopped working with kernel 5.3 up and the driver didn't have a update since launched the new kernel I would suggest you build the driver in a VM with a fedora version of the older kernel to find out if the error is caused by the kernel.

**Comment by lwfinger** [comment]
I have been building and testing these drivers with every kernel up through v5.5, Running openSUSE Tumbleweed with NetworkManager, there have been no problems. The interaction between the wifi and wired interface suggests a network management problem. I think you are running ARCH, thus I suggest checking if other of their users have a problem. It is most likely something in their user-land network control, not a kernel problem.
