### ISSUE TITLE
Rtl8723de in the kernel

### ISSUE THREAD

**Issue by KingLucius** [lwfinger/rtlwifi_new#514]
According to this [commit](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/commit/?id=11bdc578ec861c7797ec614d60737a0448b68195), is this driver is not needed anymore?
Because it still not working by default after updating kernel and latest Linux firmware package.

**Comment by lwfinger** [comment]
That commit was for FIRMWARE, not a driver. RTL8723DE is not yet in the kernel. Realtek is working on a version that will become part of the driver family rtw88, but it is not yet submitted, and certainly not reviewed by the community.

**Comment by KingLucius** [comment]
Is there any way toknow when the driver get included in the kernel?

**Comment by lwfinger** [comment]
There are too many variables. The earliest it could be is kernel v5.7.

**Comment by cata0309** [comment]
Any news on bringing RTL8723DE in the kernel! Where can I see the progress of Realtek bringing it to the kernel ?

**Comment by lwfinger** [comment]
Subscribe to linux-wireless@vger.kernel.org. My latest private information says that it is undergoing internal review at Realtek.

**Comment by cata0309** [comment]
How can I subscribe ? It's an email adress

**Comment by bjo81** [comment]
Write an email to `majordomo@vger.kernel.org` with `subscribe linux-wireless` in the body.

**Comment by lwfinger** [comment]
Exactly.
