### ISSUE TITLE
RTL8822CS kernel Panic with injection test

### ISSUE THREAD

**Issue by ImedJ** [lwfinger/rtlwifi_new#516]
Hi,

We have serious problem with RTL8822CS (SDIO interface)
Station mode, AP mode are OK. We are using driver: rtl88x2CS_WiFi_linux_v5.7.3.3_35690.20191109_COEX20190531-0e0e
Aireplay-ng injection test is also OK: aireplay-ng --test wlan0

When we use MDK4 to do injection test, we have a kernel Panic.
Same test is OK when we use RTL8812AU (from Alpha) with required driver.

We think that our kernel image is OK (4.14.98).
Problem is on RTL8822CS driver.

please find below kernel panic message:

[  186.147480] CPU: 3 PID: 3572 Comm: mdk4 Tainted: G        W  O    4.14.98-2.1
[  186.155829] Hardware name: FSL i.MX8MM DDR3L Validation board (DT)           
[  186.162007] Call trace:                                                      
[  186.164460] [<ffff000008089c48>] dump_backtrace+0x0/0x3c8                    
[  186.169859] [<ffff00000808a024>] show_stack+0x14/0x20                        
[  186.174911] [<ffff000008dc9f40>] dump_stack+0x9c/0xbc                        
[  186.179964] [<ffff0000080f3c44>] __schedule_bug+0x4c/0x70                    
[  186.185362] [<ffff000008dde4b8>] __schedule+0x558/0x5e8                      
[  186.190586] [<ffff000008dde580>] schedule+0x38/0xa0                          
[  186.195466] [<ffff000008a67108>] __mmc_claim_host+0x98/0x210                 
[  186.201125] [<ffff000008a74678>] sdio_claim_host+0x20/0x38                   
[  186.207242] [<ffff000000f39704>] rtw_sdio_raw_write+0x294/0x2e8 [88x2cs]     
[  186.214561] [<ffff000000f30c80>] sdio_io+0x98/0x2f0 [88x2cs]                 
[  186.220835] [<ffff000000f30f40>] rtw_sdio_write_cmd53+0x14/0x1c [88x2cs]     
[  186.228150] [<ffff000000f98be4>] rtl8822cs_write_port+0x70/0x84 [88x2cs]     
[  186.235465] [<ffff000000f98c18>] sdio_write_port+0x20/0x48 [88x2cs]          
[  186.242331] [<ffff000000ed8ae0>] _rtw_write_port+0x18/0x20 [88x2cs]          
[  186.249208] [<ffff000000f99e7c>] rtl8822cs_mgnt_xmit+0xec/0x118 [88x2cs]     
[  186.256516] [<ffff000000f65fb8>] rtw_hal_mgnt_xmit+0x40/0x60 [88x2cs]        
[  186.263551] [<ffff000000ee7ffc>] dump_mgntframe+0x48/0x78 [88x2cs]           
[  186.270337] [<ffff000000f1b164>] rtw_monitor_xmit_entry+0x13c/0x218 [88x2cs] 
[  186.278001] [<ffff000000f4a678>] rtw_xmit_entry+0x28/0x38 [88x2cs]           
[  186.284190] [<ffff000008bddad0>] dev_hard_start_xmit+0x90/0x128              
[  186.290111] [<ffff000008c0efb4>] sch_direct_xmit+0x10c/0x198                 
[  186.295769] [<ffff000008bde120>] __dev_queue_xmit+0x4a0/0x5c8                
[  186.301513] [<ffff000008bde258>] dev_queue_xmit+0x10/0x18                    
[  186.306913] [<ffff000008cce8ac>] packet_sendmsg+0xa54/0x1470                 
[  186.312572] [<ffff000008bbc4d8>] sock_sendmsg+0x18/0x30                      
[  186.317795] [<ffff000008bbc55c>] sock_write_iter+0x6c/0xb0                   
[  186.323282] [<ffff00000821541c>] __vfs_write+0xac/0x118                      
[  186.328506] [<ffff00000821567c>] vfs_write+0xa4/0x1b0                        
[  186.333557] [<ffff000008215940>] SyS_write+0x48/0xb0                         
[  186.338520] Exception stack(0xffff000010063ec0 to 0xffff000010064000)        
[  186.344960] 3ec0: 0000000000000006 0000fffff2d11368 0000000000000064 0000fff0
[  186.352788] 3ee0: 02f25000000102f2 0000fffff2d113cc ffffffff00000080 3138367f
[  186.360616] 3f00: 0000000000000040 000000000055f000 6154050000120064 8b84820c
[  186.368444] 3f20: 302418120c083296 18dd0601036c6048 0000000000000057 00006e80
[  186.376272] 3f40: 000000000042f220 0000ffffbbd2a598 0000fffff2d1227f 00000006
[  186.384100] 3f60: 0000000000000058 0000fffff2d11368 0000000006da7df0 0000000c
[  186.391928] 3f80: 0000000000417d90 0000000000433000 000000000042e000 00000008
[  186.399756] 3fa0: 0000000006da7820 0000fffff2d112e0 000000000041531c 0000fff0
[  186.407584] 3fc0: 0000ffffbbd2a5c0 0000000080000000 0000000000000006 00000000
[  186.415412] 3fe0: 0000000000000000 0000000000000000 0000000000000000 00000000
[  186.423242] [<ffff000008083b18>] __sys_trace_return+0x0/0x4                  
[  186.429839] Kernel panic - not syncing: Aiee, killing interrupt handler!     
[  186.436550] CPU: 2 PID: 3572 Comm: mdk4 Tainted: G        W  O    4.14.98-2.1
[  186.444899] Hardware name: FSL i.MX8MM DDR3L Validation board (DT)           
[  186.451077] Call trace:                                                      
[  186.453531] [<ffff000008089c48>] dump_backtrace+0x0/0x3c8                    
[  186.458929] [<ffff00000808a024>] show_stack+0x14/0x20                        
[  186.463981] [<ffff000008dc9f40>] dump_stack+0x9c/0xbc                        
[  186.469033] [<ffff0000080ce5b0>] panic+0x11c/0x28c                           
[  186.473823] [<ffff0000080d25a8>] do_exit+0x768/0x998                         
[  186.478787] [<ffff0000080d2840>] do_group_exit+0x38/0xa0                     
[  186.484099] [<ffff0000080dd570>] get_signal+0xf8/0x4a8                       
[  186.489237] [<ffff0000080886a4>] do_signal+0x6c/0xc08                        
[  186.494287] [<ffff0000080898d8>] do_notify_resume+0xc8/0x108                 
[  186.499945] Exception stack(0xffff000010063ec0 to 0xffff000010064000)        
[  186.506384] 3ec0: 0000000000000064 0000fffff2d11368 0000000000000064 0000fff0
[  186.514213] 3ee0: 02f25000000102f2 0000fffff2d113cc ffffffff00000080 3138367f
[  186.522041] 3f00: 0000000000000040 000000000055f000 6154050000120064 8b84820c
[  186.529868] 3f20: 302418120c083296 18dd0601036c6048 0000000000000057 00006e80
[  186.537696] 3f40: 000000000042f220 0000ffffbbd2a598 0000fffff2d1227f 00000006
[  186.545524] 3f60: 0000000000000058 0000fffff2d11368 0000000006da7df0 0000000c
[  186.553352] 3f80: 0000000000417d90 0000000000433000 000000000042e000 00000008
[  186.561180] 3fa0: 0000000006da7820 0000fffff2d112e0 000000000041531c 0000fff0
[  186.569008] 3fc0: 0000ffffbbd2a5c0 0000000080000000 0000000000000006 0000000f
[  186.576836] 3fe0: 0000000000000000 0000000000000000 0000000000000000 00000000
[  186.584664] [<ffff000008083964>] work_pending+0x8/0x10                       
[  186.589804] SMP: stopping secondary CPUs                                     
[  186.594027] Kernel Offset: disabled                                          
[  186.597514] CPU features: 0x080200c                                          
[  186.601000] Memory Limit: none                                               
[  186.604056] ---[ end Kernel panic - not syncing: Aiee, killing interrupt han!

Help please!
We are stuck

**Comment by lwfinger** [comment]
Very interesting: You report a problem with an SDIO interface to a repo that is specifically for PCI devices. What do you think I might do? In addition, you lost the line that says why the kernel panic happened!
