### ISSUE TITLE
Unable to use the wifi on kernel 5.4

### ISSUE THREAD

**Issue by Amararyan** [lwfinger/rtlwifi_new#518]
I am using a hp laptop with rtl8723de. After upgrading the kernel to 5.4, the WiFi stopped working. It was working fine till the kernel 4.15x. When I clone the rtl_wifi directory, it fails to make (screenshot attached).
![Screenshot from 2020-01-13 23-07-37](https://user-images.githubusercontent.com/42216949/72278388-e9c1c180-3659-11ea-9a47-e7ee1ba08f14.png)

**Comment by lwfinger** [comment]
Those are compiler errors, not an error in the driver code. Complain to your distro. What else changed when you updated to kernel 5.4?
