### ISSUE TITLE
rtl8821ce issue with make install

### ISSUE THREAD

**Issue by AkashiyaWolf** [lwfinger/rtlwifi_new#519]
I bought an IdeaPad S145 to use as a linux laptop. I'm running CentOS kernel ver. 4.14. The wifi in it is rtl8821ce. It does NOT have an ethernet port.

On Raspbian I did the following
git clone http://github.com/lwfinger/rtlwifi_new.git -b rtw88

I made a folder "rtlwifi_new" in the /root directory on my laptop, copied the files over, then did:
cd rtlwifi_new
make
sudo make install

Output from "make install" command
make -C /lib/modules/4.18.0-147.el8.x86_64/build M=/root/rtlwifi_new modules
make:[1]: Entering directory '/usr/src/kernels/4.18.0-147.el8.x86_64'
      Building modules, stage 2.
      MODPOST 2 modules
make[1]: Leaving directory '/usr/src/kernels/4.18.0-147.el8.x86_64'
cp: cannot stat 'firmware/*.bin' : Not a directory

EDIT:
ls /usr/src/kernels/4.18.0-147.el8.x86_64/firmware
Makefile

I'm new to all this and don't know what to do.
Do I need to make a firmware directory? If so, where do I put it?

Thank you!

**Comment by dikivan2000** [comment]
If by /root directory you mean exactly /root, you might want to try to run "make" with sudo as well, although I'd think about compiling in your home folder in general. Why would you build under /root anyways?

**Comment by lwfinger** [comment]
NEVER, NEVER install anything in the /root directory. In addition, NEVER, NEVER use "sudo" for any commands other that those that write stuff into privileged directories, or load stuff into privileged RAM. The only ones that come to mind for here are 'sudo make install' and 'sudo modprobe'.

From your home directory, clone the rtw88 branch of the repo, then 'cd rtlwifi_new'. At that point, there WILL be a directory firmware with .bin files in it. The commands 'make' and 'sudo make install' will load the driver into your system. Firmware for this device is written into /lib/firmware/rtw88/. The install part of 'sudo make install' will do the copying and create any necessary directories.
