### ISSUE TITLE
rtl8723be does not work after suspend

### ISSUE THREAD

**Issue by hanipouspilot** [lwfinger/rtlwifi_new#52]
I think it is a similar issue as in bluetooth driver. has it been reported before? Any ideas?
I will look how to fix it too.

**Comment by keeper** [comment]
@hanipouspilot,

Did you see something like "rtl8723be 0000:01:00.0: Refused to change power state, currently in D3" in dmesg?

**Comment by tarun200897** [comment]
I have this same issue. Wifi is hard blocked after suspend.

**Comment by hanipouspilot** [comment]
Hard blocks are not related to the Realtek driver. It is done by the platform driver.

**Comment by tarun200897** [comment]
The thing is that my laptop doesn't have a hardware switch and aeroplane mode switch just softblocks the wifi. Resetting my bios didn't help as well. So I thought maybe the somewhere there's a problem reading / writing the hard block status parameter in memory?

**Comment by hanipouspilot** [comment]
Should I guess what is "your laptop"? This is usually a problem of a
platform kernel driver.

2016-01-17 13:22 GMT+03:00 Tarun Kancharayan <notifications@github.com>:

**Comment by tarun200897** [comment]
Sorry, hp pavilion 15 ab032tx.

**Comment by hanipouspilot** [comment]
Try to disable the platform driver. Something like

modprobe -r hp_wmi

**Comment by tarun200897** [comment]
I've already tried that. But it doesn't help. Restarting network manager doesn't help as well. And I forgot to mention this. The Bluetooth suddenly disappears from rfkill after suspend.

**Comment by tarun200897** [comment]
Can you think of anything else?

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
