### ISSUE TITLE
Not able to modprobe rtl8723de

### ISSUE THREAD

**Issue by Phoenix181** [lwfinger/rtlwifi_new#524]
I can't modprobe the driver after installing. It showed me an error:
`modprobe: ERROR: could not insert 'rtl8723de': Unknown symbol in module, or unknown parameter (see dmesg)`
dmesg output: 
`[  770.556117] rtl_pci: Unknown symbol show_it_mac (err -2)`
`[  770.556327] rtl_pci: Unknown symbol rtl_check_beacon_key (err -2)`

This happens after upgrading kernel to 5.4.15
OS: Fedora 31
Kernel Version: 5.4.15

**Comment by lwfinger** [comment]
You are probably getting rtl_pci from the kernel version, not the one from this repo. Remove all rtl* modules - check with lsmod. Then 'sudo modprobe -v rtl8723de'. If that still fails, post the output.

**Comment by Phoenix181** [comment]
The above method worked will this be problem every time I restart?
