### ISSUE TITLE
How to specify the kernel for which the modules should be compiled ?

### ISSUE THREAD

**Issue by fvalenduc** [lwfinger/rtlwifi_new#526]
I would like to know if it is possible to compile the module for another kernel than the one currently running. This would be easier when upgrading. Now, I have to reboot the new kernel, wait 1min 30 seconds before systemd gives up enabling the wireless connection, then compile and install the modules and finally restarting the wireless connections.

It seems it is possible to specify the kernel for which the modules should be compiled like this:
make -C M=/usr/src/rtlwifi_new -j9 -l7 modules
But I have a problem with running make installl which always install the modules for the current kernel.
Is there a way to solve this ?
Thanks in advance for your help.

François Valenduc

**Comment by TimAngelico** [comment]
You can reduce your reboot time by editing /etc/dhcp/dhclient.conf and changing the timeout to something lower. The default is usually 60. I have changed mine to
timeout 15;
meaning it will only try for 15 seconds before giving up.

Hope this helps make rebooting less painful.

**Comment by jeremyb31** [comment]
fvalenduc
Why not use dkms?  It should built the new module while the new kernel is installing

**Comment by fvalenduc** [comment]
Not everybody uses ubuntu or debian. I am using gentoo.

**Comment by bjo81** [comment]
You could use my dkms-config from Arch: https://aur.archlinux.org/packages/rtlwifi_new-rtw88-dkms/

**Comment by fvalenduc** [comment]
dkms doesn't exist in gentoo.

**Comment by jeremyb31** [comment]
Can new kernels be used in gentoo?  I am sure the rtw88 module exists in 5.3 and newer

**Comment by fvalenduc** [comment]
I need the rtl8723de modules which is only available in the rtlwifi_new git tree. The rtl8723be driver is well in the kernel tree, it would be easier if rtl8723de was also included.
I wonder what is the real difference between the 2 drivers, beside one letter which prevent from  adding this driver to the kernel.

**Comment by jeremyb31** [comment]
The easiest way might be to modify Makefile on line 4 there is `KVER  := $(shell uname -r)` if you change $(shell uname -r) to the newly installed kernel version, the make and sudo make install should work for the new kernel as the $(shell uname -r) will just use the running kernel version

**Comment by fvalenduc** [comment]
Indeed, I had already understood that this line explains why it always install the modules for the kernel currently running. But I wonder wheter there is a more complete solution which would use a parameter given on the make command.

**Comment by jeremyb31** [comment]
Might want to see how gentoo handles kernel updates with nvidia graphics or broadcom-sta drivers

**Comment by lwfinger** [comment]
@fvanduc: Yes, there is only one letter different between RTL8723BE and RTL8723DE, but the underlying device is very different.

Yes, you can use a different kernel to build the driver with appropriate input parameters to the make command. No, I will not tell you how as that will cause many more users to have problems that I would be asked to help. If you put the source code in your home file tree, and you use a separate partition for /home as is recommended, then the source code will survive an update in the kernel. After booting the new kernel, you can then build using 'make && sudo make install". Network access will not be needed. If it is, then your distro has a broken update process.
