### ISSUE TITLE
rtl8822be not working on kernel 5.4x

### ISSUE THREAD

**Issue by TimAngelico** [lwfinger/rtlwifi_new#527]
I'm using Debian 11 Bullseye, running kernel 5.4.0-3-amd64, on a Lenovo a485. Everything worked fine out of the box on kernel 4.19, but after upgrading to 5.3 and then 5.4, systemd didn't recognise the wifi chip.

Following the instructions from here:
https://unix.stackexchange.com/questions/394012/wifi-not-working-in-debian-8-9-having-rtl8723de-driver-10ecd723/394032#394032
everything executed without throwing any errors, but wlan0 still didn't work.

I have made sure linux-headers is up to date

Latest extended branch (e32609):
[  365.168356] halmac: chip_id 0xa, chip_version 0x3
[  365.179374] rtl8822be: Using firmware rtlwifi/rtl8822befw.bin
[  365.179724] rtl8822be 0000:02:00.0: firmware: failed to load rtlwifi/rtl8822befw.bin (-2)
[  365.179730] rtl8822be 0000:02:00.0: Direct firmware load for rtlwifi/rtl8822befw.bin failed with error -2
[  365.179733] rtlwifi: Selected firmware is not available
[  365.181126] ieee80211 phy2: Selected rate control algorithm 'rtl_rc'
[  365.181527] rtlwifi: rtlwifi: wireless switch is on

Going back a few commits (83fc4f):
[  907.656365] halmac: chip_id 0xa, chip_version 0x3
[  907.666479] rtl8822be: Using firmware rtlwifi/rtl8822befw.bin
[  907.666919] rtl8822be 0000:02:00.0: firmware: direct-loading firmware rtlwifi/rtl8822befw.bin
[  907.668480] ieee80211 phy3: Selected rate control algorithm 'rtl_rc'
[  907.669453] rtlwifi: rtlwifi: wireless switch is on

But attempting to ifup wlan0 faiils:
Could not set interface wlan0 flags (UP): Operation not permitted
WEXT: Could not set interface 'wlan0' UP
wlan0: Failed to initialize driver interface
ifup: failed to bring up wlan0

And dmesg says:
[  913.156951] rtl8822be: halmac_init_hal failed

Thanks in advance

**Comment by lwfinger** [comment]
Did you read the dmesg output? You have not installed the correct firmware. See the line at [ 365.179724].
