### ISSUE TITLE
Bluetooth and WiFi not working at the same time.

### ISSUE THREAD

**Issue by p9malino26** [lwfinger/rtlwifi_new#529]
## Description

I am using your driver on my RTL8723DE card on my laptop. Both WiFi and Bluetooth work on their own but when WiFi is switched on, I am able to detect and connect to my Bluetooth earphones fine but when I try to play some audio through my Bluetooth earphones when they are connected, the audio either doesn't play or it heavily stutters. The BT connection is then usually lost. I am able to listen to audio normally through the earphones when WiFi is switched off. This problem does not occur on Windows 10 on the same laptop/WiFi card. 

## System Info
Operating System: Manjaro Linux 64 bit vers. 19.0
Kernel: This happened on all kernels that I have used from 4.19 to 5.5.
*I am using the extended branch of your driver.

**Comment by lwfinger** [comment]
I have said this many, many, many times - I do not do Bluetooth!!!!

**Comment by p9malino26** [comment]
Fine, I totally respect that but then who is responsible for Bluetooth and
the cooperation between your driver and the Bluetooth? Do I get the
Bluetooth functionality out of the driver in your repository (even if it
was not written by you) or from something else? Also, it would really help
if you stated that in the README file very, very clearly.
