### ISSUE TITLE
hiccup on Thinkpad e540 edge (rtl8723be)

### ISSUE THREAD

**Issue by mikevmk** [lwfinger/rtlwifi_new#53]
I'm running ubnutu 15.04 on ThinkPad e540 and the stock driver was barely usable (any net stream stopped to work in 20-40 sec)

After I compiled this driver from git it works much better but I still have issues 

'ping 8.8.8.8' have 4-10 lost packets in 1000, ~5% of all packets have bad reply time (200-400 Ms, when other is 15-20 Ms)

Any internet stream (youtube, internet radio) become silent for 1-2 sec every 3-5 minutes

I've disabled 'n' version of Wifi on router but this didn't help. Other devices works fine with that router.

There is no error messages in 'journalctl' and 'dmesg' output.

What information can I provide you to help to resolve this? And how I can do this?
# iwconfig

wlan0     IEEE 802.11bgn  ESSID:"roszkh.ru"  
          Mode:Managed  Frequency:2.437 GHz  Access Point: 64:70:02:43:37:06  
          Bit Rate=54 Mb/s   Tx-Power=20 dBm  
          Retry short limit:7   RTS thr=2347 B   Fragment thr:off
          Encryption key:off
          Power Management:off
          Link Quality=66/70  Signal level=-44 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0
# for file in /sys/module/rtl8723be/parameters/*; do echo -n "${file}: "; cat $file; done

/sys/module/rtl8723be/parameters/debug: 0
/sys/module/rtl8723be/parameters/disable_watchdog: N
/sys/module/rtl8723be/parameters/fwlps: N
/sys/module/rtl8723be/parameters/ips: Y
/sys/module/rtl8723be/parameters/msi: N
/sys/module/rtl8723be/parameters/swenc: N
/sys/module/rtl8723be/parameters/swlps: N
# cat /etc/modprobe.d/rtl8723be.conf

options rtl8723be fwlps=0 swlps=0
# lspci -v

[...]
04:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8723BE PCIe Wireless Network Adapter
    Subsystem: Lenovo Device b728
    Flags: bus master, fast devsel, latency 0, IRQ 16
    I/O ports at 3000 [size=256]
    Memory at f0c00000 (64-bit, non-prefetchable) [size=16K]
    Capabilities: [40] Power Management version 3
    Capabilities: [50] MSI: Enable- Count=1/1 Maskable- 64bit+
    Capabilities: [70] Express Endpoint, MSI 00
    Capabilities: [100] Advanced Error Reporting
    Capabilities: [140] Device Serial Number 00-23-b7-fe-ff-4c-e0-00
    Capabilities: [150] Latency Tolerance Reporting
    Capabilities: [158] L1 PM Substates
    Kernel driver in use: rtl8723be

Please, help

**Comment by mikevmk** [comment]
I turned off the ips and turned on the debug

Nothing changed, still no errors and hiccup

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
