### ISSUE TITLE
RTL8822BE Problem

### ISSUE THREAD

**Issue by JordaNO10** [lwfinger/rtlwifi_new#531]
Hello There,
i've done all of the instructions you listed 
but sadly it did not work
i am using oracle VM virtual box
Kali linux on Debian x64
but after everything is done the Network card doesnt seem to pop up 
even after a reboot, i have tried a lot of guides but nothing seems to work
*i am pretty new to Kali and trying my best*
Please help
Thank you

**Comment by lwfinger** [comment]
Please tell me WHAT you did, not what you thought you were supposed to do.

**Comment by yagoplx** [comment]
Are you trying to use your wireless network card in a VM? 

This is an issue to be solved with hardware passthrough, not plugging it in and expecting the VM to know about the device.

What even is the device? An USB dongle? A PCI card?
Why not setup the device on Debian and then use NAT on the VM?

**Comment by JordaNO10** [comment]
Hello there again
after I got really mad about the OS
I installed a fresh one again
Using Oracle VM Virtual BOX
Kali Linux 2020 installed on Debian x64
followed your steps For The 
RTL8822BE 
and now I Don't know what to do 

*Tried to use Tenda 322U Wifi Adapter , But it doesn't Recognize it

**Comment by yagoplx** [comment]
From README: 
```
These drivers will not build for kernels older than 4.14. If you are using a kernel newer than 5.2,
I suggest that you use the driver built into the kernel!
```

Kali is on 5.4, you don't need to do anything this repository says - it's already in the kernel.

Install Kali Linux on the computer, in dual boot with Debian.
 ### not in **Oracle VM Virtual BOX**

**Comment by lwfinger** [comment]
YOU CANNOT RUN A PCI DEVICE IN A VIRTUAL MACHINE. That requires PCI PASSTHRU, and very few machines have a BIOS that will support that. None of mine do!

If you want to use wifi on the system, configure it in the host and use NAT in the guest.
