### ISSUE TITLE
modprobe rtl8723de : operation not allowed

### ISSUE THREAD

**Issue by himanshu-1608** [lwfinger/rtlwifi_new#532]
uname -sr value is Linux 5.3.0-40-generic.
I installed the rtl8723de driver as said in repo using steps : 
git clone https://github.com/lwfinger/rtlwifi_new.git -b extended
cd rtlwifi_new
make
sudo make install
sudo modprobe -r rtl8723de
sudo modprobe rtl8723de
At this point , a problem is approaching :
![Screenshot from 2020-03-03 01-40-23](https://user-images.githubusercontent.com/45948079/75713873-aea24d00-5cf0-11ea-8969-476819715b94.png)
I followed the issue registered here : 
https://github.com/lwfinger/rtlwifi_new/issues/333
I have changed ant_sel value to 2 and 1 . But not working .
I have disabled secured boot by changing BIOS settings.
Changed priority of UBUNTU from lower to higher.
Tried all combinations of priority and ant_sel values(even if it doesn't matter much) and rebooted every time .
It took several hours.
Still not working!

**Comment by lwfinger** [comment]
The first thing to do is to look at the output of dmesg to see why the operation is not permitted. Fix that before you try random fixes suggested by who knows. That might save hours as well.

**Comment by GodcraftPlata** [comment]
Try the following:

**Comment by GodcraftPlata** [comment]
Try the following:

`git clone https://github.com/lwfinger/rtlwifi_new.git -b extended
cd rtlwifi_new
make clean
make
sudo make install
sudo modprobe -r rtl8723de
sudo modprobe rtl8723de`

Don't use `sudo su` if possible.

**Comment by lwfinger** [comment]
"make clean" is never needed on a fresh clone, and rarely thereafter; however it does not help. Using sudo is necessary for any step that changes files in the Linux core or loads a module. The above sequence is correct. Using | to string commands together is dangerous. Using && is better as a failure will abort the sequence. An "or" will keep going doing nonsense, and perhaps harm.
