### ISSUE TITLE
rtl8723de cp: target '/lib/firmware//rtlwifi/.' is not a directory

### ISSUE THREAD

**Issue by mrizkimaulidan** [lwfinger/rtlwifi_new#533]
Hello, how do I fix this error? This error appears when I'm perform sudo make install command. I'm using Kali Linux 2020.1 fresh install with rtl8723de wireless driver code. Thank you!

![Image](https://i.imgur.com/BehAo8P.png)

**Comment by mrizkimaulidan** [comment]
Nevermind it's fixed now. The solution is I'm creating a folder named rtlwifi at /lib/firmware/ folder, and copy all file inside firmware/rtlwifi/ at github source and paste it on /lib/firmware/rtlwifi/ folder. Thank you so much for sharing the driver repositories! I'm closing this issue.

**Comment by lwfinger** [comment]
Your distro should have installed firmware and installed some files in that directory previously. I will change Makefile to create that folder when it does not exist.
