### ISSUE TITLE
Driver for Realtek 8811CU USB

### ISSUE THREAD

**Issue by Frick-David** [lwfinger/rtlwifi_new#534]
I do not see the driver for this usb in this repo. Is it possible covered by another device's driver?

Thanks.

**Comment by lwfinger** [comment]
Not likely that it is covered by one of these. The 8811au would be the closest, but it probably won't work.
It appears that there is a GitHub version. Try
git clone https://github.com/brektrou/rtl8821CU.git
Apparently, the 8821CU and the 8811CU share a driver. Good luck.
