### ISSUE TITLE
RTL8821AE concurrent modes?

### ISSUE THREAD

**Issue by johnothwolo** [lwfinger/rtlwifi_new#537]
Does the RTL8821AE support concurrent modes?

**Comment by lwfinger** [comment]
What do you want to do?

**Comment by johnothwolo** [comment]
I'm trying to run an access point and client connection from the same card. I tried creating 2 separate interfaces, but I get a `resource busy` error when I try to `ifconfig up` them both.

**Comment by lwfinger** [comment]
The driver needs to create two interfaces to be able to do what you want. That gets very complicated, and has never been done for any of the Realtek PCI devices that I know about. Just add a USB card for the client connection.

**Comment by johnothwolo** [comment]
I was afraid I'd have to do that, but thanks for the support anyways.
