### ISSUE TITLE
8723DE BT + WiFi cross-incompatibility

### ISSUE THREAD

**Issue by dikivan2000** [lwfinger/rtlwifi_new#539]
Greetings.
If have stumbled upon a problem (that is rather persistent, it's been around for a couple of months at least) with WiFi limiting Bluetooth functionality to a point where BT becomes unusable.
The issue is that when WiFi is on, the A2DP protocol nearly stops working. The sound stutters and lags beyond recognition. File transfer has not been tested, but the audio streaming is non-existent, not only through A2DP. When WiFi is turned off, everything's perfect. I understand that this is due to interference, however there is no such issue on Windows, which implies there is a workaround.

**Comment by lwfinger** [comment]
You are certainly welcome to revise the drivers to fix this interference. As I have said many times, I do not do Bluetooth and I have no interest in such a project.

If you want to look at it, you will need to carefully examine all over-the-air packets in the 2.4 G band to see what is interfering with the BT stuff.

**Comment by dikivan2000** [comment]
> You are certainly welcome to revise the drivers to fix this interference. As I have said many times, I do not do Bluetooth and I have no interest in such a project.
> 
> If you want to look at it, you will need to carefully examine all over-the-air packets in the 2.4 G band to see what is interfering with the BT stuff.

Thanks for the info, I'll take a look at it.
