### ISSUE TITLE
Bluetooth RTL8723 not working at all after the module is loaded.

### ISSUE THREAD

**Issue by mehanzhi** [lwfinger/rtlwifi_new#54]
Hello,

After I checked all this:
[root@localhost work]# lsmod |grep -i rtl87
rtl8723be             139259  0 
btcoexist             187416  1 rtl8723be
rtl_pci                39540  1 rtl8723be
rtlwifi               118563  3 btcoexist,rtl_pci,rtl8723be
mac80211              683564  3 rtl_pci,rtlwifi,rtl8723be
[root@localhost work]# 
[root@localhost work]# rfkill list
0: ideapad_wlan: Wireless LAN
    Soft blocked: no
    Hard blocked: no
1: ideapad_bluetooth: Bluetooth
    Soft blocked: no
    Hard blocked: no
2: phy0: Wireless LAN
    Soft blocked: no
    Hard blocked: no
[root@localhost work]# 
[root@localhost work]# uname -r
3.19.8-100.fc20.x86_64
[root@localhost work]# cat /etc/_release_
Fedora release 20 (Heisenbug)
NAME=Fedora
VERSION="20 (Heisenbug)"
ID=fedora
VERSION_ID=20
PRETTY_NAME="Fedora 20 (Heisenbug)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:20"
HOME_URL="https://fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=20
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=20
Fedora release 20 (Heisenbug)
Fedora release 20 (Heisenbug)
cpe:/o:fedoraproject:fedora:20
[root@localhost work]# 

I still can't get the bluetooth working. I'm not sure how exactly to check if it's working, so I'm just watching the bluetooth settings on my gnome menu. 

Anybody else have the same issue?

Thanks.

**Comment by lwfinger** [comment]
Where is the Bluetooth driver coming from?

**Comment by mehanzhi** [comment]
Hello,

It's from https://github.com/lwfinger/rtlwifi_new.git

Thanks!

**Comment by lwfinger** [comment]
There are no Bluetooth drivers for Realtek devices in this repo. You need to pull the repo at http://github.com/lwfinger/rtl8723au_bt.git and use the "kernel" branch.

**Comment by mehanzhi** [comment]
hmm, tried this one too and got the same result, but I'll report it there. 

Thanks.

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
