### ISSUE TITLE
RTW88 with rtw_pci gives a new mac on each boot.

### ISSUE THREAD

**Issue by bcv** [lwfinger/rtlwifi_new#540]
Hi,
 My laptop is HP pavilion. I have an `RTL8822BE 802.11a/b/g/n/ac WiFi adapter` 
I cloned this repo, switched to rtw88 branch and compiled the driver. The driver works fine and I am able to connect to the internet. 
However, On every boot I get this message 
```
[  233.574657] rtw_pci 0000:01:00.0: start vif b0:68:e6:6d:YY:XX on port 0
[  233.577632] rtw_pci 0000:01:00.0: stop vif b0:68:e6:6d:YY:XX on port 0
[  234.021393] rtw_pci 0000:01:00.0: start vif 36:2e:bc:0c:25:22 on port 0
```
Where b0:68:e6:6d:YY:XX  is the actual MAC of the card. The mac of wlo1 however in this instance is reported as 36:2e:bc:0c:25:22 and keeps changing for every boot thus my DHCP IP keeps changing. 

Is there a way to fix this MAC or even better if it can be made the same as the MAC of the card  i.e b0:68:e6:6d:YY:XX please ?

I have redacted the YY and XX and they are not actual strings in kernel messages.

**Comment by lwfinger** [comment]
User space is changing the MAC, not the driver. You will need to fix it there. If a constant IP address is required, you will need to change that elsewhere.
