### ISSUE TITLE
 could not insert 'rtl8723de': Operation not permitted

### ISSUE THREAD

**Issue by Anuradha4dm** [lwfinger/rtlwifi_new#542]
I have run the following codes,
sudo dkms add ./rtlwifi_new
sudo dkms install rtlwifi-new/0.6
sudo modprobe -r rtl8723de && modprobe rtl8723de

after run the last code it gives me,following error
could not insert 'rtl8723de': Operation not permitted

how i can fixed it?????

**Comment by lwfinger** [comment]
sudo modprobe -r rtl8723de && sudo modprobe rtl8723de

Those are two separate commands. The && means that the second should be executed ONLY if the first one did not fail. The "sudo" in your form only applies to the first one. Both need sudo.
