### ISSUE TITLE
rtl8723be for Ubuntu Kernel 5.3.x Not Working At All

### ISSUE THREAD

**Issue by Garry14** [lwfinger/rtlwifi_new#543]
I have cloned this rtlwifi_new then moved to **extended** branch. 
`git pull`
`make clean`
`make`
`sudo make install`
`sudo modprobe -r rtl8723be`
`sudo modprobe rtl8723be`

My signal still weak.. 

`sudo su -`
`echo "options rtl8723be ant_sel=2" > /etc/modprobe.d/rtl8723be.conf`
`exit`

then

`sudo modprobe -r rtl8723be`
`sudo modprobe rtl8723be`

Not affected.. 

My signal : 
`iwlist scan | egrep -i 'SSID|level'`

<pre>Quality=38/70  Signal <font color="#FF5555"><b>level</b></font>=-72 dBm</pre>

**Comment by lwfinger** [comment]
To be absolutely certain that a new ant_sel value has been applied, you need to cold boot the system. The device MUST be unpowered. Note that you either have to blacklist the driver or modify a .conf file in /etc/modprobe.d/, otherwise the driver will be loaded at boot!

A signal level of 72 dBm does mean that the driver is not looking at the correct antenna, but I do not think your tests are definitive. BTW, "ant_sel=2" is usually correct for those damned HP laptops with the problem.

**Comment by Garry14** [comment]
But my Laptop is HP

**Comment by lwfinger** [comment]
That is what I said.

**Comment by dev-harsh1998** [comment]
@Garry14 try compiling my fork, personal branch if laptop is was bought prior to 2017

**Comment by lwfinger** [comment]
Not all Lenovo or HP laptops suffer from the problem. On some of them, the manufacturer supplied TWO antennas. Those units have no signal strength difficulties.With some other models, they only supplied a single antenna and left the other connector open. This action is not the problem. The real trouble is that those units have a ROM that says that the antenna is connected to the other antenna. Rather than taking the step of reprogramming the ROM, they chose to modify the Windows driver to ignore the ROM when selecting an antenna. Of course, that means that any driver that believes the ROM will get it wrong. The ant_sel parameter was added to the Linux driver to allow a user to override the ROM, much in the way the Windows driver does.

Old laptops are much more likely to have two antennas and will not see the problem. @Garry14 does have it, thus I'm not sure what having him use your fork will correct.

**Comment by mikhailnov** [comment]
I have switched the `rtlwifi_new` dkms package in ROSA Linux from master branch (was built from commit 9dd7de8bcd53f3de55363cf76b8c92329c2e8e8b) to the extended branch (commit 47270286e13d2f9155df3fef25ef39d67ae6b58d)
The user, whose rtl8723be did work correctly, now reports this:
```
[    9.386403] rtlwifi_new: loading out-of-tree module taints kernel.
[    9.410817] BUG: unable to handle kernel NULL pointer dereference at 0000000000000000
[    9.410822] IP:           (null)
[    9.410824] PGD 0 P4D 0 
[    9.410827] Oops: 0010 [#1] PREEMPT SMP PTI
[    9.410829] Modules linked in: rtl8723be_new(O+) btcoexist_new(O) rtl8723_common_new(O) rtl_pci_new(O) rtlwifi_new(O) intel_wmi_thunderbolt mac80211 ecdh_generic cfg80211 int3403_thermal soc_button_array intel_vbtn sparse_keymap hp_wireless int3400_thermal mac_hid acpi_thermal_rel snd_hda_codec_hdmi snd_soc_skl intel_th_gth intel_th_pci intel_th snd_soc_skl_ipc snd_hda_ext_core snd_hda_codec_realtek snd_soc_sst_dsp snd_soc_sst_ipc snd_soc_acpi snd_hda_codec_generic snd_soc_core snd_compress ac97_bus snd_pcm_dmaengine i2c_i801 acpi_pad snd_hda_intel mei_me mei snd_hda_codec snd_hda_core snd_hwdep shpchp snd_pcm snd_timer snd soundcore intel_pch_thermal processor_thermal_device int340x_thermal_zone intel_soc_dts_iosf sch_fq_codel overlay binfmt_misc ip_tables x_tables amdkfd amd_iommu_v2 amdgpu i915
[    9.410852]  crct10dif_pclmul crc32_pclmul ghash_clmulni_intel chash i2c_algo_bit pcbc drm_kms_helper aesni_intel ttm hid_generic syscopyarea aes_x86_64 sysfillrect crypto_simd sysimgblt usbhid glue_helper fb_sys_fops cryptd r8169 drm hid serio_raw mii ahci libahci wmi video sunrpc autofs4
[    9.410864] CPU: 3 PID: 651 Comm: systemd-udevd Tainted: G           O     4.15.0-desktop-91.3rosa-x86_64 #1
[    9.410866] Hardware name: HP HP Notebook/8226, BIOS F.32 05/20/2019
[    9.410867] RIP: 0010:          (null)
[    9.410869] RSP: 0018:ffffb069c11ff9d0 EFLAGS: 00010282
[    9.410871] RAX: 0000000000000000 RBX: ffff9b9c363d1520 RCX: ffff9b9c363d1548
[    9.410872] RDX: ffffffffc0c49040 RSI: 00000000000000fc RDI: ffff9b9c363d1520
[    9.410874] RBP: ffffb069c11ff9f0 R08: 0000000000000001 R09: 0000000000000017
[    9.410875] R10: 0000000000000000 R11: 0000000000004001 R12: ffff9b9c363d1520
[    9.410877] R13: ffff9b9c363d0760 R14: ffff9b9c363d1520 R15: ffff9b9c37f2a0a0
[    9.410879] FS:  00007f95976a1580(0000) GS:ffff9b9c41d80000(0000) knlGS:0000000000000000
[    9.410881] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[    9.410883] CR2: 0000000000000000 CR3: 0000000268ce6001 CR4: 00000000003606e0
[    9.410884] Call Trace:
[    9.410892]  rtl8723be_read_eeprom_info+0x29/0xf0 [rtl8723be_new]
[    9.410896]  rtl_pci_probe+0x7b8/0x20f0 [rtl_pci_new]
[    9.410901]  local_pci_probe+0x4a/0xa0
[    9.410904]  ? pci_match_device+0xe0/0x110
[    9.410906]  pci_device_probe+0x118/0x1c0
[    9.410910]  driver_probe_device+0x2b3/0x4a0
[    9.410912]  __driver_attach+0xef/0x100
[    9.410914]  ? driver_probe_device+0x4a0/0x4a0
[    9.410931]  bus_for_each_dev+0x72/0xc0
[    9.410937]  driver_attach+0x1e/0x20
[    9.410939]  bus_add_driver+0x1f4/0x270
[    9.410943]  ? 0xffffffffc0c50000
[    9.410944]  driver_register+0x60/0xe0
[    9.410946]  ? 0xffffffffc0c50000
[    9.410949]  __pci_register_driver+0x5a/0x60
[    9.410954]  rtl8723be_driver_init+0x23/0x1000 [rtl8723be_new]
[    9.410957]  do_one_initcall+0x55/0x1ac
[    9.410960]  ? kmem_cache_alloc_trace+0xa1/0x1e0
[    9.410964]  do_init_module+0x5f/0x21c
[    9.410967]  load_module+0x190d/0x1f00
[    9.410971]  ? ima_post_read_file+0x83/0xa0
[    9.410975]  SYSC_finit_module+0xe5/0x120
[    9.410977]  ? SYSC_finit_module+0xe5/0x120
[    9.410981]  SyS_finit_module+0xe/0x10
[    9.410983]  do_syscall_64+0x73/0x130
[    9.410987]  entry_SYSCALL_64_after_hwframe+0x3d/0xa2
[    9.410989] RIP: 0033:0x7f95964a3af9
[    9.410990] RSP: 002b:00007ffdb0696728 EFLAGS: 00000246 ORIG_RAX: 0000000000000139
[    9.410992] RAX: ffffffffffffffda RBX: 000055ee7b894240 RCX: 00007f95964a3af9
[    9.410994] RDX: 0000000000000000 RSI: 00007f9596de27f6 RDI: 0000000000000013
[    9.410995] RBP: 00007f9596de27f6 R08: 0000000000000000 R09: 0000000000000000
[    9.410996] R10: 0000000000000013 R11: 0000000000000246 R12: 0000000000000000
[    9.410998] R13: 000055ee7ba774e0 R14: 0000000000020000 R15: 000055ee7b894240
[    9.411000] Code:  Bad RIP value.
[    9.411005] RIP:           (null) RSP: ffffb069c11ff9d0
[    9.411006] CR2: 0000000000000000
[    9.411009] ---[ end trace 974c84ef6553c2ee ]---
```

It is kernel 4.15 from Ubuntu, adn there is no good debuginfo for it, I will try to ask him to check from the upstream kernel 5.4.28 where there is debuginfo in case it will help.

**Comment by mikhailnov** [comment]
Maybe it is offtop in this issue, but the title says "not working at all", but the description says that signal level is low.

**Comment by lwfinger** [comment]
No one pays any attention to the issue title. I get rtl8723ae issues in an rtl8723be set. Why should they change now?

So far, the majority of NULL pointer issues cannot be duplicated by me. I can only assume that some distros are publishing crap kernels. I guess that is what you get when you choose the hottest distros on DistroWatch, or some similar site. Those of us that maintain solid distros do not set up click robots to get our ratings high!!

I cannot do anything with kernels without debug info.

**Comment by mikhailnov** [comment]
Here I paid attention at the title of the issue, but no comments inside it. Sorry.
Nowadays I myself maintain kernels in ROSA and build propper debuginfo. If I am able to convince that user to reproduce the issue, I will give you all the information, including the sources of the kernels, all patches (the kernel is mostly vanilla), Kconfig, kernel binaries and debuginfo and I will ask that user to provide a binary kernel module that was built on host host via dkms.
If a separate issue is needed, please let me know. I will try to be more attentive next time.
