### ISSUE TITLE
Driver not working with RTL8723DE with kernel 5.3.0-46-generic

### ISSUE THREAD

**Issue by mayank-chandak** [lwfinger/rtlwifi_new#547]
The wifi network adapter indicates to be missing just as before installing the drivers on Ubuntu.

**Comment by lwfinger** [comment]
OK, please give me a little more information.
Post the output of 'lspci -nn'.
Did you checkout the "extended" branch? Use 'git branch' to check.
Does the output of dmesg mention any problems?
Post the output of 'lsmod | grep 8873'.

**Comment by mayank-chandak** [comment]
lspci -nn gives the following output

00:00.0 Host bridge [0600]: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Host Bridge/DRAM Registers [8086:1904] (rev 08)
00:02.0 VGA compatible controller [0300]: Intel Corporation Skylake GT2 [HD Graphics 520] [8086:1916] (rev 07)
00:04.0 Signal processing controller [1180]: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Thermal Subsystem [8086:1903] (rev 08)
00:14.0 USB controller [0c03]: Intel Corporation Sunrise Point-LP USB 3.0 xHCI Controller [8086:9d2f] (rev 21)
00:14.2 Signal processing controller [1180]: Intel Corporation Sunrise Point-LP Thermal subsystem [8086:9d31] (rev 21)
00:16.0 Communication controller [0780]: Intel Corporation Sunrise Point-LP CSME HECI #1 [8086:9d3a] (rev 21)
00:17.0 SATA controller [0106]: Intel Corporation Sunrise Point-LP SATA Controller [AHCI mode] [8086:9d03] (rev 21)
00:1c.0 PCI bridge [0604]: Intel Corporation Sunrise Point-LP PCI Express Root Port #1 [8086:9d10] (rev f1)
00:1c.5 PCI bridge [0604]: Intel Corporation Sunrise Point-LP PCI Express Root Port #6 [8086:9d15] (rev f1)
00:1d.0 PCI bridge [0604]: Intel Corporation Sunrise Point-LP PCI Express Root Port #9 [8086:9d18] (rev f1)
00:1f.0 ISA bridge [0601]: Intel Corporation Sunrise Point-LP LPC Controller [8086:9d48] (rev 21)
00:1f.2 Memory controller [0580]: Intel Corporation Sunrise Point-LP PMC [8086:9d21] (rev 21)
00:1f.3 Audio device [0403]: Intel Corporation Sunrise Point-LP HD Audio [8086:9d70] (rev 21)
00:1f.4 SMBus [0c05]: Intel Corporation Sunrise Point-LP SMBus [8086:9d23] (rev 21)
02:00.0 Ethernet controller [0200]: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller [10ec:8168] (rev 15)
03:00.0 Network controller [0280]: Realtek Semiconductor Co., Ltd. RTL8723DE 802.11b/g/n PCIe Adapter [10ec:d723]

Yes, I was already on extended branch.

dmesg gives the following output

[   12.665969] Bluetooth: hci0: RTL: rtl: loading rtl_bt/rtl8723d_config.bin
[   12.961579] Bluetooth: hci0: RTL: cfg_sz 10, total sz 33266
[   12.979618] rtlwifi: loading out-of-tree module taints kernel.
[   12.979687] rtlwifi: module verification failed: signature and/or required key missing - tainting kernel
[   13.191579] rtl8723_common: version magic '5.3.0-45-generic SMP mod_unload ' should be '5.3.0-46-generic SMP mod_unload '


lsmod | grep 8873 does not give any output.

**Comment by lwfinger** [comment]
[ 12.979687] rtlwifi: module verification failed: signature and/or required key missing - tainting kernel

Go into your BIOS and turn off secure boot.

**Comment by mayank-chandak** [comment]
Secure boot was already disabled.

**Comment by lwfinger** [comment]
Then your kernel is demanding a key, which this driver does not have.
https://ubuntu.com/blog/how-to-sign-things-for-secure-boot tells you what to do. My kernels do not demand it when the BIOS does not. I am not going to do that.

**Comment by mayank-chandak** [comment]
So, I could not really understand how I can give the key which it was demanding. So, I waited for an updated kernel. I think there was something wrong with the kernel. Anyways, the kernel 5.4 supports my adapter too, so, I didn't need to install the drivers.

Thanks
