### ISSUE TITLE
RTL8723DE Availability after waking up and Speed

### ISSUE THREAD

**Issue by fjaviergallucci** [lwfinger/rtlwifi_new#550]
Hi guys,

Thanks for invest your time to make the life of all of us easier. I need some help regarding my HP laptop. I had to install Ubuntu 20.04 (not my favorite Linux dist, but was the only one to load all the hardware, after trying with Debian, Manjaro, Debian non-free, Mint).

These is the specs of the network adapter and the kernel:

> $ lshw -C network
 *-network                 
       description: Wireless interface
       product: RTL8723DE 802.11b/g/n PCIe Adapter
       vendor: Realtek Semiconductor Co., Ltd.
       physical id: 0
       bus info: pci@0000:01:00.0
       logical name: wlo1
       version: 00
       serial: e8:6f:38:a4:f4:33
       width: 64 bits
       clock: 33MHz
       capabilities: bus_master cap_list ethernet physical wireless
       configuration: broadcast=yes driver=rtw_pci driverversion=5.4.0-26-generic firmware=N/A ip=192.168.1.95 latency=0 link=yes multicast=yes wireless=IEEE 802.11
       resources: irq:139 ioport:3000(size=256) memory:82200000-8220ffff

> $uname -a
Linux francisco 5.4.0-26-generic #30-Ubuntu SMP Mon Apr 20 16:58:30 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

So I have two problems actually:
1. Speed: I run some speed test on the connection and I always got less than 15mb, and in my other devices (Windows laptop about 250mb, cellphones about 60mb) I got much more. My plan is supposed to be 300mb.

2. Availability: If I send the laptop to sleep, when I wake it up, the wifi nor the BT are working. I need to restart the OS in order to them to work again.

Any help guys you can give me that would be great, I have days searching on internet for solutions. I tried disable the power management, restarting services, and others.

I installed the driver with DKMS, instead modprobe. Not sure if this can be a problem.

Thanks

**Comment by lwfinger** [comment]
I have no idea why the driver fails to wake up after sleeping. My only suggestion is that you find out how to run scripts after waking up and create one that unloads and reloads the driver. As the location of such a script is distro dependent, I cannot give you further advice.

Please be aware that I know nothing of the internals of the device, thus I cannot help the speed issue. I do not work for Realtek, and I have no NDAs with them. There is a new driver coming provided by Realtek. My tests show it getting about 50 Mbps.

**Comment by lwfinger** [comment]
The new driver for RTL8723DE is now in the wireless_drivers_next repo. To make it easier for users here, it is now in the rtw88 branch. Do the following:

git checkout origin/rtw88 -b rtw88
make
sudo make install

This version should build on kernels 4.5 or newer.

Please be aware that on June 1, 2020, all branches in this repo will be deleted except for rtw88. If you really need the other drivers for old kernels, use the "backports" project. These old drivers have been taking too much of my time!

**Comment by fjaviergallucci** [comment]
Awesome. Thanks for doing this.
