### ISSUE TITLE
rtl8723de. rtlwifi_new-master can't be compiled with 'make' on 5.6.8-arch1-1

### ISSUE THREAD

**Issue by antonkharkov** [lwfinger/rtlwifi_new#557]
I tried to compile the latest package rtlwifi_new-master on 5.6.8-arch1-1 for rtl8723de, but it stops with the errors below. What can be the problem?

[a_l@al rtlwifi_new-master]$ make
make -C /lib/modules/5.6.8-arch1-1/build M=/home/a_l/rtlwifi_new-master modules
make[1]: Entering directory '/usr/lib/modules/5.6.8-arch1-1/build'
  CC [M]  /home/a_l/rtlwifi_new-master/btcoexist/halbtc8192e2ant.o
  CC [M]  /home/a_l/rtlwifi_new-master/btcoexist/halbtc8723b1ant.o
  CC [M]  /home/a_l/rtlwifi_new-master/btcoexist/halbtc8723b2ant.o
  CC [M]  /home/a_l/rtlwifi_new-master/btcoexist/halbtc8821a1ant.o
  CC [M]  /home/a_l/rtlwifi_new-master/btcoexist/halbtc8821a2ant.o
  CC [M]  /home/a_l/rtlwifi_new-master/btcoexist/halbtcoutsrc.o
  CC [M]  /home/a_l/rtlwifi_new-master/btcoexist/rtl_btc.o
  LD [M]  /home/a_l/rtlwifi_new-master/btcoexist/btcoexist.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8188ee/dm.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8188ee/fw.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8188ee/hw.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8188ee/led.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8188ee/phy.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8188ee/pwrseq.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8188ee/pwrseqcmd.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8188ee/rf.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8188ee/sw.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8188ee/table.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8188ee/trx.o
  LD [M]  /home/a_l/rtlwifi_new-master/rtl8188ee/rtl8188ee.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192c/main.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192c/dm_common.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192c/fw_common.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192c/phy_common.o
  LD [M]  /home/a_l/rtlwifi_new-master/rtl8192c/rtl8192c-common.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192ce/dm.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192ce/fw.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192ce/hw.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192ce/led.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192ce/phy.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192ce/rf.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192ce/sw.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192ce/table.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192ce/trx.o
  LD [M]  /home/a_l/rtlwifi_new-master/rtl8192ce/rtl8192ce.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192cu/dm.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192cu/hw.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192cu/led.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192cu/mac.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192cu/phy.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192cu/rf.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192cu/sw.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192cu/table.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192cu/trx.o
  LD [M]  /home/a_l/rtlwifi_new-master/rtl8192cu/rtl8192cu.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192de/dm.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192de/fw.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192de/hw.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192de/led.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192de/phy.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192de/rf.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192de/sw.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192de/table.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192de/trx.o
  LD [M]  /home/a_l/rtlwifi_new-master/rtl8192de/rtl8192de.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192ee/dm.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192ee/fw.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192ee/hw.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192ee/led.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192ee/phy.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192ee/pwrseq.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192ee/pwrseqcmd.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192ee/rf.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192ee/sw.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192ee/table.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192ee/trx.o
  LD [M]  /home/a_l/rtlwifi_new-master/rtl8192ee/rtl8192ee.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192se/dm.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192se/fw.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192se/hw.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192se/led.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192se/phy.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192se/rf.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192se/sw.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192se/table.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8192se/trx.o
  LD [M]  /home/a_l/rtlwifi_new-master/rtl8192se/rtl8192se.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8723ae/dm.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8723ae/fw.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8723ae/hal_btc.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8723ae/hal_bt_coexist.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8723ae/hw.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8723ae/led.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8723ae/phy.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8723ae/pwrseq.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8723ae/pwrseqcmd.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8723ae/rf.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8723ae/sw.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8723ae/table.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8723ae/trx.o
  LD [M]  /home/a_l/rtlwifi_new-master/rtl8723ae/rtl8723ae.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8723be/dm.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8723be/fw.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8723be/hw.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8723be/led.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8723be/phy.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8723be/pwrseq.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8723be/pwrseqcmd.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8723be/rf.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8723be/sw.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8723be/table.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8723be/trx.o
  LD [M]  /home/a_l/rtlwifi_new-master/rtl8723be/rtl8723be.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8723com/main.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8723com/dm_common.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8723com/fw_common.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8723com/phy_common.o
  LD [M]  /home/a_l/rtlwifi_new-master/rtl8723com/rtl8723-common.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8821ae/dm.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8821ae/fw.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8821ae/hw.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8821ae/led.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8821ae/phy.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8821ae/pwrseq.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8821ae/pwrseqcmd.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8821ae/rf.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8821ae/sw.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8821ae/table.o
  CC [M]  /home/a_l/rtlwifi_new-master/rtl8821ae/trx.o
  LD [M]  /home/a_l/rtlwifi_new-master/rtl8821ae/rtl8821ae.o
  CC [M]  /home/a_l/rtlwifi_new-master/base.o
  CC [M]  /home/a_l/rtlwifi_new-master/cam.o
  CC [M]  /home/a_l/rtlwifi_new-master/core.o
  CC [M]  /home/a_l/rtlwifi_new-master/debug.o
  CC [M]  /home/a_l/rtlwifi_new-master/efuse.o
  CC [M]  /home/a_l/rtlwifi_new-master/ps.o
  CC [M]  /home/a_l/rtlwifi_new-master/rc.o
/home/a_l/rtlwifi_new-master/rc.c:289:11: error: initialization of ‘void * (*)(struct ieee80211_hw *)’ from incompatible pointer type ‘void * (*)(struct ieee80211_hw *, struct dentry *)’ [-Werror=incompatible-pointer-types]
  289 |  .alloc = rtl_rate_alloc,
      |           ^~~~~~~~~~~~~~
/home/a_l/rtlwifi_new-master/rc.c:289:11: note: (near initialization for ‘rtl_rate_ops.alloc’)
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:268: /home/a_l/rtlwifi_new-master/rc.o] Error 1
make[1]: *** [Makefile:1683: /home/a_l/rtlwifi_new-master] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.6.8-arch1-1/build'
make: *** [Makefile:58: all] Error 2
[a_l@al rtlwifi_new-master]$

**Comment by lwfinger** [comment]
The problem is that your idiotic disto backported a change made in kernel 5.7.0 to 5.6.8. As I am getting very tired of explaining, I do not have the time nor the patience to keep track of every distro to condition the build to work without breaking it for people running vanilla kernels.

Near where you get the error, you will find a test for kernel 5,7,0. Change that to 5.6.8, and it should compile. Beware, that you will get problems if there are any updates as a git pull will fail if your source does not match mine.

By the way, this is the 3rd time I have written this info this morning, and it is not yet 11 AM here!

**Comment by antonkharkov** [comment]
Well, the problem was a complete mess with KDMS. After removing them and installing from the extended branch everything works now. Thanks a lot for your great support!

**Comment by lwfinger** [comment]
I find dkms more trouble than it is worth.
