### ISSUE TITLE
Help: Failed building on kernel 5.4.x

### ISSUE THREAD

**Issue by donihalim** [lwfinger/rtlwifi_new#558]
I just upgraded my kernel on Void Linux to ` 5.4.36_1` but I got error when building the extended branch (need rtl8723de). Build were success on previous kernel version `5.4.35_1` and failed after upgrading the kernel.

Here's the error log:
```
/var/lib/dkms/rtlwifi-new/0.6/build/rc.c:340:11: error: initialization of 'void
* (*)(struct ieee80211_hw *)' from incompatible pointer type 'void * (*)(struct
ieee80211_hw *, struct dentry *)'
[-Werror=incompatible-pointer-types]
  340 |  .alloc = rtl_rate_alloc,
      |           ^~~~~~~~~~~~~~
/var/lib/dkms/rtlwifi-new/0.6/build/rc.c:340:11: note: (near initialization for
'rtl_rate_ops.alloc')
cc1: some warnings being treated as errors
make[1]: *** [scripts/Makefile.build:266: /var/lib/dkms/rtlwifi-new/0.6/build/rc.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:1691: /var/lib/dkms/rtlwifi-new/0.6/build] Error 2
make: Leaving directory '/usr/src/kernel-headers-5.4.36_1'```

Kernel version:
`Linux void 5.4.36_1 #1 SMP PREEMPT Thu Apr 30 22:51:27 UTC 2020 x86_64 GNU/Linux`

Thank you.

**Comment by donihalim** [comment]
full log
[make.log](https://github.com/lwfinger/rtlwifi_new/files/4565706/make.log)

**Comment by estevaozr** [comment]
I was about to create an issue for a similar problem I had. Same build error but on Arch Linux:
`Linux (name) 5.6.8-arch1-1 #1 SMP PREEMPT Wed, 29 Apr 2020 16:22:56 +0000 x86_64 GNU/Linux
`
and got this error:

>/home/user/workspace/rtl8723de_lwfinger/rtlwifi_new/rc.c:340:11: error: initialization of ‘void * (*)(struct ieee80211_hw *)’ from incompatible pointer type ‘void * (*)(struct ieee80211_hw *, struct dentry *)’ [-Werror=incompatible-pointer-types]
>  340 |  .alloc = rtl_rate_alloc,
>      |           ^~~~~~~~~~~~~~
>/home/user/workspace/rtl8723de_lwfinger/rtlwifi_new/rc.c:340:11: note: (near initialization for ‘rtl_rate_ops.alloc’)

I changed the source code like this and I was able to build and use the final result as normal (using it right now)

> diff --git a/rc.c b/rc.c
>index 8452e07..9f32558 100644
>--- a/rc.c
>+++ b/rc.c
>@@ -294,11 +294,11 @@ static void rtl_rate_update(void *ppriv,
> }
> #endif
> 
>-#if (LINUX_VERSION_CODE >= KERNEL_VERSION(5, 7, 0))
>+//#if (LINUX_VERSION_CODE >= KERNEL_VERSION(5, 7, 0))
> static void *rtl_rate_alloc(struct ieee80211_hw *hw)
>-#else
>-static void *rtl_rate_alloc(struct ieee80211_hw *hw, struct dentry *debugfsdir)
>-#endif
>+//#else
>+//static void *rtl_rate_alloc(struct ieee80211_hw *hw, struct dentry *debugfsdir)
>+//#endif
> {
> 	struct rtl_priv *rtlpriv = rtl_priv(hw);
> 	return rtlpriv;

I think the Kernel version in this check could be wrong, but I don't know much about what should be there.

Hope this could help out fixing this.

**Comment by donihalim** [comment]
I also have similar problem on Arch Linux (Dual boot) huh.
I'll try the patch, thank you very much.

**Comment by lwfinger** [comment]
In rc.r, you will see code that says
#if`` LINUX_VERSION_CODE >= KERNEL_VERSION(5, 7, 0)
static void *rtl_rate_alloc(struct ieee80211_hw *hw)
#else
static void *rtl_rate_alloc(struct ieee80211_hw *hw, struct dentry *debugfsdir)
#endif

Change the 5, 7, 0 to whatever version is failing now. The version check is correct in my code; however, some bastard has backported a kernel API change. That should not happen!

**Comment by lwfinger** [comment]
This issue is not properly fixed. See Issue #570 for explanation.

**Comment by donihalim** [comment]
Thank you for the follow up
