### ISSUE TITLE
Can not install the RTL8723DE module after updating to Fedora 32

### ISSUE THREAD

**Issue by edier88** [lwfinger/rtlwifi_new#559]
Hi there, I hope you are fine.
I want to say that everything worked great in Fedora 31. However, after a clean install of Fedora 32 and after doing a "make" I get these two warnings and this error:

  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8723be/hw.o
/var/lib/dkms/rtlwifi-new/0.6/build/rtl8723ae/phy.c: In function ‘rtl8723e_phy_set_txpower_level.part.0’:
/var/lib/dkms/rtlwifi-new/0.6/build/rtl8723ae/phy.c:645:47: warning: ‘ofdmpowerlevel’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  645 |  rtlphy->cur_ofdm24g_txpwridx = ofdmpowerlevel[0];
.......|.................................................~~~~~~~~~~~~~~^~~

  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/phydm_smt_ant.o
/var/lib/dkms/rtlwifi-new/0.6/build/rtl8192c/phy_common.c: In function ‘rtl92c_phy_set_txpower_level’:
/var/lib/dkms/rtlwifi-new/0.6/build/rtl8192c/phy_common.c:579:47: warning: ‘ofdmpowerlevel’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  579 |  rtlphy->cur_ofdm24g_txpwridx = ofdmpowerlevel[0];
.......|.................................................~~~~~~~~~~~~~~^~~

  CC [M]  /home/edier88/Documents/rtlwifi_new/rc.o
/home/edier88/Documents/rtlwifi_new/rc.c:336:11: error: initialization of ‘void * (*)(struct ieee80211_hw *, struct dentry *)’ from incompatible pointer type ‘void * (*)(struct ieee80211_hw *)’ [-Werror=incompatible-pointer-types]
  336 |  .alloc = rtl_rate_alloc,
.......|.............^~~~~~~~~~~~~~
/home/edier88/Documents/rtlwifi_new/rc.c:336:11: note: (near initialization for ‘rtl_rate_ops.alloc’)

At the end the output gives me this:

cc1: some warnings being treated as errors
make[1]: *** [scripts/Makefile.build:268: /var/lib/dkms/rtlwifi-new/0.6/build/rc.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:1683: /var/lib/dkms/rtlwifi-new/0.6/build] Error 2
make: Leaving directory '/usr/src/kernels/5.6.7-300.fc32.x86_64'

Fedora 32 comes with this Kernel Version: 5.6.7-300
It has something to do with the kernel update? 
There's something I can do, or am I doing something wrong?
Thanks in advance for your replies!

**Comment by lwfinger** [comment]
Pull again. The error was fixed today. Ignore the warning.

**Comment by neetupandey20** [comment]
hello i got same issue in my ubuntu 16.04 
 CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/base.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/cam.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/core.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/debug.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/efuse.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/ps.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rc.o
/var/lib/dkms/rtlwifi-new/0.6/build/rc.c:336:11: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .alloc = rtl_rate_alloc,
           ^
/var/lib/dkms/rtlwifi-new/0.6/build/rc.c:336:11: note: (near initialization for ‘rtl_rate_ops.alloc’)
cc1: some warnings being treated as errors

**Comment by lwfinger** [comment]
This issue is not properly fixed. See Issue #570 for explanation.
