### ISSUE TITLE
Does not install with linux 5.6.8-arch1-1

### ISSUE THREAD

**Issue by favre49** [lwfinger/rtlwifi_new#560]
When upgrading to version 5.6.8, the following error is encountered on install:

```
/var/lib/dkms/rtlwifi_new/r303.2113764/build/rc.c:340:11: error: initialization of ‘void * (*)(struct ieee80211_hw *)’ from incompatible pointer type ‘void * (*)(struct ieee80211_hw *, struct dentry *)’ [-Werror=incompatible-pointer-types]
  340 |  .alloc = rtl_rate_alloc,
      |           ^~~~~~~~~~~~~~
/var/lib/dkms/rtlwifi_new/r303.2113764/build/rc.c:340:11: note: (near initialization for ‘rtl_rate_ops.alloc’)
  CC [M]  /var/lib/dkms/rtlwifi_new/r303.2113764/build/pci.o
cc1: some warnings being treated as errors
make[1]: *** [scripts/Makefile.build:268: /var/lib/dkms/rtlwifi_new/r303.2113764/build/rc.o] Error 1

```

Full log can be found [here](http://p.ip.fi/qCOW)

System details:
Arch Linux
Kernel 5.6.8
RTL8822BE
rtlwifi_new, r303.2113764

**Comment by grip90** [comment]
I just installed Ubuntu 20.04 LTS. I am facing the same issue while trying to run make. Please let me know if there's a solution

**Comment by klaasg** [comment]
I have the same error, for RTL8723DE (extended branch).

**Comment by pradhanharshil** [comment]
I tried to install it from AUR on linux lts kernel 5.4.36-1-lts and it failed to install.

**Comment by jonathonf** [comment]
Come on people, try [searching for existing issues](https://github.com/lwfinger/rtlwifi_new/issues?q=rtl_rate_alloc) before posting a "new" one and then you won't annoy the developer with constant stream of duplicate reports which have already been answered.

This is a duplicate of #554 and several others.

**Comment by favre49** [comment]
You're right, that's my bad. I'll close this because #554 is also apparently fixed.

**Comment by lwfinger** [comment]
The developer gets REALLY annoyed when people report a problem WITHOUT doing a 'git pull' first!!!! Why do I bother?????

**Comment by jonathonf** [comment]
> Why do I bother?????

Because we love you and you're doing an amazing job. :kissing_heart:

**Comment by TonyThuitai** [comment]
You can use the AUR (Arch User Repository) package: rtlwifi_new-extended-dkms on Arch or any other Arch-based distro. I have tested it today on Manjaro 20.0 and it installs the rtl8723de driver for my PC. The AUR package was modified yesterday to use the latest changes/commits.

**Comment by lwfinger** [comment]
This issue is not properly fixed. See Issue #570 for explanation.
