### ISSUE TITLE
build fails because of incompatible-pointer type in rc.c

### ISSUE THREAD

**Issue by GitMensch** [lwfinger/rtlwifi_new#561]
~~~
/tmp/rtlwifi_new/rc.c:336:11: error: initialization of ‘void * (*)(struct ieee80211_hw *, struct dentry *)’ from incompatible pointer type ‘void * (*)(struct ieee80211_hw *)’ [-Werror=incompatible-pointer-types]
  336 |  .alloc = rtl_rate_alloc,
      |           ^~~~~~~~~~~~~~
/tmp/rtlwifi_new/rc.c:336:11: note: (near initialization for ‘rtl_rate_ops.alloc’)
cc1: some warnings being treated as errors
~~~

Using GCC 9.3 and linux-libre-5.6.8 kernel headers.

**Comment by lwfinger** [comment]
That fucking bug is fixed. DO A GIT PULL BEFORE YOU REPORT A PROBLEM!!!!!

**Comment by GitMensch** [comment]
That is very strange as I did a clean git clone from the extended branch (*that* info was definitely missing) directly before building and about half an hour before posting the bug. Is it only part of the extended branch or did my checkout via `git clone https://github.com/lwfinger/rtlwifi_new.git -b extended` is bad?

**Comment by lwfinger** [comment]
I do not know what your problem is, but I pushed that fix with commit f19fee2633819ee2abc.

What is the top non-merge commit in your source?

**Comment by lwfinger** [comment]
I just did a new clone, and it was fine.

**Comment by GitMensch** [comment]
> I do not know what your problem is, but I pushed that fix with commit f19fee2.

`git log` says that is the last commit on the local clone...
`git pull` says "Already up to date".

Hm, make and install works today ?!? Maybe reboot fixed some pending kernel header updates - I have no clue (build and install of rtl8723au_bt worked yesterday).

Sorry for the noise.

**Comment by lwfinger** [comment]
This issue is not properly fixed. See Issue #570 for explanation.

**Comment by GajendraMahato** [comment]
Any one help me
i got this problem 
root@kali:~/Downloads/rtlwifi_new-extended# make install
make -C /lib/modules/5.6.0-kali2-amd64/build M=/root/Downloads/rtlwifi_new-extended modules
make[1]: Entering directory '/usr/src/linux-headers-5.6.0-kali2-amd64'
  CC [M]  /root/Downloads/rtlwifi_new-extended/rc.o
/root/Downloads/rtlwifi_new-extended/rc.c:336:11: error: initialization of ‘void * (*)(struct ieee80211_hw *)’ from incompatible pointer type ‘void * (*)(struct ieee80211_hw *, struct dentry *)’ [-Werror=incompatible-pointer-types]
  336 |  .alloc = rtl_rate_alloc,
      |           ^~~~~~~~~~~~~~
/root/Downloads/rtlwifi_new-extended/rc.c:336:11: note: (near initialization for ‘rtl_rate_ops.alloc’)
cc1: some warnings being treated as errors
make[3]: *** [/usr/src/linux-headers-5.6.0-kali2-common/scripts/Makefile.build:273: /root/Downloads/rtlwifi_new-extended/rc.o] Error 1
make[2]: *** [/usr/src/linux-headers-5.6.0-kali2-common/Makefile:1704: /root/Downloads/rtlwifi_new-extended] Error 2
make[1]: *** [/usr/src/linux-headers-5.6.0-kali2-common/Makefile:180: sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.6.0-kali2-amd64'
make: *** [Makefile:85: all] Error 2
root@kali:~/Downloads/rtlwifi_new-extended#
