### ISSUE TITLE
Latest commit to rtlwifi_new extended branch causes rtl8723de to fail to build and install on Linux Mint 19.3 with kernel 5.3 due to incompatible pointer error

### ISSUE THREAD

**Issue by TonyThuitai** [lwfinger/rtlwifi_new#563]
I have installed Linux Mint 19.3 XFCE with the same kernel version (5.3.0-51-generic after update but came with kernel 5.0) and same updates twice this month for Testing purposes before I use it as a daily driver. I used the the  [ubuntuhandbook manual link](http://ubuntuhandbook.org/index.php/2019/04/nstall-rtl8723de-wifi-driver-ubuntu-19-04/) to install the rtl8723de driver. The driver installed successfully on mid-morning (UTC+3) May 1st but Today (May 3rd) early morning (UTC+3), the driver installs but not working even after poweroff and turning the PC on and even tried to modprobe the driver code but it says that the module does not exist in the modules directory tree of the kernel. I suspect the last commit caused the issue but not the distribution because the driver never fails to install on my PC before the last commit. Reinstalled Linux Mint but the driver always fails to install with the error. Also tested the driver on Manjaro via the rtlwifi_new-extended-dkms AUR package which was updated yesterday after the last commit and it works on kernel 5.4.36. Note that I am an intermediate Linux user who is a GitHub beginner.

DKMS make.log for rtlwifi-new-0.6 for kernel 5.3.0-51-generic (x86_64)
Sun May  3 10:49:41 EAT 2020
make: Entering directory '/usr/src/linux-headers-5.3.0-51-generic'
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/btcoexist/halbtc8192e2ant.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/halmac/halmac_api.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/phydm_debug.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8188ee/dm.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/halmac/halmac_88xx/halmac_api_88xx_usb.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8188ee/fw.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/btcoexist/halbtc8723b1ant.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/phydm_antdiv.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/halmac/halmac_88xx/halmac_api_88xx_sdio.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8188ee/hw.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/phydm_soml.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/halmac/halmac_88xx/halmac_api_88xx.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/btcoexist/halbtc8723b2ant.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/phydm_smt_ant.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8188ee/led.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/phydm_interface.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/btcoexist/halbtc8821a1ant.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/halmac/halmac_88xx/halmac_api_88xx_pcie.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8188ee/phy.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/phydm_phystatus.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/btcoexist/halbtc8821a2ant.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/halmac/halmac_88xx/halmac_func_88xx.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/phydm_hwconfig.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8188ee/pwrseq.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/btcoexist/halbtc8822b1ant.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8188ee/rf.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/phydm.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/halmac/halmac_88xx/halmac_8822b/halmac_api_8822b_pcie.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8188ee/sw.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/phydm_dig.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/halmac/halmac_88xx/halmac_8822b/halmac_func_8822b.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/btcoexist/halbtc8822b2ant.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8188ee/table.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8188ee/trx.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/phydm_pathdiv.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/halmac/halmac_88xx/halmac_8822b/halmac_api_8822b_sdio.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/phydm_rainfo.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/halmac/halmac_88xx/halmac_8822b/halmac_api_8822b.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/btcoexist/halbtc8822bwifionly.o
  LD [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8188ee/rtl8188ee.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192c/main.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/phydm_dynamictxpower.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/halmac/halmac_88xx/halmac_8822b/halmac_8822b_phy.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/btcoexist/halbtc8723d1ant.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192c/dm_common.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/phydm_adaptivity.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/halmac/halmac_88xx/halmac_8822b/halmac_8822b_pwr_seq.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/phydm_cfotracking.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/halmac/halmac_88xx/halmac_8822b/halmac_api_8822b_usb.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192c/fw_common.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/btcoexist/halbtc8723d2ant.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/halmac/rtl_halmac.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/phydm_noisemonitor.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192c/phy_common.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/phydm_dfs.o
  LD [M]  /var/lib/dkms/rtlwifi-new/0.6/build/halmac/halmac.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192ce/dm.o
  LD [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192c/rtl8192c-common.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192cu/dm.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/btcoexist/halbtcoutsrc.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/phydm_adc_sampling.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192ce/hw.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192cu/hw.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/phydm_ccx.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/btcoexist/rtl_btc.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/phydm_psd.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192cu/led.o
  LD [M]  /var/lib/dkms/rtlwifi-new/0.6/build/btcoexist/btcoexist.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192ce/led.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192de/dm.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/phydm_primary_cca.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192ce/phy.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192cu/mac.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/phydm_cck_pd.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192de/fw.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/phydm_rssi_monitor.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192ce/rf.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192cu/phy.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192de/hw.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/phydm_auto_dbg.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192cu/rf.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192ce/sw.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/phydm_math_lib.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192cu/sw.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192de/led.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192ce/table.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192ce/trx.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/phydm_api.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192cu/table.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192cu/trx.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192de/phy.o
  LD [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192ce/rtl8192ce.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192ee/dm.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/phydm_pow_train.o
  LD [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192cu/rtl8192cu.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/halrf/halrf.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192ee/fw.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/halrf/halphyrf_ce.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/halrf/halrf_powertracking_ce.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192de/rf.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192ee/hw.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/halrf/halrf_powertracking.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/halrf/halrf_kfree.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192de/sw.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/halrf/rtl8822b/halrf_8822b.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/halrf/rtl8822b/halrf_iqk_8822b.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192de/table.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192de/trx.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192ee/led.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/rtl8822b/halhwimg8822b_bb.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/rtl8822b/halhwimg8822b_mac.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192ee/phy.o
  LD [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192de/rtl8192de.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192se/dm.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/rtl8822b/halhwimg8822b_rf.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/rtl8822b/phydm_hal_api8822b.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192se/fw.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192ee/pwrseq.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/rtl8822b/phydm_regconfig8822b.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/rtl8822b/phydm_rtl8822b.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192se/hw.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/rtl8723d/halhwimg8723d_bb.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192ee/rf.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/rtl8723d/halhwimg8723d_mac.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192se/led.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192ee/sw.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/rtl8723d/halhwimg8723d_rf.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192se/phy.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192se/rf.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192ee/table.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192ee/trx.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/rtl8723d/phydm_regconfig8723d.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192se/sw.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8723ae/dm.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/rtl8723d/phydm_rtl8723d.o
  LD [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192ee/rtl8192ee.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8723be/dm.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192se/table.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192se/trx.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8723ae/fw.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/halrf/rtl8723d/halrf_8723d.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8723be/fw.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8723ae/hal_btc.o
  LD [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8192se/rtl8192se.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8723com/main.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/rtl_phydm.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8723be/hw.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8723ae/hal_bt_coexist.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8723com/dm_common.o
  LD [M]  /var/lib/dkms/rtlwifi-new/0.6/build/phydm/phydm_mod.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8723de/fw.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8723ae/hw.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8723com/fw_common.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8723be/led.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8723de/hw.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8723com/phy_common.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8723be/phy.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8723ae/led.o
  LD [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8723com/rtl8723-common.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8821ae/dm.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8723ae/phy.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8723de/led.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8723be/pwrseq.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8821ae/fw.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8723de/phy.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8723ae/pwrseq.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8723be/rf.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8821ae/hw.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8723ae/rf.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8723be/sw.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8723de/pwrseq.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8723be/table.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8723ae/sw.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8723de/rf.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8723be/trx.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8821ae/led.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8723de/sw.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8723ae/table.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8723ae/trx.o
  LD [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8723be/rtl8723be.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8822be/fw.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8821ae/phy.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8723de/table.o
  LD [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8723ae/rtl8723ae.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8822be/hw.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8822be/led.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8723de/trx.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8822be/phy.o
  LD [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8723de/rtl8723de.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/base.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8822be/sw.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8821ae/pwrseq.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8822be/trx.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8821ae/rf.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/cam.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8821ae/sw.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8821ae/table.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8821ae/trx.o
  LD [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8822be/rtl8822be.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/core.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/debug.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/efuse.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/ps.o
  LD [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rtl8821ae/rtl8821ae.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rc.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/regd.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/stats.o
/var/lib/dkms/rtlwifi-new/0.6/build/rc.c:336:11: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .alloc = rtl_rate_alloc,
           ^~~~~~~~~~~~~~
/var/lib/dkms/rtlwifi-new/0.6/build/rc.c:336:11: note: (near initialization for ‘rtl_rate_ops.alloc’)
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/pci.o
cc1: some warnings being treated as errors
scripts/Makefile.build:288: recipe for target '/var/lib/dkms/rtlwifi-new/0.6/build/rc.o' failed
make[1]: *** [/var/lib/dkms/rtlwifi-new/0.6/build/rc.o] Error 1
make[1]: *** Waiting for unfinished jobs....
Makefile:1656: recipe for target '_module_/var/lib/dkms/rtlwifi-new/0.6/build' failed
make: *** [_module_/var/lib/dkms/rtlwifi-new/0.6/build] Error 2
make: Leaving directory '/usr/src/linux-headers-5.3.0-51-generic'

**Comment by TonyThuitai** [comment]
I have read similar issues and understand that a 'git pull' is needed for it to work but not 'git clone'. Your instructions have git clone but not git pull. Please update the instructions. You can delete the issue, I cannot delete it here

**Comment by lwfinger** [comment]
If you look at the source, you will see instructions on what to change.

**Comment by lwfinger** [comment]
By the way, git clone is used to obtain a new source for the FIRST time. After that, you use 'git pull' from within the directory containing that source to get any updates.

I do not plan to offer a git tutorial. There are many of these on-line already.

**Comment by TonyThuitai** [comment]
I reinstalled Linux Mint XFCE 19.3. Git cloned the extended branch. Git pull within directory but it says it is up to date. Changed the line in the rc.c file and it installs successfully and the driver works. Thanks @lwfinger. I understand that you have a hard time keeping up with distribution changes especially back-porting of kernel features in older kernels.

**Comment by lwfinger** [comment]
Yes, it is a problem made specially difficult by my friends  in the wireless developers group.

**Comment by lwfinger** [comment]
This issue is now properly fixed. See Issue #570 for explanation.

**Comment by TonyThuitai** [comment]
@lwfinger Thanks for the fix. If it were not for you I would have had replaced my Hp laptop's rtl8723de for an Intel one if it can work with one antenna
