### ISSUE TITLE
RTL8822BE unable to connect to WiFi networks Ubuntu 18.04 Kernel 5.3

### ISSUE THREAD

**Issue by ofir5551** [lwfinger/rtlwifi_new#564]
Hello.

I'm using Ubuntu 18.04 LTS and I've been struggling with a wifi-related issue for the past few months - ever since Ubuntu has started to use the 5.x kernel.

As of now, I'm running 5.3.0-51-generic that was automatically installed using apt-update/upgrade.

The problem is - I can find all wifi networks around me but cannot connect to any of them.
I tried running the following commands but with no success: 
```
git clone http://github.com/lwfinger/rtlwifi_new.git -b rtw88
cd rtlwifi_new
make
sudo make install
```

The thing is, sometimes when I mess around for a few hours it somehow starts working properly, but the next day it doesn't and I have no idea what is causing this issue / what is fixing it.

I'm using ASUS FX570UD Laptop, with Realtek RTL8822BE wireless card. 

I'm attaching the outputs of dmesg, lspci -vvvnn, lshw -C network and lsmod -- all after installing the repo.

I'm a pretty beginner linux user, and will gladly provide any additional necessary logs.

Thanks in advance and sorry for any English mistakes!

[dmesg not working.txt](https://github.com/lwfinger/rtlwifi_new/files/4570114/dmesg.not.working.txt)
[lspci not working.txt](https://github.com/lwfinger/rtlwifi_new/files/4570115/lspci.not.working.txt)
[lshw not working.txt](https://github.com/lwfinger/rtlwifi_new/files/4570116/lshw.not.working.txt)
[lsmod not working.txt](https://github.com/lwfinger/rtlwifi_new/files/4570118/lsmod.not.working.txt)

**Comment by ofir5551** [comment]
For your convenience, I've pasted the attached logs on pastebin so you won't have to download them :-)

dmesg - https://pastebin.com/Pxv8GbZ7
lspci -vvvnn - https://pastebin.com/0NxaYyQb
lshw - https://pastebin.com/U9SxYMcb
lsmod - https://pastebin.com/ub8uXffC

**Comment by lwfinger** [comment]
You are getting a WARNING dump from nouveau, but also this one from rtw88:

[Sun May  3 01:28:57 2020] purge skb(s) not reported by firmware
[Sun May  3 01:28:57 2020] WARNING: CPU: 5 PID: 0 at /home/ofir/rtlwifi_new/tx.c:163 rtw_tx_report_purge_timer+0x24/0x50 [rtw88]

This one should not be fatal.
You are getting
[Sun May  3 01:32:11 2020] wlp3s0: disassociated from 14:ae:db:3e:5c:bd (Reason: 2=PREV_AUTH_NOT_VALID)

I think you said that it worked before Ubuntu switched to a 5.3 kernel. Is that correct? What else changed at that time? Are you aware that this driver is built into kernel 5.3 and you do not need to use this repo. In fact that one likely has fixes not here. If you are willing to switch to 20.04 LTS, that will get you kernel 5.4, which is even better.

**Comment by ofir5551** [comment]
Thank you for the quick response.

Since the problem first started to randomly occur, I have tried to reinstall Ubuntu 18.04 a few times and the problem persisted even without changing any built in drivers. 

Everything worked fine while I was using an 4.X kernel but once Ubuntu switched to 5.X, the problem showed up from times to times and randomly fixed itself without my intervention (after messing around with things like rebooting a few times, turning off and on airplane mode etc.)

Nowadays, in 5.3, the problem is still occuring and is worse than ever, I can see all my networks but can't connect to any of them.

I will try installing a clean Ubuntu 20.04 as a last resort - but if you have any other ideas of what could be the problem I'd rather try that first.

Thanks again for your time

**Comment by lwfinger** [comment]
I have heard of other Ubuntu users having flaky problems that are cleared up with a new kernel, then reappear with an even newer one. I do not use Ubuntu, and never will. All I know is that I have never seen any of this type of problem with the 8822ce chips. I use openSUSE Tumbleweed with a rolling release, plus I am usually running a mainline tip kernel.

**Comment by ofir5551** [comment]
Hi again,

I have just turned on my laptop after not using it all day, and it miraculously works now, without me doing literally anything all day.

I'm attaching the same logs, maybe you can spot the difference between the ones I provided above (the ones when I wasn't able to connect to any wifi) to these ones (the ones I'll be attaching to this comment, while my wifi is working properly)

I have tried running 'diff' but don't know what is relevant to my issue and what is not.

Thanks again for the quick replies, and sorry for my ignorance in Linux, I'm still at the beginning of my journey

dmesg - https://pastebin.com/sE4R7GB5
lspci - https://pastebin.com/PU2B17HN
lshw - https://pastebin.com/Bde2GCKn
lsmod - https://pastebin.com/QhMRrK5C


[dmesg working.txt](https://github.com/lwfinger/rtlwifi_new/files/4572079/dmesg.working.txt)
[lspci working.txt](https://github.com/lwfinger/rtlwifi_new/files/4572080/lspci.working.txt)
[lshw working.txt](https://github.com/lwfinger/rtlwifi_new/files/4572081/lshw.working.txt)
[lsmod working.txt](https://github.com/lwfinger/rtlwifi_new/files/4572082/lsmod.working.txt)

**Comment by Marcelovk** [comment]
I have exactly the same issue. For me the last kernel that works (Under ubuntu) is 5.0.3. Anything newer than that causes the same exceptions in dmesg. I also tried a Fedora live image with 5.6 and had the same behavior

The difference is that I have a RTL8822CE in an Asus FX505DV.

**Comment by lwfinger** [comment]
What branch are you using?

**Comment by Marcelovk** [comment]
rtw88 branch, and the same behavior is found in the original kernel module.

**Comment by lwfinger** [comment]
The rtw88 branch is EXACTLY the same as the driver in the wireless-testing-next repo. This code will be in kernel 5.8

If you are having trouble other than building the driver, you need to present your problem and supporting evidence on the mailing list at linux-wireless@vger.kernel.org. The device developers read that list. They are the ones that know how the device is supposed to work.
