### ISSUE TITLE
Unable to build and install rtlwifi_new dkms module version r304.f19fee2 on Manjaro Linux for RTL8723DE wireless card

### ISSUE THREAD

**Issue by CryogenicNeo** [lwfinger/rtlwifi_new#566]
Hello @lwfinger and Community!

I'm trying to update the `rtlwifi_new` driver for a `RTL8723DE` wireless card on Manjaro using Linux kernel version `4.19-119-1-MANJARO` and `5.4.36-1-MANJARO`. The install process throws an build error that relies on file `rc.o`.

This is the command I executed:

    # dkms install rtlwifi_new/r304.f19fee2 -k 4.19.119-1-MANJARO                                                 

    Kernel preparation unnecessary for this kernel.  Skipping...

    Building module:
    cleaning build area....(bad exit status: 2)
    make -j4 KERNELRELEASE=4.19.119-1-MANJARO -C /usr/lib/modules/4.19.119-1-MANJARO/build M=/var/lib/dkms/rtlwifi_new/r304.f19fee2/build............................................(bad exit status: 2)
    Error! Bad return status for module build on kernel: 4.19.119-1-MANJARO (x86_64)
    Consult /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/make.log for more information.

The same error was thrown when build for linux kernel version `4.19-119-1-MANJARO` and `5.4.36-1-MANJARO`. 

This is `make.log` file:

    $ cat /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/make.log                                                    [10]
    DKMS make.log for rtlwifi_new-r304.f19fee2 for kernel 4.19.119-1-MANJARO (x86_64)
    dom 03 may 2020 13:26:31 -05
    make: se entra en el directorio '/usr/lib/modules/4.19.119-1-MANJARO/build'
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/btcoexist/halbtc8192e2ant.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/phydm_debug.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8188ee/dm.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/halmac/halmac_api.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/halmac/halmac_88xx/halmac_api_88xx_usb.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8188ee/fw.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/btcoexist/halbtc8723b1ant.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/halmac/halmac_88xx/halmac_api_88xx_sdio.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/phydm_antdiv.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8188ee/hw.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/phydm_soml.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/halmac/halmac_88xx/halmac_api_88xx.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/btcoexist/halbtc8723b2ant.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/phydm_smt_ant.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/phydm_interface.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8188ee/led.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/halmac/halmac_88xx/halmac_api_88xx_pcie.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8188ee/phy.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/btcoexist/halbtc8821a1ant.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/phydm_phystatus.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/halmac/halmac_88xx/halmac_func_88xx.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/phydm_hwconfig.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8188ee/pwrseq.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/btcoexist/halbtc8821a2ant.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/phydm.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8188ee/rf.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/halmac/halmac_88xx/halmac_8822b    /halmac_api_8822b_pcie.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/btcoexist/halbtc8822b1ant.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8188ee/sw.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/halmac/halmac_88xx/halmac_8822b/halmac_func_8822b.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/phydm_dig.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8188ee/table.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8188ee/trx.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/halmac/halmac_88xx/halmac_8822b/halmac_api_8822b_sdio.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/phydm_pathdiv.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/halmac/halmac_88xx/halmac_8822b/halmac_api_8822b.o
    LD [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8188ee/rtl8188ee.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/btcoexist/halbtc8822b2ant.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/btcoexist/halbtc8822bwifionly.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/phydm_rainfo.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/halmac/halmac_88xx/halmac_8822b/halmac_8822b_phy.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/phydm_dynamictxpower.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/halmac/halmac_88xx/halmac_8822b/halmac_8822b_pwr_seq.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/phydm_adaptivity.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/phydm_cfotracking.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/btcoexist/halbtc8723d1ant.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/halmac/halmac_88xx/halmac_8822b/halmac_api_8822b_usb.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/halmac/rtl_halmac.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/phydm_noisemonitor.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/phydm_dfs.o
    LD [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/halmac/halmac.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/btcoexist/halbtc8723d2ant.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192c/main.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/btcoexist/halbtcoutsrc.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/phydm_adc_sampling.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192c/dm_common.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/phydm_ccx.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/btcoexist/rtl_btc.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/phydm_psd.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192c/fw_common.o
    LD [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/btcoexist/btcoexist.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192c/phy_common.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/phydm_primary_cca.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/phydm_cck_pd.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/phydm_rssi_monitor.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/phydm_auto_dbg.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/phydm_math_lib.o
    LD [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192c/rtl8192c-common.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192ce/dm.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/phydm_api.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/phydm_pow_train.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192ce/hw.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192ce/led.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/halrf/halrf.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/halrf/halphyrf_ce.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192ce/phy.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/halrf/halrf_powertracking_ce.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/halrf/halrf_powertracking.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/halrf/halrf_kfree.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192ce/rf.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/halrf/rtl8822b/halrf_8822b.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/halrf/rtl8822b/halrf_iqk_8822b.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/rtl8822b/halhwimg8822b_bb.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192ce/sw.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/rtl8822b/halhwimg8822b_mac.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/rtl8822b/halhwimg8822b_rf.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/rtl8822b/phydm_hal_api8822b.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192ce/table.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192ce/trx.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/rtl8822b/phydm_regconfig8822b.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/rtl8822b/phydm_rtl8822b.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/rtl8723d/halhwimg8723d_bb.o
    LD [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192ce/rtl8192ce.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/rtl8723d/halhwimg8723d_mac.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192cu/dm.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/rtl8723d/halhwimg8723d_rf.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/rtl8723d/phydm_regconfig8723d.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192cu/hw.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/rtl8723d/phydm_rtl8723d.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/halrf/rtl8723d/halrf_8723d.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/rtl_phydm.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192cu/led.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192cu/mac.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192cu/phy.o
    LD [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/phydm/phydm_mod.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192cu/rf.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192cu/sw.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192de/dm.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192ee/dm.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192se/dm.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192cu/table.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192cu/trx.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192se/fw.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192de/fw.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192ee/fw.o
    LD [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192cu/rtl8192cu.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192de/hw.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192se/hw.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8723ae/dm.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192ee/hw.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8723ae/fw.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192de/led.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192se/led.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192ee/led.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192de/phy.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8723ae/hal_btc.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192se/phy.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192ee/phy.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8723ae/hal_bt_coexist.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192se/rf.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192de/rf.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8723ae/hw.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192se/sw.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192de/sw.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192ee/pwrseq.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192se/table.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192se/trx.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192de/table.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192de/trx.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192ee/rf.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8723ae/led.o
    LD [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192se/rtl8192se.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8723ae/phy.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192ee/sw.o
    LD [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192de/rtl8192de.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8723be/dm.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8723ae/pwrseq.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8723ae/rf.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192ee/table.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8723ae/sw.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8723be/fw.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192ee/trx.o
    LD [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8192ee/rtl8192ee.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8723ae/table.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8723com/main.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8723ae/trx.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8723com/dm_common.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8723be/hw.o
    LD [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8723ae/rtl8723ae.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8723com/fw_common.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8723de/fw.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8821ae/dm.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8723com/phy_common.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8723de/hw.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8821ae/fw.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8723be/led.o
    LD [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8723com/rtl8723-common.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8723be/phy.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8822be/fw.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8723de/led.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8821ae/hw.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8822be/hw.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8723de/phy.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8723be/pwrseq.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8821ae/led.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8723be/rf.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8822be/led.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8723de/pwrseq.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8821ae/phy.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8822be/phy.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8723be/sw.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8723de/rf.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8723de/sw.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8723be/table.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8822be/sw.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8723be/trx.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8723de/table.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8723de/trx.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8822be/trx.o
    LD [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8723be/rtl8723be.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/base.o
    LD [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8723de/rtl8723de.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/cam.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8821ae/pwrseq.o
    LD [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8822be/rtl8822be.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/core.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/debug.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8821ae/rf.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/efuse.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/ps.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8821ae/sw.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rc.o
    /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rc.c:336:11: error: inicialización de ‘void * (*)(struct ieee80211_hw *, struct dentry *)’ desde un tipo depuntero ‘void * (*)(struct ieee80211_hw *)’ incompatible [-Werror=incompatible-pointer-types]
    336 |  .alloc = rtl_rate_alloc,
    |           ^~~~~~~~~~~~~~
    /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rc.c:336:11: nota: (cerca de la inicialización de ‘rtl_rate_ops.alloc’)
    cc1: algunos avisos se tratan como errores
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/regd.o
    make[1]: *** [scripts/Makefile.build:303: /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rc.o] Error 1
    make[1]: *** Se espera a que terminen otras tareas....
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8821ae/table.o
    CC [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8821ae/trx.o
    LD [M]  /var/lib/dkms/rtlwifi_new/r304.f19fee2/build/rtl8821ae/rtl8821ae.o
    make: *** [Makefile:1522: _module_/var/lib/dkms/rtlwifi_new/r304.f19fee2/build] Error 2
    make: se sale del directorio '/usr/lib/modules/4.19.119-1-MANJARO/build'

I appreciate your work on this driver and your help to solve this issue.
I will gladly provide any additional logs if you need.
Thanks in advance!

Sorry for any English mistakes in this issue report.

---
# Temporary solution

The commit `302.68b91e8` in the repository for the` extended` branch was the last working version I installed on both kernels. So, to solve this problem, I had to get back again to that version.

**Comment by lwfinger** [comment]
A fix for a substantial bug in mac80211 was pushed to the kernel about 10 days ago and backported to all stable kernels. Accordingly, I pushed a fix to account for that issue with commit f19fee2633819ee2. If your kernel is not one that was patched for the original bug, rc.c has comments that tell you exactly what you need to do. The error message is not enough to tell me which condition you have. The majority of people need the change. If you do not, you will be the first person not to need the change.

Alternatively, you should check out commit 68b91e8d313ef8 until such time as you get an updated kernel and need the change in calling sequence.

**Comment by lwfinger** [comment]
This issue is now properly fixed. See Issue #570 for explanation.

**Comment by CryogenicNeo** [comment]
Thank you!
