### ISSUE TITLE
make fails on arch linux kernal 5.6.8-arch1-1

### ISSUE THREAD

**Issue by prkprime** [lwfinger/rtlwifi_new#567]
wifi drivers returns the error on arch linux kernal 5.6.8-arch1-1

`Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...(bad exit status: 2)
make -j8 KERNELRELEASE=5.6.8-arch1-1 -C /usr/lib/modules/5.6.8-arch1-1/build M=/var/lib/dkms/rtlwifi-new/0.6/build................(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.6.8-arch1-1 (x86_64)
Consult /var/lib/dkms/rtlwifi-new/0.6/build/make.log for more information.`

I'm attaching the make.log file
[make.log](https://github.com/lwfinger/rtlwifi_new/files/4572905/make.log)

**Comment by warriormaster12** [comment]
I had the same issue. Rebooted and it disappeared but once I reinstalled the drivers, it can't for some reason see our dual-bandwidth wi-fi. I have to use my hotspot.

**Comment by lwfinger** [comment]
This issue is now properly fixed. See Issue #570 for explanation.
