### ISSUE TITLE
rtl8723de make install errors in HP 15-da0077TX with Ubuntu18.04 LTS 

### ISSUE THREAD

**Issue by AmartyaCSB** [lwfinger/rtlwifi_new#568]
I am getting the following errors on make install.
Kernel: 5.3.0-51-generic
Everything has been same since quite few weeks

make -C /lib/modules/5.3.0-51-generic/build M=/home/amartya/rtlwifi_new modules
make[1]: Entering directory '/usr/src/linux-headers-5.3.0-51-generic'
  CC [M]  /home/amartya/rtlwifi_new/rc.o
/home/amartya/rtlwifi_new/rc.c:289:11: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .alloc = rtl_rate_alloc,
           ^~~~~~~~~~~~~~
/home/amartya/rtlwifi_new/rc.c:289:11: note: (near initialization for ‘rtl_rate_ops.alloc’)
cc1: some warnings being treated as errors
scripts/Makefile.build:288: recipe for target '/home/amartya/rtlwifi_new/rc.o' failed
make[2]: *** [/home/amartya/rtlwifi_new/rc.o] Error 1
Makefile:1656: recipe for target '_module_/home/amartya/rtlwifi_new' failed
make[1]: *** [_module_/home/amartya/rtlwifi_new] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.3.0-51-generic'
Makefile:58: recipe for target 'all' failed
make: *** [all] Error 2

How do I get away with the incompatible pointer type error. Is there a problem with the Linux kernel? Should I downgrade it?

**Comment by lwfinger** [comment]
Did you do a 'git pull'? If so, then your kernel is not under stable maintenance, and you will need to 'git checkout 68b91e8d313e.

**Comment by lwfinger** [comment]
This issue is now properly fixed. See Issue #570 for explanation.

**Comment by AmartyaCSB** [comment]
Yes. Figured out the solution by checking out the commit you mentioned earlier. 
Thanks for this again

**Comment by lwfinger** [comment]
Note, the checkout an earlier version is now obsolete. If you 'git checkout extended' and 'git pull', it should still work. If not, please let me know.
