### ISSUE TITLE
rtlwifi_new/rc.c:336:11: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]   .alloc = rtl_rate_alloc

### ISSUE THREAD

**Issue by satya-p14** [lwfinger/rtlwifi_new#569]
~/rtlwifi_new$ sudo make install
make -C /lib/modules/4.15.0-99-generic/build M=/home/-/-/rtlwifi_new modules
make[1]: Entering directory '/usr/src/linux-headers-4.15.0-99-generic'
  CC [M]  /home/-/-/rtlwifi_new/base.o
  CC [M]  /home/-/-/rtlwifi_new/cam.o
  CC [M]  /home/-/-/rtlwifi_new/core.o
  CC [M]  /home/-/-/rtlwifi_new/debug.o
  CC [M]  /home/-/-/rtlwifi_new/efuse.o
  CC [M]  /home/-/-/rtlwifi_new/ps.o
  CC [M]  /home/-/-/rtlwifi_new/rc.o
/home/-/-/rtlwifi_new/rc.c:336:11: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .alloc = rtl_rate_alloc,
           ^~~~~~~~~~~~~~
/home/-/-/rtlwifi_new/rc.c:336:11: note: (near initialization for ‘rtl_rate_ops.alloc’)
cc1: some warnings being treated as errors
scripts/Makefile.build:330: recipe for target '/home/-/-/rtlwifi_new/rc.o' failed
make[2]: *** [/home/-/-/rtlwifi_new/rc.o] Error 1
Makefile:1577: recipe for target '_module_/home/-/-/rtlwifi_new' failed
make[1]: *** [_module_/home/-/-/rtlwifi_new] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-99-generic'
Makefile:85: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lwfinger** [comment]
Did you do a git pull? If not, then do so. If you did the pull, then you need to 'git checkout 68b91e8d313e'.

**Comment by lwfinger** [comment]
This issue is now properly fixed. See Issue #570 for explanation.
