### ISSUE TITLE
RTL8723BE Bluetooth: failed to load rtl8723b_config (-2) This is not 8723a, use new patch style!  Fw: exists, config file:not exists

### ISSUE THREAD

**Issue by maferv** [lwfinger/rtlwifi_new#57]
Hello guys. 

I installed your wifi drivers and they worked perfectly! Thank you for sharing them. 

To get bluetooth working I installed the firmware from this repository [1] and I got a fine working bluetooth device. But annoyingly, every time I boot, systemd displays:

[   10.275239] rtk_btusb: btusb_open hdev->promisc ==0
[   10.277451] rtk_btusb: lmp_version = 0x8723
[   10.294770] usb 1-2.1: firmware: failed to load rtl8723b_config (-2) 
[   10.312043] rtk_btusb: This is not 8723a, use new patch style! 
[   10.313620] rtk_btusb: Fw: exists, config file:not exists

full dmesg lines referring to bluetooth: http://pastebin.com/ngwHuNrb
lsusb -vvv: http://pastebin.com/NqTYxESE
lspci -vvv: http://pastebin.com/SB9SbnVq

What is going on? Should I worry? What should I do to fix this? FWIW I'm using Debian stable (3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux). I came here to report this issue because troy-tan warns not to post any issues in that repository.

Thank you very much in advance!

[1] https://github.com/troy-tan/driver_store/tree/master/bluetooth/8723BE

**Comment by lwfinger** [comment]
You need to clone the repo at http://gitbub.com/lwfinger/rtl8723a_bt.git, checkout the kernel branch, then run "make" and "sudo make install". Despite the name of the repo, that will get you the correct driver and firmware.

**Comment by maferv** [comment]
I can't access that repository. What am I doing wrong?

$  git clone http://gitbub.com/lwfinger/rtl8723a_bt.git
Cloning into 'rtl8723a_bt'...
fatal: http://gitbub.com/lwfinger/rtl8723a_bt.git/info/refs not valid: is this a git repository?

Maybe you misspelled it? is it https://github.com/lwfinger/rtl8723au.git?

**Comment by lwfinger** [comment]
Yes, it is GitHub.com.

**Comment by Ayysir** [comment]
https://github.com/lwfinger/rtl8723au_bt you mean @lwfinger ? this is compatible with RTL8723BE?

**Comment by lwfinger** [comment]
Yes. If you examine that repo, you will see it has code for *ALL* Realtek USB BT devices, except for the RTL8723BS, which is a serial device.

**Comment by Ayysir** [comment]
ahh @lwfinger  just make and make install and let it run? using archlinux distro

**Comment by maferv** [comment]
I uninstalled the previous firmware/modules and installed the ones from https://github.com/lwfinger/rtl8723au_bt. I get a device with hcitool dev but it doesn't work, i.e.: It doesn't find any devices and it isn't found by any other devices. What should I do? Are you sure it should work perfectly? When I used https://github.com/troy-tan/driver_store/tree/master/bluetooth/8723BE bluetooth was working just fine (as far as I could see) but every time I booted I got that warning message.

**Comment by lwfinger** [comment]
Obviously, you should use whatever works. All of these various code sources are temporary anyway. Once we get to kernel 4.2, the driver for these Realtek devices will be part of the kernel.

**Comment by maferv** [comment]
Then I'll stick to the one that is working but with unexpected warning messages. I hope the troy-tan is the version that is going to be included in Linux 4.2. I'll be looking forward to it. Thank you for your explanations. Great job!

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
