### ISSUE TITLE
rtl8273 signal strength low at ant_sel=1 and connect to any network on ant_sel=2

### ISSUE THREAD

**Issue by rishit-singh** [lwfinger/rtlwifi_new#571]
I first set ant_sel=2, got a signal strength of -27, but when I tried to connect to a network, it kept on prompting me for the password repeatedly, due to` lo1: authentication with 62:4d:7f:82:92:41 timed out` error that I found in the `dmesg` output, and the status was set to busy. Setting ant_sel=1 fixed the error, but the signal strength was dropped down to -79, and after some time the connection was failed.

**Comment by lwfinger** [comment]
If authentication worked with ant_sel=1, then the same passphrase will work with ant_sel=2.
