### ISSUE TITLE
The wifi speed is low

### ISSUE THREAD

**Issue by yash3001** [lwfinger/rtlwifi_new#572]
Low wifi speed when I installed your drivers. 
Also, if the speed remains slow, how do i uninstall it?

**Comment by lwfinger** [comment]
You did it wrong! Am I supposed to guess what kind of device you have? What kernel are you using? Why are you wasting my time?

**Comment by yash3001** [comment]
> You did it wrong! Am I supposed to guess what kind of device you have? What kernel are you using? Why are you wasting my time?

Nice reply, thanks you helped a lot
