### ISSUE TITLE
Bulding on Android-x86 Kernel 4.19.

### ISSUE THREAD

**Issue by hmtheboy154** [lwfinger/rtlwifi_new#573]
Hello, I'm trying to build this module with Kernel 4.19 by attaching it with kati build in nougat source. I use this source back when the latest commit was e3260995279100d7ec9addc407922ce895a93cea and it can compile just fine not only in Kernel 4.19 but also others kernel.
But then some compile error happen and I have to merge the latest commit. Although it was fixed but then I got this.
```
/media/Work/nougat-x86/out/target/product/x86_64/obj/kmodule/rtlwifi/rc.c:336:11: error: initialization of ‘void * (*)(struct ieee80211_hw *, struct dentry *)’ from incompatible pointer type ‘void * (*)(struct ieee80211_hw *)’ [-Werror=incompatible-pointer-types]
  336 |  .alloc = rtl_rate_alloc,
      |           ^~~~~~~~~~~~~~
/media/Work/nougat-x86/out/target/product/x86_64/obj/kmodule/rtlwifi/rc.c:336:11: note: (near initialization for ‘rtl_rate_ops.alloc’)
cc1: some warnings being treated as errors
```
It's that because of my kernel source or my compiler ? Hope you can help me with this 
(I'm using Fedora 32 and my toolchain is gcc version 10.0.1 20200430 (Red Hat 10.0.1-0.13) )

**Comment by lwfinger** [comment]
Please run the following command in terminal and report the output:
echo $(grep alloc /lib/modules/`uname -r`/build/include/net/mac80211.h | grep void)

**Comment by hmtheboy154** [comment]
Here it is : 
```net]$ echo $(grep alloc mac80211.h | grep void)
void *(*alloc)(struct ieee80211_hw *hw, struct dentry *debugfsdir); void *(*alloc_sta)(void *priv, struct ieee80211_sta *sta, gfp_t gfp);
```
But I get it from the kernel source, not in /lib/modules since I'm building for Android-x86.

**Comment by lwfinger** [comment]
Yes, the Makefile is oriented toward building drivers for the running kernel.

How do you specify a kernel tree in your build process?
What command did you issue to get the output in your reply?

**Comment by hmtheboy154** [comment]
Hello again. So I haven't read much in kati build process in Android 7.1 source, but what I saw when I type make kernel -j4 into the source it will create a build-android_x86_64.ninja file and inside there I saw the kernel modules building rules 
![image](https://user-images.githubusercontent.com/39849246/81366070-582f0180-90d9-11ea-9ef4-5b4d4c7eee9f.png)
the full command it made is 
``` 
command = /bin/bash -c "(rm -rf out/target/product/x86_64/system/lib/modules ) && (make -j2 -C kernel O=/media/Work/nougat-x86/out/target/product/x86_64/obj/kernel ARCH=x86_64 CROSS_COMPILE=\" \"  INSTALL_MOD_PATH=/media/Work/nougat-x86/out/target/product/x86_64/system modules_install ) && (for kmod in tp_smapi rtlwifi wl rtl8821ce rtl8188eus rtl8812au ; do 		echo Installing additional kernel module \$${kmod} ; 		 make -j2 -C kernel O=/media/Work/nougat-x86/out/target/product/x86_64/obj/kernel ARCH=x86_64 CROSS_COMPILE=\" \"  INSTALL_MOD_PATH=/media/Work/nougat-x86/out/target/product/x86_64/system M=/media/Work/nougat-x86/out/target/product/x86_64/obj/kmodule/\$${kmod} modules_install ; 	done ) && (rm -f out/target/product/x86_64/system/lib/modules/*/{build,source} )"
build out/target/product/x86_64/system/lib/modules/4.19.120-android-x86_64/modules.dep: rule61005 /media/Work/nougat-x86/out/target/product/x86_64/obj/kernel/arch/x86_64/boot/bzImage out/target/product/x86_64/obj/kmodule/tp_smapi out/target/product/x86_64/obj/kmodule/rtlwifi out/target/product/x86_64/obj/kmodule/wl out/target/product/x86_64/obj/kmodule/rtl8821ce out/target/product/x86_64/obj/kmodule/rtl8188eus out/target/product/x86_64/obj/kmodule/rtl8812au
rule rule61006
```
Some addition, here is what I did to build the module
here is my Android source folder 
![image](https://user-images.githubusercontent.com/39849246/81366275-c673c400-90d9-11ea-83b1-53d598925099.png)

And here is the kernel module source location
![image](https://user-images.githubusercontent.com/39849246/81366350-ee632780-90d9-11ea-9340-cfe60d6332ef.png)

I have to create an Android.mk file so the Android build will recognise the module folder
![image](https://user-images.githubusercontent.com/39849246/81366467-4568fc80-90da-11ea-96bb-e4493d7a0b53.png)

And have to add to TARGET_EXTRA_KERNEL_MODULES in BoardConfig.mk 
![image](https://user-images.githubusercontent.com/39849246/81366574-86611100-90da-11ea-8ac7-2f75305372d8.png)

and then type make kernel -j4 for to build kernel bzImage and modules

the last command you gave me, I type it like this
```
echo $(grep alloc kernel/include/net/mac80211.h | grep void)
```
![image](https://user-images.githubusercontent.com/39849246/81367258-3be09400-90dc-11ea-8b46-a287f03fc9d2.png)

**Comment by hmtheboy154** [comment]
If you ask about the kernel source : https://git.osdn.net/view?p=android-x86/kernel.git;a=tree;h=refs/heads/kernel-4.19;hb=refs/heads/kernel-4.19

I use Google kernel source to upstream it https://android.googlesource.com/kernel/common/+/refs/heads/android-4.19

**Comment by lwfinger** [comment]
I don't want to spend too much time on this. I do not see where the kernel source tree gets to the make file. To make it work for you, just delete the following line from my Makefile:
ccflags-y += -DRTL_RATE_ALLOC_1_ARG

**Comment by hmtheboy154** [comment]
It worked, thanks a lot :D
