### ISSUE TITLE
rtl8723de upstream

### ISSUE THREAD

**Issue by burdi01** [lwfinger/rtlwifi_new#574]
From the rtlwifi_new readme:
```
Note: If your kernel is 4.17 or newer, AND your card is not an RTL8723DE, then you should NOT be using the external driver. The built-in one is the same.
It includes the following drivers:
rtl8192ce, rtl8192cu, rtl8192se, rtl8192de, rtl8188ee, rtl8192ee, rtl8723ae, rtl8723be, rtl8821ae, and rtl8723de. The rtl8723de is available ONLY in the extended branch, which is the recommended one.
```
From issue #564:
`Are you aware that this driver *) is built into kernel 5.3 and you do not need to use this repo. In fact that one likely has fixes not here.`
*) Actually the rtl8822be driver is not in the above list, but the gist is the same.

I build distribution-like kernels -- to be used on (hopefully) all hardware out there. So all of the drivers in the above list (including the rtl8723de one) should be provided. However the rtlwifi_new-extended makefile only supports a "make all". In effect this will overwrite the kernel's built-in drivers.
Am I correct in assuming the above drivers to use some common code the version of which in the kernel may drift apart from the one that the rtl8723de driver expects?

Also do you have any idea on when or if the rtl8723de code will be upstreamed and who will initiate this?

Kind regards, Dick

**Comment by lwfinger** [comment]
To limit the drivers being built is a simple change to Makefile. I decided a long time ago that a Kconfig frontend would confusing. See the backports project to see what I mean.

Realtek has written the rtl8723de driver for mainline. It has just been merged as part of rtw88 in wireless_drivers_next, which means it will be in kernel 5.8, and in the backports project. Kernel 5.7 will be released in about a month, which means 5.8.0-rc1 is about 6 weeks away.

**Comment by TonyThuitai** [comment]
The only distribution that I know of that comes with the RTL8723DE out of the box at this time is Ubuntu 20.04 and can be tested when trying Ubuntu or any Ubuntu flavour live. I have tested it and it works flawlessly. I think it is build in the 5.4 kernel because the driver is not shown in Ubuntu's Driver Manager.

**Comment by burdi01** [comment]
**@TonyThuitai**: My testing indicates otherwise:
```
root@riposo:~/works# uname -a
Linux riposo 5.4.0-29-generic #33-Ubuntu SMP Wed Apr 29 14:32:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
root@riposo:~/works# modprobe rtl8723be
root@riposo:~/works# modprobe rtl8723de
modprobe: FATAL: Module rtl8723de not found in directory /lib/modules/5.4.0-29-generic
root@riposo:~/works# grep rtl8723'/lib/modules/5.4.0-29-generic/modules.alias' 
alias pci:v000010ECd00008723sv*sd*bc*sc*i* rtl8723ae
alias pci:v000010ECd0000B723sv*sd*bc*sc*i* rtl8723be
root@riposo:~/works# grep rtl8723 '/lib/modules/5.4.0-29-generic/modules.builtin' 
root@riposo:~/works# exit

```

**Comment by lwfinger** [comment]
It is NOT built into ANY kernel from any distro. There may be a dkms package provided that downloads the git source and builds it whenever the kernel changes.

**Comment by TonyThuitai** [comment]
@burdi01 Your testing is correct. @lwfinger The WiFi module can be used when downloading updates while installing Ubuntu 20.04. The packages dkms and build-essential are not installed. How did Ubuntu include the rtl8723de if the required packages for building and installing a git source driver are not installed.

**Comment by lwfinger** [comment]
Ask them.
