### ISSUE TITLE
Yet again with that pesky incompatible pointer type issue.

### ISSUE THREAD

**Issue by orotvold** [lwfinger/rtlwifi_new#575]
On debian/bullseye i get:

$ make
grep: /lib/modules/5.6.0-1-amd64/build/include/net/mac80211.h: No such file or directory
...

There is no such file on my system but there is a:

/usr/src/linux-headers-5.6.0-1-common/include/net/mac80211.h 

so a cheeky workaround with a symlink got it trough the build and it's now working here.

Not sure if this is a bug in debian or rtlwifi, but since the compiler finds that file a fix might be to use CC -E on a source file including that file and greping the output of that.

**Comment by lwfinger** [comment]
For the build to work, the headers should be in the subdirectory of /lib/modules as output by 'uname -r'. Once you do that, then my script works, and no link should be needed. I'm not sure when your setup will break, but I predict it will, and the modules you make will not load.
