### ISSUE TITLE
Error while installing RTL8723DE

### ISSUE THREAD

**Issue by AlbinDavis** [lwfinger/rtlwifi_new#579]
rtlwifi_new/rc.c:336:11: error: initialization of ‘void * (*)(struct ieee80211_hw *, struct dentry *)’ from incompatible pointer type ‘void * (*)(struct ieee80211_hw *)’ [-Werror=incompatible-pointer-types]
  336 |  .alloc = rtl_rate_alloc,
      |           ^~~~~~~~~~~~~~
/home/lbndvs/rtlwifi_new/rc.c:336:11: note: (near initialization for ‘rtl_rate_ops.alloc’)
cc1: some warnings being treated as errors
make[3]: *** [/usr/src/linux-headers-5.5.0-kali2-common/scripts/Makefile.build:271: /home/lbndvs/rtlwifi_new/rc.o] Error 1
make[2]: *** [/usr/src/linux-headers-5.5.0-kali2-common/Makefile:1707: /home/lbndvs/rtlwifi_new] Error 2
make[1]: *** [/usr/src/linux-headers-5.5.0-kali2-common/Makefile:179: sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.5.0-kali2-amd64'
make: *** [Makefile:89: all] Error 2

**Comment by r3pek** [comment]
update you source code to the latest version. if you cloned using git just make a git pull

**Comment by lwfinger** [comment]
NEVER EVER make a complaint about something not building until you have done a 'git pull'. If you have not used git, then please join the 21st century and abandon that awful zip method of obtaining sources from GitHub.

**Comment by AlbinDavis** [comment]
> update you source code to the latest version. if you cloned using git just make a git pull

thank you
