### ISSUE TITLE
Installed fine, but no wi-fi working

### ISSUE THREAD

**Issue by GustavoAle** [lwfinger/rtlwifi_new#581]
I'm trying to make one Rtl8188 Wi-Fi Dongle to work on Xubuntu. I built the repository as described in README, installed and manage to run modprobe without any errors but the wifi still not working, also iwconfig shows no device.

I tried everything and now I'm kind upset with this wifi adapter. :(

**Comment by lwfinger** [comment]
RTL8188 is not a sufficient description. This repo handles the RTL8188EE, but none of the other devices.

Is yours a PCI device, or is it USB? If the former, please post the appropriate line of the output of 'lspci -nn'. If USB, then the output of lsusb.

**Comment by GustavoAle** [comment]
The adapter I have is kind a mystery box, in the original package there's no information about brand and chip model. I presumed that the chip is RTL8188EE because is the name of the driver that came along with the adapter CD. 
I tried both RTL8188EE and RTL8192EE drivers with no luck.

lsusb output:
```
csm@csm-1:~$ lsusb
Bus 001 Device 004: ID 0bda:f179 Realtek Semiconductor Corp. 802.11n
Bus 001 Device 003: ID 058f:6362 Alcor Micro Corp. Flash Card Reader/Writer
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 005 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 004 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 003 Device 002: ID 1d57:0008 Xenta 2.4G Wireless Optical Mouse
Bus 003 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub

```

**Comment by lwfinger** [comment]
The last letter of the device name is for the bus type: E for PCI, U for USB, and S for SDIO. Those drivers you mentioned could never handle a USB card.

That ID is for an RTL8188FU. I have never seen one of these; however, there are at least 2 GitHub repos for a driver.

https://github.com/ulli-kroll/rtl8188fu
https://github.com/kelebek333/rtl8188fu

Good luck. I have no part in any of these devices.

**Comment by GustavoAle** [comment]
Thanks for your support, 
with the kelebek333 repository finally I was able to make the wifi adapter works. :)
