### ISSUE TITLE
Need help regarding rtlwifi_new please help me

### ISSUE THREAD

**Issue by Suraj9769** [lwfinger/rtlwifi_new#582]
/root/rtlwifi_new/rc.c:336:11: error: initialization of ‘void * (*)(struct ieee80211_hw *, struct dentry *)’ from incompatible pointer type ‘void * (*)(struct ieee80211_hw *)’ [-Werror=incompatible-pointer-types]
  336 |  .alloc = rtl_rate_alloc,
      |           ^~~~~~~~~~~~~~
/root/rtlwifi_new/rc.c:336:11: note: (near initialization for ‘rtl_rate_ops.alloc’)
cc1: some warnings being treated as errors
make[3]: *** [/usr/src/linux-headers-5.5.0-kali2-common/scripts/Makefile.build:271: /root/rtlwifi_new/rc.o] Error 1
make[2]: *** [/usr/src/linux-headers-5.5.0-kali2-common/Makefile:1707: /root/rtlwifi_new] Error 2
make[1]: *** [/usr/src/linux-headers-5.5.0-kali2-common/Makefile:179: sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.5.0-kali2-amd64'
make: *** [Makefile:88: all] Error 2

**Comment by lwfinger** [comment]
You should NOT be using rtlwifi_new branches master or extended. If you are using any device other than RTL8723DE, then the native driver in your 5.5 kernel should be used. If you have an RTL8723DE, then you need branch rtw88.

In 2 weeks all branches other than rtw88 will be deleted.

**Comment by Suraj9769** [comment]
Hey, thanks for the reply. The wifi issue is solved now but the problem is
whenever I try to run command related to wlan0, my computer freezes and I
have to hard start my pc. Can you help me?

**Comment by lwfinger** [comment]
I do need more information. What wifi card do you have? What driver are you using? Please check the output of dmesg BEFORE it freezes. Is anything logged when it hangs?
