### ISSUE TITLE
error when compile rtw88 with Kernel 4.19

### ISSUE THREAD

**Issue by hmtheboy154** [lwfinger/rtlwifi_new#583]
Hello, I'm having this error when compile rtw88 with Manjaro running Kernel 4.19 : 
 

> [hmtheboy154@hm-virtualbox rtw88]$ make
make -C /lib/modules/4.19.121-1-MANJARO/build M=/home/hmtheboy154/rtw88 modules
make[1]: Entering directory '/usr/lib/modules/4.19.121-1-MANJARO/build'
  CC [M]  /home/hmtheboy154/rtw88/mac80211.o
/home/hmtheboy154/rtw88/mac80211.c: In function ‘rtw_ops_ampdu_action’:
/home/hmtheboy154/rtw88/mac80211.c:589:10: error: ‘IEEE80211_AMPDU_TX_START_IMMEDIATE’ undeclared (first use in this function); did you mean ‘IEEE80211_AMPDU_TX_START’?
  589 |   return IEEE80211_AMPDU_TX_START_IMMEDIATE;
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |          IEEE80211_AMPDU_TX_START
/home/hmtheboy154/rtw88/mac80211.c:589:10: note: each undeclared identifier is reported only once for each function it appears in
/home/hmtheboy154/rtw88/mac80211.c: At top level:
/home/hmtheboy154/rtw88/mac80211.c:855:3: error: ‘const struct ieee80211_ops’ has no member named ‘can_aggregate_in_amsdu’
  855 |  .can_aggregate_in_amsdu = rtw_ops_can_aggregate_in_amsdu,
      |   ^~~~~~~~~~~~~~~~~~~~~~
/home/hmtheboy154/rtw88/mac80211.c:855:28: error: initialization of ‘int (*)(struct ieee80211_hw *, int,  struct survey_info *)’ from incompatible pointer type ‘bool (*)(struct ieee80211_hw *, struct sk_buff *, struct sk_buff *)’ {aka ‘_Bool (*)(struct ieee80211_hw *, struct sk_buff *, struct sk_buff *)’} [-Werror=incompatible-pointer-types]
  855 |  .can_aggregate_in_amsdu = rtw_ops_can_aggregate_in_amsdu,
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/hmtheboy154/rtw88/mac80211.c:855:28: note: (near initialization for ‘rtw_ops.get_survey’)
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:304: /home/hmtheboy154/rtw88/mac80211.o] Error 1
make[1]: *** [Makefile:1522: _module_/home/hmtheboy154/rtw88] Error 2
make[1]: Leaving directory '/usr/lib/modules/4.19.121-1-MANJARO/build'
make: *** [Makefile:72: all] Error 2

![Screenshot_2020-05-19_11-36-41](https://user-images.githubusercontent.com/39849246/82285278-48f76000-99c5-11ea-842d-f96cd6410c88.png)

(to avoid confusion like last time, I decided to compile modules in a VM first then compile in Android-x86 source later)

**Comment by lwfinger** [comment]
I fixed the two missing routines that you report. The fix for the first ("IEEE80211_AMPDU_TX_START_IMMEDIATE") should not cause any problems with the driver.

The fix for the missing callback can_aggregate_in_amsdu effectively turns off packet aggregation, thus the performance will probably be hurt.

Do a 'git pull' and try again. There may be other errors.

**Comment by yoann-dev** [comment]
Hi @lwfinger,
 
There are few errors :
```
make -C /lib/modules/4.19.0-9-amd64/build M=/home/yoann/Dev/rtlwifi_new modules
make[1] : on entre dans le répertoire « /usr/src/linux-headers-4.19.0-9-amd64 »
  CC [M]  /home/yoann/Dev/rtlwifi_new/main.o
  CC [M]  /home/yoann/Dev/rtlwifi_new/mac80211.o
  CC [M]  /home/yoann/Dev/rtlwifi_new/util.o
  CC [M]  /home/yoann/Dev/rtlwifi_new/debug.o
  CC [M]  /home/yoann/Dev/rtlwifi_new/tx.o
  CC [M]  /home/yoann/Dev/rtlwifi_new/rx.o
  CC [M]  /home/yoann/Dev/rtlwifi_new/mac.o
  CC [M]  /home/yoann/Dev/rtlwifi_new/phy.o
  CC [M]  /home/yoann/Dev/rtlwifi_new/coex.o
  CC [M]  /home/yoann/Dev/rtlwifi_new/efuse.o
  CC [M]  /home/yoann/Dev/rtlwifi_new/fw.o
  CC [M]  /home/yoann/Dev/rtlwifi_new/ps.o
  CC [M]  /home/yoann/Dev/rtlwifi_new/sec.o
  CC [M]  /home/yoann/Dev/rtlwifi_new/wow.o
  CC [M]  /home/yoann/Dev/rtlwifi_new/bf.o
  CC [M]  /home/yoann/Dev/rtlwifi_new/regd.o
  LD [M]  /home/yoann/Dev/rtlwifi_new/rtw_core.o
  CC [M]  /home/yoann/Dev/rtlwifi_new/rtw8822b.o
In file included from /usr/src/linux-headers-4.19.0-9-common/include/linux/list.h:9,
                 from /usr/src/linux-headers-4.19.0-9-common/include/linux/module.h:9,
                 from /home/yoann/Dev/rtlwifi_new/rtw8822b.c:5:
/usr/src/linux-headers-4.19.0-9-common/include/linux/kernel.h:72:25: error: expected declaration specifiers or ‘...’ before ‘(’ token
 #define ARRAY_SIZE(arr) (sizeof(arr) / sizeof((arr)[0]) + __must_be_array(arr))
                         ^
/home/yoann/Dev/rtlwifi_new/rtw8822b.c:2278:15: note: in expansion of macro ‘ARRAY_SIZE’
 static_assert(ARRAY_SIZE(rf_para_tx_8822b) == ARRAY_SIZE(rf_para_rx_8822b));
               ^~~~~~~~~~
make[4]: *** [/usr/src/linux-headers-4.19.0-9-common/scripts/Makefile.build:309: /home/yoann/Dev/rtlwifi_new/rtw8822b.o] Error 1
make[3]: *** [/usr/src/linux-headers-4.19.0-9-common/Makefile:1537: _module_/home/yoann/Dev/rtlwifi_new] Error 2
make[2]: *** [Makefile:146: sub-make] Error 2
make[1]: *** [Makefile:8: all] Error 2
make[1] : on quitte le répertoire « /usr/src/linux-headers-4.19.0-9-amd64 »
make: *** [Makefile:72: all] Error 2
```

**Comment by lwfinger** [comment]
I think I fixed the ARRAY_SIZE problem. Do a pull and try again.

**Comment by yoann-dev** [comment]
Exactly the same error, after pull, clean and make : 

```
In file included from /usr/src/linux-headers-4.19.0-9-common/include/linux/list.h:9,
                 from /usr/src/linux-headers-4.19.0-9-common/include/linux/module.h:9,
                 from /home/yoann/Dev/rtlwifi_new/rtw8822b.c:5:
/usr/src/linux-headers-4.19.0-9-common/include/linux/kernel.h:72:25: error: expected declaration specifiers or ‘...’ before ‘(’ token
 #define ARRAY_SIZE(arr) (sizeof(arr) / sizeof((arr)[0]) + __must_be_array(arr))
                         ^
/home/yoann/Dev/rtlwifi_new/rtw8822b.c:2278:15: note: in expansion of macro ‘ARRAY_SIZE’
 static_assert(ARRAY_SIZE(rf_para_tx_8822b) == ARRAY_SIZE(rf_para_rx_8822b));
```

**Comment by lwfinger** [comment]
I misinterpreted the error. Try again.

**Comment by yoann-dev** [comment]
The file `rtw8822c.c` needs the same fix than you did for `rtw8822b.c` for the ARRAY_SIZE.

And then build continues without errors !

Thanks Larry for your work

**Comment by lwfinger** [comment]
Thanks for the feedback. I pushed that change.

**Comment by yoann-dev** [comment]
You're welcome !

Build succeeded with the last commit.

**Comment by hmtheboy154** [comment]
![Screenshot_2020-05-20_09-06-18](https://user-images.githubusercontent.com/39849246/82396874-3fc7cb00-9a79-11ea-86fc-a0487cbb52ca.png)

Sucessfully built this morning, thanks for helping us :D
