### ISSUE TITLE
RTL8822BE halmac_init_hal failed.

### ISSUE THREAD

**Issue by thematdev** [lwfinger/rtlwifi_new#584]
OS: Arch Linux
Kernel: 5.6.13-arch1-1

I can't connect to wireless networks, because of error in adapter initialization.

dmesg prompt: https://pastebin.com/8w2QbiLr
lspci prompt: https://pastebin.com/Ne6bcrev
Then it keeps spamming `halmac_init_hal failed`.
So i have tried to make from branches `extended` and `rtw88` and `master`, but it didn't helped.
Also i have tried to put `aspm=0` in `/etc/modprobe.d/rtl8822be.conf`.

Any suggestions?

**Comment by lwfinger** [comment]
In each of these cases, you need to show exactly what driver was actually loaded using the command 'lsmod | grep 88'. With several different drivers on your system, and no indication that you blacklisted any of them, who knows what is going wrong.

Actually, driver rtw_8822be from branch rtw88 is the one you should use.

**Comment by thematdev** [comment]
`lsmod | grep 88` result https://pastebin.com/H145PnDm
So what should i do to fix my problem?
What should I blacklist and how should i blacklist?

**Comment by lwfinger** [comment]
rtl8822be              94208  0
halmac                192512  1 rtl8822be
phydm_mod             917504  1 rtl8822be
btcoexist             479232  1 rtl8822be
rtl_pci                36864  1 rtl8822be
rtlwifi               188416  5 rtl8822be,rtl_pci,halmac,btcoexist,phydm_mod

None of the above should be loaded. Blacklisting 'rtl8822be' should remove all of them.

How to blacklist is well covered on the Web. I leave that for you to discover.

**Comment by thematdev** [comment]
I have created `/etc/modprobe.d/blacklist.conf` file and added
`blacklist rtl8822be`. "Halmac init hal failed" disappeared, but network is not working.

**Comment by lwfinger** [comment]
Do you have ANY drivers for the 8822be loaded?

**Comment by Armysilverbox** [comment]
I have this problem too.
After ps start, wifi works 10-30 sec and return error, then trying to search, but can't find any access point.
result of "lsmod | grep 88" 
nls_iso8859_1          16384  1
rtw_8822be             16384  0
rtw_8822b             225280  1 rtw_8822be
rtw_pci                24576  1 rtw_8822be
rtw_core              163840  2 rtw_8822b,rtw_pci

**Comment by Thiviyan** [comment]
> I have this problem too.
> After ps start, wifi works 10-30 sec and return error, then trying to search, but can't find any access point.
> result of "lsmod | grep 88"
> nls_iso8859_1 16384 1
> rtw_8822be 16384 0
> rtw_8822b 225280 1 rtw_8822be
> rtw_pci 24576 1 rtw_8822be
> rtw_core 163840 2 rtw_8822b,rtw_pci
> 
> when I add rtl8822be to the blacklist, rtw_8822be is used after restart, but the netlist is empty.
> 
> if you do the opposite, blacklist rtw_8822be, then after restarting
> 
> sudo modprobe -r rtl8822be
> sudo modprobe rtw_8822be
> sudo lshw -C network
> shows that I use rtw_8822be and everything works.
> why it happens.
> 
> Result: if system launched on rtw_8822be wifi working, but netlist is empty
> if system launched on rtl8822be wifi working, but netlist is empty, but if i change from rtl8822be to rtw_8822be, wifi is working good
> 
> Any ideas please?
> 
> Upd.
> 
> Ok, i found solution.
> r8822be driver from linux-5.1.21, installing from git repo.
> if anyone have same problem, try it.
> After install, reboot and everything work ok.
> sudo lshw -c network
> returns that driver=r8822be

this one works without any hassles..

booting into windows os and again booting back into linux solved the halmac_init_hal failed issues (every now and then i had to do this ) when using rtlwifi_new drivers on linux version 5.6.0

**Comment by thematdev** [comment]
Problem persists. I have drivers loaded. I have blacklisted "rtl8822be".
`lsmod | grep 88` prompt: https://pastebin.com/u0Fk5XpM
`dmesg` prompt: https://pastebin.com/6fVt4Nhr

There is a new error appears.

**Comment by lwfinger** [comment]
You should be blacklisting rtl8822be as that one os no longer supported by anyone.

That ASPM error should be reported to the people that are supporting rtw88. I have no idea what is wrong. My only suggestion is that you try loading rtw_pci with option disable_msi=y.

If that does not help, send your dmesg fragment to linux-wireless@vger.kernel.org. I do suggest that you post the material in-line, not on pastebin. For short postings like the two above, people like me hate having to open another site to see some critical piece of information. About 100 lines is probably a good transition.
