### ISSUE TITLE
Can not install the RTL8723DE module in Kali Linux

### ISSUE THREAD

**Issue by Velarde030414** [lwfinger/rtlwifi_new#585]
Hello
I'm new to kali linux and I'm trying to install RTL8723DE module but it seems to be showing some kind of error
the error starts when I type "sudo make"  in the terminal
this is the error:
grep: /lib/modules/5.6.0-kali1-amd64/build/include/net/mac80211.h: No such file or directory
make -C /lib/modules/5.6.0-kali1-amd64/build M=/rtlwifi_new modules
make[1]: Entering directory '/usr/src/linux-headers-5.6.0-kali1-amd64'
grep: /lib/modules/5.6.0-kali1-amd64/build/include/net/mac80211.h: No such file or directory
  CC [M]  /rtlwifi_new/rc.o
/rtlwifi_new/rc.c:336:11: error: initialization of ‘void * (*)(struct ieee80211_hw *, struct dentry *)’ from incompatible pointer type ‘void * (*)(struct ieee80211_hw *)’ [-Werror=incompatible-pointer-types]
  336 |  .alloc = rtl_rate_alloc,
      |           ^~~~~~~~~~~~~~
/rtlwifi_new/rc.c:336:11: note: (near initialization for ‘rtl_rate_ops.alloc’)
cc1: some warnings being treated as errors
make[3]: *** [/usr/src/linux-headers-5.6.0-kali1-common/scripts/Makefile.build:273: /rtlwifi_new/rc.o] Error 1
make[2]: *** [/usr/src/linux-headers-5.6.0-kali1-common/Makefile:1696: /rtlwifi_new] Error 2
make[1]: *** [/usr/src/linux-headers-5.6.0-kali1-common/Makefile:180: sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.6.0-kali1-amd64'
make: *** [Makefile:88: all] Error 2

**Comment by lwfinger** [comment]
The source code has instructions on what you need to do for this issue; however, you are actually using the wrong driver!!

From the directory containing the sources. do the following:
git checkout origin/rtw88 -b rtw88
make
sudo make install

Now you will be using the driver from the 5.8.0 kernel. Any problems with it should be reported to linux-wireless@vger.kernel.org.

**Comment by djguru00** [comment]
please tell me surely from which directory should I run this command?

**Comment by djguru00** [comment]
I also have the same problem

**Comment by lwfinger** [comment]
From the directory containing the sources.

If you have not already checked out the sources, then from any directory
git clone http://github.com/lwfinger/rtlwifi_new.git -b rtw88

Next time do some research on what to do. I am very tired of answering the same question over and over and over. I run these repos as a service to users, but the load is too great. My morning mail had about 20 messages about this kind of stuff.
