### ISSUE TITLE
 rtlwifi_new 

### ISSUE THREAD

**Issue by arnaud02** [lwfinger/rtlwifi_new#587]
1 _ first error

CC [M] /root/rtlwifi_new/phydm/halrf/rtl8723d/halrf_8723d.o
CC [M] /root/rtlwifi_new/phydm/rtl_phydm.o
/root/rtlwifi_new/phydm/rtl_phydm.c: In function ‘rtl_phydm_add_sta’:
/root/rtlwifi_new/phydm/rtl_phydm.c:919:38: warning: taking address of packed member of ‘struct rtl_sta_info’ may result in an unaligned pointer value [-Waddress-of-packed-member]
919 | phydm_cmn_sta_info_hook(dm, mac_id, &sta_entry->cmn_info);
| ^~~~~~~~~~~~~~~~~~~~
/root/rtlwifi_new/phydm/rtl_phydm.c: In function ‘dump_sta_info’:
/root/rtlwifi_new/phydm/rtl_phydm.c:1362:12: warning: taking address of packed member of ‘struct rtl_sta_info’ may result in an unaligned pointer value [-Waddress-of-packed-member]
1362 | ra_info = &sta_entry->cmn_info.ra_info;
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

2 _ second error

LD [M] /root/rtlwifi_new/rtl8192de/rtl8192de.o
CC [M] /root/rtlwifi_new/rtl8192ee/dm.o
/root/rtlwifi_new/rtl8192ee/dm.c: In function ‘rtl92ee_dm_check_rssi_monitor’:
/root/rtlwifi_new/rtl8192ee/dm.c:524:28: warning: taking address of packed member of ‘struct rtl_sta_info’ may result in an unaligned pointer value [-Waddress-of-packed-member]
524 | struct rssi_sta *stat = &drv_priv->rssi_stat;
| ^~~~~~~~~~~~~~~~~~~~
CC [M] /root/rtlwifi_new/rtl8192ee/fw.o

3_ third error

LD [M] /root/rtlwifi_new/rtl8822be/rtl8822be.o
CC [M] /root/rtlwifi_new/base.o
/root/rtlwifi_new/base.c: In function ‘rtl_action_proc’:
/root/rtlwifi_new/base.c:1945:16: warning: taking address of packed member of ‘struct rtl_sta_info’ may result in an unaligned pointer value [-Waddress-of-packed-member]
1945 | tid_data = &sta_entry->tids[tid];
| ^~~~~~~~~~~~~~~~~~~~~
/root/rtlwifi_new/base.c: In function ‘rtl_tx_agg_start’:
/root/rtlwifi_new/base.c:2253:13: warning: taking address of packed member of ‘struct rtl_sta_info’ may result in an unaligned pointer value [-Waddress-of-packed-member]
2253 | tid_data = &sta_entry->tids[tid];
| ^~~~~~~~~~~~~~~~~~~~~
/root/rtlwifi_new/base.c: In function ‘rtl_rx_agg_start’:
/root/rtlwifi_new/base.c:2312:13: warning: taking address of packed member of ‘struct rtl_sta_info’ may result in an unaligned pointer value [-Waddress-of-packed-member]
2312 | tid_data = &sta_entry->tids[tid];
| ^~~~~~~~~~~~~~~~~~~~~
CC [M] /root/rtlwifi_new/cam.o
CC [M] /root/rtlwifi_new/core.o
/root/rtlwifi_new/core.c: In function ‘rtl_op_sta_add’:
/root/rtlwifi_new/core.c:959:17: warning: taking address of packed member of ‘struct rtl_sta_info’ may result in an unaligned pointer value [-Waddress-of-packed-member]
959 | list_add_tail(&sta_entry->list, &rtlpriv->entry_list);
| ^~~~~~~~~~~~~~~~
/root/rtlwifi_new/core.c: In function ‘rtl_op_sta_remove’:
/root/rtlwifi_new/core.c:1066:12: warning: taking address of packed member of ‘struct rtl_sta_info’ may result in an unaligned pointer value [-Waddress-of-packed-member]
1066 | list_del(&sta_entry->list);
| ^~~~~~~~~~~~~~~~
CC [M] /root/rtlwifi_new/debug.o
CC [M] /root/rtlwifi_new/efuse.o
CC [M] /root/rtlwifi_new/ps.o
CC [M] /root/rtlwifi_new/rc.o
/root/rtlwifi_new/rc.c:336:11: error: initialization of ‘void * (*)(struct ieee80211_hw *, struct dentry )’ from incompatible pointer type ‘void * ()(struct ieee80211_hw *)’ [-Werror=incompatible-pointer-types]
336 | .alloc = rtl_rate_alloc,
| ^~~~~~~~~~~~~~
/root/rtlwifi_new/rc.c:336:11: note: (near initialization for ‘rtl_rate_ops.alloc’)
cc1: some warnings being treated as errors
make[4]: *** [/usr/src/linux-headers-5.2.0-kali2-common/scripts/Makefile.build:284: /root/rtlwifi_new/rc.o] Error 1
make[3]: *** [/usr/src/linux-headers-5.2.0-kali2-common/Makefile:1610: module/root/rtlwifi_new] Error 2
make[2]: *** [Makefile:179: sub-make] Error 2
make[1]: *** [Makefile:8: all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.2.0-kali2-amd64'
make: *** [Makefile:88: all] Error 2

**Comment by lwfinger** [comment]
Congratulations - You are seeing warnings never seen before.

The error has instructions on how to fix it in the source code. read IT.

Other than this, I am no longer paying attention to any complaints or issues for any branch of rtlwifi_new EXCEPT for rtw88!!!!!!
