### ISSUE TITLE
Rtw88 : rtw8723de very slow, antenna problem ?

### ISSUE THREAD

**Issue by yoann-dev** [lwfinger/rtlwifi_new#589]
Hello @lwfinger,

I have installed the rtw_8723de driver from the rtw88 branch (before I used the rtl8723de from extended branch). Wifi is very slow compared to the older version. Maybe antenna selection could be explained this slowness ?

I have tried to put the modprobe option to select antenna (like on extended branch), but it's not worked. I couldn't find any settings to properly select antenna in the code via modprobe.

```
$ dmesg
[    4.181500] rtw_core: loading out-of-tree module taints kernel.
[    4.181600] rtw_core: module verification failed: signature and/or required key missing - tainting kernel
[    4.206654] rtw_8723de: unknown parameter 'ant_sel' ignored
[    4.213066] rtw_8723de 0000:02:00.0: firmware: direct-loading firmware rtw88/rtw8723d_fw.bin
[    4.213070] rtw_8723de 0000:02:00.0: Firmware version 48.0.0, H2C version 0

$ uname -a
Linux yoann-Laptop 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64 GNU/Linux
```

Thanks for your answers.

**Comment by kimocoder** [comment]
Instead of opening another report, I'll just share here, Larry.

The USB side of RTW88 is under development in the link below, if you wan't to keep track of it somehow. Cheers :+1: 

https://github.com/neojou/rtw88-usb

**Comment by lwfinger** [comment]
Thanks for the info.
