### ISSUE TITLE
Erron on Compilation

### ISSUE THREAD

**Issue by brenda1111** [lwfinger/rtlwifi_new#591]
i got this error during make command and i referenced many solution even that you provided but nothing worked for me. This used to work perfectly for me before few months but when i reinstalled kali and tried to install rtlwifi_new i get this error  everytime. i kindly request ti help me out and resolve this issue. Thank you. i'm attaching the screenshot of the error.
![oie_9VhdJglcjP9K](https://user-images.githubusercontent.com/65823337/82735676-00cb9b00-9d41-11ea-9fc8-295b38d1b875.png)

**Comment by lwfinger** [comment]
If you edit the source file that has the error, you will see the fix.

You might consider doing a little searching about errors. This has been covered at least 20 times, and I am tired of repeating the same answer over and over!!!

Note that this branch of the repo does away next week. As you are using kernel 5.3, you should use the kernel driver for all devices except RTL8723DE. For that particular device you will need to switch to the rtw88 branch.

**Comment by brenda1111** [comment]
Thank you so much. it worked perfectly.

**Comment by brenda1111** [comment]
@lwfinger My Bluetooth isn't working, driver is rtl8723de. Its was all perfectly working on older rtlwifi extended branch; Just one make and modprobe command that's it. can you please help me to get that error compiled (error that i posted with picture). Thank You
