### ISSUE TITLE
Compilation error for rc.o | MXLinux 4.19.0 | RTL8723de

### ISSUE THREAD

**Issue by sarquis88** [lwfinger/rtlwifi_new#594]
Hello,
When I try to do "make" it appears the following error:

`/home/tomsar/Downloads/rtlwifi_new/rc.c:336:11: error: initialization of ‘void * (*)(struct ieee80211_hw *, struct dentry *)’ from incompatible pointer type ‘void * (*)(struct ieee80211_hw *)’ [-Werror=incompatible-pointer-types]
  .alloc = rtl_rate_alloc,
           ^~~~~~~~~~~~~~
/home/tomsar/Downloads/rtlwifi_new/rc.c:336:11: note: (near initialization for ‘rtl_rate_ops.alloc’)
cc1: some warnings being treated as errors
make[4]: *** [/usr/src/linux-headers-4.19.0-6-common/scripts/Makefile.build:309: /home/tomsar/Downloads/rtlwifi_new/rc.o] Error 1
make[3]: *** [/usr/src/linux-headers-4.19.0-6-common/Makefile:1534: _module_/home/tomsar/Downloads/rtlwifi_new] Error 2
make[2]: *** [Makefile:146: sub-make] Error 2
make[1]: *** [Makefile:8: all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.19.0-6-amd64'
make: *** [Makefile:88: all] Error 2`

As I've mentioned in the title, i'm running MXLinux in the kernel's 4.19.0 version, and my wireless device is RTL8723de.
Please could someone help me? Thanks in advance.

Regards

**Comment by yoann-dev** [comment]
Hello @sarquis88 ,

I have encountered the same problem ( #578 ), so I have forked this repository to work on extended branch for Debian 10 : https://github.com/yoann-dev/rtlwifi_new_debian_10

MxLinux is based on Debian, so it should work for you with RTL8723de.

**Comment by sarquis88** [comment]
Thanks you a lot @yoann-dev, It works!!! 
I should have seen your issue (#578), my apologies.
