### ISSUE TITLE
@lwfinger My Bluetooth isn't working, driver is rtl8723de. Its was all perfectly working on older rtlwifi extended branch; Just one make and modprobe command that's it. can you please help me to get that error compiled (error that i posted with picture). Thank You

### ISSUE THREAD

**Issue by brenda1111** [lwfinger/rtlwifi_new#595]
@lwfinger My Bluetooth isn't working, driver is rtl8723de. Its was all perfectly working on older rtlwifi extended branch; Just one make and modprobe command that's it. can you please help me to get that error compiled (error that i posted with picture). Thank You

_Originally posted by @brenda1111 in https://github.com/lwfinger/rtlwifi_new/issues/591#issuecomment-634443562_

**Comment by cata0309** [comment]
I know @lwfinger does not do bluetooth related stuff but I experience a similar problem. I cannot use both Wifi and Bluetooth simultaneously !

**Comment by lwfinger** [comment]
The extended branch is deleted. If the rtw88 branch fails, then you need to follow the last paragraph of README.md to get help.

**Comment by cata0309** [comment]
I managed to solve it, I was inserting the wrong conf options
