### ISSUE TITLE
Parrot os and Kali Linux freezing after changing adapter to monitor mode

### ISSUE THREAD

**Issue by Shiva9361** [lwfinger/rtlwifi_new#599]
After using the rtw88 repo my wifi started working but when I do
Sudo ifconfig wlan0 down
Iwconfig wlan0 mode monitor
And last
Sudo ifconfig wlan0 up my computer freezes. I tried in both kali and parrot but the same result please help me

**Comment by lwfinger** [comment]
Read the last paragraph of README.md

**Comment by Shiva9361** [comment]
Sir I am using rtl8723de and the I can't understand what you mean by using the driver built into the kernel

**Comment by lwfinger** [comment]
That is NOT what I told you!  WHAT DOES THE LAST PARAGRAPH OF README.md SAY?

Mine says
"When you have problems where the driver builds and loads correctly, but fails to work, a GitHub
issue is NOT the best place to report it. I have no idea of the internal workings of any of the
chips, and the Realtek engineers who do will not read these issues. To reach them, send E-mail to
linux-wireless@vger.kernel.org. Include a detailed description of any messages in the kernel
logs and any steps that you have taken to analyze or fix the problem. If your description is
not complete, you are unlikely to get any satisfaction."
