### ISSUE TITLE
A typo in dkms.conf in rtw88 branch

### ISSUE THREAD

**Issue by hanipouspilot** [lwfinger/rtlwifi_new#600]
BUILT_MODULE_NAME[0]="rtl_pci" should be

BUILT_MODULE_NAME[0]="rtw_pci"

**Comment by burdi01** [comment]
Confirming the above change to resolve the dkms build on Xubuntu 20.04.
However, immediately afterwards the driver is given as rtw_pci instead of rtw_8723de as I expected. And a subsequent reboot hangs ...
:D

**Comment by lwfinger** [comment]
Thanks. I fixed it and added the RTL8821CE to dkms.conf.
