### ISSUE TITLE
Unable to install WiFi adapter in Hp laptop kernel above 5.0

### ISSUE THREAD

**Issue by iamkabilan** [lwfinger/rtlwifi_new#603]
sudo make install not working

**Comment by lwfinger** [comment]
Your description is not specific.

**Comment by iamkabilan** [comment]
I am using HP laptop(Ubuntu), my wifi adapter disappeard after kernel update(5.0) and my adapter is Realtek, you have abadoned the master, so where can I download the driver.

**Comment by lwfinger** [comment]
It would be helpful if you were so kind as to state what adapter you have. I abandoned master because the drivers are available in kernel 5.0, thus your question is not understandable. It is exactly this kind of posting that caused me to stop wasting a lot of time, and abandon the old drivers!!
