### ISSUE TITLE
inflate: data stream error (incorrect data check)B/s

### ISSUE THREAD

**Issue by Gissp** [lwfinger/rtlwifi_new#604]
buenas noches me podrian ayudar a solucionar este problema
kali@kali:~$ git clone https://github.com/lwfinger/rtlwifi_new.git -b rtw88 
Cloning into 'rtlwifi_new'...
remote: Enumerating objects: 28, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (23/23), done.
error: inflate: data stream error (incorrect data check)B/s
fatal: pack has bad object at offset 1071942: inflate returned -3
fatal: index-pack failed

**Comment by lwfinger** [comment]
I have no idea what is wrong with your git. When I do your command:

finger@localhost:~/home:lwfinger:branches:Virtualization/virtualbox> git clone https://github.com/lwfinger/rtlwifi_new.git -b rtw88
Cloning into 'rtlwifi_new'...
remote: Enumerating objects: 28, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 6742 (delta 7), reused 20 (delta 5), pack-reused 6714
Receiving objects: 100% (6742/6742), 16.08 MiB | 12.40 MiB/s, done.
Resolving deltas: 100% (5395/5395), done.

If the error persists, uninstall and reinstall git. It seems to be corrupt.

**Comment by Gissp** [comment]
muchas gracias siempre atento a tus indicaciones
