### ISSUE TITLE
@lwfinger RTL8723D Bluetooth works fine on KERNELS 4.19.x, but the adapter is NOT DETECTED ON NEWER KERNELS

### ISSUE THREAD

**Issue by ShubhamSharma64337** [lwfinger/rtlwifi_new#606]
Hi, I have a hp laptop with Windows 10 preinstalled. It has rtl8723de wifi adapter and rtl8723d blutooth. The rtl8723d bluetooth adapter gets detected in 4.19.x kernel versions but does not get detected in any kernel versions after that. I have tried 4.20 and 5.x.x kernels and none of them were able to detect it. According to the dmesg log, I think that the newer kernels are not even able to detect the hci0 device, and thus there is no log regarding the loading of the firmware. 
Here is the sudo dmesg | grep Blue output on MX Linux with older kernel on which bluetooth works : 
[ 12.264937] Bluetooth: Core ver 2.22
[ 12.264947] Bluetooth: HCI device and connection manager initialized
[ 12.264948] Bluetooth: HCI socket layer initialized
[ 12.264950] Bluetooth: L2CAP socket layer initialized
[ 12.264952] Bluetooth: SCO socket layer initialized
[ 12.402352] Bluetooth: hci0: RTL: rtl: examining hci_ver=08 hci_rev=000d lmp_ver=08 lmp_subver=8723
[ 12.403335] Bluetooth: hci0: RTL: rom_version status=0 version=2
[ 12.403336] Bluetooth: hci0: RTL: rtl: loading rtl_bt/rtl8723d_fw.bin
[ 12.440366] Bluetooth: hci0: RTL: rtl: loading rtl_bt/rtl8723d_config.bin
[ 18.871947] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[ 18.871947] Bluetooth: BNEP filters: protocol multicast
[ 18.871950] Bluetooth: BNEP socket layer initialized
[ 29.993005] Bluetooth: RFCOMM TTY layer initialized
[ 29.993010] Bluetooth: RFCOMM socket layer initialized
[ 29.993013] Bluetooth: RFCOMM ver 1.11

And here is sudo dmesg | grep Blue output on Ubuntu with newer kernel on which bluetooth doesn't work: 
[ 95.362787] Bluetooth: Core ver 2.22
[ 95.362811] Bluetooth: HCI device and connection manager initialized
[ 95.362815] Bluetooth: HCI socket layer initialized
[ 95.362817] Bluetooth: L2CAP socket layer initialized
[ 95.362820] Bluetooth: SCO socket layer initialized

This is the output from Ubuntu 19.04, but I have also tried 19.10, 20.04 and they give the same result. In the first two ubuntu versions, the rtl_bt folder was not there by default in /lib/firmware/ and I placed it there but it had no effect. In the latest 20.04 version, the rtl_bt folder is already placed in the /lib/firmware/ and also contains the proper firmware files for my adapter. Also, in this newer kernel, the btusb module is not loaded by default on boot, but even loading it doesn't change anything. So as far as I think, the kernel first detects the presence of the bluetooth adapter(shown as hci0 in the log) and then loads the firmware for it. But these newer kernel versions, the adapter is not even detected, let alone the firmware loading. 

Also, when I installed the older 4.19 kernel on the same Ubuntu 20.04 os and booted from that older kernel, it began detecting the bluetooth fine! Also, the Wi-Fi works fine on all the kernels.
Can anybody please explain if there is any solution for this problem and what is really happening?

**Comment by Lollixzc** [comment]
Have you correctly installed all the modules? Read the readme [here](https://github.com/lwfinger/rtlwifi_new/tree/rtw88#rtlwifi_new). I don't think it is a driver issue, maybe you need to change the antenna with the `ant_sel=1 or 2` option.

**Comment by lwfinger** [comment]
For newer kernels, the built-in kernel modules work for BT. Check the output of dmesg to verify that you have the correct firmware and configuration files.
