### ISSUE TITLE
How to use kernel built drivers (README.md)

### ISSUE THREAD

**Issue by serhumanos** [lwfinger/rtlwifi_new#609]
Hi, in README.md says:

> The master branch of this repo is officially abandoned. If you are running a kernel newer than 5.0, use the drivers built into your kernel. 

i have the kernel: 5.3.0-53-generic, using KDE Neon based on Ubuntu.
but there is no recognition of wifi card, i MUST install this driver to be able to use wifi ~~(bluetooth only works if wifi is not connected :( but i can live with this)~~.
How can i use the drivers built into my kernel?

edit: **my card is RTL8723DE**, 
- compiling branch rtw88 is working after reboot.
- **now with this driver bluetooth work fine with wifi enabled too!**

thank you very much!

**Comment by lwfinger** [comment]
What card do you have? My crystal ball is broken.

**Comment by serhumanos** [comment]
> What card do you have? My crystal ball is broken.
heheheh thx, i came back to edit my post to add this info, hehe, sorry and thanks for your quick reply.
(i suppose my linux distro do not have the built in RTL8723de driver, but this message may help some other lost like me)

**Comment by lwfinger** [comment]
Only some later Ubuntu releases have rtl8723de drivers built in. You needed to switch to the rtw88 branch, as you did, and as the README.md says.

I'm glad you got it working.
