### ISSUE TITLE
System freeze with 0bda:8176

### ISSUE THREAD

**Issue by bhack** [lwfinger/rtlwifi_new#61]
Kernel version: 3.10.40 
rtlwifi Commit:fe8e96938599e97cf4f76d22e6ab00066ff05ec5

```
[141.655299] usb 2-1.2: New USB device found, idVendor=0bda, idProduct=8176
[  141.655357] usb 2-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  141.655400] usb 2-1.2: Product: 802.11n WLAN Adapter
[  141.655437] usb 2-1.2: Manufacturer: Realtek
[  141.655473] usb 2-1.2: SerialNumber: 00e04c000001
[  141.814707] cfg80211: Calling CRDA to update world regulatory domain
[  141.924411] cfg80211: World regulatory domain updated:
[  141.924439] cfg80211:   (start_freq - end_freq @ bandwidth), (max_antenna_gain, max_eirp)
[  141.924455] cfg80211:   (2402000 KHz - 2472000 KHz @ 40000 KHz), (300 mBi, 2000 mBm)
[  141.924469] cfg80211:   (2457000 KHz - 2482000 KHz @ 40000 KHz), (300 mBi, 2000 mBm)
[  141.924481] cfg80211:   (2474000 KHz - 2494000 KHz @ 20000 KHz), (300 mBi, 2000 mBm)
[  141.924493] cfg80211:   (5170000 KHz - 5250000 KHz @ 40000 KHz), (300 mBi, 2000 mBm)
[  141.924503] cfg80211:   (5735000 KHz - 5835000 KHz @ 40000 KHz), (300 mBi, 2000 mBm)
[  142.029971] Chip version 0x10
[  142.235760] MAC address: 5c:f3:70:06:56:64
[  142.235789] Board Type 0
[  142.236919] rx_max_size 15360, rx_urb_num 8, in_ep 1
[  142.237421] Loading firmware rtlwifi/rtl8192cufw_TMSC.bin
[  142.263978] ieee80211 phy0: Selected rate control algorithm 'rtl_rc'
[  142.275064] usbcore: registered new interface driver rtl8192cu
[  142.293810] Loading alternative firmware rtlwifi/rtl8192cufw.bin
[  142.293820] Firmware rtlwifi/rtl8192cufw_TMSC.bin not available
[  142.320788] MAC auto ON okay!
[  142.385823] Tx queue select: 0x05
[  142.907749] rtl8192c_common:_rtl92c_fw_free_to_go():<0-0> Polling FW ready fail!! REG_MCUFWDL:0x00000006 .
[  142.907754] rtl8192c_common:rtl92c_download_fw():<0-0> Firmware is not ready to run!
[  143.272833] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[  143.738262] reg 0xe08, usbctrl_vendorreq TimeOut! status:0xffffffb9 value=0x0
```

**Comment by bhack** [comment]
Chip reference http://www.realtek.com/products/productsView.aspx?Langid=1&PNid=21&PFid=48&Level=5&Conn=4&ProdID=274

**Comment by bhack** [comment]
Doesn't freeze anymore with Rock branch but interface isn't not visible (module are correctly loaded and also the firmware was found)

**Comment by lwfinger** [comment]
Please post the pertinent parts of the output of dmesg. Your narrative does not have enough info to even try for a fix. I will try to duplicate your result, but I do not have a lot of hope.

By the way, this repo includes the USB driver only for convenience. There are a lot of mainline fixes for rtl8192cu that never get backported to this repo. You should try either a new (4.1 or 4.2-rcX) kernel or use the backports code at https://wireless.wiki.kernel.org/en/users/download/stable. Use either the 4.1.1 or 4.2-rc1 versions.

**Comment by bhack** [comment]
I cannot try 4.1 4.2-rcX on this embedded platform.
Backport code for 4.1.1 or 4.2-rc1 versions seems to not let enable rtlwifi for 3.10.40. Do you want that i test an older backport version? Do you suggest a specific backport to try?

**Comment by lwfinger** [comment]
What do you mean "seems to not let enable rtlwifi for 3.10.40"? Does it build but not create a wireless device?

Is there a problem with the rtl8192cu driver built into 3.10?

**Comment by bhack** [comment]
It is not in list with make menuconfig.

**Comment by lwfinger** [comment]
Did you select nl80211 and mac80211? Without them, you cannot build any of the rtlwifi drivers.

**Comment by bhack** [comment]
I've enabled nl80211 and cfg80211 but rtlwifi it not in the menu (instead broadcom and others are there)

**Comment by lwfinger** [comment]
Post your .config from the backports directory.

**Comment by bhack** [comment]
It is at https://gist.github.com/bhack/857d58e5adef25d59774

**Comment by lwfinger** [comment]
You have enabled cfg80211, but not mac80211.

**Comment by bhack** [comment]
I don't have mac80211 in the backport menu. If i force with make defconfig-rtlwifi I got many warning as you can see at https://gist.github.com/bhack/0708d012b0b32f917007

**Comment by lwfinger** [comment]
To enable MAC80211, you need CFG80211, CRYPTO, CRYPTO_ARC4, CRYPTO_AES, CRYPTO_GCM, and CRC32.   Your configuration is missing CRYPTO_GCM.

I do not know enough about backports to know if that is a problem with backports on your kernel version, a configuration problem with yur kernel, or some other difficulty. Try adding a line that says "CPTCFG_CRYPTO_GCM=m" to your .config before running 'make menuconfig'. If that does not work, send a question to linux-wireless@vger.kernel.org.
