### ISSUE TITLE
make: *** No rule to make target 'install'.  Stop.

### ISSUE THREAD

**Issue by tushargoyal22** [lwfinger/rtlwifi_new#611]
I followed these below commands in past many times and it worked to succesful run wifi.
But now its giving error regarding make
```
git clone https://github.com/lwfinger/rtlwifi_new.git
cd rtlwifi_new/ && git checkout origin/extended -b extended
sudo apt-get install linux-headers-generic build-essential git
sudo make install
sudo modprobe -r rtl8723de
sudo modprobe rtl8723de
sudo modprobe -r rtl8723de && sleep 5 && sudo modprobe rtl8723de ant_sel=2
echo "options rtl8723de ant_sel=2" | sudo tee /etc/modprobe.d/rtl8723de.conf

```
Can you please help me out to get this sorted.
@lwfinger

**Comment by tushargoyal22** [comment]
sudo make install
this command is failing

**Comment by tushargoyal22** [comment]
```
sudo apt purge bcmwl-kernel-source
sudo sed -i '/blacklist bcma/ d' /etc/modprobe.d/blacklist.conf
sudo sed -i '/blacklist brcmsmac/ d' /etc/modprobe.d/blacklist.conf
```
I tried out above commands also but `sudo make install` is not working

**Comment by Lollixzc** [comment]
What type of errors are you receiving? Could you please post the errors? Remember to use the rtw88 branch, because the other branches are no longer maintained.

**Comment by tushargoyal22** [comment]
> What type of errors are you receiving? Could you please post the errors? Remember to use the rtw88 branch, because the other branches are no longer maintained.

can you please share the set of commands need to be used to install the wifi adapter. I used below commands till date whenever adapter was not recognized . But today its not working.  How to use rtw88 particular branch
```
git clone https://github.com/lwfinger/rtlwifi_new.git
cd rtlwifi_new/ && git checkout origin/extended -b extended
sudo apt-get install linux-headers-generic build-essential git
sudo make install
sudo modprobe -r rtl8723de
sudo modprobe rtl8723de
sudo modprobe -r rtl8723de && sleep 5 && sudo modprobe rtl8723de ant_sel=2
echo "options rtl8723de ant_sel=2" | sudo tee /etc/modprobe.d/rtl8723de.conf
```

**Comment by Lollixzc** [comment]
You need to do the following steps.
To download the first time the repository do the following:
```bash
git clone https://github.com/lwfinger/rtlwifi_new.git
cd rtlwifi_new/ && git checkout origin/rtw88 -b rtw88
```

If you already cloned the repository do the following:
```bash
cd rtlwifi_new/
`git checkout origin/rtw88 -b rtw88`
git pull  
```
The last line is the command that updates the repository you cloned earlier. `git checkout origin/rtw88 -b rtw88` This command needs to be used only one time, when you choose what branch to work on.

When you have done that, you can proceed to compile and install the modules with the following commands:
```bash
make
sudo make install
```

If all works correctly, you can now load the wifi modules through these command, selecting what antenna to load:
```bash
sudo modprobe rtl8723de ant_sel=2
```

Remember that you have to blacklist the wifi kernel modules if you want to load these new ones. Search in the internet on how to do that.

**Comment by tushargoyal22** [comment]
![Screenshot from 2020-06-12 15-27-50](https://user-images.githubusercontent.com/43175862/84490812-5270a100-acc1-11ea-8c6d-d03c3bd49e89.png)

```
sudo apt purge bcmwl-kernel-source
sudo sed -i '/blacklist bcma/ d' /etc/modprobe.d/blacklist.conf
sudo sed -i '/blacklist brcmsmac/ d' /etc/modprobe.d/blacklist.conf
```
Even after using this to blacklist ,it gave same error as below
**modprobe: FATAL: Module rtl8723de not found in directory /lib/modules/5.3.0-59-generic**

**Comment by Lollixzc** [comment]
You are not loading the correct module. What you need to load probably is `sudo modprobe rtw_8723de ant_sel=2`

**Comment by tushargoyal22** [comment]
It worked, thanks a lot. Do i need to add something now, beacause earlier also after some span of time  on restarting laptop it went lost and i had to always repeat the steps again

**Comment by Lollixzc** [comment]
If you want to make your option `ant_sel=2` permanent read [this part](https://github.com/lwfinger/rtlwifi_new/tree/rtw88#option-configuration) of the readme. In your case the module is named `rtw_8723de`. 
You need to blacklist the default kernel module in order to load the correct one. [Here](https://askubuntu.com/questions/110341/how-to-blacklist-kernel-modules) is an answer that will help you do that. I think your issue is solved now, so you can close this issue.

**Comment by lwfinger** [comment]
@Lollixzc - Thanks for handling this issue.
@tushargoyal22 - Never post that "The command is failing" without posting the errors. When you do that, you make it impossible for anyone to help.

As a general rule, look at the file README.md. It covers this case.
