### ISSUE TITLE
RTL8821AE Fails to Authenticate to 5GHz WPA2 Network [Ubuntu 20.04]

### ISSUE THREAD

**Issue by fastoe** [lwfinger/rtlwifi_new#612]
Initially, I noticed after a kernel update to 4.15 that the kernel-provided rtl module was no longer letting me connect to my 5GHz WPA2-personal encrypted wireless network with authentication timing out. I assumed this was potentially due to a fix that had been committed upstream but not included in the kernel, so I downloaded the available source code for the extended branch, built, and installed it, but the authentication seems to still time out. I did verify the password was correct multiple times!

5g can't connect:
- ubuntu 14.04
- ubuntu 20.04 
- linuxmint-18.3-cinnamon-64bit

5g can connect:
- ubuntu 18.04.3
- linux mint 19.2
- kali-linux-2020.2
- openSUSE-Leap-15.1

Let me know if I can help by providing any additional information.

**Comment by lwfinger** [comment]
This driver is no longer covered in this repo. I now respond only to issues in branch rtw88 for drivers rtw-8723de, rtw-8821c, rtw-8822b and rtw-8822c. For the RTL8821AE, you should be using the driver in the kernel and post questions/issues with the mailing list linux-wireless@vger.kernel.org.
