### ISSUE TITLE
Please, help me anyone

### ISSUE THREAD

**Issue by AlanTheKnight** [lwfinger/rtlwifi_new#614]
I've started using Linux recently and I've got problems with my wifi, so I installed this rtl8723be driver. Yesterday my kernel was updated to 5.3.0 and I've lost my WiFi. This repository is deleted. I don't know what other driver can I use. Please, help me. You all are advanced users and as I've started just recently I really need it.
First of all, I couldn't understand why my driver disappeared. Anyway when I type
```sudo modprobe rtl8723be``` command it's not giving me any results. I've tried removing it and turning on again but it doesn't seem to work. My device is Realtek Semiconductor d723 What driver do I need to use and how?

**Comment by lwfinger** [comment]
This kind of uninformed question is the reason that the repository was deleted. In fact, you were given 2 weeks notice AND the file README.md tells you exactly what to do. Although you will not likely read this either, here is what you do:
1. Delete this repository and undo any changes you made to use it. In particular, undo the dkms crap.
2. Reboot. This will cause your system to use the driver built into kernel 5.3, which is exactly what was here before it was deleted.
