### ISSUE TITLE
rtl8723be is not working on linux kernel version 5.4.0-37

### ISSUE THREAD

**Issue by govi20** [lwfinger/rtlwifi_new#617]
I have updated my Linux machine from 5.3.xxx to 5.4.0-37, my wifi stopped working. I pulled rtw88 branch and installed the driver using following steps.

```
govi@falcon:~/script/rtl_kernel5/rtlwifi_new-rtw88$ sudo make
make -C /lib/modules/5.4.0-37-generic/build M=/home/govi/script/rtl_kernel5/rtlwifi_new-rtw88 modules
make[1]: Entering directory '/usr/src/linux-headers-5.4.0-37-generic'
  Building modules, stage 2.
  MODPOST 10 modules
make[1]: Leaving directory '/usr/src/linux-headers-5.4.0-37-generic'

```
make install fails with the following error
```

    make -C /lib/modules/5.4.0-37-generic/build M=/home/xyz/script/rtl_kernel5/rtlwifi_new modules
    make[1]: Entering directory '/usr/src/linux-headers-5.4.0-37-generic'
      Building modules, stage 2.
      MODPOST 10 modules
    make[1]: Leaving directory '/usr/src/linux-headers-5.4.0-37-generic'
    Making backups
    modprobe: FATAL: Module rtwpci not found.
    make: *** [Makefile:84: install] Error 1
```

**Comment by Lollixzc** [comment]
Did you clone correctly the repository? It seems it doesn't find some files...

Try to re-clone the repository, and make sure you have all the dependencies met from the [README](https://github.com/lwfinger/rtlwifi_new/tree/rtw88). And usually you do `make` into the rtlwifi_new directory.

**Comment by govi20** [comment]
@Lollixzc yes git clone -b rtw88 https://github.com/lwfinger/rtlwifi_new.git

**Comment by Lollixzc** [comment]
Have you tried again???? It doesn't find the correct files... Have you done a `make clean` before rebuilding the modules? If you have not read the [README](https://github.com/lwfinger/rtlwifi_new/tree/rtw88) file, please go and read it carefully... Otherwise I will not help you anymore, because it seems you haven't downloaded correctly the source files

**Comment by govi20** [comment]
No, I did not run `make clean`. I am quite sure, I have downloaded the source code correctly and I am on the right branch.

**Comment by Lollixzc** [comment]
I just tried to recompile the modules and I don't have any issue compiling them. I suggest you to delete the folder and try again to clone it, because it seems that you are missing some files...

**Comment by lwfinger** [comment]
The subject says "rtl8723be". NO branch of rtlwifi_new handles that driver. Please read README.md!
