### ISSUE TITLE
The Wifi gets Laggy after period of Time 

### ISSUE THREAD

**Issue by hazooma** [lwfinger/rtlwifi_new#618]
Hello ,
I am writing this to send you my issue ! i  guess there is a bug in the new version! what happens with me that after time the connection of my Wifi is lost and then when i try to go to the setting to toggle the wifi on/off the machine gets too lagy ! 
4.20.0-042000-generic

**Comment by yagoplx** [comment]
What gets "laggy"? The computer is freezing or does the wireless connection's speed drop? Please be more specific with your issue. The first assumption could mean that the problem is not this driver's fault but rather in userspace.

**Comment by rodrigomvf** [comment]
I have the same issue...for me the speed drop and after this the connection drop.
rtw_8822be             16384  0
rtw_pci                24576  1 rtw_8822be
rtw_8822b             225280  1 rtw_8822be
rtw_core              159744  2 rtw_8822b,rtw_pci
mac80211              847872  2 rtw_core,rtw_pci
cfg80211              704512  2 rtw_core,mac80211

**Comment by lwfinger** [comment]
For this kind of problem, there is nothing anyone reading this can help you. Please read the last paragraph of README.md and take the actions suggested there. Please be aware that the information posted here would be so incomplete as to be ignored!
