### ISSUE TITLE
rtw_8723de driver becomes unavailable after installing the snapd package in Linux Mint 19.3 and rebooting

### ISSUE THREAD

**Issue by TonyThuitai** [lwfinger/rtlwifi_new#619]
After installing snapd in Linux Mint 19.3 with kernel 5.3.0-59-generic and rebooting, the WiFi module becomes unavailable and after a second reboot the driver works. I performed two tests and the WiFi module fails on both after installing the snapd package and rebooting the first time. The driver works after a second reboot without doing anything except unloading the driver before reboot.

Below are the logs of the error as reported by dmesg and journald. The USB logs are caused by the module errors:
1st log as reported by dmesg:
[    7.061560] usb 2-4: device descriptor read/64, error -71
[    7.305439] usb 2-4: device descriptor read/64, error -71
[    7.673430] usb 2-4: device descriptor read/64, error -71
[    7.917449] usb 2-4: device descriptor read/64, error -71
[    8.573421] usb 2-4: device not accepting address 3, error -71
[    9.129422] usb 2-4: device not accepting address 3, error -71
[    9.397524] usb 2-4: device descriptor read/64, error -71
[    9.637514] usb 2-4: device descriptor read/64, error -71
[   10.009490] usb 2-4: device descriptor read/64, error -71
[   10.249422] usb 2-4: device descriptor read/64, error -71
[   11.445418] usb 2-4: device not accepting address 7, error -71
[   11.997417] usb 2-4: device not accepting address 8, error -71
[   11.997565] usb usb2-port4: unable to enumerate USB device
[   12.812500] rtw_8723de 0000:0d:00.0: failed to poll offset=0x5 mask=0x1 value=0x0
[   12.812504] rtw_8723de 0000:0d:00.0: mac power on failed
[   12.812506] rtw_8723de 0000:0d:00.0: failed to power on mac
[   18.885488] rtw_8723de 0000:0d:00.0: failed to poll offset=0x5 mask=0x3 value=0x0
[   18.885492] rtw_8723de 0000:0d:00.0: mac power on failed
[   18.885494] rtw_8723de 0000:0d:00.0: failed to power on mac
[   24.933678] rtw_8723de 0000:0d:00.0: failed to poll offset=0x5 mask=0x3 value=0x0
[   24.933682] rtw_8723de 0000:0d:00.0: mac power on failed
[   24.933684] rtw_8723de 0000:0d:00.0: failed to power on mac
[   41.030398] rtw_8723de 0000:0d:00.0: failed to poll offset=0x5 mask=0x3 value=0x0
[   41.030402] rtw_8723de 0000:0d:00.0: mac power on failed
[   41.030404] rtw_8723de 0000:0d:00.0: failed to power on mac
[   47.049732] rtw_8723de 0000:0d:00.0: failed to poll offset=0x5 mask=0x3 value=0x0
[   47.049737] rtw_8723de 0000:0d:00.0: mac power on failed
[   47.049738] rtw_8723de 0000:0d:00.0: failed to power on mac
[   63.015505] rtw_8723de 0000:0d:00.0: failed to poll offset=0x5 mask=0x3 value=0x0
[   63.015509] rtw_8723de 0000:0d:00.0: mac power on failed
[   63.015511] rtw_8723de 0000:0d:00.0: failed to power on mac
[   69.023433] rtw_8723de 0000:0d:00.0: failed to poll offset=0x5 mask=0x3 value=0x0
[   69.023437] rtw_8723de 0000:0d:00.0: mac power on failed
[   69.023439] rtw_8723de 0000:0d:00.0: failed to power on mac
[   85.011499] rtw_8723de 0000:0d:00.0: failed to poll offset=0x5 mask=0x3 value=0x0
[   85.011505] rtw_8723de 0000:0d:00.0: mac power on failed
[   85.011508] rtw_8723de 0000:0d:00.0: failed to power on mac
[   91.014760] rtw_8723de 0000:0d:00.0: failed to poll offset=0x5 mask=0x3 value=0x0
[   91.014764] rtw_8723de 0000:0d:00.0: mac power on failed
[   91.014766] rtw_8723de 0000:0d:00.0: failed to power on mac
[  107.007403] rtw_8723de 0000:0d:00.0: failed to poll offset=0x5 mask=0x3 value=0x0
[  107.007407] rtw_8723de 0000:0d:00.0: mac power on failed
[  107.007409] rtw_8723de 0000:0d:00.0: failed to power on mac
[  112.998795] rtw_8723de 0000:0d:00.0: failed to poll offset=0x5 mask=0x3 value=0x0
[  112.998798] rtw_8723de 0000:0d:00.0: mac power on failed
[  112.998800] rtw_8723de 0000:0d:00.0: failed to power on mac
[  129.002695] rtw_8723de 0000:0d:00.0: failed to poll offset=0x5 mask=0x3 value=0x0
[  129.002699] rtw_8723de 0000:0d:00.0: mac power on failed
[  129.002701] rtw_8723de 0000:0d:00.0: failed to power on mac
[  134.992648] rtw_8723de 0000:0d:00.0: failed to poll offset=0x5 mask=0x3 value=0x0
[  134.992652] rtw_8723de 0000:0d:00.0: mac power on failed
[  134.992654] rtw_8723de 0000:0d:00.0: failed to power on mac

2nd Log as reported by journald
06:57:15 wpa_supplicant: wlo1: Failed to initialize driver interface
06:57:15 kernel: rtw_8723de 0000:0d:00.0: failed to power on mac
06:57:15 NetworkManager: <error> [1592193435.7559] sup-iface[0x55ae8fabf500,wlo1]: error adding interface: wpa_supplicant couldn't grab this interface.
06:57:15 wpa_supplicant: WEXT: Could not set interface 'wlo1' UP
06:57:09 kernel: rtw_8723de 0000:0d:00.0: failed to power on mac
06:57:09 wpa_supplicant: nl80211: Could not set interface 'wlo1' UP
06:56:53 kernel: rtw_8723de 0000:0d:00.0: failed to power on mac
06:56:53 wpa_supplicant: wlo1: Failed to initialize driver interface
06:56:53 NetworkManager: <error> [1592193413.7620] sup-iface[0x55ae8fabf5b0,wlo1]: error adding interface: wpa_supplicant couldn't grab this interface.
06:56:53 wpa_supplicant: WEXT: Could not set interface 'wlo1' UP
06:56:47 kernel: rtw_8723de 0000:0d:00.0: failed to power on mac
06:56:47 wpa_supplicant: nl80211: Could not set interface 'wlo1' UP
06:56:31 kernel: rtw_8723de 0000:0d:00.0: failed to power on mac
06:56:31 wpa_supplicant: wlo1: Failed to initialize driver interface
06:56:31 NetworkManager: <error> [1592193391.7780] sup-iface[0x55ae8fabf5b0,wlo1]: error adding interface: wpa_supplicant couldn't grab this interface.
06:56:31 wpa_supplicant: WEXT: Could not set interface 'wlo1' UP
06:56:25 kernel: rtw_8723de 0000:0d:00.0: failed to power on mac
06:56:25 wpa_supplicant: Could not set interface wlo1 flags (UP): Invalid argument
06:56:09 kernel: rtw_8723de 0000:0d:00.0: failed to power on mac
06:56:09 wpa_supplicant: wlo1: Failed to initialize driver interface
06:56:09 NetworkManager: <error> [1592193369.7867] sup-iface[0x55ae8fabf500,wlo1]: error adding interface: wpa_supplicant couldn't grab this interface.
06:56:09 wpa_supplicant: WEXT: Could not set interface 'wlo1' UP
06:56:03 kernel: rtw_8723de 0000:0d:00.0: failed to power on mac
06:56:03 wpa_supplicant: nl80211: Could not set interface 'wlo1' UP
06:55:47 kernel: rtw_8723de 0000:0d:00.0: failed to power on mac
06:55:47 NetworkManager: <error> [1592193347.8131] sup-iface[0x55ae8fabf450,wlo1]: error adding interface: wpa_supplicant couldn't grab this interface.
06:55:47 wpa_supplicant: wlo1: Failed to initialize driver interface
06:55:41 kernel: rtw_8723de 0000:0d:00.0: failed to power on mac
06:55:41 wpa_supplicant: nl80211: Could not set interface 'wlo1' UP
06:55:25 kernel: rtw_8723de 0000:0d:00.0: failed to power on mac
06:55:25 NetworkManager: <error> [1592193325.6976] sup-iface[0x55ae8fabf240,wlo1]: error adding interface: wpa_supplicant couldn't grab this interface.
06:55:25 wpa_supplicant: random: Cannot read from /dev/random: Resource temporarily unavailable
06:55:19 kernel: rtw_8723de 0000:0d:00.0: failed to power on mac
06:55:19 wpa_supplicant: nl80211: Could not set interface 'wlo1' UP
06:55:13 kernel: rtw_8723de 0000:0d:00.0: failed to power on mac
06:55:12 kernel: usb usb2-port4: unable to enumerate USB device

**Comment by lwfinger** [comment]
I cound not determine what snapd is after looking at a couple of web pages; however, it looks as if it is just another piece of Canonical nonsense. It clearly destroys the USB system and seems as if it is messing with the PCI system as well.

Get rid of snapd. Does rtw_8723de work then?

**Comment by TonyThuitai** [comment]
When rebooting the system the first time after snapd is installed, the errors occur maybe due to something that snapd does when the system starts for the first reboot only. I only unloaded the driver by using `sudo modprobe -r rtw_8723de` and rebooted the system again and the driver works and has not failed again. It seems that what snapd was initialising or doing when the system is restarting the first time after the package has been installed seems to cause the issue and the driver works after another reboot.

**Comment by lwfinger** [comment]
Then the modprobe -r/modprobe combination would have worked as well as a reboot.
