### ISSUE TITLE
Unable to make the drivers in Ubuntu 18.04.4 LTS - HP Laptop

### ISSUE THREAD

**Issue by ChavanKarthik** [lwfinger/rtlwifi_new#621]
I have cloned the drivers and trying to execute "sudo make install". But the below error is shown 
"**make: *** No rule to make target 'install'.  Stop**."  
Machine configuration (HP-Laptop):
Description:	Ubuntu 18.04.4 LTS
Codename:	bionic
Kernal Version : 5.3.0-59-generic
Architecture: x86-64

**Comment by ChavanKarthik** [comment]
Can someone share the older version(6 Months old) repository? As it was working absolutely fine in my machine. 
It will be great help for me.

Thanks and Regards,
Chavan Karthik,
mechavan321@gmail.com

**Comment by lwfinger** [comment]
If you search GitHub, you will find the name of the individual, and the GitHub repo that does exactly what you want. It is this kind of behavior (not willing to do any work) that made me delete the repo.

If your device is an RTL8723DE, then you should be using the rtw88 branch. If any of the other devices that used to be covered by the master branch, then you should use the ones in the kernel. They are the same as the old ones.

**Comment by ChavanKarthik** [comment]
Hi, Thanks for your valuable response. I tried to use the rtw88 branch and it worked. Also, I will go through the GitHub.
