### ISSUE TITLE
RTL8822be not working at all, even after installing drivers

### ISSUE THREAD

**Issue by leoperegrino** [lwfinger/rtlwifi_new#622]
## Background Information

I have a thinkpad E490 with a RTL8822be, wich obviously does not work. I used this repo for fixing the missing drivers of the wifi card since about kernel 5 with arch linux. A couple of weeks ago it stopped working, still with arch. I changed to manjaro for other reasons and still doesn't work.

### Currently, this is my kernel info:
`$ uname -a`

```
Linux manjaro 5.6.16-1-MANJARO #1 SMP PREEMPT Wed Jun 3 14:26:28 UTC 2020 x86_64 GNU/Linux
```

### These are the realtek devices in my machine:
`$ lspci | grep realtek`

```
02:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTS522A PCI Express Card Reader (rev 01)
04:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 10)
05:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTL8822BE 802.11a/b/g/n/ac WiFi adapter (rev ff)
07:00.0 Non-Volatile memory controller: Realtek Semiconductor Co., Ltd. Device 5762 (rev 01)
```

### Drivers after the rtlwifi_new:
`$ lsmod | grep rtw`

```
rtw_8822be             16384  0
rtw_8822b             229376  1 rtw_8822be
rtw_pci                28672  1 rtw_8822be
rtw_core              192512  2 rtw_8822b,rtw_pci
mac80211             1028096  2 rtw_core,rtw_pci
cfg80211              888832  2 rtw_core,mac80211
```

### lspci with highest verbosity for the RTL8822be returns this:
`# lspci -vvxxx`

```
05:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTL8822BE 802.11a/b/g/n/ac WiFi adapter (rev ff) (prog-if ff)
	!!! Unknown header type 7f
	Kernel driver in use: rtw_8822be
	Kernel modules: rtw_8822be
00: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
10: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
20: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
30: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
40: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
50: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
60: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
70: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
80: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
90: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
a0: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
b0: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
c0: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
d0: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
e0: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
f0: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
```

### After a network reboot, dmesg gives this error:
`# systemctl restart NetworkManager &&  dmesg | grep rtw`

```
[ 4510.285754] rtw_8822be 0000:05:00.0: failed to poll offset=0x5 mask=0x2 value=0x0
[ 4510.285766] rtw_8822be 0000:05:00.0: mac power on failed
```

After several research, I've found one workarround that fixes the wifi but blocks bluetooth. It can be found [here](https://www.reddit.com/r/archlinux/comments/exr82b/tried_55_from_testing_and_wifi_rtl8822be_stopped/fk9qfuo/). Still, I'm looking for a more elegant solution to my problem.

Am I missing something here? Or this is a real problem?

**Comment by rodrigomvf** [comment]
rtwpci conflicts with rtw_pci
Blacklist rtwpci

**Comment by rodrigomvf** [comment]
Dont blacklist this 
blacklist btrtl
blacklist btusb

**Comment by rodrigomvf** [comment]
For me just Blacklist rtwpci was enough

**Comment by leoperegrino** [comment]
But was I not suposed to see rtwpci in the output of lsmod if was using it?

**Comment by lwfinger** [comment]
If you have a kernel new enough that it contains rtw_pci, why are you using this repo?

**Comment by lwfinger** [comment]
If you have an ASPM problem, rtw_pci has an option that will disable ASPM support. That option has been submitted to wireless-testing, but not yet approved as module options are frowned upon.

**Comment by leoperegrino** [comment]
Yes, as stated in the comment on the link I posted, it seems that is a ASPM problem. 

But I'm not sure if I've understood you. Do you mean that the linux kernel or this repo that has not yet implemented the ASPM config? 

Am I able to fix with:

```
options rtw_pci aspm=0
```
at `/etc/modprobe.d/rtw_pci.conf` ?

**Comment by lwfinger** [comment]
The option is available here, but not (yet?) in the kernel. The correct line in the modprobe.d file would be
options rtw_pci disable_aspm=y

**Comment by leoperegrino** [comment]
Thank you very much for your help, the problem is finally solved. 
Closing the issue.
