### ISSUE TITLE
sudo make install not working

### ISSUE THREAD

**Issue by Haidar0096** [lwfinger/rtlwifi_new#623]
Hello I am not expert in linux command line commands
I was following [this](https://medium.com/@siddhesh.m/fix-no-wifi-adapter-found-for-hp-laptops-with-ubuntu-18-04-9ea509523841) article to set up the wifi adapter on ubuntu 18.04 on hp laptop (after each update to the system the wifi adapter breaks and I must do these steps again)

The steps are:

```
sudo apt-get install linux-headers-$(uname -r) build-essential git
git clone https://github.com/lwfinger/rtlwifi_new.git
cd rtlwifi_new/ && git checkout origin/extended -b extended
sudo make install
sudo modprobe -r rtl8723de
sudo modprobe rtl8723de
sudo modprobe -r rtl8723de && sleep 5 && sudo modprobe rtl8723de ant_sel=2
echo "options rtl8723de ant_sel=2" | sudo tee /etc/modprobe.d/rtl8723de.conf
```

This used to work before (I used to do it every time I upgraded the system and it works, it brings back the wifi adapter after it breaks)

But I don't know why this time it is not working.

```
sudo apt-get install linux-headers-$(uname -r) build-essential git
git clone https://github.com/lwfinger/rtlwifi_new.git
cd rtlwifi_new/ && git checkout origin/extended -b extended
```
These 3 commands are working, but when I write
`sudo make install`
I get
`make: *** No rule to make target 'install'.  Stop.`

Please help me ?

**Comment by lwfinger** [comment]
Look at README.md. Beginning on June 1, I abandoned the extended branch as I got tired of answering the same questions over and over.  If you followed the rule of 'make && sudo make install' the way you should have, you would have seen a more definitive error message.

The RTL8723DE driver is now in the rtw88 branch of this repo.

**Comment by Haidar0096** [comment]
I know that it is rtw88 branch
And I looked at reame before you tell me, and followed it step by step but didn't work
Anyway [this](https://askubuntu.com/a/1235988/1014105) asnwer on Stackoverflow solved the problem

Thanks for NOT being patient and NOT helpful for a BEGGINER like me :(

**Comment by Haidar0096** [comment]
> I know that it is rtw88 branch
> And I looked at reame before you tell me, and followed it step by step but didn't work
> Anyway [this](https://askubuntu.com/a/1235988/1014105) asnwer on Stackoverflow solved the problem
> 
> Thanks for NOT being patient and NOT helpful for a BEGGINER like me :(



> Look at README.md. Beginning on June 1, I abandoned the extended branch as I got tired of answering the same questions over and over. If you followed the rule of 'make && sudo make install' the way you should have, you would have seen a more definitive error message.
> 
> The RTL8723DE driver is now in the rtw88 branch of this repo.

I know that it is rtw88 branch
And I looked at reame before you tell me, and followed it step by step but didn't work
Anyway this asnwer on Stackoverflow solved the problem

Thanks for NOT being patient and NOT helpful for a BEGGINER like me :(

**Comment by lwfinger** [comment]
If you had gotten roughly 40 e-mails per day asking the same stupid question, you would not be patient either.

If you are getting the "make: *** No rule to make target 'install'. Stop. message, then your installation  is not complete. Do the following in a terminal:
rm -rf rtlwifi_new
git clone http://github.com/rtlwifi_new.git -b rtw88
cd rtlwifi_new
make
sudo make install

Once you complete those commands, you will have the source downloaded. If you get an error in the 'make' step, it will likely be that the kernel modules are not installed.

I'm sorry if I was a bit impatient, but I am regretting the day I ever opened a GitHub repo. I'm 80 years old, and I'm not sure I want to spend what is left of my life doing this!!!!!!!!!

**Comment by Haidar0096** [comment]
> If you had gotten roughly 40 e-mails per day asking the same stupid question, you would not be patient either.
> 
> If you are getting the "make: *** No rule to make target 'install'. Stop. message, then your installation is not complete. Do the following in a terminal:
> rm -rf rtlwifi_new
> git clone [http://github.com/rtlwifi_new.git](https://github.com/rtlwifi_new.git) -b rtw88
> cd rtlwifi_new
> make
> sudo make install
> 
> Once you complete those commands, you will have the source downloaded. If you get an error in the 'make' step, it will likely be that the kernel modules are not installed.
> 
> I'm sorry if I was a bit impatient, but I am regretting the day I ever opened a GitHub repo. I'm 80 years old, and I'm not sure I want to spend what is left of my life doing this!!!!!!!!!

All respect to you Sir, and I am very sorry for being offensive <3
