### ISSUE TITLE
RTL8723BE module for ubuntu 20.04

### ISSUE THREAD

**Issue by VarunRaje** [lwfinger/rtlwifi_new#627]
I recently update my laptop from 18.04 to 20.04. and range of my wifi is turns very low. it was working fine with 18.04. I check rtl88 branch for module but I have not found module for RTL8723BE.

**Comment by lwfinger** [comment]
Nor will you. For RTL8723BE, you MUST use the drivers in the kernel. You probably lost an ant_sel setting.

**Comment by jastisriradheshyam** [comment]
As **Ubuntu 20.04** has **kernel 5.4**, it already contains driver for RTL8723BE. So, as lwfinger suggested ant_sel setting may be a problem.

- My current setting as follows:
`options rtl8723be ant_sel=0 ips=0 fwlps=0 aspm=0 disable_watchdog=1`

- If you want similar configuration run the command given below and restart your system.
```sh
sudo echo "options rtl8723be ant_sel=0 ips=0 fwlps=0 aspm=0 disable_watchdog=1" | sudo tee /etc/modprobe.d/rtl8723be.conf > /dev/null
```

- If above setting still does not solve the problem try to tune the setting in `/etc/modprobe.d/rtl8723be.conf` and run :
```
sudo modprobe -r rtl8723be
sudo modprobe rtl8723be
```

References:
- [rtl8723be options · lwfinger/rtlwifi_new Wiki](https://github.com/lwfinger/rtlwifi_new/wiki/rtl8723be-options)
- [How to choose ant_sel for weak signal? · lwfinger/rtlwifi_new Wiki](https://github.com/lwfinger/rtlwifi_new/wiki/How-to-choose-ant_sel-for-weak-signal%3F)

**Comment by VarunRaje** [comment]
Thanks @jastisriradheshyam

It works with your command.  

@lwfinger Thanks, for your suggestion.
