### ISSUE TITLE
wifi strength unstable 

### ISSUE THREAD

**Issue by thor8911** [lwfinger/rtlwifi_new#629]
seem this driver make my wifi strength unstable compare to previous driver. The signal sometime become full bar and suddenly drop to the lowest bar. and sometimes disconnected by itself. Any method to strengthening the signal?

**Comment by lwfinger** [comment]
Pleasee reread your posting and tell me how I am supposed to know what you are talking about!

**Comment by thor8911** [comment]
Oh,After i install this driver, my wifi signal become unstable and disconnected. My hardware is rtl8821ce.

**Comment by lwfinger** [comment]
Read and follow the last paragraph of README.md. For your kind of problem, you need the experts, which I am not.
