### ISSUE TITLE
rtl8192ee wifi problem

### ISSUE THREAD

**Issue by JoeyAndres** [lwfinger/rtlwifi_new#63]
I have a kernel 4.1.2-2 in Fedora 23 OS. I currently have problems with my rtl8192ee (been a problem ever since I installed linux). Anway the following are what is going on and the corresponding log from dmesg.

1. Enabling wifi from disabled state:

[ 8748.730291] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
[ 8873.755667] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
[ 8873.767630] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready

2. Attempting to connect:

[ 9099.920485] wlp2s0: authenticate with b8:9b:c9:d5:4e:c1
[ 9099.937422] wlp2s0: direct probe to b8:9b:c9:d5:4e:c1 (try 1/3)
[ 9100.137952] wlp2s0: direct probe to b8:9b:c9:d5:4e:c1 (try 2/3)
[ 9100.339111] wlp2s0: direct probe to b8:9b:c9:d5:4e:c1 (try 3/3)
[ 9100.540327] wlp2s0: authentication with b8:9b:c9:d5:4e:c1 timed out
[ 9111.414955] wlp2s0: authenticate with b8:9b:c9:d5:4e:c1
[ 9111.431850] wlp2s0: direct probe to b8:9b:c9:d5:4e:c1 (try 1/3)
[ 9111.632450] wlp2s0: direct probe to b8:9b:c9:d5:4e:c1 (try 2/3)
[ 9111.833677] wlp2s0: direct probe to b8:9b:c9:d5:4e:c1 (try 3/3)
[ 9112.034877] wlp2s0: authentication with b8:9b:c9:d5:4e:c1 timed out

... (goes on)

if you need anymore logs, pls tell me where to get them and I will gladly provide you with it.

**Comment by lwfinger** [comment]
Always say what branch you are using for repos with multiple branches. If you are using the driver from the kernel, then why have you posted here?

**Comment by JoeyAndres** [comment]
@lwfinger Sorry, I used the master of rtlwifi_new. I just mentioned the kernel maybe its relevant.

**Comment by lwfinger** [comment]
I had not tested the RTL8192EE for a while. Using the master branch with kernel 4.2-rc4, I get the following:

[   13.856120] Using firmware rtlwifi/rtl8192eefw_new.bin
[   13.896633] ieee80211 phy0: Selected rate control algorithm 'rtl_rc'
[   13.901272] rtlwifi: wireless switch is on
[   13.910922] rtl8192ee 0000:02:00.0 wlp2s0: renamed from wlan0
[   38.582186] wlp2s0: authenticate with 00:1a:70:46:ba:b1
[   38.616346] wlp2s0: send auth to 00:1a:70:46:ba:b1 (try 1/3)
[   38.618548] wlp2s0: authenticated
[   38.618936] rtl8192ee 0000:02:00.0 wlp2s0: disabling HT/VHT due to WEP/TKIP use
[   38.619209] wlp2s0: associate with 00:1a:70:46:ba:b1 (try 1/3)
[   38.624315] wlp2s0: RX AssocResp from 00:1a:70:46:ba:b1 (capab=0x411 status=0 aid=1)
[   38.635916] wlp2s0: associated

Above was for WPA1.  Switching to WPA2, the new log info is

[  379.527074] wlp2s0: deauthenticating from 00:1a:70:46:ba:b1 by local choice (Reason: 3=DEAUTH_LEAVING)
[  379.528254] rtlwifi:rtl_cam_del_entry():<0-0> cam_bitmap: 0x4
[  379.547331] rtlwifi:rtl_cam_del_entry():<0-0> cam_bitmap: 0x0
[  379.557795] cfg80211: World regulatory domain updated:
[  379.557798] cfg80211:  DFS Master region: unset
[  380.417818] wlp2s0: authenticate with d8:eb:97:ec:75:8c
[  380.435390] wlp2s0: send auth to d8:eb:97:ec:75:8c (try 1/3)
[  380.438461] wlp2s0: authenticated
[  380.439114] wlp2s0: associate with d8:eb:97:ec:75:8c (try 1/3)
[  380.442920] wlp2s0: RX AssocResp from d8:eb:97:ec:75:8c (capab=0x411 status=0 aid=1)
[  380.454382] wlp2s0: associated

Again it associated on the first try.

I am using NetworkManager from an openSUSE 13.2 installation. Note that neither of my connections mention anything about a "direct probe". Are you trying a P2P or Ad-Hoc connection?

**Comment by JoeyAndres** [comment]
1. At startup:

[   32.193765] rtl8192ee: Using firmware rtlwifi/rtl8192eefw.bin
[   32.199541] ieee80211 phy0: Selected rate control algorithm 'rtl_rc'
[   32.199703] rtlwifi: rtlwifi: wireless switch is on
[   32.251126] rtl8192ee 0000:02:00.0 wlp2s0: renamed from wlan0
[   32.290900] cfg80211: Calling CRDA to update world regulatory domain
[   32.298592] cfg80211: World regulatory domain updated:
[   32.298595] cfg80211:  DFS Master region: unset
[   32.298596] cfg80211:   (start_freq - end_freq @ bandwidth), (max_antenna_gain, max_eirp), (dfs_cac_time)
[   32.298598] cfg80211:   (2402000 KHz - 2472000 KHz @ 40000 KHz), (N/A, 2000 mBm), (N/A)
[   32.298599] cfg80211:   (2457000 KHz - 2482000 KHz @ 40000 KHz), (N/A, 2000 mBm), (N/A)
[   32.298600] cfg80211:   (2474000 KHz - 2494000 KHz @ 20000 KHz), (N/A, 2000 mBm), (N/A)
[   32.298602] cfg80211:   (5170000 KHz - 5250000 KHz @ 80000 KHz, 160000 KHz AUTO), (N/A, 2000 mBm), (N/A)
[   32.298603] cfg80211:   (5250000 KHz - 5330000 KHz @ 80000 KHz, 160000 KHz AUTO), (N/A, 2000 mBm), (0 s)
[   32.298604] cfg80211:   (5490000 KHz - 5730000 KHz @ 160000 KHz), (N/A, 2000 mBm), (0 s)
[   32.298605] cfg80211:   (5735000 KHz - 5835000 KHz @ 80000 KHz), (N/A, 2000 mBm), (N/A)
[   32.298606] cfg80211:   (57240000 KHz - 63720000 KHz @ 2160000 KHz), (N/A, 0 mBm), (N/A)
[   32.298614] cfg80211: Calling CRDA for country: CA
[   32.302397] cfg80211: Regulatory domain changed to country: CA
[   32.302401] cfg80211:  DFS Master region: FCC
[   32.302402] cfg80211:   (start_freq - end_freq @ bandwidth), (max_antenna_gain, max_eirp), (dfs_cac_time)
[   32.302405] cfg80211:   (2402000 KHz - 2472000 KHz @ 40000 KHz), (N/A, 3000 mBm), (N/A)
[   32.302407] cfg80211:   (5170000 KHz - 5250000 KHz @ 80000 KHz, 160000 KHz AUTO), (N/A, 1700 mBm), (N/A)
[   32.302410] cfg80211:   (5250000 KHz - 5330000 KHz @ 80000 KHz, 160000 KHz AUTO), (N/A, 2400 mBm), (0 s)
[   32.302412] cfg80211:   (5490000 KHz - 5730000 KHz @ 160000 KHz), (N/A, 2400 mBm), (0 s)
[   32.302414] cfg80211:   (5735000 KHz - 5835000 KHz @ 80000 KHz), (N/A, 3000 mBm), (N/A)
[   32.302738] snd_hda_intel 0000:00:03.0: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[   32.356363] Adding 8191996k swap on /dev/mapper/fedora-swap.  Priority:-1 extents:1 across:8191996k SSFS
[   32.371461] input: HDA Intel HDMI HDMI/DP,pcm=3 as /devices/pci0000:00/0000:00:03.0/sound/card0/input10
[   32.371627] input: HDA Intel HDMI HDMI/DP,pcm=7 as /devices/pci0000:00/0000:00:03.0/sound/card0/input11
[   32.371895] input: HDA Intel HDMI HDMI/DP,pcm=8 as /devices/pci0000:00/0000:00:03.0/sound/card0/input12
[   32.376541] snd_hda_codec_realtek hdaudioC1D0: autoconfig for ALC3232: line_outs=1 (0x14/0x0/0x0/0x0/0x0) type:speaker
[   32.376544] snd_hda_codec_realtek hdaudioC1D0:    speaker_outs=0 (0x0/0x0/0x0/0x0/0x0)
[   32.376545] snd_hda_codec_realtek hdaudioC1D0:    hp_outs=2 (0x16/0x15/0x0/0x0/0x0)
[   32.376546] snd_hda_codec_realtek hdaudioC1D0:    mono: mono_out=0x0
[   32.376547] snd_hda_codec_realtek hdaudioC1D0:    inputs:
[   32.376549] snd_hda_codec_realtek hdaudioC1D0:      Dock Mic=0x19
[   32.376550] snd_hda_codec_realtek hdaudioC1D0:      Mic=0x1a
[   32.376551] snd_hda_codec_realtek hdaudioC1D0:      Internal Mic=0x12
[   32.383381] media: Linux media interface: v0.10
[   32.388537] input: HDA Intel PCH Dock Mic as /devices/pci0000:00/0000:00:1b.0/sound/card1/input13
[   32.388646] input: HDA Intel PCH Mic as /devices/pci0000:00/0000:00:1b.0/sound/card1/input14
[   32.388732] input: HDA Intel PCH Dock Headphone as /devices/pci0000:00/0000:00:1b.0/sound/card1/input15
[   32.388815] input: HDA Intel PCH Headphone as /devices/pci0000:00/0000:00:1b.0/sound/card1/input16
[   32.409305] Linux video capture interface: v2.00
[   32.422895] Bluetooth: Core ver 2.20
[   32.422911] NET: Registered protocol family 31
[   32.422913] Bluetooth: HCI device and connection manager initialized
[   32.422917] Bluetooth: HCI socket layer initialized
[   32.422919] Bluetooth: L2CAP socket layer initialized
[   32.422925] Bluetooth: SCO socket layer initialized
[   32.444349] usbcore: registered new interface driver btusb
[   32.445362] uvcvideo: Found UVC 1.00 device Integrated Camera (5986:0397)
[   32.445537] Bluetooth: hci0: rtl: examining hci_ver=06 hci_rev=000a lmp_ver=06 lmp_subver=8761
[   32.445540] Bluetooth: hci0: rtl: loading rtl_bt/rtl8761a_fw.bin
[   32.446185] input: Integrated Camera as /devices/pci0000:00/0000:00:14.0/usb1/1-12/1-12:1.0/input/input17
[   32.446277] usbcore: registered new interface driver uvcvideo
[   32.446279] USB Video Class driver (1.1.1)
[   32.452265] vboxguest: PCI device not found, probably running on physical hardware.
[   32.457578] Bluetooth: hci0: rom_version status=0 version=2
[   32.480478] vboxguest: PCI device not found, probably running on physical hardware.
[   32.482007] EXT4-fs (dm-3): mounted filesystem with ordered data mode. Opts: (null)
[   32.484163] EXT4-fs (sda2): mounted filesystem with ordered data mode. Opts: (null)
[   32.510514] FAT-fs (sda1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
[   33.132211] vboxdrv: Found 8 processor cores.
[   33.132680] vboxdrv: fAsync=0 offMin=0xcd offMax=0x10ee
[   33.132739] vboxdrv: TSC mode is 'synchronous', kernel timer mode is 'normal'.
[   33.132740] vboxdrv: Successfully loaded version 4.3.30_RPMFusion (interface 0x001a000a).
[   33.327870] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   33.327872] Bluetooth: BNEP filters: protocol multicast
[   33.327875] Bluetooth: BNEP socket layer initialized
[   33.768655] vboxpci: IOMMU not found (not registered)
[   33.917793] nf_conntrack version 0.5.0 (65536 buckets, 262144 max)
[   33.934431] ip6_tables: (C) 2000-2006 Netfilter Core Team
[   33.998609] Ebtables v2.0 registered
[   34.011154] bridge: automatic filtering via arp/ip/ip6tables has been deprecated. Update your scripts to load br_netfilter if you need this.
[   34.303603] IPv6: ADDRCONF(NETDEV_UP): enp0s25: link is not ready
[   34.495661] IPv6: ADDRCONF(NETDEV_UP): enp0s25: link is not ready
[   34.498940] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
[   34.510575] loop: module loaded
[   35.267188] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
[   35.433975] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
[   35.522173] Bridge firewalling registered
[   36.465128] tun: Universal TUN/TAP device driver, 1.6
[   36.465130] tun: (C) 1999-2004 Max Krasnyansky <maxk@qualcomm.com>
[   36.489585] device virbr0-nic entered promiscuous mode
[   36.650999] virbr0: port 1(virbr0-nic) entered listening state
[   36.651013] virbr0: port 1(virbr0-nic) entered listening state
[   36.751992] virbr0: port 1(virbr0-nic) entered disabled state
[   37.074176] e1000e: enp0s25 NIC Link is Up 100 Mbps Full Duplex, Flow Control: Rx/Tx
[   37.074181] e1000e 0000:00:19.0 enp0s25: 10/100 speed: disabling TSO
[   37.074219] IPv6: ADDRCONF(NETDEV_CHANGE): enp0s25: link becomes ready
[   42.328225] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
[   45.066730] Bluetooth: RFCOMM TTY layer initialized
[   45.066736] Bluetooth: RFCOMM socket layer initialized
[   45.066818] Bluetooth: RFCOMM ver 1.11
[   55.249950] wlp2s0: authenticate with b8:9b:c9:d5:4e:c1
[   55.283285] wlp2s0: send auth to b8:9b:c9:d5:4e:c1 (try 1/3)
[   55.383988] wlp2s0: send auth to b8:9b:c9:d5:4e:c1 (try 2/3)
[   55.456556] wlp2s0: authenticated
[   55.457074] wlp2s0: associate with b8:9b:c9:d5:4e:c1 (try 1/3)
[   55.476751] wlp2s0: RX AssocResp from b8:9b:c9:d5:4e:c1 (capab=0xc11 status=0 aid=2)
[   55.487491] wlp2s0: associated
[   55.487505] IPv6: ADDRCONF(NETDEV_CHANGE): wlp2s0: link becomes ready
[   55.488391] cfg80211: Calling CRDA for country: US
[   55.497830] cfg80211: Regulatory domain changed to country: US
[   55.497834] cfg80211:  DFS Master region: FCC
[   55.497835] cfg80211:   (start_freq - end_freq @ bandwidth), (max_antenna_gain, max_eirp), (dfs_cac_time)
[   55.497838] cfg80211:   (2402000 KHz - 2472000 KHz @ 40000 KHz), (N/A, 3000 mBm), (N/A)
[   55.497840] cfg80211:   (5170000 KHz - 5250000 KHz @ 80000 KHz, 160000 KHz AUTO), (N/A, 1700 mBm), (N/A)
[   55.497842] cfg80211:   (5250000 KHz - 5330000 KHz @ 80000 KHz, 160000 KHz AUTO), (N/A, 2300 mBm), (0 s)
[   55.497844] cfg80211:   (5490000 KHz - 5730000 KHz @ 160000 KHz), (N/A, 2300 mBm), (0 s)
[   55.497846] cfg80211:   (5735000 KHz - 5835000 KHz @ 80000 KHz), (N/A, 3000 mBm), (N/A)
[   55.497847] cfg80211:   (57240000 KHz - 63720000 KHz @ 2160000 KHz), (N/A, 4000 mBm), (N/A)

2. At this point: I am connected to the network (but slow).

3. After watching some videos off youtube the wireless disconnected and asked for password:

[  805.609722] wlp2s0: Connection to AP b8:9b:c9:d5:4e:c1 lost
[  805.657948] cfg80211: Calling CRDA to update world regulatory domain
[  805.661296] cfg80211: World regulatory domain updated:
[  805.661299] cfg80211:  DFS Master region: unset
[  805.661300] cfg80211:   (start_freq - end_freq @ bandwidth), (max_antenna_gain, max_eirp), (dfs_cac_time)
[  805.661302] cfg80211:   (2402000 KHz - 2472000 KHz @ 40000 KHz), (N/A, 2000 mBm), (N/A)
[  805.661303] cfg80211:   (2457000 KHz - 2482000 KHz @ 40000 KHz), (N/A, 2000 mBm), (N/A)
[  805.661304] cfg80211:   (2474000 KHz - 2494000 KHz @ 20000 KHz), (N/A, 2000 mBm), (N/A)
[  805.661305] cfg80211:   (5170000 KHz - 5250000 KHz @ 80000 KHz, 160000 KHz AUTO), (N/A, 2000 mBm), (N/A)
[  805.661306] cfg80211:   (5250000 KHz - 5330000 KHz @ 80000 KHz, 160000 KHz AUTO), (N/A, 2000 mBm), (0 s)
[  805.661307] cfg80211:   (5490000 KHz - 5730000 KHz @ 160000 KHz), (N/A, 2000 mBm), (0 s)
[  805.661308] cfg80211:   (5735000 KHz - 5835000 KHz @ 80000 KHz), (N/A, 2000 mBm), (N/A)
[  805.661309] cfg80211:   (57240000 KHz - 63720000 KHz @ 2160000 KHz), (N/A, 0 mBm), (N/A)
[  805.661321] cfg80211: Calling CRDA for country: CA
[  805.663275] cfg80211: Regulatory domain changed to country: CA
[  805.663277] cfg80211:  DFS Master region: FCC
[  805.663278] cfg80211:   (start_freq - end_freq @ bandwidth), (max_antenna_gain, max_eirp), (dfs_cac_time)
[  805.663279] cfg80211:   (2402000 KHz - 2472000 KHz @ 40000 KHz), (N/A, 3000 mBm), (N/A)
[  805.663281] cfg80211:   (5170000 KHz - 5250000 KHz @ 80000 KHz, 160000 KHz AUTO), (N/A, 1700 mBm), (N/A)
[  805.663282] cfg80211:   (5250000 KHz - 5330000 KHz @ 80000 KHz, 160000 KHz AUTO), (N/A, 2400 mBm), (0 s)
[  805.663283] cfg80211:   (5490000 KHz - 5730000 KHz @ 160000 KHz), (N/A, 2400 mBm), (0 s)
[  805.663284] cfg80211:   (5735000 KHz - 5835000 KHz @ 80000 KHz), (N/A, 3000 mBm), (N/A)
[  806.590528] wlp2s0: authenticate with b8:9b:c9:d5:4e:c1
[  806.607655] wlp2s0: send auth to b8:9b:c9:d5:4e:c1 (try 1/3)
[  806.708726] wlp2s0: send auth to b8:9b:c9:d5:4e:c1 (try 2/3)
[  806.809815] wlp2s0: send auth to b8:9b:c9:d5:4e:c1 (try 3/3)
[  806.910947] wlp2s0: authentication with b8:9b:c9:d5:4e:c1 timed out
[  808.270428] wlp2s0: authenticate with b8:9b:c9:d5:4e:c1
[  808.287340] wlp2s0: send auth to b8:9b:c9:d5:4e:c1 (try 1/3)
[  808.388405] wlp2s0: send auth to b8:9b:c9:d5:4e:c1 (try 2/3)
[  808.392184] wlp2s0: authenticated
[  808.392406] wlp2s0: associate with b8:9b:c9:d5:4e:c1 (try 1/3)
[  808.465598] wlp2s0: RX AssocResp from b8:9b:c9:d5:4e:c1 (capab=0xc11 status=0 aid=2)
[  808.476224] wlp2s0: associated
[  808.476301] cfg80211: Calling CRDA for country: US
[  808.477880] cfg80211: Regulatory domain changed to country: US
[  808.477882] cfg80211:  DFS Master region: FCC
[  808.477884] cfg80211:   (start_freq - end_freq @ bandwidth), (max_antenna_gain, max_eirp), (dfs_cac_time)
[  808.477885] cfg80211:   (2402000 KHz - 2472000 KHz @ 40000 KHz), (N/A, 3000 mBm), (N/A)
[  808.477887] cfg80211:   (5170000 KHz - 5250000 KHz @ 80000 KHz, 160000 KHz AUTO), (N/A, 1700 mBm), (N/A)
[  808.477888] cfg80211:   (5250000 KHz - 5330000 KHz @ 80000 KHz, 160000 KHz AUTO), (N/A, 2300 mBm), (0 s)
[  808.477889] cfg80211:   (5490000 KHz - 5730000 KHz @ 160000 KHz), (N/A, 2300 mBm), (0 s)
[  808.477890] cfg80211:   (5735000 KHz - 5835000 KHz @ 80000 KHz), (N/A, 3000 mBm), (N/A)
[  808.477891] cfg80211:   (57240000 KHz - 63720000 KHz @ 2160000 KHz), (N/A, 4000 mBm), (N/A)
[  814.689944] wlp2s0: deauthenticated from b8:9b:c9:d5:4e:c1 (Reason: 15=4WAY_HANDSHAKE_TIMEOUT)
[  814.716079] cfg80211: Calling CRDA to update world regulatory domain
[  814.717980] cfg80211: World regulatory domain updated:
[  814.717983] cfg80211:  DFS Master region: unset
[  814.717984] cfg80211:   (start_freq - end_freq @ bandwidth), (max_antenna_gain, max_eirp), (dfs_cac_time)
[  814.717986] cfg80211:   (2402000 KHz - 2472000 KHz @ 40000 KHz), (N/A, 2000 mBm), (N/A)
[  814.717987] cfg80211:   (2457000 KHz - 2482000 KHz @ 40000 KHz), (N/A, 2000 mBm), (N/A)
[  814.717988] cfg80211:   (2474000 KHz - 2494000 KHz @ 20000 KHz), (N/A, 2000 mBm), (N/A)
[  814.717990] cfg80211:   (5170000 KHz - 5250000 KHz @ 80000 KHz, 160000 KHz AUTO), (N/A, 2000 mBm), (N/A)
[  814.717991] cfg80211:   (5250000 KHz - 5330000 KHz @ 80000 KHz, 160000 KHz AUTO), (N/A, 2000 mBm), (0 s)
[  814.717993] cfg80211:   (5490000 KHz - 5730000 KHz @ 160000 KHz), (N/A, 2000 mBm), (0 s)
[  814.717994] cfg80211:   (5735000 KHz - 5835000 KHz @ 80000 KHz), (N/A, 2000 mBm), (N/A)
[  814.717995] cfg80211:   (57240000 KHz - 63720000 KHz @ 2160000 KHz), (N/A, 0 mBm), (N/A)
[  814.718124] cfg80211: Calling CRDA for country: CA
[  814.719682] cfg80211: Regulatory domain changed to country: CA
[  814.719685] cfg80211:  DFS Master region: FCC
[  814.719686] cfg80211:   (start_freq - end_freq @ bandwidth), (max_antenna_gain, max_eirp), (dfs_cac_time)
[  814.719688] cfg80211:   (2402000 KHz - 2472000 KHz @ 40000 KHz), (N/A, 3000 mBm), (N/A)
[  814.719690] cfg80211:   (5170000 KHz - 5250000 KHz @ 80000 KHz, 160000 KHz AUTO), (N/A, 1700 mBm), (N/A)
[  814.719692] cfg80211:   (5250000 KHz - 5330000 KHz @ 80000 KHz, 160000 KHz AUTO), (N/A, 2400 mBm), (0 s)
[  814.719693] cfg80211:   (5490000 KHz - 5730000 KHz @ 160000 KHz), (N/A, 2400 mBm), (0 s)
[  814.719695] cfg80211:   (5735000 KHz - 5835000 KHz @ 80000 KHz), (N/A, 3000 mBm), (N/A)

**Comment by JoeyAndres** [comment]
Another Instance:

1. **Startup**

 19.151515] Using firmware rtlwifi/rtl8192eefw_new.bin
[   19.156561] ieee80211 phy0: Selected rate control algorithm 'rtl_rc'
[   19.156778] rtlwifi: wireless switch is on
[   19.171236] rtl8192ee 0000:02:00.0 wlp2s0: renamed from wlan0
[   19.191738] cfg80211: Calling CRDA for country: CA
[   19.193226] cfg80211: Regulatory domain changed to country: CA
[   19.193228] cfg80211:  DFS Master region: FCC
[   19.193230] cfg80211:   (start_freq - end_freq @ bandwidth), (max_antenna_gain, max_eirp), (dfs_cac_time)
[   19.193232] cfg80211:   (2402000 KHz - 2472000 KHz @ 40000 KHz), (N/A, 3000 mBm), (N/A)
[   19.193233] cfg80211:   (5170000 KHz - 5250000 KHz @ 80000 KHz, 160000 KHz AUTO), (N/A, 1700 mBm), (N/A)
[   19.193235] cfg80211:   (5250000 KHz - 5330000 KHz @ 80000 KHz, 160000 KHz AUTO), (N/A, 2400 mBm), (0 s)
[   19.193236] cfg80211:   (5490000 KHz - 5730000 KHz @ 160000 KHz), (N/A, 2400 mBm), (0 s)
[   19.193237] cfg80211:   (5735000 KHz - 5835000 KHz @ 80000 KHz), (N/A, 3000 mBm), (N/A)
[   19.532589] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   19.532591] Bluetooth: BNEP filters: protocol multicast
[   19.532595] Bluetooth: BNEP socket layer initialized
[   19.715699] vboxdrv: Found 8 processor cores.
[   19.716201] vboxdrv: fAsync=0 offMin=0xc8 offMax=0x5d1c
[   19.716257] vboxdrv: TSC mode is 'synchronous', kernel timer mode is 'normal'.
[   19.716258] vboxdrv: Successfully loaded version 4.3.30_RPMFusion (interface 0x001a000a).
[   20.103033] vboxpci: IOMMU not found (not registered)
[   20.188420] nf_conntrack version 0.5.0 (65536 buckets, 262144 max)
[   20.349517] ip6_tables: (C) 2000-2006 Netfilter Core Team
[   20.513136] Ebtables v2.0 registered
[   20.533332] bridge: automatic filtering via arp/ip/ip6tables has been deprecated. Update your scripts to load br_netfilter if you need this.
[   20.691433] IPv6: ADDRCONF(NETDEV_UP): enp0s25: link is not ready
[   20.889171] IPv6: ADDRCONF(NETDEV_UP): enp0s25: link is not ready
[   20.890527] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
[   20.900110] loop: module loaded
[   21.710169] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
[   21.786773] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
[   21.885027] Bridge firewalling registered
[   23.405565] e1000e: enp0s25 NIC Link is Up 100 Mbps Full Duplex, Flow Control: Rx/Tx
[   23.405569] e1000e 0000:00:19.0 enp0s25: 10/100 speed: disabling TSO
[   23.405604] IPv6: ADDRCONF(NETDEV_CHANGE): enp0s25: link becomes ready
[   23.570718] tun: Universal TUN/TAP device driver, 1.6
[   23.570721] tun: (C) 1999-2004 Max Krasnyansky <maxk@qualcomm.com>
[   23.641629] device virbr0-nic entered promiscuous mode
[   23.747748] virbr0: port 1(virbr0-nic) entered listening state
[   23.747759] virbr0: port 1(virbr0-nic) entered listening state
[   23.785765] virbr0: port 1(virbr0-nic) entered disabled state
[   27.424107] IPv6: ADDRCONF(NETDEV_UP): wlp2s0: link is not ready
[   27.467305] systemd-journald[785]: File /var/log/journal/87a506eb220c4ddf9abd822b333446f2/user-1000.journal corrupted or uncleanly shut down, renaming and replacing.
[   28.789923] Adjusting tsc more than 11% (8692242 vs 8484482)
[   30.049672] Bluetooth: RFCOMM TTY layer initialized
[   30.049679] Bluetooth: RFCOMM socket layer initialized
[   30.049760] Bluetooth: RFCOMM ver 1.11
[   40.198895] wlp2s0: authenticate with b8:9b:c9:d5:4e:c1
[   40.231379] wlp2s0: send auth to b8:9b:c9:d5:4e:c1 (try 1/3)
[   40.233825] wlp2s0: authenticated
[   40.234662] wlp2s0: associate with b8:9b:c9:d5:4e:c1 (try 1/3)
[   40.251766] wlp2s0: RX AssocResp from b8:9b:c9:d5:4e:c1 (capab=0xc11 status=0 aid=2)
[   40.262368] wlp2s0: associated
[   40.262380] IPv6: ADDRCONF(NETDEV_CHANGE): wlp2s0: link becomes ready
[   40.263256] cfg80211: Calling CRDA for country: US
[   40.270955] cfg80211: Regulatory domain changed to country: US
[   40.270958] cfg80211:  DFS Master region: FCC
[   40.270960] cfg80211:   (start_freq - end_freq @ bandwidth), (max_antenna_gain, max_eirp), (dfs_cac_time)
[   40.270962] cfg80211:   (2402000 KHz - 2472000 KHz @ 40000 KHz), (N/A, 3000 mBm), (N/A)
[   40.270965] cfg80211:   (5170000 KHz - 5250000 KHz @ 80000 KHz, 160000 KHz AUTO), (N/A, 1700 mBm), (N/A)
[   40.270967] cfg80211:   (5250000 KHz - 5330000 KHz @ 80000 KHz, 160000 KHz AUTO), (N/A, 2300 mBm), (0 s)
[   40.270969] cfg80211:   (5490000 KHz - 5730000 KHz @ 160000 KHz), (N/A, 2300 mBm), (0 s)
[   40.270971] cfg80211:   (5735000 KHz - 5835000 KHz @ 80000 KHz), (N/A, 3000 mBm), (N/A)
[   40.270973] cfg80211:   (57240000 KHz - 63720000 KHz @ 2160000 KHz), (N/A, 4000 mBm), (N/A)
[   74.819733] input: FC:F1:52:EF:10:A2 as /devices/virtual/input/input18

2. Did some network related stuff, then loading pages becomes so slow and I mannually disconnect (it didn't disconnect by itself):

[  642.973205] wlp2s0: AP b8:9b:c9:d5:4e:c1 changed bandwidth, new config is 2462 MHz, width 1 (2462/0 MHz)
[  763.276412] wlp2s0: deauthenticating from b8:9b:c9:d5:4e:c1 by local choice (Reason: 3=DEAUTH_LEAVING)
[  763.277243] rtlwifi:rtl_cam_del_entry():<0-0> cam_bitmap: 0x4
[  763.295075] rtlwifi:rtl_cam_del_entry():<0-0> cam_bitmap: 0x0

**Comment by lwfinger** [comment]
I do not use P2P; however, your setup appears to work for a while at least.

I know nothing of the internals of the chips, thus I cannot help you with the slow speed and/or connection drops. There are two things to try: (1) load the module with the "ips=0" option. The easiest way to do that is with a .conf file in /etc/modprobe.d/, and (2) try the rock branch. Rock, a Realtek engineer, has pushed some new changes that have not yet been ported to any other code. They may help.

**Comment by JoeyAndres** [comment]
@lwfinger Thanks, I'll try those stuff and post my experience.

**Comment by JoeyAndres** [comment]
@lwfinger Thanks, that worked. And also big thanks to Rock.

# Instruction
I installed (1) and (2). I found instructions on how to do (1) in [here](http://askubuntu.com/questions/526214/how-to-set-parameters-for-realtek-wifi-rtl8723). The instructions is not be followed fully since it will lead to a crash thus, the following is my guess on how to amend it:

1. ```echo "options ips=0" > /etc/modprobe.d/rtl8192ee.conf```
2. ```sudo modprobe -r rtl8192ee```
3. ```sudo modprobe rtl8192ee && sudo reboot```

Without the sudo reboot, my computer freeze.

# Caveat
Another caveat. @lwfinger helped me solved the Bluetooth problem in this [issue](https://github.com/lwfinger/rtlwifi_new/issues/58). But connecting my Bluetooth headphone, the network speed drops, but disconnecting my headphone (not necessarily ```rmod btusb``` but simply disconnecting the bluetooth headphone).

The following occurs when I turn on my bluetooth headphone (merely the presence that it is detected interrupts the network):
```[ 1491.385967] input: FC:F1:52:EF:10:A2 as /devices/virtual/input/input19```
No log occurs when I disconnect bluetooth, but the network sure do return after a lot of retries.

At this point, although I am disappointed with the Bluetooth, I am satisfied since after 6 months, there's finally a solid solution. I'm sure Bluetooth problem will be amended in the future.

Without further ado thanks again.
