### ISSUE TITLE
WiFi driver is not working for kernel 5.2 for RTL8723BE

### ISSUE THREAD

**Issue by dranercom** [lwfinger/rtlwifi_new#630]
It said that the WiFi drivers comes with the kernel with version greater than 5.0. But when i upgraded to kernel 5.2 in Arch Linux, still the WiFi range is very low and connection drops frequently. I have been using rtlwifi drivers for RTL8723BE for years. Now the branch is abandoned, the support is completely lost for the new kernel versions. When i use the extended version to compile, it throws many errors. 

`make -C /lib/modules/5.7.6-arch1-1/build M=/home/cognicor/rtlwifi_new modules
make[1]: Entering directory '/usr/lib/modules/5.7.6-arch1-1/build'
  CC [M]  /home/cognicor/rtlwifi_new/base.o
In file included from /home/cognicor/rtlwifi_new/base.c:26:
/home/cognicor/rtlwifi_new/wifi.h:1601:2: error: unknown type name ‘__kernel_time_t’
 1601 |  __kernel_time_t last_suspend_sec;
`

`[cognicor@epsilon ~]$ gcc --version
gcc (GCC) 10.1.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[cognicor@epsilon ~]$ uname -r
5.7.6-arch1-1
[cognicor@epsilon ~]$ 
`
Can anyone help me with this.

**Comment by Lollixzc** [comment]
Did you read the [README](https://github.com/lwfinger/rtlwifi_new/blob/master/README.md)? You need to use the rtw88 branch if you want to continue using this paritcular driver

**Comment by lwfinger** [comment]
Not for the 8723BE. Use the one in the kernel. If the signal is weak, then you have the wrong ant_sel parameter. That has been covered so many times that I will never repeat it again. Yes, I am a crotchety old maqn!!

**Comment by dranercom** [comment]
I am so sorry. I did some research and couldn't get it to work. Changing ant_sel worked. Closing this issue.

**Comment by dranercom** [comment]
> Did you read the [README](https://github.com/lwfinger/rtlwifi_new/blob/master/README.md)? You need to use the rtw88 branch if you want to continue using this particular driver

That branch is not for rtl8723be

**Comment by Lollixzc** [comment]
Sometimes I am confused by the similar names of the Realtek chips, I need to pay more attention to the different letters and codes when someone asks help :laughing:
