### ISSUE TITLE
rtl8812ae: high ping under load (or randomly)

### ISSUE THREAD

**Issue by ocrete** [lwfinger/rtlwifi_new#631]
When using my rtl8812ae card on my desktop, I get regular high pings (and low performance), especially when loading the connection. A iwlwifi laptop right next to it has a perfect connection.

Playing around with the module parameters didn't help, but I noticed that `iwconfig` on the laptop reports rates in the 100-200 Mb/s range while the rtl card always says 866 Mb/s. So I tried forcing a max of 200Mb/s using `iwconfig wlp2s0 rate 200M auto` and it seems to improve the stability, so I'm suspecting that something is wrong with the rate control. Especially that if I force any rate, `iwconfig` reports  6 Mb/s (but it clearly goes faster than this.

Any hint on how I can help debug this would be great.

I have a RTL8812AE card (PCI ID 0x10ec:0x8203)
Loaded driver is rtl8821ae
I'm running kernel 5.6.19 with linux-firmware 20200619-109 (from Fedora 32)

**Comment by ocrete** [comment]
I should also mention that the same network card works perfectly in Windows, so it definitely seems like a driver bug

**Comment by yagoplx** [comment]
Try turning off ASPM in the BIOS and report back with results.

-------- Mensagem Original --------
Ativo 4 de jul de 2020 20:06, Olivier Crête escreveu:

**Comment by yagoplx** [comment]
If the issue persists please send an email to

linux-wireless@vger.kernel.org

concerning your problem.

The realtek devs will catch up with you - this github repo is just a code mirror.

-------- Mensagem Original --------
Ativo 4 de jul de 2020 20:06, Olivier Crête escreveu:
