### ISSUE TITLE
Wifi not working rtl_8723de for kernel 5.5.0

### ISSUE THREAD

**Issue by anish-mishr** [lwfinger/rtlwifi_new#633]
Wifi not working for my linux distro having kenerl 5.5.0 also linux headers are unable to locate 
i have tried all the solution availabe but problr=em remains same

make -C /lib/modules/5.5.0-kali2-amd64/build M=/home/kali/Downloads/rtlwifi_new modules
make[1]: *** /lib/modules/5.5.0-kali2-amd64/build: No such file or directory.  Stop.

**Comment by yagoplx** [comment]
Oh my god! How is this a problem for this driver to fix? If your WiFi doesn't work you need to install linux-firmware, and the problem will likely go away! and Linux headers if you want to build this out of tree driver. That's a problem with your distro, not us! I am ashamed of this generation of "hackers"' incompetence.

-------- Mensagem Original --------
Ativo 5 de jul de 2020 02:30, anish-mishr escreveu:

**Comment by lwfinger** [comment]
+1
