### ISSUE TITLE
Compile error on 4.1.6-1-ARCH

### ISSUE THREAD

**Issue by DiamondBond** [lwfinger/rtlwifi_new#65]
sorry if this isnt the place to post in, but idk where else to ask for help
heres the compile output:

diamond ~/.wifi master $ make
make -C /lib/modules/4.1.6-1-ARCH/build M=/home/diamond/.wifi modules
make[1]: Entering directory '/usr/lib/modules/4.1.6-1-ARCH/build'
make[1]: *** No rule to make target 'modules'.  Stop.
make[1]: Leaving directory '/usr/lib/modules/4.1.6-1-ARCH/build'
Makefile:53: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lwfinger** [comment]
You are missing the kernel header package, which is needed to build an out-of-kernel module. As I am not an ARCH user, I do not know what the package is named. A quick search for "ARCH Linux kernel headers" found https://bbs.archlinux.org/viewtopic.php?id=179918.

Just be sure that any kernel header package that you download matches *exactly* with the version given by the command "uname -r".

**Comment by DiamondBond** [comment]
thanks alot! :) linux-headers is the package, i thought i installed this and build-essentials ages ago, turns out i may have not, im sorry for opening a issue for such a silly thing though.
