### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by Kolip** [lwfinger/rtlwifi_new#66]
I have a compilation error that I cannot figure out. I am on OpenSuse 13.1 with desktop kernel 3.11+. Quick response appreciated. 

_**/rtlwifi_new/core.c:453:3: error: invalid use of undefined type ‘struct cfg80211_pkt_pattern’
   if (patterns[i].pattern_len > MAX_WOL_PATTERN_SIZE) {
   ^
*__/rtlwifi_new/core.c:453:15: error: dereferencing pointer to incomplete type
   if (patterns[i].pattern_len > MAX_WOL_PATTERN_SIZE) {
               ^
*__/rtlwifi_new/core.c:458:3: error: invalid use of undefined type ‘struct cfg80211_pkt_pattern’
   pattern_os = patterns[i].pattern;
   ^
*__/rtlwifi_new/core.c:458:24: error: dereferencing pointer to incomplete type
   pattern_os = patterns[i].pattern;
                        ^
*_*/rtlwifi_new/core.c:459:3: error: invalid use of undefined type ‘struct cfg80211_pkt_pattern’
   mask_len = DIV_ROUND_UP(patterns[i].pattern_len, 8);
   ^

**Comment by lwfinger** [comment]
It should work now. The fix had been applied to the troy and rock branches, but not to the master branch.

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
