### ISSUE TITLE
rtl8188ee Hard blocked

### ISSUE THREAD

**Issue by varlesh** [lwfinger/rtlwifi_new#67]
Please help. My friend have All-in-One PC DEXP.
I install Ubuntu 15.04 amd64, upgrade kernel to 4.2 and compiling and install driver for rtl8188ee.
But wireles card not enabled, because:
rfkill list
```
0: phy0: Wireless LAN
           Soft blocked: no
           Hard blocked: yes
```
rfkill unblock all - not working. BIOS not have settings for WLAN, keyboard not have Fn-key.
Please help.
It's possible enable card on module or any other variant on Linux?

**Comment by lwfinger** [comment]
If there is not an fn key for wireless, then your friend's machine has a physical switch. Sometimes, they can be hard to find.

No, it is not possible to override a hard block from the driver.

**Comment by varlesh** [comment]
Thanks for support.
