### ISSUE TITLE
Link is not working one-way only (mostly for MAC's and Iphones)

### ISSUE THREAD

**Issue by Sfinx** [lwfinger/rtlwifi_new#68]
Hello,

I'm using stock ubuntu server 15.x, rtlwifi_new and hostapd. Hostapd.conf is ::

```
interface=wlan0
country_code=GD
hw_mode=g
channel=3
ieee80211n=1
driver=nl80211
require_ht=0
require_vht=0
ht_capab=[HT40-][HT40+][SHORT-GI-40][DSSS_CCK-40]
ctrl_interface=/var/run/hostapd
ctrl_interface_group=0
macaddr_acl=0
ssid=xyz
ignore_broadcast_ssid=0
wpa_pairwise=CCMP
rsn_pairwise=CCMP
auth_algs=3
wpa=2
wpa_key_mgmt=WPA-PSK
wpa_passphrase=123456789
wmm_enabled=0
ieee8021x=0
eap_server=0
```

The problem is that no MAC's of IPhones can't connect to wifi - using tcpdump I see that link is one way at these devices (only RX is working from them, they just do not see any transmitting by the AP traffic). The syslog says endlessly something like ::

```
Sep 21 16:41:45 Gate hostapd: wlan0: STA xx:xx:xx:xx:6f:96 IEEE 802.11: associated (aid 6)
Sep 21 16:41:45 Gate hostapd: wlan0: STA xx:xx:xx:xx:6f:96 WPA: pairwise key handshake completed (RSN)
Sep 21 16:42:30 Gate hostapd: wlan0: STA xx:xx:xx:xx:6f:96 IEEE 802.11: disassociated
Sep 21 16:42:31 Gate hostapd: wlan0: STA xx:xx:xx:xx:6f:96 IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)

```

What can be the problem ? H/w is Edimax clone

```
01:00.0 Network controller [0280]: Realtek Semiconductor Co., Ltd. RTL8812AE 802.11ac PCIe Wireless Network Adapter [10ec:8812] (rev 01)
    Subsystem: Device [7392:d822]
    Flags: bus master, fast devsel, latency 0, IRQ 32
    I/O ports at e000 [size=256]
    Memory at f7b00000 (64-bit, non-prefetchable) [size=16K]
    Capabilities: [40] Power Management version 3
    Capabilities: [50] MSI: Enable+ Count=1/1 Maskable- 64bit+
    Capabilities: [70] Express Endpoint, MSI 00
    Capabilities: [100] Advanced Error Reporting
    Capabilities: [140] Device Serial Number xx-xx-xx-xx-xx-xx-xx-xx
    Capabilities: [150] Latency Tolerance Reporting
    Capabilities: [158] L1 PM Substates
    Kernel driver in use: rtl8821ae
```

How to debug this ?

**Comment by lwfinger** [comment]
Obviously there is an incompatibility between the hostapd and Apple wifi stacks. The syslog results make it look as it the encryption keys are not set correctly. As I have no iPhone to test, I cannot test here, but if I did, I would try the following:

1. Try loading rtl8821ae with the "swenc=1" option. That will pass the encryption to the kernel rather that trying to do it in the firmware.

2. Try to eliminate hostapd from the setup by using the mini-AP implementation found in NetworkManager.

3. Use wireshark on a 3rd computer to capture the "in the air" traffic between the hostapd-based AP and one of the iPhones.

4. If #3 is not possible, then use tcpdump to capture the data being received by hostapd to see if we can get more details than are

**Comment by Sfinx** [comment]
Its not incompatibility within the WiFi stacks but definitely lower level one - I've the installed Ubuntu at the same Air laptop and seeing just exact the same picture as with MacOS. The laptop seeing incoming traffic from AP (for example DHCP6 routing information) but AP do not see the traffic from laptop.  I will try  to load the driver with swenc=1 option tomorrow and report.

**Comment by Sfinx** [comment]
swenc=1 helps a little bit. I do not see the mass "deauthenticated due to inactivity" messages anymore. But the AP is still buggy like a hell. There are huge delays and packet loss during light-loaded network sessions. For example you can see (pic attached) the ping to windows machine from both sides :

![wifi_delays](https://cloud.githubusercontent.com/assets/1393676/10457106/6b227c84-71cd-11e5-837c-efc6189bf8b4.png)

What can be the problem ?

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
