### ISSUE TITLE
RTL8192EE Monitor mode issues

### ISSUE THREAD

**Issue by LogicParrot** [lwfinger/rtlwifi_new#7]
Monitor mode is not working as expected.
This was tested with Aircrack-ng.
Packet auditing (via airodump-ng)  misses almost all packets.
Packet injection works perfectly.

Hardware information:

> description: Wireless interface, Realtek 818b
> product: Realtek Semiconductor Co., Ltd. 
> width: 64 bits
> clock: 33MHz
> capabilities: pm msi pciexpress bus_master cap_list ethernet physical wireless
> configuration: broadcast=yes driver=rtl8192ee driverversion=3.2.0-4-amd64 firmware=N/A >latency=0 link=yes multicast=yes wireless=IEEE 802.11bgn
> resources: irq:44 ioport:3000(size=256) memory:f0400000-f0403fff

Here is a sample capture (Fake macs)

> BSSID              PWR  Beacons    #Data, #/s  CH  MB   ENC  CIPHER AUTH ESSID
> 
> AA:AA:AA:AA:AA:AP  -48      154    15077 2026  11  54 . WPA2 CCMP   PSK  Bob                      
> 
> BSSID              STATION            PWR   Rate    Lost    Frames  Probe                            
> 
> (not associated)   BB:BB:BB:BB:BB:BB  -51    0 - 1      0        6  Bob  
> AA:AA:AA:AA:AA:AP  ME:ME:ME:ME:ME:ME    0   54 -54      0    15071                                        

Note that it captured 15071 frames of my own browsing, yet 6 packets of BB's browing. (I was browsing with both computers).

There is a possibility that this is purely a hardware issue.

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
