### ISSUE TITLE
unable to mount pendrive

### ISSUE THREAD

**Issue by rkp600** [lwfinger/rtlwifi_new#71]
Error mounting /dev/sdc1 at /media/zincrokx/AVIKIVI: Command-line `mount -t "exfat" -o "uhelper=udisks2,nodev,nosuid,uid=1000,gid=1000,iocharset=utf8,namecase=0,errors=remount-ro,umask=0077" "/dev/sdc1" "/media/zincrokx/AVIKIVI"' exited with non-zero exit status 32: mount: unknown filesystem type 'exfat'

**Comment by lwfinger** [comment]
This is not a problem with rtlwifi_new. The error message says that "exfat" is wrong. You should probably use "vfat".
