### ISSUE TITLE
Error on Fedora 22

### ISSUE THREAD

**Issue by auriga1** [lwfinger/rtlwifi_new#72]
**Fedora 22**
_Kernel_: **4.1.10-200.fc22.x86_64**
_Netbook_: **Samsung Stream 13.3''**

`make`

`make -C /lib/modules/4.1.10-200.fc22.x86_64/build M=/home/silvio/Scaricati/wifi/rtlwifi_new-master modules
make[1]: *** /lib/modules/4.1.10-200.fc22.x86_64/build: File o directory non esistente.  Arresto.
Makefile:57: set di istruzioni per l'obiettivo "all" non riuscito
make: *** [all] Errore 2`

**Comment by auriga1** [comment]
__OK__, *sorry for this*!!!

It was my system:

`dnf install kernel-devel gcc`

and `make` warked.

Do I have something else to do after the `make install`?

**Comment by lwfinger** [comment]
Reboot.

**Comment by auriga1** [comment]
I've re-installed a fresh kernel version, re-done `make` and `make install`.
Now my wireless network adapter is not usable.

`lspci`

`00:00.0 Host bridge: Intel Corporation Atom Processor Z36xxx/Z37xxx Series SoC Transaction Register (rev 0e)
00:02.0 VGA compatible controller: Intel Corporation Atom Processor Z36xxx/Z37xxx Series Graphics & Display (rev 0e)
00:14.0 USB controller: Intel Corporation Atom Processor Z36xxx/Z37xxx Series USB xHCI (rev 0e)
00:1a.0 Encryption controller: Intel Corporation Atom Processor Z36xxx/Z37xxx Series Trusted Execution Engine (rev 0e)
00:1b.0 Audio device: Intel Corporation Atom Processor Z36xxx/Z37xxx Series High Definition Audio Controller (rev 0e)
00:1c.0 PCI bridge: Intel Corporation Atom Processor E3800 Series PCI Express Root Port 1 (rev 0e)
00:1c.1 PCI bridge: Intel Corporation Atom Processor E3800 Series PCI Express Root Port 2 (rev 0e)
00:1c.3 PCI bridge: Intel Corporation Atom Processor E3800 Series PCI Express Root Port 4 (rev 0e)
00:1f.0 ISA bridge: Intel Corporation Atom Processor Z36xxx/Z37xxx Series Power Control Unit (rev 0e)
00:1f.3 SMBus: Intel Corporation Atom Processor E3800 Series SMBus Controller (rev 0e)
02:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8723BE PCIe Wireless Network Adapter
03:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTS5229 PCI Express Card Reader (rev 01)`

Please, what can I do?
Actually I'm using an older kernel version, but I need to restart my network connection 6 or 7 times per day.

Thanks

**Comment by lwfinger** [comment]
For RTL8723BE, it helps to turn off power save when the module is loaded.

For the new kernel, what error messages do you get? Saying that it is "unusable" wastes my time.

**Comment by auriga1** [comment]
Here I am,
sorry for wasting your time, but I think that not all of us are as expert as you are.

"*Unusable*": my os can't use my wireless adapter, I can't choose a wireless connection because there is not the wireless icon.
I've tried these commands:

1) `lspci` is the same than before.

2)`iwlist scan | grep ESSID`

`no results`

3)`dmesg | grep 'rtl'`

`[   15.974485] Bluetooth: hci0: rtl: examining hci_ver=06 hci_rev=000b lmp_ver=06 lmp_subver=8723
[   15.974492] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723b_fw.bin`

I don't know what to do for give you more informations, but if you want to help I'm here.

Thank you in advance,
Silvio

**Comment by lwfinger** [comment]
You need to examine dmesg more carefully. If nothing shows up in a scan, then either you have blacklisted the kernel module, or the firmware is missing.

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
