### ISSUE TITLE
Error in modprobe rtl8192ee in 3.13.0-65 kernel Ubuntu14.04

### ISSUE THREAD

**Issue by DarkAngelZT** [lwfinger/rtlwifi_new#73]
After update to 3.13.0-65 kernel, when i try to insert module after compile finished.
I get error: 
sudo modprobe rtl8192ee
error: invalid module name rtl8192ee

ps: The driver works fine on the old kernel 3.13.0-63 and before.

**Comment by buddy102** [comment]
I built this couple of days back (3.10.92-1 kernel on centos6) I do see a rtl8192ee module built. So certainly not a case of module rename etc.

**Comment by lwfinger** [comment]
Look at the actual message in the output of the dmesg command.

**Comment by DarkAngelZT** [comment]
The problem has been solved at latest kernel 3.13.0-68
