### ISSUE TITLE
Wifi dropout with RTL8723BE on Dell 3552

### ISSUE THREAD

**Issue by mj-harvey** [lwfinger/rtlwifi_new#77]
Hi, 

I've a Dell 3552 Inspiron laptop with an RTL8723BE Wifi chip. The laptop ships with Ubuntu 14.04 LTS, which I've upgraded to Ubuntu 15.10.
Since the upgrade, I've noted spontaneous drop-outs of the wifi. I've tried all 8 combinations of the fwlps, ips and msi options without improvement. Turning on debugging with debug=5, I noticed that the failure was correlated with the appearance of "Trigger 8723be Thermal Meter!!" in the syslog.

Taking the current HEAD and short-circuiting the method rtl8723be_dm_check_txpower_tracking() so that it is a nop seems to have restored stability.

Not sure what to make of that - perhaps you've some insight into whats might be happening?

Matt

**Comment by lwfinger** [comment]
Thanks for the input. That appears to be valuable information. To complete your information, I would like to know which branch of the repo you are using. On multi-branched projects, that should always be reported.

Routine rtl8723be_dm_check_txpower_tracking() came from Realtek, and I have no understanding of how or what it is doing. I'll try to figure it out.

I am not an Ubuntu user, thus saying 14.04 or 15.10 tells me nothing other than the latter is newer. Please specify the kernel version that each is running. You appear to imply that the same version of this repo works better with the 14.04 kernel than it does with the 15.10 kernel. Is that so? If true, a bisection of the base kernels would be useful.

Have you tried the in-kernel version of the driver?

**Comment by mj-harvey** [comment]
The kernel is  4.2.0-19-generic #23-Ubuntu . I don't know how far this deviates from the vanilla 4.2.0, or what build configuration was used. I went straight from the driver in that kernel build to the HEAD of the master branch of this repo.

The 14.04 kernel is 3.19.0


I'm still seeing dropouts on the wifi connect, accompanied by the syslog message:

[  372.583020] wlp1s0: AP 6a:96:bf:6f:80:1c changed bandwidth, new config is 2412 MHz, width 1 (2412/0 MHz)

does that indicate anything useful?

**Comment by mj-harvey** [comment]
I'm not really in a position to do kernel bisection, though I could on rtlwireless_new if that's useful

**Comment by lwfinger** [comment]
That message is coming from mac80211 and indicates that your AP has suddenly switched the bandwidth to an impossible value. I have no idea why that is happening.

**Comment by lwfinger** [comment]
A later thought: Make certain that the AP has the latest firmware version.

**Comment by mj-harvey** [comment]
I switched the AP to a different, fixed channel and haven't had a drop.out
since. i expect my earlier correlation was a red-herring.

matt

On 14 December 2015 at 23:20, lwfinger <notifications@github.com> wrote:

> A later thought: Make certain that the AP has the latest firmware version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lwfinger/rtlwifi_new/issues/77#issuecomment-164578286>
> .
>



-- 
<https://www.acellera.com>


<https://twitter.com/acellera?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor>
    <https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/acellera>
<https://www.acellera.com/md-simulation-blog-news/>     [image:
skype:acellera] <http://is.gd/1eXkbS>

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
