### ISSUE TITLE
rtl8188ee constant association/authentication loop

### ISSUE THREAD

**Issue by Yomi0** [lwfinger/rtlwifi_new#8]
This is similar to the kernel bug that was created here : https://bugzilla.kernel.org/show_bug.cgi?id=78691

I'll add changed symptoms (if any) to a Gist.

This happens when I'm on campus. They've got Cisco routers placed all throughout campus.
In the logs below, (the dmesg.) it would appear the adapter is apparently receiving something from an AP that doesn't exist...(check the APs in the dmesg against the ones in the list of APs...) The lines that say 
`rtlwifi:rtl_action_proc:( )`

I've noticed that this doesn't occur at a certain library. (I'll call this library A.)
It happens at another library, with one router (I'll call this library B.) but I think they've got two different kinds of routers.

I've commented out Line 1704 in base.c as you suggested, @troy-tan. It didn't make a difference.
Here is the current configuration from systool -v -m rtl8188ee, along with debug output and a list of the APs I was around : https://gist.github.com/Yomi0/1da897124b41d33a15f0

Let me know if there's any more information you need, let me know.

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
