### ISSUE TITLE
Any way to select antenna?

### ISSUE THREAD

**Issue by jeremyb31** [lwfinger/rtlwifi_new#80]
Seems some manufactures are only using one antenna with a card that has two connectors, please see
http://ubuntuforums.org/showthread.php?t=2304607&p=13402744#post13402744

**Comment by StacoNiK** [comment]
Thanks

**Comment by modev32** [comment]
the owner of this git has mentioned a hint to start up with https://github.com/lwfinger/rtlwifi_new/issues/28#issuecomment-167862936
I wish if I could go for that but I have lack of knowledge and time. I wish someone could manage to solve this with the software way. Because as you have mentioned there is a hardware workaround for this ... but for me i can't go that far as it's just a 1 day old laptop :sweat_smile:

**Comment by modev32** [comment]
Hi guys. after looking around the driver's files i found something similar to what the developer mentioned before about `ant_set` in this comment https://github.com/lwfinger/rtlwifi_new/issues/28#issuecomment-167862936. 

so at this file https://github.com/lwfinger/rtlwifi_new/blob/master/rtl8723be/trx.h scroll to line 405 to 420 there you can see an if statement with same content (within if&else) but with different order .. I noticed something `ant_sel:1` I don't know if changing this to `ant_sel:2` in both statements and compiling it again could do the trick ? I wish a have 1% knowledge about this as i'm just a java developer. can someone confirm this ?

**Comment by lwfinger** [comment]
That absolutely will break everything, The :1 part there is setting up a field that is 1 bit wide. Changing that to a width of will absolutely not work.

Why change the code? Do the following:

sudo modprobe -rv rtl8723be
sudo modprobe -v rtl8723be ant_sel=1

Test the results. Then

sudo modprobe -rv rtl8723be
sudo modprobe -v rtl8723be ant_sel=2

Test again. Is one or the other better? If so then do the following:

su -
echo "options rtl8723be ant_sel=Y" > /etc/modprobe.d/50-rtl8723be.conf

where Y is 1 or 2 depending on which works better.

**Comment by modev32** [comment]
Good thing i have asked before trying to act smart :)
Seems to be the same issue with both 1 & 2. I start to think of the hardware way.
thanks anyway :+1:

**Comment by modev32** [comment]
Ok i went through the hard way.. Replacing the connector... It was very difficult (maybe for me) as i couldn't recognize the driver and it was very small hidden beside the board covered with a small sticker. Altho it has small numbers 1 and 2..it was connected in 1.. A very small tiny wire.. I managed to switch it to port 2 i will include a photo of how it looks in HP pavilion x360 13-s100nx..

Btw that fixed everything i installed Ubuntu 15.10 again ( fresh install ) it seems that Ubuntu recognize it perfectly.. No need to blacklist anything or to change any configurations or install any drivers it just worked directly like it worked on windows.. 

Here how it looks ( red dot is connector 1. Green is 2)
http://i.imgur.com/DBIkUwm.jpg

Happy to lose my warranty just the second day of the laptop age :)

**Comment by thetechnaddict** [comment]
Is the switch working? The one to select the antenna?
In a related issue (#28 lost TCP Packages) the thread indicates that it is not.

I'm experiencing this problem on a HP 15-ac116ns

Symptoms are slow, weak connection unless laptop is placed within a few centimeters of the router.

HP refuse to support (other than to re-install windows) - Love 'em - but still unwilling to invalidate warranty on first day of use.

Many thanks for your work  - as a first step we'll use the usb adaptor stolen from a raspberry pi, so the card will remain in place as it is should you need any tests / information from a live problem card.

**Comment by lwfinger** [comment]
The change is not working. It seems the code where it is needed is executed before the code that would allow it to be set. So far, no way around that dilemma. Perhaps you should report a defect to HP. The EEPROM bit that says which antenna to use should match the one on which the connector is placed.

**Comment by thetechnaddict** [comment]
Thanks for your rapid response. 

Sadly HP have chosen to be arses over this stating that running Linux invalidates warranty.

Interesting position to take!

Sent with Unibox

**Comment by jeremyb31** [comment]
The rock.new_btcoex branch fixes the issue, many thanks
