### ISSUE TITLE
rtl8723ae don't work at Ubuntu 14.04

### ISSUE THREAD

**Issue by hijera** [lwfinger/rtlwifi_new#81]
Hi, i'm using MSI S12 and compiled rtlwifi_new today from master.
when i'm trying to execute modprobe it says:
`modprobe: ERROR: could not insert 'rtl8723ae': Invalid argument`
dmesg:
`[ 3351.340006] rtl8723ae: disagrees about version of symbol rtl_btc_get_ops_pointer`
`[ 3351.340025] rtl8723ae: Unknown symbol rtl_btc_get_ops_pointer (err -22)`
My kernel is:
`Linux hj 3.13.0-73-generic #116-Ubuntu SMP Fri Dec 4 15:33:02 UTC 2015 i686 athlon i686 GNU/Linux`

**Comment by lwfinger** [comment]
Your kernel headers do not match the kernel you are running.

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
