### ISSUE TITLE
RTL8723BE unable to connect to wireless networks

### ISSUE THREAD

**Issue by alfbr** [lwfinger/rtlwifi_new#83]
Loading the driver with the option msi=1, I was able to scan wireless networks.  I am running the latest Debian stable, i.e., 8/Jessie. I am testing from the KDE desktop, so connection with plasma-nm version 0.9.3.4, which again uses networkmanager version 0.9.10.

I tried setting up wireless using iwconfig directly without success (disabling networkmanager). Also tried the Debian way setting up wireless in /etc/network/interfaces (any interfaces set-up there will be ignored by networkmanager). Neither resulted in a working connection.

I am running openwrt on the router, and set-up an unsecure interface to rule out any authentication issues, so no need for wep/wpa/wpa2.

I confirmed with a second laptop here with identical software set-up (a thinkpad with intel wireless running KDE spin of Debian 8) to ensure that all approaches resulted in working network connection.

This issue came out of #34

**Comment by lwfinger** [comment]
What signal strengths are you getting in the scan? It is possible that the detected networks are very weak. A number of vendors are only supplying a single antenna and the EEPROM does not contain the correct antenna info. At the moment, the code cannot overcome this problem.

**Comment by alfbr** [comment]
I dont't think so, I am connecting with a plethora of other devices without issues, this is the scan results:
          Cell 02 - Address: 4E:E6:76:F9:5F:AB
                    Channel:5
                    Frequency:2.432 GHz (Channel 5)
                    Quality=70/70  Signal level=-40 dBm  
                    Encryption key:off
                    ESSID:"guest"
                    Bit Rates:1 Mb/s; 2 Mb/s; 5.5 Mb/s; 11 Mb/s; 6 Mb/s
                              9 Mb/s; 12 Mb/s; 18 Mb/s
                    Bit Rates:24 Mb/s; 36 Mb/s; 48 Mb/s; 54 Mb/s
                    Mode:Master
                    Extra:tsf=0000002b26ae9600
                    Extra: Last beacon: 400ms ago
                    IE: Unknown: 00056775657374
                    IE: Unknown: 010882848B960C121824
                    IE: Unknown: 030105
                    IE: Unknown: 0706555320010B1B
                    IE: Unknown: 2A0104
                    IE: Unknown: 32043048606C
                    IE: Unknown: 2D1ACE111BFFFF000000000000000000000100000000000000000000
                    IE: Unknown: 3D1605070600000000000000000000000000000000000000
                    IE: Unknown: DD180050F2020101000003A4000027A4000042435E0062322F00

**Comment by alfbr** [comment]
The scan was done with the rtl8723be nic by the way.

**Comment by lwfinger** [comment]
I should hope that to be the case when we are trying to diagnose a connection problem.

Using NM, what is the dmesg output when trying to connect? I want to see the part after the firmware load message.

**Comment by alfbr** [comment]
Ah, finally success. It seems the module needs to be loaded with the msi=1 option at boot time. Adding the "options rtl8723be msi=1" in /etc/modprobe.d/ and rebooting gave successful connection. Using modprobe -r rtl8723be
modprobe rtl8723be msi=1
after boot made me unable to connect (regardless of user space tools used). Huge thanks for following me on this one. I will report back should the issue resurface. I am closing the issue, feel free to reopen if you want to further investigate.

For the record the output you requested when attempting unsuccessful connection is the following:
[  357.471228] Using firmware rtlwifi/rtl8723befw.bin
[  357.471464] rtl8723be 0000:02:00.0: firmware: direct-loading firmware rtlwifi/rtl8723befw.bin
[  357.473958] ieee80211 phy0: Selected rate control algorithm 'rtl_rc'
[  357.475158] rtlwifi: wireless switch is on
[  357.475593] rtl8723be 0000:02:00.0: irq 93 for MSI/MSI-X
[  357.914170] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[  368.039980] wlan0: authenticate with 4c:e6:76:f9:5f:aa
[  368.073071] wlan0: send auth to 4c:e6:76:f9:5f:aa (try 1/3)
[  368.788610] wlan0: send auth to 4c:e6:76:f9:5f:aa (try 2/3)
[  368.892921] wlan0: send auth to 4c:e6:76:f9:5f:aa (try 3/3)
[  368.897745] wlan0: authenticated
[  373.073844] wlan0: aborting authentication with 4c:e6:76:f9:5f:aa by local choice (Reason: 3=DEAUTH_LEAVING)
