### ISSUE TITLE
10ec:8176 rtl8192ce 200-3200+ms latency on 802.11n 2.4GHz network with no load

### ISSUE THREAD

**Issue by penalvch** [lwfinger/rtlwifi_new#84]
Still an issue with git pull of rtlwifi_new and linux-firmware from today.

More information:
https://bugzilla.kernel.org/show_bug.cgi?id=105471
http://www.spinics.net/lists/linux-wireless/msg136921.html
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1445840

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
