### ISSUE TITLE
RTL8723BE mainline vs rtlwifi_new. No BT scan results.

### ISSUE THREAD

**Issue by carlocaione** [lwfinger/rtlwifi_new#90]
Using the mainline driver for the RTL8723BE I have no scan results from BT when the WiFi is enabled. BT works just fine once the WiFi is disabled.

The problem is not present using the `rtlwifi_new` drivers.

While investigating this issue (and I'm not sure if this is the cause of the problem) I noticed that while the `rtlwifi_new` detects 1 single antenna (`btcoexist->board_info.btdm_ant_num == 1`) and uses `halbtc8723b1ant` for the `btcoexist` module, the mainline driver is only able to use the 2 antennas version `halbtc8723b2ant` even though it also reports 1 single antenna for the device. Could be this the cause of the problem?

I tried to use the whole `btcoexist` module of the `rtlwifi_new` branch with the mainline driver but the result doesn't change at all, BT scan results are not available when WiFi is enabled.

Any idea?

**Comment by carlocaione** [comment]
@lwfinger any idea?

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
