### ISSUE TITLE
Error: Operation not permitted when setting RTL8723ae as active driver

### ISSUE THREAD

**Issue by copperwire** [lwfinger/rtlwifi_new#92]
I'm sorry if this is just something obvious I've overlooked, but some checking around yielded no answers. 

When I try to set the new driver after unloading the previous one with 
    `sudo modprobe -rv rtl8723ae`
    `sudo modprobe -v rtl8723ae`

it yields the following error:

`install /bin/false 
modprobe: ERROR: ../libkmod/libkmod-module.c:959 command_do() Error running install command for rtlwifi
 modprobe: ERROR: could not insert 'rtl8723ae': Operation not permitted` 

[I've asked the same question on askubuntu, which includes some more details](http://askubuntu.com/questions/725191/problem-with-wireless-card-rtl8723ae-on-14-04)

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
