### ISSUE TITLE
Intermittent high latency and packet loss with a RTL8812AE in AP mode

### ISSUE THREAD

**Issue by lgeek** [lwfinger/rtlwifi_new#93]
Hi,

I'm trying to run an AP on the 5 GHz band on a D-Link DWA-582 card (which is RTL8812AE-based). I'm getting intermittent periods with high packet losses or very high latency (200 - 1500ms ping latency), which pretty much stop TCP from working.

For example (note average and maximum latency):

```
$ ping -f 192.168.0.1
[...]
50111 packets transmitted, 50058 received, 0% packet loss, time 98973ms
rtt min/avg/max/mdev = 0.716/20.855/1059.926/108.622 ms
```

The minimal hostapd configuration I'm using for testing is this:

```
interface=wlp3s0
bridge=br0
country_code=GB
hw_mode=a
channel=36
ieee80211n=1
ssid=test
```

There are no other networks on this channel. There's not much of a difference if I disable the 802.11n mode or if I enable ac mode.

 I've used a third machine to inspect the packets over the air while pinging the local IP of the AP from a client. The ICMP requests look fine. The replies, however, are pretty much always being retransmitted multiple times before being acknowledged by the client (if they get acknowledged). I also seem to be losing some packets on the monitor interface. If I use _iw dev X station dump_, I can ocasionally see one or both of the RX and TX rates for the client dropping to 6 Mbps. It seems to me like it might be a rate control issue. On a related note, the _signal_ and _signal avg_ fields are all over the place (and changing every time I run iw) when the client is active (I've seen everything from 101 dBm to -120 dBm for a client that's 1m away from the AP and not moving), while the signal levels shown for an idle client appear valid.

Looking at the code, I've actually stumbled upon a work-around. On line 1067 in rtl8821ae/trx.c starts a block of code which is not compiled:

```
#if 0
        if (ieee80211_is_data_qos(fc)) {
            SET_TX_DESC_USE_RATE(pdesc, 1);
            SET_TX_DESC_TX_RATE(pdesc, DESC_RATEVHT2SS_MCS9);
        /* SET_TX_DESC_RETRY_LIMIT_ENABLE(pdesc, 1); */
        /* SET_TX_DESC_DATA_RETRY_LIMIT(pdesc, 0x3f); */
        }
#endif
```

If I re-enable it (including the two lines commented out!), things look much better:

```
$ ping -f 192.168.0.1
[...]
12807 packets transmitted, 12805 received, 0% packet loss, time 27408ms
rtt min/avg/max/mdev = 1.073/4.113/126.990/14.425 ms
```

The maximum latency is still higher than I'd expect for an otherwise idle AP on an idle channel, but at least it seems usable. The peak throughput over TCP is the same as before (~11 MB/s), but there seem to be no long periods with no connectivity. I have an Atheros card to compare against, but I'm out of time for today. I also intend to inspect the packets over the air to see what changed.

In the meantime, I was wondering why this code was disabled, whether enabling it is likely to break other things and if anyone more familiar with the driver / device / 802.11 networks thinks they understand the exact cause of the issue and if they have any ideas for a proper fix.

Thanks

**Comment by lwfinger** [comment]
Your questions are "above my pay grade". I forwarded them to the Realtek engineer that is my contact. I will let you know what answers I get back.

**Comment by lgeek** [comment]
Thanks for forwarding this. It turns out that the first two lines are not required and if I understand thing correctly, are likely to break things (like working with clients which are not 802.11ac-capable) by sending QoS frames at VHT (802.11ac) rates. The next two lines seem to do the job:

    SET_TX_DESC_RETRY_LIMIT_ENABLE(pdesc, 1);
    SET_TX_DESC_DATA_RETRY_LIMIT(pdesc, 0x3f);

I've sniffed the data over the air again and I'm now seeing very few retransmitted packets. I have no idea whether this retry limit is a number of allowed retransmissions (in which case I have no idea how it would reduce the number of retransmissions I'm seeing), some sort of timeout or something else. Throughput seems to be comparable with the Atheros card in 802.11n mode with 20 and 40 MHz channels. I have not properly tested 802.11ac yet, I'll update this if I get around to it.

**Comment by lwfinger** [comment]
I have no idea what these two parameters control other than the suggestion from the names. The first one appears to be a one-bit enable for the retry limit. The second is a 6-bit field that seems as if it controls the number of retries. The code sets that to the max value, but the question is "what retries are controlled"? I have no description of the layout of the TX and RX descriptors other than what is contained in the macros in rtl8821ae/trx.h. The above are the only ones that mention TX retries.

You might try changing the second parameter from 0x3f to 0x0f. That should be enough retries.

**Comment by mcm** [comment]
I had a similar issue with my RTL8812AE in AP mode on 5GHz. It was working in N-mode, albeit slowly, but I was completely unable to get DHCP in AC. After uncommenting this code as suggested, I was able to connect in AC mode. I left it as is, did not need to change 0x3f to 0x0f.

Just providing additional feedback.

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
