### ISSUE TITLE
rtl8723be doesn't work with Fedora 23 64bits

### ISSUE THREAD

**Issue by draikhin** [lwfinger/rtlwifi_new#94]
Hi,
Just for report an issue with HP Stream Notebook 13-c100nf and Fedora 23 64bits
After install the driver rtlwifi_new and restart my laptop wifi doesn't work.

Bye

**Comment by lwfinger** [comment]
That is so little information about the problem that I will not make any further comments.

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
