### ISSUE TITLE
Ubuntu 4.2.0-25-generic unusable after time/waking

### ISSUE THREAD

**Issue by awanninger** [lwfinger/rtlwifi_new#95]
Hello, I have been using this driver  on Ubuntu 15.10 (Wily) for about a month now without issue. However, I recently installed an update to the Ubuntu Base that has also updated my kernel. 

`uname -oivr` returns:
`4.2.0-25-generic #30-Ubuntu SMP Mon Jan 18 12:31:50 UTC 2016 x86_64 GNU/Linux`

I believe that I am seeing 2 separate issues. The Wi-Fi connects, but after a short period of time the Wi-Fi appears much slower than when I first connected. The second issue is that the upon waking my computer from sleep, the Wi-Fi is still connected, although I can not connect to any websites and the connection must be reset to make the Wi-Fi usable again.

**Comment by lwfinger** [comment]
When you say you have been using "this" driver, what do you mean? Have you used the driver built into the kernel, or have you been using the version from this repo? If the latter, you need to reinstall every time your distro updates their kernel.

If you have been using the driver in the distro's kernel, you need to find out what Ubuntu changed. After all of my time that their kernel practices have wasted, I do not touch their kernels!

**Comment by awanninger** [comment]
Sorry, I meant to elaborate. I'm using the version from this repo and I do recompile and install it each time. I have tried this process with the kernel info listed above and the problem persists.

**Comment by awanninger** [comment]
PS, if anyone needs more info from me about my setup just let me know. I'm happy to provide additional details.

**Comment by snaunton** [comment]
awanninger, to fix this create and chmod +x /etc/pm/sleep.d/00_wireless_sleep:

#!/bin/sh
case "$1" in
  suspend|hibernate)
 	/sbin/rmmod rtl8821ae
  ;;
  resume|thaw)
	/sbin/rmmod rtl8821ae
	/sbin/modprobe rtl8821ae
  ;;
esac

exit 0

**Comment by awanninger** [comment]
Thanks! This is working well.

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
