### ISSUE TITLE
RTL8723BE: Connection unstable (rock.new_btcoex)

### ISSUE THREAD

**Issue by debian98** [lwfinger/rtlwifi_new#97]
First, sorry for my bad english, I'm from Germany.
I have compiled the driver from the rock.new_btcoex branch (newest version) on my Debian Jessie 64bit. The signal strength is good, but my internet connection is very unstable. I'm permanently connected to my Wifi network, but often I can't get into the internet, every ping gets lost or needs more than 1000ms to come back. I sometimes have to wait minutes to get an internet connection again. My /etc/modprobe.d/rtl8723be.conf:
`options rtl8723be ips=N fwlps=N swlps=N swenc=Y disable_watchdog=Y ant_sel=2 msi=1`
How can I fix this problem?

**Comment by CaptainChaos** [comment]
You should  leave more information here, like what's your Laptop Model, what happens with ant_sel=1 / ant_sel=0, what does lspci -v report on your wireless card, what does dmesg state while you have the issues, and finally, which network toolkit (like wicd, networkmanager, etc) do you use? You could also try to increase the debug level (debug=0..5 rtl8723be parm) and have a look what new messages you get. Are you sure the module is loaded correctly? Does modinfo rtl8723be output the correct parameter list?
Greetings from Germany ;)

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
