### ISSUE TITLE
Having trouble uninstalling

### ISSUE THREAD

**Issue by jdurdach** [lwfinger/rtlwifi_new#98]
(Novice Alert) I have a TP-Link wn822n and I ran the following code to install it to Ubuntu, as without the proper driver, the wifi adapter will not run for more than 5 minutes without stalling out.

Here's what I entered:
sudo add-apt-repository ppa:hanipouspilot/rtlwifi
sudo apt-get update
sudo apt-get install rtlwifi-new-dkms linux-firmware

After I ran this, the card won't even light-up.
cd rtlwifi_new and cd rtlwifi-new will not work when I try to uninstall it.  
Here's my file path:
/usr/src/rtlwifi-new-0.9~trusty

Someone please help!

**Comment by lwfinger** [comment]
As you are using Ubuntu repositories, you need to get help there. I have no knowledge of Ubuntu.
